import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'Original ACT Math practice questions covering Intermediate Algebra and Coordinate Geometry content, in the 4-option multiple-choice format used since the 2026 Enhanced ACT Math section.',
  url: 'https://www.act.org/content/act/en/products-and-services/the-act-educator/the-act-test/enhancements-k12/faqs.html',
  checkedOn: '15 August 2026',
};

export const ACT_MATH_INTERMEDIATE_ALGEBRA_AND_COORDINATE_GEOMETRY_1: Question[] = [
  { id: 'act-math-intermediate-algebra-and-coordinate-geometry-01-001', section: 'Intermediate Algebra and Coordinate Geometry', topic: 'Quadratic Equations', difficulty: 'medium', question: 'What are the solutions to x² − 5x + 6 = 0?', options: ['x = 2, 3', 'x = -2, -3', 'x = 1, 6', 'x = -1, -6'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'x² − 5x + 6 factors as (x − 2)(x − 3) = 0, so x = 2 or x = 3.', source },
  { id: 'act-math-intermediate-algebra-and-coordinate-geometry-01-002', section: 'Intermediate Algebra and Coordinate Geometry', topic: 'Systems of Equations', difficulty: 'medium', question: 'Solve the system: x + y = 10 and x − y = 2.', options: ['x = 5, y = 5', 'x = 6, y = 4', 'x = 7, y = 3', 'x = 8, y = 2'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Adding the two equations gives 2x = 12, so x = 6, and substituting gives y = 4.', source },
  { id: 'act-math-intermediate-algebra-and-coordinate-geometry-01-003', section: 'Intermediate Algebra and Coordinate Geometry', topic: 'Slope', difficulty: 'medium', question: 'What is the slope of the line passing through (2, 3) and (6, 11)?', options: ['1', '1.5', '2', '2.5'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Slope = (11 − 3) / (6 − 2) = 8 / 4 = 2.', source },
  { id: 'act-math-intermediate-algebra-and-coordinate-geometry-01-004', section: 'Intermediate Algebra and Coordinate Geometry', topic: 'Midpoint Formula', difficulty: 'easy', question: 'What is the midpoint of the segment connecting (−4, 2) and (6, −8)?', options: ['(1, 5)', '(2, -3)', '(-1, -3)', '(1, -3)'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Midpoint = ((−4 + 6)/2, (2 + −8)/2) = (1, −3).', source },
  { id: 'act-math-intermediate-algebra-and-coordinate-geometry-01-005', section: 'Intermediate Algebra and Coordinate Geometry', topic: 'Distance Formula', difficulty: 'easy', question: 'What is the distance between the points (0, 0) and (3, 4)?', options: ['5', '6', '7', '25'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Distance = √(3² + 4²) = √(9 + 16) = √25 = 5.', source },
  { id: 'act-math-intermediate-algebra-and-coordinate-geometry-01-006', section: 'Intermediate Algebra and Coordinate Geometry', topic: 'Inequalities', difficulty: 'easy', question: 'Solve: 2x + 3 > 11.', options: ['x > 3', 'x > 4', 'x > 5', 'x > 7'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: '2x > 8, so x > 4.', source },
  { id: 'act-math-intermediate-algebra-and-coordinate-geometry-01-007', section: 'Intermediate Algebra and Coordinate Geometry', topic: 'Functions', difficulty: 'medium', question: 'If f(x) = 2x² − 3, what is f(3)?', options: ['9', '12', '15', '18'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'f(3) = 2(9) − 3 = 18 − 3 = 15.', source },
  { id: 'act-math-intermediate-algebra-and-coordinate-geometry-01-008', section: 'Intermediate Algebra and Coordinate Geometry', topic: 'Equation of a Line', difficulty: 'medium', question: 'What is the equation of a line with slope 3 passing through (0, −2)?', options: ['y = 3x + 2', 'y = -3x - 2', 'y = 3x - 3', 'y = 3x - 2'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Using slope-intercept form y = mx + b with m = 3 and y-intercept b = −2 gives y = 3x − 2.', source },
];
