import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'Original ACT Science practice passage and questions in the Research Summaries style used in the 2026 Enhanced ACT Science section.',
  url: 'https://www.act.org/content/act/en/products-and-services/the-act-educator/the-act-test/enhancements-k12/faqs.html',
  checkedOn: '15 August 2026',
};

const PASSAGE = `Experiment 1: A chemist measured how quickly a tablet of a solid acid dissolved in water at different temperatures. Tablets were dropped into 100 mL of water, and the time to fully dissolve was recorded. At 10°C, dissolving took 180 seconds. At 20°C, it took 110 seconds. At 30°C, it took 70 seconds. At 40°C, it took 45 seconds.

Experiment 2: The same chemist repeated the procedure at a fixed temperature of 20°C but varied the tablet's surface area by crushing it into different-sized pieces before dropping it into the water. A whole tablet took 110 seconds to dissolve. A tablet broken into 2 pieces took 75 seconds. A tablet broken into 4 pieces took 50 seconds. A tablet crushed into a fine powder took 20 seconds.`;

const read = (q: string) => `Read the experiment summaries and answer the question that follows.\n\n${PASSAGE}\n\nQuestion: ${q}`;

export const ACT_SCIENCE_RESEARCH_SUMMARIES_1: Question[] = [
  { id: 'act-science-research-summaries-01-001', section: 'Research Summaries', topic: 'Data Reading', difficulty: 'easy', question: read('In Experiment 1, how long did the tablet take to dissolve at 30°C?'), options: ['70 seconds', '110 seconds', '45 seconds', '180 seconds'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Experiment 1 reports a dissolving time of 70 seconds at 30°C.', source },
  { id: 'act-science-research-summaries-01-002', section: 'Research Summaries', topic: 'Trend Analysis', difficulty: 'medium', question: read('According to Experiment 1, what is the relationship between water temperature and dissolving time?'), options: ['As temperature increases, dissolving time increases', 'As temperature increases, dissolving time decreases', 'Temperature has no effect on dissolving time', 'Dissolving time is fastest at the lowest temperature tested'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Dissolving time drops from 180 seconds at 10°C to 45 seconds at 40°C, showing that higher temperature means faster dissolving.', source },
  { id: 'act-science-research-summaries-01-003', section: 'Research Summaries', topic: 'Data Reading', difficulty: 'easy', question: read('In Experiment 2, how long did the tablet crushed into a fine powder take to dissolve?'), options: ['50 seconds', '75 seconds', '20 seconds', '110 seconds'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Experiment 2 reports that the powdered tablet took 20 seconds to dissolve.', source },
  { id: 'act-science-research-summaries-01-004', section: 'Research Summaries', topic: 'Trend Analysis', difficulty: 'medium', question: read('According to Experiment 2, what is the relationship between surface area and dissolving time?'), options: ['Increasing surface area increases dissolving time', 'Surface area has no effect on dissolving time', 'Dissolving time is unrelated to the number of pieces', 'Increasing surface area decreases dissolving time'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Dissolving time drops from 110 seconds (whole tablet) to 20 seconds (fine powder) as the tablet is broken into more, smaller pieces, increasing surface area.', source },
  { id: 'act-science-research-summaries-01-005', section: 'Research Summaries', topic: 'Experimental Design Comparison', difficulty: 'medium', question: read('What variable was held constant in Experiment 2 that was deliberately varied in Experiment 1?'), options: ['Temperature', 'The mass of the tablet', 'The volume of water', 'The type of acid used'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Experiment 2 fixed the temperature at 20°C, while Experiment 1 deliberately varied temperature across trials.', source },
  { id: 'act-science-research-summaries-01-006', section: 'Research Summaries', topic: 'Cross-Experiment Comparison', difficulty: 'medium', question: read('Comparing the whole-tablet trial in Experiment 2 to the 20°C trial in Experiment 1, what would you expect about their dissolving times?'), options: ['They should be dramatically different since different chemists ran them', 'They should be about the same, since both describe a whole tablet dissolving at 20°C', 'Experiment 2\'s trial should take twice as long', 'There is no way to compare the two experiments'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Both trials describe a whole tablet dissolving in 100 mL of water at 20°C, and both report 110 seconds, confirming they should match.', source },
  { id: 'act-science-research-summaries-01-007', section: 'Research Summaries', topic: 'Prediction', difficulty: 'hard', question: read('Based on the trend in Experiment 1, which of the following best predicts the dissolving time at 50°C?'), options: ['More than 180 seconds', 'Between 110 and 180 seconds', 'Less than 45 seconds', 'Exactly 45 seconds'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Since dissolving time keeps decreasing as temperature rises (180, 110, 70, 45 seconds), the value at 50°C should continue that trend and fall below 45 seconds.', source },
  { id: 'act-science-research-summaries-01-008', section: 'Research Summaries', topic: 'Prediction', difficulty: 'hard', question: read('Based on the trend in Experiment 2, which of the following best predicts the dissolving time if the tablet were broken into 8 pieces?'), options: ['More than 75 seconds', 'Between 50 and 75 seconds', 'Exactly 20 seconds', 'Less than 20 seconds'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Since dissolving time keeps decreasing as the tablet is broken into more pieces (110, 75, 50, 20 seconds), 8 pieces should continue that trend and dissolve in less than 20 seconds.', source },
  { id: 'act-science-research-summaries-01-009', section: 'Research Summaries', topic: 'Experimental Purpose', difficulty: 'medium', question: read('What is the most likely purpose of running Experiment 2 in addition to Experiment 1?'), options: ['To test whether surface area, not just temperature, affects dissolving time', 'To repeat Experiment 1 exactly with no changes', 'To disprove the results of Experiment 1', 'To measure the taste of the dissolved tablets'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Experiment 2 holds temperature constant and varies surface area instead, testing a second factor that might affect dissolving time.', source },
];
