import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'Original ACT Reading practice passage and questions in the Social Science style used in the 2026 Enhanced ACT Reading section.',
  url: 'https://www.act.org/content/act/en/products-and-services/the-act-educator/the-act-test/enhancements-k12/faqs.html',
  checkedOn: '15 August 2026',
};

const PASSAGE = `City planners have increasingly turned to congestion pricing, charging drivers a fee to enter designated zones during peak hours, as a tool for managing downtown traffic. The rationale draws on a simple economic principle: when a scarce resource, road space during rush hour, is provided free of charge, demand for it tends to exceed supply, producing the gridlock familiar to commuters in large cities. By attaching a price to that resource, planners aim to shift some trips to off-peak hours, encourage carpooling or transit use, and reduce the sheer volume of vehicles competing for the same limited streets. London introduced a congestion charge in 2003 and reported a meaningful drop in traffic entering the charging zone within its first years, alongside increased revenue that the city directed toward public transit improvements. Singapore's system, which predates London's by decades, adjusts prices dynamically based on measured traffic speeds, raising fees when roads grow congested and lowering them when they do not. Critics of congestion pricing argue that a flat fee falls disproportionately on lower-income drivers who have fewer flexible transportation alternatives, since wealthier drivers can more easily absorb the cost without changing their behavior. Some cities have responded by pairing congestion charges with expanded low-cost transit service or income-based fee reductions, attempting to preserve the traffic-reduction benefits of pricing while softening its unequal impact across income levels.`;

const read = (q: string) => `Read the passage and answer the question that follows.\n\n${PASSAGE}\n\nQuestion: ${q}`;

export const ACT_READING_SOCIAL_SCIENCE_1: Question[] = [
  { id: 'act-reading-social-science-01-001', section: 'Social Science', topic: 'Main Idea', difficulty: 'easy', question: read('Which choice best states the main point of the passage?'), options: ['Congestion pricing aims to reduce traffic by charging for road use, though it raises equity concerns', 'London and Singapore have identical congestion pricing systems', 'Public transit funding has decreased since congestion pricing began', 'Congestion pricing has eliminated traffic entirely in every city that has adopted it'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage explains the economic rationale for congestion pricing, gives London and Singapore as examples, and closes on the equity criticism, matching this summary.', source },
  { id: 'act-reading-social-science-01-002', section: 'Social Science', topic: 'Detail', difficulty: 'medium', question: read('According to the passage, what did London do with the revenue from its congestion charge?'), options: ['Returned it directly to drivers as a rebate', 'Directed it toward public transit improvements', 'Used it exclusively to build new roads', 'Donated it to neighboring cities'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage states London\'s increased revenue was directed "toward public transit improvements."', source },
  { id: 'act-reading-social-science-01-003', section: 'Social Science', topic: 'Detail', difficulty: 'medium', question: read('How does Singapore\'s congestion pricing system differ from London\'s, according to the passage?'), options: ['Singapore charges a single flat fee that never changes', 'Singapore has no congestion pricing system', 'Singapore adjusts prices dynamically based on measured traffic speeds', 'Singapore only charges fees on weekends'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage states Singapore\'s system "adjusts prices dynamically based on measured traffic speeds," unlike a flat charge.', source },
  { id: 'act-reading-social-science-01-004', section: 'Social Science', topic: 'Argument', difficulty: 'medium', question: read('What is the main criticism of congestion pricing mentioned in the passage?'), options: ['It generates too much revenue for cities to manage', 'It falls disproportionately on lower-income drivers with fewer alternatives', 'It has no effect on traffic volume at all', 'It is too complicated for drivers to understand'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage states critics argue "a flat fee falls disproportionately on lower-income drivers who have fewer flexible transportation alternatives."', source },
  { id: 'act-reading-social-science-01-005', section: 'Social Science', topic: 'Vocabulary in Context', difficulty: 'medium', question: read('As used in the passage, the word "disproportionately" most nearly means'), options: ['unequally', 'evenly', 'rarely', 'temporarily'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage uses "disproportionately" to describe a fee that affects lower-income drivers more than others, meaning unequally.', source },
];
