import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'Original ACT Reading practice passage and questions in the Literary Narrative style used in the 2026 Enhanced ACT Reading section.',
  url: 'https://www.act.org/content/act/en/products-and-services/the-act-educator/the-act-test/enhancements-k12/faqs.html',
  checkedOn: '15 August 2026',
};

const PASSAGE = `When Elena returned to her grandmother's house after twelve years away, she expected the porch swing to have rotted through, the garden to have gone to weeds, the whole place to feel like a stranger's memory rather than her own. Instead, the swing still creaked at the same pitch it always had, and someone, she realized only after a moment, had kept the tomato stakes upright in neat rows along the fence. She stood at the gate for a long time before she worked out who: her grandmother's neighbor, Mr. Alavi, who had lived next door since before Elena was born and whom she had exchanged perhaps a dozen words with in her entire childhood. When he came out to greet her, wiping his hands on a dish towel, he didn't mention the years she'd been gone or ask the questions she had braced herself for. He only said the peppers were coming in early this year and asked if she still hated cilantro the way she had at nine. She laughed before she meant to, surprised that he remembered, more surprised that the memory made her feel less like a visitor and more like someone the house, and the street, had simply been waiting on. That night, sitting on the still-creaking swing, she found herself making a mental list of everything that needed fixing: the gutters, a warped step, a window that stuck, tasks she hadn't planned on taking up but that now, oddly, felt less like a burden than an invitation.`;

const read = (q: string) => `Read the passage and answer the question that follows.\n\n${PASSAGE}\n\nQuestion: ${q}`;

export const ACT_READING_LITERARY_NARRATIVE_1: Question[] = [
  { id: 'act-reading-literary-narrative-01-001', section: 'Literary Narrative', topic: 'Main Idea', difficulty: 'easy', question: read('Which choice best states the main point of the passage?'), options: ['Elena unexpectedly feels a sense of belonging returning to a home she thought she had left behind', 'Elena is angry that Mr. Alavi maintained her grandmother\'s garden without asking', 'Mr. Alavi explains to Elena why he dislikes gardening', 'Elena decides to sell her grandmother\'s house immediately'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage traces Elena\'s surprise at the well-kept house, her exchange with Mr. Alavi, and her closing shift toward wanting to stay and fix things up, all pointing to an unexpected sense of belonging.', source },
  { id: 'act-reading-literary-narrative-01-002', section: 'Literary Narrative', topic: 'Detail', difficulty: 'easy', question: read('Who kept the tomato stakes upright in the garden while Elena was away?'), options: ['Elena\'s grandmother', 'Mr. Alavi, the neighbor', 'A hired gardener', 'No one; the garden had gone to weeds'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage states Elena realized "someone... had kept the tomato stakes upright" and identifies that person as her grandmother\'s neighbor, Mr. Alavi.', source },
  { id: 'act-reading-literary-narrative-01-003', section: 'Literary Narrative', topic: 'Inference', difficulty: 'medium', question: read('What can reasonably be inferred about Mr. Alavi\'s decision not to ask Elena about her twelve years away?'), options: ['He was too shy to speak with her at all', 'He had forgotten that she had been away', 'He chose to make her feel welcomed rather than put her on the spot', 'He disapproved of her absence and avoided the topic out of anger'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'By skipping the questions Elena "had braced herself for" and instead asking about peppers and cilantro, Mr. Alavi puts her at ease rather than interrogating her.', source },
  { id: 'act-reading-literary-narrative-01-004', section: 'Literary Narrative', topic: 'Character Development', difficulty: 'medium', question: read('How does Elena\'s attitude toward the house change over the course of the passage?'), options: ['She begins the passage feeling at home and ends feeling like an outsider', 'Her attitude does not change at all', 'She grows more anxious about the state of disrepair', 'She moves from feeling like a visitor to feeling invited to stay and repair the house'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Elena starts by expecting the house to feel like "a stranger\'s memory" and ends the passage making a list of repairs that feel "less like a burden than an invitation."', source },
  { id: 'act-reading-literary-narrative-01-005', section: 'Literary Narrative', topic: 'Vocabulary in Context', difficulty: 'medium', question: read('As it is used in the passage, the word "braced" most nearly means'), options: ['prepared', 'relaxed', 'celebrated', 'forgot'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Elena had "braced herself" for difficult questions, meaning she had mentally prepared for them.', source },
];
