import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'Original AFCAT practice questions in the official 4-option multiple-choice format, covering Verbal Ability in English, Numerical Ability and Reasoning and Military Aptitude from the Indian Air Force AFCAT syllabus. Second set, built to the same section proportions as the first.',
  url: 'https://afcat.cdac.in/AFCAT/',
  checkedOn: '17 September 2026',
};

export const AFCAT_VERBAL_NUMERICAL_AND_REASONING_2: Question[] = [
  // Verbal Ability
  { id: 'afcat-verbal-numerical-and-reasoning-02-001', section: 'Verbal Ability', topic: 'Error Spotting', difficulty: 'medium', question: 'Identify the part of the sentence that contains an error: "Each of the candidates (A) / have submitted (B) / their application form (C) / before the closing date (D)."', options: ['Part A', 'Part B', 'Part C', 'Part D'], correctIndex: 1, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: 'The subject is "each of the candidates", which is singular, so the verb must be "has submitted" rather than "have submitted".', source },
  { id: 'afcat-verbal-numerical-and-reasoning-02-002', section: 'Verbal Ability', topic: 'Sentence Improvement', difficulty: 'medium', question: 'Choose the best replacement for the underlined words: "The new squadron leader is senior <than me> by three years."', options: ['senior to me', 'senior than mine', 'more senior than me', 'No improvement is needed'], correctIndex: 0, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: 'Comparatives formed from Latin adjectives such as senior, junior, superior and inferior take "to", not "than".', source },
  { id: 'afcat-verbal-numerical-and-reasoning-02-003', section: 'Verbal Ability', topic: 'Active and Passive Voice', difficulty: 'medium', question: 'Change the sentence into the passive voice: "The selection board has approved the final list."', options: ['The final list has been approved by the selection board', 'The final list was approved by the selection board', 'The final list is being approved by the selection board', 'The final list had been approved by the selection board'], correctIndex: 0, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: 'The active verb is in the present perfect, so the passive must also be present perfect: has been approved.', source },
  { id: 'afcat-verbal-numerical-and-reasoning-02-004', section: 'Verbal Ability', topic: 'Direct and Indirect Speech', difficulty: 'hard', question: 'Choose the correct indirect form: He said, "I am flying to Delhi tomorrow."', options: ['He said that I am flying to Delhi tomorrow', 'He said that he is flying to Delhi the next day', 'He said that he will fly to Delhi tomorrow', 'He said that he was flying to Delhi the next day'], correctIndex: 3, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: 'The reporting verb is in the past, so the present continuous shifts to the past continuous and "tomorrow" becomes "the next day".', source },
  { id: 'afcat-verbal-numerical-and-reasoning-02-005', section: 'Verbal Ability', topic: 'Fill in the Blanks', difficulty: 'easy', question: 'Fill in the blank with the correct preposition: "The pilot was commended ___ his presence of mind during the emergency landing."', options: ['at', 'for', 'with', 'on'], correctIndex: 1, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: 'A person is commended for something done, so "for" is the preposition that fits.', source },
  { id: 'afcat-verbal-numerical-and-reasoning-02-006', section: 'Verbal Ability', topic: 'Articles', difficulty: 'easy', question: 'Fill in the blank with the correct article: "She has proved herself ___ honest and dependable officer."', options: ['a', 'the', 'No article is needed', 'an'], correctIndex: 3, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: 'The choice depends on sound rather than spelling, and "honest" opens with a vowel sound because the h is silent.', source },
  { id: 'afcat-verbal-numerical-and-reasoning-02-007', section: 'Verbal Ability', topic: 'Sentence Rearrangement', difficulty: 'hard', question: 'Arrange the parts to form a meaningful sentence: (P) before the aircraft is cleared (Q) every component of the engine (R) for takeoff (S) is inspected by the ground crew', options: ['Q S P R', 'P R Q S', 'Q P S R', 'S Q R P'], correctIndex: 0, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: 'The subject Q takes the verb phrase S, and the time clause P closes with its complement R, giving "Every component of the engine is inspected by the ground crew before the aircraft is cleared for takeoff."', source },
  { id: 'afcat-verbal-numerical-and-reasoning-02-008', section: 'Verbal Ability', topic: 'Phrasal Verbs', difficulty: 'medium', question: 'Choose the meaning of the phrasal verb in the sentence: "Poor visibility forced the squadron to call off the sortie."', options: ['To postpone to a fixed later hour', 'To carry out despite difficulty', 'To cancel', 'To hand over to another unit'], correctIndex: 2, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: 'To call something off is to cancel it, with no suggestion that it will be rescheduled.', source },
  // Numerical Ability
  { id: 'afcat-verbal-numerical-and-reasoning-02-009', section: 'Numerical Ability', topic: 'Average', difficulty: 'easy', question: 'The average of five numbers is 27. If one of the numbers, 35, is removed, what is the average of the remaining four?', options: ['24', '25', '26', '28'], correctIndex: 1, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: 'The five numbers total 5 times 27, which is 135. Removing 35 leaves 100 across four numbers, so the average is 25.', source },
  { id: 'afcat-verbal-numerical-and-reasoning-02-010', section: 'Numerical Ability', topic: 'Simple Interest', difficulty: 'easy', question: 'What is the simple interest on 12,000 rupees at 8 percent per annum for 3 years?', options: ['2,560 rupees', '2,780 rupees', '2,880 rupees', '3,120 rupees'], correctIndex: 2, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: 'Simple interest is principal times rate times time divided by 100, which is 12000 times 8 times 3 divided by 100, or 2,880 rupees.', source },
  { id: 'afcat-verbal-numerical-and-reasoning-02-011', section: 'Numerical Ability', topic: 'Time Speed and Distance', difficulty: 'medium', question: 'A train 180 metres long crosses a stationary pole in 12 seconds. What is its speed in kilometres per hour?', options: ['45', '48', '50', '54'], correctIndex: 3, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: 'Crossing a pole covers the length of the train, so the speed is 180 divided by 12, which is 15 metres per second, and 15 times 18 divided by 5 gives 54 kilometres per hour.', source },
  { id: 'afcat-verbal-numerical-and-reasoning-02-012', section: 'Numerical Ability', topic: 'Mixture and Alligation', difficulty: 'medium', question: 'In what ratio must rice costing 60 rupees per kg be mixed with rice costing 90 rupees per kg so that the mixture costs 70 rupees per kg?', options: ['2 to 1', '1 to 2', '3 to 2', '1 to 1'], correctIndex: 0, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: 'By alligation the ratio is the difference from the dearer price to the mean, 90 minus 70, against the difference from the mean to the cheaper price, 70 minus 60, which is 20 to 10, or 2 to 1.', source },
  { id: 'afcat-verbal-numerical-and-reasoning-02-013', section: 'Numerical Ability', topic: 'Partnership', difficulty: 'medium', question: 'A invests 40,000 rupees and B invests 60,000 rupees in a business for the same period. If the annual profit is 25,000 rupees, what is B\'s share?', options: ['10,000 rupees', '12,500 rupees', '14,000 rupees', '15,000 rupees'], correctIndex: 3, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: 'The capitals are in the ratio 40,000 to 60,000, that is 2 to 3, so B takes three fifths of 25,000 rupees, which is 15,000 rupees.', source },
  { id: 'afcat-verbal-numerical-and-reasoning-02-014', section: 'Numerical Ability', topic: 'Pipes and Cisterns', difficulty: 'medium', question: 'Pipe A can fill a tank in 12 hours and pipe B can fill the same tank in 18 hours. If both are opened together, how long will the tank take to fill?', options: ['6 hours', '7 hours 12 minutes', '7 hours 30 minutes', '8 hours'], correctIndex: 1, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: 'In one hour the pipes fill one twelfth plus one eighteenth, which is five thirty-sixths, so the tank fills in thirty-six fifths of an hour, that is 7 hours and 12 minutes.', source },
  { id: 'afcat-verbal-numerical-and-reasoning-02-015', section: 'Numerical Ability', topic: 'Square Roots', difficulty: 'easy', question: 'What is the value of the square root of 1764?', options: ['36', '38', '40', '42'], correctIndex: 3, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: 'Since 42 times 42 is 1764, the square root is 42.', source },
  { id: 'afcat-verbal-numerical-and-reasoning-02-016', section: 'Numerical Ability', topic: 'Problems on Ages', difficulty: 'hard', question: 'A father is at present three times as old as his son. Twelve years from now he will be twice as old as his son. What is the father\'s present age?', options: ['30 years', '33 years', '36 years', '42 years'], correctIndex: 2, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: 'If the son is x, the father is 3x, and 3x plus 12 equals twice x plus 12, which gives x equal to 12, so the father is 36.', source },
  // Reasoning and Military Aptitude
  { id: 'afcat-verbal-numerical-and-reasoning-02-017', section: 'Reasoning and Military Aptitude', topic: 'Alphabet Series', difficulty: 'easy', question: 'Find the term that comes next in the series: AZ, BY, CX, DW, ?', options: ['EV', 'EW', 'FV', 'DV'], correctIndex: 0, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: 'The first letter advances through the alphabet while the second moves backwards from Z, so after DW comes EV.', source },
  { id: 'afcat-verbal-numerical-and-reasoning-02-018', section: 'Reasoning and Military Aptitude', topic: 'Venn Diagram Relationships', difficulty: 'medium', question: 'Which statement best describes the relationship between the three groups: Vehicles, Cars, Buses?', options: ['Cars and Buses overlap, and both lie wholly outside Vehicles', 'Cars and Buses are separate groups, and both lie wholly inside Vehicles', 'Buses lie inside Cars, and Cars lie inside Vehicles', 'All three groups overlap one another partly'], correctIndex: 1, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: 'Every car and every bus is a vehicle, so both sit inside Vehicles, and no car is a bus, so the two do not overlap.', source },
  { id: 'afcat-verbal-numerical-and-reasoning-02-019', section: 'Reasoning and Military Aptitude', topic: 'Statement and Conclusion', difficulty: 'hard', question: 'Statement: All the transport aircraft in the squadron were serviced last month. Conclusions: I. No transport aircraft in the squadron is overdue for servicing. II. Some aircraft in the squadron are not transport aircraft. Which conclusion follows?', options: ['Only conclusion I follows', 'Only conclusion II follows', 'Both conclusions follow', 'Neither conclusion follows'], correctIndex: 0, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: 'Servicing every transport aircraft last month rules out any of them being overdue, while the statement says nothing about whether the squadron holds other kinds of aircraft.', source },
  { id: 'afcat-verbal-numerical-and-reasoning-02-020', section: 'Reasoning and Military Aptitude', topic: 'Seating Arrangement', difficulty: 'hard', question: 'Five officers A, B, C, D and E sit around a circular table facing the centre. B sits immediately to the right of A. C sits second to the left of A. E is not an immediate neighbour of A. Who sits immediately to the left of E?', options: ['A', 'B', 'C', 'D'], correctIndex: 1, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: 'Since everyone faces the centre, a seat to the left is the next one clockwise. B therefore takes the seat on A\'s immediate right and C the seat two places clockwise from A. E cannot sit beside A, so E takes the seat beyond C and D the one between A and C, which leaves B on E\'s immediate left.', source },
  { id: 'afcat-verbal-numerical-and-reasoning-02-021', section: 'Reasoning and Military Aptitude', topic: 'Number Analogy', difficulty: 'medium', question: 'Complete the analogy: 7 is to 56 as 9 is to ?', options: ['72', '81', '88', '90'], correctIndex: 3, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: 'Each number is multiplied by the number one greater than itself, so 7 gives 7 times 8, which is 56, and 9 gives 9 times 10, which is 90.', source },
  { id: 'afcat-verbal-numerical-and-reasoning-02-022', section: 'Reasoning and Military Aptitude', topic: 'Cubes and Dice', difficulty: 'medium', question: 'On a standard die the faces in each opposite pair add up to 7. If the face showing 2 is on top and the face showing 3 faces north, which number is on the bottom?', options: ['3', '4', '5', '6'], correctIndex: 2, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: 'The bottom face is opposite the top, and the pair must total 7, so the face opposite 2 shows 5.', source },
  { id: 'afcat-verbal-numerical-and-reasoning-02-023', section: 'Reasoning and Military Aptitude', topic: 'Missing Number', difficulty: 'medium', question: 'Each row of the grid follows the same rule. Row 1: 4, 6, 18. Row 2: 5, 8, 32. Row 3: 7, 9, ? What number replaces the question mark?', options: ['45', '48', '54', '56'], correctIndex: 2, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: 'In each row the third number is the product of the first two less the second, since 4 times 6 less 6 is 18 and 5 times 8 less 8 is 32, so 7 times 9 less 9 is 54.', source },
  { id: 'afcat-verbal-numerical-and-reasoning-02-024', section: 'Reasoning and Military Aptitude', topic: 'Data Sufficiency', difficulty: 'hard', question: 'Question: What is the age of the youngest of four cadets? Statement I: The four ages are consecutive whole numbers. Statement II: The four ages add up to 78. Which statements are needed to answer the question?', options: ['Statement I alone is sufficient', 'Statement II alone is sufficient', 'Both statements together are sufficient', 'Even both statements together are not sufficient'], correctIndex: 2, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: 'Consecutive ages summing to 78 give four times the youngest plus 6 equal to 78, so the youngest is 18; neither statement alone pins the ages down.', source },
];
