import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'Original Agniveer Vayu practice questions in the official 4-option multiple-choice format, covering English and Mathematics at the 10+2 CBSE level from the Indian Air Force Agniveer Vayu syllabus.',
  url: 'https://agnipathvayu.cdac.in/',
  checkedOn: '16 August 2026',
};

export const AGNIVEER_VAYU_ENGLISH_AND_MATHEMATICS_1: Question[] = [
  { id: 'agniveer-vayu-english-and-mathematics-01-001', section: 'English', topic: 'Synonyms', difficulty: 'easy', question: 'Choose the word closest in meaning to "Diligent".', options: ['Hardworking', 'Lazy', 'Careless', 'Timid'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: '"Diligent" means showing care and effort in one\'s work, closest to "Hardworking".', source },
  { id: 'agniveer-vayu-english-and-mathematics-01-002', section: 'English', topic: 'Antonyms', difficulty: 'easy', question: 'Choose the word opposite in meaning to "Benevolent".', options: ['Kind', 'Cruel', 'Generous', 'Benevolent'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: '"Benevolent" means kind and generous; its opposite is "Cruel".', source },
  { id: 'agniveer-vayu-english-and-mathematics-01-003', section: 'English', topic: 'Prepositions', difficulty: 'easy', question: 'Fill in the blank: He is capable ___ solving this problem.', options: ['in', 'at', 'of', 'for'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'The correct idiomatic preposition is "of": He is capable of solving this problem.', source },
  { id: 'agniveer-vayu-english-and-mathematics-01-004', section: 'English', topic: 'Spelling', difficulty: 'easy', question: 'Choose the correctly spelled word.', options: ['Neccessary', 'Necesary', 'Necessery', 'Necessary'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'The correct spelling is "Necessary", with a single "c" and double "s".', source },
  { id: 'agniveer-vayu-english-and-mathematics-01-005', section: 'English', topic: 'One-Word Substitution', difficulty: 'medium', question: 'Choose the word that means "a person who loves and collects books".', options: ['Bibliophile', 'Philanthropist', 'Linguist', 'Astronomer'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'A "Bibliophile" is a person who loves and collects books.', source },
  { id: 'agniveer-vayu-english-and-mathematics-01-006', section: 'English', topic: 'Tenses', difficulty: 'medium', question: 'Choose the grammatically correct sentence.', options: ['She have completed her homework already.', 'She has completed her homework already.', 'She had completed her homework already, isn\'t it?', 'She completing her homework already.'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'The subject "She" takes the singular present-perfect auxiliary "has": She has completed her homework already.', source },
  { id: 'agniveer-vayu-english-and-mathematics-01-007', section: 'English', topic: 'Articles', difficulty: 'easy', question: 'Fill in the blank: ___ Sun rises in the east.', options: ['A', 'An', 'The', 'No article'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Unique objects such as "the Sun" always take the definite article "The".', source },
  { id: 'agniveer-vayu-english-and-mathematics-01-008', section: 'English', topic: 'Idioms and Phrases', difficulty: 'medium', question: 'What does the idiom "to hit the nail on the head" mean?', options: ['To make a mistake', 'To waste time', 'To be indecisive', 'To describe exactly what is causing a situation or problem'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: '"To hit the nail on the head" means to identify or describe exactly what is causing a situation or problem.', source },
  { id: 'agniveer-vayu-english-and-mathematics-01-009', section: 'English', topic: 'Voice (Active-Passive)', difficulty: 'medium', question: 'Choose the correct passive voice of: "They are building a bridge."', options: ['A bridge is being built by them.', 'A bridge was being built by them.', 'A bridge has being built by them.', 'A bridge is build by them.'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Present continuous active becomes present continuous passive: A bridge is being built by them.', source },
  { id: 'agniveer-vayu-english-and-mathematics-01-010', section: 'English', topic: 'Error Detection', difficulty: 'medium', question: 'Identify the part of the sentence that contains an error: "Neither of the boys / have finished / their / work."', options: ['Neither of the boys', 'have finished', 'their', 'work'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: '"Neither of the boys" is a singular subject, so it should take the singular verb "has finished", not "have finished".', source },
  { id: 'agniveer-vayu-english-and-mathematics-01-011', section: 'English', topic: 'Vocabulary in Context', difficulty: 'easy', question: 'Choose the correct meaning of the word "Meticulous".', options: ['Careless', 'Hasty', 'Extremely careful and precise', 'Indifferent'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: '"Meticulous" means showing great attention to detail, or extremely careful and precise.', source },
  { id: 'agniveer-vayu-english-and-mathematics-01-012', section: 'English', topic: 'Conjunctions', difficulty: 'medium', question: 'Fill in the blank: ___ it rained heavily, the match continued.', options: ['Because', 'Since', 'Unless', 'Although'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: '"Although" correctly introduces a concessive clause contrasting the heavy rain with the match continuing.', source },
  { id: 'agniveer-vayu-english-and-mathematics-01-013', section: 'Mathematics', topic: 'Quadratic Equations', difficulty: 'medium', question: 'Find the roots of the equation x² − 7x + 12 = 0.', options: ['3 and 4', '2 and 5', '1 and 6', '3 and 5'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'x² − 7x + 12 = (x − 3)(x − 4) = 0, so the roots are 3 and 4.', source },
  { id: 'agniveer-vayu-english-and-mathematics-01-014', section: 'Mathematics', topic: 'Trigonometry', difficulty: 'easy', question: 'Find the value of sin 30° + cos 60°.', options: ['0.5', '1', '1.5', '2'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'sin 30° = 0.5 and cos 60° = 0.5, so their sum is 1.', source },
  { id: 'agniveer-vayu-english-and-mathematics-01-015', section: 'Mathematics', topic: 'Sets', difficulty: 'easy', question: 'If A = {1, 2, 3, 4} and B = {3, 4, 5, 6}, find A ∩ B.', options: ['{1, 2}', '{5, 6}', '{3, 4}', '{1, 2, 3, 4, 5, 6}'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'A ∩ B contains elements common to both sets, which are 3 and 4.', source },
  { id: 'agniveer-vayu-english-and-mathematics-01-016', section: 'Mathematics', topic: 'Permutations', difficulty: 'medium', question: 'In how many ways can the letters of the word "MATH" be arranged?', options: ['12', '16', '20', '24'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'All 4 letters of "MATH" are distinct, so they can be arranged in 4! = 24 ways.', source },
  { id: 'agniveer-vayu-english-and-mathematics-01-017', section: 'Mathematics', topic: 'Probability', difficulty: 'easy', question: 'A fair coin is tossed once. Find the probability of getting a head.', options: ['1/2', '1/3', '1/4', '1'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'A fair coin has 2 equally likely outcomes, so the probability of a head is 1/2.', source },
  { id: 'agniveer-vayu-english-and-mathematics-01-018', section: 'Mathematics', topic: 'Arithmetic Progression', difficulty: 'medium', question: 'Find the 10th term of the arithmetic progression 3, 7, 11, 15, ...', options: ['35', '39', '41', '43'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Here a = 3, d = 4. The 10th term = a + 9d = 3 + 9 × 4 = 39.', source },
  { id: 'agniveer-vayu-english-and-mathematics-01-019', section: 'Mathematics', topic: 'Coordinate Geometry', difficulty: 'easy', question: 'Find the distance between the points (0, 0) and (3, 4).', options: ['4', '4.5', '5', '6'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Distance = √(3² + 4²) = √(9 + 16) = √25 = 5.', source },
  { id: 'agniveer-vayu-english-and-mathematics-01-020', section: 'Mathematics', topic: 'Mensuration', difficulty: 'easy', question: 'Find the area of a circle of radius 7 cm. (Use π = 22/7)', options: ['144 cm²', '150 cm²', '152 cm²', '154 cm²'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Area = πr² = (22/7) × 7 × 7 = 154 cm².', source },
  { id: 'agniveer-vayu-english-and-mathematics-01-021', section: 'Mathematics', topic: 'Logarithms', difficulty: 'medium', question: 'Find the value of log₂ 8.', options: ['3', '4', '2', '8'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'log₂ 8 = log₂ 2³ = 3.', source },
  { id: 'agniveer-vayu-english-and-mathematics-01-022', section: 'Mathematics', topic: 'HCF and LCM', difficulty: 'easy', question: 'Find the LCM of 12 and 18.', options: ['24', '36', '48', '72'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: '12 = 2² × 3, 18 = 2 × 3². LCM = 2² × 3² = 36.', source },
  { id: 'agniveer-vayu-english-and-mathematics-01-023', section: 'Mathematics', topic: 'Matrices', difficulty: 'medium', question: 'If matrix A has order 2×3 and matrix B has order 3×4, find the order of the product AB.', options: ['3×3', '2×3', '2×4', '4×2'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'For matrix multiplication, the product of a 2×3 matrix and a 3×4 matrix has order 2×4.', source },
  { id: 'agniveer-vayu-english-and-mathematics-01-024', section: 'Mathematics', topic: 'Statistics', difficulty: 'easy', question: 'Find the mean of the numbers 2, 4, 6, 8, 10.', options: ['5', '5.5', '6.5', '6'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Mean = (2 + 4 + 6 + 8 + 10) / 5 = 30 / 5 = 6.', source },
  { id: 'agniveer-vayu-english-and-mathematics-01-025', section: 'Mathematics', topic: 'Geometry', difficulty: 'medium', question: 'Find the sum of the interior angles of a regular hexagon.', options: ['720°', '540°', '900°', '1080°'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Sum of interior angles = (n − 2) × 180° = (6 − 2) × 180° = 720°.', source },
  { id: 'agniveer-vayu-english-and-mathematics-01-026', section: 'Mathematics', topic: 'Calculus', difficulty: 'medium', question: 'Find the derivative of x³ with respect to x.', options: ['x²', '3x²', '3x³', 'x³'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Using the power rule, d/dx(x³) = 3x².', source },
  { id: 'agniveer-vayu-english-and-mathematics-01-027', section: 'Mathematics', topic: 'Algebraic Identities', difficulty: 'easy', question: 'Simplify: (a + b)² − (a − b)².', options: ['2ab', '4ab', 'a² + b²', '2(a² + b²)'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: '(a + b)² − (a − b)² = 4ab, since expanding both and subtracting cancels the a² and b² terms.', source },
];
