import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'Original Agniveer Vayu practice questions in the official 4-option multiple-choice format, covering English and Mathematics at the 10+2 CBSE level from the Indian Air Force Agniveer Vayu syllabus.',
  url: 'https://agnipathvayu.cdac.in/',
  checkedOn: '16 August 2026',
};

export const AGNIVEER_VAYU_ENGLISH_AND_MATHEMATICS_2: Question[] = [
  { id: 'agniveer-vayu-english-and-mathematics-02-001', section: 'English', topic: 'Synonyms', difficulty: 'easy', question: 'Choose the word closest in meaning to "Resilient".', options: ['Fragile', 'Hesitant', 'Hardy', 'Gloomy'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: '"Resilient" means able to recover quickly from difficulty, closest to "Hardy".', source },
  { id: 'agniveer-vayu-english-and-mathematics-02-002', section: 'English', topic: 'Antonyms', difficulty: 'easy', question: 'Choose the word opposite in meaning to "Transparent".', options: ['Opaque', 'Clear', 'Lucid', 'Glassy'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: '"Transparent" means allowing light through; its opposite is "Opaque". Clear, lucid and glassy all share the transparent sense.', source },
  { id: 'agniveer-vayu-english-and-mathematics-02-003', section: 'English', topic: 'Prepositions', difficulty: 'easy', question: 'Fill in the blank: The aircraft is flying ___ the clouds.', options: ['between', 'among', 'across', 'above'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: '"Above" expresses a position higher than the clouds without contact, which is the sense required here.', source },
  { id: 'agniveer-vayu-english-and-mathematics-02-004', section: 'English', topic: 'Spelling', difficulty: 'easy', question: 'Choose the correctly spelled word from the four options.', options: ['Millitary', 'Military', 'Militery', 'Milatary'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'The correct spelling is "Military", with a single "l" and the ending "-ary".', source },
  { id: 'agniveer-vayu-english-and-mathematics-02-005', section: 'English', topic: 'One-Word Substitution', difficulty: 'medium', question: 'Choose the word that means "a person who flies an aircraft".', options: ['Aviator', 'Mariner', 'Cartographer', 'Machinist'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'An "Aviator" is someone who pilots an aircraft. A mariner sails, a cartographer makes maps and a machinist works machine tools.', source },
  { id: 'agniveer-vayu-english-and-mathematics-02-006', section: 'English', topic: 'Tenses', difficulty: 'medium', question: 'Choose the sentence with the correct tense.', options: ['He has joined the academy last year.', 'He had joined the academy last year.', 'He joined the academy last year.', 'He is joining the academy last year.'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'A finished action at a stated past time takes the simple past. "Last year" cannot go with the present perfect.', source },
  { id: 'agniveer-vayu-english-and-mathematics-02-007', section: 'English', topic: 'Articles', difficulty: 'easy', question: 'Fill in the blank: She is ___ university student.', options: ['an', 'a', 'the', 'No article'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: '"University" begins with a consonant sound, "yoo", so it takes "a" rather than "an".', source },
  { id: 'agniveer-vayu-english-and-mathematics-02-008', section: 'English', topic: 'Idioms and Phrases', difficulty: 'medium', question: 'What does the idiom "to clip someone\'s wings" mean?', options: ['To encourage someone to try harder', 'To injure someone accidentally', 'To promote someone quickly', 'To restrict someone\'s freedom or power'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: '"To clip someone\'s wings" means to limit the freedom, power or ambition that person had.', source },
  { id: 'agniveer-vayu-english-and-mathematics-02-009', section: 'English', topic: 'Voice (Active-Passive)', difficulty: 'medium', question: 'Choose the correct passive voice of: "The technician repairs the radar."', options: ['The radar was repaired by the technician.', 'The radar has been repaired by the technician.', 'The radar repairs the technician.', 'The radar is repaired by the technician.'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Simple present active becomes simple present passive: The radar is repaired by the technician.', source },
  { id: 'agniveer-vayu-english-and-mathematics-02-010', section: 'English', topic: 'Error Detection', difficulty: 'medium', question: 'Identify the part of the sentence that contains an error: "One of the engines / were making / an unusual noise."', options: ['One of the engines', 'were making', 'an unusual noise', 'No error'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'The subject is "One", which is singular, so the verb should be "was making" rather than "were making".', source },
  { id: 'agniveer-vayu-english-and-mathematics-02-011', section: 'English', topic: 'Vocabulary in Context', difficulty: 'easy', question: 'Choose the correct meaning of the word "Altitude".', options: ['An attitude of mind', 'The speed of travel', 'Height above sea level', 'The direction of flight'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: '"Altitude" is vertical height, measured above sea level or above ground. "Attitude" is the similar-sounding word that means a settled way of thinking.', source },
  { id: 'agniveer-vayu-english-and-mathematics-02-012', section: 'English', topic: 'Conjunctions', difficulty: 'medium', question: 'Fill in the blank: The sortie will not begin ___ the weather clears.', options: ['until', 'although', 'because', 'whereas'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: '"Until" marks the point up to which the sortie is held, which is the meaning required here.', source },
  { id: 'agniveer-vayu-english-and-mathematics-02-013', section: 'Mathematics', topic: 'Quadratic Equations', difficulty: 'medium', question: 'Find the roots of the equation x² − 9x + 20 = 0.', options: ['2 and 10', '4 and 5', '−4 and −5', '1 and 20'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'x² − 9x + 20 = (x − 4)(x − 5) = 0, so the roots are 4 and 5.', source },
  { id: 'agniveer-vayu-english-and-mathematics-02-014', section: 'Mathematics', topic: 'Trigonometry', difficulty: 'easy', question: 'Find the value of tan 45° + cot 45°.', options: ['0', '1', '1/2', '2'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'tan 45° = 1 and cot 45° = 1, so their sum is 2.', source },
  { id: 'agniveer-vayu-english-and-mathematics-02-015', section: 'Mathematics', topic: 'Sets', difficulty: 'easy', question: 'If A = {2, 4, 6, 8} and B = {4, 8, 12}, find A ∪ B.', options: ['{2, 4, 6, 8, 12}', '{4, 8}', '{2, 6, 12}', '{2, 4, 6, 8}'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'The union contains every element of either set, listed once: {2, 4, 6, 8, 12}. The set {4, 8} is the intersection.', source },
  { id: 'agniveer-vayu-english-and-mathematics-02-016', section: 'Mathematics', topic: 'Permutations', difficulty: 'medium', question: 'In how many ways can the letters of the word "PLANE" be arranged?', options: ['24', '60', '120', '720'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'All 5 letters of "PLANE" are distinct, so they can be arranged in 5! = 120 ways.', source },
  { id: 'agniveer-vayu-english-and-mathematics-02-017', section: 'Mathematics', topic: 'Probability', difficulty: 'easy', question: 'A fair six-sided die is rolled once. Find the probability of getting a number greater than 4.', options: ['1/6', '1/2', '1/3', '2/3'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Only 5 and 6 exceed 4, so the probability is 2/6 = 1/3.', source },
  { id: 'agniveer-vayu-english-and-mathematics-02-018', section: 'Mathematics', topic: 'Arithmetic Progression', difficulty: 'medium', question: 'Find the 12th term of the arithmetic progression 5, 9, 13, 17, ...', options: ['49', '45', '53', '48'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Here a = 5 and d = 4, so the 12th term = a + 11d = 5 + 44 = 49.', source },
  { id: 'agniveer-vayu-english-and-mathematics-02-019', section: 'Mathematics', topic: 'Coordinate Geometry', difficulty: 'easy', question: 'Find the distance between the points (1, 2) and (4, 6).', options: ['4', '5', '6', '7'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Distance = √((4 − 1)² + (6 − 2)²) = √(9 + 16) = √25 = 5.', source },
  { id: 'agniveer-vayu-english-and-mathematics-02-020', section: 'Mathematics', topic: 'Mensuration', difficulty: 'easy', question: 'Find the circumference of a circle of radius 14 cm. (Use π = 22/7)', options: ['44 cm', '154 cm', '616 cm', '88 cm'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Circumference = 2πr = 2 × (22/7) × 14 = 88 cm. The value 616 cm² is the area, not the circumference.', source },
  { id: 'agniveer-vayu-english-and-mathematics-02-021', section: 'Mathematics', topic: 'Logarithms', difficulty: 'medium', question: 'Find the value of log₃ 81.', options: ['4', '3', '27', '9'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: '81 = 3⁴, so log₃ 81 = 4.', source },
  { id: 'agniveer-vayu-english-and-mathematics-02-022', section: 'Mathematics', topic: 'HCF and LCM', difficulty: 'easy', question: 'Find the HCF of 24 and 36.', options: ['4', '6', '12', '72'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: '24 = 2³ × 3 and 36 = 2² × 3², so the HCF is 2² × 3 = 12. The value 72 is their LCM.', source },
  { id: 'agniveer-vayu-english-and-mathematics-02-023', section: 'Mathematics', topic: 'Matrices', difficulty: 'medium', question: 'If matrix A has order 3×2 and matrix B has order 2×5, find the order of the product AB.', options: ['2×2', '5×3', '3×2', '3×5'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'The product takes the row count of A and the column count of B, giving order 3×5.', source },
  { id: 'agniveer-vayu-english-and-mathematics-02-024', section: 'Mathematics', topic: 'Statistics', difficulty: 'easy', question: 'Find the median of the numbers 3, 7, 9, 11, 15.', options: ['7', '9', '11', '45'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'The values are already in order and there are five of them, so the median is the third value, 9.', source },
  { id: 'agniveer-vayu-english-and-mathematics-02-025', section: 'Mathematics', topic: 'Geometry', difficulty: 'medium', question: 'Find the measure of each interior angle of a regular pentagon.', options: ['108°', '120°', '72°', '540°'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'The interior angles of a pentagon sum to (5 − 2) × 180° = 540°, so each of the five equal angles is 540° / 5 = 108°.', source },
  { id: 'agniveer-vayu-english-and-mathematics-02-026', section: 'Mathematics', topic: 'Calculus', difficulty: 'medium', question: 'Find the derivative of 5x² with respect to x.', options: ['5x', '2x', '10x', '10'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'By the power rule, d(5x²)/dx = 5 × 2x = 10x.', source },
  { id: 'agniveer-vayu-english-and-mathematics-02-027', section: 'Mathematics', topic: 'Algebraic Identities', difficulty: 'easy', question: 'Simplify: (a + b)² − 2ab.', options: ['a² − b²', 'a² + b²', '2a² + 2b²', 'a² + 3b²'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: '(a + b)² = a² + 2ab + b², so subtracting 2ab leaves a² + b².', source },
];
