import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference:
    'Original TakeMockTest practice questions covering standard Class 11/12 Mathematics, Physics, and Chemistry topics matching the AP EAPCET syllabus, corroborated across multiple independent secondary sources since the official cets.apsche.ap.gov.in domain could not be independently accessed. See this exam\'s review-pending pattern disclosure for the exact scope and confidence level.',
  url: 'https://cets.apsche.ap.gov.in/',
  checkedOn: '21 August 2026',
};

export const AP_EAPCET_ENGINEERING_FULL_MOCK_1: Question[] = [
  {
    id: 'ap-eapcet-mathematics-001',
    section: 'Mathematics',
    topic: 'Quadratic Equations',
    difficulty: 'easy',
    question: 'What are the roots of the equation x^2 - 5x + 6 = 0?',
    options: ['-2 and -3', '2 and 3', '1 and 6', '2 and 4'],
    correctIndex: 1,
    marks: 1,
    negativeMarking: 0,
    explanation: 'Factoring gives (x-2)(x-3)=0, so x=2 or x=3.',
    source,
  },
  {
    id: 'ap-eapcet-mathematics-002',
    section: 'Mathematics',
    topic: 'Complex Numbers',
    difficulty: 'easy',
    question: 'What is the value of (1+i)^2, where i = sqrt(-1)?',
    options: ['2i', '2', '-2i', '1+2i-1'],
    correctIndex: 0,
    marks: 1,
    negativeMarking: 0,
    explanation: '(1+i)^2 = 1 + 2i + i^2 = 1 + 2i - 1 = 2i.',
    source,
  },
  {
    id: 'ap-eapcet-mathematics-003',
    section: 'Mathematics',
    topic: 'Permutations and Combinations',
    difficulty: 'medium',
    question: 'In how many ways can 4 distinct books be arranged in a row on a shelf?',
    options: ['20', '12', '24', '16'],
    correctIndex: 2,
    marks: 1,
    negativeMarking: 0,
    explanation: 'The number of arrangements of 4 distinct items is 4! = 24.',
    source,
  },
  {
    id: 'ap-eapcet-mathematics-004',
    section: 'Mathematics',
    topic: 'Binomial Theorem',
    difficulty: 'medium',
    question: 'What is the coefficient of x^2 in the expansion of (1+x)^6?',
    options: ['20', '15', '6', '30'],
    correctIndex: 1,
    marks: 1,
    negativeMarking: 0,
    explanation: 'The coefficient of x^2 is C(6,2) = 15.',
    source,
  },
  {
    id: 'ap-eapcet-mathematics-005',
    section: 'Mathematics',
    topic: 'Sequences and Series',
    difficulty: 'easy',
    question: 'What is the sum of the first 15 odd natural numbers?',
    options: ['210', '240', '225', '200'],
    correctIndex: 2,
    marks: 1,
    negativeMarking: 0,
    explanation: 'The sum of the first n odd numbers is n^2. Here n=15, so the sum is 15^2=225.',
    source,
  },
  {
    id: 'ap-eapcet-mathematics-006',
    section: 'Mathematics',
    topic: 'Matrices',
    difficulty: 'medium',
    question: 'What is the determinant of the matrix [[3,1],[2,4]]?',
    options: ['12', '14', '10', '8'],
    correctIndex: 2,
    marks: 1,
    negativeMarking: 0,
    explanation: 'Determinant = (3)(4) - (1)(2) = 12 - 2 = 10.',
    source,
  },
  {
    id: 'ap-eapcet-mathematics-007',
    section: 'Mathematics',
    topic: 'Straight Lines',
    difficulty: 'medium',
    question: 'What is the perpendicular distance of the origin from the line 3x + 4y - 10 = 0?',
    options: ['2', '10', '2.5', '5'],
    correctIndex: 0,
    marks: 1,
    negativeMarking: 0,
    explanation: 'Distance = |3(0)+4(0)-10| / sqrt(3^2+4^2) = 10/5 = 2.',
    source,
  },
  {
    id: 'ap-eapcet-mathematics-008',
    section: 'Mathematics',
    topic: 'Circles',
    difficulty: 'medium',
    question: 'Does the point (3,4) lie on, inside, or outside the circle x^2 + y^2 = 25?',
    options: ['At the center', 'On the circle', 'Inside the circle', 'Outside the circle'],
    correctIndex: 1,
    marks: 1,
    negativeMarking: 0,
    explanation: '3^2+4^2 = 9+16 = 25, which equals the right-hand side, so the point lies exactly on the circle.',
    source,
  },
  {
    id: 'ap-eapcet-mathematics-009',
    section: 'Mathematics',
    topic: 'Ellipse',
    difficulty: 'hard',
    question: 'What is the eccentricity of the ellipse x^2/16 + y^2/9 = 1?',
    options: ['sqrt(7)/3', '3/4', 'sqrt(7)/4', '4/3'],
    correctIndex: 2,
    marks: 1,
    negativeMarking: 0,
    explanation: 'Here a=4, b=3, so c = sqrt(a^2-b^2) = sqrt(16-9) = sqrt(7). Eccentricity e = c/a = sqrt(7)/4.',
    source,
  },
  {
    id: 'ap-eapcet-mathematics-010',
    section: 'Mathematics',
    topic: 'Limits',
    difficulty: 'medium',
    question: 'What is lim(x->0) (1 - cos x)/x^2?',
    options: ['0', '2', '1/2', '1'],
    correctIndex: 2,
    marks: 1,
    negativeMarking: 0,
    explanation: 'Using the standard limit (1-cos x)/x^2 -> 1/2 as x approaches 0.',
    source,
  },
  {
    id: 'ap-eapcet-mathematics-011',
    section: 'Mathematics',
    topic: 'Differentiation',
    difficulty: 'easy',
    question: 'If f(x) = ln(x), what is f\'(2)?',
    options: ['ln(2)', '2', '1', '1/2'],
    correctIndex: 3,
    marks: 1,
    negativeMarking: 0,
    explanation: 'f\'(x) = 1/x. At x=2, f\'(2) = 1/2.',
    source,
  },
  {
    id: 'ap-eapcet-mathematics-012',
    section: 'Mathematics',
    topic: 'Applications of Derivatives',
    difficulty: 'medium',
    question: 'What is the maximum value of f(x) = 4x - x^2?',
    options: ['0', '4', '2', '8'],
    correctIndex: 1,
    marks: 1,
    negativeMarking: 0,
    explanation: 'f\'(x) = 4 - 2x = 0 gives x=2. Since f\'\'(x)=-2<0, this is a maximum. f(2) = 8-4 = 4.',
    source,
  },
  {
    id: 'ap-eapcet-mathematics-013',
    section: 'Mathematics',
    topic: 'Definite Integration',
    difficulty: 'medium',
    question: 'What is the value of the definite integral of (2x + 1) dx from 1 to 3?',
    options: ['8', '6', '12', '10'],
    correctIndex: 3,
    marks: 1,
    negativeMarking: 0,
    explanation: 'The antiderivative is x^2+x. Evaluating from 1 to 3 gives (9+3)-(1+1) = 12-2 = 10.',
    source,
  },
  {
    id: 'ap-eapcet-mathematics-014',
    section: 'Mathematics',
    topic: 'Indefinite Integration',
    difficulty: 'easy',
    question: 'What is the indefinite integral of cos(x) dx?',
    options: ['sin(x) + C', 'cos(x) + C', '-cos(x) + C', '-sin(x) + C'],
    correctIndex: 0,
    marks: 1,
    negativeMarking: 0,
    explanation: 'The derivative of sin(x) is cos(x), so the integral is sin(x) + C.',
    source,
  },
  {
    id: 'ap-eapcet-mathematics-015',
    section: 'Mathematics',
    topic: 'Differential Equations',
    difficulty: 'hard',
    question: 'If dy/dx = 3x^2 and y = 2 when x = 1, what is y when x = 2?',
    options: ['10', '9', '8', '7'],
    correctIndex: 1,
    marks: 1,
    negativeMarking: 0,
    explanation: 'Integrating gives y = x^3 + C. Using y(1)=2 gives 1+C=2, so C=1 and y=x^3+1. At x=2, y=8+1=9.',
    source,
  },
  {
    id: 'ap-eapcet-mathematics-016',
    section: 'Mathematics',
    topic: 'Vectors',
    difficulty: 'medium',
    question: 'If a = (1,1,0) and b = (0,1,1), what is the dot product a.b?',
    options: ['1', '2', '-1', '0'],
    correctIndex: 0,
    marks: 1,
    negativeMarking: 0,
    explanation: 'a.b = (1)(0)+(1)(1)+(0)(1) = 0+1+0 = 1.',
    source,
  },
  {
    id: 'ap-eapcet-mathematics-017',
    section: 'Mathematics',
    topic: 'Three Dimensional Geometry',
    difficulty: 'medium',
    question: 'What is the distance between the points (1,2,2) and (4,6,2)?',
    options: ['7', '4', '5', '6'],
    correctIndex: 2,
    marks: 1,
    negativeMarking: 0,
    explanation: 'Distance = sqrt((4-1)^2+(6-2)^2+(2-2)^2) = sqrt(9+16+0) = sqrt(25) = 5.',
    source,
  },
  {
    id: 'ap-eapcet-mathematics-018',
    section: 'Mathematics',
    topic: 'Probability',
    difficulty: 'easy',
    question: 'A card is drawn at random from a standard deck of 52 playing cards. What is the probability that it is a king?',
    options: ['1/26', '4/13', '1/4', '1/13'],
    correctIndex: 3,
    marks: 1,
    negativeMarking: 0,
    explanation: 'There are 4 kings in a deck of 52 cards, so the probability is 4/52 = 1/13.',
    source,
  },
  {
    id: 'ap-eapcet-mathematics-019',
    section: 'Mathematics',
    topic: 'Trigonometric Identities',
    difficulty: 'medium',
    question: 'If A is an acute angle with tan(A) = 3/4, what is sin(A)?',
    options: ['5/3', '4/5', '3/4', '3/5'],
    correctIndex: 3,
    marks: 1,
    negativeMarking: 0,
    explanation: 'Using a 3-4-5 right triangle where the opposite side is 3 and the adjacent side is 4, the hypotenuse is 5, so sin(A)=3/5.',
    source,
  },
  {
    id: 'ap-eapcet-mathematics-020',
    section: 'Mathematics',
    topic: 'Sets Relations and Functions',
    difficulty: 'easy',
    question: 'How many subsets does a set with 4 elements have, including the empty set and the set itself?',
    options: ['16', '12', '8', '4'],
    correctIndex: 0,
    marks: 1,
    negativeMarking: 0,
    explanation: 'A set with n elements has 2^n subsets. Here n=4, so there are 2^4=16 subsets.',
    source,
  },
  {
    id: 'ap-eapcet-physics-001',
    section: 'Physics',
    topic: 'Kinematics',
    difficulty: 'easy',
    question: 'A body has an initial velocity of 5 m/s and accelerates at 3 m/s^2 for 4 seconds. What is its final velocity?',
    options: ['12 m/s', '20 m/s', '15 m/s', '17 m/s'],
    correctIndex: 3,
    marks: 1,
    negativeMarking: 0,
    explanation: 'v = u + at = 5 + 3*4 = 17 m/s.',
    source,
  },
  {
    id: 'ap-eapcet-physics-002',
    section: 'Physics',
    topic: 'Laws of Motion',
    difficulty: 'medium',
    question: 'A 2 kg block and a 3 kg block are connected by a string on a frictionless surface. A horizontal force of 10 N is applied to the 3 kg block, pulling both. What is the acceleration of the system?',
    options: ['10 m/s^2', '2 m/s^2', '5 m/s^2', '3.33 m/s^2'],
    correctIndex: 1,
    marks: 1,
    negativeMarking: 0,
    explanation: 'For the connected system, a = F/(m1+m2) = 10/(2+3) = 2 m/s^2.',
    source,
  },
  {
    id: 'ap-eapcet-physics-003',
    section: 'Physics',
    topic: 'Work Energy Power',
    difficulty: 'medium',
    question: 'How much work is done in lifting a 5 kg mass through a height of 2 m? (Take g = 10 m/s^2)',
    options: ['100 J', '50 J', '10 J', '20 J'],
    correctIndex: 0,
    marks: 1,
    negativeMarking: 0,
    explanation: 'Work done against gravity = mgh = 5*10*2 = 100 J.',
    source,
  },
  {
    id: 'ap-eapcet-physics-004',
    section: 'Physics',
    topic: 'Gravitation',
    difficulty: 'hard',
    question: 'The orbital speed of a satellite is v at radius r. What is its orbital speed at radius 4r, in terms of v?',
    options: ['v/2', 'v', '2v', 'v/4'],
    correctIndex: 0,
    marks: 1,
    negativeMarking: 0,
    explanation: 'Orbital speed v is proportional to 1/sqrt(r). At radius 4r, the speed becomes v/sqrt(4) = v/2.',
    source,
  },
  {
    id: 'ap-eapcet-physics-005',
    section: 'Physics',
    topic: 'Thermodynamics',
    difficulty: 'easy',
    question: 'For an ideal gas undergoing an isothermal process, what is the change in internal energy?',
    options: ['Zero', 'Negative', 'Cannot be determined', 'Positive'],
    correctIndex: 0,
    marks: 1,
    negativeMarking: 0,
    explanation: 'The internal energy of an ideal gas depends only on temperature. Since temperature is constant in an isothermal process, the change in internal energy is zero.',
    source,
  },
  {
    id: 'ap-eapcet-physics-006',
    section: 'Physics',
    topic: 'Waves',
    difficulty: 'medium',
    question: 'A wave has a frequency of 500 Hz and a wavelength of 0.68 m. What is its speed?',
    options: ['170 m/s', '340 m/s', '680 m/s', '500 m/s'],
    correctIndex: 1,
    marks: 1,
    negativeMarking: 0,
    explanation: 'Wave speed = frequency * wavelength = 500 * 0.68 = 340 m/s.',
    source,
  },
  {
    id: 'ap-eapcet-physics-007',
    section: 'Physics',
    topic: 'Electrostatics',
    difficulty: 'medium',
    question: 'Two point charges of 2 microcoulombs and 3 microcoulombs are placed 0.3 m apart. What is the force between them? (Take k = 9 x 10^9 N m^2/C^2)',
    options: ['0.6 N', '6 N', '0.006 N', '0.06 N'],
    correctIndex: 0,
    marks: 1,
    negativeMarking: 0,
    explanation: 'F = kq1q2/r^2 = (9x10^9)(2x10^-6)(3x10^-6)/(0.3)^2 = 0.054/0.09 = 0.6 N.',
    source,
  },
  {
    id: 'ap-eapcet-physics-008',
    section: 'Physics',
    topic: 'Current Electricity',
    difficulty: 'easy',
    question: 'Three resistors of 2 ohm, 3 ohm, and 5 ohm are connected in series. What is the total resistance?',
    options: ['10 ohm', '6.67 ohm', '0.97 ohm', '30 ohm'],
    correctIndex: 0,
    marks: 1,
    negativeMarking: 0,
    explanation: 'In series, resistances add directly: 2+3+5 = 10 ohm.',
    source,
  },
  {
    id: 'ap-eapcet-physics-009',
    section: 'Physics',
    topic: 'Atoms and Nuclei',
    difficulty: 'hard',
    question: 'A radioactive substance has a half-life of 10 days. What fraction of the original sample remains after 30 days?',
    options: ['1/16', '1/6', '1/8', '1/3'],
    correctIndex: 2,
    marks: 1,
    negativeMarking: 0,
    explanation: '30 days is 3 half-lives, so the remaining fraction is (1/2)^3 = 1/8.',
    source,
  },
  {
    id: 'ap-eapcet-physics-010',
    section: 'Physics',
    topic: 'Semiconductor Electronics',
    difficulty: 'medium',
    question: 'In an n-type semiconductor, what are the majority charge carriers?',
    options: ['Ions', 'Electrons', 'Holes', 'Protons'],
    correctIndex: 1,
    marks: 1,
    negativeMarking: 0,
    explanation: 'An n-type semiconductor is doped with pentavalent impurities that donate extra electrons, making electrons the majority charge carriers.',
    source,
  },
  {
    id: 'ap-eapcet-chemistry-001',
    section: 'Chemistry',
    topic: 'Some Basic Concepts of Chemistry',
    difficulty: 'easy',
    question: 'How many moles are present in 8 g of O2? (Molar mass of O2 = 32 g/mol)',
    options: ['2 mol', '0.5 mol', '0.25 mol', '4 mol'],
    correctIndex: 2,
    marks: 1,
    negativeMarking: 0,
    explanation: 'Moles = mass/molar mass = 8/32 = 0.25 mol.',
    source,
  },
  {
    id: 'ap-eapcet-chemistry-002',
    section: 'Chemistry',
    topic: 'Structure of Atom',
    difficulty: 'easy',
    question: 'How many protons are present in a Na+ ion? (Atomic number of Na = 11)',
    options: ['10', '1', '12', '11'],
    correctIndex: 3,
    marks: 1,
    negativeMarking: 0,
    explanation: 'Ionization removes or adds electrons, not protons, so a Na+ ion still has 11 protons.',
    source,
  },
  {
    id: 'ap-eapcet-chemistry-003',
    section: 'Chemistry',
    topic: 'Chemical Bonding',
    difficulty: 'medium',
    question: 'What is the molecular shape of carbon dioxide (CO2)?',
    options: ['Tetrahedral', 'Trigonal planar', 'Bent', 'Linear'],
    correctIndex: 3,
    marks: 1,
    negativeMarking: 0,
    explanation: 'CO2 has two C=O double bonds and no lone pairs on the central carbon, giving it a linear shape.',
    source,
  },
  {
    id: 'ap-eapcet-chemistry-004',
    section: 'Chemistry',
    topic: 'States of Matter',
    difficulty: 'medium',
    question: 'At constant volume, if the absolute temperature of an ideal gas is doubled, what happens to its pressure?',
    options: ['It quadruples', 'It doubles', 'It is halved', 'It stays the same'],
    correctIndex: 1,
    marks: 1,
    negativeMarking: 0,
    explanation: 'By Gay-Lussac\'s law, pressure is directly proportional to temperature at constant volume, so doubling T doubles P.',
    source,
  },
  {
    id: 'ap-eapcet-chemistry-005',
    section: 'Chemistry',
    topic: 'Thermodynamics',
    difficulty: 'medium',
    question: 'For an exothermic reaction, what is the sign of the enthalpy change?',
    options: ['Cannot be determined', 'Negative', 'Zero', 'Positive'],
    correctIndex: 1,
    marks: 1,
    negativeMarking: 0,
    explanation: 'An exothermic reaction releases heat to the surroundings, so its enthalpy change is negative by convention.',
    source,
  },
  {
    id: 'ap-eapcet-chemistry-006',
    section: 'Chemistry',
    topic: 'Equilibrium',
    difficulty: 'hard',
    question: 'For a gaseous equilibrium at constant volume, what effect does adding an inert gas have on the equilibrium position?',
    options: ['It shifts toward the side with more moles', 'It shifts toward the side with fewer moles', 'It stops the reaction', 'No effect'],
    correctIndex: 3,
    marks: 1,
    negativeMarking: 0,
    explanation: 'At constant volume, adding an inert gas does not change the partial pressures or concentrations of the reacting species, so the equilibrium position is unaffected.',
    source,
  },
  {
    id: 'ap-eapcet-chemistry-007',
    section: 'Chemistry',
    topic: 'Electrochemistry',
    difficulty: 'medium',
    question: 'At which electrode does reduction occur in any electrochemical cell?',
    options: ['Both electrodes equally', 'Neither electrode', 'Anode', 'Cathode'],
    correctIndex: 3,
    marks: 1,
    negativeMarking: 0,
    explanation: 'By definition, reduction always occurs at the cathode, whether the cell is galvanic or electrolytic.',
    source,
  },
  {
    id: 'ap-eapcet-chemistry-008',
    section: 'Chemistry',
    topic: 'd and f Block Elements',
    difficulty: 'medium',
    question: 'What is the oxidation state of iron in Fe2O3?',
    options: ['+4', '+6', '+3', '+2'],
    correctIndex: 2,
    marks: 1,
    negativeMarking: 0,
    explanation: 'Oxygen is -2, and three oxygens contribute -6. For the compound to be neutral, two iron atoms must contribute +6 total, so each iron is +3.',
    source,
  },
  {
    id: 'ap-eapcet-chemistry-009',
    section: 'Chemistry',
    topic: 'Alcohols Phenols and Ethers',
    difficulty: 'hard',
    question: 'In the Lucas test, which class of alcohol reacts fastest, producing turbidity almost immediately at room temperature?',
    options: ['Secondary alcohols', 'Primary alcohols', 'All react at the same rate', 'Tertiary alcohols'],
    correctIndex: 3,
    marks: 1,
    negativeMarking: 0,
    explanation: 'Tertiary alcohols form the most stable carbocation intermediate and react fastest with the Lucas reagent, giving turbidity almost immediately.',
    source,
  },
  {
    id: 'ap-eapcet-chemistry-010',
    section: 'Chemistry',
    topic: 'Biomolecules',
    difficulty: 'easy',
    question: 'What is the monomer unit of both starch and cellulose?',
    options: ['Sucrose', 'Amino acids', 'Glucose', 'Fructose'],
    correctIndex: 2,
    marks: 1,
    negativeMarking: 0,
    explanation: 'Both starch and cellulose are polysaccharides built from glucose units, differing only in the type of glycosidic linkage between them.',
    source,
  },
];
