import type { Question } from '../questions';

export const BITSAT_2026_MATHEMATICS_LOGICAL_REASONING_2: Question[] = [
  {
    "id": "bitsat-2026-logical-reasoning2-001",
    "section": "Logical Reasoning",
    "topic": "Verbal Reasoning: Analogy",
    "difficulty": "easy",
    "question": "Pen is to writer as scalpel is to ___ .",
    "options": ["surgeon", "patient", "hospital", "nurse"],
    "correctIndex": 0,
    "answerType": "mcq",
    "marks": 3,
    "negativeMarking": 1,
    "explanation": "A pen is the principal tool of a writer. In the same tool-to-user relationship, a scalpel is the principal tool of a surgeon.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Logical Reasoning syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-logical-reasoning2-002",
    "section": "Logical Reasoning",
    "topic": "Verbal Reasoning: Classification",
    "difficulty": "easy",
    "question": "Identify the item that does not belong with the other three.",
    "options": ["Violin", "Painting", "Guitar", "Cello"],
    "correctIndex": 1,
    "answerType": "mcq",
    "marks": 3,
    "negativeMarking": 1,
    "explanation": "Violin, guitar, and cello are string instruments. Painting is a visual art form, not a musical instrument, making it the odd one out.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Logical Reasoning syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-logical-reasoning2-003",
    "section": "Logical Reasoning",
    "topic": "Verbal Reasoning: Series Completion",
    "difficulty": "medium",
    "question": "Complete the series: 2, 5, 10, 17, 26, ___",
    "options": ["35", "40", "37", "33"],
    "correctIndex": 2,
    "answerType": "mcq",
    "marks": 3,
    "negativeMarking": 1,
    "explanation": "The successive differences are 3, 5, 7, and 9. The next difference is 11, so the next term is 26 + 11 = 37.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Logical Reasoning syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-logical-reasoning2-004",
    "section": "Logical Reasoning",
    "topic": "Verbal Reasoning: Logical Deduction",
    "difficulty": "hard",
    "question": "All engineers in the firm know CAD software. Ravi knows CAD software. Which conclusion is valid?",
    "options": ["Ravi must be an engineer at the firm.", "Ravi cannot work at the firm.", "All employees at the firm know CAD software.", "No conclusion about Ravi being an engineer can be drawn from this alone."],
    "correctIndex": 3,
    "answerType": "mcq",
    "marks": 3,
    "negativeMarking": 1,
    "explanation": "Knowing CAD software does not imply being an engineer at the firm, since others could also know it. No valid conclusion about Ravi's role can be drawn from the given statements alone.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Logical Reasoning syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-logical-reasoning2-005",
    "section": "Logical Reasoning",
    "topic": "Verbal Reasoning: Chart Logic",
    "difficulty": "hard",
    "question": "Four employees A, B, C, D sit in a row of four chairs, left to right. B sits immediately left of C, and A sits immediately left of B. Regardless of exactly where this block of three sits in the row, which employee is always seated between two others?",
    "options": ["B", "A", "C", "D"],
    "correctIndex": 0,
    "answerType": "mcq",
    "marks": 3,
    "negativeMarking": 1,
    "explanation": "A, B, and C always form a fixed consecutive block in that order, so B is always flanked by A on one side and C on the other, regardless of where the block sits relative to D.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Logical Reasoning syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-logical-reasoning2-006",
    "section": "Logical Reasoning",
    "topic": "Nonverbal Reasoning: Pattern Perception",
    "difficulty": "medium",
    "question": "A pattern shows an arrow rotating 45 degrees clockwise each step: pointing up, then up-right, then right, then down-right, ___. What comes next?",
    "options": ["up-left", "down", "left", "down-right"],
    "correctIndex": 1,
    "answerType": "mcq",
    "marks": 3,
    "negativeMarking": 1,
    "explanation": "Each step rotates the arrow 45 degrees clockwise. After down-right (135 degrees), the next position, 180 degrees, points straight down.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Logical Reasoning syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-logical-reasoning2-007",
    "section": "Logical Reasoning",
    "topic": "Nonverbal Reasoning: Figure Formation and Analysis",
    "difficulty": "medium",
    "question": "A regular hexagon is divided into 6 equal triangles by drawing lines from the centre to each vertex. How many of these triangles are needed to cover exactly one-third of the hexagon's area?",
    "options": ["1", "4", "2", "3"],
    "correctIndex": 2,
    "answerType": "mcq",
    "marks": 3,
    "negativeMarking": 1,
    "explanation": "Each of the 6 equal triangles covers one-sixth of the hexagon's area. Two such triangles cover 2/6 = 1/3 of the area.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Logical Reasoning syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-logical-reasoning2-008",
    "section": "Logical Reasoning",
    "topic": "Nonverbal Reasoning: Paper Cutting",
    "difficulty": "hard",
    "question": "A square sheet is folded in half twice, first vertically then horizontally, producing four layers. A triangular notch is cut from the corner that lies exactly at the intersection of both fold lines. After the sheet is fully unfolded, how many separate notches appear?",
    "options": ["4", "2", "3", "1"],
    "correctIndex": 3,
    "answerType": "mcq",
    "marks": 3,
    "negativeMarking": 1,
    "explanation": "Since the cut corner sits exactly at the centre of the original sheet, where both fold lines meet, unfolding reveals a single combined notch at that centre point rather than four separate ones.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Logical Reasoning syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-logical-reasoning2-009",
    "section": "Logical Reasoning",
    "topic": "Nonverbal Reasoning: Figure Matrix",
    "difficulty": "medium",
    "question": "In a figure matrix, each row's column 2 shape has double the sides of column 1, and column 3 has a shape with sides equal to the sum of columns 1 and 2. Row 1: triangle (3), hexagon (6), shape with 9 sides. Row 2: square (4), octagon (8), shape with 12 sides. Row 3: pentagon (5), ___, shape with 15 sides. Which shape completes column 2 of Row 3?",
    "options": ["decagon (10 sides)", "nonagon (9 sides)", "octagon (8 sides)", "heptagon (7 sides)"],
    "correctIndex": 0,
    "answerType": "mcq",
    "marks": 3,
    "negativeMarking": 1,
    "explanation": "Column 2 always has double the sides of column 1. Pentagon has 5 sides, so column 2 needs 10 sides, a decagon; checking column 3, 5+10=15 matches the given value.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Logical Reasoning syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-logical-reasoning2-010",
    "section": "Logical Reasoning",
    "topic": "Nonverbal Reasoning: Rule Detection",
    "difficulty": "medium",
    "question": "A sequence of shapes has 4, 8, 16, 32 sides, doubling each time. If the same rule continues, how many sides does the next shape have?",
    "options": ["48", "64", "56", "72"],
    "correctIndex": 1,
    "answerType": "mcq",
    "marks": 3,
    "negativeMarking": 1,
    "explanation": "Each term doubles the previous one: 4, 8, 16, 32, so the next term is 32 x 2 = 64.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Logical Reasoning syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-logical-reasoning2-011",
    "section": "Logical Reasoning",
    "topic": "Logical Reasoning: Rule Application",
    "difficulty": "hard",
    "question": "A rule maps a pair (a,b) to an output of the form a^2 - b. The rule gives (3,2) -> 7, (4,1) -> 15, and (5,3) -> 22. What is the output for (2,4)?",
    "options": ["2", "4", "0", "-2"],
    "correctIndex": 2,
    "answerType": "mcq",
    "marks": 3,
    "negativeMarking": 1,
    "explanation": "Checking the rule a^2-b: 3^2-2=7, 4^2-1=15, and 5^2-3=22, all consistent. For (2,4): 2^2-4 = 4-4 = 0.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Logical Reasoning syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-logical-reasoning2-012",
    "section": "Logical Reasoning",
    "topic": "Verbal Reasoning: Analogy",
    "difficulty": "easy",
    "question": "Thermometer is to temperature as barometer is to ___ .",
    "options": ["humidity", "wind speed", "altitude", "pressure"],
    "correctIndex": 3,
    "answerType": "mcq",
    "marks": 3,
    "negativeMarking": 1,
    "explanation": "A thermometer measures temperature. In the same instrument-to-measured-quantity relationship, a barometer measures atmospheric pressure.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Logical Reasoning syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-logical-reasoning2-013",
    "section": "Logical Reasoning",
    "topic": "Verbal Reasoning: Classification",
    "difficulty": "easy",
    "question": "Three of the following are forms of government. Which one is different?",
    "options": ["Constitution", "Democracy", "Monarchy", "Oligarchy"],
    "correctIndex": 0,
    "answerType": "mcq",
    "marks": 3,
    "negativeMarking": 1,
    "explanation": "Democracy, monarchy, and oligarchy are forms of government. A constitution is a governing document, not a form of government itself.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Logical Reasoning syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-logical-reasoning2-014",
    "section": "Logical Reasoning",
    "topic": "Verbal Reasoning: Series Completion",
    "difficulty": "easy",
    "question": "Complete the series: 1, 4, 9, 16, 25, ___",
    "options": ["30", "36", "42", "49"],
    "correctIndex": 1,
    "answerType": "mcq",
    "marks": 3,
    "negativeMarking": 1,
    "explanation": "The series lists perfect squares: 1^2, 2^2, 3^2, 4^2, 5^2. The next term is 6^2 = 36.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Logical Reasoning syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-logical-reasoning2-015",
    "section": "Logical Reasoning",
    "topic": "Verbal Reasoning: Logical Deduction",
    "difficulty": "medium",
    "question": "If it rains, the match is cancelled. The match was not cancelled. Which conclusion is valid?",
    "options": ["It rained.", "The match was postponed.", "It did not rain.", "The match will be rescheduled."],
    "correctIndex": 2,
    "answerType": "mcq",
    "marks": 3,
    "negativeMarking": 1,
    "explanation": "By modus tollens, since the match was not cancelled (the consequent is false), the antecedent must also be false: it did not rain.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Logical Reasoning syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-logical-reasoning2-016",
    "section": "Logical Reasoning",
    "topic": "Verbal Reasoning: Chart Logic",
    "difficulty": "medium",
    "question": "Three friends X, Y, Z have different heights. X is taller than Y. Z is shorter than Y. Who is the tallest?",
    "options": ["Y", "Z", "Cannot be determined", "X"],
    "correctIndex": 3,
    "answerType": "mcq",
    "marks": 3,
    "negativeMarking": 1,
    "explanation": "X is taller than Y, and Y is taller than Z, giving the order X > Y > Z. X is the tallest.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Logical Reasoning syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-logical-reasoning2-017",
    "section": "Logical Reasoning",
    "topic": "Nonverbal Reasoning: Pattern Perception",
    "difficulty": "medium",
    "question": "A sequence of dots forms triangular numbers: 1, 3, 6, 10, 15. How many dots are in the next triangular number?",
    "options": ["21", "20", "18", "24"],
    "correctIndex": 0,
    "answerType": "mcq",
    "marks": 3,
    "negativeMarking": 1,
    "explanation": "Triangular numbers add successive integers: 1, 1+2=3, 3+3=6, 6+4=10, 10+5=15. The next term adds 6: 15+6=21.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Logical Reasoning syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-logical-reasoning2-018",
    "section": "Logical Reasoning",
    "topic": "Nonverbal Reasoning: Figure Formation and Analysis",
    "difficulty": "easy",
    "question": "A circle is divided into 8 equal sectors. How many sectors make up three-quarters of the circle?",
    "options": ["4", "6", "5", "7"],
    "correctIndex": 1,
    "answerType": "mcq",
    "marks": 3,
    "negativeMarking": 1,
    "explanation": "Three-quarters of 8 equal sectors is 8 x 3/4 = 6 sectors.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Logical Reasoning syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-logical-reasoning2-019",
    "section": "Logical Reasoning",
    "topic": "Nonverbal Reasoning: Rule Detection",
    "difficulty": "medium",
    "question": "A sequence of numbers is formed by adding the two preceding numbers: 1, 1, 2, 3, 5, 8, ___. What is the next number?",
    "options": ["11", "12", "13", "14"],
    "correctIndex": 2,
    "answerType": "mcq",
    "marks": 3,
    "negativeMarking": 1,
    "explanation": "This is the Fibonacci sequence, where each term is the sum of the two preceding terms: 8+5=13.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Logical Reasoning syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-logical-reasoning2-020",
    "section": "Logical Reasoning",
    "topic": "Logical Reasoning: Rule Application",
    "difficulty": "hard",
    "question": "A code assigns each letter a number equal to its position in the alphabet plus 2, wrapping from Z back to A. If C is coded as E, what is F coded as?",
    "options": ["G", "I", "J", "H"],
    "correctIndex": 3,
    "answerType": "mcq",
    "marks": 3,
    "negativeMarking": 1,
    "explanation": "C is the 3rd letter and E is the 5th letter, confirming the rule of adding 2 to the position. F is the 6th letter, so F+2 gives the 8th letter, H.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Logical Reasoning syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  }
];
