import type { Question } from '../questions';

const SOURCE = {
  kind: 'original',
  reference: 'BITS HD 2026 M.E. Computer Science official brochure syllabus alignment',
  url: 'https://admissions.bits-pilani.ac.in/HD/downloads/HD_Brochure_2026_27.pdf',
  checkedOn: '2026-08-23',
} as const;

const MATHS = 'Core Mathematics';
const ELR = 'English Language Skills & Logical Reasoning';

export const BITS_HD_2026_ME_CS_TEST_1_PAPER_PRACTICE_1: Question[] = [
  {
    id: 'bits-hd-2026-me-cs-test-1-paper-practice-01-001',
    section: MATHS,
    topic: 'Calculus',
    difficulty: 'medium',
    question: 'The limit as x tends to 0 of (e^x - 1 - x)/x^2 is',
    options: ['1/2', '1', '2', '0'],
    correctIndex: 0,
    answerType: 'mcq',
    marks: 3,
    negativeMarking: 1,
    explanation: 'Expanding, e^x = 1 + x + x^2/2 + O(x^3), so the numerator is x^2/2 + O(x^3) and the ratio tends to 1/2.',
    source: SOURCE,
  },
  {
    id: 'bits-hd-2026-me-cs-test-1-paper-practice-01-002',
    section: MATHS,
    topic: 'Calculus',
    difficulty: 'medium',
    question: 'The value of the integral from 0 to pi/2 of sin^2(x) dx is',
    options: ['pi/2', 'pi/4', '1', '1/2'],
    correctIndex: 1,
    answerType: 'mcq',
    marks: 3,
    negativeMarking: 1,
    explanation: 'Using sin^2(x) = (1 - cos(2x))/2, the integral is (1/2)(pi/2) - (1/4)[sin(2x)] from 0 to pi/2 = pi/4.',
    source: SOURCE,
  },
  {
    id: 'bits-hd-2026-me-cs-test-1-paper-practice-01-003',
    section: MATHS,
    topic: 'Calculus',
    difficulty: 'hard',
    question: 'For f(x,y) = x^3 - 3xy + y^3, the critical point (1,1) is',
    options: ['a saddle point', 'a local maximum', 'a local minimum', 'not a critical point'],
    correctIndex: 2,
    answerType: 'mcq',
    marks: 3,
    negativeMarking: 1,
    explanation: 'Setting f_x = 3x^2 - 3y = 0 and f_y = 3y^2 - 3x = 0 gives (0,0) and (1,1). At (1,1), f_xx = 6, f_yy = 6 and f_xy = -3, so the discriminant is 36 - 9 = 27 > 0 with f_xx > 0, giving a local minimum.',
    source: SOURCE,
  },
  {
    id: 'bits-hd-2026-me-cs-test-1-paper-practice-01-004',
    section: MATHS,
    topic: 'Linear Algebra',
    difficulty: 'medium',
    question: 'The rank of the matrix [[1,2,3],[2,4,6],[1,1,1]] is',
    options: ['0', '1', '3', '2'],
    correctIndex: 3,
    answerType: 'mcq',
    marks: 3,
    negativeMarking: 1,
    explanation: 'The second row is exactly twice the first, so it contributes nothing. The first and third rows are not proportional, so the rank is 2.',
    source: SOURCE,
  },
  {
    id: 'bits-hd-2026-me-cs-test-1-paper-practice-01-005',
    section: MATHS,
    topic: 'Linear Algebra',
    difficulty: 'medium',
    question: 'If A is a 3 by 3 matrix with det(A) = 5, then det(2A) is',
    options: ['10', '40', '80', '5'],
    correctIndex: 1,
    answerType: 'mcq',
    marks: 3,
    negativeMarking: 1,
    explanation: 'Scaling an n by n matrix by c multiplies the determinant by c^n. Here n = 3 and c = 2, so det(2A) = 8 x 5 = 40.',
    source: SOURCE,
  },
  {
    id: 'bits-hd-2026-me-cs-test-1-paper-practice-01-006',
    section: MATHS,
    topic: 'Linear Algebra',
    difficulty: 'hard',
    question: 'For A = [[0,1],[1,0]], the matrix A^10 is',
    options: ['A', '10A', 'the 2 by 2 identity matrix', 'the 2 by 2 zero matrix'],
    correctIndex: 2,
    answerType: 'mcq',
    marks: 3,
    negativeMarking: 1,
    explanation: 'A is the swap matrix and A^2 is the identity, so every even power of A is the identity. Since 10 is even, A^10 = I.',
    source: SOURCE,
  },
  {
    id: 'bits-hd-2026-me-cs-test-1-paper-practice-01-007',
    section: MATHS,
    topic: 'Complex Variables',
    difficulty: 'medium',
    question: 'The contour integral of 1/(z - 1) taken counterclockwise around the circle |z| = 2 is',
    options: ['0', 'pi i', '-2 pi i', '2 pi i'],
    correctIndex: 3,
    answerType: 'mcq',
    marks: 3,
    negativeMarking: 1,
    explanation: 'The only singularity, a simple pole at z = 1, lies inside |z| = 2 and has residue 1, so by the residue theorem the integral is 2 pi i.',
    source: SOURCE,
  },
  {
    id: 'bits-hd-2026-me-cs-test-1-paper-practice-01-008',
    section: MATHS,
    topic: 'Complex Variables',
    difficulty: 'hard',
    question: 'The residue of (z + 1)/(z^2 - z) at z = 1 is',
    options: ['2', '-1', '1', '0'],
    correctIndex: 0,
    answerType: 'mcq',
    marks: 3,
    negativeMarking: 1,
    explanation: 'Write the function as (z + 1)/[z(z - 1)]. The pole at z = 1 is simple, so the residue is the value of (z + 1)/z at z = 1, which is 2.',
    source: SOURCE,
  },
  {
    id: 'bits-hd-2026-me-cs-test-1-paper-practice-01-009',
    section: MATHS,
    topic: 'Probability and Statistics',
    difficulty: 'medium',
    question: 'Two fair six-sided dice are rolled once. The probability that the sum is 8 is',
    options: ['1/6', '1/9', '5/36', '1/12'],
    correctIndex: 2,
    answerType: 'mcq',
    marks: 3,
    negativeMarking: 1,
    explanation: 'The ordered pairs summing to 8 are (2,6), (3,5), (4,4), (5,3) and (6,2), so 5 of the 36 equally likely outcomes qualify.',
    source: SOURCE,
  },
  {
    id: 'bits-hd-2026-me-cs-test-1-paper-practice-01-010',
    section: MATHS,
    topic: 'Probability and Statistics',
    difficulty: 'medium',
    question: 'If X follows a binomial distribution with n = 10 and p = 0.3, then Var(X) is',
    options: ['3', '0.21', '7', '2.1'],
    correctIndex: 3,
    answerType: 'mcq',
    marks: 3,
    negativeMarking: 1,
    explanation: 'For a binomial variable the variance is n p (1 - p) = 10 x 0.3 x 0.7 = 2.1. The value 3 is the mean, not the variance.',
    source: SOURCE,
  },
  {
    id: 'bits-hd-2026-me-cs-test-1-paper-practice-01-011',
    section: MATHS,
    topic: 'Probability and Statistics',
    difficulty: 'hard',
    question: 'A box holds 4 red and 6 blue balls. Two balls are drawn without replacement. The probability that both are red is',
    options: ['2/15', '4/25', '1/5', '3/20'],
    correctIndex: 0,
    answerType: 'mcq',
    marks: 3,
    negativeMarking: 1,
    explanation: 'The probability is (4/10) x (3/9) = 12/90 = 2/15. The value 4/25 is what you get by drawing with replacement instead.',
    source: SOURCE,
  },
  {
    id: 'bits-hd-2026-me-cs-test-1-paper-practice-01-012',
    section: MATHS,
    topic: 'Differential Equations',
    difficulty: 'medium',
    question: "The general solution of y'' - 4y' + 4y = 0 is",
    options: [
      'C1 e^(2x) + C2 e^(-2x)',
      '(C1 + C2 x) e^(2x)',
      'C1 cos(2x) + C2 sin(2x)',
      '(C1 + C2 x) e^(-2x)',
    ],
    correctIndex: 1,
    answerType: 'mcq',
    marks: 3,
    negativeMarking: 1,
    explanation: 'The auxiliary equation m^2 - 4m + 4 = 0 has the repeated root m = 2, so the solution carries the extra factor of x on the second term.',
    source: SOURCE,
  },
  {
    id: 'bits-hd-2026-me-cs-test-1-paper-practice-01-013',
    section: MATHS,
    topic: 'Differential Equations',
    difficulty: 'hard',
    question: 'For x > 0, the integrating factor of dy/dx + (2/x) y = x^3 is',
    options: ['e^(2x)', 'x', '1/x^2', 'x^2'],
    correctIndex: 3,
    answerType: 'mcq',
    marks: 3,
    negativeMarking: 1,
    explanation: 'The integrating factor is exp of the integral of 2/x, which is exp(2 ln x) = x^2 for x > 0.',
    source: SOURCE,
  },
  {
    id: 'bits-hd-2026-me-cs-test-1-paper-practice-01-014',
    section: MATHS,
    topic: 'Numerical Methods',
    difficulty: 'medium',
    question: 'One Newton-Raphson step for f(x) = x^2 - 2 starting from x0 = 1 gives x1 equal to',
    options: ['1.5', '2', '1.25', '1.4142'],
    correctIndex: 0,
    answerType: 'mcq',
    marks: 3,
    negativeMarking: 1,
    explanation: "x1 = x0 - f(x0)/f'(x0) = 1 - (-1)/2 = 1.5. The value 1.4142 is the root itself, which one step does not reach.",
    source: SOURCE,
  },
  {
    id: 'bits-hd-2026-me-cs-test-1-paper-practice-01-015',
    section: MATHS,
    topic: 'Numerical Methods',
    difficulty: 'hard',
    question: "Simpson's 1/3 rule with two subintervals applied to the integral from 0 to 2 of x^3 dx gives",
    options: ['3.75', '4', '4.25', '5'],
    correctIndex: 1,
    answerType: 'mcq',
    marks: 3,
    negativeMarking: 1,
    explanation: "With h = 1 the rule gives (1/3)[0 + 4(1) + 8] = 4, which matches the exact value 16/4 = 4. Simpson's 1/3 rule is exact for polynomials up to degree three.",
    source: SOURCE,
  },
  {
    id: 'bits-hd-2026-me-cs-test-1-paper-practice-01-016',
    section: ELR,
    topic: 'English Language Skills',
    difficulty: 'easy',
    question: "Choose the word closest in meaning to 'meticulous'.",
    options: ['hasty', 'indifferent', 'painstaking', 'ambiguous'],
    correctIndex: 2,
    answerType: 'mcq',
    marks: 3,
    negativeMarking: 1,
    explanation: 'Meticulous describes very careful attention to detail, which is what painstaking conveys. Hasty and indifferent are opposed to it, and ambiguous refers to unclear meaning.',
    source: SOURCE,
  },
  {
    id: 'bits-hd-2026-me-cs-test-1-paper-practice-01-017',
    section: ELR,
    topic: 'English Language Skills',
    difficulty: 'easy',
    question: 'Choose the correctly punctuated sentence from the options below.',
    options: [
      'The test, which ran for 45 minutes, was auto-submitted.',
      'The test which ran for 45 minutes, was auto-submitted.',
      'The test, which ran for 45 minutes was auto-submitted.',
      'The test which, ran for 45 minutes, was auto-submitted.',
    ],
    correctIndex: 0,
    answerType: 'mcq',
    marks: 3,
    negativeMarking: 1,
    explanation: 'A non-defining relative clause takes a comma at both ends. The other options open or close the clause without its matching comma, or break the clause after "which".',
    source: SOURCE,
  },
  {
    id: 'bits-hd-2026-me-cs-test-1-paper-practice-01-018',
    section: ELR,
    topic: 'English Language Skills',
    difficulty: 'medium',
    question: 'Select the sentence with correct subject-verb agreement.',
    options: [
      'Neither of the candidates were shortlisted.',
      'Neither of the candidates was shortlisted.',
      'Neither of the candidates have been shortlisted.',
      'Neither of the candidates are shortlisted.',
    ],
    correctIndex: 1,
    answerType: 'mcq',
    marks: 3,
    negativeMarking: 1,
    explanation: '"Neither" is the subject and is singular, so it takes a singular verb. The intervening phrase "of the candidates" does not change the number of the subject.',
    source: SOURCE,
  },
  {
    id: 'bits-hd-2026-me-cs-test-1-paper-practice-01-019',
    section: ELR,
    topic: 'English Language Skills',
    difficulty: 'medium',
    question: 'Complete the sentence: The results were promising; _____, the sample was too small to support a general claim.',
    options: ['therefore', 'moreover', 'however', 'hence'],
    correctIndex: 2,
    answerType: 'mcq',
    marks: 3,
    negativeMarking: 1,
    explanation: 'The second clause limits the first, so the sentence needs a contrastive link. Therefore and hence signal consequence, and moreover signals addition.',
    source: SOURCE,
  },
  {
    id: 'bits-hd-2026-me-cs-test-1-paper-practice-01-020',
    section: ELR,
    topic: 'English Language Skills',
    difficulty: 'medium',
    question: "In the sentence 'Having reviewed the logs, the cause became obvious,' the error is",
    options: [
      'a subject-verb disagreement',
      'an incorrect verb tense',
      'a missing coordinating conjunction',
      'a dangling modifier',
    ],
    correctIndex: 3,
    answerType: 'mcq',
    marks: 3,
    negativeMarking: 1,
    explanation: 'The opening participial phrase has no one to attach to: the cause did not review the logs. A reviser would write "Having reviewed the logs, we found the cause obvious."',
    source: SOURCE,
  },
  {
    id: 'bits-hd-2026-me-cs-test-1-paper-practice-01-021',
    section: ELR,
    topic: 'English Language Skills',
    difficulty: 'easy',
    question: 'Choose the word that best completes the sentence: The specification was deliberately _____ so that several different implementations would remain valid.',
    options: ['rigid', 'broad', 'erroneous', 'obsolete'],
    correctIndex: 1,
    answerType: 'mcq',
    marks: 3,
    negativeMarking: 1,
    explanation: 'Leaving room for several valid implementations calls for breadth. Rigid contradicts that purpose, and erroneous and obsolete describe faults rather than a design choice.',
    source: SOURCE,
  },
  {
    id: 'bits-hd-2026-me-cs-test-1-paper-practice-01-022',
    section: ELR,
    topic: 'English Language Skills',
    difficulty: 'medium',
    question: "Which revision removes the redundancy in 'The two papers both reached the same identical conclusion'?",
    options: [
      'The two papers both reached the same conclusion.',
      'Both of the two papers reached an identical conclusion.',
      'The two papers both reached an identical conclusion.',
      'Both papers reached the same conclusion.',
    ],
    correctIndex: 3,
    answerType: 'mcq',
    marks: 3,
    negativeMarking: 1,
    explanation: 'The original repeats itself twice over: "two" with "both", and "same" with "identical". Only the last option drops one term from each pair.',
    source: SOURCE,
  },
  {
    id: 'bits-hd-2026-me-cs-test-1-paper-practice-01-023',
    section: ELR,
    topic: 'English Language Skills',
    difficulty: 'medium',
    question: "A passage states: 'Automated tests catch regressions quickly, but they only cover behaviour someone has already thought to specify.' The passage implies that automated tests",
    options: [
      'cannot detect a failure in behaviour nobody has specified',
      'are slower than manual review',
      'will find every regression in a system',
      'should be written instead of specifications',
    ],
    correctIndex: 0,
    answerType: 'mcq',
    marks: 3,
    negativeMarking: 1,
    explanation: 'The limiting clause says coverage stops at what was specified, so unspecified behaviour falls outside it. The passage calls the tests quick, not slow, and makes no claim about replacing specifications.',
    source: SOURCE,
  },
  {
    id: 'bits-hd-2026-me-cs-test-1-paper-practice-01-024',
    section: ELR,
    topic: 'Logical Reasoning',
    difficulty: 'medium',
    question: 'All members of the review panel are researchers. Some researchers are not statisticians. Which conclusion necessarily follows?',
    options: [
      'Some members of the panel are not statisticians.',
      'No member of the panel is a statistician.',
      'Nothing follows about the panel members from these two statements alone.',
      'All statisticians are researchers.',
    ],
    correctIndex: 2,
    answerType: 'mcq',
    marks: 3,
    negativeMarking: 1,
    explanation: 'The researchers who are not statisticians need not be the panel members: every panel member could still be a statistician. This is the classic undistributed middle, so no conclusion about the panel is forced.',
    source: SOURCE,
  },
  {
    id: 'bits-hd-2026-me-cs-test-1-paper-practice-01-025',
    section: ELR,
    topic: 'Logical Reasoning',
    difficulty: 'medium',
    question: 'Five servers A, B, C, D and E are ranked by uptime, highest first. C is above D, E is below D but above B, and A is above C. Which server has the third-highest uptime?',
    options: ['A', 'C', 'D', 'E'],
    correctIndex: 2,
    answerType: 'mcq',
    marks: 3,
    negativeMarking: 1,
    explanation: 'The constraints chain into the single order A, C, D, E, B from highest to lowest, so the third-highest is D.',
    source: SOURCE,
  },
  {
    id: 'bits-hd-2026-me-cs-test-1-paper-practice-01-026',
    section: ELR,
    topic: 'Logical Reasoning',
    difficulty: 'easy',
    question: 'If SOFT is coded as TPGU by shifting each letter one place forward, then HARD is coded as',
    options: ['IBSE', 'GZQC', 'IBSD', 'HBSE'],
    correctIndex: 0,
    answerType: 'mcq',
    marks: 3,
    negativeMarking: 1,
    explanation: 'Shifting each of H, A, R and D one place forward gives I, B, S and E. GZQC shifts backward, and the other two leave one letter unshifted.',
    source: SOURCE,
  },
  {
    id: 'bits-hd-2026-me-cs-test-1-paper-practice-01-027',
    section: ELR,
    topic: 'Logical Reasoning',
    difficulty: 'hard',
    question: "Exactly one of P, Q and R is telling the truth. P says 'Q is lying.' Q says 'R is lying.' R says 'P and Q are both lying.' Who is telling the truth?",
    options: ['P', 'R', 'None of them', 'Q'],
    correctIndex: 3,
    answerType: 'mcq',
    marks: 3,
    negativeMarking: 1,
    explanation: 'If P alone were truthful, Q would be lying, so R would be truthful as well, which contradicts the condition. If R alone were truthful, P would be lying, so Q would be truthful, again a contradiction. Q alone being truthful is consistent throughout.',
    source: SOURCE,
  },
  {
    id: 'bits-hd-2026-me-cs-test-1-paper-practice-01-028',
    section: ELR,
    topic: 'Logical Reasoning',
    difficulty: 'medium',
    question: 'In a class of 40 students, 25 play chess, 18 play carrom and 8 play both. How many play neither game?',
    options: ['3', '5', '7', '8'],
    correctIndex: 1,
    answerType: 'mcq',
    marks: 3,
    negativeMarking: 1,
    explanation: 'By inclusion and exclusion, 25 + 18 - 8 = 35 students play at least one game, leaving 40 - 35 = 5 who play neither.',
    source: SOURCE,
  },
  {
    id: 'bits-hd-2026-me-cs-test-1-paper-practice-01-029',
    section: ELR,
    topic: 'Logical Reasoning',
    difficulty: 'medium',
    question: 'Defects found per build were: Build 1, 12; Build 2, 9; Build 3, 15; Build 4, 4. By approximately what percentage did the defect count fall from Build 3 to Build 4?',
    options: ['about 73%', 'about 27%', 'about 65%', 'about 80%'],
    correctIndex: 0,
    answerType: 'mcq',
    marks: 3,
    negativeMarking: 1,
    explanation: 'The fall is 15 - 4 = 11 against a base of 15, so 11/15 is about 73%. The figure of about 27% is the share that remains, not the fall.',
    source: SOURCE,
  },
  {
    id: 'bits-hd-2026-me-cs-test-1-paper-practice-01-030',
    section: ELR,
    topic: 'Logical Reasoning',
    difficulty: 'medium',
    question: "A rule states: 'If the build passes, the artifact is published.' On one run the artifact was not published. Which conclusion is valid?",
    options: [
      'The build passed.',
      'Nothing at all can be concluded about the build.',
      'The build did not pass.',
      'The artifact was corrupted.',
    ],
    correctIndex: 2,
    answerType: 'mcq',
    marks: 3,
    negativeMarking: 1,
    explanation: 'The contrapositive of "if the build passes then the artifact is published" is "if the artifact is not published then the build did not pass", which is logically equivalent to the rule.',
    source: SOURCE,
  },
];
