import type { Question } from '../questions';

export const BITSAT_2026_MATHEMATICS_CHEMISTRY_2: Question[] = [
  {
    "id": "bitsat-2026-chemistry2-001",
    "section": "Chemistry",
    "topic": "States of Matter",
    "difficulty": "medium",
    "question": "According to the ideal gas equation, if the absolute temperature of a fixed amount of gas is doubled at constant pressure, its volume",
    "options": ["doubles", "halves", "remains the same", "quadruples"],
    "correctIndex": 0,
    "answerType": "mcq", "marks": 3, "negativeMarking": 1,
    "explanation": "At constant pressure, V is directly proportional to T (Charles's law), so doubling the absolute temperature doubles the volume.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Chemistry syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-chemistry2-002",
    "section": "Chemistry",
    "topic": "Atomic Structure",
    "difficulty": "medium",
    "question": "The number of unpaired electrons in the ground-state electronic configuration of nitrogen (atomic number 7) is",
    "options": ["2", "3", "1", "4"],
    "correctIndex": 1,
    "answerType": "mcq", "marks": 3, "negativeMarking": 1,
    "explanation": "Nitrogen's configuration is 1s2 2s2 2p3. By Hund's rule, the three 2p electrons occupy separate orbitals with parallel spin, giving 3 unpaired electrons.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Chemistry syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-chemistry2-003",
    "section": "Chemistry",
    "topic": "Chemical Bonding and Molecular Structure",
    "difficulty": "hard",
    "question": "The shape of the XeF4 molecule, based on VSEPR theory, is",
    "options": ["tetrahedral", "see-saw", "square planar", "trigonal bipyramidal"],
    "correctIndex": 2,
    "answerType": "mcq", "marks": 3, "negativeMarking": 1,
    "explanation": "Xenon in XeF4 has 4 bonding pairs and 2 lone pairs in an octahedral electron arrangement; the lone pairs occupy axial positions, leaving a square planar molecular shape.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Chemistry syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-chemistry2-004",
    "section": "Chemistry",
    "topic": "Thermodynamics",
    "difficulty": "medium",
    "question": "For a process carried out at constant pressure, the heat absorbed by the system equals the change in",
    "options": ["internal energy", "entropy", "Gibbs free energy", "enthalpy"],
    "correctIndex": 3,
    "answerType": "mcq", "marks": 3, "negativeMarking": 1,
    "explanation": "Enthalpy is defined so that at constant pressure, qp = delta H, the heat absorbed by the system.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Chemistry syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-chemistry2-005",
    "section": "Chemistry",
    "topic": "Physical and Chemical Equilibria",
    "difficulty": "medium",
    "question": "For the equilibrium N2O4(g) in equilibrium with 2NO2(g), increasing the pressure at constant temperature shifts the equilibrium",
    "options": ["towards N2O4", "towards NO2", "no shift occurs", "shifts unpredictably"],
    "correctIndex": 0,
    "answerType": "mcq", "marks": 3, "negativeMarking": 1,
    "explanation": "By Le Chatelier's principle, increasing pressure favours the side with fewer gas moles. N2O4 has 1 mole of gas versus 2 moles of NO2, so the equilibrium shifts towards N2O4.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Chemistry syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-chemistry2-006",
    "section": "Chemistry",
    "topic": "Electrochemistry",
    "difficulty": "medium",
    "question": "In a Daniell cell (Zn-Cu), the standard cell potential is 1.10 V. If E-standard(Cu2+/Cu) = 0.34 V, what is E-standard(Zn2+/Zn)?",
    "options": ["-1.44 V", "-0.76 V", "0.76 V", "1.44 V"],
    "correctIndex": 1,
    "answerType": "mcq", "marks": 3, "negativeMarking": 1,
    "explanation": "E(cell) = E(cathode) - E(anode), so 1.10 = 0.34 - E(Zn2+/Zn), giving E(Zn2+/Zn) = 0.34 - 1.10 = -0.76 V.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Chemistry syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-chemistry2-007",
    "section": "Chemistry",
    "topic": "Chemical Kinetics",
    "difficulty": "medium",
    "question": "The rate of a reaction is found to double when the concentration of a single reactant is doubled, all else constant. The order of the reaction with respect to that reactant is",
    "options": ["zero", "two", "one", "three"],
    "correctIndex": 2,
    "answerType": "mcq", "marks": 3, "negativeMarking": 1,
    "explanation": "If rate is proportional to [A]^n and doubling [A] doubles the rate, then 2 = 2^n, so n = 1, a first-order dependence.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Chemistry syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-chemistry2-008",
    "section": "Chemistry",
    "topic": "Surface Chemistry",
    "difficulty": "medium",
    "question": "Which of the following best describes physisorption, as opposed to chemisorption?",
    "options": ["Involves strong covalent bond formation", "Is generally irreversible", "Requires high activation energy", "Involves weak van der Waals forces between adsorbate and adsorbent"],
    "correctIndex": 3,
    "answerType": "mcq", "marks": 3, "negativeMarking": 1,
    "explanation": "Physisorption is characterized by weak van der Waals attraction between the adsorbate and adsorbent, unlike chemisorption, which forms stronger chemical bonds and is generally less reversible.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Chemistry syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-chemistry2-009",
    "section": "Chemistry",
    "topic": "Hydrogen and s-block Elements",
    "difficulty": "medium",
    "question": "Among the alkali metals, which one has the highest first ionization enthalpy?",
    "options": ["Lithium", "Sodium", "Potassium", "Rubidium"],
    "correctIndex": 0,
    "answerType": "mcq", "marks": 3, "negativeMarking": 1,
    "explanation": "Ionization enthalpy decreases down a group as atomic size increases. Lithium, the smallest alkali metal, has the highest first ionization enthalpy among them.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Chemistry syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-chemistry2-010",
    "section": "Chemistry",
    "topic": "p-, d-, and f-block Elements",
    "difficulty": "medium",
    "question": "Which of the following ions is expected to be colourless due to a completely filled d-subshell?",
    "options": ["Cu2+", "Zn2+", "Fe2+", "Ti3+"],
    "correctIndex": 1,
    "answerType": "mcq", "marks": 3, "negativeMarking": 1,
    "explanation": "Zn2+ has a completely filled 3d10 configuration, so no d-d electronic transitions are possible, making it colourless.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Chemistry syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-chemistry2-011",
    "section": "Chemistry",
    "topic": "Principles of Organic Chemistry and Hydrocarbons",
    "difficulty": "medium",
    "question": "Markovnikov's rule predicts that when HBr adds to propene (CH3-CH=CH2), the major product is",
    "options": ["1-bromopropane", "1,2-dibromopropane", "2-bromopropane", "propan-1-ol"],
    "correctIndex": 2,
    "answerType": "mcq", "marks": 3, "negativeMarking": 1,
    "explanation": "Markovnikov's rule places the halogen on the more substituted carbon, giving 2-bromopropane as the major product.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Chemistry syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-chemistry2-012",
    "section": "Chemistry",
    "topic": "Stereochemistry",
    "difficulty": "medium",
    "question": "A compound with one chiral centre and no other stereocentres exists as",
    "options": ["a pair of diastereomers", "a meso compound", "a set of four stereoisomers", "a pair of enantiomers"],
    "correctIndex": 3,
    "answerType": "mcq", "marks": 3, "negativeMarking": 1,
    "explanation": "A single chiral centre gives rise to exactly two non-superimposable mirror-image forms, a pair of enantiomers.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Chemistry syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-chemistry2-013",
    "section": "Chemistry",
    "topic": "Organic Compounds with Functional Groups Containing Oxygen and Nitrogen",
    "difficulty": "easy",
    "question": "The functional group present in an amide is",
    "options": ["-CONH2", "-COOH", "-CHO", "-COOR"],
    "correctIndex": 0,
    "answerType": "mcq", "marks": 3, "negativeMarking": 1,
    "explanation": "An amide contains the carbonyl group bonded to a nitrogen atom, represented as -CONH2 in a primary amide.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Chemistry syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-chemistry2-014",
    "section": "Chemistry",
    "topic": "Biological, Industrial and Environmental Chemistry",
    "difficulty": "medium",
    "question": "Which gas is the largest contributor to the anthropogenic (human-caused) greenhouse effect by volume of emissions?",
    "options": ["Methane", "Carbon dioxide", "Nitrous oxide", "Ozone"],
    "correctIndex": 1,
    "answerType": "mcq", "marks": 3, "negativeMarking": 1,
    "explanation": "Carbon dioxide, released mainly from burning fossil fuels, is the largest contributor to anthropogenic greenhouse gas emissions by volume.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Chemistry syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-chemistry2-015",
    "section": "Chemistry",
    "topic": "Theoretical Principles of Experimental Chemistry",
    "difficulty": "medium",
    "question": "In gravimetric analysis, the precipitate is typically dried or ignited before weighing primarily to",
    "options": ["increase its solubility", "change its colour", "obtain a product of constant, definite composition", "increase its molar mass arbitrarily"],
    "correctIndex": 2,
    "answerType": "mcq", "marks": 3, "negativeMarking": 1,
    "explanation": "Drying or igniting removes moisture and volatile impurities, converting the precipitate into a product of constant, known composition suitable for accurate weighing.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Chemistry syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-chemistry2-016",
    "section": "Chemistry",
    "topic": "States of Matter",
    "difficulty": "medium",
    "question": "According to Graham's law of diffusion, the rate of diffusion of a gas is",
    "options": ["directly proportional to its molar mass", "independent of molar mass", "directly proportional to the square root of its molar mass", "inversely proportional to the square root of its molar mass"],
    "correctIndex": 3,
    "answerType": "mcq", "marks": 3, "negativeMarking": 1,
    "explanation": "Graham's law states that the rate of diffusion is inversely proportional to the square root of the gas's molar mass.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Chemistry syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-chemistry2-017",
    "section": "Chemistry",
    "topic": "Atomic Structure",
    "difficulty": "easy",
    "question": "The maximum number of electrons that can occupy the M shell (n=3) is",
    "options": ["18", "8", "32", "9"],
    "correctIndex": 0,
    "answerType": "mcq", "marks": 3, "negativeMarking": 1,
    "explanation": "The maximum number of electrons in a shell is given by 2n^2. For n=3, this is 2(9)=18.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Chemistry syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-chemistry2-018",
    "section": "Chemistry",
    "topic": "Chemical Bonding and Molecular Structure",
    "difficulty": "easy",
    "question": "The bond angle in methane (CH4) is approximately",
    "options": ["120 degrees", "109.5 degrees", "90 degrees", "180 degrees"],
    "correctIndex": 1,
    "answerType": "mcq", "marks": 3, "negativeMarking": 1,
    "explanation": "Methane's carbon is sp3 hybridised with a tetrahedral geometry, giving a bond angle of approximately 109.5 degrees.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Chemistry syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-chemistry2-019",
    "section": "Chemistry",
    "topic": "Thermodynamics",
    "difficulty": "medium",
    "question": "For a spontaneous process at constant temperature and pressure, the sign of the Gibbs free energy change (delta G) is",
    "options": ["positive", "zero", "negative", "undefined"],
    "correctIndex": 2,
    "answerType": "mcq", "marks": 3, "negativeMarking": 1,
    "explanation": "A process is spontaneous at constant temperature and pressure when delta G is negative.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Chemistry syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-chemistry2-020",
    "section": "Chemistry",
    "topic": "Physical and Chemical Equilibria",
    "difficulty": "medium",
    "question": "The pH of a 0.001 M solution of a strong monobasic acid, fully dissociated, is",
    "options": ["1", "2", "4", "3"],
    "correctIndex": 3,
    "answerType": "mcq", "marks": 3, "negativeMarking": 1,
    "explanation": "For a fully dissociated strong monobasic acid, [H+] = 0.001 = 10^-3 M, so pH = -log(10^-3) = 3.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Chemistry syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-chemistry2-021",
    "section": "Chemistry",
    "topic": "Electrochemistry",
    "difficulty": "medium",
    "question": "In the electrolysis of molten sodium chloride, which product forms at the cathode?",
    "options": ["Sodium metal", "Chlorine gas", "Oxygen gas", "Hydrogen gas"],
    "correctIndex": 0,
    "answerType": "mcq", "marks": 3, "negativeMarking": 1,
    "explanation": "At the cathode, reduction occurs: Na+ ions gain electrons to form sodium metal. Chlorine gas forms at the anode instead.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Chemistry syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-chemistry2-022",
    "section": "Chemistry",
    "topic": "Chemical Kinetics",
    "difficulty": "medium",
    "question": "For a first-order reaction, a plot of ln[A] versus time gives",
    "options": ["a straight line with positive slope", "a straight line with negative slope", "a curve, not a straight line", "a horizontal line"],
    "correctIndex": 1,
    "answerType": "mcq", "marks": 3, "negativeMarking": 1,
    "explanation": "For a first-order reaction, ln[A] = ln[A]0 - kt, which is a straight line with a negative slope equal to -k.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Chemistry syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-chemistry2-023",
    "section": "Chemistry",
    "topic": "Surface Chemistry",
    "difficulty": "medium",
    "question": "Catalysts increase the rate of a reaction primarily by",
    "options": ["increasing the temperature of the reactants", "shifting the equilibrium position", "lowering the activation energy of the reaction", "increasing the concentration of reactants"],
    "correctIndex": 2,
    "answerType": "mcq", "marks": 3, "negativeMarking": 1,
    "explanation": "A catalyst provides an alternative reaction pathway with lower activation energy, increasing the reaction rate without being consumed.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Chemistry syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-chemistry2-024",
    "section": "Chemistry",
    "topic": "Hydrogen and s-block Elements",
    "difficulty": "medium",
    "question": "Among the alkaline earth metals, which one does not impart a characteristic colour to a Bunsen flame?",
    "options": ["Calcium", "Strontium", "Barium", "Beryllium"],
    "correctIndex": 3,
    "answerType": "mcq", "marks": 3, "negativeMarking": 1,
    "explanation": "Beryllium's small size and high ionization energy mean it does not undergo the electronic transitions needed for visible flame colouration, unlike calcium, strontium, and barium.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Chemistry syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-chemistry2-025",
    "section": "Chemistry",
    "topic": "p-, d-, and f-block Elements",
    "difficulty": "medium",
    "question": "The general electronic configuration of the lanthanides involves the progressive filling of which subshell?",
    "options": ["4f", "5f", "3d", "4d"],
    "correctIndex": 0,
    "answerType": "mcq", "marks": 3, "negativeMarking": 1,
    "explanation": "The lanthanide series is characterized by the progressive filling of the 4f subshell.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Chemistry syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-chemistry2-026",
    "section": "Chemistry",
    "topic": "Principles of Organic Chemistry and Hydrocarbons",
    "difficulty": "medium",
    "question": "Which of the following hydrocarbons will decolourise bromine water rapidly without requiring a catalyst or UV light?",
    "options": ["Ethane", "Ethene", "Benzene", "Methane"],
    "correctIndex": 1,
    "answerType": "mcq", "marks": 3, "negativeMarking": 1,
    "explanation": "Ethene's carbon-carbon double bond reacts readily with bromine via electrophilic addition, rapidly decolourising bromine water without needing a catalyst or UV light.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Chemistry syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-chemistry2-027",
    "section": "Chemistry",
    "topic": "Stereochemistry",
    "difficulty": "medium",
    "question": "Which term describes stereoisomers that are non-superimposable mirror images of each other?",
    "options": ["Conformers", "Diastereomers", "Enantiomers", "Structural isomers"],
    "correctIndex": 2,
    "answerType": "mcq", "marks": 3, "negativeMarking": 1,
    "explanation": "Enantiomers are pairs of stereoisomers that are non-superimposable mirror images of one another.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Chemistry syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-chemistry2-028",
    "section": "Chemistry",
    "topic": "Organic Compounds with Functional Groups Containing Oxygen and Nitrogen",
    "difficulty": "hard",
    "question": "Which reagent is commonly used to convert a primary aromatic amine into a diazonium salt (diazotization)?",
    "options": ["Sodium hydroxide", "Concentrated sulfuric acid", "Potassium permanganate", "Nitrous acid (NaNO2/HCl, cold)"],
    "correctIndex": 3,
    "answerType": "mcq", "marks": 3, "negativeMarking": 1,
    "explanation": "Diazotization uses nitrous acid, generated in situ from sodium nitrite and hydrochloric acid, at low temperature to convert a primary aromatic amine into a diazonium salt.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Chemistry syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-chemistry2-029",
    "section": "Chemistry",
    "topic": "Biological, Industrial and Environmental Chemistry",
    "difficulty": "medium",
    "question": "Eutrophication of a water body is primarily caused by excess",
    "options": ["nutrients such as nitrogen and phosphorus", "dissolved oxygen", "heavy metals only", "plastic waste only"],
    "correctIndex": 0,
    "answerType": "mcq", "marks": 3, "negativeMarking": 1,
    "explanation": "Eutrophication results from excess nutrients, especially nitrogen and phosphorus, which promote algal blooms that deplete dissolved oxygen as they decompose.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Chemistry syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  },
  {
    "id": "bitsat-2026-chemistry2-030",
    "section": "Chemistry",
    "topic": "Theoretical Principles of Experimental Chemistry",
    "difficulty": "medium",
    "question": "In an acid-base titration, the indicator is chosen so that its colour change occurs",
    "options": ["at the very start of the titration", "close to the equivalence point of the titration", "only in strongly acidic solutions", "independent of the equivalence point"],
    "correctIndex": 1,
    "answerType": "mcq", "marks": 3, "negativeMarking": 1,
    "explanation": "A suitable indicator changes colour within the pH range close to the equivalence point, so the observed endpoint closely matches the true equivalence point.",
    "source": { "kind": "original", "reference": "Written to the official BITSAT-2026 Chemistry syllabus and approved Mathematics-variant pattern", "url": "https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf", "checkedOn": "2026-08-24" }
  }
];
