import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'Original CDS English practice questions in the official 4-option multiple-choice format, covering grammar, usage, vocabulary, and comprehension from the UPSC CDS syllabus.',
  url: 'https://upsc.gov.in/examinations/Combined%20Defence%20Services%20Examination',
  checkedOn: '16 August 2026',
};

export const CDS_ENGLISH_1: Question[] = [
  { id: 'cds-english-01-001', section: 'Grammar and Usage', topic: 'Subject-Verb Agreement', difficulty: 'easy', question: 'Choose the grammatically correct sentence.', options: ['Each of the students have a book.', 'Each of the students are having a book.', 'Each of the students has a book.', 'Each of the students having a book.'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: '"Each" is singular, so it takes the singular verb "has": Each of the students has a book.', source },
  { id: 'cds-english-01-002', section: 'Grammar and Usage', topic: 'Prepositions', difficulty: 'easy', question: 'Fill in the blank: He is afraid ___ the dark.', options: ['from', 'by', 'for', 'of'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'The correct idiomatic preposition is "of": He is afraid of the dark.', source },
  { id: 'cds-english-01-003', section: 'Grammar and Usage', topic: 'Conditional Sentences', difficulty: 'medium', question: 'Fill in the blank: If it rains, we ___ the trip.', options: ['will cancel', 'cancel', 'would cancel', 'cancelled'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'In a first conditional sentence, the main clause uses the future simple: "will cancel".', source },
  { id: 'cds-english-01-004', section: 'Grammar and Usage', topic: 'Spelling', difficulty: 'easy', question: 'Choose the correctly spelled word.', options: ['Definately', 'Definitely', 'Definitly', 'Defenitely'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'The correct spelling is "Definitely".', source },
  { id: 'cds-english-01-005', section: 'Grammar and Usage', topic: 'Articles', difficulty: 'easy', question: 'Fill in the blank: He is ___ honest man.', options: ['a', 'the', 'an', 'no article needed'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: '"Honest" begins with a silent "h" and a vowel sound, so it takes "an": an honest man.', source },
  { id: 'cds-english-01-006', section: 'Grammar and Usage', topic: 'Voice (Active-Passive)', difficulty: 'medium', question: 'Choose the correct passive voice of: "They are building a bridge."', options: ['A bridge built by them.', 'A bridge was being built by them.', 'A bridge has being built by them.', 'A bridge is being built by them.'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'Present continuous active becomes present continuous passive: A bridge is being built by them.', source },
  { id: 'cds-english-01-007', section: 'Vocabulary and Comprehension', topic: 'Synonyms', difficulty: 'easy', question: 'Choose the word closest in meaning to "Candid".', options: ['Frank', 'Secretive', 'Rude', 'Timid'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: '"Candid" means truthful and straightforward, closest to "Frank".', source },
  { id: 'cds-english-01-008', section: 'Vocabulary and Comprehension', topic: 'Antonyms', difficulty: 'easy', question: 'Choose the word opposite in meaning to "Generous".', options: ['Kind', 'Stingy', 'Charitable', 'Warm'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: '"Generous" means willing to give freely; its opposite is "Stingy".', source },
  { id: 'cds-english-01-009', section: 'Vocabulary and Comprehension', topic: 'One-Word Substitution', difficulty: 'medium', question: 'Choose the word that means "a person who loves and collects books".', options: ['Philatelist', 'Numismatist', 'Bibliophile', 'Bibliographer'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'A "Bibliophile" is a person who loves and collects books.', source },
  { id: 'cds-english-01-010', section: 'Vocabulary and Comprehension', topic: 'Prepositions', difficulty: 'easy', question: 'Fill in the blank: He was deprived ___ his rights.', options: ['with', 'for', 'from', 'of'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'The correct idiomatic preposition is "of": deprived of his rights.', source },
  { id: 'cds-english-01-011', section: 'Vocabulary and Comprehension', topic: 'Idioms and Phrases', difficulty: 'easy', question: 'What does the idiom "to spill the beans" mean?', options: ['To reveal a secret', 'To waste food', 'To cause an argument', 'To make a mistake'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: '"To spill the beans" means to reveal secret or confidential information.', source },
  { id: 'cds-english-01-012', section: 'Vocabulary and Comprehension', topic: 'Spelling', difficulty: 'easy', question: 'Identify the correctly spelled word from the options below.', options: ['Neccessary', 'Necessary', 'Necesary', 'Neccesary'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'The correct spelling is "Necessary", with a single "c" followed by double "s".', source },
];
