import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'Original CDS Elementary Mathematics practice questions in the official 4-option multiple-choice format, covering Arithmetic, Algebra, Trigonometry, Geometry, and Mensuration from the UPSC CDS syllabus.',
  url: 'https://upsc.gov.in/examinations/Combined%20Defence%20Services%20Examination',
  checkedOn: '16 August 2026',
};

export const CDS_ELEMENTARY_MATHEMATICS_1: Question[] = [
  { id: 'cds-elementary-mathematics-01-001', section: 'Arithmetic', topic: 'Profit and Loss', difficulty: 'easy', question: 'An item costing ₹800 is sold at a 20% profit. What is the selling price?', options: ['₹960', '₹900', '₹850', '₹1,000'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'SP = CP × 1.20 = 800 × 1.20 = ₹960.', source },
  { id: 'cds-elementary-mathematics-01-002', section: 'Arithmetic', topic: 'Time and Work', difficulty: 'medium', question: 'A can complete a job in 12 days and B can complete it in 18 days. Working together, how many days will they take?', options: ['6 days', '7.2 days', '8 days', '9 days'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'Combined rate = 1/12 + 1/18 = 3/36 + 2/36 = 5/36. Time = 36/5 = 7.2 days.', source },
  { id: 'cds-elementary-mathematics-01-003', section: 'Arithmetic', topic: 'Time, Speed and Distance', difficulty: 'easy', question: 'A train travels 180 km in 3 hours. What is its average speed?', options: ['50 km/h', '55 km/h', '60 km/h', '65 km/h'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'Speed = Distance / Time = 180 / 3 = 60 km/h.', source },
  { id: 'cds-elementary-mathematics-01-004', section: 'Arithmetic', topic: 'Percentage', difficulty: 'easy', question: '40% of a number is 68. What is the number?', options: ['150', '160', '180', '170'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: '0.40 × x = 68, so x = 68 / 0.40 = 170.', source },
  { id: 'cds-elementary-mathematics-01-005', section: 'Arithmetic', topic: 'Average', difficulty: 'easy', question: 'The average of 5 numbers is 24. What is their sum?', options: ['120', '110', '130', '100'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'Sum = Average × Count = 24 × 5 = 120.', source },
  { id: 'cds-elementary-mathematics-01-006', section: 'Arithmetic', topic: 'Ratio and Proportion', difficulty: 'medium', question: '₹720 is divided among A, B, and C in the ratio 3:4:5. What is C\'s share?', options: ['₹240', '₹300', '₹360', '₹180'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'Total parts = 3+4+5 = 12. Each part = 720/12 = ₹60. C\'s share = 5 × 60 = ₹300.', source },
  { id: 'cds-elementary-mathematics-01-007', section: 'Algebra and Trigonometry', topic: 'Quadratic Equations', difficulty: 'easy', question: 'Solve for x: x² − 7x + 10 = 0. What are the roots?', options: ['x = 1, 10', 'x = 5, -2', 'x = 2, 5', 'x = -2, -5'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'Factoring: x² − 7x + 10 = (x − 2)(x − 5) = 0, so x = 2 or x = 5.', source },
  { id: 'cds-elementary-mathematics-01-008', section: 'Algebra and Trigonometry', topic: 'Algebraic Identities', difficulty: 'medium', question: 'If x + 1/x = 3, find the value of x² + 1/x².', options: ['5', '6', '9', '7'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: '(x + 1/x)² = x² + 2 + 1/x² = 9, so x² + 1/x² = 9 − 2 = 7.', source },
  { id: 'cds-elementary-mathematics-01-009', section: 'Algebra and Trigonometry', topic: 'Algebraic Identities', difficulty: 'easy', question: 'Simplify: (a + b)² − (a − b)².', options: ['4ab', '2ab', 'a² + b²', '4a²b²'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: '(a+b)² − (a−b)² = [a²+2ab+b²] − [a²−2ab+b²] = 4ab.', source },
  { id: 'cds-elementary-mathematics-01-010', section: 'Algebra and Trigonometry', topic: 'Trigonometric Ratios', difficulty: 'easy', question: 'Find the value of tan 45° + cot 45°.', options: ['1', '2', '0', '√2'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'tan 45° = 1 and cot 45° = 1, so the sum is 2.', source },
  { id: 'cds-elementary-mathematics-01-011', section: 'Algebra and Trigonometry', topic: 'Trigonometric Ratios', difficulty: 'medium', question: 'If sin θ = 3/5 and θ is acute, find cos θ.', options: ['3/5', '3/4', '4/5', '5/4'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'sin²θ + cos²θ = 1, so cos²θ = 1 − 9/25 = 16/25, giving cos θ = 4/5.', source },
  { id: 'cds-elementary-mathematics-01-012', section: 'Algebra and Trigonometry', topic: 'Indices', difficulty: 'medium', question: 'Solve for x: 3^(x+1) = 27.', options: ['1', '3', '4', '2'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: '27 = 3³, so x+1 = 3, giving x = 2.', source },
  { id: 'cds-elementary-mathematics-01-013', section: 'Geometry and Mensuration', topic: 'Mensuration (Area)', difficulty: 'easy', question: 'Find the area of a triangle with base 12 cm and height 8 cm.', options: ['48 cm²', '44 cm²', '52 cm²', '40 cm²'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'Area = (1/2) × base × height = (1/2) × 12 × 8 = 48 cm².', source },
  { id: 'cds-elementary-mathematics-01-014', section: 'Geometry and Mensuration', topic: 'Mensuration (Perimeter)', difficulty: 'easy', question: 'Find the perimeter of a rectangle with length 15 cm and breadth 9 cm.', options: ['45 cm', '48 cm', '50 cm', '54 cm'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'Perimeter = 2 × (length + breadth) = 2 × (15+9) = 48 cm.', source },
  { id: 'cds-elementary-mathematics-01-015', section: 'Geometry and Mensuration', topic: 'Mensuration (Volume)', difficulty: 'medium', question: 'Find the volume of a cube with side 5 cm.', options: ['100 cm³', '110 cm³', '125 cm³', '150 cm³'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'Volume = side³ = 5³ = 125 cm³.', source },
  { id: 'cds-elementary-mathematics-01-016', section: 'Geometry and Mensuration', topic: 'Mensuration (Circumference)', difficulty: 'medium', question: 'Find the circumference of a circle with radius 7 cm (use π = 22/7).', options: ['40 cm', '42 cm', '46 cm', '44 cm'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'Circumference = 2πr = 2 × (22/7) × 7 = 44 cm.', source },
  { id: 'cds-elementary-mathematics-01-017', section: 'Geometry and Mensuration', topic: 'Geometry (Triangles)', difficulty: 'easy', question: 'Two angles of a triangle are 50° and 60°. Find the third angle.', options: ['70°', '60°', '80°', '65°'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'The angles of a triangle sum to 180°, so the third angle = 180 − 50 − 60 = 70°.', source },
  { id: 'cds-elementary-mathematics-01-018', section: 'Geometry and Mensuration', topic: 'Mensuration (Area of Circle)', difficulty: 'medium', question: 'Find the area of a circle with radius 14 cm (use π = 22/7).', options: ['600 cm²', '616 cm²', '630 cm²', '588 cm²'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'Area = πr² = (22/7) × 14 × 14 = 616 cm².', source },
];
