import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'Original CDS English practice questions in the official 4-option multiple-choice format, covering grammar, usage, vocabulary, and comprehension from the UPSC CDS syllabus.',
  url: 'https://upsc.gov.in/examinations/Combined%20Defence%20Services%20Examination',
  checkedOn: '16 August 2026',
};

// The 24 September 2026 batch, which took every section of this bank to twelve
// questions so that each sectional test clears the ten-question floor for
// indexing. Same syllabus areas, same format; a separate source entry because
// these were written and answer-checked on that date rather than the original
// one, and a bank should not date questions earlier than they were checked.
const addedSource = { ...source, checkedOn: '24 September 2026' };

export const CDS_ENGLISH_1: Question[] = [
  // Grammar and Usage
  { id: 'cds-english-01-001', section: 'Grammar and Usage', topic: 'Subject-Verb Agreement', difficulty: 'easy', question: 'Choose the grammatically correct sentence.', options: ['Each of the students have a book.', 'Each of the students are having a book.', 'Each of the students has a book.', 'Each of the students having a book.'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: '"Each" is singular, so it takes the singular verb "has": Each of the students has a book.', source },
  { id: 'cds-english-01-002', section: 'Grammar and Usage', topic: 'Prepositions', difficulty: 'easy', question: 'Fill in the blank: He is afraid ___ the dark.', options: ['from', 'by', 'for', 'of'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'The correct idiomatic preposition is "of": He is afraid of the dark.', source },
  { id: 'cds-english-01-003', section: 'Grammar and Usage', topic: 'Conditional Sentences', difficulty: 'medium', question: 'Fill in the blank: If it rains, we ___ the trip.', options: ['will cancel', 'cancel', 'would cancel', 'cancelled'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'In a first conditional sentence, the main clause uses the future simple: "will cancel".', source },
  { id: 'cds-english-01-004', section: 'Grammar and Usage', topic: 'Spelling', difficulty: 'easy', question: 'Choose the correctly spelled word.', options: ['Definately', 'Definitely', 'Definitly', 'Defenitely'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'The correct spelling is "Definitely".', source },
  { id: 'cds-english-01-005', section: 'Grammar and Usage', topic: 'Articles', difficulty: 'easy', question: 'Fill in the blank: He is ___ honest man.', options: ['a', 'the', 'an', 'no article needed'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: '"Honest" begins with a silent "h" and a vowel sound, so it takes "an": an honest man.', source },
  { id: 'cds-english-01-006', section: 'Grammar and Usage', topic: 'Voice (Active-Passive)', difficulty: 'medium', question: 'Choose the correct passive voice of: "They are building a bridge."', options: ['A bridge built by them.', 'A bridge was being built by them.', 'A bridge has being built by them.', 'A bridge is being built by them.'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'Present continuous active becomes present continuous passive: A bridge is being built by them.', source },
  { id: 'cds-english-01-013', section: 'Grammar and Usage', topic: 'Tenses', difficulty: 'medium', question: 'Fill in the blank: The train ___ before we reached the platform.', options: ['had left', 'has left', 'was leaving', 'is leaving'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'The past perfect "had left" marks the earlier of two past actions: the train left first, and we arrived afterwards.', source: addedSource },
  { id: 'cds-english-01-014', section: 'Grammar and Usage', topic: 'Reported Speech', difficulty: 'medium', question: 'Choose the correct indirect form of: He said, "I am writing the examination tomorrow."', options: ['He said that he is writing the examination tomorrow.', 'He said that he was writing the examination the next day.', 'He said that he wrote the examination tomorrow.', 'He said that he has written the examination the next day.'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'In reported speech the present continuous shifts to the past continuous and "tomorrow" becomes "the next day".', source: addedSource },
  { id: 'cds-english-01-015', section: 'Grammar and Usage', topic: 'Question Tags', difficulty: 'easy', question: 'Choose the correct question tag: She rarely misses a class, ___?', options: ['doesn\'t she', 'isn\'t she', 'is she', 'does she'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: '"Rarely" carries a negative sense, so the sentence is treated as negative and takes the positive tag "does she".', source: addedSource },
  { id: 'cds-english-01-016', section: 'Grammar and Usage', topic: 'Degrees of Comparison', difficulty: 'medium', question: 'Choose the sentence that forms its comparative correctly.', options: ['This route is more shorter than the other.', 'This route is the most shortest of the two.', 'This route is shorter than the other.', 'This route is more short than the other.'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'A one-syllable adjective forms its comparative with -er, and it is never combined with "more".', source: addedSource },
  { id: 'cds-english-01-017', section: 'Grammar and Usage', topic: 'Pronoun Case', difficulty: 'easy', question: 'Fill in the blank: The certificates were collected by my brother and ___.', options: ['I', 'myself', 'mine', 'me'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'After the preposition "by" the pronoun takes the object form, so "me" is correct.', source: addedSource },
  { id: 'cds-english-01-018', section: 'Grammar and Usage', topic: 'Adjectives and Adverbs', difficulty: 'medium', question: 'Choose the sentence that uses the adverb correctly.', options: ['He drives careful on the highway.', 'He drives carefully on the highway.', 'He drives careful and slow.', 'He is driving careful today.'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'An adverb modifies the verb "drives", so the -ly form "carefully" is required.', source: addedSource },
  // Vocabulary and Comprehension
  { id: 'cds-english-01-007', section: 'Vocabulary and Comprehension', topic: 'Synonyms', difficulty: 'easy', question: 'Choose the word closest in meaning to "Candid".', options: ['Frank', 'Secretive', 'Rude', 'Timid'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: '"Candid" means truthful and straightforward, closest to "Frank".', source },
  { id: 'cds-english-01-008', section: 'Vocabulary and Comprehension', topic: 'Antonyms', difficulty: 'easy', question: 'Choose the word opposite in meaning to "Generous".', options: ['Kind', 'Stingy', 'Charitable', 'Warm'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: '"Generous" means willing to give freely; its opposite is "Stingy".', source },
  { id: 'cds-english-01-009', section: 'Vocabulary and Comprehension', topic: 'One-Word Substitution', difficulty: 'medium', question: 'Choose the word that means "a person who loves and collects books".', options: ['Philatelist', 'Numismatist', 'Bibliophile', 'Bibliographer'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'A "Bibliophile" is a person who loves and collects books.', source },
  { id: 'cds-english-01-010', section: 'Vocabulary and Comprehension', topic: 'Prepositions', difficulty: 'easy', question: 'Fill in the blank: He was deprived ___ his rights.', options: ['with', 'for', 'from', 'of'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'The correct idiomatic preposition is "of": deprived of his rights.', source },
  { id: 'cds-english-01-011', section: 'Vocabulary and Comprehension', topic: 'Idioms and Phrases', difficulty: 'easy', question: 'What does the idiom "to spill the beans" mean?', options: ['To reveal a secret', 'To waste food', 'To cause an argument', 'To make a mistake'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: '"To spill the beans" means to reveal secret or confidential information.', source },
  { id: 'cds-english-01-012', section: 'Vocabulary and Comprehension', topic: 'Spelling', difficulty: 'easy', question: 'Identify the correctly spelled word from the options below.', options: ['Neccessary', 'Necessary', 'Necesary', 'Neccesary'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'The correct spelling is "Necessary", with a single "c" followed by double "s".', source },
  { id: 'cds-english-01-019', section: 'Vocabulary and Comprehension', topic: 'Synonyms', difficulty: 'easy', question: 'Choose the word closest in meaning to "Obsolete".', options: ['Outdated', 'Modern', 'Valuable', 'Fragile'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: '"Obsolete" means no longer in use, which is closest to "Outdated".', source: addedSource },
  { id: 'cds-english-01-020', section: 'Vocabulary and Comprehension', topic: 'Antonyms', difficulty: 'medium', question: 'Choose the word most nearly opposite in meaning to "Frugal".', options: ['Thrifty', 'Economical', 'Extravagant', 'Careful'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: '"Frugal" means sparing with money, so its opposite is "Extravagant". Thrifty, economical and careful are close in meaning to frugal.', source: addedSource },
  { id: 'cds-english-01-021', section: 'Vocabulary and Comprehension', topic: 'One-Word Substitution', difficulty: 'medium', question: 'Choose the word that means "one who is present everywhere at the same time".', options: ['Omnipotent', 'Omniscient', 'Omnivorous', 'Omnipresent'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: '"Omnipresent" means present everywhere. Omnipotent means all-powerful, omniscient means all-knowing, and omnivorous means eating both plants and meat.', source: addedSource },
  { id: 'cds-english-01-022', section: 'Vocabulary and Comprehension', topic: 'Idioms and Phrases', difficulty: 'easy', question: 'What does the idiom "to keep something at arm\'s length" mean?', options: ['To measure it carefully', 'To avoid becoming closely involved with it', 'To guard it constantly', 'To share it with everyone'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: '"To keep at arm\'s length" means to avoid close involvement or familiarity.', source: addedSource },
  { id: 'cds-english-01-023', section: 'Vocabulary and Comprehension', topic: 'Phrasal Verbs', difficulty: 'medium', question: 'The scheme was rolled out across four districts. The phrasal verb "rolled out" means:', options: ['launched', 'withdrawn', 'reviewed', 'delayed'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: '"Roll out" means to introduce or launch something, usually in stages.', source: addedSource },
  { id: 'cds-english-01-024', section: 'Vocabulary and Comprehension', topic: 'Homophones', difficulty: 'medium', question: 'Choose the sentence that uses the word correctly.', options: ['The soldiers refused to loose their discipline.', 'The lose end of the rope was tied to a post.', 'The knot was too loose to hold the rope.', 'He did not want to loosen the match.'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: '"Loose" is an adjective meaning not tight; "lose" is a verb meaning to misplace or be defeated. A knot that is not tight is loose.', source: addedSource },
];
