import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'Original Joint CSIR-UGC NET Part A General Aptitude practice questions in the official 4-option multiple-choice format, covering logical reasoning, graphical analysis, analytical and numerical ability, series formation and puzzles. Second set, built to the same difficulty mix as the first. Parts B and C are subject-specific and are not covered.',
  url: 'https://csirnet.nta.ac.in/',
  checkedOn: '18 September 2026',
};

export const CSIR_UGC_NET_PART_A_GENERAL_APTITUDE_PRACTICE_2: Question[] = [
  { id: 'csir-ugc-net-pa-02-001', section: 'Part A: General Aptitude', topic: 'Rates of work', difficulty: 'medium', question: 'Three pumps can each fill a tank alone in 10, 15 and 30 hours respectively. How long will the tank take to fill if all three run together?', options: ['5 hours', '6 hours', '7.5 hours', '10 hours'], correctIndex: 0, answerType: 'mcq', marks: 2, negativeMarking: 0, explanation: 'In one hour the pumps fill 1/10 + 1/15 + 1/30 of the tank, which is 6/30, or one fifth. The tank therefore fills in 5 hours.', source },
  { id: 'csir-ugc-net-pa-02-002', section: 'Part A: General Aptitude', topic: 'Clock angles', difficulty: 'medium', question: 'What is the angle between the hour hand and the minute hand of a clock at 3:40?', options: ['120°', '130°', '140°', '150°'], correctIndex: 1, answerType: 'mcq', marks: 2, negativeMarking: 0, explanation: 'The minute hand is at 6 × 40 = 240°. The hour hand is at 30 × 3 + 0.5 × 40 = 110°. The difference is 130°.', source },
  { id: 'csir-ugc-net-pa-02-003', section: 'Part A: General Aptitude', topic: 'Successive percentage change', difficulty: 'easy', question: 'A reading is first increased by 20% and the result is then decreased by 20%. What is the net change from the original reading?', options: ['No change', 'A decrease of 2%', 'A decrease of 4%', 'An increase of 4%'], correctIndex: 2, answerType: 'mcq', marks: 2, negativeMarking: 0, explanation: 'The two steps multiply the reading by 1.2 and then by 0.8, giving 0.96 of the original, which is a decrease of 4%. The percentages do not cancel because the second applies to a larger base.', source },
  { id: 'csir-ugc-net-pa-02-004', section: 'Part A: General Aptitude', topic: 'Set theory', difficulty: 'medium', question: 'In a laboratory of 60 researchers, 35 use technique X, 28 use technique Y and 12 use both. How many use neither?', options: ['3', '5', '7', '9'], correctIndex: 3, answerType: 'mcq', marks: 2, negativeMarking: 0, explanation: 'The number using at least one technique is 35 + 28 − 12, which is 51, so 60 − 51, that is 9, use neither.', source },
  { id: 'csir-ugc-net-pa-02-005', section: 'Part A: General Aptitude', topic: 'Restricted arrangements', difficulty: 'hard', question: 'Five distinct samples are placed in a row. In how many arrangements are two particular samples never next to each other?', options: ['72', '84', '96', '108'], correctIndex: 0, answerType: 'mcq', marks: 2, negativeMarking: 0, explanation: 'There are 5! = 120 arrangements in all. Treating the two samples as one block gives 4! × 2 = 48 arrangements in which they are adjacent, so 120 − 48 = 72 keep them apart.', source },
  { id: 'csir-ugc-net-pa-02-006', section: 'Part A: General Aptitude', topic: 'Graphical analysis', difficulty: 'medium', question: 'A bar chart shows quarterly output of 40, 50, 60 and 75 units. By what percentage does the fourth quarter exceed the average of the first three?', options: ['25%', '50%', '60%', '75%'], correctIndex: 1, answerType: 'mcq', marks: 2, negativeMarking: 0, explanation: 'The average of 40, 50 and 60 is 50. The fourth quarter exceeds it by 25, and 25 as a percentage of 50 is 50%.', source },
  { id: 'csir-ugc-net-pa-02-007', section: 'Part A: General Aptitude', topic: 'Direction sense', difficulty: 'medium', question: 'A field worker walks 6 km north, then 8 km east, then 3 km south, then 4 km west. How far is the worker from the starting point?', options: ['3 km', '4 km', '5 km', '7 km'], correctIndex: 2, answerType: 'mcq', marks: 2, negativeMarking: 0, explanation: 'The net displacement is 3 km north and 4 km east, so the straight-line distance is the square root of 9 + 16, that is 5 km.', source },
  { id: 'csir-ugc-net-pa-02-008', section: 'Part A: General Aptitude', topic: 'Proportional reasoning', difficulty: 'easy', question: 'A reaction consumes 0.6 mol of reactant in 4 minutes. At the same rate, how long will it take to consume 2.1 mol?', options: ['8 minutes', '10 minutes', '12 minutes', '14 minutes'], correctIndex: 3, answerType: 'mcq', marks: 2, negativeMarking: 0, explanation: '2.1 mol is 3.5 times 0.6 mol, so the time is 3.5 × 4, which is 14 minutes.', source },
  { id: 'csir-ugc-net-pa-02-009', section: 'Part A: General Aptitude', topic: 'Calendar reasoning', difficulty: 'medium', question: 'If 1 March in a given year falls on a Sunday, on what day does 1 June of the same year fall?', options: ['Monday', 'Tuesday', 'Wednesday', 'Sunday'], correctIndex: 0, answerType: 'mcq', marks: 2, negativeMarking: 0, explanation: 'March has 31 days, April 30 and May 31, so 1 June is 92 days after 1 March. Since 92 leaves a remainder of 1 on division by 7, the day advances by one, from Sunday to Monday.', source },
  { id: 'csir-ugc-net-pa-02-010', section: 'Part A: General Aptitude', topic: 'Scale and proportion', difficulty: 'easy', question: 'On a map drawn to a scale of 1:50,000, two sampling sites are 6 cm apart. What is the distance between them on the ground?', options: ['1.5 km', '3 km', '5 km', '30 km'], correctIndex: 1, answerType: 'mcq', marks: 2, negativeMarking: 0, explanation: '6 cm on the map represents 6 × 50,000 = 300,000 cm on the ground, and 300,000 cm is 3 km.', source },
  { id: 'csir-ugc-net-pa-02-011', section: 'Part A: General Aptitude', topic: 'Pigeonhole reasoning', difficulty: 'hard', question: 'A drawer holds 10 red, 8 blue and 6 green tokens, drawn one at a time without looking. What is the smallest number of draws that guarantees four tokens of the same colour?', options: ['7', '9', '10', '13'], correctIndex: 2, answerType: 'mcq', marks: 2, negativeMarking: 0, explanation: 'The worst case gives three of each colour, which is 9 tokens with no colour yet reaching four. The tenth draw must be a fourth token of some colour, so 10 draws are enough and 9 are not.', source },
  { id: 'csir-ugc-net-pa-02-012', section: 'Part A: General Aptitude', topic: 'Divisibility', difficulty: 'medium', question: 'What is the smallest integer greater than 2 that leaves a remainder of 2 when divided by 3, by 4 and by 5?', options: ['32', '47', '60', '62'], correctIndex: 3, answerType: 'mcq', marks: 2, negativeMarking: 0, explanation: 'A number leaving remainder 2 on all three divisions is 2 more than a common multiple of 3, 4 and 5. The least such multiple is 60, so the number is 62.', source },
  { id: 'csir-ugc-net-pa-02-013', section: 'Part A: General Aptitude', topic: 'Averages', difficulty: 'easy', question: 'The average of 8 readings is 21. One reading of 15 is found to be wrong and is replaced by 31. What is the corrected average?', options: ['21', '22', '23', '24'], correctIndex: 2, answerType: 'mcq', marks: 2, negativeMarking: 0, explanation: 'The total rises by 31 − 15, that is 16, from 168 to 184. Dividing by 8 gives 23.', source },
  { id: 'csir-ugc-net-pa-02-014', section: 'Part A: General Aptitude', topic: 'Probability without replacement', difficulty: 'medium', question: 'A box holds 15 good and 5 defective components. Two are drawn at random without replacement. What is the probability that both are good?', options: ['1/2', '21/38', '9/16', '3/4'], correctIndex: 1, answerType: 'mcq', marks: 2, negativeMarking: 0, explanation: 'The first draw is good with probability 15/20 and the second with probability 14/19, so the probability of both is 15/20 × 14/19, which reduces to 21/38.', source },
  { id: 'csir-ugc-net-pa-02-015', section: 'Part A: General Aptitude', topic: 'Logical deduction', difficulty: 'medium', question: 'Exactly one of three technicians P, Q and R calibrated an instrument. P says "Q did it." Q says "I did not do it." R says "P did not do it." If exactly one of the three statements is true, who calibrated the instrument?', options: ['P', 'Q', 'R', 'It cannot be determined from the statements'], correctIndex: 0, answerType: 'mcq', marks: 2, negativeMarking: 0, explanation: 'If P did it, then P\'s statement is false, Q\'s is true and R\'s is false, which is exactly one true statement. If Q did it, P and R both speak truly, and if R did it, Q and R both speak truly, so only P fits the condition.', source },
];
