import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'Original FRM Part I Quantitative Analysis practice questions in the official 4-option multiple-choice format, covering probability, distributions, and regression topics that are independently verifiable by calculation.',
  url: 'https://www.garp.org/frm/program-exams',
  checkedOn: '15 August 2026',
};

export const FRM_PART_1_QUANTITATIVE_ANALYSIS_1: Question[] = [
  { id: 'frm-part-1-quantitative-analysis-01-001', section: 'Probability and Distributions', topic: 'Basic Probability', difficulty: 'easy', question: 'A fair six-sided die is rolled twice. What is the probability that the sum of the two rolls equals 7?', options: ['1/6', '1/12', '1/9', '5/36'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'There are 6 outcomes that sum to 7 out of 36 total outcomes: 6/36 = 1/6.', source },
  { id: 'frm-part-1-quantitative-analysis-01-002', section: 'Probability and Distributions', topic: 'Conditional Probability', difficulty: 'hard', question: 'In a portfolio, 40% of assets are bonds and 60% are equities. 10% of bonds default and 5% of equities default. What is the probability that a randomly selected defaulted asset is a bond?', options: ['3/7', '4/7', '1/2', '2/3'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'By Bayes\' theorem: (0.10 × 0.40) / (0.10 × 0.40 + 0.05 × 0.60) = 0.04 / 0.07 = 4/7.', source },
  { id: 'frm-part-1-quantitative-analysis-01-003', section: 'Probability and Distributions', topic: 'Expected Value', difficulty: 'easy', question: 'A discrete random variable X takes values 1, 2, and 3 with probabilities 0.2, 0.5, and 0.3 respectively. What is E[X]?', options: ['2.0', '2.3', '2.1', '1.9'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'E[X] = 1(0.2) + 2(0.5) + 3(0.3) = 0.2 + 1.0 + 0.9 = 2.1.', source },
  { id: 'frm-part-1-quantitative-analysis-01-004', section: 'Probability and Distributions', topic: 'Variance', difficulty: 'medium', question: 'Using the same random variable X (values 1, 2, 3 with probabilities 0.2, 0.5, 0.3), what is Var(X)?', options: ['0.39', '0.59', '0.29', '0.49'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'E[X²] = 1(0.2) + 4(0.5) + 9(0.3) = 0.2 + 2.0 + 2.7 = 4.9. Var(X) = E[X²] − (E[X])² = 4.9 − 2.1² = 4.9 − 4.41 = 0.49.', source },
  { id: 'frm-part-1-quantitative-analysis-01-005', section: 'Probability and Distributions', topic: 'Binomial Distribution', difficulty: 'medium', question: 'A risk analyst estimates that each of 5 independent loans has a 20% probability of default. What is the probability that exactly 2 of the 5 loans default?', options: ['0.2048', '0.1024', '0.4096', '0.0512'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Using the binomial formula: C(5,2) × 0.2² × 0.8³ = 10 × 0.04 × 0.512 = 0.2048.', source },
  { id: 'frm-part-1-quantitative-analysis-01-006', section: 'Probability and Distributions', topic: 'Normal Distribution', difficulty: 'easy', question: 'A portfolio\'s returns are normally distributed with a mean of 8% and a standard deviation of 5%. What is the z-score for a return of 3%?', options: ['-0.6', '-1', '1', '-2'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'z = (3 − 8) / 5 = −1.', source },
  { id: 'frm-part-1-quantitative-analysis-01-007', section: 'Probability and Distributions', topic: 'Covariance and Correlation', difficulty: 'medium', question: 'Two assets have Cov(X,Y) = 0.002, σX = 0.05, and σY = 0.08. What is the correlation coefficient between X and Y?', options: ['0.4', '0.8', '0.5', '0.25'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'ρ = Cov(X,Y) / (σX × σY) = 0.002 / (0.05 × 0.08) = 0.002 / 0.004 = 0.5.', source },
  { id: 'frm-part-1-quantitative-analysis-01-008', section: 'Probability and Distributions', topic: 'Combining Variances', difficulty: 'medium', question: 'Two independent asset returns have variances of 0.0025 and 0.0016. What is the variance of their sum?', options: ['0.0009', '0.0020', '0.0064', '0.0041'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'For independent variables, Var(X+Y) = Var(X) + Var(Y) = 0.0025 + 0.0016 = 0.0041.', source },
  { id: 'frm-part-1-quantitative-analysis-01-009', section: 'Probability and Distributions', topic: 'Poisson Distribution', difficulty: 'hard', question: 'The number of loan defaults in a portfolio follows a Poisson distribution with a mean of 3 defaults per year. What is the probability of exactly 0 defaults in a year? (e ≈ 2.71828)', options: ['0.0498', '0.1494', '0.2231', '0.0183'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'For a Poisson distribution, P(X=0) = e^(−λ) = e^(−3) ≈ 0.0498.', source },
  { id: 'frm-part-1-quantitative-analysis-01-010', section: 'Probability and Distributions', topic: 'Complementary Probability', difficulty: 'medium', question: 'Two independent bonds each have a default probability of 0.1. What is the probability that at least one of them defaults?', options: ['0.10', '0.19', '0.20', '0.01'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'P(at least one) = 1 − P(neither defaults) = 1 − (0.9 × 0.9) = 1 − 0.81 = 0.19.', source },
  { id: 'frm-part-1-quantitative-analysis-01-011', section: 'Regression and Estimation', topic: 'Regression Slope', difficulty: 'medium', question: 'In a simple linear regression, Cov(X,Y) = 0.0032 and Var(X) = 0.0016. What is the estimated slope coefficient?', options: ['2', '0.5', '4', '1.5'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The slope estimate is Cov(X,Y) / Var(X) = 0.0032 / 0.0016 = 2.', source },
  { id: 'frm-part-1-quantitative-analysis-01-012', section: 'Regression and Estimation', topic: 'Regression Intercept', difficulty: 'medium', question: 'A regression line has a slope of 2. The mean of Y is 0.10 and the mean of X is 0.03. What is the estimated intercept?', options: ['0.06', '0.04', '0.10', '0.02'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The intercept is ȳ − (slope × x̄) = 0.10 − (2 × 0.03) = 0.10 − 0.06 = 0.04.', source },
  { id: 'frm-part-1-quantitative-analysis-01-013', section: 'Regression and Estimation', topic: 'R-Squared', difficulty: 'easy', question: 'A regression has a correlation coefficient of 0.6 between X and Y. What is the R² of the regression?', options: ['0.60', '0.30', '0.36', '0.12'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'R² is the square of the correlation coefficient: 0.6² = 0.36.', source },
  { id: 'frm-part-1-quantitative-analysis-01-014', section: 'Regression and Estimation', topic: 'Sample Mean', difficulty: 'easy', question: 'A sample of 5 portfolio returns is: 2%, 4%, 6%, 8%, 10%. What is the sample mean?', options: ['5%', '7%', '6.5%', '6%'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Mean = (2 + 4 + 6 + 8 + 10) / 5 = 30 / 5 = 6%.', source },
  { id: 'frm-part-1-quantitative-analysis-01-015', section: 'Regression and Estimation', topic: 'Sample Standard Deviation', difficulty: 'hard', question: 'Using the same sample (2%, 4%, 6%, 8%, 10%, mean 6%), what is the sample standard deviation using the unbiased (n−1) formula?', options: ['3.16%', '2.83%', '2.00%', '4.00%'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Squared deviations from the mean are 16, 4, 0, 4, 16, summing to 40. Dividing by (n−1)=4 gives a variance of 10, and √10 ≈ 3.16.', source },
  { id: 'frm-part-1-quantitative-analysis-01-016', section: 'Regression and Estimation', topic: 'Standard Error of the Mean', difficulty: 'medium', question: 'A sample of 25 observations has a sample standard deviation of 10. What is the standard error of the sample mean?', options: ['0.4', '2', '10', '4'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Standard error = sample standard deviation / √n = 10 / √25 = 10 / 5 = 2.', source },
  { id: 'frm-part-1-quantitative-analysis-01-017', section: 'Regression and Estimation', topic: 'Confidence Intervals', difficulty: 'medium', question: 'A sample mean is 5% with a standard error of 1%. Using a z-value of 1.96 for a 95% confidence interval, what is the upper bound of the interval?', options: ['6.00%', '5.96%', '6.96%', '7.96%'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Upper bound = sample mean + (z × standard error) = 5% + (1.96 × 1%) = 6.96%.', source },
  { id: 'frm-part-1-quantitative-analysis-01-018', section: 'Regression and Estimation', topic: 'Hypothesis Testing', difficulty: 'medium', question: 'A hypothesis test has a sample mean of 3%, a hypothesized population mean of 0%, and a standard error of 1.5%. What is the t-statistic?', options: ['3', '1.5', '4.5', '2'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 't = (sample mean − hypothesized mean) / standard error = (3 − 0) / 1.5 = 2.', source },
  { id: 'frm-part-1-quantitative-analysis-01-019', section: 'Regression and Estimation', topic: 'Degrees of Freedom', difficulty: 'medium', question: 'A regression is estimated using 30 observations with 2 independent variables plus an intercept. How many degrees of freedom does the residual term have?', options: ['27', '28', '29', '30'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Residual degrees of freedom = n − k − 1 = 30 − 2 − 1 = 27, where k is the number of independent variables.', source },
  { id: 'frm-part-1-quantitative-analysis-01-020', section: 'Regression and Estimation', topic: 'Correlation Coefficient', difficulty: 'medium', question: 'A simple linear regression has an R² of 0.81. If the slope coefficient is positive, what is the correlation coefficient between X and Y?', options: ['0.81', '0.9', '0.66', '0.95'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The correlation coefficient is the square root of R², signed to match the slope: √0.81 = 0.9, positive since the slope is positive.', source },
];
