import type { Question } from '../questions';

const SOURCE = {
  kind: 'original' as const,
  reference: 'TakeMockTest original practice aligned to the IBPS PO XVI Mains Reasoning section',
  url: 'https://www.ibps.in/wp-content/uploads/Detailed-Notification_CRP-PO-XVI_Final_V1_30.06.2026.pdf',
  checkedOn: '23 August 2026',
};

const MARKS = 60 / 40;
const PENALTY = MARKS / 4;

function question(
  id: string,
  topic: string,
  difficulty: 'easy' | 'medium' | 'hard',
  prompt: string,
  options: string[],
  correctIndex: number,
  explanation: string,
): Question {
  return {
    id,
    section: 'Reasoning',
    topic,
    difficulty,
    question: prompt,
    options,
    correctIndex,
    marks: MARKS,
    negativeMarking: PENALTY,
    explanation,
    source: SOURCE,
  };
}

export const IBPS_PO_MAINS_REASONING_2: Question[] = [
  question('ibps-po-m-re2-001', 'Syllogism', 'medium', 'Statements: All rivers are streams. No stream is a lake. Conclusions: I. No river is a lake. II. Some streams are rivers. Which conclusion(s) follow?', ['Both I and II follow', 'Only I follows', 'Only II follows', 'Neither follows'], 0, 'Since all rivers are streams and no stream is a lake, no river can be a lake, so I follows. "All rivers are streams" also converts validly to "Some streams are rivers", so II follows too.'),
  question('ibps-po-m-re2-002', 'Syllogism', 'medium', 'Statements: Some chairs are tables. All tables are furniture. Conclusions: I. Some chairs are furniture. II. All furniture is tables. Which conclusion(s) follow?', ['Only II follows', 'Only I follows', 'Both I and II follow', 'Neither follows'], 1, 'Some chairs are tables and all tables are furniture, so some chairs are furniture (I). The relationship does not establish that all furniture is tables (II), only that tables are a subset of furniture.'),
  question('ibps-po-m-re2-003', 'Syllogism', 'hard', 'Statements: No doctor is an engineer. All engineers are graduates. Conclusions: I. No graduate is a doctor. II. Some graduates are not doctors. Which conclusion(s) follow?', ['Only I follows', 'Both I and II follow', 'Only II follows', 'Neither follows'], 2, 'No doctor is an engineer, and all engineers are graduates, so at least the graduates who are engineers are definitely not doctors, giving II. I over-generalises to all graduates, which is not guaranteed.'),
  question('ibps-po-m-re2-004', 'Syllogism', 'medium', 'Statements: All cups are plates. Some plates are bowls. Conclusions: I. Some bowls are cups. II. Some plates are cups. Which conclusion(s) follow?', ['Only I follows', 'Both I and II follow', 'Neither follows', 'Only II follows'], 3, 'All cups are plates guarantees some plates are cups (II, by conversion of a universal affirmative). The bowl connection to cups is not established, so I does not follow.'),
  question('ibps-po-m-re2-005', 'Coded inequalities', 'medium', "If P < Q ≤ R = S and S < T, what is the relationship between P and T?", ['P < T', 'P > T', 'P = T', 'Cannot be determined'], 0, 'P < Q ≤ R = S < T chains to P < T, since P is strictly less than everything up the chain to T.'),
  question('ibps-po-m-re2-006', 'Coded inequalities', 'hard', 'If A ≤ B < C = D and D ≤ E, what is the relationship between A and E?', ['Cannot be determined', 'A < E', 'A > E', 'A = E'], 1, 'A ≤ B < C = D ≤ E: since B < C strictly and A ≤ B, A is strictly less than everything from C up to E, so A < E.'),
  question('ibps-po-m-re2-007', 'Coded inequalities', 'medium', 'If M > N ≥ O and O > P, is M > P definitely true?', ['No', 'Cannot be determined', 'Yes', 'Only if M = O'], 2, 'M > N ≥ O > P means M is strictly greater than N, and N is at least O, and O is strictly greater than P, so M > P is definitely true.'),
  question('ibps-po-m-re2-008', 'Coding-decoding', 'medium', 'In a certain code, "office team win" is written as "lo mi ta", "team more strong" is written as "mi pa fa", and "win strong goal" is written as "lo fa go". What is the code for "win"?', ['mi', 'ta', 'fa', 'lo'], 3, '"Win" appears in the first and third statements, which share only the code "lo", so "lo" codes for "win".'),
  question('ibps-po-m-re2-009', 'Coding-decoding', 'hard', 'In a code, "steel bronze copper" is "de fa ka", "copper iron zinc" is "ka la ma", and "zinc steel wood" is "ma de na". What is the code for "steel"?', ['de', 'fa', 'ka', 'la'], 0, '"Steel" appears in the first and third statements, which share only the code "de", so "de" codes for "steel".'),
  question('ibps-po-m-re2-010', 'Coding-decoding', 'medium', 'If in a certain language MOUSE is coded as 13-15-21-19-5 (each letter by its alphabet position), how is TABLE coded?', ['20-1-12-2-5', '20-1-2-12-5', '2-1-20-12-5', '20-2-1-12-5'], 1, 'T=20, A=1, B=2, L=12, E=5, giving the code 20-1-2-12-5.'),
  question('ibps-po-m-re2-011', 'Blood relations', 'hard', "Pointing to a photograph, Kiran (who has no siblings) said, \"The person in this photo is the daughter of my grandmother's only son.\" How is the person in the photo related to Kiran, if Kiran is female?", ['Her cousin', 'Her aunt', 'Kiran herself', 'Her niece'], 2, "Kiran's grandmother's only son is Kiran's father (since Kiran has no siblings and is presumably his child); his daughter is Kiran herself."),
  question('ibps-po-m-re2-012', 'Blood relations', 'medium', "In a family, X's mother's father is Y. Y has only one son, Z. How is Z related to X?", ['Grandfather', 'Father', 'Cousin', 'Maternal uncle'], 3, "Y is X's maternal grandfather, and Z is Y's only son, which makes Z the brother of X's mother, that is, X's maternal uncle."),
  question('ibps-po-m-re2-013', 'Blood relations', 'medium', "A's father is B. B has two children, A and C. C's daughter is D. How is D related to A?", ['Niece', 'Nephew', 'Sister', 'Cousin'], 0, "C is A's sibling, and D is C's daughter, which makes D the niece of A."),
  question('ibps-po-m-re2-014', 'Direction sense', 'medium', 'A person walks 10 km east, then 6 km north, then 10 km west. How far and in which direction is he from the starting point?', ['10 km, north', '6 km, north', '16 km, east', '6 km, south'], 1, 'The eastward and westward legs of 10 km cancel out, leaving only the 6 km northward leg, so he is 6 km north of the starting point.'),
  question('ibps-po-m-re2-015', 'Direction sense', 'hard', 'Facing east, a person turns 90 degrees clockwise, then 180 degrees anticlockwise, then 90 degrees clockwise. Which direction does the person face now?', ['North', 'West', 'East', 'South'], 2, 'Starting east: +90° clockwise → south; +180° anticlockwise → north; +90° clockwise → east. The person ends up facing east again.'),
  question('ibps-po-m-re2-016', 'Ranking', 'medium', 'In a line of 50 people, Vivek is 18th from the front. If 5 people join the line in front of him, what is his new position from the front?', ['21st', '22nd', '24th', '23rd'], 3, '17 people were originally ahead of Vivek. Adding 5 more people in front increases this to 22, so his new position is 22 + 1 = 23rd.'),
  question('ibps-po-m-re2-017', 'Ranking', 'medium', 'In a class of 48 students, Anjali ranks 15th from the bottom. What is her rank from the top?', ['34th', '33rd', '35th', '32nd'], 0, 'Rank from top = total students − rank from bottom + 1 = 48 − 15 + 1 = 34th.'),
  question('ibps-po-m-re2-018', 'Data sufficiency', 'medium', 'What is the value of x? Statement I: x is a prime number less than 10. Statement II: x is an odd number. Which statement(s) are sufficient?', ['Statement I alone is sufficient', 'Both statements together are still not sufficient', 'Statement II alone is sufficient', 'Both statements together are sufficient, but neither alone'], 1, 'Statement I alone allows x to be 2, 3, 5, or 7. Statement II alone allows any odd number. Combined, x could still be 3, 5, or 7 — more than one value, so it remains insufficient.'),
  question('ibps-po-m-re2-019', 'Data sufficiency', 'medium', 'Is P greater than Q? Statement I: P = R + 5. Statement II: Q = R − 3. Which statement(s) are sufficient?', ['Statement I alone is sufficient', 'Statement II alone is sufficient', 'Both statements together are sufficient, but neither alone', 'Neither statement is sufficient even together'], 2, 'Neither statement alone compares P and Q directly, but together, P − Q = (R+5) − (R−3) = 8, which is always positive, so P is definitely greater than Q.'),
  question('ibps-po-m-re2-020', 'Data sufficiency', 'hard', 'What is the two-digit number? Statement I: The number is a multiple of 7. Statement II: The sum of its digits is 8. Which statement(s) are sufficient?', ['Statement I alone is sufficient', 'Statement II alone is sufficient', 'Neither statement is sufficient even together', 'Both statements together are sufficient, but neither alone'], 3, 'Statement I alone allows many two-digit multiples of 7. Statement II alone allows many numbers with digit sum 8. Combined, only 35 (a multiple of 7 whose digits sum to 8) satisfies both, giving a unique answer.'),
  question('ibps-po-m-re2-021', 'Statement and assumption', 'medium', 'Statement: "All employees are requested to submit their annual health checkup reports by the end of this month." Which assumption is implicit in this statement?', ['Yes, it is implicit that employees have access to get a health checkup done within the month', 'No, it is not implicit', 'Cannot be determined', 'The statement contradicts the assumption'], 0, 'An instruction with a monthly deadline implicitly assumes the recipients are able to arrange the checkup and meet it within that time.'),
  question('ibps-po-m-re2-022', 'Statement and assumption', 'medium', 'Statement: "Passengers are advised to arrive at the airport at least two hours before departure." Which assumption is implicit?', ['No, it is not implicit', 'Yes, it is implicit that passengers can arrange to reach the airport that early', 'Cannot be determined', 'The statement contradicts the assumption'], 1, 'The advisory assumes that passengers are able to plan their travel to arrive at the airport within the recommended time.'),
  question('ibps-po-m-re2-023', 'Statement and conclusion', 'medium', 'Statement: A company introduced a four-day work week on a trial basis, and employee-reported stress levels dropped in the following survey. Which conclusion is most reasonable?', ['The company will fire all remaining staff', 'All employees now work only four days permanently', 'The four-day work week likely reduced some employee stress', 'Stress levels never change regardless of policy'], 2, 'The statement links an intervention (the trial) to a specific, related outcome (a drop in reported stress), supporting a cautious causal reading, not the absolute claims in the other options.'),
  question('ibps-po-m-re2-024', 'Statement and conclusion', 'medium', 'Event I: A firmware update was pushed to all smart thermostats overnight. Event II: The next morning, several users reported unusual temperature readings. What is the most reasonable relationship?', ['Event I and Event II are unrelated', 'Event II caused Event I', 'Event I prevented Event II', 'Event II may be a consequence of Event I'], 3, 'A system-wide update immediately followed by widespread reports of unusual readings is plausibly connected, making Event II a likely consequence of Event I.'),
  question('ibps-po-m-re2-025', 'Seating arrangement', 'medium', "Five colleagues A, B, C, D and E sit in a row facing north. B sits second from the right. C sits immediately left of B. D sits at the left end. A sits immediately right of D. Who sits at the right end?", ['E', 'C', 'A', 'D'], 0, 'D is at position 1 and A, immediately right of D, is at position 2. B is second from the right, position 4, and C, immediately left of B, is at position 3. That leaves only position 5, the right end, for E.'),
  question('ibps-po-m-re2-026', 'Seating arrangement', 'hard', 'Six friends P, Q, R, S, T and U sit around a circular table facing the centre. P sits opposite S. Q sits immediately right of P. R sits immediately left of P. T sits opposite Q. Who sits opposite R?', ['T', 'U', 'S', 'Q'], 1, 'With six people around a circle, opposite pairs are fixed: P–S and Q–T are given, which leaves R and U as the remaining pair, so U sits opposite R.'),
  question('ibps-po-m-re2-027', 'Number series', 'medium', 'Find the next term: 4, 9, 19, 39, 79, ?', ['149', '155', '159', '163'], 2, 'Each term is double the previous term plus 1: 79 × 2 + 1 = 159.'),
  question('ibps-po-m-re2-028', 'Number series', 'medium', 'Find the next term: 3, 7, 15, 31, 63, ?', ['119', '123', '125', '127'], 3, 'Each term is double the previous term plus 1: 63 × 2 + 1 = 127.'),
  question('ibps-po-m-re2-029', 'Number series', 'hard', 'Find the missing term: 5, 8, 14, 26, 50, ?', ['98', '94', '102', '90'], 0, 'Each difference doubles: 3, 6, 12, 24, so the next difference is 48, giving 50 + 48 = 98.'),
  question('ibps-po-m-re2-030', 'Number series', 'medium', 'Find the next term: 2, 3, 7, 16, 32, ?', ['54', '57', '60', '63'], 1, 'The differences are 1, 4, 9, 16 (perfect squares), so the next difference is 25, giving 32 + 25 = 57.'),
  question('ibps-po-m-re2-031', 'Alphanumeric series', 'medium', 'In the arrangement "M 5 T # J 8 P @ 3 N", how many symbols are immediately followed by a letter?', ['0', '2', '1', '3'], 2, 'The symbols are "#" and "@". "#" is immediately followed by J, a letter, so it qualifies. "@" is immediately followed by 3, not a letter, so it does not. Exactly 1 symbol qualifies.'),
  question('ibps-po-m-re2-032', 'Alphanumeric series', 'medium', 'In the arrangement "7 C % D 9 X & Y 4 K", how many symbols are immediately preceded by a letter?', ['0', '1', '3', '2'], 3, 'Scanning: "%" is preceded by C (a letter), and "&" is preceded by X (a letter). Both symbols qualify, giving a count of 2.'),
  question('ibps-po-m-re2-033', 'Alphanumeric series', 'easy', 'In the word arrangement "PLANET", if all letters are arranged in alphabetical order, which letter occupies the fourth position?', ['N', 'L', 'P', 'E'], 0, 'Alphabetical order of P, L, A, N, E, T is A, E, L, N, P, T — the fourth letter is N.'),
  question('ibps-po-m-re2-034', 'Analogy', 'easy', 'Choose the pair that has the same relationship as Doctor : Hospital.', ['Patient : Hospital', 'Teacher : School', 'Nurse : Hospital', 'School : Classroom'], 1, 'A doctor typically works at a hospital, just as a teacher typically works at a school, so the relationship is one of profession to workplace.'),
  question('ibps-po-m-re2-035', 'Analogy', 'medium', 'Choose the pair that has the same relationship as Painter : Painting.', ['Symphony : Orchestra', 'Orchestra : Composer', 'Composer : Symphony', 'Music : Instrument'], 2, 'A painter creates a painting; similarly, a composer creates a symphony — both are creator-to-creation pairs.'),
  question('ibps-po-m-re2-036', 'Input-output', 'hard', 'A word-and-number arrangement machine rearranges any input by first listing all words in alphabetical order, followed by all numbers in descending order. Applying this rule to the input "17 mountain 4 river 22 stone", what is the output?', ['22 17 4 mountain river stone', 'mountain river stone 4 17 22', 'river mountain stone 22 17 4', 'mountain river stone 22 17 4'], 3, 'The words mountain, river and stone sorted alphabetically give mountain, river, stone. The numbers 17, 4 and 22 sorted descending give 22, 17, 4. Combined: "mountain river stone 22 17 4".'),
  question('ibps-po-m-re2-037', 'Input-output', 'medium', 'A number-sorting machine rearranges a given list into ascending order in one step. Input: "33 8 51 19 6". What is the output?', ['6 8 19 33 51', '51 33 19 8 6', '8 6 19 33 51', '6 8 19 51 33'], 0, 'Sorting 33, 8, 51, 19, 6 in ascending order gives 6, 8, 19, 33, 51.'),
  question('ibps-po-m-re2-038', 'Puzzle', 'hard', 'Four colleagues W, X, Y and Z have different salaries. W earns more than X but less than Y. Z earns less than X. Who earns the least?', ['W', 'Z', 'Y', 'X'], 1, 'From Y > W > X > Z, Z earns the least among the four.'),
  question('ibps-po-m-re2-039', 'Puzzle', 'medium', 'In a family, M is the spouse of N. O and P are the children of M and N. Q is the child of O. Based only on the information given, how many grandchildren do M and N have?', ['Two', 'Three', 'One', 'Cannot be determined'], 2, "Only O's child, Q, is mentioned. P's children, if any, are not mentioned, so based on the given information, M and N have exactly one known grandchild."),
  question('ibps-po-m-re2-040', 'Puzzle', 'medium', 'Three containers of different capacities are compared: Container A holds more than Container B. Container C holds less than Container B. Which container holds the least?', ['A', 'B', 'Cannot be determined', 'C'], 3, 'From A > B > C, Container C holds the least of the three.'),
];
