import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'IBPS Specialist Officer CRP SPL-XV official advertisement — Mains, Reasoning section (IT Officer)',
  url: 'https://www.ibps.in/wp-content/uploads/Detailed-Advt.-CRP-SPL-XV_Final1.pdf',
  checkedOn: '27 August 2026',
};

const SEATING_PUZZLE =
  'Six colleagues M, N, O, P, Q, and R sit around a circular table facing the centre, not necessarily in that order. N sits third to the right of M. O sits immediate right of N. P sits immediate right of O. Q sits immediate right of M.\n\n';

export const IBPS_SO_MAINS_REASONING_1: Question[] = [
  { id: 'ibps-so-m1-re-001', section: 'Reasoning', topic: 'Circular seating arrangement', difficulty: 'hard', question: `${SEATING_PUZZLE}Who sits immediate right of Q?`, options: ['R', 'N', 'O', 'P'], correctIndex: 0, explanation: 'Placing M at position 1, N (third to the right) is at position 4, O (immediate right of N) at 5, P (immediate right of O) at 6, and Q (immediate right of M) at 2. The remaining position 3 is R. R sits immediate right of Q.', source },
  { id: 'ibps-so-m1-re-002', section: 'Reasoning', topic: 'Circular seating arrangement', difficulty: 'hard', question: `${SEATING_PUZZLE}Who sits directly opposite M?`, options: ['N', 'O', 'P', 'R'], correctIndex: 0, explanation: 'With six seats, the person directly opposite is three positions away. Since N is third to the right of M, N sits directly opposite M.', source },
  { id: 'ibps-so-m1-re-003', section: 'Reasoning', topic: 'Circular seating arrangement', difficulty: 'hard', question: `${SEATING_PUZZLE}How many people sit between N and P, counting the shorter way around?`, options: ['1', '2', '0', '3'], correctIndex: 0, explanation: 'The final arrangement (clockwise) is M, Q, R, N, O, P. Going from N to P the short way (through O), only O sits between them — 1 person.', source },
  { id: 'ibps-so-m1-re-004', section: 'Reasoning', topic: 'Circular seating arrangement', difficulty: 'hard', question: `${SEATING_PUZZLE}Who sits second to the left of R?`, options: ['M', 'Q', 'N', 'O'], correctIndex: 0, explanation: 'The final arrangement (clockwise) is M, Q, R, N, O, P. Moving two positions to the left (counter-clockwise) from R lands on M.', source },
  { id: 'ibps-so-m1-re-005', section: 'Reasoning', topic: 'Syllogism', difficulty: 'hard', question: 'Statements: All coins are notes. Some notes are cards. Conclusions: I. Some coins are cards. II. Some cards are coins. Which conclusion(s) follow?', options: ['Neither follows', 'Only I follows', 'Only II follows', 'Both follow'], correctIndex: 0, explanation: 'The "some notes that are cards" could be entirely outside the subset of notes that are coins, so neither conclusion is guaranteed to follow.', source },
  { id: 'ibps-so-m1-re-006', section: 'Reasoning', topic: 'Syllogism', difficulty: 'hard', question: 'Statements: No table is a chair. All chairs are stools. Conclusions: I. No table is a stool. II. Some stools are chairs. Which conclusion(s) follow?', options: ['Only II follows', 'Only I follows', 'Both follow', 'Neither follows'], correctIndex: 0, explanation: 'Since chairs exist within stools, some stools are chairs (II follows). Tables could still overlap with the non-chair stools, so "no table is a stool" (I) does not necessarily follow.', source },
  { id: 'ibps-so-m1-re-007', section: 'Reasoning', topic: 'Syllogism', difficulty: 'medium', question: 'Statements: All doctors are surgeons. All surgeons are professionals. Conclusions: I. All doctors are professionals. II. Some professionals are doctors. Which conclusion(s) follow?', options: ['Both I and II follow', 'Only I follows', 'Only II follows', 'Neither follows'], correctIndex: 0, explanation: 'Since doctors are a subset of surgeons, who are a subset of professionals, all doctors are professionals (I), and since doctors exist within professionals, some professionals are doctors (II).', source },
  { id: 'ibps-so-m1-re-008', section: 'Reasoning', topic: 'Blood relations', difficulty: 'hard', question: 'Pointing to a photograph, a man said, "She is the daughter of my father\'s only son." If the man has no brothers, how is the girl related to him?', options: ['Sister', 'Niece', 'Wife', 'Daughter'], correctIndex: 3, explanation: "Since the man has no brothers, he is his father's only son. So the girl, the daughter of the father's only son, is the man's own daughter.", source },
  { id: 'ibps-so-m1-re-009', section: 'Reasoning', topic: 'Blood relations', difficulty: 'hard', question: 'A is the father of B. C is the daughter of B. D is the brother of C. How is A related to D?', options: ['Father', 'Uncle', 'Grandfather', 'Brother'], correctIndex: 2, explanation: 'D, being the brother of C, is also a child of B. Since A is the father of B, A is the grandfather of D.', source },
  { id: 'ibps-so-m1-re-010', section: 'Reasoning', topic: 'Direction sense', difficulty: 'medium', question: 'A person walks 12 km East, then turns South and walks 5 km, then turns West and walks 12 km. How far, and in which direction, is he from his starting point?', options: ['12 km, South', '5 km, South', '5 km, North', '17 km, South'], correctIndex: 1, explanation: 'The East (12 km) and West (12 km) legs cancel out, leaving him 5 km South of the starting point.', source },
  { id: 'ibps-so-m1-re-011', section: 'Reasoning', topic: 'Direction sense', difficulty: 'medium', question: 'Town Q is 15 km north of Town P. Town R is 8 km east of Town Q. Find the distance between P and R.', options: ['19 km', '15 km', '21 km', '17 km'], correctIndex: 3, explanation: 'P to Q (15 km) and Q to R (8 km) form a right angle. Distance PR = √(15² + 8²) = √289 = 17 km.', source },
  { id: 'ibps-so-m1-re-012', section: 'Reasoning', topic: 'Coding-decoding', difficulty: 'hard', question: "In a certain code, FRIEND is written as EQHDMC (each letter shifted one place backward). How is TEACHER written in the same code?", options: ['SDZBGDR', 'SDYBGDQ', 'SDZBGDQ', 'SDZBFDQ'], correctIndex: 2, explanation: 'Shifting each letter backward by one: T→S, E→D, A→Z, C→B, H→G, E→D, R→Q, giving SDZBGDQ.', source },
  { id: 'ibps-so-m1-re-013', section: 'Reasoning', topic: 'Coding-decoding', difficulty: 'hard', question: "In a certain code, alternating letters are shifted +1 then -1 (starting with +1): PENCIL is written as QDOBJK. How is MARKER written in the same code?", options: ['NZSJFP', 'NZSJFQ', 'NYSJFQ', 'NZSIFQ'], correctIndex: 1, explanation: 'Applying alternating +1/-1: M(+1)=N, A(-1)=Z, R(+1)=S, K(-1)=J, E(+1)=F, R(-1)=Q, giving NZSJFQ.', source },
  { id: 'ibps-so-m1-re-014', section: 'Reasoning', topic: 'Coding-decoding', difficulty: 'medium', question: "In a code, each letter is represented by its position counted from the end of the alphabet (Z=1, Y=2, and so on). What is the code for the word 'BED'?", options: ['25-21-23', '24-22-23', '25-22-24', '25-22-23'], correctIndex: 3, explanation: 'B is the 2nd letter from the start, so 25th from the end (26−2+1). E is 5th from start, 22nd from end. D is 4th from start, 23rd from end. Code: 25-22-23.', source },
  { id: 'ibps-so-m1-re-015', section: 'Reasoning', topic: 'Inequality', difficulty: 'hard', question: 'Statements: M > N ≥ O = P < Q. Conclusions: I. M > P  II. N < Q. Which conclusion(s) follow?', options: ['Only II follows', 'Both follow', 'Only I follows', 'Neither follows'], correctIndex: 2, explanation: 'Since M > N ≥ O = P, it follows that M > P (I). However, N ≥ P < Q does not establish a definite relationship between N and Q, so II does not necessarily follow.', source },
  { id: 'ibps-so-m1-re-016', section: 'Reasoning', topic: 'Inequality', difficulty: 'medium', question: 'Statements: A ≤ B < C ≤ D. Conclusions: I. A < D  II. B ≤ D. Which conclusion(s) follow?', options: ['Only I follows', 'Both I and II follow', 'Only II follows', 'Neither follows'], correctIndex: 1, explanation: 'The chain contains a strict inequality (B < C), so A < D follows (I). Since B < C ≤ D gives B < D, it also follows that B ≤ D (II).', source },
  { id: 'ibps-so-m1-re-017', section: 'Reasoning', topic: 'Alphanumeric series', difficulty: 'hard', question: 'Complete the series: C4, F9, I16, L25, ?', options: ['O35', 'P36', 'O37', 'O36'], correctIndex: 3, explanation: 'The letters skip 2 each time (C, F, I, L, O). The numbers are perfect squares for n=2,3,4,5,6: 4, 9, 16, 25, 36. Next term: O36.', source },
  { id: 'ibps-so-m1-re-018', section: 'Reasoning', topic: 'Alphanumeric series', difficulty: 'hard', question: 'Find the missing term: 27Z, 24W, 21T, 18Q, ?', options: ['15M', '16N', '15N', '15O'], correctIndex: 2, explanation: 'The numbers decrease by 3 each time (27, 24, 21, 18, 15). The letters move backward by 3 each time (Z, W, T, Q, N). Next term: 15N.', source },
  { id: 'ibps-so-m1-re-019', section: 'Reasoning', topic: 'Alphanumeric series', difficulty: 'medium', question: "If each letter of the word 'COMPUTER' is replaced by the next letter in the alphabet, how many letters in the new word are vowels?", options: ['2', '1', '0', '3'], correctIndex: 1, explanation: 'Shifting each letter forward by one: C→D, O→P, M→N, P→Q, U→V, T→U, E→F, R→S, giving DPNQVUFS. Only U is a vowel — 1 letter.', source },
  { id: 'ibps-so-m1-re-020', section: 'Reasoning', topic: 'Data sufficiency', difficulty: 'medium', question: "What is the current population of Town X? Statement I: The population of Town X increased by 10% last year to reach its current value. Statement II: The population of Town X last year (before the increase) was 50,000. Which statement(s) are sufficient to answer the question?", options: ['Statement I alone is sufficient', 'Statement II alone is sufficient', 'Either alone is sufficient', 'Both I and II together are necessary'], correctIndex: 3, explanation: 'Statement I alone gives only a percentage change with no base value. Statement II alone gives last year\'s population, not the current one. Combined, current population = 50,000 × 1.1 = 55,000.', source },
  { id: 'ibps-so-m1-re-021', section: 'Reasoning', topic: 'Data sufficiency', difficulty: 'medium', question: 'Is n divisible by 6? Statement I: n is divisible by 2. Statement II: n is divisible by 3. Which statement(s) are sufficient to answer the question?', options: ['Statement I alone is sufficient', 'Statement II alone is sufficient', 'Both I and II together are necessary', 'Either alone is sufficient'], correctIndex: 2, explanation: 'Divisibility by 2 alone does not guarantee divisibility by 3, and vice versa. Since 2 and 3 are coprime, divisibility by both together guarantees divisibility by 6.', source },
  { id: 'ibps-so-m1-re-022', section: 'Reasoning', topic: 'Ranking and order', difficulty: 'medium', question: 'In a queue of 50 people, Arjun is 22nd from the front. What is his position from the back?', options: ['28th', '29th', '30th', '27th'], correctIndex: 1, explanation: 'Position from back = total − position from front + 1 = 50 − 22 + 1 = 29th.', source },
  { id: 'ibps-so-m1-re-023', section: 'Reasoning', topic: 'Ranking and order', difficulty: 'medium', question: 'Meera is 12th from the top and 25th from the bottom in a list of students. How many students are there in total?', options: ['35', '37', '34', '36'], correctIndex: 3, explanation: 'Total students = (position from top) + (position from bottom) − 1 = 12 + 25 − 1 = 36.', source },
  { id: 'ibps-so-m1-re-024', section: 'Reasoning', topic: 'Statement and conclusion', difficulty: 'medium', question: 'Statement: "All new employees must complete a mandatory orientation session within their first week." Assumptions: I. Some new employees might skip the orientation without this rule. II. The orientation session covers essential information for new employees. Which assumption(s) is/are implicit?', options: ['Only I is implicit', 'Only II is implicit', 'Both I and II are implicit', 'Neither is implicit'], correctIndex: 2, explanation: 'The mandate implies some employees might otherwise skip it (I), and its purpose implies it covers essential information (II). Both are implicit.', source },
  { id: 'ibps-so-m1-re-025', section: 'Reasoning', topic: 'Statement and conclusion', difficulty: 'medium', question: 'Statement: "Visitors must sign the register before entering the premises." Assumptions: I. Some visitors might not sign the register without this rule. II. The register helps track who has entered the premises. Which assumption(s) is/are implicit?', options: ['Only I is implicit', 'Both I and II are implicit', 'Only II is implicit', 'Neither is implicit'], correctIndex: 1, explanation: 'The requirement implies some visitors might otherwise skip signing (I), and its purpose implies the register helps track entries (II). Both are implicit.', source },
];
