import type { Question } from '../questions';

const SOURCE = {
  kind: 'original' as const,
  reference: 'TakeMockTest original practice aligned to the IBPS Clerk CRP CSA-XVI 2026 Mains English Language section',
  url: 'https://www.ibps.in/wp-content/uploads/Notification_CRP_CSA_XVI-Final.pdf',
  checkedOn: '26 August 2026',
};

function question(
  id: string,
  topic: string,
  difficulty: 'easy' | 'medium' | 'hard',
  prompt: string,
  options: string[],
  correctIndex: number,
  explanation: string,
): Question {
  return {
    id,
    section: 'English Language',
    topic,
    difficulty,
    question: prompt,
    options,
    correctIndex,
    marks: 1,
    negativeMarking: 0.25,
    explanation,
    source: SOURCE,
  };
}

const RC_PASSAGE =
  'Financial inclusion has been a central goal of Indian banking policy for over a decade. Government-backed schemes have opened millions of no-frills bank accounts for previously unbanked citizens, particularly in rural areas. Yet simply opening an account does not guarantee active usage: studies show a meaningful share of these accounts remain dormant, with balances close to zero and no regular transactions. Banking correspondents and business facilitators have been deployed to bridge this last-mile gap, bringing basic banking services to villages without a physical branch. Even so, sustained account activity depends on more than access alone; it requires ongoing trust in the banking system, awareness of available services, and products genuinely suited to irregular or seasonal incomes. Policymakers increasingly argue that the next phase of financial inclusion must shift focus from account opening to account usage. ';

export const IBPS_CLERK_MAINS_ENGLISH_1: Question[] = [
  question('ibps-clerk-m-en-001', 'Reading comprehension', 'medium', RC_PASSAGE + 'According to the passage, what problem persists despite millions of accounts being opened?', ['Accounts are frequently closed by banks', 'A meaningful share of accounts remain dormant', 'Rural areas have no bank branches at all', 'Banking correspondents have been removed'], 1, 'The passage explicitly states that a meaningful share of accounts remain dormant, with balances close to zero and no regular transactions.'),
  question('ibps-clerk-m-en-002', 'Reading comprehension', 'medium', RC_PASSAGE + 'What role do banking correspondents and business facilitators play, per the passage?', ['They approve loan applications', 'They bring basic banking services to villages without a physical branch', 'They regulate interest rates', 'They audit bank branches'], 1, 'The passage states banking correspondents and business facilitators bring basic banking services to villages lacking a physical branch, bridging the last-mile gap.'),
  question('ibps-clerk-m-en-003', 'Reading comprehension', 'hard', RC_PASSAGE + 'What does the passage suggest is needed beyond mere account access for sustained activity?', ['Higher interest rates only', 'Trust in the system, awareness, and suitable products', 'More bank holidays', 'Stricter account-closure rules'], 1, 'The passage states that sustained account activity requires ongoing trust in the banking system, awareness of services, and products suited to irregular incomes.'),
  question('ibps-clerk-m-en-004', 'Reading comprehension', 'medium', RC_PASSAGE + 'What shift in focus do policymakers increasingly argue for, according to the passage?', ['From account usage to account opening', 'From account opening to account usage', 'From rural banking to urban banking', 'From digital banking to branch banking'], 1, 'The passage states policymakers increasingly argue that the next phase of financial inclusion must shift focus from account opening to account usage.'),
  question('ibps-clerk-m-en-005', 'Reading comprehension', 'hard', RC_PASSAGE + 'Which best describes the passage\'s overall argument?', ['Financial inclusion has completely failed in India', 'Opening accounts alone is insufficient; sustained usage requires trust and suitable products', 'Rural banking is more successful than urban banking', 'Banking correspondents have replaced all bank branches'], 1, 'The passage argues that while account-opening schemes succeeded numerically, sustained usage depends on trust, awareness, and appropriately designed products, not access alone.'),
  question('ibps-clerk-m-en-006', 'Cloze test', 'medium', 'The bank has _______ a new policy to reduce processing time for loan applications.', ['implement', 'implementing', 'implemented', 'implementation'], 2, 'The sentence requires the past participle form after "has" to form the present perfect tense: "has implemented".'),
  question('ibps-clerk-m-en-007', 'Cloze test', 'medium', 'Despite repeated reminders, the customer _______ to submit the required documents.', ['fail', 'fails', 'failed', 'failing'], 2, 'The sentence describes a completed past action, so the simple past tense "failed" is correct.'),
  question('ibps-clerk-m-en-008', 'Cloze test', 'hard', 'The manager, _______ decision was final, approved the transfer request.', ['who', 'whom', 'whose', 'which'], 2, '"Whose" is the correct possessive relative pronoun to show that the decision belongs to the manager.'),
  question('ibps-clerk-m-en-009', 'Error spotting', 'medium', 'Identify the part with an error: (A) The committee members / (B) has agreed / (C) to revise the proposal / (D) by next week.', ['A', 'B', 'C', 'D'], 1, '"Members" is plural, so it requires the plural verb "have agreed", not "has agreed" — the error is in part B.'),
  question('ibps-clerk-m-en-010', 'Error spotting', 'hard', 'Identify the part with an error: (A) Neither the clerk nor the officers / (B) was present / (C) at the meeting / (D) yesterday.', ['A', 'B', 'C', 'D'], 1, 'With "neither...nor", the verb agrees with the nearer subject; since "officers" (plural) is closer, the verb should be "were present", not "was present" — the error is in part B.'),
  question('ibps-clerk-m-en-011', 'Sentence improvement', 'medium', 'Improve the underlined part: "The bank announced that it will _increasing_ interest rates next month."', ['increasing', 'increase', 'be increase', 'increased'], 1, 'After the modal "will", the base form of the verb is required: "will increase", not "will increasing".'),
  question('ibps-clerk-m-en-012', 'Sentence improvement', 'medium', 'Improve the underlined part: "She is among the few employees who _has_ never missed a deadline."', ['has', 'have', 'having', 'had'], 1, '"Among the few employees who" takes a plural verb agreeing with "employees", so "have" is correct, not "has".'),
  question('ibps-clerk-m-en-013', 'Para jumbles', 'hard', 'Arrange the sentences in logical order: P. As a result, more transactions now happen through mobile apps than at branch counters. Q. Digital payment adoption has surged across urban and semi-urban India. R. This shift has pushed banks to redesign their branch networks. S. Branches increasingly focus on advisory services rather than routine transactions.', ['QPRS', 'PQSR', 'QRPS', 'SQPR'], 0, 'The logical order begins with the trend (Q: digital payment surge), its direct consequence (P: more mobile transactions), then the resulting bank response (R: redesigning branches), and finally the specific change (S: branches focusing on advisory services): QPRS.'),
  question('ibps-clerk-m-en-014', 'Para jumbles', 'hard', 'Arrange the sentences in logical order: P. Consequently, many banks now offer instant loan approvals through their apps. Q. Customers increasingly expect banking services to be as fast as e-commerce transactions. R. This expectation has pushed banks to automate credit assessment. S. Loan disbursal times have dropped from days to minutes for eligible customers.', ['QRPS', 'PQRS', 'QPRS', 'SQPR'], 0, 'The order begins with the customer expectation (Q), its effect on banks (R: automating credit assessment), the resulting product change (P: instant loan approvals), and finally the measurable outcome (S: faster disbursal times): QRPS.'),
  question('ibps-clerk-m-en-015', 'Fill in the blanks', 'medium', 'The auditor raised several _______ regarding the branch\'s cash-handling procedures.', ['concern', 'concerns', 'concerning', 'concernedly'], 1, '"Several" requires a plural noun, and "concerns" (plural) correctly fits the sentence.'),
  question('ibps-clerk-m-en-016', 'Fill in the blanks', 'medium', 'The new guidelines will come into _______ from the first of next quarter.', ['effect', 'affect', 'effective', 'affected'], 0, '"Come into effect" is the correct idiomatic phrase meaning to become operative.'),
  question('ibps-clerk-m-en-017', 'Vocabulary in context', 'medium', 'The word "prudent" is closest in meaning to:', ['Careless', 'Reckless', 'Indifferent', 'Wise and cautious in practical matters'], 3, '"Prudent" means acting with or showing care and thought for the future, i.e., wise and cautious.'),
  question('ibps-clerk-m-en-018', 'Vocabulary in context', 'medium', 'The word "obsolete" is closest in meaning to:', ['Modern and current', 'Extremely valuable', 'No longer produced or used; outdated', 'Newly invented'], 2, '"Obsolete" describes something no longer produced, used, or needed, i.e., outdated.'),
  question('ibps-clerk-m-en-019', 'Vocabulary in context', 'hard', 'Choose the word most nearly OPPOSITE in meaning to "meticulous".', ['Careful', 'Precise', 'Careless', 'Thorough'], 2, '"Meticulous" means showing great attention to detail; its opposite is "careless", lacking attention or care.'),
  question('ibps-clerk-m-en-020', 'One-word substitution', 'medium', 'A person who spends money extravagantly and wastefully is called:', ['Spendthrift', 'Frugal', 'Miser', 'Thrifty'], 0, 'A "spendthrift" is a person who spends money in an extravagant, wasteful manner.'),
  question('ibps-clerk-m-en-021', 'One-word substitution', 'medium', 'A statement or event that marks a turning point or new development is called:', ['Milestone', 'Anecdote', 'Prelude', 'Epilogue'], 0, 'A "milestone" refers to a significant point or event marking a stage of development or a turning point.'),
  question('ibps-clerk-m-en-022', 'Idioms and phrases', 'medium', 'What does the idiom "to break even" mean?', ['To make neither a profit nor a loss', 'To break a promise', 'To make a large profit', 'To go bankrupt'], 0, '"To break even" means to reach a point where total revenue equals total costs, resulting in neither profit nor loss.'),
  question('ibps-clerk-m-en-023', 'Idioms and phrases', 'hard', 'What does the idiom "to foot the bill" mean?', ['To walk to a restaurant', 'To refuse payment', 'To calculate a total', 'To pay for something, especially an expense'], 3, '"To foot the bill" means to pay for something, typically an expense or cost incurred.'),
  question('ibps-clerk-m-en-024', 'Sentence correction', 'hard', 'Choose the grammatically correct sentence.', ['Each of the customers were given a token number.', 'Each of the customer were given a token number.', 'Each of the customers was given a token number.', 'Each of customers was given token numbers.'], 2, '"Each" is singular and requires a singular verb ("was given"), making the second option grammatically correct.'),
  question('ibps-clerk-m-en-025', 'Sentence correction', 'medium', 'Identify the grammatically correct sentence.', ['Neither the manager nor the clerks were informed of the change.', 'Neither the manager nor the clerks was informed of the change.', 'Neither the manager or the clerks were informed of the change.', 'Neither manager nor clerks was informed of the change.'], 0, 'With "neither...nor", the verb agrees with the subject closer to it; since "clerks" (plural) is closer, the verb should be "were", making the second option correct.'),
  question('ibps-clerk-m-en-026', 'Connectors', 'medium', 'The branch reported strong deposit growth this quarter; _______, loan disbursals declined sharply.', ['therefore', 'moreover', 'however', 'consequently'], 2, '"However" correctly signals a contrast between the strong deposit growth and the unexpected decline in loan disbursals.'),
  question('ibps-clerk-m-en-027', 'Connectors', 'medium', 'The bank revised its lending policy _______ the rise in loan defaults.', ['because of', 'although', 'unless', 'whereas'], 0, '"Because of" correctly introduces the reason (rising loan defaults) for the bank\'s policy revision.'),
  question('ibps-clerk-m-en-028', 'Reading comprehension', 'medium', RC_PASSAGE + 'What is the current state of a meaningful share of no-frills accounts, per the passage?', ['They have very high balances', 'They have been permanently closed', 'They are used exclusively for large transactions', 'They remain dormant with balances close to zero'], 3, 'The passage states a meaningful share of these accounts remain dormant, with balances close to zero and no regular transactions.'),
  question('ibps-clerk-m-en-029', 'Active and passive voice', 'medium', 'Choose the correct passive voice of: "The clerk verified the documents."', ['The documents are verified by the clerk.', 'The documents had been verifying by the clerk.', 'The documents were verified by the clerk.', 'The documents verify by the clerk.'], 2, 'The original sentence is in simple past active voice, so the correct passive form is "The documents were verified by the clerk."'),
  question('ibps-clerk-m-en-030', 'Active and passive voice', 'hard', 'Choose the correct passive voice of: "The bank will launch a new savings scheme next month."', ['A new savings scheme will be launched next month.', 'A new savings scheme is launched next month.', 'A new savings scheme will launch next month.', 'A new savings scheme was launched next month.'], 0, 'The original sentence uses the future tense with "will", so the correct passive form retains that tense: "will be launched".'),
  question('ibps-clerk-m-en-031', 'Direct and indirect speech', 'medium', 'Convert to indirect speech: She said, "I will submit the report tomorrow."', ['She said that she will submit the report tomorrow.', 'She said that she submits the report tomorrow.', 'She says that she would submit the report tomorrow.', 'She said that she would submit the report the next day.'], 3, 'In indirect speech, "will" changes to "would" and "tomorrow" changes to "the next day" when the reporting verb is in the past tense.'),
  question('ibps-clerk-m-en-032', 'Direct and indirect speech', 'hard', 'Convert to indirect speech: He said, "I have completed the task."', ['He said that he has completed the task.', 'He says that he completed the task.', 'He said that he completes the task.', 'He said that he had completed the task.'], 3, 'In indirect speech, present perfect ("have completed") changes to past perfect ("had completed") when the reporting verb is in the past tense.'),
  question('ibps-clerk-m-en-033', 'Spelling', 'easy', 'Identify the correctly spelled word.', ['Recieve', 'Receeve', 'Receve', 'Receive'], 3, 'The correct spelling is "Receive", following the "i before e except after c" rule.'),
  question('ibps-clerk-m-en-034', 'Spelling', 'easy', 'Choose the correctly spelled word.', ['Necessery', 'Neccessary', 'Necessary', 'Neccessery'], 2, 'The correct spelling is "Necessary", with a single "c" and double "s".'),
  question('ibps-clerk-m-en-035', 'Word usage', 'hard', 'Choose the correct word to complete the sentence: "The new policy will _______ affect small businesses more than large corporations."', ['effect', 'affect', 'effectively', 'affectively'], 2, '"Effectively" is an adverb modifying the verb "affect" (meaning "in an effective manner"), fitting grammatically before the verb.'),
  question('ibps-clerk-m-en-036', 'Word usage', 'medium', 'Choose the correct word: "The two departments decided to _______ their resources for the new project."', ['pool', 'poll', 'pole', 'pull'], 0, '"Pool" means to combine resources together, fitting the context; "poll" refers to voting, "pole" is a rod, and "pull" means to drag.'),
  question('ibps-clerk-m-en-037', 'Reading comprehension', 'medium', RC_PASSAGE + 'For how long has financial inclusion been a central goal of Indian banking policy, per the passage?', ['Less than a year', 'Over a century', 'Since independence only', 'Over a decade'], 3, 'The passage states financial inclusion has been a central goal of Indian banking policy for over a decade.'),
  question('ibps-clerk-m-en-038', 'Cloze test', 'medium', 'The board members _______ to reconsider the merger terms after new data emerged.', ['agree', 'agreeing', 'agreement', 'agreed'], 3, 'The sentence describes a completed past action, so the simple past tense "agreed" is correct.'),
  question('ibps-clerk-m-en-039', 'Error spotting', 'medium', 'Identify the part with an error: (A) Each of the branch managers / (B) are required to submit / (C) a monthly compliance report / (D) by the fifth of every month.', ['A', 'C', 'D', 'B'], 3, '"Each" is singular and requires a singular verb, so it should be "is required", not "are required" — the error is in part B.'),
  question('ibps-clerk-m-en-040', 'Sentence improvement', 'medium', 'Improve the underlined part: "The committee _decided_ to postponing the meeting until further notice."', ['decided to postponing', 'decided postponing', 'deciding to postpone', 'decided to postpone'], 3, '"Decided to" must be followed by the base form of the verb ("to postpone"), not the gerund ("postponing").'),
];
