import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'IBPS CRP RRBs XIV official notification (Advt. dated 27.09.2025), Mains syllabus — English Language section (Office Assistants/Multipurpose)',
  url: 'https://www.ibps.in/wp-content/uploads/CRP-RRBs-XIV_Final_AD-27.09.25.pdf',
  checkedOn: '27 August 2026',
};

const RC_PASSAGE =
  "Read the following passage carefully and answer the questions that follow.\n\nSelf-help groups have quietly reshaped the financial landscape of rural India over the past three decades. A self-help group typically consists of ten to twenty women from the same village who pool small, regular savings into a common fund and lend to one another at modest rates of interest. This simple practice, once dismissed by mainstream banks as too small to matter, has grown into one of the largest microfinance networks in the world, linking millions of rural households to formal banking channels for the first time.\n\nRegional Rural Banks have played a central role in this transformation. By extending credit lines to self-help groups rather than to individual borrowers, banks reduce both the administrative cost and the risk of lending in areas with limited collateral and inconsistent income. The group itself absorbs much of the monitoring burden, since members have strong incentives to ensure that loans are repaid on time, given that a single default can affect the group's collective credit standing.\n\nThe benefits extend well beyond access to credit. Group meetings have become informal forums where women discuss household budgeting, children's education, and health concerns, gradually building confidence and a voice in decisions that were once made exclusively by male relatives. Critics note that the model is not without limitations: interest rates charged within groups can still be steep relative to formal bank loans, and the quality of record-keeping varies widely from group to group. Even so, most development economists agree that the self-help group movement has done more to advance rural financial inclusion than any single government scheme.\n\n";

const CLOZE_PASSAGE =
  'In the following passage, four numbered blanks have been left. Choose the option that best fits each blank.\n\nFinancial inclusion in rural India has (1)______ significantly over the past decade, largely due to the expansion of banking correspondents and mobile-based payment systems. Regional Rural Banks, in (2)______ with self-help groups, have extended credit to millions of first-time borrowers. However, experts (3)______ that digital literacy remains a major barrier, particularly among older residents who are (4)______ with smartphone-based banking applications.\n\n';

export const IBPS_RRB_OFFICE_ASSISTANT_MAINS_ENGLISH_LANGUAGE_1: Question[] = [
  { id: 'ibps-rrb-oa-m1-en-001', section: 'English Language', topic: 'Reading comprehension', difficulty: 'medium', question: `${RC_PASSAGE}Why do banks prefer lending to self-help groups rather than to individual borrowers, according to the passage?`, options: ['It reduces the administrative cost and risk of lending in areas with limited collateral', 'Individual borrowers are legally barred from taking rural bank loans', 'Self-help groups offer higher interest rates than individuals', 'Banks are required by law to lend only to groups'], correctIndex: 0, explanation: 'The passage states that lending to groups "reduce[s] both the administrative cost and the risk of lending in areas with limited collateral and inconsistent income."', source },
  { id: 'ibps-rrb-oa-m1-en-002', section: 'English Language', topic: 'Reading comprehension', difficulty: 'easy', question: `${RC_PASSAGE}What is the typical size of a self-help group as described in the passage?`, options: ['Ten to twenty women from the same village', 'Five to ten families from different villages', 'Fifty or more members from a district', 'Two or three households'], correctIndex: 0, explanation: 'The passage describes a self-help group as "typically consist[ing] of ten to twenty women from the same village."', source },
  { id: 'ibps-rrb-oa-m1-en-003', section: 'English Language', topic: 'Reading comprehension', difficulty: 'medium', question: `${RC_PASSAGE}Besides access to credit, what other role do group meetings serve, according to the passage?`, options: ['Informal forums for discussing household budgeting, education, and health, building confidence and voice', 'Formal training sessions run by bank auditors', 'Legal proceedings to settle loan disputes', 'Political meetings to select village representatives'], correctIndex: 0, explanation: 'The passage states group meetings "have become informal forums where women discuss household budgeting, children\'s education, and health concerns, gradually building confidence and a voice in decisions."', source },
  { id: 'ibps-rrb-oa-m1-en-004', section: 'English Language', topic: 'Reading comprehension', difficulty: 'medium', question: `${RC_PASSAGE}What criticism of the self-help group model is mentioned in the passage?`, options: ['Interest rates within groups can still be steep, and record-keeping quality varies', 'The groups are entirely unregulated by any bank', 'Most groups collapse within their first year', 'Men are excluded from all group decisions'], correctIndex: 0, explanation: 'The passage notes that "interest rates charged within groups can still be steep relative to formal bank loans, and the quality of record-keeping varies widely from group to group."', source },
  { id: 'ibps-rrb-oa-m1-en-005', section: 'English Language', topic: 'Reading comprehension', difficulty: 'medium', question: `${RC_PASSAGE}Which of the following best describes the author's overall assessment of the self-help group movement?`, options: ['It has done more to advance rural financial inclusion than any single government scheme, despite limitations', 'It has failed to make any meaningful impact on rural credit access', 'It is superior to all forms of formal banking in every respect', 'It is a temporary phenomenon that will soon be replaced entirely by digital banking'], correctIndex: 0, explanation: 'The passage concludes that despite noted limitations, "most development economists agree that the self-help group movement has done more to advance rural financial inclusion than any single government scheme."', source },
  { id: 'ibps-rrb-oa-m1-en-006', section: 'English Language', topic: 'Vocabulary in context', difficulty: 'medium', question: `${RC_PASSAGE}Choose the word closest in meaning to 'absorbs' as used in the passage ("The group itself absorbs much of the monitoring burden").`, options: ['Takes on', 'Rejects', 'Ignores', 'Postpones'], correctIndex: 0, explanation: "In this context, 'absorbs' means the group takes on or bears the monitoring burden itself.", source },
  { id: 'ibps-rrb-oa-m1-en-007', section: 'English Language', topic: 'Vocabulary in context', difficulty: 'medium', question: `${RC_PASSAGE}Choose the word most opposite in meaning to 'modest' as used in the passage ("lend to one another at modest rates of interest").`, options: ['Exorbitant', 'Reasonable', 'Fair', 'Minimal'], correctIndex: 0, explanation: "'Modest' here means low/reasonable; its opposite in this context is 'exorbitant', meaning excessively high.", source },
  { id: 'ibps-rrb-oa-m1-en-008', section: 'English Language', topic: 'Cloze test', difficulty: 'medium', question: `${CLOZE_PASSAGE}Choose the best word for blank (1).`, options: ['improved', 'worsened', 'stalled', 'declined'], correctIndex: 0, explanation: "The passage describes positive change driven by banking correspondents and mobile payments, so 'improved' fits blank (1).", source },
  { id: 'ibps-rrb-oa-m1-en-009', section: 'English Language', topic: 'Cloze test', difficulty: 'medium', question: `${CLOZE_PASSAGE}Choose the best word for blank (2).`, options: ['partnership', 'isolation', 'competition', 'conflict'], correctIndex: 0, explanation: "Regional Rural Banks working alongside self-help groups indicates a 'partnership', not isolation or conflict.", source },
  { id: 'ibps-rrb-oa-m1-en-010', section: 'English Language', topic: 'Cloze test', difficulty: 'medium', question: `${CLOZE_PASSAGE}Choose the best word for blank (3).`, options: ['caution', 'dismiss', 'ignore', 'overlook'], correctIndex: 0, explanation: "'Caution that' means to warn, which fits the sentence structure describing experts flagging a barrier.", source },
  { id: 'ibps-rrb-oa-m1-en-011', section: 'English Language', topic: 'Cloze test', difficulty: 'medium', question: `${CLOZE_PASSAGE}Choose the best word for blank (4).`, options: ['expert', 'fluent', 'skilled', 'unfamiliar'], correctIndex: 3, explanation: "Older residents facing digital literacy as a barrier would be 'unfamiliar' with smartphone-based applications.", source },
  { id: 'ibps-rrb-oa-m1-en-012', section: 'English Language', topic: 'Error spotting', difficulty: 'medium', question: 'Read the sentence below, divided into three parts. Identify the part that contains a grammatical error, or select "No error" if there is none.\n\nThe manager along with his team (A) / are reviewing the loan applications (B) / before the end of this week. (C)', options: ['A', 'C', 'B', 'No error'], correctIndex: 2, explanation: "The subject 'manager' is singular; the phrase 'along with his team' does not make the verb plural, so it should be 'is reviewing', not 'are reviewing' — the error is in part B.", source },
  { id: 'ibps-rrb-oa-m1-en-013', section: 'English Language', topic: 'Error spotting', difficulty: 'medium', question: 'Read the sentence below, divided into three parts. Identify the part that contains a grammatical error, or select "No error" if there is none.\n\nNeither of the two clerks (A) / have submitted (B) / their reports on time. (C)', options: ['A', 'B', 'C', 'No error'], correctIndex: 1, explanation: "'Neither' takes a singular verb, so it should be 'has submitted', not 'have submitted' — the error is in part B.", source },
  { id: 'ibps-rrb-oa-m1-en-014', section: 'English Language', topic: 'Error spotting', difficulty: 'medium', question: 'Read the sentence below, divided into three parts. Identify the part that contains a grammatical error, or select "No error" if there is none.\n\nShe is one of the employees (A) / who always arrive (B) / early to the branch. (C)', options: ['A', 'B', 'C', 'No error'], correctIndex: 3, explanation: "'Who' refers back to 'employees' (plural), so the plural verb 'arrive' is correct. The sentence has no error.", source },
  { id: 'ibps-rrb-oa-m1-en-015', section: 'English Language', topic: 'Error spotting', difficulty: 'medium', question: 'Read the sentence below, divided into three parts. Identify the part that contains a grammatical error, or select "No error" if there is none.\n\nThe number of complaints (A) / have increased (B) / drastically this quarter. (C)', options: ['A', 'C', 'B', 'No error'], correctIndex: 2, explanation: "'The number of' as a subject takes a singular verb, so it should be 'has increased', not 'have increased' — the error is in part B.", source },
  { id: 'ibps-rrb-oa-m1-en-016', section: 'English Language', topic: 'Sentence improvement', difficulty: 'medium', question: 'Improve the underlined part of the sentence: "He is one of the best _manager_ in the bank."', options: ['manager', 'managers', 'managing', 'management'], correctIndex: 1, explanation: "'One of the best X' requires a plural noun, so 'managers' is correct.", source },
  { id: 'ibps-rrb-oa-m1-en-017', section: 'English Language', topic: 'Sentence improvement', difficulty: 'medium', question: 'Improve the underlined part of the sentence: "_Despite of_ his hard work, he failed the interview."', options: ['Despite of the', 'In spite', 'Although of', 'Despite'], correctIndex: 3, explanation: "'Despite' is never followed by 'of'; the correct form is simply 'Despite his hard work'.", source },
  { id: 'ibps-rrb-oa-m1-en-018', section: 'English Language', topic: 'Sentence improvement', difficulty: 'medium', question: 'Improve the underlined part of the sentence: "The customer was _so much angry_ that he left without collecting his passbook."', options: ['too much angry', 'very much angry', 'so angry', 'so much angered'], correctIndex: 2, explanation: "The correlative construction 'so...that' does not take 'much' before an adjective; the correct form is 'so angry'.", source },
  { id: 'ibps-rrb-oa-m1-en-019', section: 'English Language', topic: 'Fill in the blanks', difficulty: 'medium', question: "Fill in the two blanks with the most appropriate pair of words: \"The bank has ______ its interest rates and ______ new savings schemes for rural customers.\"", options: ['increased, cancelled', 'revised, launched', 'lowered, discontinued', 'ignored, withdrawn'], correctIndex: 1, explanation: "'Revised' and 'launched' fit the positive, active tone of a bank updating rates and introducing new schemes.", source },
  { id: 'ibps-rrb-oa-m1-en-020', section: 'English Language', topic: 'Fill in the blanks', difficulty: 'medium', question: "Fill in the two blanks with the most appropriate pair of words: \"Despite the ______ in rainfall, farmers in the region managed to secure a ______ harvest.\"", options: ['increase, poor', 'decline, poor', 'surplus, bad', 'decline, good'], correctIndex: 3, explanation: "'Despite' signals a contrast, so a 'decline' in rainfall paired with a still-'good' harvest fits the sentence logic.", source },
  { id: 'ibps-rrb-oa-m1-en-021', section: 'English Language', topic: 'Fill in the blanks', difficulty: 'medium', question: "Fill in the two blanks with the most appropriate pair of words: \"The officer ______ the documents carefully before ______ the loan application.\"", options: ['ignored, approving', 'reviewed, rejecting the entirely unrelated', 'reviewed, approving', 'signed, reviewing'], correctIndex: 2, explanation: "'Reviewed...before approving' forms a logical sequence: careful review precedes the decision to approve.", source },
  { id: 'ibps-rrb-oa-m1-en-022', section: 'English Language', topic: 'One-word substitution', difficulty: 'medium', question: 'Choose the word that means "a person who lends money at excessively high interest rates."', options: ['Miser', 'Usurer', 'Philanthropist', 'Debtor'], correctIndex: 1, explanation: 'A usurer is someone who lends money at unreasonably high interest rates.', source },
  { id: 'ibps-rrb-oa-m1-en-023', section: 'English Language', topic: 'One-word substitution', difficulty: 'medium', question: 'Choose the word that means "a place where money is coined by government authority."', options: ['Treasury', 'Vault', 'Exchequer', 'Mint'], correctIndex: 3, explanation: 'A mint is the official place where coins are manufactured by government authority.', source },
  { id: 'ibps-rrb-oa-m1-en-024', section: 'English Language', topic: 'One-word substitution', difficulty: 'medium', question: 'Choose the word that means "one who is unable to pay one\'s debts."', options: ['Affluent', 'Prudent', 'Insolvent', 'Solvent'], correctIndex: 2, explanation: 'Insolvent means unable to pay debts owed.', source },
  { id: 'ibps-rrb-oa-m1-en-025', section: 'English Language', topic: 'Synonym', difficulty: 'medium', question: 'Choose the word closest in meaning to PRUDENT.', options: ['Careless', 'Judicious', 'Impulsive', 'Reckless'], correctIndex: 1, explanation: 'Prudent means acting with careful judgment, closest to "judicious".', source },
  { id: 'ibps-rrb-oa-m1-en-026', section: 'English Language', topic: 'Synonym', difficulty: 'medium', question: 'Choose the word closest in meaning to AUGMENT.', options: ['Reduce', 'Diminish', 'Erase', 'Increase'], correctIndex: 3, explanation: 'Augment means to increase or make greater.', source },
  { id: 'ibps-rrb-oa-m1-en-027', section: 'English Language', topic: 'Synonym', difficulty: 'medium', question: 'Choose the word closest in meaning to CANDID.', options: ['Secretive', 'Evasive', 'Frank', 'Deceptive'], correctIndex: 2, explanation: 'Candid means open and honest in expression, closest to "frank".', source },
  { id: 'ibps-rrb-oa-m1-en-028', section: 'English Language', topic: 'Antonym', difficulty: 'medium', question: 'Choose the word most opposite in meaning to FRUGAL.', options: ['Thrifty', 'Extravagant', 'Economical', 'Sparing'], correctIndex: 1, explanation: 'Frugal means careful with spending; its opposite is "extravagant", meaning wasteful with money.', source },
  { id: 'ibps-rrb-oa-m1-en-029', section: 'English Language', topic: 'Antonym', difficulty: 'medium', question: 'Choose the word most opposite in meaning to TRANSPARENT.', options: ['Clear', 'Obvious', 'Visible', 'Opaque'], correctIndex: 3, explanation: 'Transparent means easy to see through or understand; its opposite is "opaque".', source },
  { id: 'ibps-rrb-oa-m1-en-030', section: 'English Language', topic: 'Antonym', difficulty: 'medium', question: 'Choose the word most opposite in meaning to VOLUNTARY.', options: ['Optional', 'Willing', 'Compulsory', 'Elective'], correctIndex: 2, explanation: 'Voluntary means done by free choice; its opposite is "compulsory", meaning required.', source },
  { id: 'ibps-rrb-oa-m1-en-031', section: 'English Language', topic: 'Idioms and phrases', difficulty: 'medium', question: 'Choose the meaning of the idiom: "To foot the bill"', options: ['To avoid payment entirely', 'To pay for something', 'To dispute a bill', 'To delay payment indefinitely'], correctIndex: 1, explanation: "'To foot the bill' means to pay for something or bear the cost of it.", source },
  { id: 'ibps-rrb-oa-m1-en-032', section: 'English Language', topic: 'Idioms and phrases', difficulty: 'medium', question: 'Choose the meaning of the idiom: "To read between the lines"', options: ['To read very quickly', 'To skip parts of a text', 'To read aloud', 'To understand a hidden or implied meaning'], correctIndex: 3, explanation: "'To read between the lines' means to grasp an implied meaning that is not stated directly.", source },
  { id: 'ibps-rrb-oa-m1-en-033', section: 'English Language', topic: 'Idioms and phrases', difficulty: 'medium', question: 'Choose the meaning of the idiom: "To bite the bullet"', options: ['To avoid a difficult task', 'To speak angrily', 'To face a difficult situation with courage', 'To eat quickly'], correctIndex: 2, explanation: "'To bite the bullet' means to endure a painful or difficult situation with courage.", source },
  { id: 'ibps-rrb-oa-m1-en-034', section: 'English Language', topic: 'Active passive voice', difficulty: 'medium', question: 'Choose the correct passive voice of: "The bank manager approved the loan application."', options: ['The loan application is approved by the bank manager.', 'The loan application was approved by the bank manager.', 'The loan application had approved the bank manager.', 'The bank manager was approved by the loan application.'], correctIndex: 1, explanation: 'In the passive voice, the object "the loan application" becomes the subject, and the verb takes the correct past-tense passive form: "was approved by".', source },
  { id: 'ibps-rrb-oa-m1-en-035', section: 'English Language', topic: 'Active passive voice', difficulty: 'medium', question: 'Choose the correct passive voice of: "They will complete the audit by next week."', options: ['The audit is completed by them by next week.', 'The audit will complete them by next week.', 'The audit had been completed by them by next week.', 'The audit will be completed by them by next week.'], correctIndex: 3, explanation: 'For future simple tense, the passive form uses "will be + past participle": "The audit will be completed by them by next week."', source },
  { id: 'ibps-rrb-oa-m1-en-036', section: 'English Language', topic: 'Direct indirect speech', difficulty: 'medium', question: 'Choose the correct indirect speech of: She said, "I am submitting my resignation today."', options: ['She said that I am submitting my resignation today.', 'She said that she is submitting her resignation today.', 'She said that she was submitting her resignation that day.', 'She said that she submits her resignation that day.'], correctIndex: 2, explanation: "In indirect speech, present continuous shifts to past continuous, 'I' becomes 'she', 'my' becomes 'her', and 'today' becomes 'that day'.", source },
  { id: 'ibps-rrb-oa-m1-en-037', section: 'English Language', topic: 'Direct indirect speech', difficulty: 'medium', question: 'Choose the correct indirect speech of: He said, "Will you help me with this form?"', options: ['He said that will you help him with this form.', 'He asked if I would help him with that form.', 'He asked that I will help him with this form.', 'He asked if I will help him with that form.'], correctIndex: 1, explanation: "In indirect speech, a yes/no question introduces 'if'/'whether', 'will' shifts to 'would', and 'this' shifts to 'that'.", source },
  { id: 'ibps-rrb-oa-m1-en-038', section: 'English Language', topic: 'Synonym', difficulty: 'medium', question: 'Choose the word closest in meaning to METICULOUS.', options: ['Careless', 'Hasty', 'Sloppy', 'Careful'], correctIndex: 3, explanation: 'Meticulous means showing great attention to detail, closest to "careful".', source },
  { id: 'ibps-rrb-oa-m1-en-039', section: 'English Language', topic: 'Antonym', difficulty: 'medium', question: 'Choose the word most opposite in meaning to LENIENT.', options: ['Merciful', 'Forgiving', 'Strict', 'Gentle'], correctIndex: 2, explanation: 'Lenient means mild or tolerant; its opposite is "strict".', source },
  { id: 'ibps-rrb-oa-m1-en-040', section: 'English Language', topic: 'One-word substitution', difficulty: 'medium', question: 'Choose the word that means "a document by which a person states how his property is to be disposed of after death."', options: ['Deed', 'Will', 'Bond', 'Ledger'], correctIndex: 1, explanation: 'A "will" is the legal document specifying how a person\'s property should be distributed after death.', source },
];
