import type { Question } from '../questions';

const SOURCE = {
  kind: 'original' as const,
  reference: 'TakeMockTest original practice aligned to the IBPS PO XVI Prelims English Language section',
  url: 'https://www.ibps.in/wp-content/uploads/Detailed-Notification_CRP-PO-XVI_Final_V1_30.06.2026.pdf',
  checkedOn: '3 August 2026',
};

function question(
  id: string,
  topic: string,
  difficulty: 'easy' | 'medium' | 'hard',
  prompt: string,
  options: string[],
  correctIndex: number,
  explanation: string,
): Question {
  return {
    id,
    section: 'English Language',
    topic,
    difficulty,
    question: prompt,
    options,
    correctIndex,
    marks: 1,
    negativeMarking: 0.25,
    explanation,
    source: SOURCE,
  };
}

export const IBPS_PO_PRELIMS_ENGLISH_1: Question[] = [
  question(
    'ibps-po-p1-eng-001',
    'Subject-verb agreement',
    'easy',
    'Choose the correct completion: The list of selected candidates ___ on the notice board.',
    ['has been displayed', 'have been displayed', 'were displaying', 'display'],
    0,
    'The subject is the singular noun “list”, so it takes the singular verb phrase “has been displayed”.',
  ),
  question(
    'ibps-po-p1-eng-002',
    'Subject-verb agreement',
    'medium',
    'Choose the correct word: Neither the manager nor the employees ___ willing to extend the deadline.',
    ['was', 'were', 'is', 'has'],
    1,
    'With “neither…nor”, the verb agrees with the nearer subject. “Employees” is plural, so “were” is correct.',
  ),
  question(
    'ibps-po-p1-eng-003',
    'Tenses',
    'medium',
    'Choose the correct completion: By next June, she ___ five years of service at the bank.',
    ['completes', 'completed', 'will have completed', 'has completed'],
    2,
    'The future perfect tense describes an action completed before a stated future time: “will have completed”.',
  ),
  question(
    'ibps-po-p1-eng-004',
    'Prepositions',
    'easy',
    'Choose the correct preposition: He insisted ___ paying the bill himself.',
    ['at', 'for', 'to', 'on'],
    3,
    'The verb “insist” takes the preposition “on” before a noun or gerund: “insisted on paying”.',
  ),
  question(
    'ibps-po-p1-eng-005',
    'Vocabulary',
    'easy',
    'Choose the word closest in meaning to “concise”.',
    ['brief', 'uncertain', 'ornamental', 'repetitive'],
    0,
    '“Concise” means expressing much in few words, so “brief” is the closest synonym.',
  ),
  question(
    'ibps-po-p1-eng-006',
    'Vocabulary',
    'easy',
    'Choose the word opposite in meaning to “scarce”.',
    ['fragile', 'abundant', 'costly', 'hidden'],
    1,
    '“Scarce” means insufficient or hard to find; “abundant” means plentiful and is its opposite.',
  ),
  question(
    'ibps-po-p1-eng-007',
    'Idioms',
    'easy',
    'In the sentence “The branch is audited once in a blue moon,” what does the phrase mean?',
    ['At the correct time', 'Without warning', 'Very rarely', 'For a long period'],
    2,
    '“Once in a blue moon” is an idiom meaning that something happens very rarely.',
  ),
  question(
    'ibps-po-p1-eng-008',
    'One-word substitution',
    'medium',
    'A person who compiles a dictionary is called a:',
    ['biographer', 'stenographer', 'cartographer', 'lexicographer'],
    3,
    'A lexicographer writes or compiles dictionaries; the other options refer to different professions.',
  ),
  question(
    'ibps-po-p1-eng-009',
    'Sentence connectors',
    'easy',
    'Choose the correct word: ___ the heavy rain, the match continued as scheduled.',
    ['Despite', 'Because', 'Unless', 'During'],
    0,
    '“Despite” correctly introduces a contrast and is followed by the noun phrase “the heavy rain”.',
  ),
  question(
    'ibps-po-p1-eng-010',
    'Prepositions',
    'medium',
    'Choose the correct preposition: The committee arrived ___ a unanimous decision.',
    ['on', 'at', 'for', 'with'],
    1,
    'The standard collocation is “arrive at a decision”.',
  ),
  question(
    'ibps-po-p1-eng-011',
    'Conjunctions',
    'medium',
    'Choose the correct word: Hardly had the train left the station ___ the rain began.',
    ['than', 'then', 'when', 'while'],
    2,
    'The correlative construction is “hardly…when”; “no sooner…than” is a different construction.',
  ),
  question(
    'ibps-po-p1-eng-012',
    'Conditionals',
    'easy',
    'Choose the correct word: Unless you ___ now, you will miss the first bus.',
    ['left', 'will leave', 'had left', 'leave'],
    3,
    'In a first conditional clause introduced by “unless”, the simple present “leave” is used, not “will leave”.',
  ),
  question(
    'ibps-po-p1-eng-013',
    'Sentence correction',
    'easy',
    'Which option is grammatically correct in standard English?',
    ['Each of the applicants has submitted the form.', 'Each of the applicants have submitted the form.', 'Each of the applicant have submitted the form.', 'Each applicants has submitted the form.'],
    0,
    '“Each” is singular and takes “has”; “of the applicants” correctly uses a plural noun after the preposition.',
  ),
  question(
    'ibps-po-p1-eng-014',
    'Sentence improvement',
    'easy',
    'Choose the best replacement for the underlined idea: The officers discussed about the issue for an hour.',
    ['discussed on the issue', 'discussed the issue', 'discussed over the issue', 'had discussion the issue'],
    1,
    '“Discuss” is transitive and takes a direct object, so no preposition is needed before “the issue”.',
  ),
  question(
    'ibps-po-p1-eng-015',
    'Correlative conjunctions',
    'medium',
    'Choose the correct completion: No sooner had the bell rung ___ the students entered the hall.',
    ['when', 'then', 'than', 'while'],
    2,
    'The fixed correlative pair is “no sooner…than”.',
  ),
  question(
    'ibps-po-p1-eng-016',
    'Active and passive voice',
    'medium',
    'Choose the correct passive form of: The audit team will review the report tomorrow.',
    ['The report reviews tomorrow.', 'The report was reviewed tomorrow.', 'The report will review tomorrow.', 'The report will be reviewed tomorrow.'],
    3,
    'Future simple passive uses “will be” plus the past participle: “will be reviewed”.',
  ),
  question(
    'ibps-po-p1-eng-017',
    'Sentence arrangement',
    'medium',
    'Arrange the parts to form a coherent sentence: P: after reviewing the application; Q: the officer approved the loan; R: and verifying the documents; S: submitted by the customer.',
    ['Q-P-R-S', 'P-S-Q-R', 'Q-R-P-S', 'R-Q-S-P'],
    0,
    '“The officer approved the loan” begins the sentence, followed by the parallel actions “after reviewing… and verifying…”, with “submitted by the customer” modifying “documents”.',
  ),
  question(
    'ibps-po-p1-eng-018',
    'Sentence arrangement',
    'medium',
    'Arrange the sentences logically: A. The app then verifies the details. B. A customer first enters the account number. C. Finally, a confirmation appears on the screen. D. After verification, the customer enters the amount.',
    ['A-B-D-C', 'B-A-D-C', 'B-D-A-C', 'D-B-C-A'],
    1,
    'The sequence follows the process: enter account number, verify details, enter amount, then receive confirmation.',
  ),
  question(
    'ibps-po-p1-eng-019',
    'Sentence connectors',
    'medium',
    'Choose the best connector: The branch introduced token-based service; ___, average waiting time declined.',
    ['otherwise', 'nevertheless', 'consequently', 'similarly'],
    2,
    '“Consequently” correctly signals that the decline in waiting time was a result of the new service.',
  ),
  question(
    'ibps-po-p1-eng-020',
    'Inference',
    'medium',
    'A notice says: “Applications received after 5 p.m. on Friday will be processed on Monday.” What can be inferred?',
    ['Every Friday application is rejected.', 'The office remains open throughout the weekend.', 'Only online applications are processed on Monday.', 'A Friday application received at 6 p.m. will not be processed before Monday.'],
    3,
    'The notice directly places applications received after 5 p.m. Friday into Monday’s processing schedule.',
  ),
  question(
    'ibps-po-p1-eng-021',
    'Reading comprehension',
    'easy',
    'Read the passage: “Short, repeated study sessions usually strengthen memory better than one long session. Each review makes recall easier, especially when the reviews are separated by time.” What is the main idea?',
    ['Spaced review can improve memory.', 'Long sessions are always ineffective.', 'Recall depends only on natural ability.', 'Every subject needs the same study schedule.'],
    0,
    'The passage explains that repeated reviews separated by time help strengthen memory.',
  ),
  question(
    'ibps-po-p1-eng-022',
    'Reading comprehension',
    'medium',
    'Using the passage in the previous question, which practice would the author most likely recommend?',
    ['Reading a chapter once without revision', 'Revising a topic on several different days', 'Studying only on the night before an exam', 'Avoiding recall practice until the syllabus ends'],
    1,
    'Revising on different days applies the passage’s idea of repeated reviews separated by time.',
  ),
  question(
    'ibps-po-p1-eng-023',
    'Vocabulary in context',
    'easy',
    'In the sentence “Regular revision improves retention,” the word “retention” most nearly means:',
    ['speed of reading', 'length of a lesson', 'ability to remember', 'difficulty of a test'],
    2,
    'In this context, “retention” is the ability to keep information in memory.',
  ),
  question(
    'ibps-po-p1-eng-024',
    'Reading comprehension',
    'medium',
    'Read the statement: “Digital payments reduce the need to carry cash, but users must still protect passwords and verify recipients.” Which option is supported?',
    ['Digital payments remove every financial risk.', 'Passwords should be shared with trusted recipients.', 'Cash is no longer accepted anywhere.', 'Convenience should be accompanied by security checks.'],
    3,
    'The statement balances convenience with the need to protect credentials and verify recipients.',
  ),
  question(
    'ibps-po-p1-eng-025',
    'Cloze completion',
    'easy',
    'Choose the best word: For a long-term study plan, ___ is often more useful than a brief burst of effort.',
    ['consistency', 'hesitation', 'confusion', 'absence'],
    0,
    '“Consistency” fits the contrast between sustained effort and a brief burst of effort.',
  ),
  question(
    'ibps-po-p1-eng-026',
    'Cloze completion',
    'easy',
    'Choose the best word: A small amount of focused practice each day ___ steady progress.',
    ['prevents', 'produces', 'ignores', 'delays'],
    1,
    'Focused daily practice logically “produces” steady progress.',
  ),
  question(
    'ibps-po-p1-eng-027',
    'Cloze completion',
    'easy',
    'Choose the best connector: A useful timetable should be realistic ___ flexible.',
    ['but not', 'unless', 'and', 'because of'],
    2,
    '“And” correctly joins two compatible qualities that a useful timetable should possess.',
  ),
  question(
    'ibps-po-p1-eng-028',
    'Error spotting',
    'medium',
    'Identify the part containing an error: The principal asked / whether the forms / had been checked / before they was sent.',
    ['The principal asked', 'whether the forms', 'had been checked', 'before they was sent'],
    3,
    'The plural pronoun “they” requires “were”, so the final part should read “before they were sent”.',
  ),
  question(
    'ibps-po-p1-eng-029',
    'Spelling',
    'easy',
    'Choose the correctly spelled word.',
    ['accommodation', 'accomodation', 'acommodation', 'accommadation'],
    0,
    '“Accommodation” is spelled with double c and double m.',
  ),
  question(
    'ibps-po-p1-eng-030',
    'Word usage',
    'medium',
    'Choose the sentence in which “affect” is used correctly.',
    ['The new rule had a positive affect on attendance.', 'The new policy will affect all applicants.', 'The weather produced an affect in travel.', 'The medicine may effect how you feel.'],
    1,
    '“Affect” is correctly used as a verb meaning “influence”. In the other sentences, “effect” is needed as a noun, while the final sentence needs “affect”.',
  ),
];
