import type { Question } from '../questions';

const SOURCE = {
  kind: 'original' as const,
  reference: 'TakeMockTest original practice aligned to the IBPS Clerk CRP CSA-XVI 2026 Mains English Language section',
  url: 'https://www.ibps.in/wp-content/uploads/Notification_CRP_CSA_XVI-Final.pdf',
  checkedOn: '29 August 2026',
};

function question(
  id: string,
  topic: string,
  difficulty: 'easy' | 'medium' | 'hard',
  prompt: string,
  options: string[],
  correctIndex: number,
  explanation: string,
): Question {
  return {
    id,
    section: 'English Language',
    topic,
    difficulty,
    question: prompt,
    options,
    correctIndex,
    marks: 1,
    negativeMarking: 0.25,
    explanation,
    source: SOURCE,
  };
}

const RC_PASSAGE =
  'Partnerships between traditional banks and fintech startups have reshaped how many retail lending products reach customers in recent years. Rather than building every digital capability in-house, banks increasingly plug into fintech platforms that specialise in a single step of the lending journey, such as instant income verification or automated credit scoring. This division of labour has cut loan approval times dramatically for straightforward products like personal loans and consumer durable financing. It has also introduced new risks that regulators have had to catch up with, since a customer\'s data now often passes through several private technology vendors before a bank ever makes a lending decision. Some banks have responded by publishing clearer disclosures about which third parties handle customer data during the loan process, while others rely on contractual safeguards with their fintech partners instead of public disclosure. Industry analysts note that this partnership model is unlikely to reverse, since it lets banks compete on speed without abandoning their core role of holding the credit risk on their own books. ';

export const IBPS_CLERK_MAINS_ENGLISH_2: Question[] = [
  question('ibps-clerk-m2-en-001', 'Reading comprehension', 'medium', RC_PASSAGE + 'According to the passage, what has reshaped how retail lending products reach customers?', ['Partnerships between traditional banks and fintech startups', 'A ban on all digital lending', 'The closure of physical bank branches', 'A new government lending scheme'], 0, 'The passage opens by stating that partnerships between traditional banks and fintech startups have reshaped how retail lending products reach customers.'),
  question('ibps-clerk-m2-en-002', 'Reading comprehension', 'medium', RC_PASSAGE + 'What effect has this division of labour had on loan approval times, per the passage?', ['It has slowed them down significantly', 'It has cut them dramatically for straightforward products', 'It has had no measurable effect', 'It has made them unpredictable'], 1, 'The passage states this division of labour has cut loan approval times dramatically for straightforward products like personal loans and consumer durable financing.'),
  question('ibps-clerk-m2-en-003', 'Reading comprehension', 'hard', RC_PASSAGE + 'What new risk does the passage associate with this partnership model?', ['Fintech startups replacing banks entirely', 'A complete halt in loan disbursals', 'Customer data passing through several private vendors before a lending decision', 'Banks losing all their existing customers'], 2, 'The passage states this model has introduced new risks since customer data now often passes through several private technology vendors before a bank makes a lending decision.'),
  question('ibps-clerk-m2-en-004', 'Reading comprehension', 'medium', RC_PASSAGE + 'How have some banks responded to the data-handling risk, according to the passage?', ['By banning all fintech partnerships immediately', 'By transferring all lending decisions to regulators', 'By closing their retail lending business', 'By publishing clearer disclosures about which third parties handle customer data'], 3, 'The passage states some banks have responded by publishing clearer disclosures about which third parties handle customer data during the loan process.'),
  question('ibps-clerk-m2-en-005', 'Reading comprehension', 'hard', RC_PASSAGE + 'Why do industry analysts believe this partnership model is unlikely to reverse?', ['It lets banks compete on speed without abandoning their role of holding credit risk', 'Regulators have made it mandatory by law', 'Fintech startups have stopped operating independently', 'Customers no longer trust digital lending'], 0, 'The passage states analysts believe the model is unlikely to reverse since it lets banks compete on speed without abandoning their core role of holding the credit risk on their own books.'),
  question('ibps-clerk-m2-en-006', 'Cloze test', 'medium', 'The branch has _______ new measures to speed up account opening.', ['introducing', 'introduced', 'introduction', 'introduce'], 1, 'The sentence requires the past participle form after "has" to form the present perfect tense: "has introduced".'),
  question('ibps-clerk-m2-en-007', 'Cloze test', 'medium', 'Despite the delay, the vendor _______ to deliver the equipment on time.', ['manage', 'manages', 'managed', 'managing'], 2, 'The sentence describes a completed past action, so the simple past tense "managed" is correct.'),
  question('ibps-clerk-m2-en-008', 'Cloze test', 'hard', 'The officer, _______ report was praised, received an early promotion.', ['which', 'who', 'whom', 'whose'], 3, '"Whose" is the correct possessive relative pronoun to show that the report belongs to the officer.'),
  question('ibps-clerk-m2-en-009', 'Error spotting', 'medium', 'Identify the part with an error: (A) The board of directors / (B) have approved / (C) the merger proposal / (D) unanimously.', ['B', 'C', 'D', 'A'], 0, '"Board" is treated as a singular collective noun, so it should be "has approved", not "have approved" — the error is in part B.'),
  question('ibps-clerk-m2-en-010', 'Error spotting', 'hard', 'Identify the part with an error: (A) Either the manager or the clerks / (B) is responsible / (C) for the discrepancy / (D) in the ledger.', ['A', 'B', 'C', 'D'], 1, 'With "either...or", the verb agrees with the nearer subject; since "clerks" (plural) is closer, the verb should be "are responsible", not "is responsible" — the error is in part B.'),
  question('ibps-clerk-m2-en-011', 'Sentence improvement', 'medium', 'Improve the underlined part: "The auditor confirmed that the accounts _was_ accurate."', ['has been', 'was', 'were', 'is'], 2, 'The subject "accounts" is plural, so the correct verb is "were", not "was".'),
  question('ibps-clerk-m2-en-012', 'Sentence improvement', 'medium', 'Improve the underlined part: "He is one of the few officers who _has_ cleared the exam on the first attempt."', ['having', 'had', 'has', 'have'], 3, '"One of the few officers who" takes a plural verb agreeing with "officers", so "have" is correct, not "has".'),
  question('ibps-clerk-m2-en-013', 'Para jumbles', 'hard', 'Arrange the sentences in logical order: P. As a result, fraud detection now happens in real time rather than after the fact. Q. Banks have started using machine learning models to flag suspicious transactions. R. This shift has reduced the average time to detect fraudulent activity. S. Earlier, most fraud was identified only during manual monthly reconciliation.', ['SQRP', 'QSRP', 'SQPR', 'QRSP'], 0, 'The logical order begins with the earlier state (S: manual monthly reconciliation), the change (Q: adopting machine learning models), the resulting effect (R: reduced detection time), and finally the outcome (P: real-time detection): SQRP.'),
  question('ibps-clerk-m2-en-014', 'Para jumbles', 'hard', 'Arrange the sentences in logical order: P. This has made it easier for customers to switch banks without losing their transaction history. Q. Account portability has become a growing expectation among retail banking customers. R. Regulators have introduced frameworks requiring banks to share data securely on request. S. Building this infrastructure required significant investment from banks in secure data-sharing systems.', ['RQPS', 'QRSP', 'RQSP', 'QRPS'], 1, 'The order begins with the growing expectation (Q), the regulatory response (R: frameworks requiring data sharing), the investment required (S), and finally the resulting outcome (P: easier switching): QRSP.'),
  question('ibps-clerk-m2-en-015', 'Fill in the blanks', 'medium', 'The manager raised several _______ regarding the new reporting format.', ['objectedly', 'objection', 'objections', 'objecting'], 2, '"Several" requires a plural noun, and "objections" (plural) correctly fits the sentence.'),
  question('ibps-clerk-m2-en-016', 'Fill in the blanks', 'medium', 'The revised policy will come into _______ from the start of next month.', ['affect', 'effective', 'affected', 'effect'], 3, '"Come into effect" is the correct idiomatic phrase meaning to become operative.'),
  question('ibps-clerk-m2-en-017', 'Vocabulary in context', 'medium', 'The word "candid" is closest in meaning to:', ['Frank and honest', 'Vague', 'Deceptive', 'Secretive'], 0, '"Candid" means truthful and straightforward, i.e., frank and honest.'),
  question('ibps-clerk-m2-en-018', 'Vocabulary in context', 'medium', 'The word "redundant" is closest in meaning to:', ['Essential', 'No longer needed; superfluous', 'Highly valuable', 'Newly created'], 1, '"Redundant" describes something no longer needed or serving a useful purpose, i.e., superfluous.'),
  question('ibps-clerk-m2-en-019', 'Vocabulary in context', 'hard', 'Choose the word most nearly OPPOSITE in meaning to "diligent".', ['Careful', 'Hardworking', 'Negligent', 'Attentive'], 2, '"Diligent" means showing care and effort in one\'s work; its opposite is "negligent", lacking proper care.'),
  question('ibps-clerk-m2-en-020', 'One-word substitution', 'medium', 'A person who is an expert in the management of money is called:', ['Debtor', 'Creditor', 'Trustee', 'Financier'], 3, 'A "financier" is a person who is an expert in managing large sums of money or financial affairs.'),
  question('ibps-clerk-m2-en-021', 'One-word substitution', 'medium', 'A formal, official examination of financial records is called:', ['Audit', 'Anecdote', 'Prelude', 'Digest'], 0, 'An "audit" is a formal, official examination of an organisation\'s financial records.'),
  question('ibps-clerk-m2-en-022', 'Idioms and phrases', 'medium', 'What does the idiom "to cut corners" mean?', ['To increase spending sharply', 'To take shortcuts, often sacrificing quality', 'To design a building', 'To reduce staff'], 1, '"To cut corners" means to do something in the easiest or cheapest way, often at the expense of quality or safety.'),
  question('ibps-clerk-m2-en-023', 'Idioms and phrases', 'hard', 'What does the idiom "to make ends meet" mean?', ['To close a bank account', 'To finish a project on time', 'To have just enough money to cover basic expenses', 'To negotiate a business deal'], 2, '"To make ends meet" means to have just enough money to cover one\'s basic living expenses.'),
  question('ibps-clerk-m2-en-024', 'Sentence correction', 'hard', 'Choose the grammatically correct sentence.', ['Each of applicants was interviewed separately.', 'Each of the applicants were interviewed separately.', 'Each of the applicant were interviewed separately.', 'Each of the applicants was interviewed separately.'], 3, '"Each" is singular and requires a singular verb ("was interviewed"), making the third option grammatically correct.'),
  question('ibps-clerk-m2-en-025', 'Sentence correction', 'medium', 'Identify the grammatically correct sentence.', ['Neither the supervisor nor the trainees were notified of the audit.', 'Neither the supervisor nor the trainees was notified of the audit.', 'Neither the supervisor or the trainees were notified of the audit.', 'Neither supervisor nor trainees was notified of the audit.'], 0, 'With "neither...nor", the verb agrees with the subject closer to it; since "trainees" (plural) is closer, the verb should be "were", making the first option correct.'),
  question('ibps-clerk-m2-en-026', 'Connectors', 'medium', 'The branch recorded higher footfall this month; _______, average transaction value fell.', ['moreover', 'however', 'consequently', 'therefore'], 1, '"However" correctly signals a contrast between higher footfall and the unexpected fall in average transaction value.'),
  question('ibps-clerk-m2-en-027', 'Connectors', 'medium', 'The bank tightened its lending criteria _______ the rise in loan defaults last quarter.', ['unless', 'whereas', 'because of', 'although'], 2, '"Because of" correctly introduces the reason (rising loan defaults) for the bank\'s tightened lending criteria.'),
  question('ibps-clerk-m2-en-028', 'Reading comprehension', 'medium', RC_PASSAGE + 'What alternative to public disclosure do some banks rely on, per the passage?', ['Government-mandated audits', 'Complete withdrawal from digital lending', 'Manual verification of every transaction', 'Contractual safeguards with their fintech partners'], 3, 'The passage states some banks rely on contractual safeguards with their fintech partners instead of public disclosure.'),
  question('ibps-clerk-m2-en-029', 'Active and passive voice', 'medium', 'Choose the correct passive voice of: "The officer verified the loan application."', ['The loan application was verified by the officer.', 'The loan application verify by the officer.', 'The loan application is verified by the officer.', 'The loan application had been verifying by the officer.'], 0, 'The original sentence is in simple past active voice, so the correct passive form is "The loan application was verified by the officer."'),
  question('ibps-clerk-m2-en-030', 'Active and passive voice', 'hard', 'Choose the correct passive voice of: "The bank will launch a new digital lending platform next quarter."', ['A new digital lending platform was launched next quarter.', 'A new digital lending platform will be launched next quarter.', 'A new digital lending platform is launched next quarter.', 'A new digital lending platform will launch next quarter.'], 1, 'The original sentence uses the future tense with "will", so the correct passive form retains that tense: "will be launched".'),
  question('ibps-clerk-m2-en-031', 'Direct and indirect speech', 'medium', 'Convert to indirect speech: She said, "I will review the file tomorrow."', ['She said that she reviews the file tomorrow.', 'She says that she would review the file tomorrow.', 'She said that she would review the file the next day.', 'She said that she will review the file tomorrow.'], 2, 'In indirect speech, "will" changes to "would" and "tomorrow" changes to "the next day" when the reporting verb is in the past tense.'),
  question('ibps-clerk-m2-en-032', 'Direct and indirect speech', 'hard', 'Convert to indirect speech: He said, "I have submitted the form."', ['He said that he has submitted the form.', 'He says that he submitted the form.', 'He said that he submits the form.', 'He said that he had submitted the form.'], 3, 'In indirect speech, present perfect ("have submitted") changes to past perfect ("had submitted") when the reporting verb is in the past tense.'),
  question('ibps-clerk-m2-en-033', 'Spelling', 'easy', 'Identify the correctly spelled word.', ['Occasion', 'Occassionn', 'Occassion', 'Ocassion'], 0, 'The correct spelling is "Occasion", with a double "c" and single "s".'),
  question('ibps-clerk-m2-en-034', 'Spelling', 'easy', 'Choose the correctly spelled word.', ['Priviledge', 'Privilege', 'Priviledg', 'Previlege'], 1, 'The correct spelling is "Privilege", with no "d" before the final "ge".'),
  question('ibps-clerk-m2-en-035', 'Word usage', 'hard', 'Choose the correct word to complete the sentence: "The delay will _______ affect the loan disbursal timeline."', ['effect', 'affect', 'effectively', 'affectively'], 2, '"Effectively" is an adverb modifying the verb "affect" (meaning "in an effective manner"), fitting grammatically before the verb.'),
  question('ibps-clerk-m2-en-036', 'Word usage', 'medium', 'Choose the correct word: "The two branches decided to _______ their customer records for the audit."', ['poll', 'pole', 'pull', 'pool'], 3, '"Pool" means to combine records or resources together, fitting the context; "poll" refers to voting, "pole" is a rod, and "pull" means to drag.'),
  question('ibps-clerk-m2-en-037', 'Reading comprehension', 'medium', RC_PASSAGE + 'Which specific lending products does the passage mention as having faster approval times?', ['Personal loans and consumer durable financing', 'Home loans and education loans', 'Business loans only', 'Gold loans and vehicle loans'], 0, 'The passage specifically names personal loans and consumer durable financing as products with dramatically cut approval times.'),
  question('ibps-clerk-m2-en-038', 'Cloze test', 'medium', 'The board members _______ to revise the lending policy after the review.', ['agreement', 'agreed', 'agree', 'agreeing'], 1, 'The sentence describes a completed past action, so the simple past tense "agreed" is correct.'),
  question('ibps-clerk-m2-en-039', 'Error spotting', 'medium', 'Identify the part with an error: (A) Each of the loan officers / (B) are required to complete / (C) a monthly training module / (D) by the tenth of every month.', ['C', 'D', 'B', 'A'], 2, '"Each" is singular and requires a singular verb, so it should be "is required", not "are required" — the error is in part B.'),
  question('ibps-clerk-m2-en-040', 'Sentence improvement', 'medium', 'Improve the underlined part: "The committee _decided_ to postponing the audit until further notice."', ['decided to postponing', 'decided postponing', 'deciding to postpone', 'decided to postpone'], 3, '"Decided to" must be followed by the base form of the verb ("to postpone"), not the gerund ("postponing").'),
];
