import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'IBPS CRP RRBs XIV official notification (Advt. dated 27.09.2025), Mains syllabus — English Language section (Officer Scale I)',
  url: 'https://www.ibps.in/wp-content/uploads/CRP-RRBs-XIV_Final_AD-27.09.25.pdf',
  checkedOn: '27 August 2026',
};

const RC_PASSAGE =
  "Read the following passage carefully and answer the questions that follow.\n\nPriority sector lending has been one of the most consequential tools in Indian banking regulation, though it rarely draws public attention outside policy circles. Under this framework, banks operating in India are required to direct a specified proportion of their total lending toward sectors the central bank considers critical for broad-based economic development, chief among them agriculture, micro and small enterprises, and housing for lower-income borrowers.\n\nThe rationale is straightforward: left entirely to market forces, credit tends to flow toward borrowers who already have collateral, credit history, and steady income, leaving farmers, small traders, and first-time entrepreneurs at a persistent disadvantage. Regional Rural Banks, given their village-level presence and mandate, have historically carried a disproportionate share of this priority-sector burden compared with larger commercial banks headquartered in cities.\n\nMeeting these targets is not without friction for the lending institution. Agricultural loans, in particular, carry higher default risk during poor monsoon years, and the smaller ticket sizes typical of priority-sector lending raise the administrative cost per rupee disbursed relative to a single large corporate loan. Even so, most economists studying rural credit access argue that without a mandated minimum, the sectors most in need of formal credit would be systematically underserved, pushing borrowers back toward informal moneylenders charging far steeper rates. Whatever its costs to individual banks, priority sector lending remains, on balance, one of the more effective interventions in extending formal finance to those who would otherwise be excluded from it.\n\n";

const CLOZE_PASSAGE =
  'In the following passage, four numbered blanks have been left. Choose the option that best fits each blank.\n\nRegional Rural Banks were originally (1)______ to extend banking services to underserved rural populations who had limited (2)______ to formal credit. Over the decades, their mandate has (3)______ to include priority-sector lending targets alongside general banking services. Critics argue that without continued government support, many of these banks would struggle to remain (4)______ in low-margin rural markets.\n\n';

export const IBPS_RRB_OFFICER_SCALE_1_MAINS_ENGLISH_LANGUAGE_1: Question[] = [
  { id: 'ibps-rrb-os1-m1-en-001', section: 'English Language', topic: 'Reading comprehension', difficulty: 'medium', question: `${RC_PASSAGE}Why does credit tend to flow away from farmers and small traders under pure market forces, according to the passage?`, options: ['Such borrowers typically lack collateral, credit history, and steady income', 'Farmers and small traders are legally barred from taking bank loans', 'Banks are required by regulation to avoid lending to rural borrowers', 'Farmers and small traders always prefer informal moneylenders'], correctIndex: 0, explanation: 'The passage states that credit "tends to flow toward borrowers who already have collateral, credit history, and steady income, leaving farmers, small traders, and first-time entrepreneurs at a persistent disadvantage."', source },
  { id: 'ibps-rrb-os1-m1-en-002', section: 'English Language', topic: 'Reading comprehension', difficulty: 'easy', question: `${RC_PASSAGE}Which type of bank has historically carried a disproportionate share of the priority-sector lending burden, according to the passage?`, options: ['Regional Rural Banks', 'Large commercial banks headquartered in cities', 'Foreign banks operating in India', 'Cooperative credit societies'], correctIndex: 0, explanation: 'The passage states that "Regional Rural Banks, given their village-level presence and mandate, have historically carried a disproportionate share of this priority-sector burden."', source },
  { id: 'ibps-rrb-os1-m1-en-003', section: 'English Language', topic: 'Reading comprehension', difficulty: 'medium', question: `${RC_PASSAGE}What specific risk does the passage associate with agricultural loans?`, options: ['Higher default risk during poor monsoon years', 'Complete immunity from default risk', 'Lower administrative cost per rupee disbursed', 'Guaranteed repayment regardless of harvest outcomes'], correctIndex: 0, explanation: 'The passage notes that "agricultural loans, in particular, carry higher default risk during poor monsoon years."', source },
  { id: 'ibps-rrb-os1-m1-en-004', section: 'English Language', topic: 'Reading comprehension', difficulty: 'medium', question: `${RC_PASSAGE}According to the passage, what alternative do borrowers turn to when formal credit is unavailable?`, options: ['Informal moneylenders charging far steeper rates', 'Government subsidy schemes with no interest', 'International lending institutions', 'Cooperative societies offering interest-free loans'], correctIndex: 0, explanation: 'The passage warns that without a mandated minimum, underserved borrowers would be "pushing borrowers back toward informal moneylenders charging far steeper rates."', source },
  { id: 'ibps-rrb-os1-m1-en-005', section: 'English Language', topic: 'Reading comprehension', difficulty: 'medium', question: `${RC_PASSAGE}Which of the following best describes the author's overall assessment of priority sector lending?`, options: ['Despite costs to banks, it remains one of the more effective interventions for extending formal finance to excluded borrowers', 'It has entirely failed to achieve its intended goals', 'It benefits only large corporate borrowers, not rural ones', 'It should be abolished immediately due to high administrative costs'], correctIndex: 0, explanation: 'The passage concludes that "whatever its costs to individual banks, priority sector lending remains, on balance, one of the more effective interventions in extending formal finance to those who would otherwise be excluded from it."', source },
  { id: 'ibps-rrb-os1-m1-en-006', section: 'English Language', topic: 'Vocabulary in context', difficulty: 'medium', question: `${RC_PASSAGE}Choose the word closest in meaning to 'disproportionate' as used in the passage ("carried a disproportionate share of this priority-sector burden").`, options: ['Excessive', 'Minimal', 'Balanced', 'Negligible'], correctIndex: 0, explanation: "In this context, 'disproportionate' means an excessive or uneven share relative to what would be expected.", source },
  { id: 'ibps-rrb-os1-m1-en-007', section: 'English Language', topic: 'Vocabulary in context', difficulty: 'medium', question: `${RC_PASSAGE}Choose the word most opposite in meaning to 'mandated' as used in the passage ("without a mandated minimum").`, options: ['Optional', 'Required', 'Compulsory', 'Enforced'], correctIndex: 0, explanation: "'Mandated' means required by authority; its opposite in this context is 'optional', meaning not compulsory.", source },
  { id: 'ibps-rrb-os1-m1-en-008', section: 'English Language', topic: 'Cloze test', difficulty: 'medium', question: `${CLOZE_PASSAGE}Choose the best word for blank (1).`, options: ['established', 'dissolved', 'restricted', 'abandoned'], correctIndex: 0, explanation: "The sentence describes the original purpose of Regional Rural Banks, so 'established' (set up) fits blank (1).", source },
  { id: 'ibps-rrb-os1-m1-en-009', section: 'English Language', topic: 'Cloze test', difficulty: 'medium', question: `${CLOZE_PASSAGE}Choose the best word for blank (2).`, options: ['access', 'interest', 'knowledge', 'opposition'], correctIndex: 0, explanation: "'Limited access to formal credit' is the standard phrase describing underserved populations, fitting blank (2).", source },
  { id: 'ibps-rrb-os1-m1-en-010', section: 'English Language', topic: 'Cloze test', difficulty: 'medium', question: `${CLOZE_PASSAGE}Choose the best word for blank (3).`, options: ['expanded', 'shrunk', 'vanished', 'reversed'], correctIndex: 0, explanation: "The mandate growing to include new targets over decades indicates it has 'expanded'.", source },
  { id: 'ibps-rrb-os1-m1-en-011', section: 'English Language', topic: 'Cloze test', difficulty: 'medium', question: `${CLOZE_PASSAGE}Choose the best word for blank (4).`, options: ['hostile', 'irrelevant', 'illegal', 'viable'], correctIndex: 3, explanation: "Struggling to remain 'viable' (sustainable/functional) in low-margin markets fits the sentence's concern about financial sustainability.", source },
  { id: 'ibps-rrb-os1-m1-en-012', section: 'English Language', topic: 'Error spotting', difficulty: 'medium', question: 'Read the sentence below, divided into three parts. Identify the part that contains a grammatical error, or select "No error" if there is none.\n\nEach of the loan officers (A) / have completed (B) / their annual compliance training. (C)', options: ['A', 'C', 'B', 'No error'], correctIndex: 2, explanation: "'Each' takes a singular verb, so it should be 'has completed', not 'have completed' — the error is in part B.", source },
  { id: 'ibps-rrb-os1-m1-en-013', section: 'English Language', topic: 'Error spotting', difficulty: 'medium', question: 'Read the sentence below, divided into three parts. Identify the part that contains a grammatical error, or select "No error" if there is none.\n\nThe committee have decided (A) / to revise the lending policy (B) / before the next fiscal year. (C)', options: ['B', 'A', 'C', 'No error'], correctIndex: 1, explanation: "'Committee' as a single collective unit takes a singular verb, so it should be 'has decided', not 'have decided' — the error is in part A.", source },
  { id: 'ibps-rrb-os1-m1-en-014', section: 'English Language', topic: 'Error spotting', difficulty: 'medium', question: 'Read the sentence below, divided into three parts. Identify the part that contains a grammatical error, or select "No error" if there is none.\n\nNeither the manager nor the officers (A) / was informed (B) / about the change in procedure. (C)', options: ['A', 'C', 'No error', 'B'], correctIndex: 3, explanation: "With 'neither...nor', the verb agrees with the nearer subject ('officers', plural), so it should be 'were informed', not 'was informed' — the error is in part B.", source },
  { id: 'ibps-rrb-os1-m1-en-015', section: 'English Language', topic: 'Error spotting', difficulty: 'medium', question: 'Read the sentence below, divided into three parts. Identify the part that contains a grammatical error, or select "No error" if there is none.\n\nShe is one of the officers (A) / who have handled (B) / such a large loan portfolio. (C)', options: ['A', 'B', 'No error', 'C'], correctIndex: 2, explanation: "'Who' refers back to 'officers' (plural), so the plural verb 'have handled' is correct. The sentence has no error.", source },
  { id: 'ibps-rrb-os1-m1-en-016', section: 'English Language', topic: 'Sentence improvement', difficulty: 'medium', question: 'Improve the underlined part of the sentence: "He is one of the most _experience officer_ in the branch."', options: ['experience officers', 'experienced officers', 'experiencing officer', 'experienced officer'], correctIndex: 1, explanation: "The adjective form 'experienced' is needed, and 'one of the most X' requires a plural noun, giving 'experienced officers'.", source },
  { id: 'ibps-rrb-os1-m1-en-017', section: 'English Language', topic: 'Sentence improvement', difficulty: 'medium', question: 'Improve the underlined part of the sentence: "_Inspite_ of the heavy rainfall, the branch remained open."', options: ['Despite of', 'Regardless', 'In-spite', 'In spite'], correctIndex: 3, explanation: "'In spite of' is the correct standard phrase, written as two separate words, not the single word 'Inspite'.", source },
  { id: 'ibps-rrb-os1-m1-en-018', section: 'English Language', topic: 'Sentence improvement', difficulty: 'medium', question: 'Improve the underlined part of the sentence: "The customer was _too much satisfied_ with the service."', options: ['too much satisfying', 'so much satisfied that', 'extremely satisfied', 'too satisfying'], correctIndex: 2, explanation: "'Too much' cannot directly modify a past participle like 'satisfied' in standard usage; 'extremely satisfied' is the correct form.", source },
  { id: 'ibps-rrb-os1-m1-en-019', section: 'English Language', topic: 'Fill in the blanks', difficulty: 'medium', question: 'Fill in the two blanks with the most appropriate pair of words: "The bank has ______ new lending norms and ______ the loan approval process for small farmers."', options: ['abolished, complicated', 'introduced, simplified', 'ignored, delayed', 'introduced, complicated'], correctIndex: 1, explanation: "'Introduced' and 'simplified' fit the positive tone of a bank updating norms and easing the approval process.", source },
  { id: 'ibps-rrb-os1-m1-en-020', section: 'English Language', topic: 'Fill in the blanks', difficulty: 'medium', question: 'Fill in the two blanks with the most appropriate pair of words: "Despite the ______ in crop prices, farmers in the region reported a ______ harvest season."', options: ['increase, poor', 'decline, poor', 'surge, bad', 'decline, good'], correctIndex: 3, explanation: "'Despite' signals a contrast, so a 'decline' in prices paired with a still-'good' harvest season fits the sentence logic.", source },
  { id: 'ibps-rrb-os1-m1-en-021', section: 'English Language', topic: 'Fill in the blanks', difficulty: 'medium', question: 'Fill in the two blanks with the most appropriate pair of words: "The officer ______ the collateral documents before ______ the loan disbursement."', options: ['ignored, approving', 'verified, rejecting the unrelated', 'verified, approving', 'signed, verifying'], correctIndex: 2, explanation: "'Verified...before approving' forms a logical sequence: document verification precedes disbursement approval.", source },
  { id: 'ibps-rrb-os1-m1-en-022', section: 'English Language', topic: 'One-word substitution', difficulty: 'medium', question: "Choose the word that means \"a person who guarantees to repay another person's debt if they default.\"", options: ['Debtor', 'Guarantor', 'Creditor', 'Trustee'], correctIndex: 1, explanation: 'A guarantor is a person who agrees to be responsible for another person\'s debt if that person fails to pay.', source },
  { id: 'ibps-rrb-os1-m1-en-023', section: 'English Language', topic: 'One-word substitution', difficulty: 'medium', question: 'Choose the word that means "one who audits financial accounts to verify their accuracy."', options: ['Accountant', 'Cashier', 'Broker', 'Auditor'], correctIndex: 3, explanation: 'An auditor examines and verifies the accuracy of financial accounts and records.', source },
  { id: 'ibps-rrb-os1-m1-en-024', section: 'English Language', topic: 'One-word substitution', difficulty: 'medium', question: 'Choose the word that means "a written order directing a bank to pay a specified sum from one\'s account."', options: ['Invoice', 'Receipt', 'Cheque', 'Voucher'], correctIndex: 2, explanation: 'A cheque is a written order instructing a bank to pay a specified amount from the account holder\'s funds.', source },
  { id: 'ibps-rrb-os1-m1-en-025', section: 'English Language', topic: 'One-word substitution', difficulty: 'medium', question: 'Choose the word that means "one who has retired from service and receives a periodic payment."', options: ['Employee', 'Pensioner', 'Trainee', 'Apprentice'], correctIndex: 1, explanation: 'A pensioner is a retired person who receives a pension, a periodic payment, in place of a salary.', source },
  { id: 'ibps-rrb-os1-m1-en-026', section: 'English Language', topic: 'Synonym', difficulty: 'medium', question: 'Choose the word closest in meaning to DILIGENT.', options: ['Careless', 'Lazy', 'Negligent', 'Industrious'], correctIndex: 3, explanation: 'Diligent means showing persistent, careful effort, closest to "industrious".', source },
  { id: 'ibps-rrb-os1-m1-en-027', section: 'English Language', topic: 'Synonym', difficulty: 'medium', question: 'Choose the word closest in meaning to VIABLE.', options: ['Impossible', 'Unworkable', 'Feasible', 'Doubtful'], correctIndex: 2, explanation: 'Viable means capable of working successfully, closest to "feasible".', source },
  { id: 'ibps-rrb-os1-m1-en-028', section: 'English Language', topic: 'Synonym', difficulty: 'medium', question: 'Choose the word closest in meaning to SCRUTINIZE.', options: ['Ignore', 'Examine', 'Overlook', 'Skim'], correctIndex: 1, explanation: 'Scrutinize means to examine something closely and carefully.', source },
  { id: 'ibps-rrb-os1-m1-en-029', section: 'English Language', topic: 'Synonym', difficulty: 'medium', question: 'Choose the word closest in meaning to ASTUTE.', options: ['Naive', 'Foolish', 'Careless', 'Shrewd'], correctIndex: 3, explanation: 'Astute means having sharp judgment, closest to "shrewd".', source },
  { id: 'ibps-rrb-os1-m1-en-030', section: 'English Language', topic: 'Antonym', difficulty: 'medium', question: 'Choose the word most opposite in meaning to SOLVENT.', options: ['Wealthy', 'Prosperous', 'Insolvent', 'Stable'], correctIndex: 2, explanation: 'Solvent means having enough money to pay debts; its opposite is "insolvent", meaning unable to pay debts.', source },
  { id: 'ibps-rrb-os1-m1-en-031', section: 'English Language', topic: 'Antonym', difficulty: 'medium', question: 'Choose the word most opposite in meaning to LIBERAL (as in "a liberal lending policy").', options: ['Generous', 'Strict', 'Flexible', 'Lenient'], correctIndex: 1, explanation: 'In the context of a lending policy, "liberal" (generous, permissive) is opposite to "strict".', source },
  { id: 'ibps-rrb-os1-m1-en-032', section: 'English Language', topic: 'Antonym', difficulty: 'medium', question: 'Choose the word most opposite in meaning to AMPLE.', options: ['Abundant', 'Plentiful', 'Generous', 'Insufficient'], correctIndex: 3, explanation: 'Ample means more than enough; its opposite is "insufficient", meaning not enough.', source },
  { id: 'ibps-rrb-os1-m1-en-033', section: 'English Language', topic: 'Antonym', difficulty: 'medium', question: 'Choose the word most opposite in meaning to ABUNDANT.', options: ['Plentiful', 'Copious', 'Scarce', 'Ample'], correctIndex: 2, explanation: 'Abundant means existing in large quantities; its opposite is "scarce", meaning insufficient or rare.', source },
  { id: 'ibps-rrb-os1-m1-en-034', section: 'English Language', topic: 'Idioms and phrases', difficulty: 'medium', question: 'Choose the meaning of the idiom: "To make ends meet"', options: ['To finish a task ahead of schedule', 'To manage financially with limited resources', 'To reconcile two opposing viewpoints', 'To close a business permanently'], correctIndex: 1, explanation: "'To make ends meet' means to manage to live within one's financial means, especially with limited income.", source },
  { id: 'ibps-rrb-os1-m1-en-035', section: 'English Language', topic: 'Idioms and phrases', difficulty: 'medium', question: 'Choose the meaning of the idiom: "To cut corners"', options: ['To take a very long route to reach a destination', 'To negotiate a lower price aggressively', 'To finish a project exactly on schedule', 'To do something in the cheapest or easiest way, often sacrificing quality'], correctIndex: 3, explanation: "'To cut corners' means to do something in the easiest or cheapest way possible, often at the expense of quality or standards.", source },
  { id: 'ibps-rrb-os1-m1-en-036', section: 'English Language', topic: 'Idioms and phrases', difficulty: 'medium', question: 'Choose the meaning of the idiom: "To keep something at bay"', options: ['To store something securely in a vault', 'To delay a decision indefinitely', 'To prevent something undesirable from approaching or happening', 'To openly welcome a challenge'], correctIndex: 2, explanation: "'To keep something at bay' means to prevent something threatening or undesirable from getting closer or happening.", source },
  { id: 'ibps-rrb-os1-m1-en-037', section: 'English Language', topic: 'Active passive voice', difficulty: 'medium', question: 'Choose the correct passive voice of: "The officer sanctioned the loan within a week."', options: ['The loan is sanctioned by the officer within a week.', 'The loan was sanctioned by the officer within a week.', 'The loan had sanctioned the officer within a week.', 'The officer was sanctioned by the loan within a week.'], correctIndex: 1, explanation: 'In the passive voice, the object "the loan" becomes the subject, and the verb takes the correct past-tense passive form: "was sanctioned by".', source },
  { id: 'ibps-rrb-os1-m1-en-038', section: 'English Language', topic: 'Active passive voice', difficulty: 'medium', question: 'Choose the correct passive voice of: "They will review the credit policy next month."', options: ['The credit policy is reviewed by them next month.', 'The credit policy will review them next month.', 'The credit policy had been reviewed by them next month.', 'The credit policy will be reviewed by them next month.'], correctIndex: 3, explanation: 'For future simple tense, the passive form uses "will be + past participle": "The credit policy will be reviewed by them next month."', source },
  { id: 'ibps-rrb-os1-m1-en-039', section: 'English Language', topic: 'Direct indirect speech', difficulty: 'medium', question: 'Choose the correct indirect speech of: He said, "I have verified all the documents."', options: ['He said that I have verified all the documents.', 'He said that he has verified all the documents.', 'He said that he had verified all the documents.', 'He said that he verifies all the documents.'], correctIndex: 2, explanation: "In indirect speech, present perfect shifts to past perfect, and 'I' becomes 'he'.", source },
  { id: 'ibps-rrb-os1-m1-en-040', section: 'English Language', topic: 'Direct indirect speech', difficulty: 'medium', question: 'Choose the correct indirect speech of: She said, "Can you process this application today?"', options: ['She said that can you process this application today.', 'She asked if I could process that application that day.', 'She asked that I can process this application today.', 'She asked if I can process that application that day.'], correctIndex: 1, explanation: "In indirect speech, a yes/no question introduces 'if'/'whether', 'can' shifts to 'could', 'this' shifts to 'that', and 'today' shifts to 'that day'.", source },
];
