import type { Question } from '../questions';

const SOURCE = {
  kind: 'original' as const,
  reference: 'TakeMockTest original practice aligned to the IBPS PO XVI Mains English Language section',
  url: 'https://www.ibps.in/wp-content/uploads/Detailed-Notification_CRP-PO-XVI_Final_V1_30.06.2026.pdf',
  checkedOn: '3 August 2026',
};

const MARKS = 20 / 40;
const PENALTY = MARKS / 4;

function question(
  id: string,
  topic: string,
  difficulty: 'easy' | 'medium' | 'hard',
  prompt: string,
  options: string[],
  correctIndex: number,
  explanation: string,
): Question {
  return {
    id,
    section: 'English Language',
    topic,
    difficulty,
    question: prompt,
    options,
    correctIndex,
    marks: MARKS,
    negativeMarking: PENALTY,
    explanation,
    source: SOURCE,
  };
}

export const IBPS_PO_MAINS_ENGLISH_1: Question[] = [
  question('ibps-po-m-en-001', 'Subject-verb agreement', 'easy', 'Choose the correct completion: Each of the applicants ___ required to submit two identity documents.', ['have', 'are', 'were', 'is'], 3, '"Each" is a singular indefinite pronoun, so it takes the singular verb "is", regardless of the plural noun that follows it.'),
  question('ibps-po-m-en-002', 'Tense', 'medium', 'Choose the correct completion: By the time the auditor arrives tomorrow, the clerk ___ all the ledgers.', ['will complete', 'has completed', 'completed', 'will have completed'], 3, 'A future action completed before another future point uses the future perfect tense: "will have completed".'),
  question('ibps-po-m-en-003', 'Preposition', 'easy', 'Choose the correct preposition: The branch manager is responsible ___ all cash transactions at the counter.', ['to', 'with', 'for', 'of'], 2, '"Responsible" is idiomatically followed by the preposition "for" when referring to a duty or task.'),
  question('ibps-po-m-en-004', 'Synonym', 'medium', 'Select the option nearest in meaning to the word "meticulous".', ['Careless', 'Hasty', 'Indifferent', 'Thorough'], 3, '"Meticulous" means showing great attention to detail, which is closest in meaning to "thorough".'),
  question('ibps-po-m-en-005', 'Antonym', 'medium', 'Choose the word opposite in meaning to "generous".', ['Humble', 'Kind', 'Wealthy', 'Stingy'], 3, '"Generous" means willing to give freely; its opposite is "stingy", meaning unwilling to give or spend.'),
  question('ibps-po-m-en-006', 'Idioms', 'medium', 'What does the idiom "to bite the bullet" mean?', ['To avoid a difficult situation', 'To eat something quickly', 'To face a difficult or unpleasant situation with courage', 'To break a promise'], 2, '"To bite the bullet" means to face a painful or difficult situation with courage and resolve.'),
  question('ibps-po-m-en-007', 'One-word substitution', 'medium', 'Choose the word that means "a person who is extremely difficult to please".', ['Generous', 'Humble', 'Fastidious', 'Naive'], 2, '"Fastidious" describes someone who is excessively particular or difficult to please, especially about small details.'),
  question('ibps-po-m-en-008', 'Error spotting', 'medium', 'Identify the part containing an error: She don\'t like (A) / to attend the weekly meetings (B) / because they usually run (C) / much longer than scheduled (D).', ['Part B', 'Part C', 'Part D', 'Part A'], 3, 'The subject "She" is third-person singular and requires "doesn\'t", not "don\'t". The error is in Part A.'),
  question('ibps-po-m-en-009', 'Sentence improvement', 'medium', 'Improve the underlined part: "Each of the students have submitted their assignment on time."', ['have submitted their assignment', 'has submitted their assignment', 'having submitted its assignment', 'have submit their assignments'], 1, '"Each" takes a singular verb, so "have submitted" should be corrected to "has submitted".'),
  question('ibps-po-m-en-010', 'Active and passive voice', 'medium', 'Choose the correct passive form of: "The branch manager approved the loan application."', ['The branch manager was approved by the loan application.', 'The loan application is approved by the branch manager.', 'The loan application approved the branch manager.', 'The loan application was approved by the branch manager.'], 3, 'The original sentence is in the past simple active voice, so the passive form uses "was" plus the past participle: "was approved", with the object of the active sentence becoming the subject.'),
  question('ibps-po-m-en-011', 'Para-jumbles', 'hard', 'Arrange the parts to form a coherent sentence: P: before the branch closed for the day; Q: the cashier reconciled the cash drawer; R: and verified every receipt; S: carefully counting each note.', ['Q, S, R, P', 'P, Q, R, S', 'S, Q, P, R', 'Q, R, S, P'], 0, 'The logical order is: the cashier reconciled the cash drawer (Q), carefully counting each note (S), and verified every receipt (R), before the branch closed for the day (P) — giving Q, S, R, P.'),
  question('ibps-po-m-en-012', 'Connectors', 'medium', 'Choose the best connector: The audit was delayed by two days; ___, the final report was still submitted on time.', ['therefore', 'moreover', 'nevertheless', 'similarly'], 2, '"Nevertheless" signals a contrast between the delay and the on-time submission that followed despite it.'),
  question('ibps-po-m-en-013', 'Cloze test', 'easy', 'Choose the correct word: The new policy will ___ effect from the first of next month.', ['take', 'make', 'do', 'have'], 0, '"Take effect" is the standard idiomatic phrase meaning to become operative or valid.'),
  question('ibps-po-m-en-014', 'Spelling', 'easy', 'Pick the option that is spelled correctly.', ['Occassion', 'Occasion', 'Ocassion', 'Occaision'], 1, '"Occasion" is the correct spelling, with a single "c" doubled and a single "s".'),
  question('ibps-po-m-en-015', 'Idioms', 'medium', 'What does the idiom "to get cold feet" mean?', ['To feel unwell', 'To lose one\'s nerve or become anxious about doing something', 'To travel to a cold place', 'To finish a task quickly'], 2, '"To get cold feet" means to become nervous or lose confidence about following through with a plan.'),
  question('ibps-po-m-en-016', 'One-word substitution', 'medium', 'Choose the word that means "a statement that cannot be understood in more than one way".', ['Ambiguous', 'Unambiguous', 'Vague', 'Redundant'], 1, '"Unambiguous" describes something having only one clear interpretation, the opposite of "ambiguous".'),
  question('ibps-po-m-en-017', 'Synonym', 'medium', 'Select the option nearest in meaning to the word "prudent".', ['Reckless', 'Careful', 'Wasteful', 'Impulsive'], 1, '"Prudent" means acting with care and thought for the future, closest in meaning to "careful".'),
  question('ibps-po-m-en-018', 'Antonym', 'medium', 'Choose the word opposite in meaning to "transparent".', ['Clear', 'Visible', 'Obscure', 'Honest'], 2, '"Transparent" means easy to see through or understand; its opposite is "obscure", meaning unclear or hard to understand.'),
  question('ibps-po-m-en-019', 'Preposition', 'easy', 'Choose the correct preposition: The customer complained ___ the delay in processing the refund.', ['about', 'to', 'for', 'at'], 0, '"Complain about" is the standard idiomatic construction used when describing the subject of a complaint.'),
  question('ibps-po-m-en-020', 'Tense', 'medium', 'Choose the correct completion: I ___ in this bank for over ten years before I was transferred last month.', ['work', 'have worked', 'had worked', 'am working'], 2, 'An action completed before another past event ("was transferred") uses the past perfect tense: "had worked".'),
  question('ibps-po-m-en-021', 'Error spotting', 'medium', 'Identify the part containing an error: Neither of the two clerks (A) / were available (B) / to process the request (C) / before the branch closed (D).', ['Part A', 'Part C', 'Part D', 'Part B'], 3, '"Neither" is a singular pronoun and requires the singular verb "was", not "were". The error is in Part B.'),
  question('ibps-po-m-en-022', 'Sentence improvement', 'medium', 'Improve the underlined part: "The number of complaints have increased sharply this quarter."', ['have increased sharply', 'has increased sharply', 'having increase sharply', 'have increase sharply'], 1, '"The number of" takes a singular verb, so "have increased" should be corrected to "has increased".'),
  question('ibps-po-m-en-023', 'Active and passive voice', 'medium', 'Choose the correct active form of: "The report was reviewed by the compliance officer."', ['The compliance officer reviews the report.', 'The compliance officer reviewed the report.', 'The report reviews the compliance officer.', 'The compliance officer was reviewing the report.'], 1, 'The passive "was reviewed" is past simple, so the active form uses the past simple verb with the doer as subject: "The compliance officer reviewed the report."'),
  question('ibps-po-m-en-024', 'Para-jumbles', 'hard', 'Arrange the sentences logically: A. The customer then enters the one-time password. B. A verification code is sent to the registered mobile number. C. Finally, the transaction is confirmed on screen. D. The customer first initiates a fund transfer online.', ['D, B, A, C', 'A, B, C, D', 'B, D, A, C', 'D, A, B, C'], 0, 'The logical sequence is: the customer initiates the transfer (D), a verification code is sent (B), the customer enters the OTP (A), and the transaction is confirmed (C) — giving D, B, A, C.'),
  question('ibps-po-m-en-025', 'Connectors', 'medium', 'Choose the best connector: The new software reduced processing time; ___, staff could handle more customers each day.', ['consequently', 'although', 'unlike', 'whereas'], 0, '"Consequently" signals that the second clause is a direct result of the first — reduced processing time led to serving more customers.'),
  question('ibps-po-m-en-026', 'Cloze test', 'easy', 'Choose the correct word: Customers are advised to keep their passbooks ___ date by visiting the branch periodically.', ['up to', 'in', 'on', 'at'], 0, '"Up to date" is the standard idiomatic phrase meaning current or updated.'),
  question('ibps-po-m-en-027', 'Spelling', 'easy', 'Identify the correctly spelled word from the options below.', ['Recieve', 'Receeve', 'Receive', 'Receve'], 2, 'The correct spelling is "Receive", following the "i before e except after c" rule.'),
  question('ibps-po-m-en-028', 'Idioms', 'medium', 'What does the idiom "to keep something under wraps" mean?', ['To wrap a gift carefully', 'To store something in a cold place', 'To reveal information publicly', 'To keep something secret or hidden'], 3, '"To keep something under wraps" means to keep it secret or confidential until it is ready to be revealed.'),
  question('ibps-po-m-en-029', 'One-word substitution', 'medium', 'Choose the word that means "one who spends money extravagantly and wastefully".', ['Miser', 'Spendthrift', 'Philanthropist', 'Ascetic'], 1, 'A "spendthrift" is someone who spends money in a wasteful or extravagant way — the opposite of a "miser".'),
  question('ibps-po-m-en-030', 'Synonym', 'medium', 'Choose the word closest in meaning to "candid".', ['Deceptive', 'Frank', 'Reserved', 'Formal'], 1, '"Candid" means open, honest, and straightforward, closest in meaning to "frank".'),
  question('ibps-po-m-en-031', 'Antonym', 'medium', 'Choose the word opposite in meaning to "diligent".', ['Hardworking', 'Careful', 'Lazy', 'Punctual'], 2, '"Diligent" means showing care and effort in one\'s work; its opposite is "lazy".'),
  question('ibps-po-m-en-032', 'Preposition', 'easy', 'Choose the correct preposition: The bank is planning to invest ___ new digital infrastructure next year.', ['on', 'at', 'to', 'in'], 3, '"Invest in" is the standard idiomatic construction used with the thing being invested in.'),
  question('ibps-po-m-en-033', 'Tense', 'medium', 'Choose the correct completion: The committee ___ its decision by the time the shareholders arrive for the meeting.', ['will have announced', 'announces', 'is announcing', 'will announce'], 0, 'An action completed before another future event uses the future perfect tense: "will have announced".'),
  question('ibps-po-m-en-034', 'Error spotting', 'medium', 'Identify the part containing an error: The manager, along with his two assistants, (A) / were reviewing the quarterly figures (B) / when the fire alarm (C) / suddenly went off (D).', ['Part A', 'Part C', 'Part D', 'Part B'], 3, 'A phrase introduced by "along with" does not change the number of the main subject. The subject "The manager" is singular, so the verb should be "was reviewing", not "were reviewing". The error is in Part B.'),
  question('ibps-po-m-en-035', 'Sentence improvement', 'medium', 'Improve the underlined part: "If I was you, I would double-check the figures before submitting the report."', ['If I was you', 'If I were you', 'If I am you', 'If I would be you'], 1, 'This is a hypothetical, unreal condition, which requires the subjunctive mood: "If I were you", not "If I was you".'),
  question('ibps-po-m-en-036', 'Active and passive voice', 'medium', 'Choose the correct passive form of: "The clerk had already filed the documents before the inspection."', ['The documents had already been filed by the clerk before the inspection.', 'The documents have already been filed by the clerk before the inspection.', 'The documents were already filing by the clerk before the inspection.', 'The clerk was already filed by the documents before the inspection.'], 0, 'The original sentence is in the past perfect active voice, so the passive form uses "had been" plus the past participle: "had already been filed".'),
  question('ibps-po-m-en-037', 'Para-jumbles', 'hard', 'Arrange the parts to form a coherent sentence: P: several employees volunteered; Q: to help set up the new branch; R: within just two days of the announcement; S: being made by the regional office.', ['P, Q, R, S', 'S, R, P, Q', 'P, Q, S, R', 'R, S, P, Q'], 0, 'The parts read in order as a single coherent sentence: several employees volunteered (P) to help set up the new branch (Q) within just two days of the announcement (R) being made by the regional office (S).'),
  question('ibps-po-m-en-038', 'Connectors', 'medium', 'Choose the best connector: The branch had limited staff that week; ___, customer wait times increased noticeably.', ['as a result', 'in contrast', 'similarly', 'otherwise'], 0, '"As a result" signals that the second clause is a direct consequence of the first — limited staff led to longer wait times.'),
  question('ibps-po-m-en-039', 'Reading comprehension', 'medium', 'Read the statement: "Contactless cards let customers make small payments quickly without entering a PIN, but banks still cap the transaction value for security reasons." What can be inferred?', ['Contactless cards never require a PIN under any circumstances.', 'There is a trade-off between payment convenience and transaction security.', 'Contactless cards are only used for very large payments.', 'Banks have removed all transaction limits for contactless payments.'], 1, 'The statement links the convenience of skipping a PIN to a security-driven transaction cap, indicating a deliberate trade-off between convenience and security, not the absolute claims in the other options.'),
  question('ibps-po-m-en-040', 'Direct and indirect speech', 'medium', 'Choose the correct indirect speech form of: The customer said, "I will visit the branch tomorrow."', ['The customer said that he will visit the branch tomorrow.', 'The customer said that he visits the branch tomorrow.', 'The customer said that he would visit the branch the next day.', 'The customer said that he would visit the branch tomorrow.'], 2, 'In reported speech, "will" shifts back to "would" and the time reference "tomorrow" shifts to "the next day", since the reporting happens after the original moment of speech.'),
];
