import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'IBPS Specialist Officer CRP SPL-XV official advertisement — Mains, English Language section (IT Officer)',
  url: 'https://www.ibps.in/wp-content/uploads/Detailed-Advt.-CRP-SPL-XV_Final1.pdf',
  checkedOn: '29 August 2026',
};

const RC_PASSAGE =
  'Cyber-security awareness training has become a routine requirement across banks and financial institutions, driven less by regulatory mandate alone than by a hard-won recognition that most successful breaches begin with a single employee clicking a convincing but fraudulent link. Traditional training programmes, delivered once a year as a mandatory slideshow, have consistently failed to change actual behaviour, since employees forget the specifics within weeks and the training rarely reflects the exact tactics attackers are using at that moment. In response, several institutions have shifted toward continuous, scenario-based training: short simulated phishing emails sent at random intervals, with employees who click receiving immediate, targeted feedback rather than a formal reprimand. Early results from institutions that adopted this approach report meaningfully lower click-through rates within six months, though security researchers caution that measuring long-term behavioural change is far harder than measuring short-term compliance with a single simulated test. A further complication is that attackers themselves adapt quickly, meaning any training programme that does not evolve alongside the threat landscape risks teaching employees to recognise last year\'s tactics rather than tomorrow\'s.';

export const IBPS_SO_MAINS_ENGLISH_2: Question[] = [
  { id: 'ibps-so-m2-en-001', section: 'English Language', topic: 'Reading comprehension', difficulty: 'medium', question: `${RC_PASSAGE}\n\nAccording to the passage, what is the primary reason most successful breaches occur?`, options: ['A single employee clicking a convincing but fraudulent link', 'Outdated banking software', 'Insufficient regulatory mandates', 'A lack of firewalls'], correctIndex: 0, explanation: 'The passage states that most successful breaches begin with a single employee clicking a convincing but fraudulent link.', source },
  { id: 'ibps-so-m2-en-002', section: 'English Language', topic: 'Reading comprehension', difficulty: 'medium', question: `${RC_PASSAGE}\n\nWhy have traditional annual training programmes failed, per the passage?`, options: ['Regulators have banned them', 'Employees forget the specifics within weeks and the content rarely reflects current attacker tactics', 'They are too expensive to run', 'Employees actively refuse to attend them'], correctIndex: 1, explanation: 'The passage states employees forget the specifics within weeks and the training rarely reflects the exact tactics attackers are using at that moment.', source },
  { id: 'ibps-so-m2-en-003', section: 'English Language', topic: 'Reading comprehension', difficulty: 'medium', question: `${RC_PASSAGE}\n\nWhat happens to employees who click a simulated phishing email, per the passage?`, options: ['They receive a formal written warning', 'Nothing happens at all', 'They receive immediate, targeted feedback rather than a formal reprimand', 'They are dismissed from their role'], correctIndex: 2, explanation: 'The passage states employees who click receive immediate, targeted feedback rather than a formal reprimand.', source },
  { id: 'ibps-so-m2-en-004', section: 'English Language', topic: 'Reading comprehension', difficulty: 'hard', question: `${RC_PASSAGE}\n\nWhat complication do security researchers highlight about measuring the success of continuous training?`, options: ['Training costs cannot be measured at all', 'Institutions refuse to share their results', 'Employees always lie about clicking suspicious links', 'Long-term behavioural change is far harder to measure than short-term compliance with a single test'], correctIndex: 3, explanation: 'The passage states that measuring long-term behavioural change is far harder than measuring short-term compliance with a single simulated test.', source },
  { id: 'ibps-so-m2-en-005', section: 'English Language', topic: 'Cloze test', difficulty: 'medium', question: 'The committee decided to _______ the proposal until further data became available.', options: ['defer', 'deferring', 'deferred', 'defers'], correctIndex: 0, explanation: 'After "decided to", the base form of the verb is required: "decided to defer".', source },
  { id: 'ibps-so-m2-en-006', section: 'English Language', topic: 'Cloze test', difficulty: 'medium', question: 'The auditors insisted _______ every transaction from the last quarter.', options: ['review', 'on reviewing', 'to review', 'reviewing'], correctIndex: 1, explanation: '"Insist on" is followed by a gerund: "insisted on reviewing".', source },
  { id: 'ibps-so-m2-en-007', section: 'English Language', topic: 'Cloze test', difficulty: 'hard', question: 'Were the branch to reopen next month, footfall _______ recover within a quarter.', options: ['would have likely', 'likely will', 'would likely', 'will likely'], correctIndex: 2, explanation: 'This is a second conditional (hypothetical present/future): "Were + subject, ... would + base verb" — "would likely recover".', source },
  { id: 'ibps-so-m2-en-008', section: 'English Language', topic: 'Error spotting', difficulty: 'hard', question: 'Identify the part with an error: (A) The panel of experts / (B) were unable to reach / (C) a consensus on the / (D) proposed merger.', options: ['C', 'D', 'A', 'B'], correctIndex: 3, explanation: '"Panel" is treated as a singular collective noun here, so it should be "was unable to reach", not "were unable to reach" — the error is in part B.', source },
  { id: 'ibps-so-m2-en-009', section: 'English Language', topic: 'Error spotting', difficulty: 'medium', question: 'Identify the part with an error: (A) Neither of the branches / (B) have submitted / (C) their quarterly report / (D) on time.', options: ['B', 'C', 'D', 'A'], correctIndex: 0, explanation: '"Neither" is singular and takes a singular verb, so it should be "has submitted", not "have submitted" — the error is in part B.', source },
  { id: 'ibps-so-m2-en-010', section: 'English Language', topic: 'Error spotting', difficulty: 'medium', question: 'Identify the part with an error: (A) One of the servers / (B) have crashed / (C) during the / (D) scheduled maintenance window.', options: ['A', 'B', 'C', 'D'], correctIndex: 1, explanation: '"One of the servers" takes a singular verb, so it should be "has crashed", not "have crashed" — the error is in part B.', source },
  { id: 'ibps-so-m2-en-011', section: 'English Language', topic: 'Sentence improvement', difficulty: 'hard', question: 'Improve the underlined part: "The vendor, as well as its subcontractors, _were_ audited last week."', options: ['have been audited', 'are audited', 'was audited', 'were audited'], correctIndex: 2, explanation: 'Phrases like "as well as" do not change the number of the subject; the verb agrees with the singular subject "vendor", so it should be "was audited".', source },
  { id: 'ibps-so-m2-en-012', section: 'English Language', topic: 'Sentence improvement', difficulty: 'hard', question: 'Improve the underlined part: "Either the developers or the tester _were_ responsible for the oversight."', options: ['has been responsible', 'were responsible', 'have been responsible', 'was responsible'], correctIndex: 3, explanation: 'With "either...or", the verb agrees with the nearer subject; since "tester" (singular) is closer, it should be "was responsible".', source },
  { id: 'ibps-so-m2-en-013', section: 'English Language', topic: 'Para jumbles', difficulty: 'hard', question: 'Arrange the sentences in the correct order to form a meaningful paragraph:\nP. As a result, several regulators now mandate periodic penetration testing.\nQ. Financial institutions increasingly rely on interconnected digital systems.\nR. This interconnection has widened the potential attack surface considerably.\nS. Institutions have responded by hiring dedicated in-house security teams.', options: ['QRPS', 'QPRS', 'RQPS', 'QRSP'], correctIndex: 0, explanation: 'The logical order is: institutions rely on digital systems (Q), this widens the attack surface (R), regulators mandate testing (P), institutions hire security teams (S).', source },
  { id: 'ibps-so-m2-en-014', section: 'English Language', topic: 'Para jumbles', difficulty: 'hard', question: 'Arrange the sentences in the correct order to form a meaningful paragraph:\nP. This has reduced average loan approval time from days to minutes.\nQ. Several lenders have started using automated credit-scoring models.\nR. Faster approvals have, in turn, increased overall loan volumes.\nS. Earlier, credit assessments relied heavily on manual document review.', options: ['QPSR', 'SQPR', 'QSPR', 'SQRP'], correctIndex: 1, explanation: 'The logical order is: earlier assessments were manual (S), lenders adopted automated scoring (Q), this cut approval time (P), faster approvals raised volumes (R).', source },
  { id: 'ibps-so-m2-en-015', section: 'English Language', topic: 'Fill in the blanks', difficulty: 'medium', question: 'The board requested that the CFO _______ a detailed cost breakdown.', options: ['prepares', 'preparing', 'prepare', 'prepared'], correctIndex: 2, explanation: 'After "requested that", the subjunctive base form of the verb is used: "requested that the CFO prepare".', source },
  { id: 'ibps-so-m2-en-016', section: 'English Language', topic: 'Fill in the blanks', difficulty: 'medium', question: 'Despite repeated delays, the client remained _______ about the project timeline.', options: ['patients', 'patience', 'patiently', 'patient'], correctIndex: 3, explanation: 'An adjective is needed after "remained", so "patient" is correct.', source },
  { id: 'ibps-so-m2-en-017', section: 'English Language', topic: 'One-word substitution', difficulty: 'medium', question: 'A statement that can be interpreted in more than one way is called:', options: ['Ambiguous', 'Explicit', 'Conclusive', 'Redundant'], correctIndex: 0, explanation: 'A statement that can be interpreted in more than one way is described as "ambiguous".', source },
  { id: 'ibps-so-m2-en-018', section: 'English Language', topic: 'One-word substitution', difficulty: 'medium', question: 'A person who spends money extremely carefully, often to excess, is called:', options: ['Generous', 'Frugal', 'Extravagant', 'Reckless'], correctIndex: 1, explanation: '"Frugal" describes someone who is economical and careful with money.', source },
  { id: 'ibps-so-m2-en-019', section: 'English Language', topic: 'Synonym', difficulty: 'medium', question: "Choose the word closest in meaning to 'meticulous'.", options: ['Vague', 'Careless', 'Thorough', 'Hasty'], correctIndex: 2, explanation: '"Meticulous" means showing great attention to detail, closest in meaning to "Thorough".', source },
  { id: 'ibps-so-m2-en-020', section: 'English Language', topic: 'Synonym', difficulty: 'medium', question: "Choose the word closest in meaning to 'resilient'.", options: ['Timid', 'Fragile', 'Weak', 'Tough'], correctIndex: 3, explanation: '"Resilient" means able to withstand or recover quickly from difficulties, closest in meaning to "Tough".', source },
  { id: 'ibps-so-m2-en-021', section: 'English Language', topic: 'Antonym', difficulty: 'medium', question: "Choose the word most nearly OPPOSITE in meaning to 'meticulous'.", options: ['Careless', 'Precise', 'Thorough', 'Careful'], correctIndex: 0, explanation: '"Meticulous" means showing great attention to detail; its opposite is "Careless".', source },
  { id: 'ibps-so-m2-en-022', section: 'English Language', topic: 'Antonym', difficulty: 'medium', question: "Choose the word most nearly OPPOSITE in meaning to 'resilient'.", options: ['Adaptable', 'Fragile', 'Tough', 'Sturdy'], correctIndex: 1, explanation: '"Resilient" means tough and able to recover quickly; its opposite is "Fragile".', source },
  { id: 'ibps-so-m2-en-023', section: 'English Language', topic: 'Idioms', difficulty: 'medium', question: 'What does the idiom "to read between the lines" mean?', options: ['To read a document literally', 'To skip a section while reading', 'To understand a hidden or implied meaning', 'To read very quickly'], correctIndex: 2, explanation: '"To read between the lines" means to understand the implied or hidden meaning of something, not just its literal words.', source },
  { id: 'ibps-so-m2-en-024', section: 'English Language', topic: 'Idioms', difficulty: 'medium', question: 'What does the idiom "to be on the same page" mean?', options: ['To be seated together', 'To finish work at the same time', 'To be reading the same document', 'To be in agreement about something'], correctIndex: 3, explanation: '"To be on the same page" means to be in agreement or to have the same understanding about something.', source },
  { id: 'ibps-so-m2-en-025', section: 'English Language', topic: 'Active and passive voice', difficulty: 'medium', question: 'Choose the correct passive voice of: "The auditors have reviewed all the branch records."', options: ['All the branch records have been reviewed by the auditors.', 'All the branch records were reviewed by the auditors.', 'All the branch records had been reviewed by the auditors.', 'All the branch records are reviewed by the auditors.'], correctIndex: 0, explanation: 'The original sentence uses the present perfect tense, so the correct passive form retains that tense: "have been reviewed".', source },
];
