import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'Original IELTS General Training Reading Section 1 practice text (social and survival information) and multiple-choice questions, written in the format used in the official IELTS General Training Reading test.',
  url: 'https://ielts.org/take-a-test/test-types/ielts-general-training-test/ielts-general-training-format-reading',
  checkedOn: '14 August 2026',
};

const PASSAGE = `Riverside Community Centre: Membership and Facility Guide

Riverside Community Centre welcomes new members throughout the year. Annual membership costs £45 for adults, £25 for concession card holders (students, seniors, and unemployed residents), and is free for children under twelve when accompanied by a paying adult member. Membership cards must be shown at reception before using any facility and are valid for twelve months from the date of purchase, not from the calendar year.

The swimming pool is open Monday to Friday from 6 a.m. to 9 p.m., and on weekends from 8 a.m. to 6 p.m. Lane swimming is reserved every weekday between 6 a.m. and 8 a.m.; general swimming, including for children, is not permitted during this reserved period. Please note the pool closes for scheduled maintenance on the first Monday of every month.

The main hall may be booked by members for private events at a reduced member rate of £30 per hour, compared with £50 per hour for non-members. Bookings must be made at least two weeks in advance through reception, either in person or by phone, and a deposit of £20 is required to confirm the booking. Deposits are refunded in full if a booking is cancelled more than 48 hours before the event.

Members wishing to cancel their membership must give thirty days' written notice to reception. Refunds are not provided for the current membership period once it has begun, though members may transfer the remaining balance of their membership to a family member living at the same address.`;

const read = (q: string) => `Read the text and answer the question that follows.\n\n${PASSAGE}\n\nQuestion: ${q}`;

export const IELTS_GENERAL_TRAINING_READING_SECTION_1_1: Question[] = [
  { id: 'ielts-general-training-reading-section-1-01-001', section: 'Section 1', topic: 'Main Idea', difficulty: 'easy', question: read('What is the main purpose of this text?'), options: ['To inform members and prospective members about facility rules and prices', 'To advertise the community centre to potential sponsors', 'To announce the permanent closure of the swimming pool', 'To recruit new staff for the reception desk'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The text is a practical guide covering membership prices, pool hours, hall booking rules, and cancellation policy, aimed at informing members and prospective members.', source },
  { id: 'ielts-general-training-reading-section-1-01-002', section: 'Section 1', topic: 'Detail', difficulty: 'easy', question: read('How much does annual adult membership cost?'), options: ['£25', '£45', '£30', '£50'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The text states "Annual membership costs £45 for adults."', source },
  { id: 'ielts-general-training-reading-section-1-01-003', section: 'Section 1', topic: 'Detail', difficulty: 'easy', question: read('What does concession membership cost?'), options: ['£20', '£35', '£25', '£45'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The text states concession membership is "£25 for concession card holders (students, seniors, and unemployed residents)."', source },
  { id: 'ielts-general-training-reading-section-1-01-004', section: 'Section 1', topic: 'Detail', difficulty: 'medium', question: read('Under what condition is membership free for a child under twelve?'), options: ['Only during school holidays', 'Never; children always pay full price', 'Only if the child can swim', 'When accompanied by a paying adult member'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The text states membership "is free for children under twelve when accompanied by a paying adult member."', source },
  { id: 'ielts-general-training-reading-section-1-01-005', section: 'Section 1', topic: 'Detail', difficulty: 'medium', question: read('From what date is a membership valid for twelve months?'), options: ['From the date of purchase', 'From 1 January of the calendar year', "From the member's date of birth", 'From the first visit to the pool'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The text specifies membership is "valid for twelve months from the date of purchase, not from the calendar year."', source },
  { id: 'ielts-general-training-reading-section-1-01-006', section: 'Section 1', topic: 'Detail', difficulty: 'easy', question: read('What are the swimming pool hours on weekdays?'), options: ['8 a.m. to 6 p.m.', '6 a.m. to 9 p.m.', '6 a.m. to 6 p.m.', '9 a.m. to 9 p.m.'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The text states the pool is "open Monday to Friday from 6 a.m. to 9 p.m."', source },
  { id: 'ielts-general-training-reading-section-1-01-007', section: 'Section 1', topic: 'Detail', difficulty: 'easy', question: read('What are the swimming pool hours on weekends?'), options: ['6 a.m. to 9 p.m.', '9 a.m. to 5 p.m.', '8 a.m. to 6 p.m.', 'Closed on weekends'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The text states that "on weekends" the pool is open "from 8 a.m. to 6 p.m."', source },
  { id: 'ielts-general-training-reading-section-1-01-008', section: 'Section 1', topic: 'Detail', difficulty: 'medium', question: read('Who is NOT permitted to use the pool for general swimming between 6 a.m. and 8 a.m. on weekdays?'), options: ['Only non-members', 'No one; general swimming is allowed at all times', 'Only adults over sixty', 'Anyone, including children, since this time is reserved for lane swimming'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The text states lane swimming is reserved during this period and "general swimming, including for children, is not permitted during this reserved period."', source },
  { id: 'ielts-general-training-reading-section-1-01-009', section: 'Section 1', topic: 'Detail', difficulty: 'medium', question: read('When does the pool close for scheduled maintenance?'), options: ['The first Monday of every month', 'The last Friday of every month', 'Every weekend', 'Only once a year, in January'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The text states "the pool closes for scheduled maintenance on the first Monday of every month."', source },
  { id: 'ielts-general-training-reading-section-1-01-010', section: 'Section 1', topic: 'Detail', difficulty: 'medium', question: read('What is the hourly rate for a member booking the main hall?'), options: ['£20 per hour', '£30 per hour', '£50 per hour', '£45 per hour'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The text states the "reduced member rate" for the main hall is "£30 per hour, compared with £50 per hour for non-members."', source },
  { id: 'ielts-general-training-reading-section-1-01-011', section: 'Section 1', topic: 'Detail', difficulty: 'medium', question: read('How far in advance must main hall bookings be made?'), options: ['At least 48 hours', 'At least one week', 'At least two weeks', 'At least one month'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The text states "bookings must be made at least two weeks in advance through reception."', source },
  { id: 'ielts-general-training-reading-section-1-01-012', section: 'Section 1', topic: 'Detail', difficulty: 'medium', question: read('When is the £20 hall booking deposit refunded in full?'), options: ['Only if the event is rescheduled, not cancelled', 'Only for members who have held membership for over a year', 'Never; deposits are always non-refundable', 'If a booking is cancelled more than 48 hours before the event'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The text states "deposits are refunded in full if a booking is cancelled more than 48 hours before the event."', source },
  { id: 'ielts-general-training-reading-section-1-01-013', section: 'Section 1', topic: 'Detail', difficulty: 'medium', question: read('What notice period is required to cancel membership?'), options: ['Thirty days, given in writing', 'Seven days', 'No notice is required', 'Ninety days, given in writing'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The text states members "must give thirty days\' written notice to reception" to cancel membership.', source },
];
