import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'Original IELTS Academic Reading passage and multiple-choice practice questions, written in the skill areas and multiple-choice format used in the official IELTS Academic Reading test.',
  url: 'https://ielts.org/take-a-test/test-types/ielts-academic-test',
  checkedOn: '14 August 2026',
};

const PASSAGE = `Chronotype, the term researchers use to describe an individual's natural inclination toward earlier or later sleep and activity patterns, has attracted growing scientific interest as evidence accumulates that it is substantially influenced by genetics rather than being purely a matter of habit or discipline. Twin studies have found that identical twins, who share nearly all of their genetic material, show far more similarity in their preferred sleep timing than fraternal twins do, a pattern that would be difficult to explain if chronotype were shaped mainly by upbringing or environment. Researchers have since identified several gene variants associated with circadian rhythm regulation that appear more frequently among people who self-report as strongly 'morning types' or 'evening types.'

This genetic component has practical implications that extend well beyond personal preference. Several studies examining school and work schedules have found that when start times are misaligned with an individual's chronotype, measurable effects follow: evening types forced into early schedules report more daytime fatigue, show reduced performance on cognitive tests administered in the morning, and in some workplace studies, are involved in more safety incidents during early shifts than colleagues whose chronotype better matches the required hours. Notably, these effects were observed even after controlling for total sleep duration, suggesting that the mismatch itself, not simply insufficient sleep, contributes to the outcome.

These findings have prompted debate about whether institutions should adjust fixed schedules to accommodate chronotype variation, an idea that faces practical obstacles. Coordinating shared resources such as classrooms, public transport, and cross-team meetings becomes considerably harder if start times vary by individual rather than following a single institutional schedule. Some school districts have nonetheless experimented with delaying start times by even thirty to sixty minutes, reporting modest improvements in average attendance and reported alertness, without needing to abandon a shared schedule altogether. Critics caution that such findings, while promising, come from a limited number of institutions and may not generalize to every context, and they argue that further large-scale trials are needed before recommending changes on a wider scale.`;

const read = (q: string) => `Read the passage and answer the question that follows.\n\n${PASSAGE}\n\nQuestion: ${q}`;

export const IELTS_ACADEMIC_READING_PASSAGE_3_1: Question[] = [
  { id: 'ielts-academic-reading-passage-3-01-001', section: 'Passage 3', topic: 'Main Idea', difficulty: 'medium', question: read('What is the main focus of the passage?'), options: ['The genetic basis of chronotype and its practical implications for schedules', 'The history of sleep research as a scientific discipline', 'A comparison of sleep duration across different countries', 'The invention of tests used to measure cognitive performance'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage explains what chronotype is, presents genetic evidence for it, and then discusses its practical implications for institutional schedules, which is its central focus throughout.', source },
  { id: 'ielts-academic-reading-passage-3-01-002', section: 'Passage 3', topic: 'Detail', difficulty: 'easy', question: read('How does the passage define chronotype?'), options: ["A person's total number of hours slept per night", "An individual's natural inclination toward earlier or later sleep and activity patterns", 'A medical condition requiring treatment', 'The average bedtime of a given population'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: "The passage opens by defining chronotype as \"an individual's natural inclination toward earlier or later sleep and activity patterns.\"", source },
  { id: 'ielts-academic-reading-passage-3-01-003', section: 'Passage 3', topic: 'Detail', difficulty: 'medium', question: read('What did twin studies find regarding identical and fraternal twins?'), options: ['Fraternal twins show more similarity in sleep timing than identical twins', 'Both types of twins show identical sleep timing in all cases', 'Identical twins show far more similarity in preferred sleep timing than fraternal twins', 'Twin studies found no measurable difference at all'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage states identical twins "show far more similarity in their preferred sleep timing than fraternal twins do."', source },
  { id: 'ielts-academic-reading-passage-3-01-004', section: 'Passage 3', topic: 'Inference', difficulty: 'hard', question: read('Why does the passage present the twin-study finding as significant?'), options: ['It proves that chronotype can be changed through willpower', 'It disproves the existence of circadian rhythms', 'It shows that twins always share identical daily schedules', 'It supports a genetic rather than purely environmental explanation for chronotype'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage notes this pattern "would be difficult to explain if chronotype were shaped mainly by upbringing or environment," positioning it as genetic evidence.', source },
  { id: 'ielts-academic-reading-passage-3-01-005', section: 'Passage 3', topic: 'Detail', difficulty: 'medium', question: read('What have researchers identified in connection with morning and evening types?'), options: ['Several gene variants associated with circadian rhythm regulation', 'A single gene responsible for all sleep behaviour', 'A dietary pattern linked to sleep preference', 'A geographic pattern tied to time zones'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage states researchers "have since identified several gene variants associated with circadian rhythm regulation" linked to self-reported morning or evening types.', source },
  { id: 'ielts-academic-reading-passage-3-01-006', section: 'Passage 3', topic: 'Vocabulary in Context', difficulty: 'medium', question: read("The word 'misaligned' in the second paragraph is closest in meaning to:"), options: ['perfectly matched', 'not matched or coordinated', 'scientifically measured', 'legally required'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: "'Misaligned' describes start times that fail to match an individual's chronotype, i.e. not coordinated with it.", source },
  { id: 'ielts-academic-reading-passage-3-01-007', section: 'Passage 3', topic: 'Detail', difficulty: 'medium', question: read('Which effect is NOT mentioned as resulting from evening types being forced into early schedules?'), options: ['More daytime fatigue', 'Reduced performance on morning cognitive tests', 'Increased appetite throughout the day', 'More safety incidents during early shifts'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage lists daytime fatigue, reduced cognitive performance, and more safety incidents; appetite is not mentioned.', source },
  { id: 'ielts-academic-reading-passage-3-01-008', section: 'Passage 3', topic: 'Detail', difficulty: 'medium', question: read('What factor did the studies control for when observing these effects?'), options: ['Age of the participants', 'Room temperature during sleep', 'Type of employment contract', 'Total sleep duration'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage states "these effects were observed even after controlling for total sleep duration."', source },
  { id: 'ielts-academic-reading-passage-3-01-009', section: 'Passage 3', topic: 'Inference', difficulty: 'hard', question: read('What does controlling for total sleep duration suggest, according to the passage?'), options: ['That the schedule mismatch itself, not just insufficient sleep, contributes to the outcome', 'That sleep duration is the only factor that matters', 'That the study results are invalid', 'That evening types sleep for a shorter total duration than morning types'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage states this control suggests "the mismatch itself, not simply insufficient sleep, contributes to the outcome."', source },
  { id: 'ielts-academic-reading-passage-3-01-010', section: 'Passage 3', topic: 'Detail', difficulty: 'medium', question: read('What practical obstacle does the passage identify for adjusting schedules to chronotype?'), options: ['A lack of scientific interest in the topic', 'Difficulty coordinating shared resources like classrooms, transport, and meetings', 'The high cost of genetic testing for every individual', 'Legal restrictions preventing any schedule changes'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage states that coordinating "shared resources such as classrooms, public transport, and cross-team meetings becomes considerably harder" if schedules vary by individual.', source },
  { id: 'ielts-academic-reading-passage-3-01-011', section: 'Passage 3', topic: 'Detail', difficulty: 'medium', question: read('What have some school districts experimented with, according to the passage?'), options: ['Eliminating fixed schedules entirely', 'Extending the school day by three hours', 'Delaying start times by thirty to sixty minutes', 'Replacing classroom instruction with online learning'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage states some districts have "experimented with delaying start times by even thirty to sixty minutes."', source },
  { id: 'ielts-academic-reading-passage-3-01-012', section: 'Passage 3', topic: 'Detail', difficulty: 'medium', question: read('What outcome did these school districts report after delaying start times?'), options: ['No measurable change of any kind', 'Complete elimination of daytime fatigue', 'A significant decline in academic performance', 'Modest improvements in average attendance and reported alertness'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage states these districts reported "modest improvements in average attendance and reported alertness."', source },
  { id: 'ielts-academic-reading-passage-3-01-013', section: 'Passage 3', topic: "Writer's Opinion", difficulty: 'hard', question: read("What caution do critics raise about the school-district findings, according to the passage?"), options: ['That the findings come from a limited number of institutions and may not generalize', 'That the findings are entirely fabricated', 'That schedule changes are illegal in most regions', 'That chronotype has no genetic basis whatsoever'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: "The passage states critics note the findings \"come from a limited number of institutions and may not generalize to every context.\"", source },
  { id: 'ielts-academic-reading-passage-3-01-014', section: 'Passage 3', topic: 'Inference', difficulty: 'hard', question: read('Which statement best reflects the overall tone of the passage toward adjusting institutional schedules to chronotype?'), options: ['Fully conclusive, recommending immediate wide-scale adoption', 'Cautiously supportive, noting promising evidence alongside a need for further large-scale trials', 'Dismissive, treating the entire idea as unscientific', 'Entirely focused on cost rather than evidence'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage presents genetic and behavioural evidence favourably, but closes by noting critics want "further large-scale trials... before recommending changes on a wider scale," reflecting cautious support rather than firm endorsement.', source },
];
