import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'Original IELTS Academic Reading passage and multiple-choice practice questions, written in the skill areas and multiple-choice format used in the official IELTS Academic Reading test.',
  url: 'https://ielts.org/take-a-test/test-types/ielts-academic-test',
  checkedOn: '14 August 2026',
};

const PASSAGE = `For more than a century, lighthouses along many coastlines were staffed around the clock by keepers who lived, often with their families, in small quarters attached to the tower. Their daily responsibilities included winding the clockwork mechanism that rotated the lamp, trimming wicks, cleaning lenses of salt residue, and maintaining detailed logs of passing vessels and weather conditions. The work was frequently isolated, particularly at remote stations reachable only by boat, and keepers sometimes went weeks without contact with anyone beyond their immediate family or a supply crew.

The shift toward automation began gradually in the mid-twentieth century as electric lamps, timer switches, and eventually solar-powered systems reduced the need for constant human attendance. By the final decades of the century, most national lighthouse authorities had automated the great majority of their stations, transferring monitoring duties to centralized control rooms that could track a lamp's status remotely and dispatch technicians only when a fault was detected. Proponents of automation cited clear advantages: lower staffing costs, improved worker safety from removing people from hazardous remote locations, and more consistent light output, since electronic systems rarely suffered the human error that occasionally affected manually operated lamps.

Automation was not without critics, however. Some coastal historians argued that the departure of resident keepers erased a distinct maritime culture and left a number of towers vulnerable to vandalism or neglect once no one lived on site to notice small problems early. In response, several countries have since converted decommissioned keeper's quarters into small museums or short-term accommodation, funded partly through heritage grants and partly through tourism revenue, arguing that preserving public access to these structures matters even after their original operational purpose has been automated away. A handful of towers still retain a part-time keeper, largely for ceremonial and educational reasons rather than operational necessity.`;

const read = (q: string) => `Read the passage and answer the question that follows.\n\n${PASSAGE}\n\nQuestion: ${q}`;

export const IELTS_ACADEMIC_READING_PASSAGE_2_1: Question[] = [
  { id: 'ielts-academic-reading-passage-2-01-001', section: 'Passage 2', topic: 'Main Idea', difficulty: 'easy', question: read('What is the main topic of the passage?'), options: ['The shift from staffed to automated lighthouses and its consequences', 'The daily diet of lighthouse keepers', 'A comparison of lamp designs used in different centuries', 'The construction methods used to build coastal towers'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage moves from describing staffed lighthouse life, to the process of automation, to its benefits and criticisms, all centred on this shift and its effects.', source },
  { id: 'ielts-academic-reading-passage-2-01-002', section: 'Passage 2', topic: 'Detail', difficulty: 'easy', question: read("Which of the following was NOT listed among a keeper's daily responsibilities?"), options: ['Winding the clockwork mechanism that rotated the lamp', 'Repairing storm damage to the tower structure', 'Cleaning lenses of salt residue', 'Trimming wicks'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: "The passage lists winding the clockwork, trimming wicks, cleaning lenses, and keeping logs as daily duties; structural storm repair is not mentioned.", source },
  { id: 'ielts-academic-reading-passage-2-01-003', section: 'Passage 2', topic: 'Detail', difficulty: 'medium', question: read('When did the shift toward automation begin, according to the passage?'), options: ['In the early nineteenth century', 'Only within the last ten years', 'In the mid-twentieth century', 'Before lighthouses were staffed by keepers'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage states "the shift toward automation began gradually in the mid-twentieth century."', source },
  { id: 'ielts-academic-reading-passage-2-01-004', section: 'Passage 2', topic: 'Vocabulary in Context', difficulty: 'medium', question: read("The word 'isolated' in the first paragraph is closest in meaning to:"), options: ['well-paid', 'temporary', 'dangerous', 'cut off from other people'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: "The surrounding text describes keepers going \"weeks without contact with anyone,\" supporting the meaning of being cut off from others.", source },
  { id: 'ielts-academic-reading-passage-2-01-005', section: 'Passage 2', topic: 'Detail', difficulty: 'medium', question: read('Which technologies does the passage credit with reducing the need for constant human attendance?'), options: ['Electric lamps, timer switches, and solar-powered systems', 'Radio beacons and satellite tracking', 'Diesel generators only', 'Remote-controlled boats'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage names "electric lamps, timer switches, and eventually solar-powered systems" as the technologies enabling automation.', source },
  { id: 'ielts-academic-reading-passage-2-01-006', section: 'Passage 2', topic: 'Detail', difficulty: 'medium', question: read('Which of the following is NOT mentioned as an advantage of automation?'), options: ['Lower staffing costs', 'Faster shipping times for cargo vessels', 'More consistent light output', 'Improved worker safety'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage lists lower staffing costs, improved worker safety, and more consistent light output as advantages; shipping speed is not mentioned.', source },
  { id: 'ielts-academic-reading-passage-2-01-007', section: 'Passage 2', topic: "Writer's Opinion", difficulty: 'hard', question: read('What did coastal historians argue was lost when resident keepers departed?'), options: ['A source of tax revenue for local governments', 'The ability to send weather reports at all', 'A distinct maritime culture, along with vulnerability to unnoticed neglect', 'Public access to the coastline'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage states historians argued the departure "erased a distinct maritime culture and left a number of towers vulnerable to vandalism or neglect."', source },
  { id: 'ielts-academic-reading-passage-2-01-008', section: 'Passage 2', topic: 'Detail', difficulty: 'medium', question: read("What have several countries done with decommissioned keeper's quarters?"), options: ['Demolished them to reduce maintenance costs', 'Left them permanently sealed and inaccessible', 'Sold them exclusively to private lighthouse collectors', 'Converted them into small museums or short-term accommodation'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: "The passage states countries \"have since converted decommissioned keeper's quarters into small museums or short-term accommodation.\"", source },
  { id: 'ielts-academic-reading-passage-2-01-009', section: 'Passage 2', topic: 'Detail', difficulty: 'medium', question: read('How are these conversions typically funded, according to the passage?'), options: ['Partly through heritage grants and partly through tourism revenue', 'Entirely through private donations', 'Through a special coastal shipping tax', 'Through international lighthouse preservation treaties'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage states these projects are "funded partly through heritage grants and partly through tourism revenue."', source },
  { id: 'ielts-academic-reading-passage-2-01-010', section: 'Passage 2', topic: 'Reference', difficulty: 'medium', question: read("In the second paragraph, what does 'their' refer to in the phrase 'automated the great majority of their stations'?"), options: ['The resident keepers', 'The national lighthouse authorities', 'The coastal historians', 'The tourists visiting converted towers'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: "'Their' refers back to \"most national lighthouse authorities,\" the subject of the sentence.", source },
  { id: 'ielts-academic-reading-passage-2-01-011', section: 'Passage 2', topic: 'Detail', difficulty: 'medium', question: read('Why do a handful of towers still retain a part-time keeper, according to the passage?'), options: ['Because full automation is technically impossible at those sites', 'Because local law requires a keeper at all times', 'For ceremonial and educational reasons rather than operational necessity', 'Because those towers have no electricity supply'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage states these towers keep a part-time keeper "largely for ceremonial and educational reasons rather than operational necessity."', source },
  { id: 'ielts-academic-reading-passage-2-01-012', section: 'Passage 2', topic: 'Inference', difficulty: 'hard', question: read('Which statement best reflects the overall tone of the passage toward automation?'), options: ['Entirely negative, presenting automation as a mistake', 'Entirely positive, with no acknowledgment of loss', 'Neutral to the point of expressing no facts at all', 'Balanced, presenting both the benefits of automation and what was lost'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage details clear benefits of automation while also presenting the historians\' criticisms and the response of preserving keeper\'s quarters, making the tone balanced.', source },
  { id: 'ielts-academic-reading-passage-2-01-013', section: 'Passage 2', topic: 'Vocabulary in Context', difficulty: 'medium', question: read("The word 'decommissioned' in the third paragraph is closest in meaning to:"), options: ['taken out of active service', 'newly built', 'painted a new colour', 'relocated to another coastline'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: "'Decommissioned' describes quarters no longer in active service as a keeper's residence, consistent with the surrounding discussion of automation replacing resident keepers.", source },
];
