import type { Question } from '../questions';

export const IISER_IAT_2026_BIOLOGY_1 = [
  {
    "id": "iiser-iat-2026-biology-001",
    "section": "Biology",
    "topic": "Population genetics",
    "difficulty": "medium",
    "question": "During a genetics survey of a large randomly mating diploid plant population, 9% of individuals show a recessive phenotype controlled by allele a. Assuming Hardy–Weinberg equilibrium, what fraction of the population is expected to be heterozygous?",
    "options": ["0.18", "0.21", "0.42", "0.49"],
    "correctIndex": 2,
    "answerType": "mcq",
    "marks": 4,
    "negativeMarking": 1,
    "explanation": "The recessive phenotype frequency is q² = 0.09, so q = 0.30 and p = 0.70. Heterozygotes occur with frequency 2pq = 2(0.70)(0.30) = 0.42.",
    "source": {"kind":"original","reference":"IISER Aptitude Test 2026 official Information Brochure and syllabus","url":"https://app.iiseradmission.in/assets/pdfs/IB_IAT_2026_ENG.pdf","checkedOn":"2026-08-31"}
  },
  {
    "id": "iiser-iat-2026-biology-002",
    "section": "Biology",
    "topic": "Mendelian genetics",
    "difficulty": "easy",
    "question": "A laboratory cross uses an individual heterozygous at two independently assorting loci, AaBb, and a double-recessive tester, aabb. If both loci show complete dominance, which phenotypic ratio is expected among a large number of offspring?",
    "options": ["9:3:3:1", "3:1", "1:2:1", "1:1:1:1"],
    "correctIndex": 3,
    "answerType": "mcq",
    "marks": 4,
    "negativeMarking": 1,
    "explanation": "AaBb produces AB, Ab, aB and ab gametes in equal proportions, while aabb produces only ab. The four offspring phenotypes therefore occur equally, giving 1:1:1:1.",
    "source": {"kind":"original","reference":"IISER Aptitude Test 2026 official Information Brochure and syllabus","url":"https://app.iiseradmission.in/assets/pdfs/IB_IAT_2026_ENG.pdf","checkedOn":"2026-08-31"}
  },
  {
    "id": "iiser-iat-2026-biology-003",
    "section": "Biology",
    "topic": "Photosynthesis",
    "difficulty": "medium",
    "question": "In an actively photosynthesizing C4 leaf, a carbon atom from atmospheric CO₂ first becomes incorporated into a four-carbon compound in a mesophyll cell. Which enzyme carries out that initial fixation step?",
    "options": ["RuBisCO", "PEP carboxylase", "ATP synthase", "NADP reductase"],
    "correctIndex": 1,
    "answerType": "mcq",
    "marks": 4,
    "negativeMarking": 1,
    "explanation": "C4 plants initially fix bicarbonate in mesophyll cells using phosphoenolpyruvate carboxylase, forming oxaloacetate, a four-carbon compound.",
    "source": {"kind":"original","reference":"IISER Aptitude Test 2026 official Information Brochure and syllabus","url":"https://app.iiseradmission.in/assets/pdfs/IB_IAT_2026_ENG.pdf","checkedOn":"2026-08-31"}
  },
  {
    "id": "iiser-iat-2026-biology-004",
    "section": "Biology",
    "topic": "Photosynthetic electron transport",
    "difficulty": "hard",
    "question": "A chloroplast preparation contains an inhibitor that prevents electrons leaving photosystem II for plastoquinone, while photosystem I itself remains functional. Which process can still proceed under suitable illumination?",
    "options": ["Photolysis-driven linear electron flow from water to NADP+", "Oxygen evolution coupled to normal linear flow", "Cyclic electron flow around photosystem I", "Reduction of plastoquinone by photosystem II"],
    "correctIndex": 2,
    "answerType": "mcq",
    "marks": 4,
    "negativeMarking": 1,
    "explanation": "Blocking transfer from photosystem II to plastoquinone stops normal linear electron flow and oxygen-evolving electron supply. Photosystem I can nevertheless support cyclic electron flow, which returns electrons through carriers and generates ATP without net NADPH formation.",
    "source": {"kind":"original","reference":"IISER Aptitude Test 2026 official Information Brochure and syllabus","url":"https://app.iiseradmission.in/assets/pdfs/IB_IAT_2026_ENG.pdf","checkedOn":"2026-08-31"}
  },
  {
    "id": "iiser-iat-2026-biology-005",
    "section": "Biology",
    "topic": "Human excretion",
    "difficulty": "easy",
    "question": "A dehydrated person releases more antidiuretic hormone. The most direct effect of this hormone on the kidney collecting duct is an increase in which property?",
    "options": ["Glucose filtration", "Water permeability of the epithelial cells", "Urea synthesis", "Active secretion of sodium into the tubular fluid"],
    "correctIndex": 1,
    "answerType": "mcq",
    "marks": 4,
    "negativeMarking": 1,
    "explanation": "ADH promotes insertion of aquaporin-2 channels in collecting-duct principal cells, increasing water permeability and water reabsorption.",
    "source": {"kind":"original","reference":"IISER Aptitude Test 2026 official Information Brochure and syllabus","url":"https://app.iiseradmission.in/assets/pdfs/IB_IAT_2026_ENG.pdf","checkedOn":"2026-08-31"}
  },
  {
    "id": "iiser-iat-2026-biology-006",
    "section": "Biology",
    "topic": "Counter-current mechanism",
    "difficulty": "medium",
    "question": "Fluid entering the thick ascending limb of the loop of Henle becomes progressively more dilute. Which combination best explains this change?",
    "options": ["Water leaves the tubule while NaCl remains trapped", "Both water and NaCl leave in equal osmotic proportions", "NaCl leaves the tubule while the segment is poorly permeable to water", "Urea enters the tubule faster than water leaves"],
    "correctIndex": 2,
    "answerType": "mcq",
    "marks": 4,
    "negativeMarking": 1,
    "explanation": "The thick ascending limb reabsorbs NaCl but is effectively impermeable to water. Solute therefore leaves without accompanying water, diluting the tubular fluid.",
    "source": {"kind":"original","reference":"IISER Aptitude Test 2026 official Information Brochure and syllabus","url":"https://app.iiseradmission.in/assets/pdfs/IB_IAT_2026_ENG.pdf","checkedOn":"2026-08-31"}
  },
  {
    "id": "iiser-iat-2026-biology-007",
    "section": "Biology",
    "topic": "Gene regulation",
    "difficulty": "medium",
    "question": "For an E. coli cell with a normal lac operon growing in a medium that lacks lactose, what directly prevents high transcription of the lac structural genes?",
    "options": ["The lac repressor binds the operator", "RNA polymerase is destroyed", "The structural genes are excised from the chromosome", "The CAP protein permanently blocks the promoter"],
    "correctIndex": 0,
    "answerType": "mcq",
    "marks": 4,
    "negativeMarking": 1,
    "explanation": "Without lactose, the lac repressor remains active and binds the operator, hindering transcription of lacZYA.",
    "source": {"kind":"original","reference":"IISER Aptitude Test 2026 official Information Brochure and syllabus","url":"https://app.iiseradmission.in/assets/pdfs/IB_IAT_2026_ENG.pdf","checkedOn":"2026-08-31"}
  },
  {
    "id": "iiser-iat-2026-biology-008",
    "section": "Biology",
    "topic": "DNA replication",
    "difficulty": "easy",
    "question": "At a replication fork, one newly synthesized DNA strand is made in short pieces that are later joined. Why is discontinuous synthesis required on that strand?",
    "options": ["Helicase moves only toward a chromosome end", "DNA polymerase can extend DNA only in the 5′→3′ direction", "DNA ligase can synthesize DNA only from RNA templates", "The parental strands run in the same direction"],
    "correctIndex": 1,
    "answerType": "mcq",
    "marks": 4,
    "negativeMarking": 1,
    "explanation": "DNA polymerases add nucleotides only to a 3′ end, so synthesis proceeds 5′→3′. Because the parental strands are antiparallel, one daughter strand is made discontinuously as Okazaki fragments.",
    "source": {"kind":"original","reference":"IISER Aptitude Test 2026 official Information Brochure and syllabus","url":"https://app.iiseradmission.in/assets/pdfs/IB_IAT_2026_ENG.pdf","checkedOn":"2026-08-31"}
  },
  {
    "id": "iiser-iat-2026-biology-009",
    "section": "Biology",
    "topic": "Meiosis",
    "difficulty": "easy",
    "question": "Homologous chromosomes have paired and formed a synaptonemal complex in a meiotic cell. The exchange of corresponding DNA segments between non-sister chromatids occurs mainly during which substage of prophase I?",
    "options": ["Leptotene", "Zygotene", "Diakinesis", "Pachytene"],
    "correctIndex": 3,
    "answerType": "mcq",
    "marks": 4,
    "negativeMarking": 1,
    "explanation": "Crossing over occurs during pachytene after homologues have synapsed; chiasmata become clearly visible later during diplotene.",
    "source": {"kind":"original","reference":"IISER Aptitude Test 2026 official Information Brochure and syllabus","url":"https://app.iiseradmission.in/assets/pdfs/IB_IAT_2026_ENG.pdf","checkedOn":"2026-08-31"}
  },
  {
    "id": "iiser-iat-2026-biology-010",
    "section": "Biology",
    "topic": "Blood groups",
    "difficulty": "medium",
    "question": "One parent has genotype Iᴬi and the other has genotype Iᴮi in the ABO blood-group system. What is the probability that their child will have blood group O?",
    "options": ["0", "1/4", "1/2", "3/4"],
    "correctIndex": 1,
    "answerType": "mcq",
    "marks": 4,
    "negativeMarking": 1,
    "explanation": "Each parent can transmit i with probability 1/2. A group-O child must be ii, so the probability is (1/2)(1/2)=1/4.",
    "source": {"kind":"original","reference":"IISER Aptitude Test 2026 official Information Brochure and syllabus","url":"https://app.iiseradmission.in/assets/pdfs/IB_IAT_2026_ENG.pdf","checkedOn":"2026-08-31"}
  },
  {
    "id": "iiser-iat-2026-biology-011",
    "section": "Biology",
    "topic": "Immunity",
    "difficulty": "easy",
    "question": "A second exposure to the same antigen often produces a faster and larger antibody response than the first exposure. Which cell population is chiefly responsible for this immunological memory?",
    "options": ["Memory B cells generated during the primary response", "Mature erythrocytes", "Platelets activated during inflammation", "Neutrophils that survived the first infection"],
    "correctIndex": 0,
    "answerType": "mcq",
    "marks": 4,
    "negativeMarking": 1,
    "explanation": "Some antigen-activated B lymphocytes differentiate into long-lived memory B cells. On re-exposure they rapidly proliferate and generate antibody-secreting cells.",
    "source": {"kind":"original","reference":"IISER Aptitude Test 2026 official Information Brochure and syllabus","url":"https://app.iiseradmission.in/assets/pdfs/IB_IAT_2026_ENG.pdf","checkedOn":"2026-08-31"}
  },
  {
    "id": "iiser-iat-2026-biology-012",
    "section": "Biology",
    "topic": "Population ecology",
    "difficulty": "medium",
    "question": "A population follows the logistic growth model dN/dt = rN(1 − N/K). At what population size is its absolute growth rate dN/dt maximal?",
    "options": ["N = K/4", "N = 3K/4", "N = K/2", "N = K"],
    "correctIndex": 2,
    "answerType": "mcq",
    "marks": 4,
    "negativeMarking": 1,
    "explanation": "The product N(1−N/K) is a concave quadratic in N and reaches its maximum at N=K/2.",
    "source": {"kind":"original","reference":"IISER Aptitude Test 2026 official Information Brochure and syllabus","url":"https://app.iiseradmission.in/assets/pdfs/IB_IAT_2026_ENG.pdf","checkedOn":"2026-08-31"}
  },
  {
    "id": "iiser-iat-2026-biology-013",
    "section": "Biology",
    "topic": "Ecosystem energetics",
    "difficulty": "easy",
    "question": "An ecosystem's producers store 18,000 kJ of energy in new biomass. If approximately 10% of energy is transferred at each trophic step, about how much reaches secondary consumers through the chain producers → primary consumers → secondary consumers?",
    "options": ["180 kJ", "18 kJ", "1,800 kJ", "9,000 kJ"],
    "correctIndex": 0,
    "answerType": "mcq",
    "marks": 4,
    "negativeMarking": 1,
    "explanation": "Two transfers occur. Primary consumers receive about 1,800 kJ and secondary consumers about 180 kJ.",
    "source": {"kind":"original","reference":"IISER Aptitude Test 2026 official Information Brochure and syllabus","url":"https://app.iiseradmission.in/assets/pdfs/IB_IAT_2026_ENG.pdf","checkedOn":"2026-08-31"}
  },
  {
    "id": "iiser-iat-2026-biology-014",
    "section": "Biology",
    "topic": "Respiration",
    "difficulty": "easy",
    "question": "A germinating seed is oxidizing carbohydrate as its dominant respiratory substrate. If gas exchange is measured accurately, which respiratory quotient is expected to be closest to the theoretical value?",
    "options": ["0.5", "0.7", "1.5", "1.0"],
    "correctIndex": 3,
    "answerType": "mcq",
    "marks": 4,
    "negativeMarking": 1,
    "explanation": "Complete oxidation of carbohydrate consumes approximately as many moles of O₂ as moles of CO₂ released, so respiratory quotient CO₂/O₂ is about 1.",
    "source": {"kind":"original","reference":"IISER Aptitude Test 2026 official Information Brochure and syllabus","url":"https://app.iiseradmission.in/assets/pdfs/IB_IAT_2026_ENG.pdf","checkedOn":"2026-08-31"}
  },
  {
    "id": "iiser-iat-2026-biology-015",
    "section": "Biology",
    "topic": "Plant hormones",
    "difficulty": "medium",
    "question": "A rapid rise in abscisic acid occurs in leaves during severe water deficit. Which guard-cell response most directly promotes stomatal closure?",
    "options": ["Ion loss followed by water loss and reduced guard-cell turgor", "Starch synthesis followed by increased guard-cell turgor", "Proton uptake followed by permanent cell-wall thickening", "Chlorophyll breakdown followed by increased osmotic pressure"],
    "correctIndex": 0,
    "answerType": "mcq",
    "marks": 4,
    "negativeMarking": 1,
    "explanation": "ABA triggers ion efflux from guard cells; water follows osmotically, turgor falls, and the stomatal pore closes.",
    "source": {"kind":"original","reference":"IISER Aptitude Test 2026 official Information Brochure and syllabus","url":"https://app.iiseradmission.in/assets/pdfs/IB_IAT_2026_ENG.pdf","checkedOn":"2026-08-31"}
  }
] satisfies Question[];
