import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'Original INET practice questions in the official 4-option multiple-choice format, covering English and Reasoning and Numerical Ability from the Indian Navy Entrance Test syllabus.',
  url: 'https://www.joinindiannavy.gov.in/en/page/selection-procedure.html',
  checkedOn: '16 August 2026',
};

export const INET_ENGLISH_AND_REASONING_NUMERICAL_ABILITY_1: Question[] = [
  { id: 'inet-english-and-reasoning-numerical-ability-01-001', section: 'English', topic: 'Synonyms', difficulty: 'easy', question: 'Choose the word closest in meaning to "Frugal".', options: ['Thrifty', 'Wasteful', 'Generous', 'Extravagant'], correctIndex: 0, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: '"Frugal" means economical and sparing with money, closest to "Thrifty".', source },
  { id: 'inet-english-and-reasoning-numerical-ability-01-002', section: 'English', topic: 'Antonyms', difficulty: 'easy', question: 'Choose the word opposite in meaning to "Optimistic".', options: ['Optimistic', 'Pessimistic', 'Cheerful', 'Hopeful'], correctIndex: 1, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: '"Optimistic" means hopeful about the future; its opposite is "Pessimistic".', source },
  { id: 'inet-english-and-reasoning-numerical-ability-01-003', section: 'English', topic: 'Prepositions', difficulty: 'easy', question: 'Fill in the blank: She is fond ___ music.', options: ['with', 'for', 'of', 'about'], correctIndex: 2, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: 'The correct idiomatic preposition is "of": She is fond of music.', source },
  { id: 'inet-english-and-reasoning-numerical-ability-01-004', section: 'English', topic: 'Spelling', difficulty: 'easy', question: 'Choose the correctly spelled word.', options: ['Maintainance', 'Maintanance', 'Maintenence', 'Maintenance'], correctIndex: 3, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: 'The correct spelling is "Maintenance".', source },
  { id: 'inet-english-and-reasoning-numerical-ability-01-005', section: 'English', topic: 'One-Word Substitution', difficulty: 'medium', question: 'Choose the word that means "a person who works without payment".', options: ['Volunteer', 'Mercenary', 'Employee', 'Contractor'], correctIndex: 0, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: 'A "Volunteer" is a person who offers to do work without payment.', source },
  { id: 'inet-english-and-reasoning-numerical-ability-01-006', section: 'English', topic: 'Subject-Verb Agreement', difficulty: 'medium', question: 'Choose the grammatically correct sentence.', options: ['The jury are divided in its opinion.', 'The jury is divided in its opinion.', 'The jury were divided in its opinion.', 'The jury have divided in its opinion.'], correctIndex: 1, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: '"Jury" is a collective noun treated as singular here, so it takes the singular verb "is".', source },
  { id: 'inet-english-and-reasoning-numerical-ability-01-007', section: 'English', topic: 'Idioms and Phrases', difficulty: 'easy', question: 'What does the idiom "to break the ice" mean?', options: ['To cause an argument', 'To start a fire', 'To initiate conversation in an awkward situation', 'To end a friendship'], correctIndex: 2, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: '"To break the ice" means to initiate conversation and ease tension in an awkward or unfamiliar situation.', source },
  { id: 'inet-english-and-reasoning-numerical-ability-01-008', section: 'English', topic: 'Voice (Active-Passive)', difficulty: 'medium', question: 'Choose the correct passive voice of: "The chef is cooking dinner."', options: ['Dinner cooked by the chef.', 'Dinner was being cooked by the chef.', 'Dinner has being cooked by the chef.', 'Dinner is being cooked by the chef.'], correctIndex: 3, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: 'Present continuous active becomes present continuous passive: Dinner is being cooked by the chef.', source },
  { id: 'inet-english-and-reasoning-numerical-ability-01-009', section: 'English', topic: 'Articles', difficulty: 'easy', question: 'Fill in the blank: She bought ___ umbrella.', options: ['an', 'a', 'the', 'no article'], correctIndex: 0, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: '"Umbrella" begins with a vowel sound, so it takes the article "an".', source },
  { id: 'inet-english-and-reasoning-numerical-ability-01-010', section: 'English', topic: 'Spelling', difficulty: 'medium', question: 'Identify the correctly spelled word from the options below.', options: ['Questionaire', 'Questionnaire', 'Questionnair', 'Questionaires'], correctIndex: 1, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: 'The correct spelling is "Questionnaire", with double "n".', source },
  { id: 'inet-english-and-reasoning-numerical-ability-01-011', section: 'English', topic: 'Synonyms', difficulty: 'easy', question: 'Choose the word closest in meaning to "Industrious".', options: ['Lazy', 'Careless', 'Hardworking', 'Timid'], correctIndex: 2, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: '"Industrious" means diligent and hardworking, closest to "Hardworking".', source },
  { id: 'inet-english-and-reasoning-numerical-ability-01-012', section: 'English', topic: 'Conjunctions', difficulty: 'medium', question: 'Fill in the blank: ___ she is young, she is very wise.', options: ['Because', 'Unless', 'Whereas', 'Although'], correctIndex: 3, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: '"Although" correctly introduces a concessive clause contrasting her youth with her wisdom.', source },
  { id: 'inet-english-and-reasoning-numerical-ability-01-013', section: 'Reasoning and Numerical Ability', topic: 'Number Series', difficulty: 'medium', question: 'Find the next term: 7, 15, 31, 63, ?', options: ['127', '120', '125', '130'], correctIndex: 0, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: 'Each term follows the rule ×2+1: 63 × 2 + 1 = 127.', source },
  { id: 'inet-english-and-reasoning-numerical-ability-01-014', section: 'Reasoning and Numerical Ability', topic: 'Analogy', difficulty: 'easy', question: 'Fish is to Water as Bird is to ?', options: ['Land', 'Air', 'Water', 'Tree'], correctIndex: 1, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: 'A fish lives in water, just as a bird lives and flies in the air.', source },
  { id: 'inet-english-and-reasoning-numerical-ability-01-015', section: 'Reasoning and Numerical Ability', topic: 'Coding-Decoding', difficulty: 'medium', question: 'If MOVE is coded as NPWF (each letter shifted one place forward in the alphabet), how is HELP coded using the same rule?', options: ['IFLQ', 'IEMQ', 'IFMQ', 'JFMQ'], correctIndex: 2, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: 'Shifting each letter forward by one: H→I, E→F, L→M, P→Q, giving IFMQ.', source },
  { id: 'inet-english-and-reasoning-numerical-ability-01-016', section: 'Reasoning and Numerical Ability', topic: 'Blood Relations', difficulty: 'hard', question: 'Introducing a man, a woman said, "He is the only son of my mother\'s mother." How is the man related to the woman?', options: ['Brother', 'Cousin', 'Nephew', 'Maternal Uncle'], correctIndex: 3, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: 'The woman\'s mother\'s mother is her maternal grandmother. Her only son is the woman\'s mother\'s brother, making him the woman\'s maternal uncle.', source },
  { id: 'inet-english-and-reasoning-numerical-ability-01-017', section: 'Reasoning and Numerical Ability', topic: 'Direction Sense', difficulty: 'medium', question: 'A man walks 6 km south, then turns left and walks 8 km. How far is he from his starting point?', options: ['10 km', '12 km', '14 km', '8 km'], correctIndex: 0, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: 'Facing south and turning left means facing east, so the path forms a right triangle with legs 6 km and 8 km, giving a distance of √(6²+8²) = 10 km.', source },
  { id: 'inet-english-and-reasoning-numerical-ability-01-018', section: 'Reasoning and Numerical Ability', topic: 'Classification', difficulty: 'easy', question: 'Which of the following does not belong with the others?', options: ['Pen', 'Table', 'Pencil', 'Eraser'], correctIndex: 1, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: 'Pen, Pencil, and Eraser are stationery items, while Table is furniture.', source },
  { id: 'inet-english-and-reasoning-numerical-ability-01-019', section: 'Reasoning and Numerical Ability', topic: 'Simple Interest', difficulty: 'easy', question: 'Find the simple interest on ₹6,000 at 6% per annum for 4 years.', options: ['₹1,400', '₹1,420', '₹1,440', '₹1,460'], correctIndex: 2, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: 'SI = (P × R × T) / 100 = (6000 × 6 × 4) / 100 = ₹1,440.', source },
  { id: 'inet-english-and-reasoning-numerical-ability-01-020', section: 'Reasoning and Numerical Ability', topic: 'Average', difficulty: 'easy', question: 'Find the average of the first 10 natural numbers.', options: ['5', '5.2', '5.4', '5.5'], correctIndex: 3, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: 'Sum of first 10 natural numbers = 55. Average = 55 / 10 = 5.5.', source },
  { id: 'inet-english-and-reasoning-numerical-ability-01-021', section: 'Reasoning and Numerical Ability', topic: 'Percentage (Successive Change)', difficulty: 'medium', question: 'A number is increased by 20% and then decreased by 20%. What is the net percentage change?', options: ['-4%', '0%', '+4%', '-1%'], correctIndex: 0, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: 'Net factor = 1.2 × 0.8 = 0.96, which is a 4% decrease from the original value.', source },
  { id: 'inet-english-and-reasoning-numerical-ability-01-022', section: 'Reasoning and Numerical Ability', topic: 'HCF and LCM', difficulty: 'easy', question: 'Find the HCF of 36 and 60.', options: ['6', '12', '18', '24'], correctIndex: 1, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: '36 = 2² × 3², 60 = 2² × 3 × 5. The common factors give HCF = 2² × 3 = 12.', source },
  { id: 'inet-english-and-reasoning-numerical-ability-01-023', section: 'Reasoning and Numerical Ability', topic: 'Simplification', difficulty: 'easy', question: 'Simplify: 20 − 4 × 3 + 6 ÷ 2.', options: ['8', '9', '11', '14'], correctIndex: 2, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: 'By order of operations: 4×3=12 and 6÷2=3, so 20 − 12 + 3 = 11.', source },
  { id: 'inet-english-and-reasoning-numerical-ability-01-024', section: 'Reasoning and Numerical Ability', topic: 'Profit and Loss', difficulty: 'medium', question: 'A shopkeeper marks an item 25% above its cost price and then gives a 10% discount on the marked price. Find the net profit percentage.', options: ['10%', '12%', '12.5%', '15%'], correctIndex: 2, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: 'Taking CP = 100, MP = 125, SP = 125 × 0.9 = 112.5, giving a profit of 12.5%.', source },
];
