import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'Original INET practice questions in the official 4-option multiple-choice format, covering English and Reasoning and Numerical Ability from the Indian Navy Entrance Test syllabus.',
  url: 'https://www.joinindiannavy.gov.in/en/page/selection-procedure.html',
  checkedOn: '16 August 2026',
};

export const INET_ENGLISH_AND_REASONING_NUMERICAL_ABILITY_2: Question[] = [
  { id: 'inet-english-and-reasoning-numerical-ability-02-001', section: 'English', topic: 'Synonyms', difficulty: 'easy', question: 'Choose the word closest in meaning to "Prudent".', options: ['Cautious', 'Reckless', 'Hostile', 'Idle'], correctIndex: 0, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: '"Prudent" means acting with care and thought for the future, closest to "Cautious".', source },
  { id: 'inet-english-and-reasoning-numerical-ability-02-002', section: 'English', topic: 'Antonyms', difficulty: 'easy', question: 'Choose the word opposite in meaning to "Ancient".', options: ['Archaic', 'Modern', 'Primitive', 'Antique'], correctIndex: 1, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: '"Ancient" means belonging to the distant past; its opposite is "Modern". Archaic, primitive and antique all share the sense of old.', source },
  { id: 'inet-english-and-reasoning-numerical-ability-02-003', section: 'English', topic: 'Prepositions', difficulty: 'easy', question: 'Fill in the blank: The vessel is bound ___ Kochi.', options: ['at', 'with', 'for', 'into'], correctIndex: 2, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: 'A ship heading to a destination is "bound for" that place.', source },
  { id: 'inet-english-and-reasoning-numerical-ability-02-004', section: 'English', topic: 'Spelling', difficulty: 'medium', question: 'Choose the correctly spelled word from the options below.', options: ['Manouvre', 'Manoeuver', 'Maneouvre', 'Manoeuvre'], correctIndex: 3, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: 'The British spelling used in Indian service writing is "Manoeuvre", with the "oeu" sequence and the ending "-vre".', source },
  { id: 'inet-english-and-reasoning-numerical-ability-02-005', section: 'English', topic: 'One-Word Substitution', difficulty: 'medium', question: 'Choose the word that means "a person who hides aboard a ship or aircraft to travel without paying".', options: ['Pilgrim', 'Stowaway', 'Nomad', 'Envoy'], correctIndex: 1, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: 'A "Stowaway" hides on board a vessel to travel secretly and without paying.', source },
  { id: 'inet-english-and-reasoning-numerical-ability-02-006', section: 'English', topic: 'Subject-Verb Agreement', difficulty: 'medium', question: 'Choose the sentence with correct subject-verb agreement.', options: ['Each of the officers reports to the commander.', 'Each of the officers report to the commander.', 'Each of the officers are reporting to the commander.', 'Each of the officers have reported to the commander.'], correctIndex: 0, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: '"Each" is the singular subject and takes a singular verb. The intervening phrase "of the officers" does not change its number.', source },
  { id: 'inet-english-and-reasoning-numerical-ability-02-007', section: 'English', topic: 'Idioms and Phrases', difficulty: 'easy', question: 'What does the idiom "to weather the storm" mean?', options: ['To predict bad weather', 'To abandon a plan', 'To cause trouble deliberately', 'To survive a difficult period'], correctIndex: 3, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: '"To weather the storm" means to come safely through a period of difficulty.', source },
  { id: 'inet-english-and-reasoning-numerical-ability-02-008', section: 'English', topic: 'Voice (Active-Passive)', difficulty: 'medium', question: 'Choose the correct passive voice of: "The navigator plotted the course."', options: ['The course is plotted by the navigator.', 'The course has been plotted by the navigator.', 'The course was plotted by the navigator.', 'The navigator was plotting the course.'], correctIndex: 2, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: 'Simple past active becomes simple past passive: The course was plotted by the navigator.', source },
  { id: 'inet-english-and-reasoning-numerical-ability-02-009', section: 'English', topic: 'Articles', difficulty: 'easy', question: 'Fill in the blank: She joined ___ Indian Navy last year.', options: ['a', 'an', 'the', 'No article'], correctIndex: 2, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: 'Names of the armed services take the definite article: the Indian Navy.', source },
  { id: 'inet-english-and-reasoning-numerical-ability-02-010', section: 'English', topic: 'Spelling', difficulty: 'easy', question: 'Choose the correctly spelled word.', options: ['Ocassion', 'Occassion', 'Ocasion', 'Occasion'], correctIndex: 3, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: 'The correct spelling is "Occasion", with double "c" and a single "s".', source },
  { id: 'inet-english-and-reasoning-numerical-ability-02-011', section: 'English', topic: 'Synonyms', difficulty: 'easy', question: 'Choose the word closest in meaning to "Vigilant".', options: ['Watchful', 'Careless', 'Timid', 'Sluggish'], correctIndex: 0, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: '"Vigilant" means keeping careful watch for possible danger, closest to "Watchful".', source },
  { id: 'inet-english-and-reasoning-numerical-ability-02-012', section: 'English', topic: 'Conjunctions', difficulty: 'medium', question: 'Fill in the blank: ___ the sea was rough, the crew completed the drill.', options: ['Because', 'Although', 'Therefore', 'Unless'], correctIndex: 1, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: 'The rough sea works against completing the drill, so the sentence needs the concessive conjunction "Although".', source },
  { id: 'inet-english-and-reasoning-numerical-ability-02-013', section: 'Reasoning and Numerical Ability', topic: 'Number Series', difficulty: 'medium', question: 'Find the next term: 4, 9, 19, 39, ?', options: ['59', '69', '78', '79'], correctIndex: 3, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: 'Each term is twice the previous term plus one: 39 × 2 + 1 = 79.', source },
  { id: 'inet-english-and-reasoning-numerical-ability-02-014', section: 'Reasoning and Numerical Ability', topic: 'Analogy', difficulty: 'easy', question: 'Captain is to Ship as Pilot is to ?', options: ['Runway', 'Hangar', 'Aircraft', 'Passenger'], correctIndex: 2, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: 'A captain commands a ship, and the craft a pilot commands is an aircraft. A runway and a hangar are places, not the craft itself.', source },
  { id: 'inet-english-and-reasoning-numerical-ability-02-015', section: 'Reasoning and Numerical Ability', topic: 'Coding-Decoding', difficulty: 'medium', question: 'If SHIP is coded as TIJQ (each letter shifted one place forward in the alphabet), how is BOAT coded?', options: ['CPAU', 'CPBU', 'BPBU', 'CQBU'], correctIndex: 1, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: 'Shifting each letter one place forward gives B to C, O to P, A to B and T to U, producing CPBU.', source },
  { id: 'inet-english-and-reasoning-numerical-ability-02-016', section: 'Reasoning and Numerical Ability', topic: 'Blood Relations', difficulty: 'medium', question: 'Pointing to a woman, a man said, "She is the only daughter of my father\'s only son." How is she related to the man?', options: ['His daughter', 'His sister', 'His niece', 'His cousin'], correctIndex: 0, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: 'The man is his father\'s only son, so "my father\'s only son" refers to the speaker himself, making the woman his daughter.', source },
  { id: 'inet-english-and-reasoning-numerical-ability-02-017', section: 'Reasoning and Numerical Ability', topic: 'Direction Sense', difficulty: 'medium', question: 'A ship sails 9 km east, then turns left and sails 12 km north. How far is it from its starting point?', options: ['15 km', '21 km', '18 km', '13 km'], correctIndex: 0, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: 'The two legs are at right angles, so the distance is √(9² + 12²) = √225 = 15 km.', source },
  { id: 'inet-english-and-reasoning-numerical-ability-02-018', section: 'Reasoning and Numerical Ability', topic: 'Classification', difficulty: 'easy', question: 'Which of the following does not belong with the others?', options: ['Frigate', 'Destroyer', 'Submarine', 'Lighthouse'], correctIndex: 3, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: 'A frigate, a destroyer and a submarine are all vessels. A lighthouse is a fixed shore structure, so it is the odd one out.', source },
  { id: 'inet-english-and-reasoning-numerical-ability-02-019', section: 'Reasoning and Numerical Ability', topic: 'Simple Interest', difficulty: 'easy', question: 'Find the simple interest on ₹8,000 at 5% per annum for 3 years.', options: ['₹800', '₹1,000', '₹1,200', '₹1,600'], correctIndex: 2, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: 'Simple interest = (P × R × T) / 100 = (8000 × 5 × 3) / 100 = ₹1,200.', source },
  { id: 'inet-english-and-reasoning-numerical-ability-02-020', section: 'Reasoning and Numerical Ability', topic: 'Average', difficulty: 'medium', question: 'The average of five consecutive even numbers is 16. Find the largest of them.', options: ['18', '20', '22', '24'], correctIndex: 1, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: 'For an odd count of consecutive even numbers the average is the middle one, so the numbers are 12, 14, 16, 18 and 20, and the largest is 20.', source },
  { id: 'inet-english-and-reasoning-numerical-ability-02-021', section: 'Reasoning and Numerical Ability', topic: 'Percentage (Successive Change)', difficulty: 'medium', question: 'The price of a commodity falls by 25%. By what percentage must consumption rise to keep total expenditure unchanged?', options: ['25%', '33⅓%', '40%', '50%'], correctIndex: 1, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: 'Expenditure is price × consumption. With price at 0.75 of the original, consumption must become 1/0.75 = 4/3 of the original, a rise of 33⅓%.', source },
  { id: 'inet-english-and-reasoning-numerical-ability-02-022', section: 'Reasoning and Numerical Ability', topic: 'HCF and LCM', difficulty: 'easy', question: 'Find the LCM of 15 and 20.', options: ['60', '5', '30', '300'], correctIndex: 0, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: '15 = 3 × 5 and 20 = 2² × 5, so the LCM is 2² × 3 × 5 = 60. The value 5 is their HCF and 300 is their product.', source },
  { id: 'inet-english-and-reasoning-numerical-ability-02-023', section: 'Reasoning and Numerical Ability', topic: 'Simplification', difficulty: 'easy', question: 'Simplify: 36 ÷ 6 + 4 × 2 − 5.', options: ['7', '8', '11', '9'], correctIndex: 3, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: 'Division and multiplication come first: 6 + 8 − 5 = 9.', source },
  { id: 'inet-english-and-reasoning-numerical-ability-02-024', section: 'Reasoning and Numerical Ability', topic: 'Profit and Loss', difficulty: 'medium', question: 'An article bought for ₹450 is sold for ₹540. Find the profit percentage.', options: ['15%', '18%', '20%', '25%'], correctIndex: 2, answerType: 'mcq', marks: 4, negativeMarking: 1, explanation: 'Profit is ₹90 on a cost of ₹450, so the profit percentage is (90 / 450) × 100 = 20%.', source },
];
