import type { Question } from '../questions';

export const KVS_PRT_2025_TIER_1_ENGLISH_1: Question[] = [
  { id: 'b13-001-en-q01', section: 'Language Competency Test (English)', topic: 'Subject-verb agreement', difficulty: 'easy', question: 'Choose the sentence with correct subject–verb agreement.', options: ['The list of materials is on the desk.', 'The list of materials are on the desk.', 'The lists of material is on the desk.', 'The list of materials were on the desk.'], correctIndex: 0, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: '“The list of materials is on the desk.” is the grammatically or semantically correct choice for this item.', source: { kind: 'original', reference: 'CBSE KVS/NVS Recruitment Notification 01/2025', url: 'https://www.cbse.gov.in/cbsenew/documents/Detailed_Notification_KVS_NVS_2025_13112025.pdf', checkedOn: '2026-09-09' } },
  { id: 'b13-001-en-q02', section: 'Language Competency Test (English)', topic: 'Preposition', difficulty: 'easy', question: 'Complete the sentence: “The committee agreed ___ the revised schedule.”', options: ['at', 'on', 'for', 'by'], correctIndex: 1, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: '“on” is the grammatically or semantically correct choice for this item.', source: { kind: 'original', reference: 'CBSE KVS/NVS Recruitment Notification 01/2025', url: 'https://www.cbse.gov.in/cbsenew/documents/Detailed_Notification_KVS_NVS_2025_13112025.pdf', checkedOn: '2026-09-09' } },
  { id: 'b13-001-en-q03', section: 'Language Competency Test (English)', topic: 'Vocabulary', difficulty: 'easy', question: 'Which word is closest in meaning to “concise”?', options: ['uncertain', 'ornamental', 'brief', 'distant'], correctIndex: 2, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: '“brief” is the grammatically or semantically correct choice for this item.', source: { kind: 'original', reference: 'CBSE KVS/NVS Recruitment Notification 01/2025', url: 'https://www.cbse.gov.in/cbsenew/documents/Detailed_Notification_KVS_NVS_2025_13112025.pdf', checkedOn: '2026-09-09' } },
  { id: 'b13-001-en-q04', section: 'Language Competency Test (English)', topic: 'Antonym', difficulty: 'easy', question: 'Choose the antonym of “scarce”.', options: ['rare', 'limited', 'meagre', 'abundant'], correctIndex: 3, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: '“abundant” is the grammatically or semantically correct choice for this item.', source: { kind: 'original', reference: 'CBSE KVS/NVS Recruitment Notification 01/2025', url: 'https://www.cbse.gov.in/cbsenew/documents/Detailed_Notification_KVS_NVS_2025_13112025.pdf', checkedOn: '2026-09-09' } },
  { id: 'b13-001-en-q05', section: 'Language Competency Test (English)', topic: 'Article', difficulty: 'easy', question: 'Choose the correct phrase.', options: ['an honest response', 'a honest response', 'the honest response always', 'honest an response'], correctIndex: 0, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: '“an honest response” is the grammatically or semantically correct choice for this item.', source: { kind: 'original', reference: 'CBSE KVS/NVS Recruitment Notification 01/2025', url: 'https://www.cbse.gov.in/cbsenew/documents/Detailed_Notification_KVS_NVS_2025_13112025.pdf', checkedOn: '2026-09-09' } },
  { id: 'b13-001-en-q06', section: 'Language Competency Test (English)', topic: 'Tense', difficulty: 'easy', question: 'Choose the sentence that correctly expresses an action completed before another past action.', options: ['The bus leaves before we reached the stop.', 'The bus had left before we reached the stop.', 'The bus has left before we reached the stop.', 'The bus was leave before we reached the stop.'], correctIndex: 1, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: '“The bus had left before we reached the stop.” is the grammatically or semantically correct choice for this item.', source: { kind: 'original', reference: 'CBSE KVS/NVS Recruitment Notification 01/2025', url: 'https://www.cbse.gov.in/cbsenew/documents/Detailed_Notification_KVS_NVS_2025_13112025.pdf', checkedOn: '2026-09-09' } },
  { id: 'b13-001-en-q07', section: 'Language Competency Test (English)', topic: 'Pronoun', difficulty: 'medium', question: 'Choose the grammatically correct sentence.', options: ['Each participant submit their form on time.', 'Each participant submitted them form on time.', 'Each participant submitted their form on time.', 'Each participant submitting their form on time.'], correctIndex: 2, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: '“Each participant submitted their form on time.” is the grammatically or semantically correct choice for this item.', source: { kind: 'original', reference: 'CBSE KVS/NVS Recruitment Notification 01/2025', url: 'https://www.cbse.gov.in/cbsenew/documents/Detailed_Notification_KVS_NVS_2025_13112025.pdf', checkedOn: '2026-09-09' } },
  { id: 'b13-001-en-q08', section: 'Language Competency Test (English)', topic: 'Punctuation', difficulty: 'medium', question: 'Which sentence uses the apostrophe correctly?', options: ['The teacher’s room are on the first floor.', 'The teachers room’s is on the first floor.', 'The teachers’s room is on the first floor.', 'The teachers’ room is on the first floor.'], correctIndex: 3, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: '“The teachers’ room is on the first floor.” is the grammatically or semantically correct choice for this item.', source: { kind: 'original', reference: 'CBSE KVS/NVS Recruitment Notification 01/2025', url: 'https://www.cbse.gov.in/cbsenew/documents/Detailed_Notification_KVS_NVS_2025_13112025.pdf', checkedOn: '2026-09-09' } },
  { id: 'b13-001-en-q09', section: 'Language Competency Test (English)', topic: 'Sentence transformation', difficulty: 'medium', question: 'Choose the passive form of “The team completed the audit.”', options: ['The audit was completed by the team.', 'The audit completed the team.', 'The team was completed by the audit.', 'The audit is completing by the team.'], correctIndex: 0, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: '“The audit was completed by the team.” is the grammatically or semantically correct choice for this item.', source: { kind: 'original', reference: 'CBSE KVS/NVS Recruitment Notification 01/2025', url: 'https://www.cbse.gov.in/cbsenew/documents/Detailed_Notification_KVS_NVS_2025_13112025.pdf', checkedOn: '2026-09-09' } },
  { id: 'b13-001-en-q10', section: 'Language Competency Test (English)', topic: 'Contextual meaning', difficulty: 'medium', question: 'In “The new rule is transparent,” transparent most nearly means __.', options: ['made only of glass', 'clear and easy to understand', 'hidden from view', 'temporary and informal'], correctIndex: 1, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: '“clear and easy to understand” is the grammatically or semantically correct choice for this item.', source: { kind: 'original', reference: 'CBSE KVS/NVS Recruitment Notification 01/2025', url: 'https://www.cbse.gov.in/cbsenew/documents/Detailed_Notification_KVS_NVS_2025_13112025.pdf', checkedOn: '2026-09-09' } },
];
