import type { Question } from '../questions';

// LIC AAO (Generalist) Prelims: English Language, Test 2, 30 questions.
// Qualifying section: scored, but its marks are not included in the Prelims
// ranking calculation per the official notification (only Reasoning +
// Quantitative Aptitude count toward the merit cutoff).
const source = {
  kind: 'original' as const,
  reference: 'LIC AAO (Generalist) 2025-26 Recruitment Notification',
  url: 'https://www.licindia.in/recruitment-of-aao-generalists/-specialists/-assistant-engineers-2025',
  checkedOn: '22 August 2026',
};

export const LIC_AAO_PRELIMS_ENGLISH_LANGUAGE_2: Question[] = [
  { id: 'lic-p-en2-001', section: 'English Language', topic: 'Synonyms', difficulty: 'easy', question: 'Choose the word most similar in meaning to "PRUDENT".', options: ['Careful and sensible', 'Careless', 'Reckless', 'Impulsive'], correctIndex: 0, explanation: '"Prudent" describes someone who acts with care and good judgement, matching "careful and sensible".', source },
  { id: 'lic-p-en2-002', section: 'English Language', topic: 'Synonyms', difficulty: 'easy', question: 'Choose the word most similar in meaning to "CORDIAL".', options: ['Warm and friendly', 'Hostile', 'Distant', 'Rude'], correctIndex: 0, explanation: '"Cordial" means warm and friendly in manner.', source },
  { id: 'lic-p-en2-003', section: 'English Language', topic: 'Synonyms', difficulty: 'medium', question: 'Choose the word most similar in meaning to "ZENITH".', options: ['The lowest point', 'The highest point', 'A boundary line', 'A gradual decline'], correctIndex: 1, explanation: '"Zenith" refers to the highest point or peak of something.', source },
  { id: 'lic-p-en2-004', section: 'English Language', topic: 'Synonyms', difficulty: 'medium', question: 'Choose the word most similar in meaning to "ALLEVIATE".', options: ['To worsen', 'To postpone', 'To ease or reduce', 'To ignore'], correctIndex: 2, explanation: '"Alleviate" means to make a problem or suffering less severe.', source },
  { id: 'lic-p-en2-005', section: 'English Language', topic: 'Antonyms', difficulty: 'easy', question: 'Choose the word most opposite in meaning to "AUTHENTIC".', options: ['Real', 'Fake', 'Genuine', 'Original'], correctIndex: 1, explanation: '"Authentic" means genuine or real; its opposite is "fake".', source },
  { id: 'lic-p-en2-006', section: 'English Language', topic: 'Antonyms', difficulty: 'easy', question: 'Choose the word most opposite in meaning to "PRECISE".', options: ['Vague', 'Exact', 'Accurate', 'Clear'], correctIndex: 0, explanation: '"Precise" means exact and accurate; its opposite is "vague".', source },
  { id: 'lic-p-en2-007', section: 'English Language', topic: 'Antonyms', difficulty: 'medium', question: 'Choose the word most opposite in meaning to "CONFIDENTIAL" (as used for information).', options: ['Private', 'Secret', 'Restricted', 'Public'], correctIndex: 3, explanation: 'Confidential information is kept private; its opposite is "public", meaning openly known.', source },
  { id: 'lic-p-en2-008', section: 'English Language', topic: 'Antonyms', difficulty: 'medium', question: 'Choose the word most opposite in meaning to "LIABLE" (as used for legal responsibility).', options: ['Responsible', 'Accountable', 'Exempt', 'Obligated'], correctIndex: 2, explanation: 'Being "liable" means being legally responsible; its opposite is "exempt", meaning free from an obligation.', source },
  { id: 'lic-p-en2-009', section: 'English Language', topic: 'Spelling Correction', difficulty: 'easy', question: 'Identify the word that is spelled correctly.', options: ['Adress', 'Address', 'Addres', 'Addresss'], correctIndex: 1, explanation: 'The correct spelling is "Address", with a double "d" and a double "s".', source },
  { id: 'lic-p-en2-010', section: 'English Language', topic: 'Spelling Correction', difficulty: 'easy', question: 'Select the correctly spelled option from the choices below.', options: ['Privilege', 'Priviledge', 'Priviledg', 'Privilage'], correctIndex: 0, explanation: 'The correct spelling is "Privilege".', source },
  { id: 'lic-p-en2-011', section: 'English Language', topic: 'Spelling Correction', difficulty: 'medium', question: 'Pick the word below that has no spelling error.', options: ['Questionaire', 'Questionnair', 'Questionaires', 'Questionnaire'], correctIndex: 3, explanation: 'The correct spelling is "Questionnaire", with a double "n".', source },
  { id: 'lic-p-en2-012', section: 'English Language', topic: 'Fill in the Blanks', difficulty: 'easy', question: 'Fill in the blank: "The nominee ___ the death certificate along with the claim form."', options: ['submit', 'submitting', 'submitted', 'submits'], correctIndex: 2, explanation: 'The sentence describes a completed past action, so the simple past tense "submitted" is correct.', source },
  { id: 'lic-p-en2-013', section: 'English Language', topic: 'Fill in the Blanks', difficulty: 'medium', question: 'Fill in the blank: "If the premium is not paid within the grace period, the policy ___ lapse."', options: ['would', 'will', 'has', 'was'], correctIndex: 1, explanation: 'This is a first conditional sentence describing a likely future outcome, so "will" is correct.', source },
  { id: 'lic-p-en2-014', section: 'English Language', topic: 'Fill in the Blanks', difficulty: 'medium', question: 'Fill in the blank: "Either the agent or the customers ___ responsible for the delay."', options: ['are', 'is', 'was', 'has'], correctIndex: 0, explanation: 'With "either...or", the verb agrees with the subject nearer to it; "customers" is plural, so "are" is correct.', source },
  { id: 'lic-p-en2-015', section: 'English Language', topic: 'One Word Substitution', difficulty: 'medium', question: 'Choose the word that means "a person appointed to settle a dispute".', options: ['Claimant', 'Litigant', 'Notary', 'Arbitrator'], correctIndex: 3, explanation: 'An arbitrator is a neutral person appointed to settle a dispute between two parties.', source },
  { id: 'lic-p-en2-016', section: 'English Language', topic: 'One Word Substitution', difficulty: 'medium', question: 'Choose the word that means "one who receives benefits from an insurance policy".', options: ['Underwriter', 'Actuary', 'Beneficiary', 'Broker'], correctIndex: 2, explanation: 'A beneficiary is the person designated to receive the benefits of an insurance policy.', source },
  { id: 'lic-p-en2-017', section: 'English Language', topic: 'Idioms and Phrases', difficulty: 'easy', question: 'Choose the meaning closest to the idiom "to bear the brunt".', options: ['To avoid all responsibility', 'To suffer the main impact of something', 'To celebrate a success', 'To delay a decision'], correctIndex: 1, explanation: '"To bear the brunt" means to suffer the main force or impact of something unpleasant.', source },
  { id: 'lic-p-en2-018', section: 'English Language', topic: 'Idioms and Phrases', difficulty: 'medium', question: 'Choose the meaning closest to the idiom "to hold water" (as used for an argument).', options: ['To be valid or logical', 'To leak information', 'To waste time', 'To remain silent'], correctIndex: 0, explanation: 'An argument that "holds water" is valid and logically sound.', source },
  { id: 'lic-p-en2-019', section: 'English Language', topic: 'Error Spotting', difficulty: 'medium', question: 'Identify the part of the sentence that contains an error: "The number of claims (A) / have increased (B) / significantly over (C) / the last quarter. (D)"', options: ['Part A', 'Part C', 'No error', 'Part B'], correctIndex: 3, explanation: '"The number of" is treated as singular, so "have increased" should be "has increased".', source },
  { id: 'lic-p-en2-020', section: 'English Language', topic: 'Error Spotting', difficulty: 'medium', question: 'Identify the part of the sentence that contains an error: "Neither the manager nor the staff (A) / was informed about (B) / the new policy changes (C) / announced yesterday. (D)"', options: ['Part A', 'Part C', 'Part B', 'No error'], correctIndex: 2, explanation: 'With "neither...nor", the verb agrees with the nearer subject "staff" (plural), so "was" should be "were".', source },
  { id: 'lic-p-en2-021', section: 'English Language', topic: 'Error Spotting', difficulty: 'hard', question: 'Identify the part of the sentence that contains an error: "No sooner had the announcement been made (A) / than the customers (B) / begins to complain (C) / about the delay. (D)"', options: ['Part A', 'Part C', 'Part B', 'No error'], correctIndex: 1, explanation: 'With "no sooner...than", both clauses should be in the past tense; "begins" should be "began".', source },
  { id: 'lic-p-en2-022', section: 'English Language', topic: 'Sentence Improvement', difficulty: 'medium', question: 'Improve the underlined part: "Each of the policies have different terms." (underline: "have different")', options: ['has different', 'have differently', 'has differently', 'No improvement needed'], correctIndex: 0, explanation: '"Each" is singular and takes the singular verb "has".', source },
  { id: 'lic-p-en2-023', section: 'English Language', topic: 'Sentence Improvement', difficulty: 'medium', question: 'Improve the underlined part: "He is one of the agent who sell the most policies." (underline: "agent who sell")', options: ['agent who sells', 'agents who sells', 'No improvement needed', 'agents who sell'], correctIndex: 3, explanation: 'The phrase "one of the..." requires a plural noun ("agents"), and the relative clause verb agrees with that plural noun ("sell").', source },
  { id: 'lic-p-en2-024', section: 'English Language', topic: 'Reading Comprehension', difficulty: 'medium', question: 'Passage: "A whole life insurance policy provides coverage for the insured\'s entire lifetime and also builds a cash value component that grows over time." Based on the passage, a whole life policy covers the insured for:', options: ['A fixed term of 10 years', 'Only until retirement', 'The insured\'s entire lifetime', 'A single calendar year'], correctIndex: 2, explanation: 'The passage explicitly states the policy "provides coverage for the insured\'s entire lifetime".', source },
  { id: 'lic-p-en2-025', section: 'English Language', topic: 'Reading Comprehension', difficulty: 'medium', question: 'Passage: "A whole life insurance policy provides coverage for the insured\'s entire lifetime and also builds a cash value component that grows over time." What additional feature does a whole life policy build, according to the passage?', options: ['A higher premium every year', 'A cash value component that grows over time', 'A shorter policy term', 'An external investment fund'], correctIndex: 1, explanation: 'The passage states the policy "also builds a cash value component that grows over time".', source },
  { id: 'lic-p-en2-026', section: 'English Language', topic: 'Cloze Test', difficulty: 'medium', question: 'Fill in the blank: "Policyholders are advised to ___ their nominee details whenever there is a change in family circumstances."', options: ['update', 'ignore', 'delete', 'postpone'], correctIndex: 0, explanation: 'The sentence advises keeping nominee details current, matching "update".', source },
  { id: 'lic-p-en2-027', section: 'English Language', topic: 'Cloze Test', difficulty: 'medium', question: 'Fill in the blank: "The insurer settled the claim swiftly since the cause of death was clearly ___ by the medical report."', options: ['concealed', 'doubted', 'delayed', 'established'], correctIndex: 3, explanation: 'A swift settlement follows from the cause of death being clearly confirmed, matching "established".', source },
  { id: 'lic-p-en2-028', section: 'English Language', topic: 'Para Jumbles', difficulty: 'hard', question: 'Arrange the sentences in a logical order: (1) This makes it a popular option for long-term financial planning. (2) A whole life policy remains in force for the policyholder\'s entire life. (3) It also accumulates a cash value that policyholders can borrow against. (4) Unlike term insurance, it does not expire after a fixed period.', options: ['2, 3, 4, 1', '4, 2, 3, 1', '2, 4, 3, 1', '2, 1, 4, 3'], correctIndex: 2, explanation: 'The logical flow introduces the concept (2), contrasts it with term insurance (4), adds the cash value feature (3), and concludes with the significance (1).', source },
  { id: 'lic-p-en2-029', section: 'English Language', topic: 'Synonyms', difficulty: 'hard', question: 'Choose the word most similar in meaning to "EXORBITANT" (as used for a price or fee).', options: ['Reasonable', 'Excessively high', 'Negotiable', 'Refundable'], correctIndex: 1, explanation: '"Exorbitant" means unreasonably high, especially in reference to a price or charge.', source },
  { id: 'lic-p-en2-030', section: 'English Language', topic: 'Antonyms', difficulty: 'hard', question: 'Choose the word most opposite in meaning to "VIABLE" (as used for a business plan).', options: ['Practical', 'Feasible', 'Workable', 'Unworkable'], correctIndex: 3, explanation: 'A "viable" plan is workable and practical; its opposite, "unworkable", means unable to succeed.', source },
];
