import type { Question } from '../questions';

// LIC AAO (Generalist) Prelims: Quantitative Aptitude, Test 2, 35 questions.
// Counts toward the Prelims merit ranking (along with Reasoning Ability).
const source = {
  kind: 'original' as const,
  reference: 'LIC AAO (Generalist) 2025-26 Recruitment Notification',
  url: 'https://www.licindia.in/recruitment-of-aao-generalists/-specialists/-assistant-engineers-2025',
  checkedOn: '22 August 2026',
};

export const LIC_AAO_PRELIMS_QUANTITATIVE_APTITUDE_2: Question[] = [
  { id: 'lic-p-qa2-001', section: 'Quantitative Aptitude', topic: 'Simplification', difficulty: 'easy', question: 'What is 20% of 360 plus 30% of 180?', options: ['126', '116', '136', '146'], correctIndex: 0, explanation: '20% of 360 = 72, and 30% of 180 = 54. Their sum is 72 + 54 = 126.', source },
  { id: 'lic-p-qa2-002', section: 'Quantitative Aptitude', topic: 'Simplification', difficulty: 'easy', question: 'What is the value of (15 × 12) − (9 × 7)?', options: ['107', '127', '117', '137'], correctIndex: 2, explanation: '15 × 12 = 180, and 9 × 7 = 63. So 180 − 63 = 117.', source },
  { id: 'lic-p-qa2-003', section: 'Quantitative Aptitude', topic: 'Simplification', difficulty: 'medium', question: 'What is the value of √196 + √169?', options: ['25', '27', '26', '28'], correctIndex: 1, explanation: '√196 = 14 and √169 = 13, so their sum is 14 + 13 = 27.', source },
  { id: 'lic-p-qa2-004', section: 'Quantitative Aptitude', topic: 'Simplification', difficulty: 'medium', question: 'What is the value of two-thirds of 540 minus three-eighths of 320?', options: ['230', '240', '250', '260'], correctIndex: 1, explanation: 'Two-thirds of 540 is 360, and three-eighths of 320 is 120. So 360 − 120 = 240.', source },
  { id: 'lic-p-qa2-005', section: 'Quantitative Aptitude', topic: 'Simplification', difficulty: 'medium', question: 'What is the value of (0.8 × 0.8) − (0.5 × 0.5)?', options: ['0.39', '0.29', '0.49', '0.19'], correctIndex: 0, explanation: '0.8 × 0.8 = 0.64 and 0.5 × 0.5 = 0.25, so the difference is 0.64 − 0.25 = 0.39.', source },
  { id: 'lic-p-qa2-006', section: 'Quantitative Aptitude', topic: 'Percentage', difficulty: 'easy', question: '540 is what percent of 900?', options: ['55%', '65%', '70%', '60%'], correctIndex: 3, explanation: '(540 / 900) × 100 = 60%.', source },
  { id: 'lic-p-qa2-007', section: 'Quantitative Aptitude', topic: 'Percentage', difficulty: 'medium', question: 'A number, when increased by 25%, becomes 400. Find the original number.', options: ['310', '330', '320', '340'], correctIndex: 2, explanation: 'Let the number be x. x × 1.25 = 400, so x = 400 / 1.25 = 320.', source },
  { id: 'lic-p-qa2-008', section: 'Quantitative Aptitude', topic: 'Percentage', difficulty: 'medium', question: 'A candidate scored 456 marks out of 600 in an exam. What percentage did the candidate score?', options: ['74%', '76%', '78%', '80%'], correctIndex: 1, explanation: '(456 / 600) × 100 = 76%.', source },
  { id: 'lic-p-qa2-009', section: 'Quantitative Aptitude', topic: 'Percentage', difficulty: 'hard', question: 'If the price of an item is reduced by 20%, by what percent must the new price be increased to restore the original price?', options: ['25%', '20%', '30%', '33.33%'], correctIndex: 0, explanation: 'After a 20% reduction, the price becomes 80% of the original. To restore it, the increase needed is 20/80 × 100 = 25%.', source },
  { id: 'lic-p-qa2-010', section: 'Quantitative Aptitude', topic: 'Percentage', difficulty: 'hard', question: '50% of a number is 15 more than 30% of the same number. Find the number.', options: ['65', '70', '80', '75'], correctIndex: 3, explanation: 'Let the number be x. 0.5x − 0.3x = 15, so 0.2x = 15, giving x = 75.', source },
  { id: 'lic-p-qa2-011', section: 'Quantitative Aptitude', topic: 'Profit and Loss', difficulty: 'easy', question: 'An article with a cost price of ₹900 is sold for ₹1,035. Find the profit percentage.', options: ['12%', '18%', '15%', '20%'], correctIndex: 2, explanation: 'Profit = 1035 − 900 = 135. Profit percentage = (135 / 900) × 100 = 15%.', source },
  { id: 'lic-p-qa2-012', section: 'Quantitative Aptitude', topic: 'Profit and Loss', difficulty: 'medium', question: 'An article is sold at a loss of 12% for ₹968. Find its cost price.', options: ['₹1050', '₹1100', '₹1150', '₹1200'], correctIndex: 1, explanation: 'Selling price = 0.88 × Cost price. So Cost price = 968 / 0.88 = ₹1100.', source },
  { id: 'lic-p-qa2-013', section: 'Quantitative Aptitude', topic: 'Profit and Loss', difficulty: 'hard', question: 'A shopkeeper marks an item 50% above its cost price and then offers a discount of 20% on the marked price. Find the resulting profit percentage.', options: ['20%', '15%', '18%', '22%'], correctIndex: 0, explanation: 'Marked price = 1.5 × Cost price. Selling price = 0.8 × 1.5 × Cost price = 1.2 × Cost price, giving a profit of 20%.', source },
  { id: 'lic-p-qa2-014', section: 'Quantitative Aptitude', topic: 'Ratio and Proportion', difficulty: 'easy', question: '₹810 is divided between two people in the ratio 4:5. Find the smaller share.', options: ['₹340', '₹350', '₹370', '₹360'], correctIndex: 3, explanation: 'Total parts = 4 + 5 = 9. The smaller share = (4/9) × 810 = ₹360.', source },
  { id: 'lic-p-qa2-015', section: 'Quantitative Aptitude', topic: 'Ratio and Proportion', difficulty: 'medium', question: 'If a:b = 2:3 and b:c = 4:5, find a:b:c.', options: ['6:9:12', '8:10:15', '8:12:15', '6:12:15'], correctIndex: 2, explanation: 'To combine, scale a:b = 2:3 to 8:12 (multiplying by 4) and b:c = 4:5 to 12:15 (multiplying by 3), so both share b = 12, giving a:b:c = 8:12:15.', source },
  { id: 'lic-p-qa2-016', section: 'Quantitative Aptitude', topic: 'Ratio and Proportion', difficulty: 'hard', question: 'If x:y = 4:9, find the value of (2x + 3y):(5x − y).', options: ['31:9', '35:11', '33:10', '37:12'], correctIndex: 1, explanation: 'Let x = 4k and y = 9k. Then 2x + 3y = 8k + 27k = 35k, and 5x − y = 20k − 9k = 11k, giving a ratio of 35:11.', source },
  { id: 'lic-p-qa2-017', section: 'Quantitative Aptitude', topic: 'Ratio and Proportion', difficulty: 'medium', question: '₹36,000 is divided among A, B, and C in the ratio 3:4:5. Find B\'s share.', options: ['₹12,000', '₹9,000', '₹15,000', '₹18,000'], correctIndex: 0, explanation: 'Total parts = 3 + 4 + 5 = 12. B\'s share = (4/12) × 36,000 = ₹12,000.', source },
  { id: 'lic-p-qa2-018', section: 'Quantitative Aptitude', topic: 'Average', difficulty: 'easy', question: 'The average of 5 numbers is 38. If one of the numbers, 24, is replaced by 54, find the new average.', options: ['40', '42', '46', '44'], correctIndex: 3, explanation: 'The original sum is 38 × 5 = 190. Replacing 24 with 54 changes the sum to 190 − 24 + 54 = 220. The new average is 220 / 5 = 44.', source },
  { id: 'lic-p-qa2-019', section: 'Quantitative Aptitude', topic: 'Average', difficulty: 'medium', question: 'The average age of 8 people is 27 years. A 9th person joins the group, and the new average becomes 28 years. Find the age of the 9th person.', options: ['34', '35', '36', '37'], correctIndex: 2, explanation: 'The original total age is 27 × 8 = 216. The new total age is 28 × 9 = 252. The 9th person\'s age is 252 − 216 = 36 years.', source },
  { id: 'lic-p-qa2-020', section: 'Quantitative Aptitude', topic: 'Average', difficulty: 'medium', question: 'The average of three consecutive odd numbers is 27. Find the largest of the three numbers.', options: ['27', '29', '31', '33'], correctIndex: 1, explanation: 'The three consecutive odd numbers are 25, 27, and 29, whose average is (25+27+29)/3 = 27, so the largest is 29.', source },
  { id: 'lic-p-qa2-021', section: 'Quantitative Aptitude', topic: 'Simple and Compound Interest', difficulty: 'easy', question: 'Find the simple interest on ₹6,000 at 9% per annum for 3 years.', options: ['₹1,620', '₹1,500', '₹1,700', '₹1,800'], correctIndex: 0, explanation: 'Simple interest = (Principal × Rate × Time) / 100 = (6000 × 9 × 3) / 100 = ₹1,620.', source },
  { id: 'lic-p-qa2-022', section: 'Quantitative Aptitude', topic: 'Simple and Compound Interest', difficulty: 'medium', question: 'Find the compound interest on ₹8,000 at 10% per annum for 2 years, compounded annually.', options: ['₹1,600', '₹1,760', '₹1,840', '₹1,680'], correctIndex: 3, explanation: 'Amount = 8000 × 1.1 × 1.1 = ₹9,680. Compound interest = 9680 − 8000 = ₹1,680.', source },
  { id: 'lic-p-qa2-023', section: 'Quantitative Aptitude', topic: 'Simple and Compound Interest', difficulty: 'hard', question: 'A sum of money doubles itself in 8 years at simple interest. Find the annual rate of interest.', options: ['10%', '15%', '12.5%', '20%'], correctIndex: 2, explanation: 'If the sum doubles, the interest earned equals the principal (P) over 8 years. Rate = (P × 100) / (P × 8) = 12.5%.', source },
  { id: 'lic-p-qa2-024', section: 'Quantitative Aptitude', topic: 'Simple and Compound Interest', difficulty: 'hard', question: 'Find the difference between the simple interest and compound interest on ₹12,000 at 10% per annum for 2 years.', options: ['₹100', '₹120', '₹110', '₹130'], correctIndex: 1, explanation: 'Simple interest = (12000 × 10 × 2)/100 = ₹2,400. Compound interest: Amount = 12000 × 1.1 × 1.1 = ₹14,520, so CI = ₹2,520. The difference is ₹120.', source },
  { id: 'lic-p-qa2-025', section: 'Quantitative Aptitude', topic: 'Time and Work', difficulty: 'easy', question: 'A can complete a job in 15 days and B can complete the same job in 10 days. Working together, how many days will they take?', options: ['6 days', '5.5 days', '6.5 days', '7 days'], correctIndex: 0, explanation: 'Combined work rate = 1/15 + 1/10 = 2/30 + 3/30 = 5/30 of the job per day. Time taken = 30/5 = 6 days.', source },
  { id: 'lic-p-qa2-026', section: 'Quantitative Aptitude', topic: 'Time and Work', difficulty: 'medium', question: 'A can complete a piece of work alone in 12 days. He works alone for 5 days and then leaves. What fraction of the work is left unfinished?', options: ['5/12', '1/2', '2/3', '7/12'], correctIndex: 3, explanation: 'In 5 days, A completes 5/12 of the work, leaving 1 − 5/12 = 7/12 of the work unfinished.', source },
  { id: 'lic-p-qa2-027', section: 'Quantitative Aptitude', topic: 'Time and Work', difficulty: 'hard', question: 'A, B, and C can individually complete a piece of work in 6, 9, and 18 days respectively. Working together, how many days will they take to finish the work?', options: ['2 days', '4 days', '3 days', '5 days'], correctIndex: 2, explanation: 'Combined work rate = 1/6 + 1/9 + 1/18 = 3/18 + 2/18 + 1/18 = 6/18 = 1/3 of the job per day. Time taken = 3 days.', source },
  { id: 'lic-p-qa2-028', section: 'Quantitative Aptitude', topic: 'Time, Speed and Distance', difficulty: 'easy', question: 'A train travels 420 km in 5 hours at a uniform speed. Find its speed in km/h.', options: ['80 km/h', '84 km/h', '82 km/h', '86 km/h'], correctIndex: 1, explanation: 'Speed = Distance / Time = 420 / 5 = 84 km/h.', source },
  { id: 'lic-p-qa2-029', section: 'Quantitative Aptitude', topic: 'Time, Speed and Distance', difficulty: 'medium', question: 'Convert a speed of 108 km/h into metres per second.', options: ['30 m/s', '28 m/s', '32 m/s', '34 m/s'], correctIndex: 0, explanation: 'To convert km/h to m/s, multiply by 5/18: 108 × 5/18 = 30 m/s.', source },
  { id: 'lic-p-qa2-030', section: 'Quantitative Aptitude', topic: 'Time, Speed and Distance', difficulty: 'hard', question: 'Two trains, 180 m and 120 m long, run in opposite directions on parallel tracks at 63 km/h and 45 km/h respectively. Find the time they take to cross each other.', options: ['8 seconds', '9 seconds', '11 seconds', '10 seconds'], correctIndex: 3, explanation: 'Relative speed = 63 + 45 = 108 km/h = 30 m/s. Total length to cover = 180 + 120 = 300 m. Time = 300 / 30 = 10 seconds.', source },
  { id: 'lic-p-qa2-031', section: 'Quantitative Aptitude', topic: 'Number Series', difficulty: 'easy', question: 'Find the next number in the series: 6, 13, 22, 33, 46, ?', options: ['58', '59', '61', '60'], correctIndex: 2, explanation: 'The differences between consecutive terms increase by 2 each time (7, 9, 11, 13), so the next difference is 15, giving 46 + 15 = 61.', source },
  { id: 'lic-p-qa2-032', section: 'Quantitative Aptitude', topic: 'Number Series', difficulty: 'medium', question: 'Find the next number in the series: 2, 6, 12, 20, 30, ?', options: ['36', '42', '40', '44'], correctIndex: 1, explanation: 'Each term is the product of two consecutive integers (1×2, 2×3, 3×4, 4×5, 5×6), so the next term is 6×7=42.', source },
  { id: 'lic-p-qa2-033', section: 'Quantitative Aptitude', topic: 'Number Series', difficulty: 'easy', question: 'Find the next number in the series: 9, 16, 25, 36, 49, ?', options: ['64', '56', '60', '72'], correctIndex: 0, explanation: 'This is the series of perfect squares (3², 4², 5², 6², 7²...), so the next term is 8² = 64.', source },
  { id: 'lic-p-qa2-034', section: 'Quantitative Aptitude', topic: 'Mensuration', difficulty: 'easy', question: 'Find the area of a rectangle with length 22 m and breadth 8 m.', options: ['170 sq. m', '182 sq. m', '188 sq. m', '176 sq. m'], correctIndex: 3, explanation: 'Area of a rectangle = length × breadth = 22 × 8 = 176 sq. m.', source },
  { id: 'lic-p-qa2-035', section: 'Quantitative Aptitude', topic: 'Mensuration', difficulty: 'medium', question: 'Find the perimeter of a square with side 15 cm.', options: ['55 cm', '58 cm', '60 cm', '62 cm'], correctIndex: 2, explanation: 'Perimeter of a square = 4 × side = 4 × 15 = 60 cm.', source },
];
