import type { Question } from '../questions';

// LIC AAO (Generalist) Prelims: Reasoning Ability, Test 2, 35 questions.
// Counts toward the Prelims merit ranking (along with Quantitative Aptitude).
const source = {
  kind: 'original' as const,
  reference: 'LIC AAO (Generalist) 2025-26 Recruitment Notification',
  url: 'https://www.licindia.in/recruitment-of-aao-generalists/-specialists/-assistant-engineers-2025',
  checkedOn: '22 August 2026',
};

export const LIC_AAO_PRELIMS_REASONING_ABILITY_2: Question[] = [
  { id: 'lic-p-re2-001', section: 'Reasoning Ability', topic: 'Syllogism', difficulty: 'easy', question: 'Statements: All keys are locks. All locks are doors. Conclusion: All keys are doors. Is the conclusion valid?', options: ['Valid', 'Invalid', 'Cannot be determined', 'Only partially valid'], correctIndex: 0, explanation: 'Since every key is a lock, and every lock is a door, it necessarily follows that every key is a door. This is a valid chain syllogism.', source },
  { id: 'lic-p-re2-002', section: 'Reasoning Ability', topic: 'Syllogism', difficulty: 'medium', question: 'Statements: Some jars are bottles. All bottles are containers. Conclusion: Some jars are containers. Is the conclusion valid?', options: ['Invalid', 'Cannot be determined', 'Valid', 'Only partially valid'], correctIndex: 2, explanation: 'Since some jars are bottles, and all bottles are containers, those particular jars must also be containers, so the conclusion necessarily follows.', source },
  { id: 'lic-p-re2-003', section: 'Reasoning Ability', topic: 'Syllogism', difficulty: 'medium', question: 'Statements: No chair is a table. All stools are tables. Conclusion: No stool is a chair. Is the conclusion valid?', options: ['Invalid', 'Valid', 'Cannot be determined', 'Only partially valid'], correctIndex: 1, explanation: 'Since all stools fall within the group of tables, and no table is a chair, stools cannot be chairs either, so the conclusion necessarily follows.', source },
  { id: 'lic-p-re2-004', section: 'Reasoning Ability', topic: 'Syllogism', difficulty: 'hard', question: 'Statements: Some lawyers are judges. All judges are graduates. Conclusion: Some lawyers are graduates. Is the conclusion valid?', options: ['Invalid', 'Valid', 'Cannot be determined', 'Only partially valid'], correctIndex: 1, explanation: 'The lawyers who are also judges must be graduates, since all judges are graduates. This guarantees that at least some lawyers are graduates.', source },
  { id: 'lic-p-re2-005', section: 'Reasoning Ability', topic: 'Coding-Decoding', difficulty: 'easy', question: 'If PEARL is coded as QFBSM (each letter moved one step forward in the alphabet), how would CORAL be coded using the same rule?', options: ['DPSBM', 'CPSBM', 'DPSAM', 'DQSBM'], correctIndex: 0, explanation: 'Shifting each letter of CORAL forward by one: C→D, O→P, R→S, A→B, L→M, giving DPSBM.', source },
  { id: 'lic-p-re2-006', section: 'Reasoning Ability', topic: 'Coding-Decoding', difficulty: 'medium', question: 'In a certain code, TIGER is written as UJHFS. How would CAMEL be written in that code?', options: ['CBNFM', 'DBMFM', 'DBNFN', 'DBNFM'], correctIndex: 3, explanation: 'The code shifts each letter forward by one (T→U, I→J, G→H, E→F, R→S). Applying this to CAMEL: C→D, A→B, M→N, E→F, L→M, giving DBNFM.', source },
  { id: 'lic-p-re2-007', section: 'Reasoning Ability', topic: 'Coding-Decoding', difficulty: 'medium', question: 'If MARKET is coded as NBSLFU using a one-step-forward letter shift, what is the code for BASKET using the same rule?', options: ['BBTLFU', 'CBTLFV', 'CBTLFU', 'CATLFU'], correctIndex: 2, explanation: 'Shifting each letter of BASKET forward by one: B→C, A→B, S→T, K→L, E→F, T→U, giving CBTLFU.', source },
  { id: 'lic-p-re2-008', section: 'Reasoning Ability', topic: 'Coding-Decoding', difficulty: 'easy', question: 'If, using the code A=1, B=2, C=3, and so on, BAT is written as 2-1-20, how would COT be written using the same code?', options: ['3-14-20', '3-15-20', '4-15-20', '3-15-21'], correctIndex: 1, explanation: 'C is the 3rd letter, O is the 15th letter, and T is the 20th letter of the alphabet, giving the code 3-15-20.', source },
  { id: 'lic-p-re2-009', section: 'Reasoning Ability', topic: 'Blood Relations', difficulty: 'medium', question: 'Pointing to a photograph, Tara said, "He is the son of my father\'s only daughter." Tara is that only daughter. Who is the boy in the photograph to Tara?', options: ['Son', 'Brother', 'Nephew', 'Cousin'], correctIndex: 0, explanation: 'Tara herself is her father\'s only daughter, so the son of that daughter is Tara\'s own son.', source },
  { id: 'lic-p-re2-010', section: 'Reasoning Ability', topic: 'Blood Relations', difficulty: 'medium', question: 'A is B\'s mother. C is B\'s brother. D is C\'s son. How is D related to A?', options: ['Son', 'Nephew', 'Grandmother', 'Grandson'], correctIndex: 3, explanation: 'C is A\'s son (as B\'s brother, sharing the same mother A), and D is C\'s son, which makes D the grandson of A.', source },
  { id: 'lic-p-re2-011', section: 'Reasoning Ability', topic: 'Blood Relations', difficulty: 'hard', question: 'Pointing to a girl, a man (who has no brothers) said, "She is the daughter of my mother\'s only son." How is the girl related to the man?', options: ['Niece', 'Sister', 'Daughter', 'Cousin'], correctIndex: 2, explanation: 'Since the man has no brothers, he himself is his mother\'s only son. So "my mother\'s only son" refers to the man, making the girl his own daughter.', source },
  { id: 'lic-p-re2-012', section: 'Reasoning Ability', topic: 'Blood Relations', difficulty: 'hard', question: 'Pointing to a boy, a woman (who has no sisters) said, "He is the only son of my father\'s only daughter." How is the boy related to the woman?', options: ['Nephew', 'Son', 'Brother', 'Cousin'], correctIndex: 1, explanation: 'Since the woman has no sisters, she herself is her father\'s only daughter. So "her only son" refers to the woman\'s own son, making the boy her son.', source },
  { id: 'lic-p-re2-013', section: 'Reasoning Ability', topic: 'Direction Sense', difficulty: 'medium', question: 'A man walks 12 km east, then turns right and walks 5 km, then turns right again and walks 12 km. How far is he from his starting point, and in which direction?', options: ['5 km, south', '5 km, north', '12 km, south', '17 km, south'], correctIndex: 0, explanation: 'Plotting the path: east 12 km, then south 5 km (right turn from east), then west 12 km (right turn from south) brings him back to the same longitude as the start, 5 km to the south.', source },
  { id: 'lic-p-re2-014', section: 'Reasoning Ability', topic: 'Direction Sense', difficulty: 'medium', question: 'Rohit starts from his house and walks 9 km towards north. He then turns left and walks 12 km. How far is he from his house?', options: ['9 km', '12 km', '21 km', '15 km'], correctIndex: 3, explanation: 'Walking 9 km north then 12 km west (a left turn while facing north) forms a right-angled path. The direct distance is √(9² + 12²) = √225 = 15 km.', source },
  { id: 'lic-p-re2-015', section: 'Reasoning Ability', topic: 'Direction Sense', difficulty: 'medium', question: 'A person walks 6 km north, then 6 km east, then 6 km south. How far and in which direction is he from his starting point?', options: ['6 km, west', '12 km, east', '6 km, east', '6 km, north'], correctIndex: 2, explanation: 'The northward and southward legs of 6 km each cancel out, leaving only the 6 km eastward movement, so the final position is 6 km due east of the start.', source },
  { id: 'lic-p-re2-016', section: 'Reasoning Ability', topic: 'Direction Sense', difficulty: 'hard', question: 'If North-West becomes South, and South-West becomes East, what will North become, following the same rule?', options: ['North-East', 'South-West', 'South-East', 'West'], correctIndex: 1, explanation: 'Both given transformations correspond to rotating every direction by 135 degrees. Applying the same rotation to North gives South-West.', source },
  { id: 'lic-p-re2-017', section: 'Reasoning Ability', topic: 'Seating Arrangement', difficulty: 'medium', question: 'Five friends J, K, L, M, and N are sitting in a row facing north, not necessarily in that order. J sits third from the left end. K sits immediate right of J. L sits immediate left of J. M sits immediate right of K. Where does N sit?', options: ['Extreme left end', 'Extreme right end', 'Second from left', 'Third from right'], correctIndex: 0, explanation: 'With J at position 3, L at position 2 (left of J), K at position 4 (right of J), and M at position 5 (right of K), the only remaining seat is position 1, so N sits at the extreme left end.', source },
  { id: 'lic-p-re2-018', section: 'Reasoning Ability', topic: 'Seating Arrangement', difficulty: 'medium', question: 'Five students P, Q, R, S, and T are seated in a row facing north, not necessarily in that order. Q is second from the right end. P sits immediate left of Q. R sits immediate right of Q. S sits immediate left of P. Who sits second from the left end?', options: ['P', 'T', 'R', 'S'], correctIndex: 3, explanation: 'With Q at position 4, P at position 3 (left of Q), R at position 5 (right of Q), and S at position 2 (left of P), position 2 is occupied by S, making S second from the left.', source },
  { id: 'lic-p-re2-019', section: 'Reasoning Ability', topic: 'Ranking and Order', difficulty: 'easy', question: 'In a class of 45 students, Kabir ranks 20th from the top. What is his rank from the bottom?', options: ['25th', '27th', '26th', '24th'], correctIndex: 2, explanation: 'Rank from the bottom = total students − rank from top + 1 = 45 − 20 + 1 = 26th.', source },
  { id: 'lic-p-re2-020', section: 'Reasoning Ability', topic: 'Ranking and Order', difficulty: 'medium', question: 'Anita is 14th from the front and 22nd from the end in a queue. How many people are there in the queue?', options: ['33', '35', '34', '36'], correctIndex: 1, explanation: 'Total people = (rank from front) + (rank from end) − 1 = 14 + 22 − 1 = 35.', source },
  { id: 'lic-p-re2-021', section: 'Reasoning Ability', topic: 'Alphabet Series', difficulty: 'medium', question: 'Find the missing term in the series: C, F, J, O, ?', options: ['U', 'S', 'T', 'V'], correctIndex: 0, explanation: 'The gap between consecutive letters increases by one each time (+3, +4, +5, +6): C(3), F(6), J(10), O(15), and the next term is 15+6=21, which is U.', source },
  { id: 'lic-p-re2-022', section: 'Reasoning Ability', topic: 'Alphabet Series', difficulty: 'medium', question: 'Find the missing term in the series: Y, W, T, P, ?', options: ['L', 'J', 'I', 'K'], correctIndex: 3, explanation: 'The gap between consecutive letters decreases (moving back) by an increasing amount each time (-2, -3, -4, -5): Y(25), W(23), T(20), P(16), and the next term is 16-5=11, which is K.', source },
  { id: 'lic-p-re2-023', section: 'Reasoning Ability', topic: 'Number Series', difficulty: 'easy', question: 'Find the next number in the series: 3, 10, 29, 66, ?', options: ['125', '129', '127', '131'], correctIndex: 2, explanation: 'Each term is one more than a perfect cube (1³+2, 2³+2, 3³+2, 4³+2...), so the next term is 5³+2 = 127.', source },
  { id: 'lic-p-re2-024', section: 'Reasoning Ability', topic: 'Number Series', difficulty: 'medium', question: 'Find the next number in the series: 3, 7, 15, 31, ?', options: ['61', '63', '65', '67'], correctIndex: 1, explanation: 'Each term is double the previous term plus 1: 3×2+1=7, 7×2+1=15, 15×2+1=31, so the next term is 31×2+1=63.', source },
  { id: 'lic-p-re2-025', section: 'Reasoning Ability', topic: 'Classification', difficulty: 'easy', question: 'Which of the following does not belong with the others: Sparrow, Peacock, Ostrich, Salmon?', options: ['Salmon', 'Sparrow', 'Peacock', 'Ostrich'], correctIndex: 0, explanation: 'Sparrow, Peacock, and Ostrich are all birds, while Salmon is a fish, making it the odd one out.', source },
  { id: 'lic-p-re2-026', section: 'Reasoning Ability', topic: 'Classification', difficulty: 'medium', question: 'Select the option that does not fit with the rest: Circle, Rectangle, Pentagon, Sphere.', options: ['Circle', 'Rectangle', 'Pentagon', 'Sphere'], correctIndex: 3, explanation: 'Circle, Rectangle, and Pentagon are all two-dimensional shapes, while a Sphere is a three-dimensional solid, making it the odd one out.', source },
  { id: 'lic-p-re2-027', section: 'Reasoning Ability', topic: 'Inequality', difficulty: 'medium', question: 'Statements: X > Y ≥ Z > W. Conclusions: I. X > W  II. Y > W. Which conclusion(s) follow?', options: ['Only I follows', 'Only II follows', 'Both I and II follow', 'Neither follows'], correctIndex: 2, explanation: 'Since X > Y ≥ Z > W, it follows directly that X > W. Also, since Y ≥ Z > W, it follows that Y > W. Both conclusions are valid.', source },
  { id: 'lic-p-re2-028', section: 'Reasoning Ability', topic: 'Inequality', difficulty: 'hard', question: 'Statements: M ≥ N > O = P. Conclusions: I. M > P  II. N ≥ P. Which conclusion(s) follow?', options: ['Only I follows', 'Both I and II follow', 'Only II follows', 'Neither follows'], correctIndex: 1, explanation: 'Since N > O = P, we get N > P; combined with M ≥ N, this gives M > P (Conclusion I). Also, N > P directly implies N ≥ P (Conclusion II). Both conclusions are valid.', source },
  { id: 'lic-p-re2-029', section: 'Reasoning Ability', topic: 'Analogy', difficulty: 'easy', question: 'PEN is to WRITE as KNIFE is to ?', options: ['Cut', 'Sharpen', 'Kitchen', 'Blade'], correctIndex: 0, explanation: 'A pen is meant for writing, just as a knife is meant for cutting, so the relationship is one of purpose.', source },
  { id: 'lic-p-re2-030', section: 'Reasoning Ability', topic: 'Analogy', difficulty: 'medium', question: 'TAILOR is to CLOTHES as CARPENTER is to ?', options: ['Nails', 'Workshop', 'Hammer', 'Furniture'], correctIndex: 3, explanation: 'A tailor makes clothes, just as a carpenter makes furniture, so the relationship is one of product made.', source },
  { id: 'lic-p-re2-031', section: 'Reasoning Ability', topic: 'Analogy', difficulty: 'medium', question: '9 is to 81 as 7 is to ?', options: ['42', '47', '49', '56'], correctIndex: 2, explanation: 'The relationship is that the second number is the square of the first: 9² = 81, so 7² = 49.', source },
  { id: 'lic-p-re2-032', section: 'Reasoning Ability', topic: 'Age Puzzles', difficulty: 'hard', question: 'Six years ago, X\'s age was four times Y\'s age. After 6 more years from now, X\'s age will be twice Y\'s age. Find Y\'s present age.', options: ['10 years', '12 years', '11 years', '13 years'], correctIndex: 1, explanation: 'Let Y\'s age six years ago be x, so X\'s age then was 4x. Their present ages are (x+6) and (4x+6). Six years from now: (4x+12) = 2(x+12), which gives x=6, so Y\'s present age is x+6=12 years.', source },
  { id: 'lic-p-re2-033', section: 'Reasoning Ability', topic: 'Age Puzzles', difficulty: 'hard', question: 'A mother\'s present age is 4 times her daughter\'s present age. After 8 years, the mother\'s age will be twice the daughter\'s age. Find the daughter\'s present age.', options: ['4 years', '5 years', '6 years', '7 years'], correctIndex: 0, explanation: 'Let the daughter\'s present age be x, so the mother\'s present age is 4x. After 8 years: (4x+8) = 2(x+8), which gives x=4, so the daughter\'s present age is 4 years.', source },
  { id: 'lic-p-re2-034', section: 'Reasoning Ability', topic: 'Classification', difficulty: 'medium', question: 'Find the one that does not belong to the group: Chennai, Bengaluru, Hyderabad, Kerala.', options: ['Chennai', 'Bengaluru', 'Hyderabad', 'Kerala'], correctIndex: 3, explanation: 'Chennai, Bengaluru, and Hyderabad are all cities, while Kerala is a state, making it the odd one out.', source },
  { id: 'lic-p-re2-035', section: 'Reasoning Ability', topic: 'Coding-Decoding', difficulty: 'medium', question: 'In a certain code, RIVER is written as SJWFS (each letter shifted one step forward). How would DIVER be written using the same code?', options: ['EJWFT', 'DJWFS', 'EJWFS', 'EIWFS'], correctIndex: 2, explanation: 'Shifting each letter of DIVER forward by one: D→E, I→J, V→W, E→F, R→S, giving EJWFS.', source },
];
