import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'LIC AAO (Generalist) 2025-26 Recruitment Notification, Mains syllabus — Reasoning Ability section',
  url: 'https://www.licindia.in/recruitment-of-aao-generalists/-specialists/-assistant-engineers-2025',
  checkedOn: '27 August 2026',
};

const SCHEDULE_PUZZLE =
  "Five people M, N, O, P, and Q have interviews scheduled on five different days of the same week, Monday to Friday, not necessarily in that order. O's interview is on Monday. Q's interview is immediately after O's. N's interview is two days before P's. M's interview is not on Friday.\n\n";

const BOOKS_PUZZLE =
  'Five people R, S, T, U, and V have different numbers of books. R has more books than only one person. T has the most books. S has fewer books than U but more books than V.\n\n';

const INEQUALITY_LEGEND =
  "In these questions, the following symbols indicate relationships: '@' means greater than, '#' means less than, '%' means greater than or equal to, '$' means less than or equal to, and '&' means equal to. Read the given statements and decide which of the conclusions logically follow(s).\n\n";

const WORD_LIST =
  'Consider the following words: 1. Install 2. Instant 3. Insurance 4. Insure 5. Insurer. If these words are arranged as they would appear in an English dictionary, answer the question that follows.\n\n';

export const LIC_AAO_MAINS_REASONING_ABILITY_1: Question[] = [
  { id: 'lic-aao-m1-re-001', section: 'Reasoning Ability', topic: 'Puzzle', difficulty: 'hard', question: `${SCHEDULE_PUZZLE}On which day is P's interview?`, options: ['Friday', 'Thursday', 'Wednesday', 'Tuesday'], correctIndex: 0, marks: 3, negativeMarking: 0, explanation: "O=Monday, Q=Tuesday (immediately after O). Among the remaining days (Wednesday, Thursday, Friday), N two days before P only fits N=Wednesday, P=Friday, leaving M=Thursday. P's interview is on Friday.", source },
  { id: 'lic-aao-m1-re-002', section: 'Reasoning Ability', topic: 'Puzzle', difficulty: 'hard', question: `${SCHEDULE_PUZZLE}Who has an interview on Wednesday?`, options: ['N', 'M', 'P', 'Q'], correctIndex: 0, marks: 3, negativeMarking: 0, explanation: 'The full schedule is O=Monday, Q=Tuesday, N=Wednesday, M=Thursday, P=Friday. N has the Wednesday interview.', source },
  { id: 'lic-aao-m1-re-003', section: 'Reasoning Ability', topic: 'Puzzle', difficulty: 'hard', question: `${SCHEDULE_PUZZLE}How many people have interviews before P's?`, options: ['4', '3', '2', '1'], correctIndex: 0, marks: 3, negativeMarking: 0, explanation: 'P is on Friday, the last day of the schedule (O, Q, N, M, then P), so all 4 other people have interviews before P.', source },
  { id: 'lic-aao-m1-re-004', section: 'Reasoning Ability', topic: 'Puzzle', difficulty: 'hard', question: `${SCHEDULE_PUZZLE}Who has an interview immediately before M?`, options: ['N', 'O', 'Q', 'P'], correctIndex: 0, marks: 3, negativeMarking: 0, explanation: 'M is on Thursday. The schedule is O=Monday, Q=Tuesday, N=Wednesday, M=Thursday, P=Friday, so N (Wednesday) is immediately before M.', source },
  { id: 'lic-aao-m1-re-005', section: 'Reasoning Ability', topic: 'Puzzle', difficulty: 'hard', question: `${BOOKS_PUZZLE}Who has the most books?`, options: ['T', 'U', 'S', 'R'], correctIndex: 0, marks: 3, negativeMarking: 0, explanation: 'T is explicitly stated to have the most books, confirmed by the derived order T > U > S > R > V.', source },
  { id: 'lic-aao-m1-re-006', section: 'Reasoning Ability', topic: 'Puzzle', difficulty: 'hard', question: `${BOOKS_PUZZLE}Who has the fewest books?`, options: ['V', 'R', 'S', 'U'], correctIndex: 0, marks: 3, negativeMarking: 0, explanation: 'Working through the constraints, the full order (most to fewest) is T, U, S, R, V. V has the fewest books.', source },
  { id: 'lic-aao-m1-re-007', section: 'Reasoning Ability', topic: 'Puzzle', difficulty: 'hard', question: `${BOOKS_PUZZLE}How many people have more books than S?`, options: ['2', '1', '3', '4'], correctIndex: 0, marks: 3, negativeMarking: 0, explanation: 'The order (most to fewest) is T, U, S, R, V. T and U have more books than S — 2 people.', source },
  { id: 'lic-aao-m1-re-008', section: 'Reasoning Ability', topic: 'Puzzle', difficulty: 'hard', question: `${BOOKS_PUZZLE}Who is exactly in the middle (3rd) when ranked by number of books?`, options: ['S', 'R', 'U', 'V'], correctIndex: 0, marks: 3, negativeMarking: 0, explanation: 'The order (most to fewest) is T, U, S, R, V. The 3rd position is S.', source },
  { id: 'lic-aao-m1-re-009', section: 'Reasoning Ability', topic: 'Syllogism', difficulty: 'medium', question: 'Statements:\nAll policies are contracts.\nSome contracts are claims.\n\nConclusions:\nI. Some policies are claims.\nII. Some claims are policies.', options: ['Only I follows', 'Neither I nor II follows', 'Only II follows', 'Both I and II follow'], correctIndex: 1, marks: 3, negativeMarking: 0, explanation: 'The contracts that are claims need not overlap with the contracts that are policies, so neither conclusion can be drawn with certainty.', source },
  { id: 'lic-aao-m1-re-010', section: 'Reasoning Ability', topic: 'Syllogism', difficulty: 'medium', question: 'Statements:\nSome premiums are payments.\nAll payments are transactions.\n\nConclusions:\nI. Some premiums are transactions.\nII. Some transactions are premiums.', options: ['Only I follows', 'Only II follows', 'Neither I nor II follows', 'Both I and II follow'], correctIndex: 3, marks: 3, negativeMarking: 0, explanation: 'The premiums that are payments are also transactions (since all payments are transactions), so some premiums are transactions (I), and by conversion, some transactions are premiums (II). Both follow.', source },
  { id: 'lic-aao-m1-re-011', section: 'Reasoning Ability', topic: 'Syllogism', difficulty: 'medium', question: 'Statements:\nNo claims are rejected.\nAll rejected are invalid.\n\nConclusions:\nI. No claims are invalid.\nII. Some invalid are not claims.', options: ['Only I follows', 'Both I and II follow', 'Only II follows', 'Neither I nor II follows'], correctIndex: 2, marks: 3, negativeMarking: 0, explanation: 'Since all rejected items are invalid and no claims are rejected, the rejected items (a subset of invalid) are definitely not claims, so some invalid items are not claims (II) follows. But other invalid items outside that subset could still be claims, so "no claims are invalid" (I) does not necessarily follow.', source },
  { id: 'lic-aao-m1-re-012', section: 'Reasoning Ability', topic: 'Blood relations', difficulty: 'medium', question: "Pointing to a man, a woman said, 'His mother is the only sister of my mother.' How is the man related to the woman?", options: ['Brother', 'Cousin', 'Uncle', 'Nephew'], correctIndex: 1, marks: 3, negativeMarking: 0, explanation: "'The only sister of my mother' is the woman's maternal aunt. The man's mother being this aunt makes the man the woman's cousin.", source },
  { id: 'lic-aao-m1-re-013', section: 'Reasoning Ability', topic: 'Blood relations', difficulty: 'medium', question: "A is the son of B. C is the mother of B. D is the daughter of C, other than B. How is D related to A?", options: ['Sister', 'Mother', 'Grandmother', 'Aunt'], correctIndex: 3, marks: 3, negativeMarking: 0, explanation: "C is B's mother, and D is another daughter of C, making D a sibling of B. Since A is B's son, D (B's sister) is A's aunt.", source },
  { id: 'lic-aao-m1-re-014', section: 'Reasoning Ability', topic: 'Direction sense', difficulty: 'medium', question: 'Ramesh walks 6 m north, then turns right and walks 8 m. How far is he from his starting point?', options: ['14 m', '2 m', '10 m', '8 m'], correctIndex: 2, marks: 3, negativeMarking: 0, explanation: 'North 6 m and east 8 m form a right angle. By the Pythagorean theorem, the distance = √(6² + 8²) = √100 = 10 m.', source },
  { id: 'lic-aao-m1-re-015', section: 'Reasoning Ability', topic: 'Direction sense', difficulty: 'medium', question: 'Facing south, Leela turns 45° clockwise, then 90° clockwise. Which direction is she facing now?', options: ['South-East', 'North-West', 'North-East', 'South-West'], correctIndex: 1, marks: 3, negativeMarking: 0, explanation: 'Starting at South (180°), turning 45° clockwise gives 225° (South-West). Turning another 90° clockwise gives 315°, which is North-West.', source },
  { id: 'lic-aao-m1-re-016', section: 'Reasoning Ability', topic: 'Coding-decoding', difficulty: 'medium', question: "If 'CLAIM' is coded as 'GPEMQ' in a certain language (each letter shifted four places forward in the alphabet), how is 'BONUS' coded in the same language?", options: ['FSRYV', 'ESRYW', 'FSQYW', 'FSRYW'], correctIndex: 3, marks: 3, negativeMarking: 0, explanation: 'Shifting each letter four places forward: B→F, O→S, N→R, U→Y, S→W, giving FSRYW.', source },
  { id: 'lic-aao-m1-re-017', section: 'Reasoning Ability', topic: 'Coding-decoding', difficulty: 'easy', question: "In a certain code, each word is simply spelled backward. How is 'POLICY' coded?", options: ['YCILPO', 'YCLIOP', 'YCILOP', 'CYILOP'], correctIndex: 2, marks: 3, negativeMarking: 0, explanation: "Reversing the letters of 'POLICY' (P-O-L-I-C-Y) gives Y-C-I-L-O-P, or 'YCILOP'.", source },
  { id: 'lic-aao-m1-re-018', section: 'Reasoning Ability', topic: 'Coding-decoding', difficulty: 'medium', question: "In a certain code, each letter is represented by a number equal to three times its position in the alphabet. What is the code for 'AGE'?", options: ['3 21 12', '3 21 15', '3 18 15', '1 21 15'], correctIndex: 1, marks: 3, negativeMarking: 0, explanation: 'A is the 1st letter (1×3=3), G is the 7th letter (7×3=21), E is the 5th letter (5×3=15). Code: 3 21 15.', source },
  { id: 'lic-aao-m1-re-019', section: 'Reasoning Ability', topic: 'Inequality', difficulty: 'medium', question: `${INEQUALITY_LEGEND}Statements: A@B, B@C, C@D\nConclusions: I. A@D  II. D#B`, options: ['Only I follows', 'Only II follows', 'Neither I nor II follows', 'Both I and II follow'], correctIndex: 3, marks: 3, negativeMarking: 0, explanation: 'A>B>C>D forms a full chain, so A>D (I) holds transitively. Also, D<C<B, so D<B (II) also holds.', source },
  { id: 'lic-aao-m1-re-020', section: 'Reasoning Ability', topic: 'Inequality', difficulty: 'medium', question: `${INEQUALITY_LEGEND}Statements: K#L, L$M, N#M\nConclusions: I. K#M  II. N#L`, options: ['Only II follows', 'Both I and II follow', 'Only I follows', 'Neither I nor II follows'], correctIndex: 2, marks: 3, negativeMarking: 0, explanation: 'K<L and L≤M together give K<M (I), since K is strictly less than L which is at most M. N<M and L≤M do not fix N\'s relation to L, so II does not necessarily follow.', source },
  { id: 'lic-aao-m1-re-021', section: 'Reasoning Ability', topic: 'Inequality', difficulty: 'medium', question: `${INEQUALITY_LEGEND}Statements: X%Y, Y&Z, Z#W\nConclusions: I. X#W  II. Y#W`, options: ['Only I follows', 'Only II follows', 'Both I and II follow', 'Neither I nor II follows'], correctIndex: 1, marks: 3, negativeMarking: 0, explanation: 'Y=Z and Z<W together give Y<W (II). X≥Y and Y<W do not fix X\'s relation to W, so I does not necessarily follow.', source },
  { id: 'lic-aao-m1-re-022', section: 'Reasoning Ability', topic: 'Alphanumeric series', difficulty: 'easy', question: 'Find the missing term in the series: E, J, O, T, ?', options: ['X', 'Z', 'W', 'Y'], correctIndex: 3, marks: 3, negativeMarking: 0, explanation: 'Each letter is 5 places after the previous one: E(+5)J(+5)O(+5)T(+5)Y. So the answer is Y.', source },
  { id: 'lic-aao-m1-re-023', section: 'Reasoning Ability', topic: 'Alphanumeric series', difficulty: 'medium', question: 'Find the missing term in the series: 12, 17, 27, 42, 62, ?', options: ['85', '89', '87', '83'], correctIndex: 2, marks: 3, negativeMarking: 0, explanation: 'The differences increase by 5 each time: 5, 10, 15, 20, and next 25. So 62 + 25 = 87.', source },
  { id: 'lic-aao-m1-re-024', section: 'Reasoning Ability', topic: 'Alphanumeric series', difficulty: 'medium', question: "If the letters of the word 'CLAIMANT' are arranged in alphabetical order, which letter is 4th from the left?", options: ['L', 'I', 'A', 'M'], correctIndex: 1, marks: 3, negativeMarking: 0, explanation: 'The letters of CLAIMANT sorted alphabetically are A, A, C, I, L, M, N, T. The 4th letter from the left is I.', source },
  { id: 'lic-aao-m1-re-025', section: 'Reasoning Ability', topic: 'Data sufficiency', difficulty: 'hard', question: 'What is the sum insured under a certain policy?\nStatement I: The annual premium is ₹12,000.\nStatement II: The premium rate is 2% of the sum insured.', options: ['Statement I alone is sufficient, but Statement II alone is not sufficient', 'Statement II alone is sufficient, but Statement I alone is not sufficient', 'Either statement I or II alone is sufficient', 'Both statements I and II together are sufficient, but neither alone is sufficient'], correctIndex: 3, marks: 3, negativeMarking: 0, explanation: 'Statement I alone gives only the premium amount. Statement II alone gives only the rate. Together: sum insured = 12000 / 0.02 = ₹6,00,000.', source },
  { id: 'lic-aao-m1-re-026', section: 'Reasoning Ability', topic: 'Data sufficiency', difficulty: 'hard', question: 'Is a policyholder eligible for a maturity bonus?\nStatement I: The policy term is 20 years.\nStatement II: A maturity bonus is payable only on policies with a term of 15 years or more.', options: ['Statement I alone is sufficient, but Statement II alone is not sufficient', 'Statement II alone is sufficient, but Statement I alone is not sufficient', 'Both statements I and II together are sufficient, but neither alone is sufficient', 'Either statement I or II alone is sufficient'], correctIndex: 2, marks: 3, negativeMarking: 0, explanation: 'Statement I alone gives the term but not the eligibility rule. Statement II alone gives the rule but not this policyholder\'s specific term. Together: a 20-year term meets the 15-year-or-more rule, so the policyholder is eligible.', source },
  { id: 'lic-aao-m1-re-027', section: 'Reasoning Ability', topic: 'Ranking', difficulty: 'medium', question: 'In a group of 40 applicants, Priya ranks 14th from the top in the merit list. What is her rank from the bottom?', options: ['26', '27', '28', '25'], correctIndex: 1, marks: 3, negativeMarking: 0, explanation: 'Rank from bottom = total applicants − rank from top + 1 = 40 − 14 + 1 = 27.', source },
  { id: 'lic-aao-m1-re-028', section: 'Reasoning Ability', topic: 'Ranking', difficulty: 'medium', question: 'Among five candidates, A scored higher than B but lower than C. D scored lower than B but higher than E. Who scored the lowest?', options: ['D', 'B', 'A', 'E'], correctIndex: 3, marks: 3, negativeMarking: 0, explanation: 'Combining the clues: C > A > B > D > E. So E scored the lowest.', source },
  { id: 'lic-aao-m1-re-029', section: 'Reasoning Ability', topic: 'Alphabet test', difficulty: 'medium', question: `${WORD_LIST}Which word comes first in the dictionary arrangement?`, options: ['Instant', 'Insurance', 'Install', 'Insure'], correctIndex: 2, marks: 3, negativeMarking: 0, explanation: "Comparing letter by letter, 'Install' and 'Instant' (both 'Inst-') come before the 'Insur-' words (t comes before u at the 4th letter). Between the two, 'Install' precedes 'Instant' since their 6th letter (l vs n) puts l first.", source },
  { id: 'lic-aao-m1-re-030', section: 'Reasoning Ability', topic: 'Alphabet test', difficulty: 'medium', question: `${WORD_LIST}Which word comes exactly between 'Instant' and 'Insure' in the dictionary arrangement?`, options: ['Install', 'Insurance', 'Insurer', 'Instant'], correctIndex: 1, marks: 3, negativeMarking: 0, explanation: "The dictionary order is Install, Instant, Insurance, Insure, Insurer. The word between Instant and Insure is Insurance.", source },
];
