import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'LIC AAO (Generalist) 2025-26 Recruitment Notification, Mains syllabus — Reasoning Ability section',
  url: 'https://www.licindia.in/recruitment-of-aao-generalists/-specialists/-assistant-engineers-2025',
  checkedOn: '29 August 2026',
};

const SEATING_PUZZLE =
  'Six insurance agents — J, K, L, M, N, and O — sit in a row facing North. K sits third from the left end. Exactly two people sit between K and O. M sits immediately to the left of O. L sits at one of the extreme ends. J sits immediately to the right of L.\n\n';

const FLOOR_PUZZLE =
  'Five employees — P, Q, R, S, and T — live on different floors of a five-floor building (floor 1 is the lowest, floor 5 is the topmost). Q lives on floor 4. R lives immediately above T. S lives on the topmost floor. P does not live on floor 1.\n\n';

const INEQUALITY_LEGEND =
  "In the following questions, the symbols are used as follows: 'φ' means 'greater than', 'δ' means 'less than', 'σ' means 'greater than or equal to', 'τ' means 'less than or equal to', and 'ε' means 'equal to'. Read the statements and decide which of the conclusions logically follow(s) from the statements, disregarding commonly known facts.\n\n";

const WORD_LIST_2 =
  'Consider the following words: 1. Nominal 2. Nominee 3. Norm 4. Notice 5. Novation. If these words are arranged as they would appear in an English dictionary, answer the question that follows.\n\n';

export const LIC_AAO_MAINS_REASONING_ABILITY_2: Question[] = [
  { id: 'lic-aao-m2-re-001', section: 'Reasoning Ability', topic: 'Puzzle', difficulty: 'hard', question: `${SEATING_PUZZLE}Who sits at the extreme right end?`, options: ['O', 'M', 'K', 'N'], correctIndex: 0, marks: 3, negativeMarking: 0, explanation: 'L=1, J=2, K=3, N=4, M=5, O=6 (from the extreme end, K third from left, O three places from K, M immediately left of O, L at the free extreme end, J immediately right of L). O sits at the extreme right end.', source },
  { id: 'lic-aao-m2-re-002', section: 'Reasoning Ability', topic: 'Puzzle', difficulty: 'hard', question: `${SEATING_PUZZLE}How many people sit between L and M?`, options: ['1', '3', '2', '4'], correctIndex: 1, marks: 3, negativeMarking: 0, explanation: 'The full arrangement is L, J, K, N, M, O (positions 1-6). L is at position 1 and M is at position 5, so J, K, and N (3 people) sit between them.', source },
  { id: 'lic-aao-m2-re-003', section: 'Reasoning Ability', topic: 'Puzzle', difficulty: 'hard', question: `${SEATING_PUZZLE}Who sits second from the right end?`, options: ['O', 'K', 'M', 'N'], correctIndex: 2, marks: 3, negativeMarking: 0, explanation: 'The arrangement is L, J, K, N, M, O. Second from the right end is position 5, which is M.', source },
  { id: 'lic-aao-m2-re-004', section: 'Reasoning Ability', topic: 'Puzzle', difficulty: 'hard', question: `${SEATING_PUZZLE}Who sits immediately between K and M?`, options: ['J', 'O', 'L', 'N'], correctIndex: 3, marks: 3, negativeMarking: 0, explanation: 'The arrangement is L, J, K, N, M, O. The seat between K (position 3) and M (position 5) is position 4, occupied by N.', source },
  { id: 'lic-aao-m2-re-005', section: 'Reasoning Ability', topic: 'Puzzle', difficulty: 'hard', question: `${FLOOR_PUZZLE}Who lives on the topmost floor?`, options: ['S', 'Q', 'R', 'P'], correctIndex: 0, marks: 3, negativeMarking: 0, explanation: 'S is directly stated to live on the topmost floor (floor 5).', source },
  { id: 'lic-aao-m2-re-006', section: 'Reasoning Ability', topic: 'Puzzle', difficulty: 'hard', question: `${FLOOR_PUZZLE}On which floor does P live?`, options: ['4', '3', '2', '1'], correctIndex: 1, marks: 3, negativeMarking: 0, explanation: 'S=5, Q=4. Among floors 1-3 for P, R, T with R immediately above T: the only option consistent with P not on floor 1 is T=1, R=2, P=3.', source },
  { id: 'lic-aao-m2-re-007', section: 'Reasoning Ability', topic: 'Puzzle', difficulty: 'hard', question: `${FLOOR_PUZZLE}Who lives immediately below Q?`, options: ['T', 'S', 'P', 'R'], correctIndex: 2, marks: 3, negativeMarking: 0, explanation: 'The full arrangement (floor 1 to 5) is T, R, P, Q, S. Immediately below Q (floor 4) is P on floor 3.', source },
  { id: 'lic-aao-m2-re-008', section: 'Reasoning Ability', topic: 'Puzzle', difficulty: 'hard', question: `${FLOOR_PUZZLE}How many people live below R?`, options: ['2', '0', '3', '1'], correctIndex: 3, marks: 3, negativeMarking: 0, explanation: 'The arrangement is T (floor 1), R (floor 2), P (floor 3), Q (floor 4), S (floor 5). Only T lives below R — 1 person.', source },
  { id: 'lic-aao-m2-re-009', section: 'Reasoning Ability', topic: 'Syllogism', difficulty: 'medium', question: 'Statements:\nAll nominees are beneficiaries.\nNo beneficiary is a minor.\n\nConclusions:\nI. No nominee is a minor.\nII. Some beneficiaries are nominees.', options: ['Both I and II follow', 'Only I follows', 'Only II follows', 'Neither I nor II follows'], correctIndex: 0, marks: 3, negativeMarking: 0, explanation: 'Since all nominees are beneficiaries and no beneficiary is a minor, no nominee can be a minor (I follows). Also, converting "All nominees are beneficiaries" gives "Some beneficiaries are nominees" (II follows).', source },
  { id: 'lic-aao-m2-re-010', section: 'Reasoning Ability', topic: 'Syllogism', difficulty: 'medium', question: 'Statements:\nSome surveyors are engineers.\nSome engineers are assessors.\n\nConclusions:\nI. Some surveyors are assessors.\nII. Some assessors are surveyors.', options: ['Both I and II follow', 'Neither I nor II follows', 'Only I follows', 'Only II follows'], correctIndex: 1, marks: 3, negativeMarking: 0, explanation: 'Two particular ("some") statements about the same middle term (engineers) do not establish any definite relationship between surveyors and assessors — the surveyors who are engineers need not be the same engineers who are assessors. Neither conclusion follows.', source },
  { id: 'lic-aao-m2-re-011', section: 'Reasoning Ability', topic: 'Syllogism', difficulty: 'medium', question: 'Statements:\nAll beneficiaries are policyholders.\nAll policyholders are customers.\n\nConclusions:\nI. All beneficiaries are customers.\nII. No beneficiary is a customer.', options: ['Both I and II follow', 'Neither I nor II follows', 'Only I follows', 'Only II follows'], correctIndex: 2, marks: 3, negativeMarking: 0, explanation: 'Since all beneficiaries are policyholders and all policyholders are customers, all beneficiaries are customers by transitivity (I follows). Conclusion II directly contradicts I, so it cannot also follow.', source },
  { id: 'lic-aao-m2-re-012', section: 'Reasoning Ability', topic: 'Blood relations', difficulty: 'medium', question: 'P is the son of R. S is the husband of R. Q is the sister of P. How is Q related to S?', options: ['Sister', 'Niece', 'Mother', 'Daughter'], correctIndex: 3, marks: 3, negativeMarking: 0, explanation: "R is P's mother and S is R's husband, making S P's father. Since Q is P's sister, Q is also the daughter of R and S. Q is S's daughter.", source },
  { id: 'lic-aao-m2-re-013', section: 'Reasoning Ability', topic: 'Blood relations', difficulty: 'medium', question: "A introduces B as the son of his father's only daughter. How is B related to A?", options: ['Nephew', 'Cousin', 'Son', 'Brother'], correctIndex: 0, marks: 3, negativeMarking: 0, explanation: "A's father's only daughter is A's sister (since A is male, referred to as 'his'). B, her son, is therefore A's nephew.", source },
  { id: 'lic-aao-m2-re-014', section: 'Reasoning Ability', topic: 'Direction sense', difficulty: 'medium', question: 'Suresh walks 9 km east, then turns left and walks 12 km. How far is he from his starting point?', options: ['12 km', '15 km', '21 km', '3 km'], correctIndex: 1, marks: 3, negativeMarking: 0, explanation: 'East 9 km and north 12 km (left turn while facing east) form a right angle. By the Pythagorean theorem, distance = √(9² + 12²) = √225 = 15 km.', source },
  { id: 'lic-aao-m2-re-015', section: 'Reasoning Ability', topic: 'Direction sense', difficulty: 'medium', question: 'Facing north, Meera turns 90° clockwise, then 180° clockwise. Which direction is she facing now?', options: ['South', 'North', 'West', 'East'], correctIndex: 2, marks: 3, negativeMarking: 0, explanation: 'Starting at North (0°), turning 90° clockwise gives East (90°). Turning another 180° clockwise gives 270°, which is West.', source },
  { id: 'lic-aao-m2-re-016', section: 'Reasoning Ability', topic: 'Coding-decoding', difficulty: 'medium', question: "If 'MARKET' is coded as 'JXOHBQ' in a certain language (each letter shifted three places backward in the alphabet), how is 'BUDGET' coded in the same language?", options: ['YRADBR', 'XRADBQ', 'YSADBQ', 'YRADBQ'], correctIndex: 3, marks: 3, negativeMarking: 0, explanation: 'Shifting each letter three places backward: B→Y, U→R, D→A, G→D, E→B, T→Q, giving YRADBQ.', source },
  { id: 'lic-aao-m2-re-017', section: 'Reasoning Ability', topic: 'Coding-decoding', difficulty: 'medium', question: "In a certain code, vowels are replaced by the next vowel in the sequence A→E→I→O→U→A (consonants remain unchanged). If 'INSURANCE' is coded as 'ONSARENCI', how is 'POLICY' coded in the same language?", options: ['PULOCY', 'PALICY', 'PULICY', 'PULOCU'], correctIndex: 0, marks: 3, negativeMarking: 0, explanation: 'Replacing vowels with the next vowel in the sequence: O→U, I→O (consonants P, L, C, Y unchanged). POLICY becomes PULOCY.', source },
  { id: 'lic-aao-m2-re-018', section: 'Reasoning Ability', topic: 'Coding-decoding', difficulty: 'medium', question: "In a certain code, each letter is represented by a number equal to (27 minus its position in the alphabet). What is the code for 'CAT'?", options: ['24 26 8', '24 26 7', '23 26 7', '24 25 7'], correctIndex: 1, marks: 3, negativeMarking: 0, explanation: 'C is the 3rd letter (27−3=24), A is the 1st letter (27−1=26), T is the 20th letter (27−20=7). Code: 24 26 7.', source },
  { id: 'lic-aao-m2-re-019', section: 'Reasoning Ability', topic: 'Inequality', difficulty: 'medium', question: `${INEQUALITY_LEGEND}Statements: A φ B, B φ C, C ε D\nConclusions: I. A φ D  II. D δ B`, options: ['Only II follows', 'Neither I nor II follows', 'Both I and II follow', 'Only I follows'], correctIndex: 2, marks: 3, negativeMarking: 0, explanation: 'A>B>C=D forms a chain, so A>D (I) holds transitively. Also, D=C<B, so D<B (II) also holds.', source },
  { id: 'lic-aao-m2-re-020', section: 'Reasoning Ability', topic: 'Inequality', difficulty: 'medium', question: `${INEQUALITY_LEGEND}Statements: K δ L, L τ M, N δ M\nConclusions: I. K δ M  II. N δ L`, options: ['Only II follows', 'Both I and II follow', 'Neither I nor II follows', 'Only I follows'], correctIndex: 3, marks: 3, negativeMarking: 0, explanation: 'K<L and L≤M together give K<M (I), since K is strictly less than something at most M. N<M and L≤M do not fix N\'s relation to L, so II does not necessarily follow.', source },
  { id: 'lic-aao-m2-re-021', section: 'Reasoning Ability', topic: 'Inequality', difficulty: 'medium', question: `${INEQUALITY_LEGEND}Statements: X σ Y, Y ε Z, Z δ W\nConclusions: I. X δ W  II. Y δ W`, options: ['Only II follows', 'Only I follows', 'Both I and II follow', 'Neither I nor II follows'], correctIndex: 0, marks: 3, negativeMarking: 0, explanation: 'Y=Z and Z<W together give Y<W (II). X≥Y and Y<W do not fix X\'s relation to W, so I does not necessarily follow.', source },
  { id: 'lic-aao-m2-re-022', section: 'Reasoning Ability', topic: 'Alphanumeric series', difficulty: 'easy', question: 'Find the missing term in the series: B, F, J, N, ?', options: ['T', 'R', 'S', 'Q'], correctIndex: 1, marks: 3, negativeMarking: 0, explanation: 'Each letter is 4 places after the previous one: B(+4)F(+4)J(+4)N(+4)R. So the answer is R.', source },
  { id: 'lic-aao-m2-re-023', section: 'Reasoning Ability', topic: 'Alphanumeric series', difficulty: 'medium', question: 'Find the missing term in the series: 5, 8, 14, 23, 35, ?', options: ['52', '47', '50', '48'], correctIndex: 2, marks: 3, negativeMarking: 0, explanation: 'The differences increase by 3 each time: 3, 6, 9, 12, and next 15. So 35 + 15 = 50.', source },
  { id: 'lic-aao-m2-re-024', section: 'Reasoning Ability', topic: 'Alphanumeric series', difficulty: 'medium', question: "If the letters of the word 'INSURANCE' are arranged in alphabetical order, which letter is 5th from the right?", options: ['R', 'S', 'I', 'N'], correctIndex: 3, marks: 3, negativeMarking: 0, explanation: 'The letters of INSURANCE sorted alphabetically are A, C, E, I, N, N, R, S, U. Counting from the right: U(1st), S(2nd), R(3rd), N(4th), N(5th). The 5th letter from the right is N.', source },
  { id: 'lic-aao-m2-re-025', section: 'Reasoning Ability', topic: 'Data sufficiency', difficulty: 'hard', question: 'What is the annual premium payable on a policy?\nStatement I: The sum assured is ₹5,00,000.\nStatement II: The premium rate is 2.4% of the sum assured.', options: ['Both statements I and II together are sufficient, but neither alone is sufficient', 'Statement I alone is sufficient, but Statement II alone is not sufficient', 'Statement II alone is sufficient, but Statement I alone is not sufficient', 'Either statement I or II alone is sufficient'], correctIndex: 0, marks: 3, negativeMarking: 0, explanation: 'Statement I alone gives only the sum assured. Statement II alone gives only the rate. Together: premium = 5,00,000 × 2.4% = ₹12,000.', source },
  { id: 'lic-aao-m2-re-026', section: 'Reasoning Ability', topic: 'Data sufficiency', difficulty: 'hard', question: "In a class of 50 students, what is Ravi's rank from the top?\nStatement I: Ravi is 12th from the top.\nStatement II: Ravi is 39th from the bottom.", options: ['Both statements I and II together are sufficient, but neither alone is sufficient', 'Either statement I or II alone is sufficient', 'Statement I alone is sufficient, but Statement II alone is not sufficient', 'Statement II alone is sufficient, but Statement I alone is not sufficient'], correctIndex: 1, marks: 3, negativeMarking: 0, explanation: 'Statement I alone directly gives the rank from the top (12th). Statement II alone also gives it: rank from top = 50 − 39 + 1 = 12. Either statement alone is sufficient.', source },
  { id: 'lic-aao-m2-re-027', section: 'Reasoning Ability', topic: 'Ranking', difficulty: 'medium', question: 'In a merit list of 60 candidates, Anil ranks 23rd from the bottom. What is his rank from the top?', options: ['39', '36', '38', '37'], correctIndex: 2, marks: 3, negativeMarking: 0, explanation: 'Rank from top = total candidates − rank from bottom + 1 = 60 − 23 + 1 = 38.', source },
  { id: 'lic-aao-m2-re-028', section: 'Reasoning Ability', topic: 'Ranking', difficulty: 'medium', question: 'Among six friends, D scored more than E but less than F. G scored more than F. H scored less than E but more than I. Who scored the highest?', options: ['F', 'D', 'H', 'G'], correctIndex: 3, marks: 3, negativeMarking: 0, explanation: 'Combining the clues: G > F > D > E > H > I. So G scored the highest.', source },
  { id: 'lic-aao-m2-re-029', section: 'Reasoning Ability', topic: 'Alphabet test', difficulty: 'medium', question: `${WORD_LIST_2}Which word comes last in the dictionary arrangement?`, options: ['Novation', 'Notice', 'Norm', 'Nominee'], correctIndex: 0, marks: 3, negativeMarking: 0, explanation: 'The dictionary order is Nominal, Nominee, Norm, Notice, Novation (comparing the 3rd letter: M before R before T before V). Novation comes last.', source },
  { id: 'lic-aao-m2-re-030', section: 'Reasoning Ability', topic: 'Alphabet test', difficulty: 'medium', question: `${WORD_LIST_2}Which word comes exactly between 'Norm' and 'Novation' in the dictionary arrangement?`, options: ['Norm', 'Notice', 'Nominal', 'Nominee'], correctIndex: 1, marks: 3, negativeMarking: 0, explanation: 'The dictionary order is Nominal, Nominee, Norm, Notice, Novation. The word between Norm and Novation is Notice.', source },
];
