import type { Question } from '../questions';

// LIC AAO (Generalist) Prelims: Quantitative Aptitude, 35 questions.
// Counts toward the Prelims merit ranking (along with Reasoning Ability).
const source = {
  kind: 'original' as const,
  reference: 'LIC AAO (Generalist) 2025-26 Recruitment Notification',
  url: 'https://www.licindia.in/recruitment-of-aao-generalists/-specialists/-assistant-engineers-2025',
  checkedOn: '6 August 2026',
};

export const LIC_AAO_PRELIMS_QUANTITATIVE_APTITUDE_1: Question[] = [
  { id: 'lic-p-qa-001', section: 'Quantitative Aptitude', topic: 'Simplification', difficulty: 'easy', question: 'What is 15% of 480 plus 25% of 240?', options: ['122', '132', '142', '152'], correctIndex: 1, explanation: '15% of 480 = 72, and 25% of 240 = 60. Their sum is 72 + 60 = 132.', source },
  { id: 'lic-p-qa-002', section: 'Quantitative Aptitude', topic: 'Simplification', difficulty: 'easy', question: 'What is the value of (12 × 15) − (8 × 9)?', options: ['98', '108', '118', '128'], correctIndex: 1, explanation: '12 × 15 = 180, and 8 × 9 = 72. So 180 − 72 = 108.', source },
  { id: 'lic-p-qa-003', section: 'Quantitative Aptitude', topic: 'Simplification', difficulty: 'medium', question: 'What is the value of √225 + √144?', options: ['27', '25', '26', '28'], correctIndex: 0, explanation: '√225 = 15 and √144 = 12, so their sum is 15 + 12 = 27.', source },
  { id: 'lic-p-qa-004', section: 'Quantitative Aptitude', topic: 'Simplification', difficulty: 'medium', question: 'What is the value of three-fourths of 640 minus two-fifths of 250?', options: ['380', '360', '370', '390'], correctIndex: 0, explanation: 'Three-fourths of 640 is 480, and two-fifths of 250 is 100. So 480 − 100 = 380.', source },
  { id: 'lic-p-qa-005', section: 'Quantitative Aptitude', topic: 'Simplification', difficulty: 'medium', question: 'What is the value of (0.6 × 0.6) − (0.4 × 0.4)?', options: ['0.20', '0.10', '0.15', '0.25'], correctIndex: 0, explanation: '0.6 × 0.6 = 0.36 and 0.4 × 0.4 = 0.16, so the difference is 0.36 − 0.16 = 0.20.', source },
  { id: 'lic-p-qa-006', section: 'Quantitative Aptitude', topic: 'Percentage', difficulty: 'easy', question: '640 is what percent of 800?', options: ['80%', '70%', '75%', '85%'], correctIndex: 0, explanation: '(640 / 800) × 100 = 80%.', source },
  { id: 'lic-p-qa-007', section: 'Quantitative Aptitude', topic: 'Percentage', difficulty: 'medium', question: 'A number, when increased by 20%, becomes 300. Find the original number.', options: ['250', '230', '240', '260'], correctIndex: 0, explanation: 'Let the number be x. x × 1.2 = 300, so x = 300 / 1.2 = 250.', source },
  { id: 'lic-p-qa-008', section: 'Quantitative Aptitude', topic: 'Percentage', difficulty: 'medium', question: 'A candidate scored 385 marks out of 550 in an exam. What percentage did the candidate score?', options: ['70%', '65%', '68%', '72%'], correctIndex: 0, explanation: '(385 / 550) × 100 = 70%.', source },
  { id: 'lic-p-qa-009', section: 'Quantitative Aptitude', topic: 'Percentage', difficulty: 'hard', question: "If the price of an item is reduced by 25%, by approximately what percent must the new price be increased to restore the original price?", options: ['20%', '25%', '30%', '33.33%'], correctIndex: 3, explanation: 'After a 25% reduction, the price becomes 75% of the original. To restore it, the increase needed is 25/75 × 100 ≈ 33.33%.', source },
  { id: 'lic-p-qa-010', section: 'Quantitative Aptitude', topic: 'Percentage', difficulty: 'hard', question: '40% of a number is 20 more than 20% of the same number. Find the number.', options: ['100', '80', '90', '110'], correctIndex: 0, explanation: 'Let the number be x. 0.4x − 0.2x = 20, so 0.2x = 20, giving x = 100.', source },
  { id: 'lic-p-qa-011', section: 'Quantitative Aptitude', topic: 'Profit and Loss', difficulty: 'easy', question: 'An article with a cost price of ₹800 is sold for ₹920. Find the profit percentage.', options: ['15%', '10%', '12%', '18%'], correctIndex: 0, explanation: 'Profit = 920 − 800 = 120. Profit percentage = (120 / 800) × 100 = 15%.', source },
  { id: 'lic-p-qa-012', section: 'Quantitative Aptitude', topic: 'Profit and Loss', difficulty: 'medium', question: 'An article is sold at a loss of 18% for ₹902. Find its cost price.', options: ['₹1100', '₹1050', '₹1080', '₹1120'], correctIndex: 0, explanation: 'Selling price = 0.82 × Cost price. So Cost price = 902 / 0.82 = ₹1100.', source },
  { id: 'lic-p-qa-013', section: 'Quantitative Aptitude', topic: 'Profit and Loss', difficulty: 'hard', question: 'A shopkeeper marks an item 40% above its cost price and then offers a discount of 10% on the marked price. Find the resulting profit percentage.', options: ['22%', '26%', '24%', '28%'], correctIndex: 1, explanation: 'Marked price = 1.4 × Cost price. Selling price = 0.9 × 1.4 × Cost price = 1.26 × Cost price, giving a profit of 26%.', source },
  { id: 'lic-p-qa-014', section: 'Quantitative Aptitude', topic: 'Ratio and Proportion', difficulty: 'easy', question: '₹720 is divided between two people in the ratio 3:5. Find the smaller share.', options: ['₹250', '₹270', '₹260', '₹280'], correctIndex: 1, explanation: 'Total parts = 3 + 5 = 8. The smaller share = (3/8) × 720 = ₹270.', source },
  { id: 'lic-p-qa-015', section: 'Quantitative Aptitude', topic: 'Ratio and Proportion', difficulty: 'medium', question: 'If a:b = 3:4 and b:c = 5:6, find a:b:c.', options: ['12:16:20', '15:20:24', '15:18:24', '12:20:24'], correctIndex: 1, explanation: 'To combine, scale a:b = 3:4 to 15:20 (multiplying by 5) and b:c = 5:6 to 20:24 (multiplying by 4), so both share b = 20, giving a:b:c = 15:20:24.', source },
  { id: 'lic-p-qa-016', section: 'Quantitative Aptitude', topic: 'Ratio and Proportion', difficulty: 'hard', question: 'If x:y = 5:7, find the value of (3x + 2y):(4x − y).', options: ['27:11', '29:13', '31:15', '25:9'], correctIndex: 1, explanation: 'Let x = 5k and y = 7k. Then 3x + 2y = 15k + 14k = 29k, and 4x − y = 20k − 7k = 13k, giving a ratio of 29:13.', source },
  { id: 'lic-p-qa-017', section: 'Quantitative Aptitude', topic: 'Ratio and Proportion', difficulty: 'medium', question: '₹24,000 is divided among A, B, and C in the ratio 2:3:5. Find C\'s share.', options: ['₹10,000', '₹11,000', '₹12,000', '₹13,000'], correctIndex: 2, explanation: 'Total parts = 2 + 3 + 5 = 10. C\'s share = (5/10) × 24,000 = ₹12,000.', source },
  { id: 'lic-p-qa-018', section: 'Quantitative Aptitude', topic: 'Average', difficulty: 'easy', question: 'The average of 5 numbers is 42. If one of the numbers, 30, is replaced by 60, find the new average.', options: ['44', '46', '50', '48'], correctIndex: 3, explanation: 'The original sum is 42 × 5 = 210. Replacing 30 with 60 changes the sum to 210 − 30 + 60 = 240. The new average is 240 / 5 = 48.', source },
  { id: 'lic-p-qa-019', section: 'Quantitative Aptitude', topic: 'Average', difficulty: 'medium', question: 'The average age of 6 people is 24 years. A 7th person joins the group, and the new average becomes 25 years. Find the age of the 7th person.', options: ['29', '30', '32', '31'], correctIndex: 3, explanation: 'The original total age is 24 × 6 = 144. The new total age is 25 × 7 = 175. The 7th person\'s age is 175 − 144 = 31 years.', source },
  { id: 'lic-p-qa-020', section: 'Quantitative Aptitude', topic: 'Average', difficulty: 'medium', question: 'The average of three consecutive even numbers is 34. Find the largest of the three numbers.', options: ['32', '34', '38', '36'], correctIndex: 3, explanation: 'The three consecutive even numbers are 32, 34, and 36, whose average is (32+34+36)/3 = 34, so the largest is 36.', source },
  { id: 'lic-p-qa-021', section: 'Quantitative Aptitude', topic: 'Simple and Compound Interest', difficulty: 'easy', question: 'Find the simple interest on ₹5,000 at 8% per annum for 3 years.', options: ['₹1,000', '₹1,100', '₹1,300', '₹1,200'], correctIndex: 3, explanation: 'Simple interest = (Principal × Rate × Time) / 100 = (5000 × 8 × 3) / 100 = ₹1,200.', source },
  { id: 'lic-p-qa-022', section: 'Quantitative Aptitude', topic: 'Simple and Compound Interest', difficulty: 'medium', question: 'Find the compound interest on ₹7,000 at 10% per annum for 2 years, compounded annually.', options: ['₹1,400', '₹1,435', '₹1,505', '₹1,470'], correctIndex: 3, explanation: 'Amount = 7000 × 1.1 × 1.1 = ₹8,470. Compound interest = 8470 − 7000 = ₹1,470.', source },
  { id: 'lic-p-qa-023', section: 'Quantitative Aptitude', topic: 'Simple and Compound Interest', difficulty: 'hard', question: 'A sum of money triples itself in 8 years at simple interest. Find the annual rate of interest.', options: ['20%', '22.5%', '27.5%', '25%'], correctIndex: 3, explanation: 'If the sum triples, the interest earned equals twice the principal (2P) over 8 years. Rate = (2P × 100) / (P × 8) = 25%.', source },
  { id: 'lic-p-qa-024', section: 'Quantitative Aptitude', topic: 'Simple and Compound Interest', difficulty: 'hard', question: 'Find the difference between the simple interest and compound interest on ₹10,000 at 10% per annum for 2 years.', options: ['₹80', '₹90', '₹100', '₹110'], correctIndex: 2, explanation: 'Simple interest = (10000 × 10 × 2)/100 = ₹2,000. Compound interest: Amount = 10000 × 1.1 × 1.1 = ₹12,100, so CI = ₹2,100. The difference is ₹100.', source },
  { id: 'lic-p-qa-025', section: 'Quantitative Aptitude', topic: 'Time and Work', difficulty: 'easy', question: 'A can complete a job in 12 days and B can complete the same job in 18 days. Working together, how many days will they take?', options: ['6.8 days', '7 days', '7.2 days', '7.5 days'], correctIndex: 2, explanation: "Combined work rate = 1/12 + 1/18 = 3/36 + 2/36 = 5/36 of the job per day. Time taken = 36/5 = 7.2 days.", source },
  { id: 'lic-p-qa-026', section: 'Quantitative Aptitude', topic: 'Time and Work', difficulty: 'medium', question: 'A can complete a piece of work alone in 10 days. He works alone for 4 days and then leaves. What fraction of the work is left unfinished?', options: ['2/5', '1/2', '3/5', '3/4'], correctIndex: 2, explanation: 'In 4 days, A completes 4/10 = 2/5 of the work, leaving 1 − 2/5 = 3/5 of the work unfinished.', source },
  { id: 'lic-p-qa-027', section: 'Quantitative Aptitude', topic: 'Time and Work', difficulty: 'hard', question: 'A, B, and C can individually complete a piece of work in 10, 15, and 30 days respectively. Working together, how many days will they take to finish the work?', options: ['4 days', '5 days', '6 days', '7 days'], correctIndex: 1, explanation: "Combined work rate = 1/10 + 1/15 + 1/30 = 3/30 + 2/30 + 1/30 = 6/30 = 1/5 of the job per day. Time taken = 5 days.", source },
  { id: 'lic-p-qa-028', section: 'Quantitative Aptitude', topic: 'Time, Speed and Distance', difficulty: 'easy', question: 'A train travels 360 km in 4 hours at a uniform speed. Find its speed in km/h.', options: ['80 km/h', '85 km/h', '90 km/h', '95 km/h'], correctIndex: 2, explanation: 'Speed = Distance / Time = 360 / 4 = 90 km/h.', source },
  { id: 'lic-p-qa-029', section: 'Quantitative Aptitude', topic: 'Time, Speed and Distance', difficulty: 'medium', question: 'Convert a speed of 72 km/h into metres per second.', options: ['18 m/s', '20 m/s', '22 m/s', '24 m/s'], correctIndex: 1, explanation: 'To convert km/h to m/s, multiply by 5/18: 72 × 5/18 = 20 m/s.', source },
  { id: 'lic-p-qa-030', section: 'Quantitative Aptitude', topic: 'Time, Speed and Distance', difficulty: 'hard', question: 'Two trains, 150 m and 100 m long, run in opposite directions on parallel tracks at 54 km/h and 36 km/h respectively. Find the time they take to cross each other.', options: ['8 seconds', '9 seconds', '10 seconds', '11 seconds'], correctIndex: 2, explanation: "Relative speed = 54 + 36 = 90 km/h = 25 m/s. Total length to cover = 150 + 100 = 250 m. Time = 250 / 25 = 10 seconds.", source },
  { id: 'lic-p-qa-031', section: 'Quantitative Aptitude', topic: 'Number Series', difficulty: 'easy', question: 'Find the next number in the series: 5, 10, 17, 26, 37, ?', options: ['46', '48', '50', '52'], correctIndex: 2, explanation: 'The differences between consecutive terms increase by 2 each time (5, 7, 9, 11), so the next difference is 13, giving 37 + 13 = 50.', source },
  { id: 'lic-p-qa-032', section: 'Quantitative Aptitude', topic: 'Number Series', difficulty: 'medium', question: 'Find the next number in the series: 1, 3, 6, 10, 15, ?', options: ['18', '20', '21', '24'], correctIndex: 2, explanation: 'This is the triangular number series, where each term adds one more than the previous gap: +2, +3, +4, +5, +6, giving 15 + 6 = 21.', source },
  { id: 'lic-p-qa-033', section: 'Quantitative Aptitude', topic: 'Number Series', difficulty: 'easy', question: 'Find the next number in the series: 8, 15, 24, 35, 48, ?', options: ['59', '61', '63', '65'], correctIndex: 2, explanation: 'The differences between consecutive terms increase by 2 each time (7, 9, 11, 13), so the next difference is 15, giving 48 + 15 = 63.', source },
  { id: 'lic-p-qa-034', section: 'Quantitative Aptitude', topic: 'Mensuration', difficulty: 'easy', question: 'Find the area of a rectangle with length 15 m and breadth 8 m.', options: ['110 sq. m', '115 sq. m', '120 sq. m', '125 sq. m'], correctIndex: 2, explanation: 'Area of a rectangle = length × breadth = 15 × 8 = 120 sq. m.', source },
  { id: 'lic-p-qa-035', section: 'Quantitative Aptitude', topic: 'Mensuration', difficulty: 'medium', question: 'Find the perimeter of a square with side 12 cm.', options: ['42 cm', '44 cm', '46 cm', '48 cm'], correctIndex: 3, explanation: 'Perimeter of a square = 4 × side = 4 × 12 = 48 cm.', source },
];
