import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'Original MAT (Management Aptitude Test) practice questions in the official 4-option multiple-choice format, covering Language Comprehension, Intelligence and Critical Reasoning, Mathematical Skills, and Data Analysis and Sufficiency. Second set, built to the same section proportions and difficulty mix as the first.',
  url: 'https://mat.aima.in/',
  checkedOn: '18 September 2026',
};

export const MAT_LANGUAGE_REASONING_QUANT_DATA_2: Question[] = [
  // Language Comprehension
  { id: 'mat-lang-reas-quant-data-02-001', section: 'Language Comprehension', topic: 'Vocabulary: Synonym', difficulty: 'medium', question: 'Choose the word most similar in meaning to \'Frugal\':', options: ['Thrifty', 'Lavish', 'Fragile', 'Honest'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Frugal describes careful, sparing use of money or resources, which is what thrifty means. Lavish is its opposite, and fragile merely sounds similar.', source },
  { id: 'mat-lang-reas-quant-data-02-002', section: 'Language Comprehension', topic: 'Vocabulary: Antonym', difficulty: 'medium', question: 'Choose the word opposite in meaning to \'Ambiguous\':', options: ['Vague', 'Explicit', 'Complex', 'Doubtful'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Ambiguous means open to more than one reading, so its opposite is explicit, which leaves nothing to interpretation. Vague and doubtful sit close to ambiguous rather than against it.', source },
  { id: 'mat-lang-reas-quant-data-02-003', section: 'Language Comprehension', topic: 'Grammar', difficulty: 'medium', question: 'Fill in the blank: Neither of the two proposals ___ acceptable to the board.', options: ['are', 'were', 'is', 'have been'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: '"Neither" is singular when it stands alone as the subject, so it takes "is". The plural "proposals" sits inside the prepositional phrase and does not govern the verb.', source },
  { id: 'mat-lang-reas-quant-data-02-004', section: 'Language Comprehension', topic: 'Sentence Correction', difficulty: 'medium', question: 'Fill in the blank: Either the director or the producers ___ attending the premiere.', options: ['is', 'was', 'has been', 'are'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'With "either ... or" the verb agrees with the subject nearer to it, which is the plural "producers", so the verb is "are".', source },
  { id: 'mat-lang-reas-quant-data-02-005', section: 'Language Comprehension', topic: 'Prepositions', difficulty: 'easy', question: 'Fill in the blank: The findings are consistent ___ earlier studies in the field.', options: ['with', 'to', 'for', 'at'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'One thing is consistent with another. "Consistent to" and "consistent for" are not standard usage.', source },
  { id: 'mat-lang-reas-quant-data-02-006', section: 'Language Comprehension', topic: 'One-word Substitution', difficulty: 'medium', question: 'Select the word that means \'a place where coins are manufactured\':', options: ['Foundry', 'Mint', 'Treasury', 'Arsenal'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Coins are struck at a mint. A foundry casts metal generally, a treasury holds public funds, and an arsenal stores weapons.', source },
  { id: 'mat-lang-reas-quant-data-02-007', section: 'Language Comprehension', topic: 'Idioms and Phrases', difficulty: 'medium', question: 'What does the idiom \'to bite the bullet\' mean?', options: ['To speak without thinking', 'To take a serious risk for a small reward', 'To accept something unpleasant that cannot be avoided', 'To interrupt someone rudely'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'To bite the bullet is to face an unavoidable ordeal and get on with it. It carries no sense of recklessness or rudeness.', source },
  { id: 'mat-lang-reas-quant-data-02-008', section: 'Language Comprehension', topic: 'Reading Comprehension', difficulty: 'medium', question: 'Passage: "A warehouse that promises next-day delivery does not need faster vehicles. It needs to be holding the right items close to the customer before the order exists. That is a forecasting problem wearing the costume of a logistics problem, and the two are usually funded by different departments. When the forecast is wrong the fleet gets blamed, because the delay is visible at the door and was invisible in a spreadsheet three months earlier." According to the passage, what actually causes next-day delivery to fail?', options: ['Vehicles that are too slow for the distances involved', 'Warehouses that are built too far from customers', 'Departments that refuse to share their budgets', 'Errors in forecasting which items to hold near the customer'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage opens by ruling out faster vehicles and locates the problem in holding the right items close before the order exists, which it names a forecasting problem.', source },
  { id: 'mat-lang-reas-quant-data-02-009', section: 'Language Comprehension', topic: 'Reading Comprehension', difficulty: 'medium', question: 'Passage: "A warehouse that promises next-day delivery does not need faster vehicles. It needs to be holding the right items close to the customer before the order exists. That is a forecasting problem wearing the costume of a logistics problem, and the two are usually funded by different departments. When the forecast is wrong the fleet gets blamed, because the delay is visible at the door and was invisible in a spreadsheet three months earlier." What can be inferred about how such failures are usually attributed?', options: ['Blame settles on the part of the process that is visible when the failure appears', 'Blame is shared equally between forecasting and logistics teams', 'Forecasting teams usually accept responsibility for late deliveries', 'No department is held responsible for a late delivery'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The closing sentence contrasts a delay that is visible at the door with a forecast that was invisible in a spreadsheet months earlier, and says the fleet gets blamed.', source },
  { id: 'mat-lang-reas-quant-data-02-010', section: 'Language Comprehension', topic: 'Sentence Completion', difficulty: 'medium', question: 'Fill in the blank: Although the committee had been warned repeatedly, it ___ to act until the deadline had passed.', options: ['managed', 'failed', 'refused', 'attempted'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: '"Although" sets up a contrast with the warnings, and the sentence says action came only after the deadline, so the committee failed to act in time. "Refused" would assert a deliberate choice the sentence does not support.', source },
  // Intelligence and Critical Reasoning
  { id: 'mat-lang-reas-quant-data-02-011', section: 'Intelligence and Critical Reasoning', topic: 'Analogy', difficulty: 'medium', question: 'Cobbler is to Shoes as Cooper is to ?', options: ['Bricks', 'Glass', 'Barrels', 'Cloth'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'A cobbler makes and mends shoes, and a cooper makes barrels and casks.', source },
  { id: 'mat-lang-reas-quant-data-02-012', section: 'Intelligence and Critical Reasoning', topic: 'Coding-Decoding', difficulty: 'medium', question: 'In a certain code, \'TABLE\' is written as \'WDEOH\'. How is \'CHAIR\' written in that code?', options: ['EJCKT', 'FKDLU', 'FKCLU', 'GLEMV'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Each letter moves three places forward in the alphabet, as T gives W and E gives H. C, H, A, I and R therefore give F, K, D, L and U.', source },
  { id: 'mat-lang-reas-quant-data-02-013', section: 'Intelligence and Critical Reasoning', topic: 'Blood Relations', difficulty: 'medium', question: 'A is B\'s father. B is C\'s sister. C is D\'s mother. How is A related to D?', options: ['D\'s grandfather', 'D\'s father', 'D\'s uncle', 'D\'s brother'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'B and C are siblings, so A is the father of both. C is the mother of D, which makes A the grandfather of D.', source },
  { id: 'mat-lang-reas-quant-data-02-014', section: 'Intelligence and Critical Reasoning', topic: 'Number Series', difficulty: 'medium', question: 'Find the next number in the series: 2, 5, 11, 23, 47, ?', options: ['89', '95', '97', '99'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Each term is twice the one before it plus one, so the next is 2 × 47 + 1, that is 95.', source },
  { id: 'mat-lang-reas-quant-data-02-015', section: 'Intelligence and Critical Reasoning', topic: 'Syllogism', difficulty: 'medium', question: 'Statements: Some doctors are writers. All writers are readers. Conclusions: I. Some doctors are readers. II. All readers are writers. Which conclusions follow?', options: ['Neither conclusion follows', 'Both conclusions follow', 'Only conclusion I follows', 'Only conclusion II follows'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The doctors who are writers must also be readers, so conclusion I holds. Conclusion II reverses the second statement, which does not follow, since there may be readers who write nothing.', source },
  { id: 'mat-lang-reas-quant-data-02-016', section: 'Intelligence and Critical Reasoning', topic: 'Direction Sense', difficulty: 'medium', question: 'Facing north, a courier walks 8 km, turns right and walks 6 km, then turns right and walks 8 km. How far is the courier from the starting point?', options: ['2 km', '4 km', '5 km', '6 km'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The first and third legs are equal and opposite, north then south, so they cancel. Only the 6 km eastward leg is left.', source },
  { id: 'mat-lang-reas-quant-data-02-017', section: 'Intelligence and Critical Reasoning', topic: 'Classification', difficulty: 'medium', question: 'Three of the following four belong to one group. Which one does not belong: Kilogram, Metre, Second, Velocity?', options: ['Velocity', 'Kilogram', 'Metre', 'Second'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The kilogram, the metre and the second are base units of measurement. Velocity is a physical quantity, and its unit is derived from two of the others.', source },
  { id: 'mat-lang-reas-quant-data-02-018', section: 'Intelligence and Critical Reasoning', topic: 'Seating Arrangement', difficulty: 'hard', question: 'Six colleagues P, Q, R, S, T and U sit around a circular table facing the centre. P sits third to the left of Q. R sits second to the right of P. S is an immediate neighbour of Q. U sits immediately to the right of P. Who sits immediately to the left of R?', options: ['P', 'S', 'T', 'U'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Taking P as a fixed seat, Q sits three places clockwise from P and R two places anticlockwise from P, which puts R between Q and U. U is immediately anticlockwise of P, and the seat immediately clockwise of R is exactly that seat, so U sits to R\'s left.', source },
  { id: 'mat-lang-reas-quant-data-02-019', section: 'Intelligence and Critical Reasoning', topic: 'Statement and Assumption', difficulty: 'hard', question: 'A university has made submission of all assignments through its online portal compulsory. Which assumption underlies this decision?', options: ['The portal is cheaper to run than accepting paper submissions', 'Students who submit late do so because of paper handling', 'Students have reliable access to the internet', 'Assignments submitted online are of better quality'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Making the portal the only route assumes every student can actually reach it. The other three may be hoped for, but the rule does not depend on any of them being true.', source },
  { id: 'mat-lang-reas-quant-data-02-020', section: 'Intelligence and Critical Reasoning', topic: 'Critical Reasoning', difficulty: 'hard', question: 'A study found that people who eat breakfast weigh less on average than those who skip it, and a nutritionist concluded that eating breakfast causes weight loss. Which finding, if true, most weakens that conclusion?', options: ['Breakfast eaters report feeling more alert during the morning', 'The study followed its participants for a full year', 'Some breakfast foods contain more sugar than an average lunch', 'People already managing their weight are far more likely to keep a regular breakfast routine'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'If an existing concern with weight drives both the breakfast habit and the lower weight, the association is explained without breakfast causing anything. Sugar content and alertness leave the causal claim untouched.', source },
  // Mathematical Skills
  { id: 'mat-lang-reas-quant-data-02-021', section: 'Mathematical Skills', topic: 'Percentage', difficulty: 'medium', question: 'In an election between two candidates, the winner polled 58% of the valid votes and won by 3,200 votes. How many valid votes were cast?', options: ['20,000', '24,000', '25,000', '32,000'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The winning margin is 58% less 42%, that is 16% of the votes. If 16% is 3,200 then the total is 20,000.', source },
  { id: 'mat-lang-reas-quant-data-02-022', section: 'Mathematical Skills', topic: 'Profit and Loss', difficulty: 'medium', question: 'An article sold for ₹960 yields a profit of 20%. What is its cost price?', options: ['₹750', '₹800', '₹840', '₹1,152'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The selling price is 120% of the cost, so the cost is 960 divided by 1.2, which is ₹800. Adding 20% to 960 instead would give ₹1,152.', source },
  { id: 'mat-lang-reas-quant-data-02-023', section: 'Mathematical Skills', topic: 'Simple Interest', difficulty: 'easy', question: 'Find the simple interest on ₹15,000 at 7% per annum for 4 years.', options: ['₹3,150', '₹4,050', '₹4,200', '₹5,250'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Simple interest is 15,000 × 7 × 4 divided by 100, which is ₹4,200.', source },
  { id: 'mat-lang-reas-quant-data-02-024', section: 'Mathematical Skills', topic: 'Compound Interest', difficulty: 'medium', question: 'Find the compound interest on ₹16,000 at 10% per annum for 2 years, compounded annually.', options: ['₹1,600', '₹3,200', '₹3,300', '₹3,360'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The amount is 16,000 × 1.21, that is ₹19,360, so the interest is ₹3,360. Simple interest over the same period would be ₹3,200.', source },
  { id: 'mat-lang-reas-quant-data-02-025', section: 'Mathematical Skills', topic: 'Partnership', difficulty: 'medium', question: 'A and B invest ₹36,000 and ₹48,000 respectively for the same period. If the profit is ₹14,000, what is A\'s share?', options: ['₹6,000', '₹7,000', '₹8,000', '₹9,600'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The capitals are in the ratio 36 to 48, that is 3 to 4, so A takes three sevenths of ₹14,000, which is ₹6,000, and B takes ₹8,000.', source },
  { id: 'mat-lang-reas-quant-data-02-026', section: 'Mathematical Skills', topic: 'Averages', difficulty: 'medium', question: 'The average of 11 results is 50. The average of the first six is 49 and of the last six is 52. What is the sixth result?', options: ['50', '56', '58', '60'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The first six total 294 and the last six total 312, which is 606 in all, but the sixth result has been counted in both. Subtracting the true total of 550 leaves 56.', source },
  { id: 'mat-lang-reas-quant-data-02-027', section: 'Mathematical Skills', topic: 'Boats and Streams', difficulty: 'medium', question: 'A boat covers 30 km downstream in 2 hours and returns upstream in 3 hours. What is the speed of the stream?', options: ['1.5 km/h', '2 km/h', '2.5 km/h', '5 km/h'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Downstream speed is 15 km/h and upstream 10 km/h. The stream speed is half their difference, that is 2.5 km/h, while half their sum, 12.5 km/h, is the speed of the boat in still water.', source },
  { id: 'mat-lang-reas-quant-data-02-028', section: 'Mathematical Skills', topic: 'Pipes and Cisterns', difficulty: 'medium', question: 'Two pipes can fill a tank in 12 hours and 15 hours. Both are opened together, and after 4 hours the first is closed. How much longer does the second take to fill the tank?', options: ['3 hours', '4 hours', '5 hours', '6 hours'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Together the pipes fill three twentieths of the tank an hour, so 4 hours fills three fifths. The remaining two fifths at one fifteenth an hour takes 6 hours.', source },
  { id: 'mat-lang-reas-quant-data-02-029', section: 'Mathematical Skills', topic: 'Algebra', difficulty: 'medium', question: 'If a + b = 7 and ab = 12, what is the value of a² + b²?', options: ['25', '37', '49', '73'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'a² + b² is (a + b)² less 2ab, which is 49 − 24, that is 25.', source },
  { id: 'mat-lang-reas-quant-data-02-030', section: 'Mathematical Skills', topic: 'Mensuration', difficulty: 'medium', question: 'Find the curved surface area of a cylinder of radius 7 cm and height 15 cm (use π = 22/7).', options: ['330 cm²', '660 cm²', '770 cm²', '990 cm²'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The curved surface area is 2πrh, which is 2 × 22/7 × 7 × 15, that is 660 cm².', source },
  // Data Analysis and Sufficiency
  { id: 'mat-lang-reas-quant-data-02-031', section: 'Data Analysis and Sufficiency', topic: 'Data Sufficiency', difficulty: 'medium', question: 'What is the value of the two-digit number x? Statement I: x is a prime number between 10 and 20. Statement II: x is divisible by 13.', options: ['Statement I alone is sufficient, but Statement II alone is not sufficient', 'Statement II alone is sufficient, but Statement I alone is not sufficient', 'Both statements together are sufficient, but neither alone is sufficient', 'Both statements together are not sufficient'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Statement I allows 11, 13, 17 and 19, and Statement II allows every two-digit multiple of 13. Only 13 satisfies both, so the statements are sufficient together but not alone.', source },
  { id: 'mat-lang-reas-quant-data-02-032', section: 'Data Analysis and Sufficiency', topic: 'Data Sufficiency', difficulty: 'medium', question: 'Is the quadrilateral a square? Statement I: All four sides are equal and all four angles are right angles. Statement II: The diagonals are equal and bisect each other at right angles.', options: ['Statement I alone is sufficient, but Statement II alone is not sufficient', 'Statement II alone is sufficient, but Statement I alone is not sufficient', 'Both statements together are sufficient, but neither alone is sufficient', 'Each statement alone is sufficient'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Equal sides with right angles define a square outright, and so do diagonals that are equal and bisect each other perpendicularly. Either statement settles the question on its own.', source },
  { id: 'mat-lang-reas-quant-data-02-033', section: 'Data Analysis and Sufficiency', topic: 'Data Sufficiency', difficulty: 'medium', question: 'What is the perimeter of a rectangle? Statement I: Its length is 12 cm and its breadth is 5 cm. Statement II: Its area is 60 cm².', options: ['Statement I alone is sufficient, but Statement II alone is not sufficient', 'Statement II alone is sufficient, but Statement I alone is not sufficient', 'Both statements together are sufficient, but neither alone is sufficient', 'Both statements together are not sufficient'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Statement I gives both dimensions, so the perimeter is 34 cm. Statement II fixes only the product of the sides, which many different rectangles share, so it cannot fix the perimeter.', source },
  { id: 'mat-lang-reas-quant-data-02-034', section: 'Data Analysis and Sufficiency', topic: 'Data Interpretation', difficulty: 'medium', question: 'A retailer recorded quarterly revenue (in ₹ lakh) of Q1 120, Q2 150, Q3 135 and Q4 195. What share of the annual revenue came in Q4?', options: ['30%', '32.5%', '35%', '37.5%'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The four quarters total ₹600 lakh, and 195 as a share of 600 is 32.5%.', source },
  { id: 'mat-lang-reas-quant-data-02-035', section: 'Data Analysis and Sufficiency', topic: 'Data Interpretation', difficulty: 'medium', question: 'Using the same quarterly revenue (Q1 120, Q2 150, Q3 135, Q4 195, in ₹ lakh), by what percentage did Q4 exceed Q2?', options: ['22.5%', '25%', '30%', '35%'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The rise is 45 on a Q2 base of 150, which is 30%. Measuring against Q4 instead would give 23.1%, but the base must be the earlier quarter.', source },
  { id: 'mat-lang-reas-quant-data-02-036', section: 'Data Analysis and Sufficiency', topic: 'Data Interpretation', difficulty: 'medium', question: 'Using the same quarterly revenue (Q1 120, Q2 150, Q3 135, Q4 195, in ₹ lakh), what was the average quarterly revenue?', options: ['₹120 lakh', '₹135 lakh', '₹145 lakh', '₹150 lakh'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The total of ₹600 lakh divided by four quarters gives ₹150 lakh.', source },
  { id: 'mat-lang-reas-quant-data-02-037', section: 'Data Analysis and Sufficiency', topic: 'Data Interpretation', difficulty: 'medium', question: 'A college of 400 students is divided by stream as Science 160, Commerce 120, Arts 80 and Vocational 40. What is the ratio of Science students to Arts students?', options: ['2:1', '1:2', '3:1', '4:1'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: '160 to 80 reduces to 2 to 1.', source },
  { id: 'mat-lang-reas-quant-data-02-038', section: 'Data Analysis and Sufficiency', topic: 'Data Interpretation', difficulty: 'medium', question: 'Using the same stream figures (Science 160, Commerce 120, Arts 80, Vocational 40), Commerce students form what percentage of the college?', options: ['25%', '30%', '35%', '40%'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: '120 out of 400 is 30%.', source },
  { id: 'mat-lang-reas-quant-data-02-039', section: 'Data Analysis and Sufficiency', topic: 'Data Sufficiency', difficulty: 'medium', question: 'What is the average age of a group of people? Statement I: Their ages total 240 years. Statement II: The group has 8 members.', options: ['Statement I alone is sufficient, but Statement II alone is not sufficient', 'Statement II alone is sufficient, but Statement I alone is not sufficient', 'Both statements together are sufficient, but neither alone is sufficient', 'Both statements together are not sufficient'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'An average needs both a total and a count. Either statement alone leaves the other unknown, and together they give 30 years.', source },
  { id: 'mat-lang-reas-quant-data-02-040', section: 'Data Analysis and Sufficiency', topic: 'Data Sufficiency', difficulty: 'hard', question: 'What is the two-digit number? Statement I: It is a multiple of 9. Statement II: The difference between its two digits is 3.', options: ['Statement I alone is sufficient, but Statement II alone is not sufficient', 'Statement II alone is sufficient, but Statement I alone is not sufficient', 'Both statements together are sufficient, but neither alone is sufficient', 'Both statements together are not sufficient'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Both conditions together are met by 36 and by 63, so even the two statements taken together do not pin the number down to one value.', source },
];
