import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'Original MAT practice questions in the official 4-option multiple-choice format, covering Language Comprehension, Intelligence and Critical Reasoning, Mathematical Skills, and Data Analysis and Sufficiency, matching the syllabus confirmed via mat.aima.in and corroborating sources.',
  url: 'https://mat.aima.in/',
  checkedOn: '18 August 2026',
};

export const MAT_LANGUAGE_REASONING_QUANT_DATA_1: Question[] = [
  // Language Comprehension
  { id: 'mat-lang-reasoning-quant-data-01-001', section: 'Language Comprehension', topic: 'Vocabulary: Synonym', difficulty: 'medium', question: "Choose the word most similar in meaning to 'Meticulous':", options: ['Careless', 'Indifferent', 'Hasty', 'Painstaking'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: '"Meticulous" means showing great attention to detail, closest in meaning to "painstaking".', source },
  { id: 'mat-lang-reasoning-quant-data-01-002', section: 'Language Comprehension', topic: 'Vocabulary: Synonym', difficulty: 'medium', question: "Choose the word most similar in meaning to 'Candid':", options: ['Frank', 'Secretive', 'Evasive', 'Formal'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: '"Candid" means truthful and straightforward, closest in meaning to "frank".', source },
  { id: 'mat-lang-reasoning-quant-data-01-003', section: 'Language Comprehension', topic: 'Vocabulary: Antonym', difficulty: 'medium', question: "Choose the word opposite in meaning to 'Concise':", options: ['Brief', 'Verbose', 'Compact', 'Terse'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: '"Concise" means brief and to the point; its opposite is "verbose" (using more words than needed).', source },
  { id: 'mat-lang-reasoning-quant-data-01-004', section: 'Language Comprehension', topic: 'Grammar', difficulty: 'medium', question: 'Choose the sentence with correct subject-verb agreement.', options: ['Each of the members have paid their dues.', 'Each of the members are paying their dues.', 'Each of the member have paid their dues.', 'Each of the members has paid their dues.'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: '"Each" is singular and takes the singular verb "has": each... has paid.', source },
  { id: 'mat-lang-reasoning-quant-data-01-005', section: 'Language Comprehension', topic: 'Sentence Correction', difficulty: 'medium', question: 'Choose the grammatically correct version: "Neither the manager nor the employees was informed of the change."', options: ['Neither the manager nor the employees was informed of the change.', 'Neither the manager nor the employees were informed of the change.', 'Neither the manager or the employees were informed of the change.', 'Neither the manager nor the employees is informed of the change.'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'With "neither...nor", the verb agrees with the nearer subject; since "employees" (plural) is nearer, the verb is "were".', source },
  { id: 'mat-lang-reasoning-quant-data-01-006', section: 'Language Comprehension', topic: 'Prepositions', difficulty: 'easy', question: 'Fill in the blank: The committee is responsible ___ reviewing every application.', options: ['of', 'with', 'to', 'for'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'The correct idiomatic preposition is "for": responsible for.', source },
  { id: 'mat-lang-reasoning-quant-data-01-007', section: 'Language Comprehension', topic: 'One-word Substitution', difficulty: 'medium', question: "Select the word that means 'a statement that is difficult to understand or explain':", options: ['Ambiguous', 'Obscure', 'Enigma', 'Paradox'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: '"Enigma" refers to something puzzling or difficult to understand.', source },
  { id: 'mat-lang-reasoning-quant-data-01-008', section: 'Language Comprehension', topic: 'Idioms and Phrases', difficulty: 'medium', question: "What does the idiom 'to read between the lines' mean?", options: ['To read very slowly', 'To understand a hidden or implied meaning', 'To skip parts of a text', 'To read aloud'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: '"To read between the lines" means to understand the implied meaning that is not directly stated.', source },
  { id: 'mat-lang-reasoning-quant-data-01-009', section: 'Language Comprehension', topic: 'Reading Comprehension', difficulty: 'medium', question: 'Passage: "A growing number of small manufacturers now sell directly to customers through their own websites rather than through large retail chains. This shift lets a manufacturer set its own price and keep a larger share of each sale, but it also means the manufacturer must handle its own shipping, customer service, and returns, tasks a retail chain would otherwise absorb. Some manufacturers report that direct sales are more profitable per unit even though total sales volume is often lower than what a retail partnership would provide." Which of the following best captures the main idea of the passage?', options: ['Retail chains are being replaced entirely by direct-to-customer websites', 'Selling directly to customers raises the price per unit but lowers total profit', 'Selling directly to customers can raise profit per unit, but shifts new operational burdens onto the manufacturer', 'Manufacturers who sell directly to customers always achieve higher total sales volume'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'The passage describes both the profit-per-unit benefit of direct sales and the added operational responsibilities (shipping, service, returns) that come with it.', source },
  { id: 'mat-lang-reasoning-quant-data-01-010', section: 'Language Comprehension', topic: 'Reading Comprehension', difficulty: 'medium', question: 'Based on the passage above, which of the following can be inferred?', options: ['Manufacturers who sell directly always earn less money overall', 'Direct sales guarantee lower shipping costs than retail partnerships', 'Retail chains never allow manufacturers to set their own prices', 'A manufacturer choosing direct sales takes on responsibilities a retail chain previously handled'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'The passage states the manufacturer "must handle its own shipping, customer service, and returns, tasks a retail chain would otherwise absorb," supporting this inference.', source },
  // Intelligence and Critical Reasoning
  { id: 'mat-lang-reasoning-quant-data-01-011', section: 'Intelligence and Critical Reasoning', topic: 'Analogy', difficulty: 'medium', question: 'Chef is to Kitchen as Surgeon is to ?', options: ['Operating Room', 'Hospital', 'Clinic', 'Ward'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'A chef performs their craft in a kitchen, just as a surgeon performs theirs in an operating room.', source },
  { id: 'mat-lang-reasoning-quant-data-01-012', section: 'Intelligence and Critical Reasoning', topic: 'Coding-Decoding', difficulty: 'medium', question: "In a certain code, 'FLOWER' is written as 'GMPXFS'. How is 'GARDEN' written in that code?", options: ['HBSEFO', 'HBSEFP', 'HCSEFO', 'HBSDFO'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Each letter is shifted forward by one position: G→H, A→B, R→S, D→E, E→F, N→O, giving HBSEFO.', source },
  { id: 'mat-lang-reasoning-quant-data-01-013', section: 'Intelligence and Critical Reasoning', topic: 'Blood Relations', difficulty: 'medium', question: "Pointing to a photograph, Rohan said, 'She is the daughter of my grandfather's only son.' How is the woman in the photograph related to Rohan?", options: ['Mother', 'Aunt', 'Cousin', 'Sister'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: "Rohan's grandfather's only son is Rohan's father, so the woman is his father's daughter, meaning she is Rohan's sister.", source },
  { id: 'mat-lang-reasoning-quant-data-01-014', section: 'Intelligence and Critical Reasoning', topic: 'Number Series', difficulty: 'medium', question: 'Find the next number in the series: 3, 8, 18, 38, 78, ?', options: ['118', '138', '158', '148'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Each term is generated as (previous × 2) + 2: 3×2+2=8, 8×2+2=18, 18×2+2=38, 38×2+2=78, 78×2+2=158.', source },
  { id: 'mat-lang-reasoning-quant-data-01-015', section: 'Intelligence and Critical Reasoning', topic: 'Syllogism', difficulty: 'medium', question: 'Statements: All pens are markers. Some markers are highlighters. Conclusions: I. Some pens are highlighters. II. Some highlighters are markers.', options: ['Only conclusion I follows', 'Only conclusion II follows', 'Both conclusions follow', 'Neither conclusion follows'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'From "some markers are highlighters," it follows that some highlighters are markers (conclusion II). Conclusion I does not necessarily follow, since the markers that are highlighters may not overlap with the markers that are pens.', source },
  { id: 'mat-lang-reasoning-quant-data-01-016', section: 'Intelligence and Critical Reasoning', topic: 'Direction Sense', difficulty: 'medium', question: 'Meera walks 6 km north, then turns right and walks 8 km, then turns right again and walks 6 km. How far is she from her starting point?', options: ['6 km', '14 km', '10 km', '8 km'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'She ends up 8 km east of her starting point, since the two 6 km north-south legs cancel out, leaving only the 8 km eastward leg.', source },
  { id: 'mat-lang-reasoning-quant-data-01-017', section: 'Intelligence and Critical Reasoning', topic: 'Classification', difficulty: 'medium', question: 'Three of the following four items belong to the same category and one does not. Which one is different?', options: ['Guitar', 'Violin', 'Sitar', 'Tabla'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Guitar, Violin, and Sitar are all stringed instruments, while Tabla is a percussion instrument.', source },
  { id: 'mat-lang-reasoning-quant-data-01-018', section: 'Intelligence and Critical Reasoning', topic: 'Seating Arrangement', difficulty: 'hard', question: 'Five friends P, Q, R, S, and T sit in a row facing north. Q sits second from the left end. R sits immediately to the right of Q. S sits at the left end. P sits immediately to the left of T. Who sits in the middle of the row?', options: ['P', 'R', 'T', 'Q'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Placing S at the left end, Q second from left, R immediately right of Q, and P immediately left of T in the two remaining seats gives the order S, Q, R, P, T, so R is in the middle (third position).', source },
  { id: 'mat-lang-reasoning-quant-data-01-019', section: 'Intelligence and Critical Reasoning', topic: 'Statement and Assumption', difficulty: 'hard', question: 'Statement: "The company will hold all future team meetings online instead of in the conference room." Assumption: I. The company has reliable video-conferencing tools available. II. Employees prefer online meetings over in-person meetings.', options: ['Only assumption I is implicit', 'Only assumption II is implicit', 'Both assumptions are implicit', 'Neither assumption is implicit'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Holding meetings online assumes the company has the tools to do so (assumption I). It does not require that employees prefer this format (assumption II), since the decision could be made for other reasons like cost.', source },
  { id: 'mat-lang-reasoning-quant-data-01-020', section: 'Intelligence and Critical Reasoning', topic: 'Critical Reasoning', difficulty: 'hard', question: 'A city reports that ice cream sales and the number of drowning incidents both rise every summer. A columnist concludes that eating ice cream causes drowning. Which of the following, if true, most weakens this conclusion?', options: ['Ice cream sales have grown steadily over the past decade', 'Some people who eat ice cream never go swimming', 'Most drowning incidents occur in the afternoon', 'Warmer weather independently increases both ice cream sales and swimming activity, which raises drowning risk'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'This identifies a common cause (warmer weather) driving both variables, showing the correlation does not imply the causal link the columnist claims.', source },
  // Mathematical Skills
  { id: 'mat-lang-reasoning-quant-data-01-021', section: 'Mathematical Skills', topic: 'Mixtures and Alligation', difficulty: 'medium', question: 'A shopkeeper mixes two varieties of rice costing ₹40 per kg and ₹60 per kg in the ratio 3:2. Find the price per kg of the mixture.', options: ['₹46', '₹48', '₹50', '₹52'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'By the weighted average (alligation) rule, mixture price = (3×40 + 2×60) / 5 = (120+120)/5 = ₹48 per kg.', source },
  { id: 'mat-lang-reasoning-quant-data-01-022', section: 'Mathematical Skills', topic: 'Profit and Loss', difficulty: 'medium', question: 'A trader marks an article 40% above its cost price and then gives a 10% discount on the marked price. What is the trader\'s profit percentage?', options: ['26%', '30%', '25%', '24%'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Let cost price = 100. Marked price = 140. Selling price = 140 × 0.9 = 126. Profit = 26%.', source },
  { id: 'mat-lang-reasoning-quant-data-01-023', section: 'Mathematical Skills', topic: 'Simple Interest', difficulty: 'easy', question: 'Find the simple interest on ₹18,000 at 9% per annum for 3 years.', options: ['₹4,860', '₹4,680', '₹5,040', '₹4,500'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'SI = (18000 × 9 × 3) / 100 = ₹4,860.', source },
  { id: 'mat-lang-reasoning-quant-data-01-024', section: 'Mathematical Skills', topic: 'Compound Interest', difficulty: 'medium', question: 'Find the compound interest on ₹20,000 at 5% per annum for 2 years, compounded annually.', options: ['₹2,000', '₹1,950', '₹2,100', '₹2,050'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Amount = 20000 × 1.05 × 1.05 = 22,050. CI = 22,050 - 20,000 = ₹2,050.', source },
  { id: 'mat-lang-reasoning-quant-data-01-025', section: 'Mathematical Skills', topic: 'Ratio and Proportion', difficulty: 'medium', question: 'The ratio of ages of A and B is 5:7. After 6 years, the ratio becomes 3:4. What is the present age of A?', options: ['24 years', '28 years', '30 years', '25 years'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Let ages be 5x and 7x. (5x+6)/(7x+6) = 3/4 gives 4(5x+6) = 3(7x+6), so 20x+24 = 21x+18, giving x=6. A\'s present age = 5×6 = 30 years.', source },
  { id: 'mat-lang-reasoning-quant-data-01-026', section: 'Mathematical Skills', topic: 'Averages', difficulty: 'medium', question: 'The average weight of 9 students is 52 kg. When a tenth student joins, the average becomes 53 kg. What is the weight of the tenth student?', options: ['60 kg', '63 kg', '62 kg', '58 kg'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Total weight of 10 students = 53×10 = 530. Total weight of first 9 = 52×9 = 468. Tenth student\'s weight = 530-468 = 62 kg.', source },
  { id: 'mat-lang-reasoning-quant-data-01-027', section: 'Mathematical Skills', topic: 'Time, Speed and Distance', difficulty: 'medium', question: 'A train travels 300 km at a certain speed. If its speed had been 10 km/h more, it would have taken 1 hour less to cover the same distance. Find the original speed of the train.', options: ['50 km/h', '55 km/h', '60 km/h', '45 km/h'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Let speed = s. 300/s - 300/(s+10) = 1. Solving: 300(s+10) - 300s = s(s+10), so 3000 = s²+10s, giving s²+10s-3000=0, so s = 50 km/h.', source },
  { id: 'mat-lang-reasoning-quant-data-01-028', section: 'Mathematical Skills', topic: 'Time and Work', difficulty: 'medium', question: 'A can complete a task in 15 days and B can complete it in 10 days. If they work together, in how many days will the task be completed?', options: ['6 days', '5 days', '7 days', '8 days'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: "Combined rate = 1/15 + 1/10 = 2/30 + 3/30 = 5/30 = 1/6 of the task per day, so the task takes 6 days.", source },
  { id: 'mat-lang-reasoning-quant-data-01-029', section: 'Mathematical Skills', topic: 'Algebra', difficulty: 'medium', question: 'If x - 1/x = 3, find the value of x² + 1/x².', options: ['9', '7', '13', '11'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'x² + 1/x² = (x - 1/x)² + 2 = 9 + 2 = 11.', source },
  { id: 'mat-lang-reasoning-quant-data-01-030', section: 'Mathematical Skills', topic: 'Geometry', difficulty: 'medium', question: 'The length of a rectangle is increased by 25% and its width is decreased by 20%. What is the net percentage change in its area?', options: ['No change', '5% increase', '5% decrease', '10% increase'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Net change = 25 - 20 - (25×20)/100 = 25 - 20 - 5 = 0%, so the area is unchanged.', source },
  // Data Analysis and Sufficiency
  { id: 'mat-lang-reasoning-quant-data-01-031', section: 'Data Analysis and Sufficiency', topic: 'Data Sufficiency', difficulty: 'medium', question: 'What is the value of x? Statement I: x² = 49. Statement II: x is a positive number.', options: ['Statement I alone is sufficient, but Statement II alone is not sufficient', 'Statement II alone is sufficient, but Statement I alone is not sufficient', 'Both statements together are sufficient, but neither alone is sufficient', 'Both statements together are not sufficient'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Statement I alone gives x = 7 or x = -7 (not sufficient). Statement II alone only says x is positive (not sufficient). Together, x must be 7.', source },
  { id: 'mat-lang-reasoning-quant-data-01-032', section: 'Data Analysis and Sufficiency', topic: 'Data Sufficiency', difficulty: 'medium', question: 'Is the integer n divisible by 6? Statement I: n is divisible by 2. Statement II: n is divisible by 3.', options: ['Statement I alone is sufficient, but Statement II alone is not sufficient', 'Statement II alone is sufficient, but Statement I alone is not sufficient', 'Both statements together are sufficient, but neither alone is sufficient', 'Each statement alone is sufficient'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Neither statement alone guarantees divisibility by 6, but together (divisible by both 2 and 3), n must be divisible by 6.', source },
  { id: 'mat-lang-reasoning-quant-data-01-033', section: 'Data Analysis and Sufficiency', topic: 'Data Sufficiency', difficulty: 'medium', question: 'What is the perimeter of a rectangle? Statement I: The length of the rectangle is 12 cm. Statement II: The area of the rectangle is 96 sq. cm.', options: ['Statement I alone is sufficient, but Statement II alone is not sufficient', 'Statement II alone is sufficient, but Statement I alone is not sufficient', 'Both statements together are sufficient, but neither alone is sufficient', 'Both statements together are not sufficient'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Statement I alone gives only the length (not sufficient). Statement II alone gives only the area (not sufficient). Together: width = 96/12 = 8 cm, so perimeter = 2(12+8) = 40 cm.', source },
  { id: 'mat-lang-reasoning-quant-data-01-034', section: 'Data Analysis and Sufficiency', topic: 'Data Sufficiency', difficulty: 'medium', question: 'Was last month profitable for the company? Statement I: Revenue last month was ₹8 lakh. Statement II: Expenses last month were ₹6 lakh.', options: ['Statement I alone is sufficient, but Statement II alone is not sufficient', 'Statement II alone is sufficient, but Statement I alone is not sufficient', 'Both statements together are sufficient, but neither alone is sufficient', 'Both statements together are not sufficient'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Neither statement alone reveals whether the company was profitable, but together, revenue (8 lakh) exceeds expenses (6 lakh), confirming a profit.', source },
  { id: 'mat-lang-reasoning-quant-data-01-035', section: 'Data Analysis and Sufficiency', topic: 'Data Interpretation', difficulty: 'medium', question: 'A survey of 250 office workers recorded their preferred commute mode: Car 90, Bus 60, Train 70, Bicycle 30. What percentage of workers prefer the train?', options: ['24%', '30%', '28%', '26%'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Percentage = (70/250) × 100 = 28%.', source },
  { id: 'mat-lang-reasoning-quant-data-01-036', section: 'Data Analysis and Sufficiency', topic: 'Data Interpretation', difficulty: 'medium', question: 'Using the same commute survey (Car 90, Bus 60, Train 70, Bicycle 30), what is the ratio of workers who prefer Car to those who prefer Bicycle?', options: ['2:1', '3:1', '5:2', '3:2'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Ratio = 90:30 = 3:1.', source },
  { id: 'mat-lang-reasoning-quant-data-01-037', section: 'Data Analysis and Sufficiency', topic: 'Data Interpretation', difficulty: 'medium', question: 'A company recorded its quarterly profit (in ₹ lakh) as: Q1 40, Q2 55, Q3 50, Q4 65. What was the percentage increase in profit from Q1 to Q4?', options: ['60.5%', '62.5%', '65%', '58%'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Increase = 65-40 = 25. Percentage increase = (25/40) × 100 = 62.5%.', source },
  { id: 'mat-lang-reasoning-quant-data-01-038', section: 'Data Analysis and Sufficiency', topic: 'Data Interpretation', difficulty: 'medium', question: 'Using the same quarterly profit data (Q1 40, Q2 55, Q3 50, Q4 65, in ₹ lakh), what is the average quarterly profit for the year?', options: ['₹50 lakh', '₹52.5 lakh', '₹55 lakh', '₹48 lakh'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Average = (40+55+50+65)/4 = 210/4 = ₹52.5 lakh.', source },
  { id: 'mat-lang-reasoning-quant-data-01-039', section: 'Data Analysis and Sufficiency', topic: 'Data Interpretation', difficulty: 'medium', question: 'Using the same quarterly profit data (Q1 40, Q2 55, Q3 50, Q4 65, in ₹ lakh), in which quarter did profit decline compared to the previous quarter?', options: ['Q2', 'Q3', 'Q4', 'None of the quarters'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Profit fell from 55 (Q2) to 50 (Q3), a decline in Q3.', source },
  { id: 'mat-lang-reasoning-quant-data-01-040', section: 'Data Analysis and Sufficiency', topic: 'Data Sufficiency', difficulty: 'hard', question: 'Is x > y? Statement I: x + 3 > y + 3. Statement II: 2x > 2y.', options: ['Each statement alone is sufficient', 'Statement I alone is sufficient, but Statement II alone is not sufficient', 'Statement II alone is sufficient, but Statement I alone is not sufficient', 'Neither statement alone is sufficient'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Statement I simplifies to x > y directly. Statement II simplifies to x > y directly as well. Each statement alone is sufficient.', source },
];
