import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'Original MCAT Critical Analysis and Reasoning Skills practice questions in the official 4-option multiple-choice format, built on humanities passages of the kind the AAMC draws on for this section. Second set, built to the same length and structure as the first.',
  url: 'https://students-residents.aamc.org/prepare-mcat-exam/whats-mcat-exam',
  checkedOn: '17 September 2026',
};

const RESTORATION_PASSAGE = `Debates about the restoration of damaged paintings are usually staged as a contest between two goods: the recovery of what the artist made, and the preservation of what time has made of it. Put that way the dispute looks tractable, a matter of weighing one value against another. It is not, because the two parties are rarely disagreeing about the weights. They are disagreeing about what the object is.

For the restorer who strips a darkened varnish, the painting is the artist's arrangement of pigment, and the varnish is an accretion standing between the viewer and that arrangement. For the critic who objects, the painting is not an arrangement of pigment but an object with a history, and the darkening is part of what the object has become. Neither position is obviously wrong, and neither can be established by closer examination of the canvas, because the question at issue is prior to any examination: it concerns which properties count as belonging to the work.

What makes the dispute intractable in practice is that restoration is irreversible in one direction only. A varnish once removed cannot be replaced with the varnish that was there, though something like it can be applied. The asymmetry has led some writers to treat caution as the rational default, on the grounds that the cost of an error is unequal. But this argument proves less than it appears to. Leaving a varnish in place is not a neutral act of waiting; the varnish continues to darken, and the arrangement of pigment continues to be less visible each decade. Inaction is itself a choice with a direction, and the writer who counsels caution has simply chosen the loss that accumulates slowly over the loss that arrives at once.`;

const CRAFT_PASSAGE = `The distinction between art and craft is often drawn at the point of function: a thing made to be used is craft, a thing made to be contemplated is art. The line has never held, and the reasons it fails are more interesting than the many attempts to repair it.

Consider that the objects most confidently classed as craft are frequently made without any expectation of use. A potter producing a vessel too fragile to hold water has not thereby produced a sculpture, and the trade does not treat the piece as having changed category. Meanwhile paintings have been commissioned to cover a wall, to record a face, to advertise a merchant's standing, and their usefulness has never been thought to disqualify them.

A second attempt locates the distinction in the maker's freedom: the artist invents the form, the craftsman inherits it. This fares no better. Whole traditions of painting are governed by conventions as binding as any followed by a weaver, and individual weavers depart from inherited patterns as sharply as any painter departs from a school.

The persistence of the distinction despite these failures suggests that it is not really doing descriptive work. What it tracks, more often than not, is the social standing of the makers: which workshops were attached to courts, which trades admitted apprentices of which class, which objects were collected by whom. That is a real difference, and worth studying. It is simply not a difference in the objects, and treating it as one has led several generations of writers to search the objects for a distinction that was never there to find.`;

const TRANSLATION_ERROR_PASSAGE = `A translator who renders a pun by inventing a different pun has done something that cannot be described as accuracy, yet the alternative, a literal rendering with a footnote, is plainly worse at the only thing the original was doing. Cases like this are usually treated as marginal, the odd difficulty at the edge of an otherwise straightforward operation. The better view is that they are the ordinary case seen clearly.

Every sentence does several things at once. It states something, it sounds a certain way, it sits at a certain distance from the reader, it carries associations that have collected around its words. No second language offers a sentence that does all of these in the same proportions. The translator therefore does not choose between accuracy and licence; the translator chooses which of several accuracies to keep, knowing the others will be lost.

This is why the familiar demand that a translation be faithful is less a standard than a way of declining to state one. Faithful to which of the things the sentence was doing? The demand acquires content only when the translator has already decided, and the decision is not itself derivable from the original. It comes from a judgement about what the text is for, and that judgement belongs to the translator, who will be blamed for it in either direction.`;

export const MCAT_CARS_HUMANITIES_2: Question[] = [
  { id: 'mcat-cars-02-001', section: 'Humanities', topic: 'Main Idea', difficulty: 'hard', question: `Read the passage and answer the question that follows.\n\n${RESTORATION_PASSAGE}\n\nQuestion: Which of the following best captures the central claim of the passage?`, options: ['Restoration disputes turn on disagreement about what the object is, not on how two agreed values are weighed', 'Restorers and critics agree on what a painting is but weigh its values differently', 'Closer technical examination of a canvas can settle most restoration disputes', 'Caution is the rational default in every restoration decision'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage rejects the weighing framing in its first paragraph, stating that the parties are disagreeing about what the object is rather than about the weights.', source },
  { id: 'mcat-cars-02-002', section: 'Humanities', topic: 'Inference', difficulty: 'hard', question: `Read the passage and answer the question that follows.\n\n${RESTORATION_PASSAGE}\n\nQuestion: The author would most likely agree that the dispute cannot be settled by examining the canvas because`, options: ['the instruments available are not yet precise enough', 'restorers and critics rarely have access to the same canvas', 'the question of which properties belong to the work is prior to any examination', 'the varnish obscures the evidence that would decide the matter'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage says the question at issue is prior to any examination, concerning which properties count as belonging to the work.', source },
  { id: 'mcat-cars-02-003', section: 'Humanities', topic: 'Evaluate an Argument', difficulty: 'hard', question: `Read the passage and answer the question that follows.\n\n${RESTORATION_PASSAGE}\n\nQuestion: How does the author respond to the argument that caution should be the default because restoration errors are unequal in cost?`, options: ['By accepting it and extending it to all conservation decisions', 'By arguing that leaving a varnish in place is itself a choice with a direction of loss', 'By showing that varnish removal is in fact fully reversible', 'By denying that the two kinds of error differ in cost at all'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage grants the asymmetry but answers that inaction is not neutral, since the varnish continues to darken, so caution simply prefers slow loss to sudden loss.', source },
  { id: 'mcat-cars-02-004', section: 'Humanities', topic: 'Application', difficulty: 'hard', question: `Read the passage and answer the question that follows.\n\n${RESTORATION_PASSAGE}\n\nQuestion: Which case would most weaken the author's claim that the two parties disagree about what the object is?`, options: ['A restorer and a critic who agree on the nature of the work but reach opposite decisions after weighing recovery against history', 'A restorer who removes a varnish that the critic had also judged to be an accretion', 'A critic who declines to comment on a painting outside their period', 'A restorer who reverses a decision after new pigment analysis'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The author claims the parties are not disagreeing about weights; a genuine case of shared premises leading to opposite weightings would be a direct counterexample.', source },
  { id: 'mcat-cars-02-005', section: 'Humanities', topic: 'Main Idea', difficulty: 'medium', question: `Read the passage and answer the question that follows.\n\n${CRAFT_PASSAGE}\n\nQuestion: The central claim of the passage is that the art and craft distinction`, options: ['should be redrawn at the point of the maker\'s freedom rather than function', 'is sound but has been applied carelessly by recent writers', 'tracks the social standing of makers rather than any property of the objects', 'applies to pottery and weaving but not to painting'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The final paragraph states that what the distinction tracks is the social standing of the makers, and that this is not a difference in the objects.', source },
  { id: 'mcat-cars-02-006', section: 'Humanities', topic: 'Detail', difficulty: 'medium', question: `Read the passage and answer the question that follows.\n\n${CRAFT_PASSAGE}\n\nQuestion: The example of the vessel too fragile to hold water is used to show that`, options: ['fragile objects are generally classed as art rather than craft', 'potters rarely intend their work to be used', 'usefulness is the only reliable test of craft', 'an object may be classed as craft although it is not made for use'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The example is offered against the function test: the piece is not made for use yet the trade does not treat it as having changed category.', source },
  { id: 'mcat-cars-02-007', section: 'Humanities', topic: 'Evaluate an Argument', difficulty: 'hard', question: `Read the passage and answer the question that follows.\n\n${CRAFT_PASSAGE}\n\nQuestion: The author rejects the freedom-based distinction on the ground that`, options: ['conventions bind some painting traditions as tightly as they bind weaving, and weavers also depart from inherited patterns', 'painters have always worked under commission while weavers have not', 'the concept of freedom cannot be defined precisely enough to be useful', 'craftsmen are in fact freer than artists in most traditions'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage answers the freedom test by noting binding conventions in painting traditions and sharp departures by individual weavers.', source },
  { id: 'mcat-cars-02-008', section: 'Humanities', topic: 'Inference', difficulty: 'hard', question: `Read the passage and answer the question that follows.\n\n${CRAFT_PASSAGE}\n\nQuestion: It can be inferred that the author regards the study of workshops, apprenticeship and collecting as`, options: ['a distraction from the proper study of objects', 'valuable only for the periods in which the art and craft distinction was absent', 'the source of the confusion that the distinction has caused', 'worthwhile, since it concerns the real difference the distinction has been tracking'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage calls the social difference a real difference and worth studying, objecting only to treating it as a difference in the objects.', source },
  { id: 'mcat-cars-02-009', section: 'Humanities', topic: 'Main Idea', difficulty: 'hard', question: `Read the passage and answer the question that follows.\n\n${TRANSLATION_ERROR_PASSAGE}\n\nQuestion: The passage is primarily concerned with arguing that`, options: ['puns should be rendered literally with explanatory footnotes', 'the difficult cases in translation reveal the structure of the ordinary case', 'translation is impossible between languages of different families', 'the demand for fidelity is a sufficient standard once properly defined'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage says explicitly that cases like the pun are the ordinary case seen clearly, and builds its argument from there.', source },
  { id: 'mcat-cars-02-010', section: 'Humanities', topic: 'Detail', difficulty: 'medium', question: `Read the passage and answer the question that follows.\n\n${TRANSLATION_ERROR_PASSAGE}\n\nQuestion: According to the passage, the translator chooses between`, options: ['accuracy and licence', 'the original and its reception', 'several accuracies, knowing the others will be lost', 'the author\'s intention and the reader\'s expectation'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage states that the translator does not choose between accuracy and licence but chooses which of several accuracies to keep.', source },
  { id: 'mcat-cars-02-011', section: 'Humanities', topic: 'Inference', difficulty: 'hard', question: `Read the passage and answer the question that follows.\n\n${TRANSLATION_ERROR_PASSAGE}\n\nQuestion: The author calls the demand for fidelity "a way of declining to state" a standard because it`, options: ['asks for something no translator has ever achieved', 'applies only to literary rather than technical translation', 'was formulated before modern theories of meaning', 'leaves unanswered which of the things a sentence does must be preserved'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage immediately asks "Faithful to which of the things the sentence was doing?", indicating that the demand is empty until that is settled.', source },
  { id: 'mcat-cars-02-012', section: 'Humanities', topic: 'Application', difficulty: 'hard', question: `Read the passage and answer the question that follows.\n\n${TRANSLATION_ERROR_PASSAGE}\n\nQuestion: Which situation best illustrates the passage's account of the translator's position?`, options: ['A translator consults the author and adopts the reading the author confirms', 'A translator preserves a poem\'s metre and accepts a looser rendering of its imagery, and is criticised for the imagery', 'A translator produces a word-for-word version and appends no commentary', 'A translator declines a text on the ground that its puns cannot be carried over'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage describes the translator as keeping one accuracy at the cost of others and being blamed for the choice in either direction.', source },
];
