import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'Original MH CET Law (3-Year LLB) practice questions in the official 4-option multiple-choice format, covering Legal Aptitude and Legal Reasoning, Logical and Analytical Reasoning, and English from the Maharashtra Common Entrance Test syllabus. Legal Aptitude and Legal Reasoning questions state their own principle and facts, matching the self-contained format used across every Law exam on this site.',
  url: 'https://cetcell.mahacet.org/',
  checkedOn: '16 August 2026',
};

export const MH_CET_LAW_3_YEAR_LEGAL_LOGICAL_ENGLISH_1: Question[] = [
  // Legal Aptitude and Legal Reasoning
  { id: 'mh-cet-law-3-year-legal-logical-english-01-001', section: 'Legal Aptitude and Legal Reasoning', topic: 'Bailment', difficulty: 'medium', question: 'Principle: A bailment is the delivery of goods by one person (the bailor) to another (the bailee) for a specific purpose, on the condition that the goods will be returned or disposed of according to the bailor\'s instructions once the purpose is completed. The bailee must take as much care of the goods as a person of ordinary prudence would take of their own goods of the same value, and is liable for loss or damage only if this standard of care is not met. Facts: Meera lends her laptop to a friend, Rohan, for a week so he can complete a project, on the condition he returns it afterward. While using it responsibly and storing it safely each night, Rohan\'s laptop bag is stolen from a locked car despite reasonable precautions. Applying the principle, is Rohan liable to Meera for the loss?', options: ['No, because Rohan took the same reasonable care a prudent person would take of their own similar property, meeting the required standard', 'Yes, because any loss of borrowed property makes the borrower liable', 'Yes, because Rohan should have kept the laptop with him at all times', 'No, because theft can never result in liability under any circumstances'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Rohan met the required standard of care, so the theft despite reasonable precautions does not make him liable.', source },
  { id: 'mh-cet-law-3-year-legal-logical-english-01-002', section: 'Legal Aptitude and Legal Reasoning', topic: 'Bailment', difficulty: 'hard', question: 'Using the same principle above. Facts: Farhan leaves his motorcycle at a friend\'s garage for safekeeping while he travels. The friend, instead of storing it safely, lends the motorcycle to a stranger, who damages it in an accident. Applying the principle, is the friend liable to Farhan for the damage?', options: ['No, because accidents are always the fault of the person driving', 'Yes, because lending the motorcycle to someone else without permission falls well below the standard of care a prudent person would exercise over their own similar property', 'No, because motorcycles are inherently risky to store', 'Yes, but only if the friend intended to damage the motorcycle'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Lending the motorcycle to a stranger without permission is well below the standard of care expected, making the friend liable.', source },
  { id: 'mh-cet-law-3-year-legal-logical-english-01-003', section: 'Legal Aptitude and Legal Reasoning', topic: 'Bailment', difficulty: 'medium', question: 'Using the same principle above. Facts: A jeweller is given a diamond ring by a customer for cleaning. The jeweller stores it in the same secure safe used for the shop\'s own high-value jewellery, following the shop\'s standard security protocol. Despite this, the safe is broken into by professional burglars using specialised tools. Applying the principle, is the jeweller likely liable for the loss of the ring?', options: ['Yes, because jewellers are always strictly liable for any loss', 'No, because burglaries are entirely unpredictable events', 'Yes, because the safe should have been more secure than a professional could break into', 'No, because the jeweller stored the ring using the same level of care applied to the shop\'s own valuable goods, meeting the required standard'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Storing the ring with the same care as the shop\'s own valuable goods meets the required standard, so the jeweller is not liable despite the burglary.', source },
  { id: 'mh-cet-law-3-year-legal-logical-english-01-004', section: 'Legal Aptitude and Legal Reasoning', topic: 'Bailment', difficulty: 'medium', question: 'Using the same principle above. Facts: A warehouse owner agrees to store a trader\'s goods for a fee, but leaves the warehouse doors unlocked overnight out of carelessness, unlike his usual practice for his own stored goods. The trader\'s goods are stolen as a direct result. Applying the principle, is the warehouse owner liable?', options: ['No, because warehouses are never responsible for theft', 'Yes, but only if the trader paid an unusually high storage fee', 'No, because all thefts are unforeseeable', 'Yes, because leaving the doors unlocked, contrary to his usual practice for his own goods, falls below the required standard of care'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Deviating from his usual careful practice by leaving the doors unlocked falls below the required standard of care, making the owner liable.', source },
  { id: 'mh-cet-law-3-year-legal-logical-english-01-005', section: 'Legal Aptitude and Legal Reasoning', topic: 'Bailment', difficulty: 'medium', question: 'Using the same principle above. Facts: A car owner leaves her car with a valet for parking. The valet parks it in the designated, well-lit valet area following standard procedure, but the car is later scratched by another driver\'s carelessly opened door in the same lot. Applying the principle, is the valet likely liable for the scratch?', options: ['No, because the valet followed the standard, reasonable parking procedure and the damage was caused by an unrelated third party\'s carelessness', 'Yes, because any damage while a car is with a valet is automatically the valet\'s fault', 'Yes, because the valet should have parked the car somewhere safer', 'No, because scratches are never considered real damage'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The valet followed standard, reasonable procedure, and the damage was caused by an unrelated third party, so the valet is not liable.', source },
  { id: 'mh-cet-law-3-year-legal-logical-english-01-006', section: 'Legal Aptitude and Legal Reasoning', topic: 'Bailment', difficulty: 'hard', question: 'Using the same principle above. Facts: A tailor is given an expensive suit fabric to stitch into a garment. The tailor stores the fabric in a damp corner of the shop, unlike the dry storage used for the tailor\'s own materials, and the fabric develops mould as a result. Applying the principle, is the tailor liable for the damaged fabric?', options: ['No, because mould is a natural occurrence beyond anyone\'s control', 'Yes, because storing the customer\'s fabric differently, and less carefully, than his own materials falls below the required standard of care', 'No, because tailors are never responsible for material damage', 'Yes, but only if the tailor knew mould would develop'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Storing the customer\'s fabric less carefully than his own materials falls below the required standard of care, making the tailor liable.', source },
  // Logical and Analytical Reasoning
  { id: 'mh-cet-law-3-year-legal-logical-english-01-007', section: 'Logical and Analytical Reasoning', topic: 'Statement and Argument', difficulty: 'medium', question: 'Statement: Should all city buses be made free for senior citizens? Argument: Yes, because it would encourage more elderly residents to travel independently and reduce their isolation. Is this a strong or weak argument?', options: ['Weak, because it does not mention the cost to the city', 'Weak, because senior citizens rarely use buses', 'Strong, because it identifies a specific, relevant social benefit connected to the proposal', 'Strong, because all free public services are automatically beneficial'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The argument identifies a specific, relevant benefit (independence and reduced isolation) directly connected to the proposal, making it strong.', source },
  { id: 'mh-cet-law-3-year-legal-logical-english-01-008', section: 'Logical and Analytical Reasoning', topic: 'Number Grid', difficulty: 'medium', question: 'In the grid below, each row follows the same mathematical rule. Row 1: 3, 5, 8. Row 2: 4, 6, 10. Row 3: 6, 9, ? Find the missing number.', options: ['12', '14', '15', '16'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Each row follows the rule first + second = third: 3+5=8, 4+6=10, so 6+9=15.', source },
  { id: 'mh-cet-law-3-year-legal-logical-english-01-009', section: 'Logical and Analytical Reasoning', topic: 'Blood Relations', difficulty: 'medium', question: 'Aditi is the daughter of Bhavna. Bhavna is the sister of Chetan. Chetan is the father of Deepak. How is Aditi related to Deepak?', options: ['Cousin', 'Sister', 'Aunt', 'Niece'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Bhavna and Chetan are siblings, so their children, Aditi and Deepak, are cousins.', source },
  { id: 'mh-cet-law-3-year-legal-logical-english-01-010', section: 'Logical and Analytical Reasoning', topic: 'Cause and Effect', difficulty: 'medium', question: 'Statement: Every year, sales of raincoats and reports of slippery-road traffic accidents both increase during the monsoon season. Which of the following best explains this pattern without assuming one directly causes the other?', options: ['Raincoat sales directly cause more traffic accidents', 'Both are likely caused by the monsoon rain itself, a common underlying factor', 'Traffic accidents directly cause higher raincoat sales', 'The two events are entirely coincidental with no explanation possible'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The monsoon rain is a common underlying cause of both increased raincoat sales and more slippery-road accidents.', source },
  { id: 'mh-cet-law-3-year-legal-logical-english-01-011', section: 'Logical and Analytical Reasoning', topic: 'Mixed Series', difficulty: 'medium', question: 'Find the next term in the series: A1, C3, E5, G7, ?', options: ['H8', 'I9', 'I8', 'J9'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The letters skip one each time (A, C, E, G, I) and the numbers increase by 2 (1, 3, 5, 7, 9), giving I9.', source },
  { id: 'mh-cet-law-3-year-legal-logical-english-01-012', section: 'Logical and Analytical Reasoning', topic: 'Statement and Argument', difficulty: 'medium', question: 'Statement: Should the government ban single-use plastic bags nationwide? Argument: No, because many small vendors currently rely on cheap plastic bags and have no immediate affordable alternative. Is this a strong or weak argument?', options: ['Weak, because plastic pollution is a serious problem', 'Weak, because vendors can always find alternatives instantly', 'Weak, because the government should not consider costs', 'Strong, because it raises a genuine practical consequence directly relevant to implementing the ban'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The argument raises a genuine, practical implementation concern (lack of affordable alternatives for vendors) directly relevant to the proposed ban.', source },
  // English
  { id: 'mh-cet-law-3-year-legal-logical-english-01-013', section: 'English', topic: 'Reading Comprehension: Main Idea', difficulty: 'easy', question: 'Passage: "A neighbourhood association started a tool-lending library where residents can borrow items like drills, ladders, and pressure washers for a small refundable deposit instead of buying tools they might use only once or twice a year. Members return the tools within a week, and volunteers inspect each item before it goes back on the shelf. The association reports that the library has saved members a significant amount of money collectively, though a few popular tools are often booked weeks in advance, leading some members to suggest the association purchase duplicate copies of the most requested items." Which of the following best captures the main idea of the passage?', options: ['How a tool-lending library helps residents save money while facing high demand for popular items', 'Why residents should always buy their own tools', 'The history of neighbourhood associations', 'How to repair a pressure washer'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage describes both the money-saving benefit and the high-demand challenge of the tool-lending library.', source },
  { id: 'mh-cet-law-3-year-legal-logical-english-01-014', section: 'English', topic: 'Reading Comprehension: Vocabulary in Context', difficulty: 'easy', question: 'In the passage above, the word "refundable" is closest in meaning to:', options: ['Non-negotiable', 'Returnable', 'Extremely expensive', 'Permanently lost'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'A "refundable" deposit is one that can be returned, closest in meaning to "Returnable".', source },
  { id: 'mh-cet-law-3-year-legal-logical-english-01-015', section: 'English', topic: 'Reading Comprehension: Inference', difficulty: 'medium', question: 'It can be inferred from the passage above that the association\'s volunteers:', options: ['Charge a rental fee for every tool', 'Only lend tools to new members', 'Check the condition of tools before they are lent out again', 'Repair all tools free of charge for members'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage states volunteers "inspect each item before it goes back on the shelf," implying a condition check.', source },
  { id: 'mh-cet-law-3-year-legal-logical-english-01-016', section: 'English', topic: 'Reading Comprehension: Detail', difficulty: 'easy', question: 'According to the passage above, within how long must borrowed tools be returned?', options: ['One day', 'Two weeks', 'One month', 'One week'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage states "Members return the tools within a week."', source },
  { id: 'mh-cet-law-3-year-legal-logical-english-01-017', section: 'English', topic: 'Reading Comprehension: Tone', difficulty: 'medium', question: 'The overall tone of the passage above toward the tool-lending library is best described as:', options: ['Positive, while noting a practical limitation', 'Entirely negative', 'Strictly neutral and statistical', 'Sarcastic and dismissive'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage highlights the money-saving benefit while also noting the practical limitation of high demand for popular tools.', source },
  { id: 'mh-cet-law-3-year-legal-logical-english-01-018', section: 'English', topic: 'Reading Comprehension: Unsupported Statements', difficulty: 'medium', question: 'Which of the following is NOT supported by the passage above?', options: ['Members pay a small refundable deposit to borrow tools', 'The association already owns duplicate copies of every popular tool', 'Some popular tools are booked weeks in advance', 'Volunteers inspect tools before relending them'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage says members "suggest the association purchase duplicate copies," implying the association does not yet own them.', source },
  { id: 'mh-cet-law-3-year-legal-logical-english-01-019', section: 'English', topic: 'Prepositions', difficulty: 'easy', question: 'Fill in the blank: The committee is responsible ___ reviewing all applications.', options: ['to', 'with', 'for', 'at'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The correct idiomatic preposition is "for": responsible for reviewing.', source },
  { id: 'mh-cet-law-3-year-legal-logical-english-01-020', section: 'English', topic: 'Antonyms', difficulty: 'easy', question: 'Choose the word opposite in meaning to "Vigilant".', options: ['Watchful', 'Alert', 'Observant', 'Negligent'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: '"Vigilant" means watchful and alert; its opposite is "Negligent".', source },
  { id: 'mh-cet-law-3-year-legal-logical-english-01-021', section: 'English', topic: 'Spelling', difficulty: 'easy', question: 'Choose the correctly spelled word.', options: ['Rhythm', 'Rythm', 'Rhythem', 'Rythem'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The correct spelling is "Rhythm".', source },
  { id: 'mh-cet-law-3-year-legal-logical-english-01-022', section: 'English', topic: 'Idioms and Phrases', difficulty: 'medium', question: 'What does the idiom "to throw in the towel" mean?', options: ['To win a competition', 'To give up on something', 'To clean a room', 'To start a new project'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: '"To throw in the towel" means to give up or admit defeat.', source },
];
