import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'Original MH CET Law (5-Year LLB) practice questions in the official 4-option multiple-choice format, covering Legal Aptitude and Legal Reasoning, Logical and Analytical Reasoning, English Language, and Mathematics Aptitude from the Maharashtra Common Entrance Test syllabus. Legal Aptitude and Legal Reasoning questions state their own principle and facts, matching the official syllabus description that the section tests application of legal propositions to facts.',
  url: 'https://cetcell.mahacet.org/',
  checkedOn: '16 August 2026',
};

// The 28 September 2026 batch, which took this bank from 24 questions to 48:
// exactly half of each official section this mock builds, so Legal Aptitude
// and Legal Reasoning, Logical and Analytical Reasoning and English Language
// all clear the ten-question floor for indexing without the mock misstating
// the shape of the paper. Mathematics Aptitude stays at 4 and stays below the
// floor, and always will: the official section is 8 questions, so no faithful
// scale reaches 10. Separate source entry because these were written and
// answer-checked on that date. Every Legal Aptitude question added here states
// its own principle and facts, so it is answerable from the passage and turns
// on no statute or decided case, neither of which this environment can verify
// and both of which date.
const addedSource = { ...source, checkedOn: '28 September 2026' };

export const MH_CET_LAW_LEGAL_LOGICAL_ENGLISH_MATHEMATICS_1: Question[] = [
  // Legal Aptitude and Legal Reasoning
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-001', section: 'Legal Aptitude and Legal Reasoning', topic: 'Vicarious Liability', difficulty: 'medium', question: 'Principle: An employer is vicariously liable for the wrongful acts of an employee if those acts are committed in the course of and within the scope of the employee\'s employment. An employer is not liable for acts the employee commits that are entirely outside the scope of their employment, for purely personal reasons unconnected to their job. Facts: A delivery driver, while making deliveries for his employer, negligently runs a red light and injures a pedestrian. Applying the principle, is the employer vicariously liable for the pedestrian\'s injury?', options: ['Yes, because the driver was acting within the scope of his employment while making deliveries', 'No, because only the driver personally caused the accident', 'No, because employers are never liable for employees\' negligence', 'Yes, but only if the employer specifically instructed the driver to speed'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The driver was performing his assigned delivery duties when the accident occurred, placing the act within the scope of employment.', source },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-002', section: 'Legal Aptitude and Legal Reasoning', topic: 'Vicarious Liability', difficulty: 'hard', question: 'Using the same principle above. Facts: A security guard, during his shift, leaves his post without permission to settle a personal dispute at a nearby shop and assaults someone there. Applying the principle, is the guard\'s employer vicariously liable for the assault?', options: ['Yes, because the assault happened during the guard\'s work shift', 'No, because the assault was a personal act entirely outside the scope of the guard\'s employment duties', 'Yes, because security guards are always considered on duty', 'No, because the guard should not have been hired in the first place'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Leaving his post to settle a personal dispute is unconnected to his job duties, so the act falls outside the scope of employment.', source },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-003', section: 'Legal Aptitude and Legal Reasoning', topic: 'Vicarious Liability', difficulty: 'medium', question: 'Using the same principle above. Facts: A shop assistant, while restocking shelves as instructed, accidentally knocks a heavy box onto a customer\'s foot, injuring them. Applying the principle, is the shop owner vicariously liable?', options: ['No, because the assistant should have been more careful', 'No, because accidents are never anyone\'s legal responsibility', 'Yes, because restocking shelves was part of the assistant\'s assigned job duties when the injury occurred', 'Yes, but only if the shop owner witnessed the accident'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The assistant was performing an assigned job duty (restocking shelves) at the time of the accident, placing it within the scope of employment.', source },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-004', section: 'Legal Aptitude and Legal Reasoning', topic: 'Vicarious Liability', difficulty: 'hard', question: 'Using the same principle above. Facts: An office employee, after finishing work for the day and while driving home in his own car for entirely personal reasons, gets into an accident that injures another driver. Applying the principle, is the employee\'s office employer vicariously liable?', options: ['Yes, because the employee works for the office', 'Yes, because the accident happened on the same day as work', 'No, because car accidents are never anyone\'s fault', 'No, because commuting home after work in a personal capacity is outside the scope of employment'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Commuting home after finishing work, in a personal vehicle for personal reasons, falls outside the scope of employment.', source },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-005', section: 'Legal Aptitude and Legal Reasoning', topic: 'Vicarious Liability', difficulty: 'hard', question: 'Using the same principle above. Facts: A courier company\'s employee, instructed to hand-deliver a package to a client\'s office, takes a shortcut through a restricted area against explicit instructions and damages a barrier while doing so. Applying the principle, is the courier company vicariously liable for the barrier damage?', options: ['Yes, because the employee was still performing his assigned delivery task, even though he deviated from the instructed route', 'No, because the employee disobeyed instructions, so the act falls entirely outside employment', 'No, because barriers are not covered by vicarious liability', 'Yes, but only if the client authorised the shortcut'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Even though the employee deviated from the instructed route, he was still performing the core task of delivering the package, so the act remains within the scope of employment.', source },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-006', section: 'Legal Aptitude and Legal Reasoning', topic: 'Vicarious Liability', difficulty: 'medium', question: 'Using the same principle above. Facts: A factory worker, angry about an unrelated personal matter with a colleague, physically attacks that colleague during a lunch break, unconnected to any work task. Applying the principle, is the factory owner vicariously liable for the attack?', options: ['Yes, because the attack happened on factory premises', 'No, because the attack arose from a personal grievance unconnected to any work task', 'Yes, because all incidents during work hours are covered', 'No, because factories are never liable for workplace incidents'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The attack arose from a purely personal grievance, unconnected to the worker\'s job duties, so it falls outside the scope of employment.', source },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-007', section: 'Legal Aptitude and Legal Reasoning', topic: 'Vicarious Liability', difficulty: 'medium', question: 'Using the same principle above. Facts: A taxi driver employed by a cab company picks up a passenger as part of his normal duties, but during the ride, drives carelessly and causes an accident that injures the passenger. Applying the principle, is the cab company vicariously liable?', options: ['No, because careless driving is always the driver\'s personal fault alone', 'No, because passengers assume all risk when hiring a taxi', 'Yes, because driving passengers is squarely within the driver\'s employment duties, even if performed carelessly', 'Yes, but only if the passenger paid in advance'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Driving passengers is the driver\'s core job duty, so an accident during a ride falls within the scope of employment even if caused by carelessness.', source },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-008', section: 'Legal Aptitude and Legal Reasoning', topic: 'Vicarious Liability', difficulty: 'hard', question: 'Using the same principle above. Facts: A bank teller, following the bank\'s official cash-handling procedure, mistakenly gives a customer less change than owed due to a genuine counting error. Applying the principle, if this error causes the customer a loss, is the bank vicariously liable?', options: ['No, because counting errors are always the teller\'s personal fault', 'No, because banks are never responsible for teller mistakes', 'Yes, but only if the teller intended to shortchange the customer', 'Yes, because the teller was performing an authorised job duty, even though a mistake occurred while doing it'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The teller was performing an authorised job duty (cash handling) when the genuine error occurred, placing it within the scope of employment.', source },
  // Added 28 September 2026
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-025', section: 'Legal Aptitude and Legal Reasoning', topic: 'Trespass to Land', difficulty: 'medium', question: 'Principle: Entering another person’s land without lawful justification or permission is trespass, and it is actionable even if no damage is caused. Facts: While chasing a stray dog, Vikram ran across Anita’s fenced garden, causing no harm to anything, and left within a minute. Anita sued him for trespass. Will she succeed?', options: ['No, because no damage was caused.', 'Yes, because entry without permission is itself trespass.', 'No, because he entered for a good reason.', 'Yes, but only if the dog damaged the garden.'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The principle makes the entry itself actionable and says in terms that damage is not required, so the brevity and harmlessness of the entry do not save Vikram.', source: addedSource },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-026', section: 'Legal Aptitude and Legal Reasoning', topic: 'Defamation', difficulty: 'medium', question: 'Principle: A statement is defamatory only if it lowers the reputation of a person in the estimation of others, and it must be published, meaning communicated to at least one person other than the person defamed. Facts: In a sealed letter addressed only to Ramesh, Sunil called him a fraud. Ramesh opened it alone. Can Ramesh sue for defamation?', options: ['Yes, because the accusation was false and damaging.', 'Yes, because a letter is a permanent form.', 'No, because the statement was never communicated to a third person.', 'No, because a sealed letter is always privileged.'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Publication to someone other than the person defamed is an element of the wrong, and nobody but Ramesh ever read the letter.', source: addedSource },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-027', section: 'Legal Aptitude and Legal Reasoning', topic: 'Private Nuisance', difficulty: 'medium', question: 'Principle: A person commits private nuisance by unreasonably and substantially interfering with another’s use or enjoyment of land. An interference that is trivial or occasional is not actionable. Facts: A neighbour’s generator ran every night from 10 pm to 5 am for seven months, and the noise kept the family next door awake. They sued. Will they succeed?', options: ['Yes, because the interference was substantial and continuous.', 'No, because a generator is a lawful appliance.', 'No, because noise is never a nuisance.', 'Yes, because any noise after 10 pm is unlawful.'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Seven months of nightly noise that prevents sleep is neither trivial nor occasional, so it meets the standard the principle sets.', source: addedSource },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-028', section: 'Legal Aptitude and Legal Reasoning', topic: 'Bailment', difficulty: 'medium', question: 'Principle: A bailee who receives goods for safe keeping must take as much care of them as an ordinary prudent person would take of their own goods of the same kind. A bailee who does so is not liable for loss. Facts: A cloakroom attendant stored a traveller’s bag in a locked room, as he did with all bags. Thieves broke the lock at night and took several bags. Is the attendant liable?', options: ['No, because he took the care an ordinary prudent person would.', 'Yes, because the bag was lost while in his keeping.', 'Yes, because he should have hired a night guard.', 'No, because cloakrooms never accept liability.'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The principle measures the bailee by the care taken, not by the outcome, and locking the room is what a prudent person would do with their own goods.', source: addedSource },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-029', section: 'Legal Aptitude and Legal Reasoning', topic: 'Law of Agency', difficulty: 'medium', question: 'Principle: Acts done by an agent within the authority given by the principal bind the principal. Acts beyond that authority do not bind the principal unless the principal ratifies them. Facts: Leela authorised her agent to sell her car for not less than ₹3 lakh. The agent sold it for ₹2.5 lakh. Leela refused to hand over the car. Is she bound by the sale?', options: ['Yes, because the agent acted in her name.', 'Yes, because the buyer paid in good faith.', 'No, because agents can never sell cars.', 'No, because the sale was outside the authority she gave.'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The authority carried a floor of ₹3 lakh, so a sale below it falls outside the authority and does not bind Leela unless she chooses to ratify it.', source: addedSource },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-030', section: 'Legal Aptitude and Legal Reasoning', topic: 'Contributory Negligence', difficulty: 'hard', question: 'Principle: Where an injured person’s own want of care contributed to the injury, the compensation payable is reduced in proportion to that person’s share of the fault. Facts: A motorcyclist riding without a helmet was hit by a car driven through a red light and suffered head injuries. A court found the driver mainly at fault but held that the missing helmet worsened the injury. What follows?', options: ['The motorcyclist recovers nothing.', 'The motorcyclist recovers in full, since the driver jumped the signal.', 'The driver recovers from the motorcyclist.', 'The motorcyclist’s compensation is reduced to reflect his share of the fault.'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The principle does not bar the claim; it scales it down by the injured party’s share of the fault, which is what the finding about the helmet establishes.', source: addedSource },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-031', section: 'Legal Aptitude and Legal Reasoning', topic: 'Strict Liability', difficulty: 'hard', question: 'Principle: A person who brings onto their land something likely to cause harm if it escapes keeps it at their peril, and is liable for the damage it causes on escaping, whether or not they were careless. Facts: A factory stored industrial acid in tanks that met every safety standard. An unforeseen tank failure let acid seep into a neighbouring farm and ruin the crop. The factory proved it had taken all reasonable care. Is it liable?', options: ['No, because it took all reasonable care.', 'Yes, because liability here does not depend on carelessness.', 'No, because the failure was unforeseen.', 'Yes, but only for half the loss.'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The principle attaches liability to the escape itself. Proof of care is a defence to negligence, not to a rule that applies whether or not the keeper was careless.', source: addedSource },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-032', section: 'Legal Aptitude and Legal Reasoning', topic: 'Coercion', difficulty: 'medium', question: 'Principle: Consent is said to be caused by coercion when it is obtained by committing or threatening to commit an act forbidden by law, and an agreement whose consent was so caused is voidable at the option of the party coerced. Facts: Threatening to harm his son, a moneylender made Prakash sign a sale deed for his shop. Prakash signed and later sought to set the deed aside. Can he?', options: ['No, because he signed the deed himself.', 'No, because the threat was to a third person, not to him.', 'Yes, because his consent was caused by coercion.', 'Yes, but only if the threat was made in writing.'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'A threat to commit an act forbidden by law is coercion under the principle, and it makes the agreement voidable at the option of the coerced party, which is Prakash.', source: addedSource },
  // Logical and Analytical Reasoning
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-009', section: 'Logical and Analytical Reasoning', topic: 'Set Relations', difficulty: 'hard', question: 'In a group of 60 people, 25 like tea, 20 like coffee, and 15 like juice. 8 like both tea and coffee, 5 like both coffee and juice, 6 like both tea and juice, and 3 like all three drinks. How many people like none of the three drinks?', options: ['16', '14', '20', '10'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'People liking at least one drink = 25+20+15 − 8−5−6 + 3 = 44. People liking none = 60 − 44 = 16.', source },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-010', section: 'Logical and Analytical Reasoning', topic: 'Ages', difficulty: 'medium', question: 'The ratio of the present ages of A and B is 3:5. After 6 years, the ratio of their ages will be 2:3. Find A\'s present age.', options: ['15', '18', '21', '24'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Let A = 3x and B = 5x. (3x+6)/(5x+6) = 2/3, giving 9x+18 = 10x+12, so x = 6. A\'s present age = 3x = 18.', source },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-011', section: 'Logical and Analytical Reasoning', topic: 'Letter Series', difficulty: 'medium', question: 'Find the next term in the series: C, D, F, I, M, ?', options: ['P', 'Q', 'R', 'S'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The gaps between letters increase by 1 each time (+1, +2, +3, +4), so the next gap is +5: M (13) + 5 = 18, which is R.', source },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-012', section: 'Logical and Analytical Reasoning', topic: 'Inequalities', difficulty: 'easy', question: 'If P > Q, Q ≥ R, and R > S, which of the following must be true?', options: ['S > Q', 'Q > P', 'R > P', 'P > S'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Chaining the relations: P > Q ≥ R > S, so P must be greater than S.', source },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-013', section: 'Logical and Analytical Reasoning', topic: 'Syllogism', difficulty: 'medium', question: 'Statements: All violinists are musicians. No musician is unemployed. Conclusion I: No violinist is unemployed. Conclusion II: All musicians are violinists. Which conclusion(s) logically follow from the statements?', options: ['Only conclusion I follows', 'Only conclusion II follows', 'Both conclusions follow', 'Neither conclusion follows'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Since all violinists are musicians and no musician is unemployed, no violinist can be unemployed (conclusion I). Conclusion II reverses the first statement, which does not logically follow.', source },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-014', section: 'Logical and Analytical Reasoning', topic: 'Statement and Assumption', difficulty: 'medium', question: 'Statement: The library announced it will fine members ₹5 per day for overdue books to encourage timely returns. Which of the following is an assumption implicit in this statement?', options: ['The library has run out of books to lend', 'Members are motivated to avoid financial penalties', 'All members currently return books on time', 'The fine amount will increase every year'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'For a fine to encourage timely returns, the library must assume members are motivated to avoid financial penalties.', source },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-015', section: 'Logical and Analytical Reasoning', topic: 'Circular Arrangement', difficulty: 'hard', question: 'Six friends, J, K, L, M, N, and O, sit around a circular table at six positions numbered 1 to 6 clockwise, facing the centre. K sits third to the right of J. L sits immediately to the left of K. M sits immediately to the right of J. N sits second to the left of M. Where does O sit relative to J?', options: ['Immediately to the right of J', 'Immediately to the left of J', 'Second to the left of J', 'Third to the right of J'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Placing J at position 1: K is third to the right at position 4, L is immediately left of K at position 3, M is immediately right of J at position 2, and N is second to the left of M at position 6. The only remaining position, 5, belongs to O, which is second to the left of J.', source },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-016', section: 'Logical and Analytical Reasoning', topic: 'Classification', difficulty: 'medium', question: 'Which of the following numbers does not belong with the others: 16, 27, 64, 125, 216?', options: ['27', '64', '125', '16'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: '27, 64, 125, and 216 are perfect cubes (3³, 4³, 5³, 6³), while 16 is not a perfect cube.', source },
  // Added 28 September 2026
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-033', section: 'Logical and Analytical Reasoning', topic: 'Syllogism', difficulty: 'medium', question: 'Statements: All advocates are graduates. No graduate is illiterate. Which conclusion follows?', options: ['Some advocates are illiterate.', 'No advocate is illiterate.', 'All graduates are advocates.', 'Some graduates are illiterate.'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Every advocate is a graduate, and no graduate is illiterate, so no advocate can be illiterate.', source: addedSource },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-034', section: 'Logical and Analytical Reasoning', topic: 'Seating Arrangement', difficulty: 'medium', question: 'Six people sit in a row facing north. C is third from the left. A is immediately left of C. F is at the right end. B is immediately right of C. D is not at either end. Who sits at the left end?', options: ['A', 'D', 'E', 'B'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'C takes seat three and A seat two, so seat one is left for E once D is barred from the ends and B takes seat four.', source: addedSource },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-035', section: 'Logical and Analytical Reasoning', topic: 'Blood Relations', difficulty: 'medium', question: 'Introducing a woman, Rakesh said, "She is the wife of the only son of my mother." How is the woman related to Rakesh?', options: ['Sister', 'Wife', 'Mother', 'Aunt'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The only son of Rakesh’s mother is Rakesh himself, so the woman is his wife.', source: addedSource },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-036', section: 'Logical and Analytical Reasoning', topic: 'Coding-Decoding', difficulty: 'medium', question: 'If COURT is written as DPVSU, how is JUDGE written in the same code?', options: ['KVEHF', 'IVCHD', 'KWEIF', 'KVEIF'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Each letter moves one place forward, so J, U, D, G, E become K, V, E, H, F.', source: addedSource },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-037', section: 'Logical and Analytical Reasoning', topic: 'Number Series', difficulty: 'medium', question: 'Complete the series: 3, 8, 15, 24, 35, ?', options: ['45', '46', '47', '48'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Each term is one less than a square: 2², 3², 4², 5² and 6² less one, so the next is 7² − 1 = 48.', source: addedSource },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-038', section: 'Logical and Analytical Reasoning', topic: 'Direction Sense', difficulty: 'medium', question: 'A man walks 5 km south, turns left and walks 8 km, then turns left again and walks 5 km. In which direction is he from his starting point?', options: ['North', 'West', 'South', 'East'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The two southward and northward legs of 5 km cancel, leaving him 8 km east of where he began.', source: addedSource },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-039', section: 'Logical and Analytical Reasoning', topic: 'Statement and Assumption', difficulty: 'medium', question: 'Statement: A law college advertises, "Apply before 30 June to be considered for a scholarship." Which assumption is implicit?', options: ['Every applicant will receive a scholarship.', 'Applications received after 30 June will be considered for scholarships too.', 'Some applicants are able to apply before 30 June.', 'The college has no other source of funding.'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'A deadline is worth announcing only if some readers can meet it. The other options either overstate the offer or contradict it.', source: addedSource },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-040', section: 'Logical and Analytical Reasoning', topic: 'Odd One Out', difficulty: 'easy', question: 'Which one does not belong with the others?', options: ['Plaintiff', 'Defendant', 'Witness', 'Verdict'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The first three name people taking part in a trial. A verdict is the decision reached.', source: addedSource },
  // English Language
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-017', section: 'English Language', topic: 'Reading Comprehension: Main Idea', difficulty: 'easy', question: 'Passage: "A community centre in a suburban neighbourhood began hosting a monthly \'repair cafe,\' where volunteers with skills in electronics, sewing, and woodworking help residents fix broken household items instead of throwing them away. Visitors bring in anything from torn jackets to malfunctioning toasters, and volunteers guide them through the repair process rather than simply fixing the item for them, so that visitors leave having learned a new skill. Organisers report that the event has kept hundreds of items out of landfills over the past year, though they admit some repairs, especially of complex electronics, are turned away because no volunteer has the right expertise that month." Which of the following best captures the main idea of the passage?', options: ['How a community repair event teaches skills while reducing waste', 'Why household items break down so often', 'The history of repair cafes worldwide', 'How to start a woodworking business'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage describes both the skill-teaching approach and the waste-reduction outcome of the repair cafe.', source },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-018', section: 'English Language', topic: 'Reading Comprehension: Vocabulary in Context', difficulty: 'easy', question: 'In the passage above, the word "malfunctioning" is closest in meaning to:', options: ['Brand new', 'Not working properly', 'Extremely valuable', 'Recently purchased'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: '"Malfunctioning" describes something that is not working properly, as in a malfunctioning toaster.', source },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-019', section: 'English Language', topic: 'Reading Comprehension: Inference', difficulty: 'medium', question: 'It can be inferred from the passage above that repair cafe volunteers:', options: ['Charge a fee for every repair', 'Only accept electronic items', 'Prioritise teaching visitors over simply completing repairs for them', 'Are professional repair technicians paid by the centre'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage states volunteers "guide them through the repair process rather than simply fixing the item for them," implying a focus on teaching.', source },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-020', section: 'English Language', topic: 'Reading Comprehension: Detail', difficulty: 'easy', question: 'According to the passage above, how often is the repair cafe held?', options: ['Weekly', 'Daily', 'Yearly', 'Monthly'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage states the community centre "began hosting a monthly \'repair cafe.\'"', source },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-021', section: 'English Language', topic: 'Reading Comprehension: Tone', difficulty: 'medium', question: 'The overall tone of the passage above toward the repair cafe initiative is best described as:', options: ['Appreciative, while acknowledging a limitation', 'Harshly critical throughout', 'Completely neutral and factual only', 'Dismissive of its impact'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage highlights the positive impact (keeping items out of landfills) while also noting the limitation that some complex repairs are turned away.', source },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-022', section: 'English Language', topic: 'Reading Comprehension: Unsupported Statements', difficulty: 'medium', question: 'Which of the following is NOT supported by the passage above?', options: ['Volunteers have skills in electronics, sewing, and woodworking', 'Every item brought to the repair cafe is successfully repaired', 'The event has kept hundreds of items out of landfills', 'Some complex electronics repairs are turned away'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage explicitly states some repairs "are turned away because no volunteer has the right expertise that month," contradicting this statement.', source },
  // Added 28 September 2026
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-041', section: 'English Language', topic: 'Reading Comprehension: Main Idea', difficulty: 'medium', question: 'Passage: "For decades the village kept its stepwell covered, treating it as a hazard rather than a structure. The well had supplied drinking water until a piped scheme arrived in the 1980s, after which it filled with silt and was fenced off. When a conservation trust offered to restore it, the panchayat split. One group argued the money would be better spent on the water pipeline, which still runs dry for two months each summer. The other pointed out that the stepwell had held water through droughts that emptied every borewell in the district, and that a structure which worked for four centuries deserved more than a fence. The trust eventually funded both, which nobody had proposed." Which of the following best states what the passage is about?', options: ['A dispute over restoring a stepwell that ended in an unproposed compromise.', 'The failure of piped water schemes in rural India.', 'The engineering methods used to build stepwells.', 'A panchayat election fought over water.'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage sets out a split over how to spend the trust’s money and closes with the trust funding both, which nobody had suggested.', source: addedSource },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-042', section: 'English Language', topic: 'Reading Comprehension: Detail', difficulty: 'easy', question: 'According to the passage above, why was the stepwell fenced off?', options: ['It had been damaged in a drought.', 'It filled with silt after piped water arrived.', 'The conservation trust asked for it.', 'The panchayat could not agree on its use.'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage says the well filled with silt after the piped scheme arrived in the 1980s and was then fenced off.', source: addedSource },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-043', section: 'English Language', topic: 'Reading Comprehension: Inference', difficulty: 'medium', question: 'It can be inferred from the passage above that the piped scheme:', options: ['Has replaced the stepwell entirely.', 'Was funded by the conservation trust.', 'Is unreliable in the hottest part of the year.', 'Was built before the stepwell.'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage says the pipeline still runs dry for two months each summer, which is a statement about its reliability at that season.', source: addedSource },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-044', section: 'English Language', topic: 'Reading Comprehension: Vocabulary in Context', difficulty: 'easy', question: 'In the passage above, the word "split" is closest in meaning to:', options: ['Divided in opinion', 'Broke physically', 'Departed quickly', 'Shared equally'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The sentence goes on to describe two groups arguing for different things, so "split" means divided in opinion.', source: addedSource },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-045', section: 'English Language', topic: 'Reading Comprehension: Author’s Attitude', difficulty: 'medium', question: 'The final sentence, "The trust eventually funded both, which nobody had proposed," suggests that the author finds the outcome:', options: ['Predictable', 'Unjust', 'Disappointing', 'Mildly ironic'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Noting that the solution adopted was one neither side had put forward points to the irony of the dispute, not to injustice or disappointment.', source: addedSource },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-046', section: 'English Language', topic: 'Reading Comprehension: Structure', difficulty: 'medium', question: 'The passage presents the disagreement by:', options: ['Giving each side’s argument in turn.', 'Quoting the panchayat’s minutes.', 'Listing the costs of both options.', 'Describing the stepwell’s architecture.'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'One group’s argument about the pipeline is given first, then the other’s about droughts and the well’s four centuries of service.', source: addedSource },
  // Mathematics Aptitude
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-023', section: 'Mathematics Aptitude', topic: 'Ratio and Proportion', difficulty: 'easy', question: 'A sum of ₹6,000 is divided between two people in the ratio 2:3. Find the larger share.', options: ['₹2,400', '₹3,000', '₹3,600', '₹4,200'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Total parts = 2+3 = 5, so 1 part = ₹1,200. The larger share = 3 parts = 3 × ₹1,200 = ₹3,600.', source },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-024', section: 'Mathematics Aptitude', topic: 'Square Roots', difficulty: 'easy', question: 'Find the value of √225 + √144.', options: ['25', '26', '27', '28'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: '√225 = 15 and √144 = 12, so 15 + 12 = 27.', source },
  // Added 28 September 2026
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-047', section: 'Mathematics Aptitude', topic: 'Percentage', difficulty: 'easy', question: 'In an entrance test of 120 questions, a candidate answered 85% correctly. How many did the candidate get right?', options: ['96', '100', '108', '102'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: '85% of 120 = 0.85 × 120 = 102.', source: addedSource },
  { id: 'mh-cet-law-legal-logical-english-mathematics-01-048', section: 'Mathematics Aptitude', topic: 'Average', difficulty: 'medium', question: 'The average of five numbers is 28. If one number is removed, the average of the rest is 25. What was the number removed?', options: ['36', '40', '44', '32'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The five numbers total 140 and the remaining four total 100, so the number removed is 40.', source: addedSource },
];
