import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'NABARD Assistant Manager Grade A (RDBS) Recruitment 2025 official advertisement — Phase I, General Awareness section',
  url: 'https://www.nabard.org/auth/writereaddata/CareerNotices/0512255230Final Advertisement Grade A (RDBS, Legal, P&SS) 2025 (1).pdf',
  checkedOn: '24 August 2026',
};

export const NABARD_GRADE_A_PHASE_1_GENERAL_AWARENESS_2: Question[] = [
  { id: 'nabard-ga-p1-ga2-001', section: 'General Awareness', topic: 'Banking Institutions', difficulty: 'medium', question: 'NABARD was established based on the recommendations of which committee?', options: ['Shivaraman Committee (CRAFICARD)', 'Narasimham Committee', 'Rangarajan Committee', 'Khan Committee'], correctIndex: 0, explanation: 'NABARD was established following the recommendations of the Shivaraman Committee, formally the Committee to Review Arrangements for Institutional Credit for Agriculture and Rural Development (CRAFICARD).', source },
  { id: 'nabard-ga-p1-ga2-002', section: 'General Awareness', topic: 'Monetary Policy', difficulty: 'medium', question: 'The rate at which the Reserve Bank of India borrows short-term funds from commercial banks is called the:', options: ['Repo Rate', 'Reverse Repo Rate', 'Bank Rate', 'Marginal Standing Facility Rate'], correctIndex: 1, explanation: 'The Reverse Repo Rate is the rate at which the RBI borrows short-term funds from commercial banks, absorbing excess liquidity from the banking system.', source },
  { id: 'nabard-ga-p1-ga2-003', section: 'General Awareness', topic: 'Banking Regulation', difficulty: 'medium', question: 'The Lead Bank Scheme, under which a designated bank coordinates banking development in each district, was introduced following the recommendations of which committee?', options: ['Narasimham Committee', 'Khusro Committee', 'Gadgil Study Group / Nariman Committee', 'Chakravarty Committee'], correctIndex: 2, explanation: 'The Lead Bank Scheme was introduced in 1969 based on the recommendations of the Gadgil Study Group and the Nariman Committee.', source },
  { id: 'nabard-ga-p1-ga2-004', section: 'General Awareness', topic: 'Financial Terms', difficulty: 'medium', question: 'A loan account where the interest has remained overdue for more than 90 days is classified as a Non-Performing Asset; loans that are current or overdue for less than 90 days are classified as:', options: ['Doubtful Assets', 'Loss Assets', 'Sub-Standard Assets', 'Standard Assets'], correctIndex: 3, explanation: 'A loan that does not disclose any problem and does not carry more than normal risk is classified as a Standard Asset, distinct from an NPA.', source },
  { id: 'nabard-ga-p1-ga2-005', section: 'General Awareness', topic: 'Indian Polity', difficulty: 'medium', question: 'The Concurrent List of the Seventh Schedule of the Indian Constitution allows legislative authority to be exercised by:', options: ['Both the Union and State Governments', 'Only the Union Government', 'Only State Governments', 'Only local municipal bodies'], correctIndex: 0, explanation: 'The Concurrent List of the Seventh Schedule allows both the Union Parliament and State Legislatures to make laws on the subjects listed within it.', source },
  { id: 'nabard-ga-p1-ga2-006', section: 'General Awareness', topic: 'Banking Awareness', difficulty: 'medium', question: 'Small Finance Banks in India, unlike Payments Banks, are permitted to:', options: ['Issue currency notes', 'Extend loans and advances to small borrowers', 'Set the national repo rate', 'Operate as apex regulators'], correctIndex: 1, explanation: 'Small Finance Banks are permitted to extend loans and advances, primarily to underserved sections such as small businesses and farmers, unlike Payments Banks which cannot lend.', source },
  { id: 'nabard-ga-p1-ga2-007', section: 'General Awareness', topic: 'Financial Regulators', difficulty: 'medium', question: 'Which regulatory body oversees and regulates the insurance sector in India?', options: ['RBI', 'SEBI', 'IRDAI', 'PFRDA'], correctIndex: 2, explanation: 'The Insurance Regulatory and Development Authority of India (IRDAI) regulates and promotes the insurance industry in India.', source },
  { id: 'nabard-ga-p1-ga2-008', section: 'General Awareness', topic: 'Union Budget', difficulty: 'medium', question: 'The Economic Survey of India, typically presented a day before the Union Budget, is prepared under the guidance of the:', options: ['Reserve Bank Governor', 'Comptroller and Auditor General', 'Chief Justice of India', 'Chief Economic Adviser'], correctIndex: 3, explanation: 'The Economic Survey is prepared under the guidance of the Chief Economic Adviser to the Government of India, within the Ministry of Finance.', source },
  { id: 'nabard-ga-p1-ga2-009', section: 'General Awareness', topic: 'Banking Sector Reforms', difficulty: 'medium', question: 'The recommendation to set up the Board for Financial Supervision, aimed at strengthening banking supervision in India, came from which committee?', options: ['Narasimham Committee', 'Kelkar Committee', 'Tarapore Committee', 'Rajan Committee'], correctIndex: 0, explanation: 'The Narasimham Committee (1991) recommended setting up the Board for Financial Supervision to strengthen the RBI\'s supervisory function over banks.', source },
  { id: 'nabard-ga-p1-ga2-010', section: 'General Awareness', topic: 'Geography', difficulty: 'medium', question: 'Which Indian state is the largest producer of wheat, according to recent agricultural production data?', options: ['Punjab', 'Uttar Pradesh', 'Haryana', 'Madhya Pradesh'], correctIndex: 1, explanation: 'Uttar Pradesh is consistently the largest producer of wheat among Indian states by total production volume.', source },
  { id: 'nabard-ga-p1-ga2-011', section: 'General Awareness', topic: 'Deposit Insurance', difficulty: 'medium', question: 'The Deposit Insurance and Credit Guarantee Corporation (DICGC) is a wholly owned subsidiary of which institution?', options: ['Ministry of Finance', 'SEBI', 'Reserve Bank of India', 'NABARD'], correctIndex: 2, explanation: 'The DICGC is a wholly owned subsidiary of the Reserve Bank of India, established to provide deposit insurance and credit guarantee cover.', source },
  { id: 'nabard-ga-p1-ga2-012', section: 'General Awareness', topic: 'International Organisations', difficulty: 'medium', question: 'India is a founding member of which multilateral development bank, established by the BRICS nations and headquartered in Shanghai?', options: ['World Bank', 'International Monetary Fund', 'Asian Development Bank', 'New Development Bank (NDB)'], correctIndex: 3, explanation: 'India is a founding member of the New Development Bank (NDB), established by the BRICS nations and headquartered in Shanghai.', source },
  { id: 'nabard-ga-p1-ga2-013', section: 'General Awareness', topic: 'Government Schemes', difficulty: 'medium', question: 'The Pradhan Mantri Mudra Yojana (PMMY) primarily provides collateral-free loans up to what maximum limit to non-corporate, non-farm micro and small enterprises?', options: ['₹10 lakh', '₹5 lakh', '₹20 lakh', '₹25 lakh'], correctIndex: 0, explanation: 'PMMY provides collateral-free loans up to ₹10 lakh under three categories (Shishu, Kishor, Tarun) to non-corporate, non-farm micro and small enterprises.', source },
  { id: 'nabard-ga-p1-ga2-014', section: 'General Awareness', topic: 'Currency and Payments', difficulty: 'medium', question: 'The Aadhaar Enabled Payment System (AEPS), which allows banking transactions using biometric authentication, is operated using infrastructure developed by:', options: ['SEBI', 'National Payments Corporation of India (NPCI)', 'NABARD', 'IRDAI'], correctIndex: 1, explanation: 'The Aadhaar Enabled Payment System (AEPS) operates on infrastructure developed by the National Payments Corporation of India (NPCI).', source },
  { id: 'nabard-ga-p1-ga2-015', section: 'General Awareness', topic: 'Sports', difficulty: 'medium', question: 'The Arjuna Award, presented for outstanding achievement in sports, is conferred by which body?', options: ['Ministry of Education', 'Indian Olympic Association', 'Ministry of Youth Affairs and Sports', 'Sports Authority of India (independently)'], correctIndex: 2, explanation: 'The Arjuna Award is conferred by the Ministry of Youth Affairs and Sports, Government of India, for outstanding sporting achievement.', source },
  { id: 'nabard-ga-p1-ga2-016', section: 'General Awareness', topic: 'Currency', difficulty: 'medium', question: 'The Wholesale Price Index (WPI), used to track inflation at the wholesale level in India, is released by which ministry?', options: ['Ministry of Finance', 'Ministry of Statistics and Programme Implementation', 'Reserve Bank of India', 'Ministry of Commerce and Industry'], correctIndex: 3, explanation: 'The Wholesale Price Index (WPI) is compiled and released by the Office of the Economic Adviser under the Ministry of Commerce and Industry.', source },
  { id: 'nabard-ga-p1-ga2-017', section: 'General Awareness', topic: 'Space and Science', difficulty: 'medium', question: "India's Aditya-L1 mission, launched to study the Sun, was placed in orbit around which point in space?", options: ['Lagrange Point 1 (L1)', 'Geostationary orbit', 'The Moon\'s surface', 'Mars orbit'], correctIndex: 0, explanation: 'Aditya-L1 was placed in a halo orbit around the Sun-Earth Lagrange Point 1 (L1), enabling continuous observation of the Sun.', source },
  { id: 'nabard-ga-p1-ga2-018', section: 'General Awareness', topic: 'Government Institutions', difficulty: 'medium', question: 'Which institution is primarily responsible for conducting the quinquennial Agriculture Census in India?', options: ['National Statistical Office', 'Ministry of Agriculture and Farmers Welfare', 'NITI Aayog', 'Election Commission of India'], correctIndex: 1, explanation: 'The Agriculture Census is conducted by the Ministry of Agriculture and Farmers Welfare, typically once every five years.', source },
  { id: 'nabard-ga-p1-ga2-019', section: 'General Awareness', topic: 'Banking Awareness', difficulty: 'medium', question: 'Which of the following banks was formed after the merger of Andhra Bank and Corporation Bank with Union Bank of India in 2020?', options: ['State Bank of India', 'Punjab National Bank', 'Union Bank of India (merged entity)', 'Bank of Baroda'], correctIndex: 2, explanation: 'Andhra Bank and Corporation Bank were merged into Union Bank of India in April 2020 as part of the government\'s public sector bank consolidation.', source },
  { id: 'nabard-ga-p1-ga2-020', section: 'General Awareness', topic: 'Banking Institutions', difficulty: 'medium', question: "NABARD's initial share capital, at the time of its establishment, was contributed jointly by the Government of India and:", options: ['The World Bank', 'State Governments', 'Commercial banks', 'The Reserve Bank of India'], correctIndex: 3, explanation: "NABARD's initial share capital was contributed jointly by the Government of India and the Reserve Bank of India.", source },
];
