import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'NABARD Assistant Manager Grade A (RDBS) Recruitment 2025 official advertisement — Phase I, Computer Knowledge section',
  url: 'https://www.nabard.org/auth/writereaddata/CareerNotices/0512255230Final Advertisement Grade A (RDBS, Legal, P&SS) 2025 (1).pdf',
  checkedOn: '6 August 2026',
};

export const NABARD_GRADE_A_PHASE_1_COMPUTER_KNOWLEDGE_1: Question[] = [
  { id: 'nabard-ga-p1-ck-001', section: 'Computer Knowledge', topic: 'Networking', difficulty: 'medium', question: 'Which device connects multiple networks and routes data packets between them based on IP addresses?', options: ['Hub', 'Switch', 'Router', 'Repeater'], correctIndex: 2, explanation: 'A router forwards data packets between different networks by examining IP addresses and determining the best path.', source },
  { id: 'nabard-ga-p1-ck-002', section: 'Computer Knowledge', topic: 'Networking', difficulty: 'medium', question: 'What does the abbreviation "LAN" stand for?', options: ['Local Area Network', 'Long Area Network', 'Linked Area Network', 'Limited Access Network'], correctIndex: 0, explanation: 'LAN stands for Local Area Network, a network confined to a small geographic area such as an office or building.', source },
  { id: 'nabard-ga-p1-ck-003', section: 'Computer Knowledge', topic: 'Database Concepts', difficulty: 'medium', question: 'In a relational database, which key uniquely identifies each record in a table?', options: ['Primary key', 'Foreign key', 'Candidate key', 'Composite index'], correctIndex: 0, explanation: 'A primary key is a column or set of columns that uniquely identifies each row in a database table.', source },
  { id: 'nabard-ga-p1-ck-004', section: 'Computer Knowledge', topic: 'Database Concepts', difficulty: 'medium', question: 'Which language is primarily used to query and manage data in relational databases?', options: ['HTML', 'XML', 'CSS', 'SQL'], correctIndex: 3, explanation: 'SQL (Structured Query Language) is the standard language for querying and managing relational databases.', source },
  { id: 'nabard-ga-p1-ck-005', section: 'Computer Knowledge', topic: 'Number Systems', difficulty: 'medium', question: 'What is the binary equivalent of the decimal number 13?', options: ['1101', '1110', '1011', '1010'], correctIndex: 0, explanation: '13 in binary is 1101, since 8+4+0+1 = 13 (1×8 + 1×4 + 0×2 + 1×1).', source },
  { id: 'nabard-ga-p1-ck-006', section: 'Computer Knowledge', topic: 'Generations of Computers', difficulty: 'medium', question: 'Which generation of computers is primarily associated with the use of microprocessors?', options: ['First generation', 'Second generation', 'Third generation', 'Fourth generation'], correctIndex: 3, explanation: 'The fourth generation of computers (from the early 1970s onward) is defined by the use of microprocessors, which integrated the CPU onto a single chip.', source },
  { id: 'nabard-ga-p1-ck-007', section: 'Computer Knowledge', topic: 'Software Types', difficulty: 'easy', question: 'Which of the following is an example of system software?', options: ['Microsoft Word', 'Adobe Photoshop', 'Tally', 'Operating System'], correctIndex: 3, explanation: 'An Operating System is system software that manages hardware resources and provides a platform for application software to run.', source },
  { id: 'nabard-ga-p1-ck-008', section: 'Computer Knowledge', topic: 'Internet Fundamentals', difficulty: 'medium', question: 'What does "URL" stand for?', options: ['Uniform Resource Locator', 'Universal Reference Link', 'Unified Resource List', 'User Retrieval Language'], correctIndex: 0, explanation: 'URL stands for Uniform Resource Locator, the address used to locate a resource on the internet.', source },
  { id: 'nabard-ga-p1-ck-009', section: 'Computer Knowledge', topic: 'Internet Fundamentals', difficulty: 'medium', question: 'Which protocol is used to securely transfer data over the web, indicated by a padlock icon in the browser?', options: ['FTP', 'HTTP', 'HTTPS', 'SMTP'], correctIndex: 2, explanation: 'HTTPS (HyperText Transfer Protocol Secure) encrypts data transferred between a browser and a website, indicated by a padlock icon.', source },
  { id: 'nabard-ga-p1-ck-010', section: 'Computer Knowledge', topic: 'Digital Banking Technology', difficulty: 'medium', question: 'Which banking technology system enables a customer to access their account from any branch of the same bank, regardless of where the account was opened?', options: ['ATM network', 'Internet gateway', 'Point of Sale (POS)', 'Core Banking Solution (CBS)'], correctIndex: 3, explanation: 'Core Banking Solution (CBS) links all branches of a bank to a centralised system, allowing customers to transact from any branch.', source },
  { id: 'nabard-ga-p1-ck-011', section: 'Computer Knowledge', topic: 'Cybersecurity', difficulty: 'medium', question: 'A malicious program that disguises itself as legitimate software but performs harmful actions once installed is known as a:', options: ['Firewall', 'Cache', 'Cookie', 'Trojan horse'], correctIndex: 3, explanation: 'A Trojan horse disguises itself as legitimate or useful software while secretly performing malicious actions once installed.', source },
  { id: 'nabard-ga-p1-ck-012', section: 'Computer Knowledge', topic: 'Cybersecurity', difficulty: 'medium', question: 'What is the primary purpose of a firewall in a computer network?', options: ['To increase internet speed', 'To monitor and control incoming and outgoing network traffic based on security rules', 'To compress files for storage', 'To translate domain names into IP addresses'], correctIndex: 1, explanation: 'A firewall monitors and filters incoming and outgoing network traffic based on predetermined security rules, blocking unauthorised access.', source },
  { id: 'nabard-ga-p1-ck-013', section: 'Computer Knowledge', topic: 'MS Excel', difficulty: 'medium', question: 'Which Excel function adds up a range of numeric values in selected cells?', options: ['AVERAGE()', 'COUNT()', 'SUM()', 'MAX()'], correctIndex: 2, explanation: 'The SUM() function in Excel adds up all the numeric values in a specified range of cells.', source },
  { id: 'nabard-ga-p1-ck-014', section: 'Computer Knowledge', topic: 'MS Excel', difficulty: 'medium', question: 'In Microsoft Excel, what does the function VLOOKUP primarily perform?', options: ['Sorts data alphabetically', 'Searches for a value in the first column of a range and returns a value in the same row from another column', 'Formats cells based on conditions', 'Calculates the standard deviation of a dataset'], correctIndex: 1, explanation: 'VLOOKUP searches for a specified value in the first column of a table and returns a corresponding value from another column in the same row.', source },
  { id: 'nabard-ga-p1-ck-015', section: 'Computer Knowledge', topic: 'Computer Memory', difficulty: 'easy', question: 'Which type of computer memory is non-volatile and retains its content even when power is switched off?', options: ['RAM', 'Cache memory', 'ROM', 'Register'], correctIndex: 2, explanation: 'ROM (Read-Only Memory) is non-volatile, meaning it retains stored data even without power.', source },
  { id: 'nabard-ga-p1-ck-016', section: 'Computer Knowledge', topic: 'Data Storage Units', difficulty: 'easy', question: 'Arrange the following storage units in increasing order of size: Megabyte, Kilobyte, Gigabyte, Byte.', options: ['Byte, Kilobyte, Megabyte, Gigabyte', 'Kilobyte, Byte, Gigabyte, Megabyte', 'Gigabyte, Megabyte, Kilobyte, Byte', 'Byte, Megabyte, Kilobyte, Gigabyte'], correctIndex: 0, explanation: 'In increasing order of size: Byte < Kilobyte < Megabyte < Gigabyte, each roughly 1,024 times larger than the previous unit.', source },
  { id: 'nabard-ga-p1-ck-017', section: 'Computer Knowledge', topic: 'Email Fundamentals', difficulty: 'medium', question: 'In an email, what is the purpose of the "Bcc" field?', options: ['To mark the email as urgent', 'To send a copy visible to all recipients', 'To send a hidden copy without other recipients seeing that address', 'To attach a file automatically'], correctIndex: 2, explanation: '"Bcc" (blind carbon copy) sends a copy of the email to an address without other recipients being able to see that it was included.', source },
  { id: 'nabard-ga-p1-ck-018', section: 'Computer Knowledge', topic: 'Operating Systems', difficulty: 'medium', question: 'What is the primary function of an operating system\'s "kernel"?', options: ['Displaying the graphical user interface', 'Managing core system resources such as memory and the CPU', 'Running web browsers', 'Formatting documents'], correctIndex: 1, explanation: 'The kernel is the core component of an operating system that manages fundamental resources like the CPU, memory, and hardware communication.', source },
  { id: 'nabard-ga-p1-ck-019', section: 'Computer Knowledge', topic: 'Digital Payments Technology', difficulty: 'medium', question: 'Which of the following enables instant, round-the-clock interbank electronic fund transfer in India, unlike NEFT which is processed in batches?', options: ['RTGS', 'IMPS', 'Demand Draft', 'Cheque Truncation System'], correctIndex: 1, explanation: 'IMPS (Immediate Payment Service) enables instant, 24x7 interbank fund transfers, unlike batch-processed systems.', source },
  { id: 'nabard-ga-p1-ck-020', section: 'Computer Knowledge', topic: 'Computer Viruses', difficulty: 'medium', question: 'A computer program that replicates itself and spreads to other computers without needing to attach itself to another program is called a:', options: ['Virus', 'Worm', 'Spyware', 'Adware'], correctIndex: 1, explanation: 'A worm is a standalone malicious program that self-replicates and spreads across networks without needing to attach to a host program, unlike a virus.', source },
];
