import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'NABARD Assistant Manager Grade A (RDBS) Recruitment 2025 official advertisement — Phase I, General Awareness section',
  url: 'https://www.nabard.org/auth/writereaddata/CareerNotices/0512255230Final Advertisement Grade A (RDBS, Legal, P&SS) 2025 (1).pdf',
  checkedOn: '6 August 2026',
};

export const NABARD_GRADE_A_PHASE_1_GENERAL_AWARENESS_1: Question[] = [
  { id: 'nabard-ga-p1-ga-001', section: 'General Awareness', topic: 'Banking Institutions', difficulty: 'medium', question: 'In which year was NABARD established as India\'s apex development bank for agriculture and rural development?', options: ['1982', '1975', '1990', '1995'], correctIndex: 0, explanation: 'NABARD was established on 12 July 1982, based on the recommendations of the Shivaraman Committee (CRAFICARD).', source },
  { id: 'nabard-ga-p1-ga-002', section: 'General Awareness', topic: 'Banking Institutions', difficulty: 'medium', question: 'Where is the headquarters of NABARD located?', options: ['New Delhi', 'Nagpur', 'Pune', 'Mumbai'], correctIndex: 3, explanation: 'NABARD\'s head office is located in Mumbai, Maharashtra.', source },
  { id: 'nabard-ga-p1-ga-003', section: 'General Awareness', topic: 'Monetary Policy', difficulty: 'medium', question: 'The rate at which the Reserve Bank of India lends short-term funds to commercial banks against government securities is called the:', options: ['Reverse Repo Rate', 'Bank Rate', 'Marginal Standing Facility Rate', 'Repo Rate'], correctIndex: 3, explanation: 'The Repo Rate is the rate at which the RBI lends short-term funds to commercial banks against government securities.', source },
  { id: 'nabard-ga-p1-ga-004', section: 'General Awareness', topic: 'Banking Regulation', difficulty: 'medium', question: 'Which committee\'s recommendations led to the establishment of Regional Rural Banks in India in 1975?', options: ['Narayanan Committee', 'Narasimham Committee', 'Khusro Committee', 'Chakravarty Committee'], correctIndex: 0, explanation: 'The Narayanan Committee (1975) recommended the establishment of Regional Rural Banks to serve rural credit needs.', source },
  { id: 'nabard-ga-p1-ga-005', section: 'General Awareness', topic: 'Financial Terms', difficulty: 'medium', question: 'A loan account is classified as a Non-Performing Asset (NPA) when interest or principal repayment remains overdue for a period of:', options: ['30 days', '60 days', '120 days', '90 days'], correctIndex: 3, explanation: 'As per RBI norms, a loan account is classified as a Non-Performing Asset when interest or principal repayment remains overdue for more than 90 days.', source },
  { id: 'nabard-ga-p1-ga-006', section: 'General Awareness', topic: 'Indian Polity', difficulty: 'medium', question: 'Which Article of the Indian Constitution places agriculture under the State List, giving states primary legislative authority over it?', options: ['Article 246 read with the Seventh Schedule', 'Article 14', 'Article 32', 'Article 370'], correctIndex: 0, explanation: 'Article 246, read with Entry 14 of the State List in the Seventh Schedule, places agriculture primarily under state legislative authority.', source },
  { id: 'nabard-ga-p1-ga-007', section: 'General Awareness', topic: 'Banking Awareness', difficulty: 'medium', question: 'Which activity are Payments Banks in India (such as India Post Payments Bank) prohibited from undertaking?', options: ['Accepting savings deposits', 'Facilitating money transfers', 'Issuing loans and credit cards', 'Selling mutual fund products'], correctIndex: 2, explanation: 'Payments Banks are not permitted to issue loans or credit cards; they are restricted to accepting deposits (up to a prescribed limit) and offering payments and remittance services.', source },
  { id: 'nabard-ga-p1-ga-008', section: 'General Awareness', topic: 'Financial Regulators', difficulty: 'medium', question: 'Which regulatory body oversees and regulates the securities market in India, including stock exchanges?', options: ['RBI', 'IRDAI', 'SEBI', 'PFRDA'], correctIndex: 2, explanation: 'The Securities and Exchange Board of India (SEBI) regulates the securities market in India, including stock exchanges.', source },
  { id: 'nabard-ga-p1-ga-009', section: 'General Awareness', topic: 'Union Budget', difficulty: 'medium', question: 'The Union Budget of India is presented in Parliament by the:', options: ['President', 'Prime Minister', 'Finance Minister', 'Reserve Bank Governor'], correctIndex: 2, explanation: 'The Union Budget of India is presented in Parliament by the Union Finance Minister.', source },
  { id: 'nabard-ga-p1-ga-010', section: 'General Awareness', topic: 'Banking Sector Reforms', difficulty: 'medium', question: 'The Narasimham Committee, whose recommendations shaped major banking sector reforms in India, submitted its reports in which decade?', options: ['1970s', '1980s', '1990s', '2000s'], correctIndex: 2, explanation: 'The Narasimham Committee submitted its two influential reports in 1991 and 1998, shaping India\'s banking sector reforms.', source },
  { id: 'nabard-ga-p1-ga-011', section: 'General Awareness', topic: 'Geography', difficulty: 'medium', question: 'Which Indian state has the largest total geographical area under agricultural cultivation?', options: ['Punjab', 'Uttar Pradesh', 'Madhya Pradesh', 'Rajasthan'], correctIndex: 3, explanation: 'Rajasthan has the largest total geographical area under agricultural land use among Indian states, though yield per hectare varies.', source },
  { id: 'nabard-ga-p1-ga-012', section: 'General Awareness', topic: 'Deposit Insurance', difficulty: 'medium', question: 'The Deposit Insurance and Credit Guarantee Corporation (DICGC) currently insures bank deposits up to what amount per depositor per bank?', options: ['₹1 lakh', '₹3 lakh', '₹5 lakh', '₹10 lakh'], correctIndex: 2, explanation: 'DICGC insures bank deposits up to ₹5 lakh per depositor per bank, covering both principal and interest.', source },
  { id: 'nabard-ga-p1-ga-013', section: 'General Awareness', topic: 'International Organisations', difficulty: 'medium', question: 'India is a founding member of which international financial institution headquartered in Beijing, focused on infrastructure development in Asia?', options: ['Asian Infrastructure Investment Bank (AIIB)', 'World Bank', 'International Monetary Fund', 'Asian Development Bank'], correctIndex: 0, explanation: 'India is a founding member of the Asian Infrastructure Investment Bank (AIIB), headquartered in Beijing, which focuses on infrastructure development in Asia.', source },
  { id: 'nabard-ga-p1-ga-014', section: 'General Awareness', topic: 'Government Schemes', difficulty: 'medium', question: 'The Stand-Up India scheme primarily aims to promote entrepreneurship among which groups?', options: ['Scheduled Caste, Scheduled Tribe, and women entrepreneurs', 'Only retired government employees', 'Only urban youth', 'Only large corporates'], correctIndex: 0, explanation: 'Stand-Up India aims to facilitate bank loans for setting up greenfield enterprises among Scheduled Caste, Scheduled Tribe, and women entrepreneurs.', source },
  { id: 'nabard-ga-p1-ga-015', section: 'General Awareness', topic: 'Currency and Payments', difficulty: 'medium', question: 'Which organisation is responsible for issuing and managing RuPay, India\'s domestic card payment network?', options: ['RBI', 'NABARD', 'SEBI', 'National Payments Corporation of India (NPCI)'], correctIndex: 3, explanation: 'The National Payments Corporation of India (NPCI) developed and manages RuPay, India\'s domestic card payment network.', source },
  { id: 'nabard-ga-p1-ga-016', section: 'General Awareness', topic: 'Sports', difficulty: 'medium', question: 'The Khelo India Youth Games, launched to promote sports culture at the grassroots level, are held:', options: ['Once every four years', 'Annually', 'Once every two years', 'Only at the state level'], correctIndex: 1, explanation: 'The Khelo India Youth Games are held annually to promote a sporting culture among young athletes at the grassroots level.', source },
  { id: 'nabard-ga-p1-ga-017', section: 'General Awareness', topic: 'Currency', difficulty: 'medium', question: 'The Consumer Price Index (CPI), used by the RBI for inflation targeting, is compiled and released by which body?', options: ['Reserve Bank of India', 'National Statistical Office (NSO)', 'NABARD', 'SEBI'], correctIndex: 1, explanation: 'The Consumer Price Index (CPI) is compiled and released by the National Statistical Office (NSO), Ministry of Statistics and Programme Implementation.', source },
  { id: 'nabard-ga-p1-ga-018', section: 'General Awareness', topic: 'Space and Science', difficulty: 'medium', question: 'India\'s Chandrayaan-3 mission, which successfully soft-landed near the Moon\'s south pole in 2023, was launched by which organisation?', options: ['DRDO', 'ISRO', 'BARC', 'CSIR'], correctIndex: 1, explanation: 'The Indian Space Research Organisation (ISRO) launched and executed the Chandrayaan-3 mission, which soft-landed near the Moon\'s south pole in August 2023.', source },
  { id: 'nabard-ga-p1-ga-019', section: 'General Awareness', topic: 'Government Institutions', difficulty: 'medium', question: 'Which institution is primarily responsible for conducting the decennial Census of India?', options: ['National Statistical Office', 'Office of the Registrar General and Census Commissioner', 'NITI Aayog', 'Election Commission of India'], correctIndex: 1, explanation: 'The Office of the Registrar General and Census Commissioner of India conducts the decennial Census of India.', source },
  { id: 'nabard-ga-p1-ga-020', section: 'General Awareness', topic: 'Banking Awareness', difficulty: 'medium', question: 'Which of the following banks was formed after the merger of Vijaya Bank and Dena Bank with Bank of Baroda in 2019?', options: ['State Bank of India', 'Bank of Baroda (merged entity)', 'Punjab National Bank', 'Canara Bank'], correctIndex: 1, explanation: 'Vijaya Bank and Dena Bank were merged into Bank of Baroda in April 2019, creating India\'s third-largest public sector bank at the time.', source },
];
