import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference:
    'Original TakeMockTest practice questions covering the NATA 2026 Mathematics syllabus topic list (10+2 level: Algebra, Trigonometry, Coordinate Geometry, Calculus, Mensuration, Vectors and 3D Geometry, Matrices, Probability), corroborated across multiple independent secondary sources since the official nata.in and coa.gov.in domains could not be independently accessed. See this exam\'s review-pending pattern disclosure for the exact scope and confidence level.',
  url: 'https://www.nata.in/',
  checkedOn: '20 August 2026',
};

export const NATA_MATHEMATICS_1: Question[] = [
  {
    id: 'nata-mathematics-01-001',
    section: 'Mathematics',
    topic: 'Algebra',
    difficulty: 'easy',
    question: 'Solve for x: x^2 - 5x + 6 = 0. What are the roots?',
    options: ['2, 3', '1, 6', '-2, -3', '2, -3'],
    correctIndex: 0,
    answerType: 'mcq',
    marks: 2,
    negativeMarking: 0,
    explanation: 'Factoring: x^2 - 5x + 6 = (x - 2)(x - 3) = 0, so x = 2 or x = 3.',
    source,
  },
  {
    id: 'nata-mathematics-01-002',
    section: 'Mathematics',
    topic: 'Algebra',
    difficulty: 'medium',
    question: 'If alpha and beta are the roots of 2x^2 - 7x + 3 = 0, what is alpha + beta?',
    options: ['7', '3.5', '1.5', '-3.5'],
    correctIndex: 1,
    answerType: 'mcq',
    marks: 2,
    negativeMarking: 0,
    explanation: 'For ax^2 + bx + c = 0, the sum of roots is -b/a = 7/2 = 3.5.',
    source,
  },
  {
    id: 'nata-mathematics-01-003',
    section: 'Mathematics',
    topic: 'Algebra',
    difficulty: 'hard',
    question: 'How many distinct real roots does x^3 - 3x + 2 = 0 have?',
    options: ['1', '3', '2', '0'],
    correctIndex: 2,
    answerType: 'mcq',
    marks: 2,
    negativeMarking: 0,
    explanation:
      'x = 1 satisfies the equation (1 - 3 + 2 = 0). Dividing gives x^3 - 3x + 2 = (x - 1)^2(x + 2), so the distinct real roots are x = 1 and x = -2, giving 2 distinct real roots.',
    source,
  },
  {
    id: 'nata-mathematics-01-004',
    section: 'Mathematics',
    topic: 'Trigonometry',
    difficulty: 'easy',
    question: 'If sin(theta) = 3/5 and theta is acute, what is cos(theta)?',
    options: ['0.6', '0.75', '1.2', '0.8'],
    correctIndex: 3,
    answerType: 'mcq',
    marks: 2,
    negativeMarking: 0,
    explanation: 'This is a 3-4-5 right triangle, so cos(theta) = 4/5 = 0.8.',
    source,
  },
  {
    id: 'nata-mathematics-01-005',
    section: 'Mathematics',
    topic: 'Trigonometry',
    difficulty: 'medium',
    question: 'What is the exact value of tan(75 degrees)?',
    options: ['2 + sqrt(3)', '2 - sqrt(3)', '1 + sqrt(3)', 'sqrt(3)'],
    correctIndex: 0,
    answerType: 'mcq',
    marks: 2,
    negativeMarking: 0,
    explanation:
      'tan(75) = tan(45 + 30) = (1 + 1/sqrt(3)) / (1 - 1/sqrt(3)) = (sqrt(3) + 1) / (sqrt(3) - 1). Rationalizing gives (4 + 2sqrt(3)) / 2 = 2 + sqrt(3).',
    source,
  },
  {
    id: 'nata-mathematics-01-006',
    section: 'Mathematics',
    topic: 'Trigonometry',
    difficulty: 'hard',
    question:
      'From a point 50 m from the base of a tower, the angle of elevation to the top is 30 degrees. What is the height of the tower, to the nearest whole metre?',
    options: ['50 m', '29 m', '87 m', '17 m'],
    correctIndex: 1,
    answerType: 'mcq',
    marks: 2,
    negativeMarking: 0,
    explanation: 'Height = 50 x tan(30) = 50 x (1/sqrt(3)) is approximately 50 x 0.5774 = 28.87, which rounds to 29 m.',
    source,
  },
  {
    id: 'nata-mathematics-01-007',
    section: 'Mathematics',
    topic: 'Coordinate Geometry',
    difficulty: 'easy',
    question: 'Find the distance between the points (3, 4) and (7, 1).',
    options: ['7', '4', '5', '6'],
    correctIndex: 2,
    answerType: 'mcq',
    marks: 2,
    negativeMarking: 0,
    explanation: 'Distance = sqrt((7-3)^2 + (1-4)^2) = sqrt(16 + 9) = sqrt(25) = 5.',
    source,
  },
  {
    id: 'nata-mathematics-01-008',
    section: 'Mathematics',
    topic: 'Coordinate Geometry',
    difficulty: 'medium',
    question: 'Find the slope of the line joining the points (2, 3) and (6, 11).',
    options: ['1/2', '-2', '4', '2'],
    correctIndex: 3,
    answerType: 'mcq',
    marks: 2,
    negativeMarking: 0,
    explanation: 'Slope = (11 - 3) / (6 - 2) = 8 / 4 = 2.',
    source,
  },
  {
    id: 'nata-mathematics-01-009',
    section: 'Mathematics',
    topic: 'Coordinate Geometry',
    difficulty: 'hard',
    question: 'Find the equation of the line perpendicular to 2x + 3y = 6 that passes through (1, 2).',
    options: ['3x - 2y + 1 = 0', '3x + 2y - 7 = 0', '2x - 3y + 4 = 0', '3x - 2y - 1 = 0'],
    correctIndex: 0,
    answerType: 'mcq',
    marks: 2,
    negativeMarking: 0,
    explanation:
      'The slope of 2x + 3y = 6 is -2/3, so a perpendicular line has slope 3/2. Using point-slope form through (1, 2): y - 2 = (3/2)(x - 1), which simplifies to 3x - 2y + 1 = 0.',
    source,
  },
  {
    id: 'nata-mathematics-01-010',
    section: 'Mathematics',
    topic: 'Calculus',
    difficulty: 'easy',
    question: 'If y = x^3 - 4x, what is dy/dx at x = 2?',
    options: ['12', '8', '4', '6'],
    correctIndex: 1,
    answerType: 'mcq',
    marks: 2,
    negativeMarking: 0,
    explanation: 'dy/dx = 3x^2 - 4. At x = 2, this is 3(4) - 4 = 8.',
    source,
  },
  {
    id: 'nata-mathematics-01-011',
    section: 'Mathematics',
    topic: 'Calculus',
    difficulty: 'medium',
    question: 'Evaluate the indefinite integral of (3x^2 + 2x) with respect to x.',
    options: ['3x^3 + x^2 + C', 'x^3 + 2x^2 + C', 'x^3 + x^2 + C', 'x^2 + x + C'],
    correctIndex: 2,
    answerType: 'mcq',
    marks: 2,
    negativeMarking: 0,
    explanation: 'The integral of 3x^2 is x^3, and the integral of 2x is x^2, giving x^3 + x^2 + C.',
    source,
  },
  {
    id: 'nata-mathematics-01-012',
    section: 'Mathematics',
    topic: 'Calculus',
    difficulty: 'hard',
    question: 'What is the maximum value of f(x) = -x^2 + 4x + 1?',
    options: ['4', '6', '1', '5'],
    correctIndex: 3,
    answerType: 'mcq',
    marks: 2,
    negativeMarking: 0,
    explanation:
      "f'(x) = -2x + 4 = 0 gives x = 2. Since the coefficient of x^2 is negative, this is a maximum: f(2) = -4 + 8 + 1 = 5.",
    source,
  },
  {
    id: 'nata-mathematics-01-013',
    section: 'Mathematics',
    topic: 'Mensuration',
    difficulty: 'easy',
    question: 'Find the area of a circle with radius 7 cm. (Use pi = 22/7.)',
    options: ['154 cm^2', '144 cm^2', '49 cm^2', '22 cm^2'],
    correctIndex: 0,
    answerType: 'mcq',
    marks: 2,
    negativeMarking: 0,
    explanation: 'Area = pi x r^2 = (22/7) x 49 = 22 x 7 = 154 cm^2.',
    source,
  },
  {
    id: 'nata-mathematics-01-014',
    section: 'Mathematics',
    topic: 'Mensuration',
    difficulty: 'medium',
    question: 'Find the volume of a cylinder with radius 3 cm and height 7 cm. (Use pi = 22/7.)',
    options: ['189 cm^3', '198 cm^3', '176 cm^3', '154 cm^3'],
    correctIndex: 1,
    answerType: 'mcq',
    marks: 2,
    negativeMarking: 0,
    explanation: 'Volume = pi x r^2 x h = (22/7) x 9 x 7 = 22 x 9 = 198 cm^3.',
    source,
  },
  {
    id: 'nata-mathematics-01-015',
    section: 'Mathematics',
    topic: 'Vectors and 3D Geometry',
    difficulty: 'easy',
    question: 'Find the magnitude of the vector (3, 4, 0).',
    options: ['7', '4', '5', '3'],
    correctIndex: 2,
    answerType: 'mcq',
    marks: 2,
    negativeMarking: 0,
    explanation: 'Magnitude = sqrt(3^2 + 4^2 + 0^2) = sqrt(25) = 5.',
    source,
  },
  {
    id: 'nata-mathematics-01-016',
    section: 'Mathematics',
    topic: 'Vectors and 3D Geometry',
    difficulty: 'medium',
    question: 'Find the dot product of the vectors (1, 2, 3) and (4, -5, 6).',
    options: ['0', '-12', '20', '12'],
    correctIndex: 3,
    answerType: 'mcq',
    marks: 2,
    negativeMarking: 0,
    explanation: 'Dot product = (1)(4) + (2)(-5) + (3)(6) = 4 - 10 + 18 = 12.',
    source,
  },
  {
    id: 'nata-mathematics-01-017',
    section: 'Mathematics',
    topic: 'Matrices',
    difficulty: 'easy',
    question: 'If A = [[1, 2], [3, 4]], what is the determinant of A?',
    options: ['-2', '2', '-10', '10'],
    correctIndex: 0,
    answerType: 'mcq',
    marks: 2,
    negativeMarking: 0,
    explanation: 'Determinant = (1)(4) - (2)(3) = 4 - 6 = -2.',
    source,
  },
  {
    id: 'nata-mathematics-01-018',
    section: 'Mathematics',
    topic: 'Matrices',
    difficulty: 'medium',
    question: 'If A = [[2, 0], [1, 3]] and B = [[1, 4], [0, 2]], what is A x B?',
    options: ['[[2, 8], [1, 4]]', '[[2, 8], [1, 10]]', '[[2, 4], [1, 10]]', '[[2, 8], [3, 10]]'],
    correctIndex: 1,
    answerType: 'mcq',
    marks: 2,
    negativeMarking: 0,
    explanation:
      'Row 1: [2(1) + 0(0), 2(4) + 0(2)] = [2, 8]. Row 2: [1(1) + 3(0), 1(4) + 3(2)] = [1, 10]. So A x B = [[2, 8], [1, 10]].',
    source,
  },
  {
    id: 'nata-mathematics-01-019',
    section: 'Mathematics',
    topic: 'Probability',
    difficulty: 'easy',
    question: 'A die is rolled once. What is the probability of getting a number greater than 4?',
    options: ['1/2', '1/6', '1/3', '2/3'],
    correctIndex: 2,
    answerType: 'mcq',
    marks: 2,
    negativeMarking: 0,
    explanation: 'The numbers greater than 4 are 5 and 6, so the probability is 2/6 = 1/3.',
    source,
  },
  {
    id: 'nata-mathematics-01-020',
    section: 'Mathematics',
    topic: 'Probability',
    difficulty: 'medium',
    question: 'Two fair coins are tossed together. What is the probability of getting exactly one head?',
    options: ['1/4', '3/4', '1/3', '1/2'],
    correctIndex: 3,
    answerType: 'mcq',
    marks: 2,
    negativeMarking: 0,
    explanation: 'The outcomes are HH, HT, TH, TT. Exactly one head occurs in HT and TH, so the probability is 2/4 = 1/2.',
    source,
  },
];
