import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'Original Indian Navy Agniveer SSR practice questions in the official 4-option multiple-choice format, covering English and Mathematics from the SSR (Senior Secondary Recruit) syllabus.',
  url: 'https://www.joinindiannavy.gov.in/en/page/selection-procedure.html',
  checkedOn: '16 August 2026',
};

export const NAVY_SSR_ENGLISH_AND_MATHEMATICS_1: Question[] = [
  { id: 'navy-ssr-english-and-mathematics-01-001', section: 'English', topic: 'Synonyms', difficulty: 'easy', question: 'Choose the word closest in meaning to "Audacious".', options: ['Bold', 'Timid', 'Modest', 'Cautious'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: '"Audacious" means showing a willingness to take bold risks, closest to "Bold".', source },
  { id: 'navy-ssr-english-and-mathematics-01-002', section: 'English', topic: 'Antonyms', difficulty: 'easy', question: 'Choose the word opposite in meaning to "Meagre".', options: ['Scanty', 'Ample', 'Sparse', 'Thin'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: '"Meagre" means lacking in quantity; its opposite is "Ample".', source },
  { id: 'navy-ssr-english-and-mathematics-01-003', section: 'English', topic: 'Prepositions', difficulty: 'easy', question: 'Fill in the blank: The committee consists ___ five members.', options: ['in', 'with', 'of', 'from'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'The correct idiomatic preposition is "of": The committee consists of five members.', source },
  { id: 'navy-ssr-english-and-mathematics-01-004', section: 'English', topic: 'Spelling', difficulty: 'easy', question: 'Choose the correctly spelled word.', options: ['Resturant', 'Restaurent', 'Resturaunt', 'Restaurant'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'The correct spelling is "Restaurant".', source },
  { id: 'navy-ssr-english-and-mathematics-01-005', section: 'English', topic: 'One-Word Substitution', difficulty: 'medium', question: 'Choose the word that means "a person who designs buildings".', options: ['Architect', 'Sculptor', 'Engineer', 'Carpenter'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'An "Architect" is a person who designs buildings and other structures.', source },
  { id: 'navy-ssr-english-and-mathematics-01-006', section: 'English', topic: 'Modal Verbs', difficulty: 'medium', question: 'Choose the grammatically correct sentence.', options: ['You had better to finish your homework before dinner.', 'You had better finish your homework before dinner.', 'You had better finishing your homework before dinner.', 'You better finished your homework before dinner.'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'The modal phrase "had better" is followed directly by the base form of the verb: "had better finish".', source },
  { id: 'navy-ssr-english-and-mathematics-01-007', section: 'English', topic: 'Articles', difficulty: 'easy', question: 'Fill in the blank: My father is ___ honest man.', options: ['a', 'the', 'an', 'no article'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: '"Honest" begins with a silent "h", giving it a vowel sound, so it takes the article "an".', source },
  { id: 'navy-ssr-english-and-mathematics-01-008', section: 'English', topic: 'Narration', difficulty: 'medium', question: 'Choose the correct indirect speech for: He said, "I am going to the market."', options: ['He said that he is going to the market.', 'He said that he had going to the market.', 'He told that he was going to the market.', 'He said that he was going to the market.'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'In indirect speech, present continuous shifts to past continuous and the pronoun changes: He said that he was going to the market.', source },
  { id: 'navy-ssr-english-and-mathematics-01-009', section: 'English', topic: 'Voice (Active-Passive)', difficulty: 'medium', question: 'Choose the correct passive voice of: "The librarian issues new books every Monday."', options: ['New books are issued by the librarian every Monday.', 'New books were issued by the librarian every Monday.', 'New books issued by the librarian every Monday.', 'New books are being issued by the librarian every Monday.'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Present simple active becomes present simple passive: New books are issued by the librarian every Monday.', source },
  { id: 'navy-ssr-english-and-mathematics-01-010', section: 'English', topic: 'Tenses', difficulty: 'medium', question: 'Fill in the blank: By the time we reached the station, the train ___ already left.', options: ['has', 'had', 'have', 'having'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'An action completed before another past action takes the past perfect tense: the train had already left.', source },
  { id: 'navy-ssr-english-and-mathematics-01-011', section: 'English', topic: 'Vocabulary in Context', difficulty: 'medium', question: 'Choose the correct meaning of the word "Gregarious".', options: ['Solitary', 'Aggressive', 'Fond of company', 'Timid'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: '"Gregarious" describes someone who is sociable and fond of company.', source },
  { id: 'navy-ssr-english-and-mathematics-01-012', section: 'English', topic: 'Conjunctions', difficulty: 'medium', question: 'Fill in the blank: ___ he apologized sincerely, she refused to forgive him.', options: ['Because', 'Since', 'So that', 'Even though'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: '"Even though" correctly introduces a concessive clause contrasting his sincere apology with her refusal to forgive.', source },
  { id: 'navy-ssr-english-and-mathematics-01-013', section: 'Mathematics', topic: 'Time and Work', difficulty: 'medium', question: 'Working alone, Rahul can paint a wall in 6 hours, and Priya can paint the same wall in 12 hours. If they paint together, how many hours will they take?', options: ['4', '5', '4.5', '6'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Combined rate = 1/6 + 1/12 = 2/12 + 1/12 = 3/12 = 1/4 of the wall per hour, so together they take 4 hours.', source },
  { id: 'navy-ssr-english-and-mathematics-01-014', section: 'Mathematics', topic: 'Ratio and Proportion', difficulty: 'medium', question: 'The ratio of two numbers is 4:7. If the smaller number is 28, find the larger number.', options: ['42', '49', '56', '63'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Since 4 parts = 28, 1 part = 7. The larger number = 7 parts = 7 × 7 = 49.', source },
  { id: 'navy-ssr-english-and-mathematics-01-015', section: 'Mathematics', topic: 'Percentage', difficulty: 'easy', question: '28% of a number is 84. Find the number.', options: ['280', '290', '300', '310'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: '0.28 × x = 84, so x = 84 / 0.28 = 300.', source },
  { id: 'navy-ssr-english-and-mathematics-01-016', section: 'Mathematics', topic: 'Speed, Distance and Time', difficulty: 'easy', question: 'A cyclist covers 90 km in 2.5 hours. Find the average speed.', options: ['30 km/h', '33 km/h', '34 km/h', '36 km/h'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Speed = Distance ÷ Time = 90 ÷ 2.5 = 36 km/h.', source },
  { id: 'navy-ssr-english-and-mathematics-01-017', section: 'Mathematics', topic: 'Number System', difficulty: 'medium', question: 'Which of the following is divisible by both 3 and 4?', options: ['132', '130', '134', '128'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: '132 ÷ 3 = 44 and 132 ÷ 4 = 33, so 132 is divisible by both 3 and 4.', source },
  { id: 'navy-ssr-english-and-mathematics-01-018', section: 'Mathematics', topic: 'Simplification', difficulty: 'easy', question: 'Simplify: 45 ÷ 9 × 3 − 7.', options: ['6', '8', '9', '7'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'By order of operations: 45 ÷ 9 = 5, then 5 × 3 = 15, then 15 − 7 = 8.', source },
  { id: 'navy-ssr-english-and-mathematics-01-019', section: 'Mathematics', topic: 'Mixture and Alligation', difficulty: 'medium', question: 'In what ratio must tea priced at ₹300/kg be mixed with tea priced at ₹200/kg to obtain a mixture worth ₹240/kg?', options: ['2:3', '5:3', '3:2', '3:5'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'By the alligation rule, the ratio = (300 − 240) : (240 − 200) = 60 : 40 = 3:2.', source },
  { id: 'navy-ssr-english-and-mathematics-01-020', section: 'Mathematics', topic: 'Mensuration', difficulty: 'easy', question: 'Find the area of a triangle with base 10 cm and height 6 cm.', options: ['24 cm²', '27 cm²', '28 cm²', '30 cm²'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Area = (1/2) × base × height = (1/2) × 10 × 6 = 30 cm².', source },
  { id: 'navy-ssr-english-and-mathematics-01-021', section: 'Mathematics', topic: 'Trigonometry', difficulty: 'medium', question: 'Find the value of sin 60° × cos 30°.', options: ['3/4', '1/2', '√3/2', '1'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'sin 60° = √3/2 and cos 30° = √3/2, so their product is (√3/2) × (√3/2) = 3/4.', source },
  { id: 'navy-ssr-english-and-mathematics-01-022', section: 'Mathematics', topic: 'Probability', difficulty: 'easy', question: 'A box contains 3 green and 5 yellow marbles. One marble is drawn at random. Find the probability that it is green.', options: ['1/2', '3/8', '5/8', '1/4'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'There are 3 green marbles out of 8 total, so the probability is 3/8.', source },
  { id: 'navy-ssr-english-and-mathematics-01-023', section: 'Mathematics', topic: 'Simple Equations', difficulty: 'easy', question: 'Solve for x: 3x − 7 = 11.', options: ['4', '5', '6', '7'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: '3x = 11 + 7 = 18, so x = 18 / 3 = 6.', source },
  { id: 'navy-ssr-english-and-mathematics-01-024', section: 'Mathematics', topic: 'Mensuration', difficulty: 'medium', question: 'Find the volume of a cuboid with length 8 cm, breadth 5 cm, and height 3 cm.', options: ['100 cm³', '110 cm³', '115 cm³', '120 cm³'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.25, explanation: 'Volume = length × breadth × height = 8 × 5 × 3 = 120 cm³.', source },
];
