import type { Question } from '../questions';

// NIACL AO (Generalist) Prelims: Reasoning Ability, 35 questions.
// Qualifying stage only: Phase I marks do not carry forward into the final
// merit list, which is decided by the Phase II objective score plus interview.
const source = {
  kind: 'original' as const,
  reference: 'New India Assurance Co. Ltd: Recruitment of 550 Administrative Officers (Generalists & Specialists) 2025',
  url: 'https://www.newindia.co.in/assets/docs/recruitment/RECRUITMENT%20OF%20ADMINISTRATIVE%20OFFICERS%202025/RECRUITMENT%20OF%20_5_50%20ADMINISTRATIVE%20OFFICERS%20(GENERALISTS%20&%20SPECIALISTS)%20(SCALE-I)%20202_5.pdf',
  checkedOn: '6 August 2026',
};

export const NIACL_AO_PRELIMS_REASONING_ABILITY_1: Question[] = [
  { id: 'niacl-p-re-001', section: 'Reasoning Ability', topic: 'Syllogism', difficulty: 'easy', question: 'Statements: All chairs are tables. All tables are desks. Conclusion: All chairs are desks. Is the conclusion valid?', options: ['Invalid', 'Cannot be determined', 'Only partially valid', 'Valid'], correctIndex: 3, explanation: 'Since every chair is a table, and every table is a desk, it necessarily follows that every chair is a desk. This is a standard valid chain syllogism.', source },
  { id: 'niacl-p-re-002', section: 'Reasoning Ability', topic: 'Syllogism', difficulty: 'medium', question: 'Statements: Some files are folders. All folders are cabinets. Conclusion: Some files are cabinets. Is the conclusion valid?', options: ['Invalid', 'Cannot be determined', 'Only partially valid', 'Valid'], correctIndex: 3, explanation: 'Since some files are folders, and all folders are cabinets, those particular files that are folders must also be cabinets, so "some files are cabinets" necessarily follows.', source },
  { id: 'niacl-p-re-003', section: 'Reasoning Ability', topic: 'Syllogism', difficulty: 'medium', question: 'Statements: No claim is fraudulent. All rejected applications are fraudulent. Conclusion: No rejected application is a claim. Is the conclusion valid?', options: ['Invalid', 'Cannot be determined', 'Only partially valid', 'Valid'], correctIndex: 3, explanation: 'Since all rejected applications fall within the group of fraudulent items, and no claim is fraudulent, rejected applications cannot be claims either, so the conclusion necessarily follows.', source },
  { id: 'niacl-p-re-004', section: 'Reasoning Ability', topic: 'Syllogism', difficulty: 'hard', question: 'Statements: Some surveyors are engineers. All engineers are graduates. Conclusion: Some surveyors are graduates. Is the conclusion valid?', options: ['Invalid', 'Cannot be determined', 'Only partially valid', 'Valid'], correctIndex: 3, explanation: 'The surveyors who are also engineers must be graduates, since all engineers are graduates. This guarantees that at least some surveyors are graduates.', source },
  { id: 'niacl-p-re-005', section: 'Reasoning Ability', topic: 'Coding-Decoding', difficulty: 'easy', question: 'If POLICY is coded as QPMJDZ (each letter moved one step forward in the alphabet), how would CLAIMS be coded using the same rule?', options: ['DMBJMT', 'CMBJNT', 'DMAJNT', 'DMBJNT'], correctIndex: 3, explanation: 'Shifting each letter of CLAIMS forward by one: C→D, L→M, A→B, I→J, M→N, S→T, giving DMBJNT.', source },
  { id: 'niacl-p-re-006', section: 'Reasoning Ability', topic: 'Coding-Decoding', difficulty: 'medium', question: 'In a certain code, MOTOR is written as NPUPS. How would BROKER be written in that code?', options: ['CSPLFT', 'CSPKFS', 'BSPLFS', 'CSPLFS'], correctIndex: 3, explanation: 'The code shifts each letter forward by one (M→N, O→P, T→U, O→P, R→S). Applying this to BROKER: B→C, R→S, O→P, K→L, E→F, R→S, giving CSPLFS.', source },
  { id: 'niacl-p-re-007', section: 'Reasoning Ability', topic: 'Coding-Decoding', difficulty: 'medium', question: 'If BRANCH is coded as CSBODI using a one-step-forward letter shift, what is the code for OFFICE using the same rule?', options: ['OGGJDF', 'PGGJDE', 'PGGJDF', 'PGFJDF'], correctIndex: 2, explanation: 'Shifting each letter of OFFICE forward by one: O→P, F→G, F→G, I→J, C→D, E→F, giving PGGJDF.', source },
  { id: 'niacl-p-re-008', section: 'Reasoning Ability', topic: 'Coding-Decoding', difficulty: 'easy', question: 'If, using the code A=1, B=2, C=3, and so on, RISK is written as 18-9-19-11, how would FUND be written using the same code?', options: ['6-20-14-4', '6-21-13-4', '6-21-14-4', '5-21-14-4'], correctIndex: 2, explanation: 'F is the 6th letter, U is the 21st letter, N is the 14th letter, and D is the 4th letter of the alphabet, giving the code 6-21-14-4.', source },
  { id: 'niacl-p-re-009', section: 'Reasoning Ability', topic: 'Blood Relations', difficulty: 'medium', question: 'Pointing to a photograph, Rohan said, "He is the son of my mother\'s only son." How is the boy in the photograph related to Rohan?', options: ['Brother', 'Nephew', 'Cousin', 'Son'], correctIndex: 1, explanation: "Rohan's mother's only son is Rohan's brother. That brother's son is Rohan's nephew.", source },
  { id: 'niacl-p-re-010', section: 'Reasoning Ability', topic: 'Blood Relations', difficulty: 'medium', question: "P is Q's father. R is Q's sister. S is R's husband. How is S related to P?", options: ['Son', 'Son-in-law', 'Brother-in-law', 'Nephew'], correctIndex: 1, explanation: "R is P's daughter, and S is R's husband, which makes S the son-in-law of P.", source },
  { id: 'niacl-p-re-011', section: 'Reasoning Ability', topic: 'Blood Relations', difficulty: 'hard', question: 'Pointing to a boy, a woman (who has no brothers) said, "He is the son of my father\'s only daughter." How is the boy related to the woman?', options: ['Nephew', 'Son', 'Brother', 'Cousin'], correctIndex: 1, explanation: 'Since the woman has no brothers, she herself is her father\'s only daughter. So "my father\'s only daughter" refers to the woman, making the boy her own son.', source },
  { id: 'niacl-p-re-012', section: 'Reasoning Ability', topic: 'Blood Relations', difficulty: 'hard', question: 'Pointing to a boy, a man (who has no brothers) said, "He is the son of my father\'s only son." How is the boy related to the man?', options: ['Nephew', 'Son', 'Brother', 'Cousin'], correctIndex: 1, explanation: 'Since the man has no brothers, he himself is his father\'s only son. So "my father\'s only son" refers to the man, making the boy the man\'s own son.', source },
  { id: 'niacl-p-re-013', section: 'Reasoning Ability', topic: 'Direction Sense', difficulty: 'medium', question: 'A man walks 12 km north, then turns right and walks 5 km, then turns right again and walks 12 km. How far is he from his starting point, and in which direction?', options: ['5 km, west', '5 km, east', '12 km, south', '17 km, east'], correctIndex: 1, explanation: 'Plotting the path: north 12 km, then east 5 km (right turn from north), then south 12 km (right turn from east) brings him back to the same latitude as the start, 5 km to the east.', source },
  { id: 'niacl-p-re-014', section: 'Reasoning Ability', topic: 'Direction Sense', difficulty: 'medium', question: 'Meera starts from her office and walks 9 km towards south. She then turns left and walks 12 km. How far is she from her office?', options: ['15 km', '18 km', '20 km', '21 km'], correctIndex: 0, explanation: 'Walking 9 km south then 12 km east (a left turn while facing south) forms a right-angled path. The direct distance is √(9² + 12²) = √225 = 15 km.', source },
  { id: 'niacl-p-re-015', section: 'Reasoning Ability', topic: 'Direction Sense', difficulty: 'medium', question: 'A person walks 6 km east, then 6 km south, then 6 km west. How far and in which direction is he from his starting point?', options: ['6 km, south', '6 km, north', '12 km, south', '6 km, east'], correctIndex: 0, explanation: 'The eastward and westward legs of 6 km each cancel out, leaving only the 6 km southward movement, so the final position is 6 km due south of the start.', source },
  { id: 'niacl-p-re-016', section: 'Reasoning Ability', topic: 'Direction Sense', difficulty: 'hard', question: 'If North-West becomes South, and South-West becomes East, what will North become, following the same rule?', options: ['South-East', 'North-West', 'South-West', 'West'], correctIndex: 0, explanation: 'Both given transformations correspond to rotating every direction by 135 degrees clockwise. Applying the same rotation to North gives South-East.', source },
  { id: 'niacl-p-re-017', section: 'Reasoning Ability', topic: 'Seating Arrangement', difficulty: 'medium', question: 'Five colleagues J, K, L, M, and N are sitting in a row facing north, not necessarily in that order. J sits third from the left end. K sits immediate right of J. L sits immediate left of J. M sits immediate right of K. Where does N sit?', options: ['Extreme left end', 'Extreme right end', 'Second from left', 'Third from right'], correctIndex: 0, explanation: 'With J at position 3, L at position 2 (left of J), K at position 4 (right of J), and M at position 5 (right of K), the only remaining seat is position 1, so N sits at the extreme left end.', source },
  { id: 'niacl-p-re-018', section: 'Reasoning Ability', topic: 'Seating Arrangement', difficulty: 'medium', question: 'Five clerks V, W, X, Y, and Z are seated in a row facing north, not necessarily in that order. W is second from the right end. V sits immediate left of W. X sits immediate right of W. Y sits immediate left of V. Who sits second from the left end?', options: ['V', 'Y', 'Z', 'X'], correctIndex: 1, explanation: 'With W at position 4, V at position 3 (left of W), X at position 5 (right of W), and Y at position 2 (left of V), position 2 is occupied by Y, making Y second from the left.', source },
  { id: 'niacl-p-re-019', section: 'Reasoning Ability', topic: 'Ranking and Order', difficulty: 'easy', question: 'In a batch of 60 trainees, Arjun ranks 22nd from the top. What is his rank from the bottom?', options: ['38th', '39th', '40th', '41st'], correctIndex: 1, explanation: 'Rank from the bottom = total trainees − rank from top + 1 = 60 − 22 + 1 = 39th.', source },
  { id: 'niacl-p-re-020', section: 'Reasoning Ability', topic: 'Ranking and Order', difficulty: 'medium', question: 'Kavya is 15th from the front and 20th from the end in a queue. How many people are there in the queue?', options: ['32', '33', '34', '35'], correctIndex: 2, explanation: 'Total people = (rank from front) + (rank from end) − 1 = 15 + 20 − 1 = 34.', source },
  { id: 'niacl-p-re-021', section: 'Reasoning Ability', topic: 'Alphabet Series', difficulty: 'medium', question: 'Find the missing term in the series: C, F, J, O, U, ?', options: ['A', 'B', 'C', 'D'], correctIndex: 1, explanation: 'The gap between consecutive letters increases by one each time (+3, +4, +5, +6, +7): C(3), F(6), J(10), O(15), U(21), and the next term is 21+7=28, which is B (wrapping past 26).', source },
  { id: 'niacl-p-re-022', section: 'Reasoning Ability', topic: 'Alphabet Series', difficulty: 'medium', question: 'Find the missing term in the series: Y, V, R, M, ?', options: ['G', 'H', 'I', 'F'], correctIndex: 0, explanation: 'The gap between consecutive letters decreases (moving back) by an increasing amount each time (-3, -4, -5, -6): Y(25), V(22), R(18), M(13), and the next term is 13-6=7, which is G.', source },
  { id: 'niacl-p-re-023', section: 'Reasoning Ability', topic: 'Number Series', difficulty: 'easy', question: 'Find the next number in the series: 2, 9, 28, 65, 126, ?', options: ['207', '215', '217', '227'], correctIndex: 2, explanation: 'Each term follows n³ + 1 for n = 1, 2, 3, 4, 5, 6: 1³+1=2, 2³+1=9, 3³+1=28, 4³+1=65, 5³+1=126, so the next term is 6³+1=217.', source },
  { id: 'niacl-p-re-024', section: 'Reasoning Ability', topic: 'Number Series', difficulty: 'medium', question: 'Find the next number in the series: 4, 6, 10, 16, 24, ?', options: ['30', '32', '34', '36'], correctIndex: 2, explanation: 'The differences between consecutive terms increase by 2 each time (2, 4, 6, 8), so the next difference is 10, giving 24 + 10 = 34.', source },
  { id: 'niacl-p-re-025', section: 'Reasoning Ability', topic: 'Classification', difficulty: 'easy', question: 'Which of the following does not belong with the others: Sparrow, Eagle, Ostrich, Crocodile?', options: ['Sparrow', 'Eagle', 'Ostrich', 'Crocodile'], correctIndex: 3, explanation: 'Sparrow, Eagle, and Ostrich are all birds, while Crocodile is a reptile, making it the odd one out.', source },
  { id: 'niacl-p-re-026', section: 'Reasoning Ability', topic: 'Classification', difficulty: 'medium', question: 'Select the option that does not fit with the rest: Rectangle, Rhombus, Trapezium, Sphere.', options: ['Rectangle', 'Rhombus', 'Trapezium', 'Sphere'], correctIndex: 3, explanation: 'Rectangle, Rhombus, and Trapezium are all two-dimensional shapes, while a Sphere is a three-dimensional solid, making it the odd one out.', source },
  { id: 'niacl-p-re-027', section: 'Reasoning Ability', topic: 'Inequality', difficulty: 'medium', question: 'Statements: M > N ≥ O > P. Conclusions: I. M > P  II. N > P. Which conclusion(s) follow?', options: ['Only I follows', 'Only II follows', 'Both I and II follow', 'Neither follows'], correctIndex: 2, explanation: 'Since M > N ≥ O > P, it follows directly that M > P. Also, since N ≥ O > P, it follows that N > P. Both conclusions are valid.', source },
  { id: 'niacl-p-re-028', section: 'Reasoning Ability', topic: 'Inequality', difficulty: 'hard', question: 'Statements: X ≥ Y > Z = W. Conclusions: I. X > W  II. Y ≥ W. Which conclusion(s) follow?', options: ['Only I follows', 'Only II follows', 'Both I and II follow', 'Neither follows'], correctIndex: 2, explanation: 'Since Y > Z = W, we get Y > W; combined with X ≥ Y, this gives X > W (Conclusion I). Also, Y > W directly implies Y ≥ W (Conclusion II). Both conclusions are valid.', source },
  { id: 'niacl-p-re-029', section: 'Reasoning Ability', topic: 'Analogy', difficulty: 'easy', question: 'DOCTOR is to PATIENT as SURVEYOR is to ?', options: ['CLAIM', 'HOSPITAL', 'MEDICINE', 'DEGREE'], correctIndex: 0, explanation: 'A doctor examines and treats a patient, just as a surveyor examines and assesses a claim, so the relationship is one of professional function.', source },
  { id: 'niacl-p-re-030', section: 'Reasoning Ability', topic: 'Analogy', difficulty: 'medium', question: 'FARMER is to CROP as INSURER is to ?', options: ['Policy', 'Farmer', 'Weather', 'Bank'], correctIndex: 0, explanation: 'A farmer produces and manages a crop, just as an insurer produces and manages a policy, so the relationship is one of the item created and administered.', source },
  { id: 'niacl-p-re-031', section: 'Reasoning Ability', topic: 'Analogy', difficulty: 'medium', question: '5 is to 125 as 4 is to ?', options: ['16', '48', '64', '80'], correctIndex: 2, explanation: 'The relationship is that the second number is the cube of the first: 5³ = 125, so 4³ = 64.', source },
  { id: 'niacl-p-re-032', section: 'Reasoning Ability', topic: 'Age Puzzles', difficulty: 'hard', question: "Six years ago, X's age was twice Y's age. After 6 more years from now, X's age will be one and a half times Y's age. Find Y's present age.", options: ['16 years', '17 years', '18 years', '19 years'], correctIndex: 2, explanation: "Let Y's age six years ago be y, so X's age then was 2y. Their present ages are (y+6) and (2y+6). Six years from now: (2y+12) = 1.5(y+12), which gives y=12, so Y's present age is y+6=18 years.", source },
  { id: 'niacl-p-re-033', section: 'Reasoning Ability', topic: 'Age Puzzles', difficulty: 'hard', question: "A mother's present age is 4 times her daughter's present age. After 8 years, the mother's age will be twice the daughter's age. Find the daughter's present age.", options: ['3 years', '4 years', '5 years', '6 years'], correctIndex: 1, explanation: "Let the daughter's present age be x, so the mother's present age is 4x. After 8 years: (4x+8) = 2(x+8), which gives 4x+8=2x+16, so 2x=8 and x=4. The daughter's present age is 4 years.", source },
  { id: 'niacl-p-re-034', section: 'Reasoning Ability', topic: 'Classification', difficulty: 'medium', question: 'Find the one that does not belong to the group: Chennai, Bengaluru, Hyderabad, Karnataka.', options: ['Chennai', 'Bengaluru', 'Hyderabad', 'Karnataka'], correctIndex: 3, explanation: 'Chennai, Bengaluru, and Hyderabad are all cities, while Karnataka is a state, making it the odd one out.', source },
  { id: 'niacl-p-re-035', section: 'Reasoning Ability', topic: 'Coding-Decoding', difficulty: 'medium', question: 'In a certain code, MARKET is written as NBSLFU (each letter shifted one step forward). How would BUDGET be written using the same code?', options: ['CVEHFU', 'CVEHFV', 'CVDHFU', 'BVEHFU'], correctIndex: 0, explanation: 'Shifting each letter of BUDGET forward by one: B→C, U→V, D→E, G→H, E→F, T→U, giving CVEHFU.', source },
];
