import type { Question } from '../questions';

// NIACL AO (Generalist) Prelims: Quantitative Aptitude, 35 questions.
// Qualifying stage only: Phase I marks do not carry forward into the final
// merit list, which is decided by the Phase II objective score plus interview.
const source = {
  kind: 'original' as const,
  reference: 'New India Assurance Co. Ltd: Recruitment of 550 Administrative Officers (Generalists & Specialists) 2025',
  url: 'https://www.newindia.co.in/assets/docs/recruitment/RECRUITMENT%20OF%20ADMINISTRATIVE%20OFFICERS%202025/RECRUITMENT%20OF%20_5_50%20ADMINISTRATIVE%20OFFICERS%20(GENERALISTS%20&%20SPECIALISTS)%20(SCALE-I)%20202_5.pdf',
  checkedOn: '6 August 2026',
};

export const NIACL_AO_PRELIMS_QUANTITATIVE_APTITUDE_1: Question[] = [
  { id: 'niacl-p-qa-001', section: 'Quantitative Aptitude', topic: 'Simplification', difficulty: 'easy', question: 'What is 15% of 480 plus 20% of 350?', options: ['132', '142', '152', '162'], correctIndex: 1, explanation: '15% of 480 = 72, and 20% of 350 = 70. Their sum is 72 + 70 = 142.', source },
  { id: 'niacl-p-qa-002', section: 'Quantitative Aptitude', topic: 'Simplification', difficulty: 'easy', question: 'What is the value of (14 × 17) − (9 × 11)?', options: ['129', '139', '149', '159'], correctIndex: 1, explanation: '14 × 17 = 238, and 9 × 11 = 99. So 238 − 99 = 139.', source },
  { id: 'niacl-p-qa-003', section: 'Quantitative Aptitude', topic: 'Simplification', difficulty: 'medium', question: 'What is the value of √196 + √169?', options: ['27', '25', '26', '28'], correctIndex: 0, explanation: '√196 = 14 and √169 = 13, so their sum is 14 + 13 = 27.', source },
  { id: 'niacl-p-qa-004', section: 'Quantitative Aptitude', topic: 'Simplification', difficulty: 'medium', question: 'What is the value of three-fourths of 640 minus two-fifths of 300?', options: ['360', '340', '350', '370'], correctIndex: 0, explanation: 'Three-fourths of 640 is 480, and two-fifths of 300 is 120. So 480 − 120 = 360.', source },
  { id: 'niacl-p-qa-005', section: 'Quantitative Aptitude', topic: 'Simplification', difficulty: 'medium', question: 'What is the value of (0.5 × 0.5) − (0.3 × 0.3)?', options: ['0.10', '0.16', '0.20', '0.25'], correctIndex: 1, explanation: '0.5 × 0.5 = 0.25 and 0.3 × 0.3 = 0.09, so the difference is 0.25 − 0.09 = 0.16.', source },
  { id: 'niacl-p-qa-006', section: 'Quantitative Aptitude', topic: 'Percentage', difficulty: 'easy', question: '528 is what percent of 660?', options: ['80%', '70%', '75%', '85%'], correctIndex: 0, explanation: '(528 / 660) × 100 = 80%.', source },
  { id: 'niacl-p-qa-007', section: 'Quantitative Aptitude', topic: 'Percentage', difficulty: 'medium', question: 'A number, when increased by 25%, becomes 375. Find the original number.', options: ['300', '280', '290', '310'], correctIndex: 0, explanation: 'Let the number be x. x × 1.25 = 375, so x = 375 / 1.25 = 300.', source },
  { id: 'niacl-p-qa-008', section: 'Quantitative Aptitude', topic: 'Percentage', difficulty: 'medium', question: 'A candidate scored 462 marks out of 660 in an exam. What percentage did the candidate score?', options: ['70%', '65%', '68%', '72%'], correctIndex: 0, explanation: '(462 / 660) × 100 = 70%.', source },
  { id: 'niacl-p-qa-009', section: 'Quantitative Aptitude', topic: 'Percentage', difficulty: 'hard', question: "If the price of an item is reduced by 20%, by what percent must the new price be increased to restore the original price?", options: ['20%', '25%', '30%', '35%'], correctIndex: 1, explanation: 'After a 20% reduction, the price becomes 80% of the original. To restore it, the increase needed is 20/80 × 100 = 25%.', source },
  { id: 'niacl-p-qa-010', section: 'Quantitative Aptitude', topic: 'Percentage', difficulty: 'hard', question: '30% of a number is 24 more than 15% of the same number. Find the number.', options: ['160', '140', '150', '170'], correctIndex: 0, explanation: 'Let the number be x. 0.3x − 0.15x = 24, so 0.15x = 24, giving x = 160.', source },
  { id: 'niacl-p-qa-011', section: 'Quantitative Aptitude', topic: 'Profit and Loss', difficulty: 'easy', question: 'An article with a cost price of ₹900 is sold for ₹1,035. Find the profit percentage.', options: ['15%', '10%', '12%', '18%'], correctIndex: 0, explanation: 'Profit = 1035 − 900 = 135. Profit percentage = (135 / 900) × 100 = 15%.', source },
  { id: 'niacl-p-qa-012', section: 'Quantitative Aptitude', topic: 'Profit and Loss', difficulty: 'medium', question: 'An article is sold at a loss of 18% for ₹861. Find its cost price.', options: ['₹1,050', '₹1,000', '₹1,025', '₹1,075'], correctIndex: 0, explanation: 'Selling price = 0.82 × Cost price. So Cost price = 861 / 0.82 = ₹1,050.', source },
  { id: 'niacl-p-qa-013', section: 'Quantitative Aptitude', topic: 'Profit and Loss', difficulty: 'hard', question: 'A shopkeeper marks an item 50% above its cost price and then offers a discount of 20% on the marked price. Find the resulting profit percentage.', options: ['15%', '20%', '18%', '22%'], correctIndex: 1, explanation: 'Marked price = 1.5 × Cost price. Selling price = 0.8 × 1.5 × Cost price = 1.2 × Cost price, giving a profit of 20%.', source },
  { id: 'niacl-p-qa-014', section: 'Quantitative Aptitude', topic: 'Ratio and Proportion', difficulty: 'easy', question: '₹810 is divided between two people in the ratio 4:5. Find the smaller share.', options: ['₹340', '₹360', '₹350', '₹370'], correctIndex: 1, explanation: 'Total parts = 4 + 5 = 9. The smaller share = (4/9) × 810 = ₹360.', source },
  { id: 'niacl-p-qa-015', section: 'Quantitative Aptitude', topic: 'Ratio and Proportion', difficulty: 'medium', question: 'If a:b = 3:4 and b:c = 4:5, find a:b:c.', options: ['3:4:5', '3:5:4', '4:3:5', '3:4:6'], correctIndex: 0, explanation: 'Since the value of b already matches in both ratios (4 = 4), the ratios combine directly to give a:b:c = 3:4:5.', source },
  { id: 'niacl-p-qa-016', section: 'Quantitative Aptitude', topic: 'Ratio and Proportion', difficulty: 'hard', question: 'If x:y = 4:5, find the value of (2x + 3y):(5x − 2y).', options: ['21:8', '23:10', '25:12', '19:8'], correctIndex: 1, explanation: 'Let x = 4k and y = 5k. Then 2x + 3y = 8k + 15k = 23k, and 5x − 2y = 20k − 10k = 10k, giving a ratio of 23:10.', source },
  { id: 'niacl-p-qa-017', section: 'Quantitative Aptitude', topic: 'Ratio and Proportion', difficulty: 'medium', question: '₹16,000 is divided among A, B, and C in the ratio 3:5:8. Find C\'s share.', options: ['₹6,000', '₹7,000', '₹9,000', '₹8,000'], correctIndex: 3, explanation: 'Total parts = 3 + 5 + 8 = 16. C\'s share = (8/16) × 16,000 = ₹8,000.', source },
  { id: 'niacl-p-qa-018', section: 'Quantitative Aptitude', topic: 'Average', difficulty: 'easy', question: 'The average of 5 numbers is 38. If one of the numbers, 28, is replaced by 58, find the new average.', options: ['40', '42', '46', '44'], correctIndex: 3, explanation: 'The original sum is 38 × 5 = 190. Replacing 28 with 58 changes the sum to 190 − 28 + 58 = 220. The new average is 220 / 5 = 44.', source },
  { id: 'niacl-p-qa-019', section: 'Quantitative Aptitude', topic: 'Average', difficulty: 'medium', question: 'The average age of 6 people is 26 years. A 7th person joins the group, and the new average becomes 27 years. Find the age of the 7th person.', options: ['31', '32', '34', '33'], correctIndex: 3, explanation: "The original total age is 26 × 6 = 156. The new total age is 27 × 7 = 189. The 7th person's age is 189 − 156 = 33 years.", source },
  { id: 'niacl-p-qa-020', section: 'Quantitative Aptitude', topic: 'Average', difficulty: 'medium', question: 'The average of three consecutive even numbers is 32. Find the largest of the three numbers.', options: ['30', '32', '36', '34'], correctIndex: 3, explanation: 'The three consecutive even numbers are 30, 32, and 34, whose average is (30+32+34)/3 = 32, so the largest is 34.', source },
  { id: 'niacl-p-qa-021', section: 'Quantitative Aptitude', topic: 'Simple and Compound Interest', difficulty: 'easy', question: 'Find the simple interest on ₹6,000 at 9% per annum for 3 years.', options: ['₹1,520', '₹1,570', '₹1,670', '₹1,620'], correctIndex: 3, explanation: 'Simple interest = (Principal × Rate × Time) / 100 = (6000 × 9 × 3) / 100 = ₹1,620.', source },
  { id: 'niacl-p-qa-022', section: 'Quantitative Aptitude', topic: 'Simple and Compound Interest', difficulty: 'medium', question: 'Find the compound interest on ₹9,000 at 10% per annum for 2 years, compounded annually.', options: ['₹1,790', '₹1,840', '₹1,940', '₹1,890'], correctIndex: 3, explanation: 'Amount = 9000 × 1.1 × 1.1 = ₹10,890. Compound interest = 10890 − 9000 = ₹1,890.', source },
  { id: 'niacl-p-qa-023', section: 'Quantitative Aptitude', topic: 'Simple and Compound Interest', difficulty: 'hard', question: 'A sum of money triples itself in 10 years at simple interest. Find the annual rate of interest.', options: ['15%', '18%', '22%', '20%'], correctIndex: 3, explanation: 'If the sum triples, the interest earned equals twice the principal (2P) over 10 years. Rate = (2P × 100) / (P × 10) = 20%.', source },
  { id: 'niacl-p-qa-024', section: 'Quantitative Aptitude', topic: 'Simple and Compound Interest', difficulty: 'hard', question: 'Find the difference between the simple interest and compound interest on ₹8,000 at 10% per annum for 2 years.', options: ['₹60', '₹70', '₹90', '₹80'], correctIndex: 3, explanation: 'Simple interest = (8000 × 10 × 2)/100 = ₹1,600. Compound interest: Amount = 8000 × 1.1 × 1.1 = ₹9,680, so CI = ₹1,680. The difference is ₹80.', source },
  { id: 'niacl-p-qa-025', section: 'Quantitative Aptitude', topic: 'Time and Work', difficulty: 'easy', question: 'A can complete a job in 10 days and B can complete the same job in 15 days. Working together, how many days will they take?', options: ['5 days', '6 days', '7 days', '8 days'], correctIndex: 1, explanation: 'Combined work rate = 1/10 + 1/15 = 3/30 + 2/30 = 5/30 of the job per day. Time taken = 30/5 = 6 days.', source },
  { id: 'niacl-p-qa-026', section: 'Quantitative Aptitude', topic: 'Time and Work', difficulty: 'medium', question: 'A can complete a piece of work alone in 15 days. He works alone for 5 days and then leaves. What fraction of the work is left unfinished?', options: ['1/3', '1/2', '2/3', '3/4'], correctIndex: 2, explanation: 'In 5 days, A completes 5/15 = 1/3 of the work, leaving 1 − 1/3 = 2/3 of the work unfinished.', source },
  { id: 'niacl-p-qa-027', section: 'Quantitative Aptitude', topic: 'Time and Work', difficulty: 'hard', question: 'A, B, and C can individually complete a piece of work in 12, 18, and 36 days respectively. Working together, how many days will they take to finish the work?', options: ['5 days', '6 days', '7 days', '8 days'], correctIndex: 1, explanation: 'Combined work rate = 1/12 + 1/18 + 1/36 = 3/36 + 2/36 + 1/36 = 6/36 = 1/6 of the job per day. Time taken = 6 days.', source },
  { id: 'niacl-p-qa-028', section: 'Quantitative Aptitude', topic: 'Time, Speed and Distance', difficulty: 'easy', question: 'A vehicle travels 400 km in 5 hours at a uniform speed. Find its speed in km/h.', options: ['70 km/h', '75 km/h', '80 km/h', '85 km/h'], correctIndex: 2, explanation: 'Speed = Distance / Time = 400 / 5 = 80 km/h.', source },
  { id: 'niacl-p-qa-029', section: 'Quantitative Aptitude', topic: 'Time, Speed and Distance', difficulty: 'medium', question: 'Convert a speed of 90 km/h into metres per second.', options: ['20 m/s', '22 m/s', '25 m/s', '28 m/s'], correctIndex: 2, explanation: 'To convert km/h to m/s, multiply by 5/18: 90 × 5/18 = 25 m/s.', source },
  { id: 'niacl-p-qa-030', section: 'Quantitative Aptitude', topic: 'Time, Speed and Distance', difficulty: 'hard', question: 'Two trains, 200 m and 150 m long, run in opposite directions on parallel tracks at 45 km/h each. Find the time they take to cross each other.', options: ['12 seconds', '13 seconds', '14 seconds', '15 seconds'], correctIndex: 2, explanation: 'Relative speed = 45 + 45 = 90 km/h = 25 m/s. Total length to cover = 200 + 150 = 350 m. Time = 350 / 25 = 14 seconds.', source },
  { id: 'niacl-p-qa-031', section: 'Quantitative Aptitude', topic: 'Number Series', difficulty: 'easy', question: 'Find the next number in the series: 5, 9, 15, 23, 33, ?', options: ['41', '43', '45', '47'], correctIndex: 2, explanation: 'The differences between consecutive terms increase by 2 each time (4, 6, 8, 10), so the next difference is 12, giving 33 + 12 = 45.', source },
  { id: 'niacl-p-qa-032', section: 'Quantitative Aptitude', topic: 'Number Series', difficulty: 'medium', question: 'Find the next number in the series: 3, 8, 17, 30, 47, ?', options: ['62', '65', '68', '71'], correctIndex: 2, explanation: 'The differences between consecutive terms increase by 4 each time (5, 9, 13, 17), so the next difference is 21, giving 47 + 21 = 68.', source },
  { id: 'niacl-p-qa-033', section: 'Quantitative Aptitude', topic: 'Number Series', difficulty: 'easy', question: 'Find the next number in the series: 5, 13, 29, 61, 125, ?', options: ['243', '248', '253', '258'], correctIndex: 2, explanation: 'Each term follows the rule (previous term × 2) + 3: 5×2+3=13, 13×2+3=29, ..., 125×2+3=253.', source },
  { id: 'niacl-p-qa-034', section: 'Quantitative Aptitude', topic: 'Mensuration', difficulty: 'easy', question: 'Find the area of a rectangle with length 18 m and breadth 10 m.', options: ['170 sq. m', '175 sq. m', '180 sq. m', '185 sq. m'], correctIndex: 2, explanation: 'Area of a rectangle = length × breadth = 18 × 10 = 180 sq. m.', source },
  { id: 'niacl-p-qa-035', section: 'Quantitative Aptitude', topic: 'Mensuration', difficulty: 'medium', question: 'Find the perimeter of a square with side 15 cm.', options: ['50 cm', '55 cm', '60 cm', '65 cm'], correctIndex: 2, explanation: 'Perimeter of a square = 4 × side = 4 × 15 = 60 cm.', source },
];
