import type { Question } from '../questions';

// NIACL AO (Generalist) Prelims: English Language, 30 questions.
// Qualifying stage only: Phase I marks do not carry forward into the final
// merit list, which is decided by the Phase II objective score plus interview.
const source = {
  kind: 'original' as const,
  reference: 'New India Assurance Co. Ltd: Recruitment of 550 Administrative Officers (Generalists & Specialists) 2025',
  url: 'https://www.newindia.co.in/assets/docs/recruitment/RECRUITMENT%20OF%20ADMINISTRATIVE%20OFFICERS%202025/RECRUITMENT%20OF%20_5_50%20ADMINISTRATIVE%20OFFICERS%20(GENERALISTS%20&%20SPECIALISTS)%20(SCALE-I)%20202_5.pdf',
  checkedOn: '6 August 2026',
};

export const NIACL_AO_PRELIMS_ENGLISH_LANGUAGE_1: Question[] = [
  { id: 'niacl-p-en-001', section: 'English Language', topic: 'Synonyms', difficulty: 'easy', question: 'Choose the word most similar in meaning to "METHODICAL".', options: ['Systematic and orderly', 'Random', 'Hasty', 'Careless'], correctIndex: 0, explanation: '"Methodical" describes something done in a systematic, orderly way.', source },
  { id: 'niacl-p-en-002', section: 'English Language', topic: 'Synonyms', difficulty: 'easy', question: 'Choose the word most similar in meaning to "MITIGATE".', options: ['Worsen', 'Ignore', 'Delay', 'Make less severe'], correctIndex: 3, explanation: '"Mitigate" means to make a problem or its effects less severe.', source },
  { id: 'niacl-p-en-003', section: 'English Language', topic: 'Synonyms', difficulty: 'medium', question: 'Choose the word most similar in meaning to "VIABLE".', options: ['Workable', 'Impossible', 'Expensive', 'Risky'], correctIndex: 0, explanation: '"Viable" means capable of working successfully, matching "workable".', source },
  { id: 'niacl-p-en-004', section: 'English Language', topic: 'Synonyms', difficulty: 'medium', question: 'Choose the word most similar in meaning to "SCRUTINIZE".', options: ['Ignore', 'Approve blindly', 'Summarize', 'Examine closely'], correctIndex: 3, explanation: '"Scrutinize" means to examine something closely and carefully.', source },
  { id: 'niacl-p-en-005', section: 'English Language', topic: 'Antonyms', difficulty: 'easy', question: 'Choose the word most opposite in meaning to "NEGLIGENT".', options: ['Careless', 'Forgetful', 'Slow', 'Careful'], correctIndex: 3, explanation: '"Negligent" means failing to take proper care; its opposite is "careful".', source },
  { id: 'niacl-p-en-006', section: 'English Language', topic: 'Antonyms', difficulty: 'medium', question: 'Choose the word most opposite in meaning to "VOLUNTARY" (as used for a scheme or contribution).', options: ['Optional', 'Willing', 'Compulsory', 'Generous'], correctIndex: 2, explanation: '"Voluntary" means done by free choice; its opposite is "compulsory", meaning required.', source },
  { id: 'niacl-p-en-007', section: 'English Language', topic: 'Antonyms', difficulty: 'medium', question: 'Choose the word most opposite in meaning to "COMPREHENSIVE" (as used for a policy\'s coverage).', options: ['Thorough', 'Complete', 'Limited', 'Detailed'], correctIndex: 2, explanation: 'A comprehensive policy covers a wide range of risks; its opposite is "limited", meaning restricted in scope.', source },
  { id: 'niacl-p-en-008', section: 'English Language', topic: 'Antonyms', difficulty: 'hard', question: 'Choose the word most opposite in meaning to "LIABLE" (as used for legal responsibility).', options: ['Accountable', 'Responsible', 'Exempt', 'Bound'], correctIndex: 2, explanation: '"Liable" means legally responsible for something; its opposite is "exempt", meaning free from an obligation.', source },
  { id: 'niacl-p-en-009', section: 'English Language', topic: 'Spelling Correction', difficulty: 'easy', question: 'Find the correctly spelled word among the four options below.', options: ['Neccessary', 'Neccesary', 'Necesary', 'Necessary'], correctIndex: 3, explanation: 'The correct spelling is "Necessary", with a single "c" and double "s".', source },
  { id: 'niacl-p-en-010', section: 'English Language', topic: 'Spelling Correction', difficulty: 'easy', question: 'From the four spellings given, mark the one that is correct.', options: ['Accomodate', 'Acommodate', 'Accommodate', 'Acomodate'], correctIndex: 2, explanation: 'The correct spelling is "Accommodate", with a double "c" and double "m".', source },
  { id: 'niacl-p-en-011', section: 'English Language', topic: 'Spelling Correction', difficulty: 'medium', question: 'Out of the four options, select the one with no spelling mistake.', options: ['Questionaire', 'Questionnairre', 'Questionnaire', 'Questionnare'], correctIndex: 2, explanation: 'The correct spelling is "Questionnaire", with a double "n".', source },
  { id: 'niacl-p-en-012', section: 'English Language', topic: 'Fill in the Blanks', difficulty: 'easy', question: 'Fill in the blank: "The surveyor ___ the damage before the claim was approved."', options: ['inspect', 'inspecting', 'inspects', 'inspected'], correctIndex: 3, explanation: 'The sentence describes a completed past action, so the simple past tense "inspected" is correct.', source },
  { id: 'niacl-p-en-013', section: 'English Language', topic: 'Fill in the Blanks', difficulty: 'medium', question: 'Fill in the blank: "Had the premium been paid on time, the discount ___ applied."', options: ['would have', 'will have', 'had', 'does'], correctIndex: 0, explanation: 'This is a third conditional sentence (had + past participle, ... would have + past participle), so "would have" is correct.', source },
  { id: 'niacl-p-en-014', section: 'English Language', topic: 'Fill in the Blanks', difficulty: 'medium', question: 'Fill in the blank: "Neither the agent nor the branch officers ___ aware of the revised guidelines."', options: ['was', 'is', 'has', 'were'], correctIndex: 3, explanation: 'With "neither...nor", the verb agrees with the subject nearer to it; "officers" is plural, so "were" is correct.', source },
  { id: 'niacl-p-en-015', section: 'English Language', topic: 'One Word Substitution', difficulty: 'medium', question: 'Choose the word that means "a person appointed to assess the extent of loss or damage for an insurance claim".', options: ['Surveyor', 'Beneficiary', 'Auditor', 'Notary'], correctIndex: 0, explanation: 'A surveyor is a professional appointed to inspect and assess loss or damage before an insurance claim is settled.', source },
  { id: 'niacl-p-en-016', section: 'English Language', topic: 'One Word Substitution', difficulty: 'medium', question: 'Choose the word that means "money paid periodically to keep an insurance policy in force".', options: ['Deductible', 'Indemnity', 'Rebate', 'Premium'], correctIndex: 3, explanation: 'The premium is the amount a policyholder pays, usually periodically, to keep a policy active.', source },
  { id: 'niacl-p-en-017', section: 'English Language', topic: 'Idioms and Phrases', difficulty: 'easy', question: 'Choose the meaning closest to the idiom "to read the fine print".', options: ['To read very quickly', 'To check the detailed conditions carefully', 'To skim through a document', 'To read aloud'], correctIndex: 1, explanation: '"To read the fine print" means to check the small, detailed conditions of an agreement carefully before accepting it.', source },
  { id: 'niacl-p-en-018', section: 'English Language', topic: 'Idioms and Phrases', difficulty: 'medium', question: 'Choose the meaning closest to the idiom "to be in the same boat".', options: ['To travel together', 'To be in a similar difficult situation', 'To agree on a decision', 'To compete against each other'], correctIndex: 1, explanation: '"To be in the same boat" means to be facing the same difficult situation or problem as someone else.', source },
  { id: 'niacl-p-en-019', section: 'English Language', topic: 'Error Spotting', difficulty: 'medium', question: 'Identify the part of the sentence that contains an error: "Each of the policyholders (A) / are required to renew (B) / their policy within (C) / thirty days of expiry. (D)"', options: ['Part A', 'Part B', 'Part C', 'No error'], correctIndex: 1, explanation: '"Each" is singular and takes a singular verb, so "are required" should be "is required".', source },
  { id: 'niacl-p-en-020', section: 'English Language', topic: 'Error Spotting', difficulty: 'medium', question: 'Identify the part of the sentence that contains an error: "The claims officer along with two assistants (A) / were reviewing (B) / the pending applications (C) / yesterday afternoon. (D)"', options: ['Part A', 'Part B', 'Part C', 'No error'], correctIndex: 1, explanation: 'With phrases like "along with", the verb agrees with the main subject "officer" (singular), so "were" should be "was".', source },
  { id: 'niacl-p-en-021', section: 'English Language', topic: 'Error Spotting', difficulty: 'hard', question: 'Identify the part of the sentence that contains an error: "Scarcely had the inspection begun (A) / when the surveyor\'s vehicle (B) / breaks down suddenly, (C) / delaying the entire process. (D)"', options: ['Part A', 'Part B', 'Part C', 'No error'], correctIndex: 2, explanation: 'With "scarcely...when", the second clause should also be in the past tense; "breaks" should be "broke" to match the narrative tense.', source },
  { id: 'niacl-p-en-022', section: 'English Language', topic: 'Sentence Improvement', difficulty: 'medium', question: 'Improve the underlined part: "The panel have finalised their decision on the appeal." (underline: "have finalised their")', options: ['has finalised its', 'have finalised its', 'has finalised their', 'No improvement needed'], correctIndex: 0, explanation: '"Panel" is treated as a singular collective noun here, so it takes the singular verb "has" and the singular possessive "its".', source },
  { id: 'niacl-p-en-023', section: 'English Language', topic: 'Sentence Improvement', difficulty: 'medium', question: 'Improve the underlined part: "She is one of the officer who always meets the deadline." (underline: "officer who always meets")', options: ['officers who always meet', 'officer who always meet', 'officers who always meets', 'No improvement needed'], correctIndex: 0, explanation: 'The phrase "one of the..." requires a plural noun ("officers"), and the relative clause verb agrees with that plural noun ("meet").', source },
  { id: 'niacl-p-en-024', section: 'English Language', topic: 'Reading Comprehension', difficulty: 'medium', question: 'Passage: "In general insurance, the premium charged for a policy depends on the assessed risk: a higher likelihood of a claim generally results in a higher premium, while a lower risk profile can qualify a policyholder for a discount." Based on the passage, a lower risk profile typically leads to:', options: ['A higher premium', 'No change in premium', 'A possible discount', 'Automatic claim rejection'], correctIndex: 2, explanation: 'The passage states that a lower risk profile can qualify a policyholder for a discount on the premium.', source },
  { id: 'niacl-p-en-025', section: 'English Language', topic: 'Reading Comprehension', difficulty: 'medium', question: 'Passage: "In general insurance, the premium charged for a policy depends on the assessed risk: a higher likelihood of a claim generally results in a higher premium, while a lower risk profile can qualify a policyholder for a discount." What does the premium primarily depend on, according to the passage?', options: ['The policyholder\'s age', 'The assessed risk', 'The size of the company', 'The date of purchase'], correctIndex: 1, explanation: 'The passage explicitly states that the premium charged depends on the assessed risk.', source },
  { id: 'niacl-p-en-026', section: 'English Language', topic: 'Cloze Test', difficulty: 'medium', question: 'Fill in the blank: "Before renewing a policy, a customer should carefully ___ the terms and conditions mentioned in the document."', options: ['ignore', 'review', 'discard', 'postpone'], correctIndex: 1, explanation: 'The sentence advises careful examination before a renewal decision, which matches "review".', source },
  { id: 'niacl-p-en-027', section: 'English Language', topic: 'Cloze Test', difficulty: 'medium', question: 'Fill in the blank: "The survey report was filed on time because the surveyor visited the site ___."', options: ['reluctantly', 'promptly', 'occasionally', 'incorrectly'], correctIndex: 1, explanation: 'A report filed on time follows from a site visit made without delay, matching "promptly".', source },
  { id: 'niacl-p-en-028', section: 'English Language', topic: 'Para Jumbles', difficulty: 'hard', question: 'Arrange the sentences in a logical order: (1) This reduces the financial loss the policyholder would otherwise bear. (2) General insurance provides protection against loss to property, health, or liability. (3) It is therefore an important tool for managing everyday financial risk. (4) The insurer compensates the policyholder for a covered loss, subject to the policy terms.', options: ['2, 4, 1, 3', '2, 1, 4, 3', '4, 2, 1, 3', '2, 3, 4, 1'], correctIndex: 0, explanation: 'The logical flow introduces the concept (2), explains the compensation mechanism (4), states the effect (1), and concludes with the significance (3).', source },
  { id: 'niacl-p-en-029', section: 'English Language', topic: 'Synonyms', difficulty: 'hard', question: 'Choose the word most similar in meaning to "EXPEDITE".', options: ['To delay', 'To speed up', 'To cancel', 'To postpone'], correctIndex: 1, explanation: '"Expedite" means to make a process happen faster, matching "to speed up".', source },
  { id: 'niacl-p-en-030', section: 'English Language', topic: 'Antonyms', difficulty: 'hard', question: 'Choose the word most opposite in meaning to "FRUGAL" (as used for spending habits).', options: ['Thrifty', 'Careful', 'Extravagant', 'Modest'], correctIndex: 2, explanation: '"Frugal" means careful and economical with money; its opposite is "extravagant", meaning spending lavishly.', source },
];
