import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'Original NISM Series V-A Mutual Fund Distributors practice questions in the official 4-option multiple-choice format, covering the NAV, returns, SIP, and compounding calculations that are independently verifiable by formula.',
  url: 'https://www.nism.ac.in/frequently-asked-questions-mutual-fund-distributors/',
  checkedOn: '15 August 2026',
};

export const NISM_SERIES_V_A_MUTUAL_FUND_DISTRIBUTORS_1: Question[] = [
  { id: 'nism-series-v-a-mutual-fund-distributors-01-001', section: 'NAV and Returns Calculations', topic: 'NAV Calculation', difficulty: 'easy', question: 'A mutual fund scheme has total assets of ₹50,00,000 and total liabilities of ₹2,00,000. If there are 4,80,000 units outstanding, what is the NAV per unit?', options: ['₹10', '₹9', '₹12', '₹11'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'NAV = (Total Assets − Total Liabilities) / Units Outstanding = (50,00,000 − 2,00,000) / 4,80,000 = 48,00,000 / 4,80,000 = ₹10.', source },
  { id: 'nism-series-v-a-mutual-fund-distributors-01-002', section: 'NAV and Returns Calculations', topic: 'Units Allotted', difficulty: 'easy', question: 'An investor invests ₹25,000 in a mutual fund scheme when the NAV is ₹25. How many units will be allotted?', options: ['900', '1000', '1250', '800'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Units allotted = Investment amount / NAV = 25,000 / 25 = 1,000.', source },
  { id: 'nism-series-v-a-mutual-fund-distributors-01-003', section: 'NAV and Returns Calculations', topic: 'Absolute Return', difficulty: 'easy', question: 'An investor purchased units at an NAV of ₹20 and redeemed them when the NAV was ₹25. What is the absolute return?', options: ['20%', '5%', '25%', '30%'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Absolute return = (25 − 20) / 20 = 5/20 = 25%.', source },
  { id: 'nism-series-v-a-mutual-fund-distributors-01-004', section: 'NAV and Returns Calculations', topic: 'Redemption Value', difficulty: 'easy', question: 'An investor holds 500 units of a mutual fund scheme. If the current NAV is ₹32.50, what is the redemption value of the holding?', options: ['₹15,000', '₹17,000', '₹16,000', '₹16,250'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Redemption value = Units × NAV = 500 × 32.50 = ₹16,250.', source },
  { id: 'nism-series-v-a-mutual-fund-distributors-01-005', section: 'NAV and Returns Calculations', topic: 'CAGR', difficulty: 'medium', question: 'An investment of ₹10,000 grew to ₹12,100 in 2 years. What is the CAGR (compound annual growth rate)?', options: ['10%', '21%', '5%', '12%'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'CAGR = (12,100 / 10,000)^(1/2) − 1 = (1.21)^0.5 − 1 = 1.10 − 1 = 10%.', source },
  { id: 'nism-series-v-a-mutual-fund-distributors-01-006', section: 'NAV and Returns Calculations', topic: 'Portfolio Valuation', difficulty: 'medium', question: 'An investor holds 200 units in Scheme A (NAV ₹40) and 150 units in Scheme B (NAV ₹60). What is the total portfolio value?', options: ['₹16,000', '₹17,000', '₹18,000', '₹15,000'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Portfolio value = (200 × 40) + (150 × 60) = 8,000 + 9,000 = ₹17,000.', source },
  { id: 'nism-series-v-a-mutual-fund-distributors-01-007', section: 'NAV and Returns Calculations', topic: 'Expense Ratio Impact', difficulty: 'medium', question: 'A mutual fund scheme generates a gross annual return of 12%. If the total expense ratio is 1.5%, what is the approximate net return to the investor?', options: ['13.5%', '12%', '10.5%', '9%'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Approximate net return = Gross return − Expense ratio = 12% − 1.5% = 10.5%.', source },
  { id: 'nism-series-v-a-mutual-fund-distributors-01-008', section: 'NAV and Returns Calculations', topic: 'Units to Redeem', difficulty: 'easy', question: 'An investor wants to redeem ₹9,000 from a scheme where the current NAV is ₹45. How many units need to be redeemed?', options: ['180', '220', '150', '200'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Units to redeem = Amount required / NAV = 9,000 / 45 = 200.', source },
  { id: 'nism-series-v-a-mutual-fund-distributors-01-009', section: 'NAV and Returns Calculations', topic: 'Holding Value Change', difficulty: 'medium', question: 'An investor holds 1,000 units purchased at an NAV of ₹18. After one year, the NAV is ₹21.60. What is the increase in the value of the holding?', options: ['₹3,600', '₹3,000', '₹2,160', '₹4,000'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Value before = 1,000 × 18 = ₹18,000. Value after = 1,000 × 21.60 = ₹21,600. Increase = ₹3,600.', source },
  { id: 'nism-series-v-a-mutual-fund-distributors-01-010', section: 'NAV and Returns Calculations', topic: 'Annualized Return', difficulty: 'medium', question: 'An investment grew by 8% over a 6-month period. What is the approximate simple annualized return?', options: ['8%', '16%', '4%', '24%'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Simple annualization doubles a 6-month return: 8% × 2 = 16%.', source },
  { id: 'nism-series-v-a-mutual-fund-distributors-01-011', section: 'SIP and Growth Calculations', topic: 'Rule of 72', difficulty: 'easy', question: 'Using the Rule of 72, approximately how many years will it take for an investment to double at an annual compounded return of 12%?', options: ['6 years', '8 years', '9 years', '12 years'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Rule of 72: doubling time ≈ 72 / annual return = 72 / 12 = 6 years.', source },
  { id: 'nism-series-v-a-mutual-fund-distributors-01-012', section: 'SIP and Growth Calculations', topic: 'SIP Total Investment', difficulty: 'easy', question: 'An investor starts a monthly SIP of ₹5,000 for 3 years. What is the total amount invested, before returns?', options: ['₹1,50,000', '₹1,80,000', '₹2,00,000', '₹1,60,000'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Total invested = Monthly amount × number of months = 5,000 × 36 = ₹1,80,000.', source },
  { id: 'nism-series-v-a-mutual-fund-distributors-01-013', section: 'SIP and Growth Calculations', topic: 'Rupee Cost Averaging', difficulty: 'medium', question: 'An investor invests a fixed amount each month for 4 months at NAVs of ₹10, ₹12, ₹8, and ₹10. What is the simple average of these four NAV figures?', options: ['₹11', '₹10.5', '₹10', '₹9.5'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Simple average = (10 + 12 + 8 + 10) / 4 = 40 / 4 = ₹10.', source },
  { id: 'nism-series-v-a-mutual-fund-distributors-01-014', section: 'SIP and Growth Calculations', topic: 'Compound Growth', difficulty: 'hard', question: '₹1,00,000 is invested for 3 years at an annual compounded return of 10%. Using (1.10)³ ≈ 1.331, what is the approximate maturity value?', options: ['₹1,30,000', '₹1,21,000', '₹1,40,000', '₹1,33,100'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Maturity value = Principal × (1.10)³ = 1,00,000 × 1.331 = ₹1,33,100.', source },
  { id: 'nism-series-v-a-mutual-fund-distributors-01-015', section: 'SIP and Growth Calculations', topic: 'CAGR', difficulty: 'hard', question: 'An investment of ₹8,000 grew to ₹9,261 in 3 years. Given that (1.05)³ = 1.157625, what is the CAGR?', options: ['5%', '15.76%', '10%', '7.5%'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: '9,261 / 8,000 = 1.157625 = (1.05)³, so the CAGR is 5%.', source },
  { id: 'nism-series-v-a-mutual-fund-distributors-01-016', section: 'SIP and Growth Calculations', topic: 'SIP Units Accumulated', difficulty: 'medium', question: 'An investor invests ₹2,000 every month for 5 months at a constant NAV of ₹20 each month. How many total units are accumulated?', options: ['400', '500', '450', '550'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Each month\'s units = 2,000 / 20 = 100. Over 5 months: 100 × 5 = 500 units.', source },
  { id: 'nism-series-v-a-mutual-fund-distributors-01-017', section: 'SIP and Growth Calculations', topic: 'CAGR', difficulty: 'hard', question: 'An investment doubled in value over 5 years. Using 2^(1/5) ≈ 1.1487, what is the approximate CAGR?', options: ['20%', '10%', '14.9%', '25%'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'CAGR = 2^(1/5) − 1 ≈ 1.1487 − 1 = 0.1487, or approximately 14.9%.', source },
  { id: 'nism-series-v-a-mutual-fund-distributors-01-018', section: 'SIP and Growth Calculations', topic: 'Simple vs Compound Interest', difficulty: 'medium', question: '₹50,000 is invested for 2 years. What is the difference between the maturity value at 10% simple interest per annum and 10% compound interest (annual compounding) per annum?', options: ['₹1,000', '₹250', '₹0', '₹500'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Simple interest maturity = 50,000 + (50,000 × 0.10 × 2) = ₹60,000. Compound interest maturity = 50,000 × (1.10)² = ₹60,500. Difference = ₹500.', source },
  { id: 'nism-series-v-a-mutual-fund-distributors-01-019', section: 'SIP and Growth Calculations', topic: 'Chained Annual Growth', difficulty: 'medium', question: 'A fund grows by 10% in year 1 and 20% in year 2, each on the new base. Starting with ₹10,000, what is the value at the end of year 2?', options: ['₹13,200', '₹13,000', '₹12,000', '₹13,300'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'After year 1: 10,000 × 1.10 = ₹11,000. After year 2: 11,000 × 1.20 = ₹13,200.', source },
  { id: 'nism-series-v-a-mutual-fund-distributors-01-020', section: 'SIP and Growth Calculations', topic: 'Absolute Return', difficulty: 'medium', question: 'Using the fund growth from the previous question (₹10,000 growing to ₹13,200 over 2 years), what is the total absolute return over the two years?', options: ['30%', '32%', '33%', '20%'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Absolute return = (13,200 − 10,000) / 10,000 = 3,200 / 10,000 = 32%.', source },
];
