import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'Original NMAT by GMAC practice questions in the official 4-option multiple-choice format, covering Language Skills, Logical Reasoning and Quantitative Skills. Second set, built to the same section proportions and difficulty mix as the first.',
  url: 'https://www.mba.com/exams/nmat',
  checkedOn: '18 September 2026',
};

export const NMAT_LANGUAGE_LOGICAL_REASONING_QUANTITATIVE_2: Question[] = [
  // Language Skills
  { id: 'nmat-lang-lr-quant-02-001', section: 'Language Skills', topic: 'Reading Comprehension: Main Idea', difficulty: 'easy', question: 'Passage: "When a factory automates a task, the saving is usually reported as the wage that is no longer paid. That figure is easy to compute and almost always wrong. The wage disappears, but so does the operator\'s informal knowledge of when the machine is about to fail, which nobody had written down because nobody had been asked to. Plants that automate well tend to be the ones that spend a year recording what their operators already know before installing anything. Plants that automate badly find the gap only when the first unplanned stoppage runs longer than the manual process ever did." Which of the following best states the main idea of the passage?', options: ['Reported savings from automation leave out the operator knowledge that is lost with the job', 'Automation rarely saves a factory any money at all', 'Machines fail more often than the operators they replace', 'Factories should record operator knowledge in order to reduce wages'], correctIndex: 0, answerType: 'mcq', marks: 3, negativeMarking: 0, explanation: 'The passage accepts that the wage is saved but argues the figure is wrong because it ignores the undocumented knowledge that goes with the worker. It never claims automation saves nothing, nor that machines fail more often.', source },
  { id: 'nmat-lang-lr-quant-02-002', section: 'Language Skills', topic: 'Reading Comprehension: Detail', difficulty: 'easy', question: 'Passage: "When a factory automates a task, the saving is usually reported as the wage that is no longer paid. That figure is easy to compute and almost always wrong. The wage disappears, but so does the operator\'s informal knowledge of when the machine is about to fail, which nobody had written down because nobody had been asked to. Plants that automate well tend to be the ones that spend a year recording what their operators already know before installing anything. Plants that automate badly find the gap only when the first unplanned stoppage runs longer than the manual process ever did." According to the passage, what do plants that automate well do first?', options: ['They replace the oldest machines before the newest ones', 'They spend a year recording what their operators already know', 'They retain the operators on a reduced wage', 'They wait for the first unplanned stoppage before installing anything'], correctIndex: 1, answerType: 'mcq', marks: 3, negativeMarking: 0, explanation: 'The passage says such plants "spend a year recording what their operators already know before installing anything". The stoppage is what happens to the plants that automate badly.', source },
  { id: 'nmat-lang-lr-quant-02-003', section: 'Language Skills', topic: 'Reading Comprehension: Inference', difficulty: 'medium', question: 'Passage: "When a factory automates a task, the saving is usually reported as the wage that is no longer paid. That figure is easy to compute and almost always wrong. The wage disappears, but so does the operator\'s informal knowledge of when the machine is about to fail, which nobody had written down because nobody had been asked to. Plants that automate well tend to be the ones that spend a year recording what their operators already know before installing anything. Plants that automate badly find the gap only when the first unplanned stoppage runs longer than the manual process ever did." Which of the following is most strongly supported by the passage?', options: ['Unplanned stoppages are shorter in automated plants than in manual ones', 'Operators deliberately withhold what they know from their employers', 'A plant that automates without recording operator knowledge is more exposed to long stoppages', 'The wage saving from automation is impossible to calculate'], correctIndex: 2, answerType: 'mcq', marks: 3, negativeMarking: 0, explanation: 'The closing sentence ties automating badly, which is automating without the recording step, to a first stoppage that runs longer than the manual process. The passage says the knowledge went unwritten because nobody asked, not because anyone withheld it.', source },
  { id: 'nmat-lang-lr-quant-02-004', section: 'Language Skills', topic: 'Reading Comprehension: Vocabulary in Context', difficulty: 'medium', question: 'Passage: "When a factory automates a task, the saving is usually reported as the wage that is no longer paid. That figure is easy to compute and almost always wrong. The wage disappears, but so does the operator\'s informal knowledge of when the machine is about to fail, which nobody had written down because nobody had been asked to. Plants that automate well tend to be the ones that spend a year recording what their operators already know before installing anything. Plants that automate badly find the gap only when the first unplanned stoppage runs longer than the manual process ever did." In the passage, "informal" is closest in meaning to:', options: ['Casual', 'Friendly', 'Imprecise', 'Unwritten'], correctIndex: 3, answerType: 'mcq', marks: 3, negativeMarking: 0, explanation: 'The passage itself glosses the word in the clause that follows: the knowledge "nobody had written down". The other three are ordinary senses of informal that the sentence does not support.', source },
  { id: 'nmat-lang-lr-quant-02-005', section: 'Language Skills', topic: 'Vocabulary: Synonym', difficulty: 'easy', question: 'Choose the word most similar in meaning to \'Prudent\':', options: ['Cautious', 'Generous', 'Hasty', 'Wealthy'], correctIndex: 0, answerType: 'mcq', marks: 3, negativeMarking: 0, explanation: 'Prudent describes someone who acts with care and foresight, which is what cautious means. Hasty is close to its opposite.', source },
  { id: 'nmat-lang-lr-quant-02-006', section: 'Language Skills', topic: 'Vocabulary: Antonym', difficulty: 'medium', question: 'Choose the word opposite in meaning to \'Lucid\':', options: ['Clear', 'Obscure', 'Bright', 'Simple'], correctIndex: 1, answerType: 'mcq', marks: 3, negativeMarking: 0, explanation: 'Lucid means easy to understand, so obscure is its opposite. Clear and simple are close to it in meaning, and bright picks up only its secondary sense of shining.', source },
  { id: 'nmat-lang-lr-quant-02-007', section: 'Language Skills', topic: 'Grammar', difficulty: 'medium', question: 'Fill in the blank: One of the quarterly reports ___ still missing from the file.', options: ['are', 'were', 'is', 'have been'], correctIndex: 2, answerType: 'mcq', marks: 3, negativeMarking: 0, explanation: 'The subject of the sentence is "one", which is singular, so the verb is "is". The plural "reports" belongs to the prepositional phrase and does not govern the verb.', source },
  { id: 'nmat-lang-lr-quant-02-008', section: 'Language Skills', topic: 'Sentence Correction', difficulty: 'medium', question: 'Choose the correctly constructed sentence.', options: ['Walking through the factory, the noise was deafening', 'Walking through the factory, deafening noise was heard', 'The noise was deafening, walking through the factory', 'Walking through the factory, we found the noise deafening'], correctIndex: 3, answerType: 'mcq', marks: 3, negativeMarking: 0, explanation: 'The opening participle must describe the subject of the main clause. Only the last sentence supplies a subject, "we", that can do the walking; in the others the noise is left doing it.', source },
  { id: 'nmat-lang-lr-quant-02-009', section: 'Language Skills', topic: 'Para Jumble', difficulty: 'medium', question: 'Arrange the sentences into a coherent paragraph. P: The first commercial container ship sailed in 1956. Q: Before it, cargo was loaded piece by piece by hand. R: A single crossing could take weeks to load and unload. S: The box cut that work to hours.', options: ['P Q R S', 'Q R P S', 'P R Q S', 'Q P R S'], correctIndex: 0, answerType: 'mcq', marks: 3, negativeMarking: 0, explanation: 'P introduces the ship, Q refers back to it as "it" and describes what came before, R elaborates on that older method, and S closes with the contrast the whole paragraph is building towards.', source },
  { id: 'nmat-lang-lr-quant-02-010', section: 'Language Skills', topic: 'Prepositions', difficulty: 'easy', question: 'Fill in the blank: She was appointed ___ the post of deputy director last month.', options: ['at', 'to', 'for', 'in'], correctIndex: 1, answerType: 'mcq', marks: 3, negativeMarking: 0, explanation: 'A person is appointed to a post. "Appointed for" would introduce a purpose rather than a position.', source },
  { id: 'nmat-lang-lr-quant-02-011', section: 'Language Skills', topic: 'One-word Substitution', difficulty: 'medium', question: 'Select the word that means \'a person who remains unmoved by pleasure or pain\':', options: ['Cynic', 'Sceptic', 'Stoic', 'Ascetic'], correctIndex: 2, answerType: 'mcq', marks: 3, negativeMarking: 0, explanation: 'A stoic endures both without complaint. A cynic distrusts motives, a sceptic doubts claims, and an ascetic gives up comforts by choice, which is a different idea from being unmoved by them.', source },
  { id: 'nmat-lang-lr-quant-02-012', section: 'Language Skills', topic: 'Commonly Confused Words', difficulty: 'easy', question: 'Fill in the blank: The two colours ___ each other well in the new brand palette.', options: ['compliment', 'complements', 'compliments', 'complement'], correctIndex: 3, answerType: 'mcq', marks: 3, negativeMarking: 0, explanation: 'To complement is to complete or go well with; to compliment is to praise. The subject "colours" is plural, so the verb takes no s.', source },
  // Logical Reasoning
  { id: 'nmat-lang-lr-quant-02-013', section: 'Logical Reasoning', topic: 'Seating Arrangement', difficulty: 'medium', question: 'Six colleagues A, B, C, D, E and F sit in a row facing north. C sits at one of the ends. A sits third to the right of C. B sits immediately to the left of E. D does not sit next to A. E sits somewhere to the right of D. Who sits at the extreme right end?', options: ['E', 'A', 'B', 'C'], correctIndex: 0, answerType: 'mcq', marks: 3, negativeMarking: 0, explanation: 'C must be at the left end for A to sit three places to its right, which puts A fourth. B and E take the fifth and sixth seats in that order, since the only other adjacent pair left would put E to the left of D. That leaves D second, F third, and E at the right end.', source },
  { id: 'nmat-lang-lr-quant-02-014', section: 'Logical Reasoning', topic: 'Seating Arrangement', difficulty: 'medium', question: 'Using the same seating arrangement, how many colleagues sit between F and B?', options: ['0', '1', '2', '3'], correctIndex: 1, answerType: 'mcq', marks: 3, negativeMarking: 0, explanation: 'F is third and B is fifth in the row, so only the colleague in the fourth seat, A, sits between them.', source },
  { id: 'nmat-lang-lr-quant-02-015', section: 'Logical Reasoning', topic: 'Seating Arrangement', difficulty: 'medium', question: 'Using the same seating arrangement, who sits immediately to the left of A?', options: ['B', 'D', 'F', 'C'], correctIndex: 2, answerType: 'mcq', marks: 3, negativeMarking: 0, explanation: 'A occupies the fourth seat and F the third, so F sits immediately to the left of A.', source },
  { id: 'nmat-lang-lr-quant-02-016', section: 'Logical Reasoning', topic: 'Blood Relations', difficulty: 'medium', question: 'Pointing to a girl, Rahul said, "She is the daughter of the only sister of my father." How is the girl related to Rahul?', options: ['His sister', 'His niece', 'His aunt', 'His cousin'], correctIndex: 3, answerType: 'mcq', marks: 3, negativeMarking: 0, explanation: 'The only sister of Rahul\'s father is his aunt, and the aunt\'s daughter is his cousin.', source },
  { id: 'nmat-lang-lr-quant-02-017', section: 'Logical Reasoning', topic: 'Coding-Decoding', difficulty: 'hard', question: 'In a certain code, \'MANGO\' is written as 13-1-14-7-15. How is \'PEAR\' written in that code?', options: ['16-5-1-18', '15-5-1-18', '16-4-1-17', '16-5-2-18'], correctIndex: 0, answerType: 'mcq', marks: 3, negativeMarking: 0, explanation: 'Each letter is replaced by its position in the alphabet, as M gives 13 and O gives 15. P, E, A and R are the 16th, 5th, 1st and 18th letters.', source },
  { id: 'nmat-lang-lr-quant-02-018', section: 'Logical Reasoning', topic: 'Syllogism', difficulty: 'medium', question: 'Statements: All books are papers. No paper is plastic. Conclusions: I. No book is plastic. II. Some papers are books. Which conclusions follow?', options: ['Only conclusion I follows', 'Both conclusions follow', 'Only conclusion II follows', 'Neither conclusion follows'], correctIndex: 1, answerType: 'mcq', marks: 3, negativeMarking: 0, explanation: 'Every book is a paper and no paper is plastic, so no book can be plastic, which gives conclusion I. Conclusion II is the first statement read the other way round, which also holds.', source },
  { id: 'nmat-lang-lr-quant-02-019', section: 'Logical Reasoning', topic: 'Number Series', difficulty: 'medium', question: 'Find the next number in the series: 7, 10, 16, 28, 52, ?', options: ['84', '96', '100', '104'], correctIndex: 2, answerType: 'mcq', marks: 3, negativeMarking: 0, explanation: 'The differences are 3, 6, 12 and 24, each double the one before, so the next difference is 48 and the next term is 52 + 48, that is 100.', source },
  { id: 'nmat-lang-lr-quant-02-020', section: 'Logical Reasoning', topic: 'Analogy', difficulty: 'easy', question: 'Ornithologist is to Birds as Entomologist is to ?', options: ['Fish', 'Plants', 'Reptiles', 'Insects'], correctIndex: 3, answerType: 'mcq', marks: 3, negativeMarking: 0, explanation: 'An ornithologist studies birds and an entomologist studies insects. Fish belong to an ichthyologist, plants to a botanist and reptiles to a herpetologist.', source },
  { id: 'nmat-lang-lr-quant-02-021', section: 'Logical Reasoning', topic: 'Direction Sense', difficulty: 'medium', question: 'A surveyor walks 5 km due south and then 12 km due east. How far is the surveyor from the starting point?', options: ['13 km', '15 km', '17 km', '19 km'], correctIndex: 0, answerType: 'mcq', marks: 3, negativeMarking: 0, explanation: 'The two legs are at right angles, so the distance is the square root of 25 + 144, that is 13 km. Adding the legs would give 17 km, which is the path length rather than the displacement.', source },
  { id: 'nmat-lang-lr-quant-02-022', section: 'Logical Reasoning', topic: 'Critical Reasoning', difficulty: 'hard', question: 'A hospital introduced a new triage system, and average waiting time fell by 20% over the following quarter. The administrator concluded that the triage system caused the fall. Which finding, if true, most weakens that conclusion?', options: ['Waiting time is measured from arrival rather than from first assessment', 'The hospital opened two additional consultation rooms in the same quarter', 'Staff reported that the new system was simple to follow', 'A neighbouring hospital saw waiting times rise over the same quarter'], correctIndex: 1, answerType: 'mcq', marks: 3, negativeMarking: 0, explanation: 'A second change made at the same time could account for the fall on its own, which is what breaks the link between the triage system and the result. The neighbouring hospital rising, if anything, supports the conclusion rather than weakening it.', source },
  { id: 'nmat-lang-lr-quant-02-023', section: 'Logical Reasoning', topic: 'Statement and Assumption', difficulty: 'medium', question: 'A publisher is discontinuing its print edition because online readership now exceeds print readership. Which assumption is this decision based on?', options: ['Print production costs have risen faster than online costs', 'Online readership will continue to grow every year', 'Most print readers will continue reading the publication online', 'No competitor still publishes a print edition'], correctIndex: 2, answerType: 'mcq', marks: 3, negativeMarking: 0, explanation: 'The decision only makes sense if ending print does not simply lose those readers. The other three might each be true without being needed for the reasoning to hold.', source },
  { id: 'nmat-lang-lr-quant-02-024', section: 'Logical Reasoning', topic: 'Classification', difficulty: 'easy', question: 'Three of the following four belong to one group. Which one does not belong: Triangle, Rectangle, Pentagon, Cylinder?', options: ['Triangle', 'Rectangle', 'Pentagon', 'Cylinder'], correctIndex: 3, answerType: 'mcq', marks: 3, negativeMarking: 0, explanation: 'A triangle, a rectangle and a pentagon are plane figures bounded by straight sides. A cylinder is a solid, and it has no sides of that kind.', source },
  // Quantitative Skills
  { id: 'nmat-lang-lr-quant-02-025', section: 'Quantitative Skills', topic: 'Partnership', difficulty: 'easy', question: 'A invests ₹25,000 for 12 months and B invests ₹20,000 for 9 months. If the annual profit is ₹40,000, what is B\'s share?', options: ['₹15,000', '₹16,000', '₹20,000', '₹25,000'], correctIndex: 0, answerType: 'mcq', marks: 3, negativeMarking: 0, explanation: 'Capital multiplied by time gives 300,000 for A and 180,000 for B, a ratio of 5 to 3. B therefore takes three eighths of ₹40,000, which is ₹15,000, and A takes ₹25,000.', source },
  { id: 'nmat-lang-lr-quant-02-026', section: 'Quantitative Skills', topic: 'Successive Discounts', difficulty: 'medium', question: 'An article marked at ₹2,500 is sold after successive discounts of 20% and 10%. What is the selling price?', options: ['₹1,750', '₹1,800', '₹1,850', '₹1,875'], correctIndex: 1, answerType: 'mcq', marks: 3, negativeMarking: 0, explanation: 'The first discount leaves ₹2,000 and the second leaves 90% of that, which is ₹1,800. A single discount of 25% would give ₹1,875, which is why successive discounts do not simply add.', source },
  { id: 'nmat-lang-lr-quant-02-027', section: 'Quantitative Skills', topic: 'Time and Work', difficulty: 'medium', question: 'A can finish a job in 20 days and B in 30 days. They work together for 5 days, after which A leaves. How many more days does B need to finish the job?', options: ['12.5 days', '15 days', '17.5 days', '20 days'], correctIndex: 2, answerType: 'mcq', marks: 3, negativeMarking: 0, explanation: 'Together they do one twelfth of the job a day, so 5 days completes five twelfths. The remaining seven twelfths at B\'s rate of one thirtieth a day takes 17.5 days.', source },
  { id: 'nmat-lang-lr-quant-02-028', section: 'Quantitative Skills', topic: 'Pipes and Cisterns', difficulty: 'medium', question: 'A pipe fills a tank in 6 hours while an outlet empties it in 9 hours. If both are opened together on an empty tank, how long will it take to fill?', options: ['3.6 hours', '9 hours', '15 hours', '18 hours'], correctIndex: 3, answerType: 'mcq', marks: 3, negativeMarking: 0, explanation: 'In one hour the tank gains one sixth less one ninth, which is one eighteenth, so filling takes 18 hours.', source },
  { id: 'nmat-lang-lr-quant-02-029', section: 'Quantitative Skills', topic: 'Mixtures and Alligation', difficulty: 'medium', question: 'In what ratio must tea costing ₹80 per kg be mixed with tea costing ₹100 per kg so that the mixture costs ₹86 per kg?', options: ['7:3', '3:7', '5:3', '2:1'], correctIndex: 0, answerType: 'mcq', marks: 3, negativeMarking: 0, explanation: 'By alligation the ratio is the distance from the dearer price to the mean against the distance from the mean to the cheaper price, that is (100 − 86) to (86 − 80), or 7 to 3.', source },
  { id: 'nmat-lang-lr-quant-02-030', section: 'Quantitative Skills', topic: 'Probability', difficulty: 'medium', question: 'A bag holds 4 red, 5 green and 3 blue balls. One ball is drawn at random. What is the probability that it is red or blue?', options: ['1/4', '7/12', '2/3', '3/4'], correctIndex: 1, answerType: 'mcq', marks: 3, negativeMarking: 0, explanation: 'There are 7 favourable balls out of 12, giving 7/12. The value 1/4 is the probability of drawing a blue ball alone.', source },
  { id: 'nmat-lang-lr-quant-02-031', section: 'Quantitative Skills', topic: 'Mensuration', difficulty: 'medium', question: 'Find the area of a rhombus whose diagonals measure 16 cm and 12 cm.', options: ['48 cm²', '72 cm²', '96 cm²', '192 cm²'], correctIndex: 2, answerType: 'mcq', marks: 3, negativeMarking: 0, explanation: 'The area of a rhombus is half the product of its diagonals, which is half of 192, that is 96 cm². Omitting the half gives 192.', source },
  { id: 'nmat-lang-lr-quant-02-032', section: 'Quantitative Skills', topic: 'Arithmetic Progression', difficulty: 'medium', question: 'Find the sum of the first 20 terms of an arithmetic progression whose first term is 3 and whose common difference is 5.', options: ['950', '980', '1,000', '1,010'], correctIndex: 3, answerType: 'mcq', marks: 3, negativeMarking: 0, explanation: 'The sum is 10 times (2 × 3 + 19 × 5), which is 10 × 101, that is 1,010.', source },
  { id: 'nmat-lang-lr-quant-02-033', section: 'Quantitative Skills', topic: 'LCM and HCF', difficulty: 'easy', question: 'What is the least common multiple of 12, 18 and 24?', options: ['72', '96', '108', '144'], correctIndex: 0, answerType: 'mcq', marks: 3, negativeMarking: 0, explanation: 'Taking the highest power of each prime gives 2³ × 3², which is 72.', source },
  { id: 'nmat-lang-lr-quant-02-034', section: 'Quantitative Skills', topic: 'Data Interpretation', difficulty: 'medium', question: 'A company recorded monthly sales (in ₹ lakh) of January 40, February 55, March 50, April 70 and May 60. What is the average monthly sales figure?', options: ['50', '55', '60', '65'], correctIndex: 1, answerType: 'mcq', marks: 3, negativeMarking: 0, explanation: 'The five months total ₹275 lakh, and 275 divided by 5 is ₹55 lakh.', source },
  { id: 'nmat-lang-lr-quant-02-035', section: 'Quantitative Skills', topic: 'Data Interpretation', difficulty: 'medium', question: 'Using the same sales figures (January 40, February 55, March 50, April 70, May 60, in ₹ lakh), by what percentage do April sales exceed March sales?', options: ['20%', '28.6%', '40%', '42.9%'], correctIndex: 2, answerType: 'mcq', marks: 3, negativeMarking: 0, explanation: 'The rise is 20 on a March base of 50, which is 40%. Dividing by the April figure instead would give 28.6%, but the base must be the earlier month.', source },
  { id: 'nmat-lang-lr-quant-02-036', section: 'Quantitative Skills', topic: 'Algebra', difficulty: 'hard', question: 'If x + 1/x = 4, what is the value of x³ + 1/x³?', options: ['16', '40', '48', '52'], correctIndex: 3, answerType: 'mcq', marks: 3, negativeMarking: 0, explanation: 'Cubing gives (x + 1/x)³ = x³ + 1/x³ + 3(x + 1/x), so x³ + 1/x³ is 64 − 12, that is 52.', source },
];
