import type { Question } from '../questions';

export const NVS_TGT_MATHEMATICS_2025_TIER_1_ENGLISH_1: Question[] = [
  { id: 'b13-002-en-q01', section: 'Language Competency Test (English)', topic: 'Parallelism', difficulty: 'medium', question: 'Choose the sentence with correct parallel structure.', options: ['The role requires planning lessons, to assess work, and guiding students.', 'The role requires plan lessons, assessing work, and to guide students.', 'The role requiring planning, assess, and guidance.', 'The role requires planning lessons, assessing work, and guiding students.'], correctIndex: 3, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: '“The role requires planning lessons, assessing work, and guiding students.” is the option that correctly completes or interprets the language task.', source: { kind: 'original', reference: 'CBSE KVS/NVS Recruitment Notification 01/2025', url: 'https://www.cbse.gov.in/cbsenew/documents/Detailed_Notification_KVS_NVS_2025_13112025.pdf', checkedOn: '2026-09-09' } },
  { id: 'b13-002-en-q02', section: 'Language Competency Test (English)', topic: 'Conditional', difficulty: 'medium', question: 'Complete: “If the server ___ earlier, we would have restored the file sooner.”', options: ['had responded', 'responds', 'would respond', 'has responding'], correctIndex: 0, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: '“had responded” is the option that correctly completes or interprets the language task.', source: { kind: 'original', reference: 'CBSE KVS/NVS Recruitment Notification 01/2025', url: 'https://www.cbse.gov.in/cbsenew/documents/Detailed_Notification_KVS_NVS_2025_13112025.pdf', checkedOn: '2026-09-09' } },
  { id: 'b13-002-en-q03', section: 'Language Competency Test (English)', topic: 'Vocabulary', difficulty: 'medium', question: 'Choose the word closest in meaning to “prudent”.', options: ['reckless', 'wise and careful', 'temporary', 'noisy'], correctIndex: 1, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: '“wise and careful” is the option that correctly completes or interprets the language task.', source: { kind: 'original', reference: 'CBSE KVS/NVS Recruitment Notification 01/2025', url: 'https://www.cbse.gov.in/cbsenew/documents/Detailed_Notification_KVS_NVS_2025_13112025.pdf', checkedOn: '2026-09-09' } },
  { id: 'b13-002-en-q04', section: 'Language Competency Test (English)', topic: 'Idiom', difficulty: 'medium', question: '“To draw the line” most nearly means __.', options: ['to make a sketch', 'to delay indefinitely', 'to set a limit', 'to copy a sentence'], correctIndex: 2, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: '“to set a limit” is the option that correctly completes or interprets the language task.', source: { kind: 'original', reference: 'CBSE KVS/NVS Recruitment Notification 01/2025', url: 'https://www.cbse.gov.in/cbsenew/documents/Detailed_Notification_KVS_NVS_2025_13112025.pdf', checkedOn: '2026-09-09' } },
  { id: 'b13-002-en-q05', section: 'Language Competency Test (English)', topic: 'Modifier', difficulty: 'medium', question: 'Choose the sentence with the modifier placed clearly.', options: ['Walking to the hall, the new notice board was noticed by Neha.', 'Neha noticed, walking to the hall the new notice board.', 'The hall walking, Neha noticed the board.', 'Walking to the hall, Neha noticed the new notice board.'], correctIndex: 3, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: '“Walking to the hall, Neha noticed the new notice board.” is the option that correctly completes or interprets the language task.', source: { kind: 'original', reference: 'CBSE KVS/NVS Recruitment Notification 01/2025', url: 'https://www.cbse.gov.in/cbsenew/documents/Detailed_Notification_KVS_NVS_2025_13112025.pdf', checkedOn: '2026-09-09' } },
  { id: 'b13-002-en-q06', section: 'Language Competency Test (English)', topic: 'Reported speech', difficulty: 'medium', question: 'Choose the correct reported form: Ravi said, “I am ready.”', options: ['Ravi said that he was ready.', 'Ravi said that I am ready.', 'Ravi says he had ready.', 'Ravi said that he is being ready yesterday.'], correctIndex: 0, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: '“Ravi said that he was ready.” is the option that correctly completes or interprets the language task.', source: { kind: 'original', reference: 'CBSE KVS/NVS Recruitment Notification 01/2025', url: 'https://www.cbse.gov.in/cbsenew/documents/Detailed_Notification_KVS_NVS_2025_13112025.pdf', checkedOn: '2026-09-09' } },
  { id: 'b13-002-en-q07', section: 'Language Competency Test (English)', topic: 'Word usage', difficulty: 'medium', question: 'Choose the sentence using “affect” correctly.', options: ['The affect of rain was visible.', 'Lack of sleep can affect concentration.', 'The rule had no affect on attendance.', 'Her affect was to improve the file.'], correctIndex: 1, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: '“Lack of sleep can affect concentration.” is the option that correctly completes or interprets the language task.', source: { kind: 'original', reference: 'CBSE KVS/NVS Recruitment Notification 01/2025', url: 'https://www.cbse.gov.in/cbsenew/documents/Detailed_Notification_KVS_NVS_2025_13112025.pdf', checkedOn: '2026-09-09' } },
  { id: 'b13-002-en-q08', section: 'Language Competency Test (English)', topic: 'Conjunction', difficulty: 'medium', question: 'Complete: “The report was brief, ___ it covered every required point.”', options: ['because of', 'unless', 'yet', 'therefore because'], correctIndex: 2, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: '“yet” is the option that correctly completes or interprets the language task.', source: { kind: 'original', reference: 'CBSE KVS/NVS Recruitment Notification 01/2025', url: 'https://www.cbse.gov.in/cbsenew/documents/Detailed_Notification_KVS_NVS_2025_13112025.pdf', checkedOn: '2026-09-09' } },
  { id: 'b13-002-en-q09', section: 'Language Competency Test (English)', topic: 'Voice', difficulty: 'medium', question: 'Choose the active form of “The forms were checked by the clerk.”', options: ['The forms checked the clerk.', 'The clerk was checked by the forms.', 'The forms had checking clerk.', 'The clerk checked the forms.'], correctIndex: 3, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: '“The clerk checked the forms.” is the option that correctly completes or interprets the language task.', source: { kind: 'original', reference: 'CBSE KVS/NVS Recruitment Notification 01/2025', url: 'https://www.cbse.gov.in/cbsenew/documents/Detailed_Notification_KVS_NVS_2025_13112025.pdf', checkedOn: '2026-09-09' } },
  { id: 'b13-002-en-q10', section: 'Language Competency Test (English)', topic: 'Cohesion', difficulty: 'medium', question: 'Which connector best completes: “The first method is faster; ___, the second is more accurate.”', options: ['however', 'therefore', 'similarly because', 'for example only'], correctIndex: 0, answerType: 'mcq', marks: 3, negativeMarking: 1, explanation: '“however” is the option that correctly completes or interprets the language task.', source: { kind: 'original', reference: 'CBSE KVS/NVS Recruitment Notification 01/2025', url: 'https://www.cbse.gov.in/cbsenew/documents/Detailed_Notification_KVS_NVS_2025_13112025.pdf', checkedOn: '2026-09-09' } },
];
