import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'Original PTE Academic Reading practice questions in the official Multiple Choice, Choose Single Answer format, where one option of four is correct. Second set, built to the same length as the first.',
  url: 'https://www.pearsonpte.com/pte-academic/format',
  checkedOn: '17 September 2026',
};

const read = (text: string, q: string) => `Read the passage and answer the question that follows.\n\n${text}\n\nQuestion: ${q}`;

export const PTE_READING_MULTIPLE_CHOICE_SINGLE_ANSWER_2: Question[] = [
  { id: 'pte-reading-mcsa-02-001', section: 'Multiple Choice: Single Answer', topic: 'Main Idea', difficulty: 'medium', question: read('Night-shift lighting trials in three hospitals replaced overhead fluorescent panels with tunable fixtures that shift towards warmer tones after midnight. Staff reported falling asleep more easily at the end of a shift, and error rates on medication checks were unchanged. The trial teams were careful to note that the units volunteering for the trial already had lower error rates than the hospitals as a whole, so the second finding says less than it appears to.', 'What is the main point of the passage?'), options: ['The lighting change improved sleep after shifts, while the error finding is weakened by how the units were selected', 'The lighting change reduced medication errors across all three hospitals', 'Warmer lighting was found to disrupt sleep in night-shift staff', 'The trials proved that fluorescent lighting causes medication errors'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage reports the sleep benefit and then qualifies the error result by noting the volunteering units were already unrepresentative.', source },
  { id: 'pte-reading-mcsa-02-002', section: 'Multiple Choice: Single Answer', topic: 'Detail', difficulty: 'easy', question: read('The city archive will close to the public for eight weeks from 3 March while its climate control is replaced. Readers with material already on order may collect it from the temporary desk in the central library between 10am and 2pm on weekdays. New orders cannot be placed during the closure, and digitised items remain available online throughout.', 'What may readers do during the closure?'), options: ['Place new orders at the temporary desk', 'Collect material already on order, on weekday afternoons only', 'Collect material already on order, on weekdays between 10am and 2pm', 'Visit the archive building by appointment'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The notice states that readers with material already on order may collect it on weekdays between 10am and 2pm.', source },
  { id: 'pte-reading-mcsa-02-003', section: 'Multiple Choice: Single Answer', topic: 'Inference', difficulty: 'hard', question: read('A common defence of long copyright terms is that they let publishers recover investment in works that sell slowly. The pattern of actual sales tells against it. Revenue for the large majority of titles is concentrated in the first few years and then falls close to zero, and the small number of works that still earn after several decades are overwhelmingly those that were commercially successful at once. The term protects, in practice, the books that needed protection least.', 'What can be inferred from the passage?'), options: ['Slow-selling works generate most long-term publishing revenue', 'The stated justification for long terms does not match which works actually benefit', 'Publishers do not recover their investment in any title', 'Copyright terms have been shortened in response to sales data'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage argues the term chiefly protects works that succeeded immediately, which is not the slow-recovery case used to justify it.', source },
  { id: 'pte-reading-mcsa-02-004', section: 'Multiple Choice: Single Answer', topic: 'Vocabulary in Context', difficulty: 'medium', question: read('Early adopters of the scheme were promised that reporting would be light. In practice each participating council now files four separate returns, two of which request the same figures in different units, and staff describe the burden as having crept upward without any single decision to increase it.', 'In this passage, "crept upward" most nearly means'), options: ['rose suddenly after a formal change', 'increased gradually and without announcement', 'was measured incorrectly by staff', 'fell more slowly than expected'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The phrase is glossed by the rest of the sentence, which says the burden grew without any single decision to increase it.', source },
  { id: 'pte-reading-mcsa-02-005', section: 'Multiple Choice: Single Answer', topic: 'Detail', difficulty: 'medium', question: read('Applicants must submit two references. One must be academic and dated within the last two years. The second may be academic or professional and carries no date restriction. Applicants who left formal study more than ten years ago may substitute a second professional reference for the academic one, provided they explain the substitution in the covering letter.', 'Who may submit two professional references?'), options: ['Any applicant who explains the choice in the covering letter', 'Applicants whose academic reference is more than two years old', 'No applicant under any circumstances', 'Applicants who left formal study more than ten years ago and explain the substitution'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The substitution is available only to those who left formal study more than ten years ago, and only with an explanation in the covering letter.', source },
  { id: 'pte-reading-mcsa-02-006', section: 'Multiple Choice: Single Answer', topic: 'Writer\'s Purpose', difficulty: 'hard', question: read('It is worth being precise about what the survey measured. Respondents were asked whether they had used the service in the past year, not whether they had found it useful, and the headline figure has since been quoted as evidence of satisfaction. Nothing in the instrument supports that reading, and the researchers have said so twice.', 'Why does the writer mention that the researchers have said so twice?'), options: ['To show that the researchers are uncertain about their own findings', 'To emphasise that the misreading has persisted despite correction', 'To indicate that the survey was repeated in a second year', 'To suggest the survey should be withdrawn'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The detail underlines that the misuse of the figure continues even though the authors have publicly corrected it.', source },
  { id: 'pte-reading-mcsa-02-007', section: 'Multiple Choice: Single Answer', topic: 'Main Idea', difficulty: 'medium', question: read('Seed banks are often presented as an insurance policy for crop diversity, and as storage they work well. What they store less well is the knowledge of how a variety was grown: the timing, the companion planting, the local judgement about when to sow. A seed recovered after fifty years can be germinated. A cultivation practice abandoned for fifty years usually cannot be recovered at all, because nobody wrote it down.', 'What is the main point of the passage?'), options: ['Seed banks preserve seed effectively but not the practices needed to grow it', 'Seed banks fail to keep stored seed viable over long periods', 'Crop diversity is best preserved by abandoning seed banks', 'Cultivation practices are recorded more thoroughly than seed'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage grants that storage works and locates the loss in the unrecorded cultivation knowledge.', source },
  { id: 'pte-reading-mcsa-02-008', section: 'Multiple Choice: Single Answer', topic: 'Detail', difficulty: 'easy', question: read('From January the loyalty scheme will award one point for every two pounds spent in store and one point for every pound spent online. Points expire twenty-four months after they are earned. Vouchers issued from points must be used within six months of issue and cannot be exchanged for cash.', 'How long do points remain valid?'), options: ['Six months from issue', 'Twelve months from the date earned', 'Twenty-four months from the date earned', 'They do not expire'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage states that points expire twenty-four months after they are earned; the six-month limit applies to vouchers, not points.', source },
  { id: 'pte-reading-mcsa-02-009', section: 'Multiple Choice: Single Answer', topic: 'Inference', difficulty: 'hard', question: read('Reviewers asked to assess the same manuscript under two conditions, with and without the authors\' names, disagreed with themselves about as often as they disagreed with each other. The result is usually read as evidence of bias. It is at least as good evidence that the judgement being asked for is not stable enough to be measured twice, whoever is making it.', 'The author of the passage suggests that the result'), options: ['may reflect the instability of the judgement rather than bias', 'proves that reviewers are biased by author names', 'shows that reviewers should be given more time', 'indicates that anonymous review should be abandoned'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The final sentence offers instability of the judgement itself as a rival reading at least as well supported as bias.', source },
  { id: 'pte-reading-mcsa-02-010', section: 'Multiple Choice: Single Answer', topic: 'Detail', difficulty: 'medium', question: read('The grant covers equipment, fieldwork travel and open-access publication charges. It does not cover salary costs of any kind, conference attendance, or the purchase of computing hardware with a useful life beyond the grant period. Applicants unsure whether an item qualifies should ask before submitting rather than after.', 'Which of the following is covered by the grant?'), options: ['A laptop expected to last five years', 'A conference registration fee', 'Part of a research assistant\'s salary', 'Fieldwork travel'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Fieldwork travel is named among the covered items, while the other three fall under the stated exclusions.', source },
  { id: 'pte-reading-mcsa-02-011', section: 'Multiple Choice: Single Answer', topic: 'Vocabulary in Context', difficulty: 'medium', question: read('The report treats the fall in applications as a puzzle, but the timing is hardly opaque: the fee rose in the same month, and no other change of comparable size took effect that year.', 'In this passage, "opaque" most nearly means'), options: ['expensive', 'recent', 'hard to explain', 'widely reported'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The sentence contrasts the word with an obvious explanation, so it means difficult to account for.', source },
  { id: 'pte-reading-mcsa-02-012', section: 'Multiple Choice: Single Answer', topic: 'Writer\'s Purpose', difficulty: 'hard', question: read('Any account of the decline has to explain why it began three years before the regulation that is usually blamed for it. Explanations that start with the regulation are not merely incomplete; they are ruled out by the dates, and repeating them with more detail does not help.', 'What is the writer\'s purpose in this passage?'), options: ['To propose an alternative cause of the decline', 'To argue that the regulation should be repealed', 'To recommend collecting more detailed data on the regulation', 'To show that a common explanation is excluded by the chronology'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The writer uses the three-year gap to rule the standard explanation out, without proposing a replacement.', source },
];
