import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'RBI Assistant 2026 official recruitment notification (Panel Year 2025), Mains syllabus — English Language section',
  url: 'https://website.rbi.org.in/web/rbi/-/recruitment-for-the-post-of-assistant-panel-year-2025-in-reserve-bank-of-india',
  checkedOn: '27 August 2026',
};

const RC_PASSAGE =
  "Read the following passage carefully and answer the questions that follow.\n\nAmong the many functions the Reserve Bank of India performs, currency management rarely draws as much public attention as monetary policy announcements, yet it touches the daily life of nearly every citizen more directly than most other central bank activities. The RBI is solely responsible for designing, printing, and distributing India's currency notes and coins, coordinating a supply chain that stretches from currency printing presses to bank branches to the cash machines millions of people rely on every day.\n\nIn recent years, the volume of digital transactions in India has grown at a pace that surprised even optimistic forecasters, driven largely by the Unified Payments Interface and an expanding base of smartphone users in smaller towns and rural areas. Even so, cash in circulation has not declined in absolute terms; if anything, the value of currency notes in circulation has continued to rise year over year, suggesting that digital and cash payments have grown alongside each other rather than one displacing the other.\n\nThis pattern complicates the popular narrative of an imminent 'cashless society'. Cash remains the preferred mode of payment for a significant share of small, informal transactions, particularly in areas with patchy internet connectivity or among people less comfortable with digital interfaces. Recognising this, the RBI has continued to invest in cleaner, more durable currency alongside its efforts to widen the digital payments ecosystem, treating the two as complementary rather than as a race with a clear winner.\n\n";

const CLOZE_PASSAGE =
  "In the following passage, four numbered blanks have been left. Choose the option that best fits each blank.\n\nThe Reserve Bank of India (1)______ the sole authority to issue currency notes in the country, a power it (2)______ under a specific statute. Coins, by contrast, are minted by the Government of India and (3)______ into circulation through the RBI's distribution network. Together, these arrangements (4)______ that the country's currency supply remains centrally coordinated.\n\n";

export const RBI_ASSISTANT_MAINS_ENGLISH_LANGUAGE_1: Question[] = [
  { id: 'rbi-asst-m1-en-001', section: 'English Language', topic: 'Reading comprehension', difficulty: 'medium', question: `${RC_PASSAGE}According to the passage, which central bank function is discussed that draws less public attention than monetary policy announcements?`, options: ['Currency management', 'Interest rate decisions', 'Bank licensing', 'Foreign exchange reserves'], correctIndex: 0, explanation: 'The passage opens by stating that "currency management rarely draws as much public attention as monetary policy announcements."', source },
  { id: 'rbi-asst-m1-en-002', section: 'English Language', topic: 'Reading comprehension', difficulty: 'medium', question: `${RC_PASSAGE}What is described as having grown at a pace that surprised even optimistic forecasters, driven largely by UPI?`, options: ['The volume of digital transactions', 'The number of currency printing presses', 'The value of cash in circulation', 'The number of bank branches'], correctIndex: 0, explanation: 'The passage states "the volume of digital transactions in India has grown at a pace that surprised even optimistic forecasters, driven largely by the Unified Payments Interface."', source },
  { id: 'rbi-asst-m1-en-003', section: 'English Language', topic: 'Reading comprehension', difficulty: 'medium', question: `${RC_PASSAGE}What has happened to cash in circulation despite the growth of digital payments, according to the passage?`, options: ['It has continued to rise in value year over year', 'It has declined sharply', 'It has remained exactly unchanged', 'It has been officially discontinued'], correctIndex: 0, explanation: 'The passage notes that "the value of currency notes in circulation has continued to rise year over year."', source },
  { id: 'rbi-asst-m1-en-004', section: 'English Language', topic: 'Reading comprehension', difficulty: 'medium', question: `${RC_PASSAGE}Why does cash remain preferred for a significant share of small, informal transactions, according to the passage?`, options: ['Patchy internet connectivity or discomfort with digital interfaces', 'A legal requirement that small transactions use only cash', 'Digital payments are more expensive than cash', 'Banks actively discourage digital transactions'], correctIndex: 0, explanation: 'The passage attributes this to areas "with patchy internet connectivity or among people less comfortable with digital interfaces."', source },
  { id: 'rbi-asst-m1-en-005', section: 'English Language', topic: 'Reading comprehension', difficulty: 'medium', question: `${RC_PASSAGE}Which of the following best describes the author's overall view on digital versus cash payments in India?`, options: ['They have grown alongside each other rather than one displacing the other', 'Digital payments have completely replaced cash', 'Cash usage has been officially banned', 'Digital payments are declining in popularity'], correctIndex: 0, explanation: 'The passage concludes that the RBI treats digital and cash payments "as complementary rather than as a race with a clear winner."', source },
  { id: 'rbi-asst-m1-en-006', section: 'English Language', topic: 'Vocabulary in context', difficulty: 'medium', question: `${RC_PASSAGE}Choose the word closest in meaning to 'complicates' as used in the passage ("this pattern complicates the popular narrative").`, options: ['Undermines', 'Confirms', 'Simplifies', 'Ignores'], correctIndex: 0, explanation: "In this context, 'complicates' means the pattern undermines or casts doubt on the simple narrative of an imminent cashless society.", source },
  { id: 'rbi-asst-m1-en-007', section: 'English Language', topic: 'Vocabulary in context', difficulty: 'medium', question: `${RC_PASSAGE}Choose the word most opposite in meaning to 'durable' as used in the passage ("cleaner, more durable currency").`, options: ['Fragile', 'Sturdy', 'Long-lasting', 'Resilient'], correctIndex: 0, explanation: "'Durable' means able to withstand wear; its opposite is 'fragile', meaning easily damaged.", source },
  { id: 'rbi-asst-m1-en-008', section: 'English Language', topic: 'Cloze test', difficulty: 'medium', question: `${CLOZE_PASSAGE}Choose the best word for blank (1).`, options: ['holds', 'lacks', 'shares', 'denies'], correctIndex: 0, explanation: "The RBI being the 'sole authority' to issue currency means it 'holds' that authority.", source },
  { id: 'rbi-asst-m1-en-009', section: 'English Language', topic: 'Cloze test', difficulty: 'medium', question: `${CLOZE_PASSAGE}Choose the best word for blank (2).`, options: ['exercises', 'abandons', 'questions', 'forfeits'], correctIndex: 0, explanation: "A power granted 'under a specific statute' is one the RBI 'exercises', not abandons or forfeits.", source },
  { id: 'rbi-asst-m1-en-010', section: 'English Language', topic: 'Cloze test', difficulty: 'medium', question: `${CLOZE_PASSAGE}Choose the best word for blank (3).`, options: ['released', 'withheld', 'destroyed', 'hidden'], correctIndex: 0, explanation: "Coins minted by the Government are 'released' into circulation through the RBI's distribution network.", source },
  { id: 'rbi-asst-m1-en-011', section: 'English Language', topic: 'Cloze test', difficulty: 'medium', question: `${CLOZE_PASSAGE}Choose the best word for blank (4).`, options: ['prevent', 'discourage', 'eliminate', 'ensure'], correctIndex: 3, explanation: "These arrangements are described as working together to 'ensure' centrally coordinated currency supply.", source },
  { id: 'rbi-asst-m1-en-012', section: 'English Language', topic: 'Error spotting', difficulty: 'medium', question: 'Read the sentence below, divided into three parts. Identify the part that contains a grammatical error, or select "No error" if there is none.\n\nThe RBI along with several public sector banks (A) / have launched a new financial literacy campaign (B) / targeting rural households. (C)', options: ['A', 'C', 'B', 'No error'], correctIndex: 2, explanation: "The subject 'RBI' is singular; 'along with several public sector banks' does not make the verb plural, so it should be 'has launched', not 'have launched' — the error is in part B.", source },
  { id: 'rbi-asst-m1-en-013', section: 'English Language', topic: 'Error spotting', difficulty: 'medium', question: 'Read the sentence below, divided into three parts. Identify the part that contains a grammatical error, or select "No error" if there is none.\n\nNeither the cashier nor the branch manager (A) / were aware (B) / of the new currency verification procedure. (C)', options: ['A', 'B', 'C', 'No error'], correctIndex: 1, explanation: "With 'neither...nor', the verb agrees with the nearer subject ('branch manager', singular), so it should be 'was aware', not 'were aware' — the error is in part B.", source },
  { id: 'rbi-asst-m1-en-014', section: 'English Language', topic: 'Error spotting', difficulty: 'medium', question: 'Read the sentence below, divided into three parts. Identify the part that contains a grammatical error, or select "No error" if there is none.\n\nShe is one of the few employees (A) / who has completed (B) / the advanced currency-handling training. (C)', options: ['A', 'C', 'No error', 'B'], correctIndex: 3, explanation: "'Who' refers back to 'employees' (plural), so it should be 'who have completed', not 'who has completed' — the error is in part B.", source },
  { id: 'rbi-asst-m1-en-015', section: 'English Language', topic: 'Error spotting', difficulty: 'medium', question: 'Read the sentence below, divided into three parts. Identify the part that contains a grammatical error, or select "No error" if there is none.\n\nThe number of counterfeit notes detected (A) / has declined steadily (B) / over the past three years. (C)', options: ['A', 'B', 'No error', 'C'], correctIndex: 2, explanation: "'The number of' as a subject correctly takes the singular verb 'has declined'. The sentence has no error.", source },
  { id: 'rbi-asst-m1-en-016', section: 'English Language', topic: 'Sentence improvement', difficulty: 'medium', question: 'Improve the underlined part of the sentence: "He is one of the most _efficient employee_ in the department."', options: ['efficient employee', 'efficient employees', 'efficiency employees', 'efficiently employees'], correctIndex: 1, explanation: "'One of the most X' requires a plural noun, so 'efficient employees' is correct.", source },
  { id: 'rbi-asst-m1-en-017', section: 'English Language', topic: 'Sentence improvement', difficulty: 'medium', question: 'Improve the underlined part of the sentence: "_Despite of_ the heavy workload, she completed the task on time."', options: ['Despite of the', 'In spite the', 'Although of', 'Despite'], correctIndex: 3, explanation: "'Despite' is never followed by 'of'; the correct form is simply 'Despite the heavy workload'.", source },
  { id: 'rbi-asst-m1-en-018', section: 'English Language', topic: 'Sentence improvement', difficulty: 'medium', question: 'Improve the underlined part of the sentence: "The manager was _too much pleased_ with the team\'s performance."', options: ['too much pleasing', 'so much pleased', 'extremely pleased', 'too pleasing'], correctIndex: 2, explanation: "'Too much' cannot directly modify a past participle like 'pleased' in standard usage; 'extremely pleased' is the correct form.", source },
  { id: 'rbi-asst-m1-en-019', section: 'English Language', topic: 'Fill in the blanks', difficulty: 'medium', question: 'Fill in the two blanks with the most appropriate pair of words: "The bank has ______ its currency verification machines and ______ staff training accordingly."', options: ['discarded, cancelled', 'upgraded, revised', 'ignored, delayed', 'upgraded, abolished'], correctIndex: 1, explanation: "'Upgraded' and 'revised' fit the positive tone of a bank updating equipment and adjusting training.", source },
  { id: 'rbi-asst-m1-en-020', section: 'English Language', topic: 'Fill in the blanks', difficulty: 'medium', question: 'Fill in the two blanks with the most appropriate pair of words: "Despite the ______ workload, the team managed to ______ the deadline."', options: ['light, miss', 'heavy, miss', 'light, meet', 'heavy, meet'], correctIndex: 3, explanation: "'Despite' signals a contrast, so a 'heavy' workload paired with still managing to 'meet' the deadline fits the sentence logic.", source },
  { id: 'rbi-asst-m1-en-021', section: 'English Language', topic: 'Fill in the blanks', difficulty: 'medium', question: 'Fill in the two blanks with the most appropriate pair of words: "The officer ______ the cash register before ______ it for the day."', options: ['ignored, closing', 'balanced, opening the previously', 'balanced, closing', 'opened, balancing'], correctIndex: 2, explanation: "'Balanced...before closing' forms a logical end-of-day sequence: reconciling the register precedes shutting it down.", source },
  { id: 'rbi-asst-m1-en-022', section: 'English Language', topic: 'One-word substitution', difficulty: 'medium', question: "Choose the word that means \"a written record of a bank customer's account transactions maintained by the bank.\"", options: ['Ledger', 'Passbook', 'Voucher', 'Invoice'], correctIndex: 1, explanation: "A passbook is the record book issued to a customer showing their account's transaction history.", source },
  { id: 'rbi-asst-m1-en-023', section: 'English Language', topic: 'One-word substitution', difficulty: 'medium', question: 'Choose the word that means "one who deals in the buying and selling of foreign currency."', options: ['Auditor', 'Trustee', 'Debtor', 'Money changer'], correctIndex: 3, explanation: 'A money changer is a person or business that exchanges one currency for another.', source },
  { id: 'rbi-asst-m1-en-024', section: 'English Language', topic: 'One-word substitution', difficulty: 'medium', question: 'Choose the word that means "a person who has no means to repay any of his debts."', options: ['Solvent', 'Affluent', 'Bankrupt', 'Prosperous'], correctIndex: 2, explanation: 'Bankrupt describes someone who is legally declared unable to pay their debts.', source },
  { id: 'rbi-asst-m1-en-025', section: 'English Language', topic: 'One-word substitution', difficulty: 'medium', question: 'Choose the word that means "a person or entity that receives a benefit or payment, such as from a will or insurance policy."', options: ['Trustee', 'Beneficiary', 'Guarantor', 'Depositor'], correctIndex: 1, explanation: 'A beneficiary is the person designated to receive benefits or payments from a policy, will, or trust.', source },
  { id: 'rbi-asst-m1-en-026', section: 'English Language', topic: 'Synonym', difficulty: 'medium', question: 'Choose the word closest in meaning to AUTHENTIC.', options: ['Fake', 'Counterfeit', 'Fraudulent', 'Genuine'], correctIndex: 3, explanation: 'Authentic means real and not fake, closest to "genuine".', source },
  { id: 'rbi-asst-m1-en-027', section: 'English Language', topic: 'Synonym', difficulty: 'medium', question: 'Choose the word closest in meaning to VIGILANT.', options: ['Careless', 'Negligent', 'Watchful', 'Distracted'], correctIndex: 2, explanation: 'Vigilant means keeping careful watch, closest to "watchful".', source },
  { id: 'rbi-asst-m1-en-028', section: 'English Language', topic: 'Synonym', difficulty: 'medium', question: 'Choose the word closest in meaning to ROBUST.', options: ['Fragile', 'Sturdy', 'Weak', 'Flimsy'], correctIndex: 1, explanation: 'Robust means strong and well-built, closest to "sturdy".', source },
  { id: 'rbi-asst-m1-en-029', section: 'English Language', topic: 'Synonym', difficulty: 'medium', question: 'Choose the word closest in meaning to LUCID.', options: ['Confusing', 'Vague', 'Obscure', 'Clear'], correctIndex: 3, explanation: 'Lucid means easy to understand, closest to "clear".', source },
  { id: 'rbi-asst-m1-en-030', section: 'English Language', topic: 'Antonym', difficulty: 'medium', question: 'Choose the word most opposite in meaning to GENUINE.', options: ['Authentic', 'Legitimate', 'Counterfeit', 'Real'], correctIndex: 2, explanation: 'Genuine means real and authentic; its opposite is "counterfeit", meaning fake or forged.', source },
  { id: 'rbi-asst-m1-en-031', section: 'English Language', topic: 'Antonym', difficulty: 'medium', question: 'Choose the word most opposite in meaning to OBSOLETE.', options: ['Outdated', 'Current', 'Antiquated', 'Old-fashioned'], correctIndex: 1, explanation: 'Obsolete means no longer in use; its opposite is "current", meaning up to date.', source },
  { id: 'rbi-asst-m1-en-032', section: 'English Language', topic: 'Antonym', difficulty: 'medium', question: 'Choose the word most opposite in meaning to PROMPT.', options: ['Immediate', 'Timely', 'Punctual', 'Delayed'], correctIndex: 3, explanation: 'Prompt means done without delay; its opposite is "delayed".', source },
  { id: 'rbi-asst-m1-en-033', section: 'English Language', topic: 'Antonym', difficulty: 'medium', question: 'Choose the word most opposite in meaning to CONCEAL.', options: ['Hide', 'Disguise', 'Reveal', 'Cover'], correctIndex: 2, explanation: 'Conceal means to hide something; its opposite is "reveal", meaning to make known.', source },
  { id: 'rbi-asst-m1-en-034', section: 'English Language', topic: 'Idioms and phrases', difficulty: 'medium', question: 'Choose the meaning of the idiom: "To break the bank"', options: ['To rob a bank physically', "To use up all of one's money", 'To open a new bank account', 'To close a bank permanently'], correctIndex: 1, explanation: "'To break the bank' means to use up all of one's available money on something.", source },
  { id: 'rbi-asst-m1-en-035', section: 'English Language', topic: 'Idioms and phrases', difficulty: 'medium', question: 'Choose the meaning of the idiom: "To keep track of"', options: ['To lose interest in something', 'To follow someone physically', 'To forget about something entirely', 'To stay informed or updated about something'], correctIndex: 3, explanation: "'To keep track of' means to stay informed about the progress or status of something.", source },
  { id: 'rbi-asst-m1-en-036', section: 'English Language', topic: 'Idioms and phrases', difficulty: 'medium', question: 'Choose the meaning of the idiom: "To make a clean sweep"', options: ['To clean a room thoroughly', 'To lose everything in a competition', 'To win everything or completely eliminate something', 'To postpone an event indefinitely'], correctIndex: 2, explanation: "'To make a clean sweep' means to win completely or remove everything unwanted at once.", source },
  { id: 'rbi-asst-m1-en-037', section: 'English Language', topic: 'Active passive voice', difficulty: 'medium', question: 'Choose the correct passive voice of: "The cashier verified the signature."', options: ['The signature is verified by the cashier.', 'The signature was verified by the cashier.', 'The signature had verified the cashier.', 'The cashier was verified by the signature.'], correctIndex: 1, explanation: 'In the passive voice, the object "the signature" becomes the subject, and the verb takes the correct past-tense passive form: "was verified by".', source },
  { id: 'rbi-asst-m1-en-038', section: 'English Language', topic: 'Active passive voice', difficulty: 'medium', question: 'Choose the correct passive voice of: "The RBI will issue new currency guidelines next quarter."', options: ['New currency guidelines are issued by the RBI next quarter.', 'New currency guidelines will issue the RBI next quarter.', 'New currency guidelines had been issued by the RBI next quarter.', 'New currency guidelines will be issued by the RBI next quarter.'], correctIndex: 3, explanation: 'For future simple tense, the passive form uses "will be + past participle": "New currency guidelines will be issued by the RBI next quarter."', source },
  { id: 'rbi-asst-m1-en-039', section: 'English Language', topic: 'Direct indirect speech', difficulty: 'medium', question: 'Choose the correct indirect speech of: He said, "I have deposited the cash today."', options: ['He said that I have deposited the cash today.', 'He said that he has deposited the cash today.', 'He said that he had deposited the cash that day.', 'He said that he deposits the cash that day.'], correctIndex: 2, explanation: "In indirect speech, present perfect shifts to past perfect, 'I' becomes 'he', and 'today' becomes 'that day'.", source },
  { id: 'rbi-asst-m1-en-040', section: 'English Language', topic: 'Direct indirect speech', difficulty: 'medium', question: 'Choose the correct indirect speech of: She said, "Will you verify this document?"', options: ['She said that will you verify this document.', 'She asked if I would verify that document.', 'She asked that I will verify this document.', 'She asked if I will verify that document.'], correctIndex: 1, explanation: "In indirect speech, a yes/no question introduces 'if'/'whether', 'will' shifts to 'would', and 'this' shifts to 'that'.", source },
];
