import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'RBI Assistant 2026 official recruitment notification (Panel Year 2025), Mains syllabus — Reasoning Ability section',
  url: 'https://website.rbi.org.in/web/rbi/-/recruitment-for-the-post-of-assistant-panel-year-2025-in-reserve-bank-of-india',
  checkedOn: '29 August 2026',
};

const CIRCULAR_PUZZLE =
  'Six people G, H, I, J, K, and L sit around a circular table, all facing away from the centre (outward), not necessarily in the given order. H sits third to the right of G. I sits second to the left of H. K sits immediately right of I. L sits second to the right of K. J sits immediately left of G.\n\n';

const AGE_PUZZLE =
  'Six colleagues M, N, O, P, Q, and R have different ages. O is older than only two people. The oldest is not M. N is younger than P but older than Q. M is older than P.\n\n';

const INEQUALITY_LEGEND =
  "In these questions, the following symbols indicate relationships: '@' means greater than, '#' means less than, '%' means greater than or equal to, '$' means less than or equal to, and '&' means equal to. Read the given statements and decide which of the conclusions logically follow(s).\n\n";

const WORD_LIST =
  'Consider the following words: 1. Reliable 2. Relevant 3. Release 4. Relative 5. Relay. If these words are arranged as they would appear in an English dictionary, answer the question that follows.\n\n';

export const RBI_ASSISTANT_MAINS_REASONING_ABILITY_2: Question[] = [
  { id: 'rbi-asst-m2-re-001', section: 'Reasoning Ability', topic: 'Seating arrangement', difficulty: 'hard', question: `${CIRCULAR_PUZZLE}Who sits immediately to the right of K?`, options: ['H', 'I', 'K', 'L'], correctIndex: 0, marks: 1, negativeMarking: 0.25, explanation: 'The clockwise order (all facing outward) is G, I, K, H, L, J. Immediately to the right (clockwise) of K is H.', source },
  { id: 'rbi-asst-m2-re-002', section: 'Reasoning Ability', topic: 'Seating arrangement', difficulty: 'hard', question: `${CIRCULAR_PUZZLE}Who sits exactly opposite I?`, options: ['K', 'L', 'G', 'J'], correctIndex: 1, marks: 1, negativeMarking: 0.25, explanation: 'With six people seated, the person exactly opposite is three seats away. In the order G, I, K, H, L, J, three seats clockwise from I lands on L.', source },
  { id: 'rbi-asst-m2-re-003', section: 'Reasoning Ability', topic: 'Seating arrangement', difficulty: 'hard', question: `${CIRCULAR_PUZZLE}Who sits second to the left of L?`, options: ['G', 'H', 'K', 'J'], correctIndex: 2, marks: 1, negativeMarking: 0.25, explanation: 'The order is G, I, K, H, L, J. Moving two seats to the left (anticlockwise) of L lands on K.', source },
  { id: 'rbi-asst-m2-re-004', section: 'Reasoning Ability', topic: 'Seating arrangement', difficulty: 'hard', question: `${CIRCULAR_PUZZLE}Who sits second to the left of H?`, options: ['K', 'L', 'G', 'I'], correctIndex: 3, marks: 1, negativeMarking: 0.25, explanation: 'The order is G, I, K, H, L, J, and back to G. Moving two seats to the left (anticlockwise) of H lands on I.', source },
  { id: 'rbi-asst-m2-re-005', section: 'Reasoning Ability', topic: 'Puzzle', difficulty: 'hard', question: `${AGE_PUZZLE}Who is the oldest among the six?`, options: ['R', 'M', 'P', 'O'], correctIndex: 0, marks: 1, negativeMarking: 0.25, explanation: 'Working through the constraints, the age order (youngest to oldest) is Q, N, O, P, M, R. R is the oldest.', source },
  { id: 'rbi-asst-m2-re-006', section: 'Reasoning Ability', topic: 'Puzzle', difficulty: 'hard', question: `${AGE_PUZZLE}Who is the youngest among the six?`, options: ['N', 'Q', 'O', 'P'], correctIndex: 1, marks: 1, negativeMarking: 0.25, explanation: 'The age order (youngest to oldest) is Q, N, O, P, M, R. Q is the youngest.', source },
  { id: 'rbi-asst-m2-re-007', section: 'Reasoning Ability', topic: 'Puzzle', difficulty: 'hard', question: `${AGE_PUZZLE}How many people are older than N?`, options: ['3', '5', '4', '2'], correctIndex: 2, marks: 1, negativeMarking: 0.25, explanation: 'The age order (youngest to oldest) is Q, N, O, P, M, R. Everyone ranked after N — namely O, P, M, and R — is older than N, which is 4 people.', source },
  { id: 'rbi-asst-m2-re-008', section: 'Reasoning Ability', topic: 'Puzzle', difficulty: 'hard', question: `${AGE_PUZZLE}Who is exactly in the middle (3rd) when the six are ranked from youngest to oldest?`, options: ['P', 'N', 'M', 'O'], correctIndex: 3, marks: 1, negativeMarking: 0.25, explanation: 'The age order (youngest to oldest) is Q, N, O, P, M, R. The 3rd position from youngest is O.', source },
  { id: 'rbi-asst-m2-re-009', section: 'Reasoning Ability', topic: 'Syllogism', difficulty: 'medium', question: 'Statements:\nAll bonds are securities.\nSome securities are shares.\n\nConclusions:\nI. Some bonds are shares.\nII. Some shares are bonds.', options: ['Neither I nor II follows', 'Only I follows', 'Only II follows', 'Both I and II follow'], correctIndex: 0, marks: 1, negativeMarking: 0.25, explanation: 'The securities that are shares need not overlap with the securities that are bonds, so neither conclusion can be drawn with certainty.', source },
  { id: 'rbi-asst-m2-re-010', section: 'Reasoning Ability', topic: 'Syllogism', difficulty: 'medium', question: 'Statements:\nSome loans are advances.\nAll advances are credits.\n\nConclusions:\nI. Some loans are credits.\nII. Some credits are loans.', options: ['Only I follows', 'Both I and II follow', 'Only II follows', 'Neither I nor II follows'], correctIndex: 1, marks: 1, negativeMarking: 0.25, explanation: 'The loans that are advances are also credits (since all advances are credits), so some loans are credits (I), and by conversion, some credits are loans (II). Both follow.', source },
  { id: 'rbi-asst-m2-re-011', section: 'Reasoning Ability', topic: 'Syllogism', difficulty: 'medium', question: 'Statements:\nNo shares are debentures.\nAll debentures are instruments.\n\nConclusions:\nI. No shares are instruments.\nII. Some instruments are not shares.', options: ['Only I follows', 'Neither I nor II follows', 'Only II follows', 'Both I and II follow'], correctIndex: 2, marks: 1, negativeMarking: 0.25, explanation: 'Since all debentures are instruments and no shares are debentures, the debentures (a subset of instruments) are definitely not shares, so some instruments are not shares (II) follows. But other instruments outside the debenture subset could still be shares, so "no shares are instruments" (I) does not necessarily follow.', source },
  { id: 'rbi-asst-m2-re-012', section: 'Reasoning Ability', topic: 'Syllogism', difficulty: 'medium', question: 'Statements:\nAll ledgers are registers.\nNo register is outdated.\n\nConclusions:\nI. No ledger is outdated.\nII. Some registers are ledgers.', options: ['Only I follows', 'Only II follows', 'Neither I nor II follows', 'Both I and II follow'], correctIndex: 3, marks: 1, negativeMarking: 0.25, explanation: 'Since all ledgers are registers and no register is outdated, no ledger can be outdated (I). Also, since all ledgers are registers, some registers are ledgers (II), by conversion. Both follow.', source },
  { id: 'rbi-asst-m2-re-013', section: 'Reasoning Ability', topic: 'Blood relations', difficulty: 'medium', question: "Pointing to a photograph, a man said, 'She is the daughter of my grandfather's only son.' How is the woman related to the man?", options: ['Sister', 'Aunt', 'Cousin', 'Niece'], correctIndex: 0, marks: 1, negativeMarking: 0.25, explanation: "The man's grandfather's only son is the man's own father. The daughter of the man's father is therefore the man's sister.", source },
  { id: 'rbi-asst-m2-re-014', section: 'Reasoning Ability', topic: 'Blood relations', difficulty: 'medium', question: 'M is the daughter of N. O is the wife of N. P is the daughter of O, other than M. How is N related to P?', options: ['Brother', 'Father', 'Uncle', 'Grandfather'], correctIndex: 1, marks: 1, negativeMarking: 0.25, explanation: 'O is the wife of N, and P is another daughter of O. Since N and O are a couple, P is also the daughter of N, making N the father of P.', source },
  { id: 'rbi-asst-m2-re-015', section: 'Reasoning Ability', topic: 'Blood relations', difficulty: 'medium', question: 'A is the son of B. C is the sister of B. D is the daughter of C. How is D related to A?', options: ['Nephew', 'Uncle', 'Cousin', 'Brother'], correctIndex: 2, marks: 1, negativeMarking: 0.25, explanation: "B is the parent of A. C, being the sibling of B, is A's aunt. D, being the daughter of C, is therefore A's cousin.", source },
  { id: 'rbi-asst-m2-re-016', section: 'Reasoning Ability', topic: 'Direction sense', difficulty: 'medium', question: 'Karan walks 6 m north, then turns right and walks 9 m, then turns right again and walks 6 m. How far is he from the starting point, and in which direction?', options: ['6 m, East', '9 m, North', '9 m, West', '9 m, East'], correctIndex: 3, marks: 1, negativeMarking: 0.25, explanation: 'North 6 m, then east 9 m, then south 6 m. The north and south legs cancel out, leaving him 9 m east of the starting point.', source },
  { id: 'rbi-asst-m2-re-017', section: 'Reasoning Ability', topic: 'Direction sense', difficulty: 'medium', question: 'Point M is 15 km north of point L. Point K is 20 km east of point M. What is the shortest distance between L and K?', options: ['25 km', '20 km', '35 km', '24 km'], correctIndex: 0, marks: 1, negativeMarking: 0.25, explanation: 'L to M is 15 km and M to K is 20 km, at a right angle. By the Pythagorean theorem, LK = √(15² + 20²) = √625 = 25 km.', source },
  { id: 'rbi-asst-m2-re-018', section: 'Reasoning Ability', topic: 'Direction sense', difficulty: 'medium', question: 'Facing south, Meera turns 90° anticlockwise, then 45° clockwise. Which direction is she facing now?', options: ['North-East', 'South-East', 'South-West', 'North-West'], correctIndex: 1, marks: 1, negativeMarking: 0.25, explanation: 'Starting at South (180°), turning 90° anticlockwise gives 180 − 90 = 90° (East). Turning 45° clockwise from there gives 90 + 45 = 135°, which is South-East.', source },
  { id: 'rbi-asst-m2-re-019', section: 'Reasoning Ability', topic: 'Coding-decoding', difficulty: 'medium', question: "If 'RIVER' is coded as 'PGTCP' in a certain language (each letter shifted two places back in the alphabet), how is 'STONE' coded in the same language?", options: ['QRMLD', 'QSMLC', 'QRMLC', 'PRMLC'], correctIndex: 2, marks: 1, negativeMarking: 0.25, explanation: 'Each letter is shifted two places back: S→Q, T→R, O→M, N→L, E→C, giving QRMLC.', source },
  { id: 'rbi-asst-m2-re-020', section: 'Reasoning Ability', topic: 'Coding-decoding', difficulty: 'hard', question: "In a certain code, each letter is written as the letter equally far from the end of the alphabet as it is from the beginning (A=Z, B=Y, and so on). How is 'CLOUD' coded?", options: ['XOLFV', 'XPLFW', 'XOMFW', 'XOLFW'], correctIndex: 3, marks: 1, negativeMarking: 0.25, explanation: 'Using position 27 minus the letter\'s position: C(3)→X(24), L(12)→O(15), O(15)→L(12), U(21)→F(6), D(4)→W(23). This gives XOLFW.', source },
  { id: 'rbi-asst-m2-re-021', section: 'Reasoning Ability', topic: 'Coding-decoding', difficulty: 'medium', question: "In a certain code, each letter is represented by the sum of the digits of its position in the alphabet (for example, the 23rd letter W is coded as 2+3=5). What is the code for 'BOND'?", options: ['2 6 5 4', '2 7 5 4', '3 6 5 4', '2 6 4 4'], correctIndex: 0, marks: 1, negativeMarking: 0.25, explanation: 'B is the 2nd letter (single digit, sum=2), O is the 15th letter (1+5=6), N is the 14th letter (1+4=5), D is the 4th letter (single digit, sum=4). Code: 2 6 5 4.', source },
  { id: 'rbi-asst-m2-re-022', section: 'Reasoning Ability', topic: 'Coding-decoding', difficulty: 'hard', question: "In a code, each letter of a word is shifted one place backward in the alphabet, and the resulting word is written in reverse order. How is 'LOAN' coded?", options: ['NZMK', 'MZNK', 'MZNJ', 'MYNK'], correctIndex: 1, marks: 1, negativeMarking: 0.25, explanation: "Shifting each letter one place backward: L→K, O→N, A→Z (wrapping), N→M, giving KNZM. Reversing this gives MZNK.", source },
  { id: 'rbi-asst-m2-re-023', section: 'Reasoning Ability', topic: 'Inequality', difficulty: 'medium', question: `${INEQUALITY_LEGEND}Statements: J@K, K&L, L@M\nConclusions: I. J@M  II. K@M`, options: ['Only I follows', 'Only II follows', 'Both I and II follow', 'Neither I nor II follows'], correctIndex: 2, marks: 1, negativeMarking: 0.25, explanation: 'K=L and L>M together give K>M (II). Also, J>K=L>M transitively gives J>M (I). Both follow.', source },
  { id: 'rbi-asst-m2-re-024', section: 'Reasoning Ability', topic: 'Inequality', difficulty: 'medium', question: `${INEQUALITY_LEGEND}Statements: N@O, O%P, Q$P\nConclusions: I. N@P  II. O@Q`, options: ['Only II follows', 'Neither I nor II follows', 'Both I and II follow', 'Only I follows'], correctIndex: 3, marks: 1, negativeMarking: 0.25, explanation: 'N>O and O≥P together give N>P (I), since N is strictly greater than O which is at least P. O≥P and Q≤P do not fix a strict relation between O and Q (both could be equal), so II does not necessarily follow.', source },
  { id: 'rbi-asst-m2-re-025', section: 'Reasoning Ability', topic: 'Inequality', difficulty: 'medium', question: `${INEQUALITY_LEGEND}Statements: R%S, S&T, T#U\nConclusions: I. R#U  II. S#U`, options: ['Only II follows', 'Only I follows', 'Both I and II follow', 'Neither I nor II follows'], correctIndex: 0, marks: 1, negativeMarking: 0.25, explanation: 'S=T and T<U together give S<U (II). R≥S and S<U do not fix R\'s relation to U (R could be much larger than S), so I does not necessarily follow.', source },
  { id: 'rbi-asst-m2-re-026', section: 'Reasoning Ability', topic: 'Alphanumeric series', difficulty: 'medium', question: 'Find the missing term in the series: C, G, L, R, ?', options: ['X', 'Y', 'Z', 'W'], correctIndex: 1, marks: 1, negativeMarking: 0.25, explanation: 'The gaps between letters increase by one each time: C(+4)G(+5)L(+6)R(+7)Y. So the answer is Y.', source },
  { id: 'rbi-asst-m2-re-027', section: 'Reasoning Ability', topic: 'Alphanumeric series', difficulty: 'hard', question: 'Find the missing term in the series: A1, D4, H9, ?, S25', options: ['M15', 'N16', 'M16', 'N17'], correctIndex: 2, marks: 1, negativeMarking: 0.25, explanation: 'The letters occupy alphabet positions 1, 4, 8, 13, 19 (differences increasing by 1), and the numbers are perfect squares 1, 4, 9, 16, 25. The missing 4th term (position 13 = M, number 16) is M16.', source },
  { id: 'rbi-asst-m2-re-028', section: 'Reasoning Ability', topic: 'Alphanumeric series', difficulty: 'medium', question: 'Find the missing term in the series: 4, 9, 17, 28, 42, ?', options: ['56', '57', '58', '59'], correctIndex: 3, marks: 1, negativeMarking: 0.25, explanation: 'The differences increase by 3 each time: 5, 8, 11, 14, and next 17. So 42 + 17 = 59.', source },
  { id: 'rbi-asst-m2-re-029', section: 'Reasoning Ability', topic: 'Alphanumeric series', difficulty: 'medium', question: "If the letters of the word 'KEYBOARD' are arranged in alphabetical order, which letter is 4th from the right?", options: ['K', 'R', 'O', 'Y'], correctIndex: 0, marks: 1, negativeMarking: 0.25, explanation: 'The letters of KEYBOARD sorted alphabetically are A, B, D, E, K, O, R, Y. Counting from the right, the 4th letter is K.', source },
  { id: 'rbi-asst-m2-re-030', section: 'Reasoning Ability', topic: 'Data sufficiency', difficulty: 'hard', question: 'What is the area of a rectangle?\nStatement I: The perimeter of the rectangle is 36 cm.\nStatement II: The length is 10 cm.', options: ['Statement I alone is sufficient, but Statement II alone is not sufficient', 'Both statements I and II together are sufficient, but neither alone is sufficient', 'Statement II alone is sufficient, but Statement I alone is not sufficient', 'Either statement I or II alone is sufficient'], correctIndex: 1, marks: 1, negativeMarking: 0.25, explanation: 'Statement I alone gives only the sum of length and breadth (18 cm), not each individually. Statement II alone gives only the length. Together: perimeter 36 gives length+breadth=18, and length=10 gives breadth=8, so area = 10×8 = 80 sq cm.', source },
  { id: 'rbi-asst-m2-re-031', section: 'Reasoning Ability', topic: 'Data sufficiency', difficulty: 'hard', question: 'Is a certain number divisible by 24?\nStatement I: The number is divisible by 8.\nStatement II: The number is divisible by 6.', options: ['Statement I alone is sufficient, but Statement II alone is not sufficient', 'Statement II alone is sufficient, but Statement I alone is not sufficient', 'Both statements I and II together are sufficient, but neither alone is sufficient', 'Either statement I or II alone is sufficient'], correctIndex: 2, marks: 1, negativeMarking: 0.25, explanation: 'Being divisible by 8 alone does not guarantee divisibility by 24, and neither does divisibility by 6 alone. Together, being divisible by both 8 and 6 guarantees divisibility by their LCM, which is 24.', source },
  { id: 'rbi-asst-m2-re-032', section: 'Reasoning Ability', topic: 'Data sufficiency', difficulty: 'hard', question: 'What is a certain two-digit number?\nStatement I: The sum of its digits is 11.\nStatement II: The number is a multiple of 19 and lies between 70 and 90.', options: ['Statement I alone is sufficient, but Statement II alone is not sufficient', 'Both statements I and II together are sufficient, but neither alone is sufficient', 'Either statement I or II alone is sufficient', 'Statement II alone is sufficient, but Statement I alone is not sufficient'], correctIndex: 3, marks: 1, negativeMarking: 0.25, explanation: 'Statement II alone: the only multiple of 19 between 70 and 90 is 76, so it is sufficient by itself. Statement I alone allows many two-digit numbers with digit sum 11 (29, 38, 47, 56, 65, 74, 83, 92), so it is not sufficient alone.', source },
  { id: 'rbi-asst-m2-re-033', section: 'Reasoning Ability', topic: 'Data sufficiency', difficulty: 'hard', question: 'Who among X, Y, and Z is the tallest?\nStatement I: X is taller than Y.\nStatement II: Z is shorter than X.', options: ['Both statements I and II together are sufficient, but neither alone is sufficient', 'Statement I alone is sufficient, but Statement II alone is not sufficient', 'Statement II alone is sufficient, but Statement I alone is not sufficient', 'Either statement I or II alone is sufficient'], correctIndex: 0, marks: 1, negativeMarking: 0.25, explanation: 'Statement I alone does not relate Z. Statement II alone does not relate Y. Together: X>Y and X>Z, so X is the tallest.', source },
  { id: 'rbi-asst-m2-re-034', section: 'Reasoning Ability', topic: 'Ranking', difficulty: 'medium', question: 'In a class of 45 students, Priya ranks 18th from the top. What is her rank from the bottom?', options: ['27', '28', '29', '30'], correctIndex: 1, marks: 1, negativeMarking: 0.25, explanation: 'Rank from bottom = total students − rank from top + 1 = 45 − 18 + 1 = 28.', source },
  { id: 'rbi-asst-m2-re-035', section: 'Reasoning Ability', topic: 'Ranking', difficulty: 'hard', question: 'In a row of children, Aman is 9th from the left and Divya is 11th from the right. If there are 5 children between them, how many children are there in the row?', options: ['20', '23', '25', '27'], correctIndex: 2, marks: 1, negativeMarking: 0.25, explanation: "Let the total be T. Divya's position from the left is T − 10. The children strictly between positions 9 and (T−10) number (T−10) − 9 − 1 = T − 20. Setting T − 20 = 5 gives T = 25.", source },
  { id: 'rbi-asst-m2-re-036', section: 'Reasoning Ability', topic: 'Ranking', difficulty: 'medium', question: 'In a queue of 30 people, Rohan is 8th from the front and S is 12th from the back. How many people are between them?', options: ['8', '9', '11', '10'], correctIndex: 3, marks: 1, negativeMarking: 0.25, explanation: "S's position from the front is 30 − 12 + 1 = 19. The people strictly between position 8 and position 19 are at positions 9 to 18, which is 10 people.", source },
  { id: 'rbi-asst-m2-re-037', section: 'Reasoning Ability', topic: 'Ranking', difficulty: 'medium', question: 'Among five friends, C is shorter than D but taller than E. F is taller than D but shorter than G. Who is the tallest?', options: ['G', 'F', 'D', 'C'], correctIndex: 0, marks: 1, negativeMarking: 0.25, explanation: 'Combining the clues: G > F > D > C > E. So G is the tallest.', source },
  { id: 'rbi-asst-m2-re-038', section: 'Reasoning Ability', topic: 'Alphabet test', difficulty: 'medium', question: `${WORD_LIST}Which word comes first in the dictionary arrangement?`, options: ['Relay', 'Relative', 'Release', 'Relevant'], correctIndex: 1, marks: 1, negativeMarking: 0.25, explanation: "Comparing the fifth letter of the 'Rela-' words (Relative='t', Relay='y'), Relative comes first since 't' is earlier alphabetically, and both 'Rela-' words precede the 'Rele-' and 'Reli-' words.", source },
  { id: 'rbi-asst-m2-re-039', section: 'Reasoning Ability', topic: 'Alphabet test', difficulty: 'medium', question: `${WORD_LIST}Which word comes exactly between 'Relay' and 'Relevant' in the dictionary arrangement?`, options: ['Relative', 'Relevant', 'Release', 'Relay'], correctIndex: 2, marks: 1, negativeMarking: 0.25, explanation: 'The dictionary order is Relative, Relay, Release, Relevant, Reliable. The word between Relay and Relevant is Release.', source },
  { id: 'rbi-asst-m2-re-040', section: 'Reasoning Ability', topic: 'Alphabet test', difficulty: 'medium', question: `${WORD_LIST}Which word comes last in the dictionary arrangement?`, options: ['Release', 'Relevant', 'Relay', 'Reliable'], correctIndex: 3, marks: 1, negativeMarking: 0.25, explanation: "'Reliable' begins with 'Reli-', which comes after every 'Rela-' and 'Rele-' word alphabetically (i comes after a and e), so it comes last.", source },
];
