import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'RRB Technician CEN 02/2025 official notification, CBT syllabus for Grade I Signal: Basics of Computers and Applications',
  url: 'https://rrbajmer.gov.in/Upload_PDF/Detailed%20CEN%202-2025_%20Technician%20Categories-638866538197092718.pdf',
  checkedOn: '23 August 2026',
};

export const RRB_TECHNICIAN_GRADE1_SIGNAL_COMPUTERS_APPLICATIONS_2: Question[] = [
  { id: 'rrb-tech-g1-bca2-001', section: 'Basics of Computers and Applications', topic: 'Computer Architecture', difficulty: 'easy', question: 'Which unit of the CPU performs arithmetic and logical operations?', options: ['Arithmetic Logic Unit', 'Control Unit', 'Cache', 'Register'], correctIndex: 0, explanation: 'The Arithmetic Logic Unit (ALU) is the part of the CPU that performs arithmetic and logical operations.', source },
  { id: 'rrb-tech-g1-bca2-002', section: 'Basics of Computers and Applications', topic: 'Computer Architecture', difficulty: 'medium', question: 'Which of the following best describes cache memory?', options: ['A type of permanent secondary storage', 'Small, very fast memory that stores frequently used data near the CPU', 'An output device', 'A type of printer'], correctIndex: 1, explanation: 'Cache memory is small, very fast memory located close to the CPU that stores frequently accessed data to speed up processing.', source },
  { id: 'rrb-tech-g1-bca2-003', section: 'Basics of Computers and Applications', topic: 'Computer Virus', difficulty: 'medium', question: 'Which of these is a common way a computer virus can spread?', options: ['Increasing CPU clock speed', 'Defragmenting the hard disk', 'Infected email attachments or removable drives', 'Installing an operating system update'], correctIndex: 2, explanation: 'Computer viruses commonly spread through infected email attachments or removable storage devices such as USB drives.', source },
  { id: 'rrb-tech-g1-bca2-004', section: 'Basics of Computers and Applications', topic: 'Computer Virus', difficulty: 'medium', question: "A 'worm' differs from a typical virus mainly because it:", options: ['Requires a host program to attach to and spread', 'Only affects printers', 'Improves system performance', 'Can replicate and spread across networks without attaching to a host file'], correctIndex: 3, explanation: 'Unlike a typical virus, a worm can replicate itself and spread across networks independently, without needing to attach to a host file.', source },
  { id: 'rrb-tech-g1-bca2-005', section: 'Basics of Computers and Applications', topic: 'Data Representation', difficulty: 'medium', question: 'In computer data representation, one kilobyte (KB) is equal to how many bytes?', options: ['1024 bytes', '1000 bytes', '100 bytes', '512 bytes'], correctIndex: 0, explanation: 'One kilobyte (KB) is equal to 1024 bytes (2^10) in standard binary computer measurement.', source },
  { id: 'rrb-tech-g1-bca2-006', section: 'Basics of Computers and Applications', topic: 'Data Representation', difficulty: 'medium', question: 'What is the binary equivalent of the decimal number 13?', options: ['1011', '1101', '1110', '1010'], correctIndex: 1, explanation: '13 in decimal equals 8+4+1, which is 1101 in binary (1×8 + 1×4 + 0×2 + 1×1 = 13).', source },
  { id: 'rrb-tech-g1-bca2-007', section: 'Basics of Computers and Applications', topic: 'Input and Output Devices', difficulty: 'easy', question: 'Among Printer, Monitor, Scanner, and Projector, which one is used to input data into a computer rather than to produce output?', options: ['Printer', 'Monitor', 'Scanner', 'Projector'], correctIndex: 2, explanation: 'A scanner is an input device used to digitize documents or images into a computer, unlike a printer, monitor, or projector, which are all output devices.', source },
  { id: 'rrb-tech-g1-bca2-008', section: 'Basics of Computers and Applications', topic: 'Internet and Email', difficulty: 'easy', question: "What does the abbreviation 'ISP' stand for?", options: ['Internal System Process', 'Integrated Server Protocol', 'Information Sharing Platform', 'Internet Service Provider'], correctIndex: 3, explanation: 'ISP stands for Internet Service Provider, a company that provides individuals and organizations access to the internet.', source },
  { id: 'rrb-tech-g1-bca2-009', section: 'Basics of Computers and Applications', topic: 'Internet and Email', difficulty: 'medium', question: 'Which protocol is commonly used to send email messages from a client to a server?', options: ['SMTP', 'FTP', 'HTTP', 'DNS'], correctIndex: 0, explanation: 'SMTP (Simple Mail Transfer Protocol) is the standard protocol used for sending email messages from a client to a mail server.', source },
  { id: 'rrb-tech-g1-bca2-010', section: 'Basics of Computers and Applications', topic: 'MS Office', difficulty: 'easy', question: 'Which MS Office application is primarily used for creating presentations with slides?', options: ['MS Word', 'MS PowerPoint', 'MS Access', 'MS Excel'], correctIndex: 1, explanation: 'MS PowerPoint is the MS Office application primarily used for creating slide-based presentations.', source },
  { id: 'rrb-tech-g1-bca2-011', section: 'Basics of Computers and Applications', topic: 'MS Office', difficulty: 'medium', question: 'In MS Excel, which keyboard shortcut is commonly used to copy selected cells?', options: ['Ctrl+V', 'Ctrl+X', 'Ctrl+C', 'Ctrl+Z'], correctIndex: 2, explanation: 'Ctrl+C is the standard keyboard shortcut used to copy selected cells or content in MS Excel and most other applications.', source },
  { id: 'rrb-tech-g1-bca2-012', section: 'Basics of Computers and Applications', topic: 'Networking', difficulty: 'medium', question: "What does the abbreviation 'WAN' stand for in computer networking?", options: ['Wireless Access Network', 'Web Access Node', 'Worldwide Access Network', 'Wide Area Network'], correctIndex: 3, explanation: 'WAN stands for Wide Area Network, a network that spans a large geographical area, connecting multiple LANs across cities or countries.', source },
  { id: 'rrb-tech-g1-bca2-013', section: 'Basics of Computers and Applications', topic: 'Networking', difficulty: 'medium', question: 'Which networking device operates by forwarding data only to the specific device it is addressed to, based on MAC address?', options: ['Switch', 'Hub', 'Modem', 'Repeater'], correctIndex: 0, explanation: 'A switch forwards data only to the specific device addressed, using MAC addresses, unlike a hub, which broadcasts data to all connected devices.', source },
  { id: 'rrb-tech-g1-bca2-014', section: 'Basics of Computers and Applications', topic: 'Operating Systems', difficulty: 'easy', question: 'Which of the following is a mobile operating system developed by Google?', options: ['Windows', 'Android', 'macOS', 'Unix'], correctIndex: 1, explanation: 'Android is a mobile operating system developed by Google, widely used on smartphones and tablets.', source },
  { id: 'rrb-tech-g1-bca2-015', section: 'Basics of Computers and Applications', topic: 'Operating Systems', difficulty: 'medium', question: "What is 'multitasking' in the context of an operating system?", options: ['Formatting the hard disk', 'Connecting to the internet', 'Running multiple programs seemingly at the same time', 'Printing multiple documents at once'], correctIndex: 2, explanation: 'Multitasking refers to an operating system\'s ability to execute multiple processes or programs seemingly simultaneously by rapidly switching between them.', source },
  { id: 'rrb-tech-g1-bca2-016', section: 'Basics of Computers and Applications', topic: 'Operating Systems', difficulty: 'medium', question: 'Which component of an operating system is primarily responsible for organizing and managing files and folders on storage devices?', options: ['Device driver', 'Web browser', 'Compiler', 'File system'], correctIndex: 3, explanation: 'The file system is the component of an operating system responsible for organizing, storing, and managing files and folders on storage devices.', source },
  { id: 'rrb-tech-g1-bca2-017', section: 'Basics of Computers and Applications', topic: 'Storage Devices', difficulty: 'medium', question: 'Which storage device uses a spinning magnetic disk to read and write data?', options: ['Hard Disk Drive', 'Solid State Drive', 'RAM', 'Cache memory'], correctIndex: 0, explanation: 'A Hard Disk Drive (HDD) uses a spinning magnetic disk to read and write data, unlike a Solid State Drive, which has no moving parts.', source },
  { id: 'rrb-tech-g1-bca2-018', section: 'Basics of Computers and Applications', topic: 'Storage Devices', difficulty: 'medium', question: 'What is the typical storage capacity of a standard single-layer DVD?', options: ['700 MB', '4.7 GB', '1 TB', '128 MB'], correctIndex: 1, explanation: 'A standard single-layer DVD has a typical storage capacity of about 4.7 GB, larger than a CD (700 MB) but smaller than modern hard disks.', source },
  { id: 'rrb-tech-g1-bca2-019', section: 'Basics of Computers and Applications', topic: 'Websites and Web Browsers', difficulty: 'easy', question: 'What is the primary purpose of a search engine such as Google Search?', options: ['To store user files', 'To send emails', 'To help users find information on the internet', 'To design web pages'], correctIndex: 2, explanation: 'A search engine helps users find relevant information and web pages on the internet by indexing and ranking web content.', source },
  { id: 'rrb-tech-g1-bca2-020', section: 'Basics of Computers and Applications', topic: 'Websites and Web Browsers', difficulty: 'medium', question: "What does the abbreviation 'HTML' stand for in web page design?", options: ['High Transfer Markup Language', 'HyperText Management Language', 'Host Text Markup Language', 'HyperText Markup Language'], correctIndex: 3, explanation: 'HTML stands for HyperText Markup Language, the standard markup language used to create and structure web pages.', source },
];
