import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'RRB Junior Engineer / DMS / CMA CEN No. 05/2025 official notification — CBT-I, General Awareness section',
  url: 'https://web.archive.org/web/2025/https://www.rrbcdg.gov.in/uploads/2025/05-JE/052025JE-CEN.pdf',
  checkedOn: '22 August 2026',
};

export const RRB_JE_CBT1_GENERAL_AWARENESS_2: Question[] = [
  { id: 'rrb-je-cbt1-ga2-001', section: 'General Awareness', topic: 'Indian History', difficulty: 'easy', question: 'Who was the first Governor-General of independent India?', options: ['Lord Mountbatten', 'C. Rajagopalachari', 'Rajendra Prasad', 'Warren Hastings'], correctIndex: 0, explanation: 'Lord Mountbatten served as the first Governor-General of independent India from 1947 to 1948.', source },
  { id: 'rrb-je-cbt1-ga2-002', section: 'General Awareness', topic: 'Indian History', difficulty: 'medium', question: 'The Jallianwala Bagh massacre took place in which city?', options: ['Lahore', 'Delhi', 'Amritsar', 'Chandigarh'], correctIndex: 2, explanation: 'The Jallianwala Bagh massacre occurred in Amritsar on 13 April 1919.', source },
  { id: 'rrb-je-cbt1-ga2-003', section: 'General Awareness', topic: 'Indian History', difficulty: 'medium', question: 'Who founded the Indian National Congress in 1885?', options: ['Bal Gangadhar Tilak', 'Allan Octavian Hume', 'Dadabhai Naoroji', 'Surendranath Banerjee'], correctIndex: 1, explanation: 'Allan Octavian Hume, a retired British civil servant, played a key role in founding the Indian National Congress in 1885.', source },
  { id: 'rrb-je-cbt1-ga2-004', section: 'General Awareness', topic: 'Indian History', difficulty: 'easy', question: 'The Quit India Movement was launched in which year?', options: ['1940', '1942', '1944', '1946'], correctIndex: 1, explanation: 'The Quit India Movement was launched by Mahatma Gandhi on 8 August 1942.', source },
  { id: 'rrb-je-cbt1-ga2-005', section: 'General Awareness', topic: 'Indian History', difficulty: 'hard', question: 'Which Mughal emperor built the Red Fort in Delhi?', options: ['Shah Jahan', 'Akbar', 'Jahangir', 'Aurangzeb'], correctIndex: 0, explanation: 'Shah Jahan commissioned the construction of the Red Fort, completed in 1648.', source },
  { id: 'rrb-je-cbt1-ga2-006', section: 'General Awareness', topic: 'Indian Geography', difficulty: 'easy', question: 'Which is the longest river in India?', options: ['Yamuna', 'Godavari', 'Narmada', 'Ganga'], correctIndex: 3, explanation: 'The Ganga is the longest river in India, flowing approximately 2,525 km.', source },
  { id: 'rrb-je-cbt1-ga2-007', section: 'General Awareness', topic: 'Indian Geography', difficulty: 'medium', question: 'Which Indian state has the longest coastline?', options: ['Tamil Nadu', 'Andhra Pradesh', 'Gujarat', 'Kerala'], correctIndex: 2, explanation: 'Gujarat has the longest coastline among Indian states, at roughly 1,600 km.', source },
  { id: 'rrb-je-cbt1-ga2-008', section: 'General Awareness', topic: 'Indian Economy', difficulty: 'medium', question: 'Which committee recommended the establishment of the Regional Rural Banks in India?', options: ['Narasimham Committee', 'Narasimha Committee on RRBs', 'M. Narasimham Working Group', 'Vaghul Committee'], correctIndex: 1, explanation: 'The Narasimha Committee on Rural Credit (1975) recommended setting up Regional Rural Banks, which were established in 1975.', source },
  { id: 'rrb-je-cbt1-ga2-009', section: 'General Awareness', topic: 'Indian Economy', difficulty: 'medium', question: 'Which organisation regulates the securities market in India?', options: ['SEBI', 'RBI', 'IRDAI', 'NABARD'], correctIndex: 0, explanation: 'The Securities and Exchange Board of India (SEBI) regulates the securities market in India.', source },
  { id: 'rrb-je-cbt1-ga2-010', section: 'General Awareness', topic: 'General Science', difficulty: 'easy', question: 'What is the chemical symbol for gold?', options: ['Gd', 'Go', 'Ag', 'Au'], correctIndex: 3, explanation: 'Gold\'s chemical symbol, Au, comes from its Latin name "aurum".', source },
  { id: 'rrb-je-cbt1-ga2-011', section: 'General Awareness', topic: 'General Science', difficulty: 'easy', question: 'Which gas is most abundant in the Earth\'s atmosphere?', options: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen'], correctIndex: 2, explanation: 'Nitrogen makes up about 78% of the Earth\'s atmosphere, the largest share of any gas.', source },
  { id: 'rrb-je-cbt1-ga2-012', section: 'General Awareness', topic: 'Static GK', difficulty: 'easy', question: 'Which is the smallest state in India by area?', options: ['Sikkim', 'Goa', 'Tripura', 'Nagaland'], correctIndex: 1, explanation: 'Goa is the smallest state in India by area, covering approximately 3,702 km².', source },
  { id: 'rrb-je-cbt1-ga2-013', section: 'General Awareness', topic: 'Static GK', difficulty: 'medium', question: 'The headquarters of the International Court of Justice is located in which city?', options: ['The Hague', 'Geneva', 'Vienna', 'Brussels'], correctIndex: 0, explanation: 'The International Court of Justice is headquartered at the Peace Palace in The Hague, Netherlands.', source },
  { id: 'rrb-je-cbt1-ga2-014', section: 'General Awareness', topic: 'Sports', difficulty: 'easy', question: 'In which sport is the term "googly" used?', options: ['Hockey', 'Badminton', 'Tennis', 'Cricket'], correctIndex: 3, explanation: 'A "googly" is a type of deceptive delivery bowled by a leg-spin bowler in cricket.', source },
  { id: 'rrb-je-cbt1-ga2-015', section: 'General Awareness', topic: 'Environment', difficulty: 'medium', question: 'World Environment Day is observed every year on which date?', options: ['22 April', '16 September', '5 June', '3 March'], correctIndex: 2, explanation: 'World Environment Day is observed on 5 June each year to promote environmental awareness.', source },
];
