import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'RRB Paramedical Categories CEN 03/2025 official notification, CBT syllabus: General Awareness. Second set. Restricted to facts fixed by the text of the Constitution, by dated historical events or by physical geography, rather than to current counts, office-holders, records or schemes, which cannot be re-verified as they change.',
  url: 'https://rrbsecunderabad.gov.in/wp-content/uploads/2025/08/Final-CEN-03_2025-English.pdf',
  checkedOn: '18 September 2026',
};

export const RRB_PARAMEDICAL_GENERAL_AWARENESS_2: Question[] = [
  { id: 'rrb-paramedical-ga-02-001', section: 'General Awareness', topic: 'Indian Polity', difficulty: 'easy', question: 'Which Article of the Constitution of India abolishes untouchability?', options: ['Article 17', 'Article 19', 'Article 21', 'Article 25'], correctIndex: 0, answerType: 'mcq', explanation: 'Article 17 abolishes untouchability and forbids its practice in any form. Article 19 covers the freedoms of speech and assembly, Article 21 the protection of life and personal liberty, and Article 25 the freedom of religion.', source },
  { id: 'rrb-paramedical-ga-02-002', section: 'General Awareness', topic: 'Indian Polity', difficulty: 'medium', question: 'Which Schedule of the Constitution of India lists the languages recognised by the Union?', options: ['Seventh Schedule', 'Eighth Schedule', 'Ninth Schedule', 'Tenth Schedule'], correctIndex: 1, answerType: 'mcq', explanation: 'The Eighth Schedule lists the recognised languages. The Seventh Schedule holds the Union, State and Concurrent Lists, the Ninth certain land reform laws, and the Tenth the anti-defection provisions.', source },
  { id: 'rrb-paramedical-ga-02-003', section: 'General Awareness', topic: 'Indian Geography', difficulty: 'medium', question: 'Which river is known as the Dakshina Ganga, or the Ganga of the South?', options: ['Krishna', 'Kaveri', 'Godavari', 'Narmada'], correctIndex: 2, answerType: 'mcq', explanation: 'The Godavari carries the name Dakshina Ganga. It is the longest river of peninsular India, rising in Maharashtra and flowing east into the Bay of Bengal.', source },
  { id: 'rrb-paramedical-ga-02-004', section: 'General Awareness', topic: 'Indian Geography', difficulty: 'medium', question: 'Which is the southernmost point of mainland India?', options: ['Indira Point', 'Rameswaram', 'Dhanushkodi', 'Kanyakumari'], correctIndex: 3, answerType: 'mcq', explanation: 'Kanyakumari is the southern tip of the mainland. Indira Point lies further south but is in the Nicobar Islands, so it is the southernmost point of India rather than of the mainland.', source },
  { id: 'rrb-paramedical-ga-02-005', section: 'General Awareness', topic: 'Freedom Struggle', difficulty: 'easy', question: 'In which year was the Indian National Congress founded?', options: ['1885', '1905', '1916', '1920'], correctIndex: 0, answerType: 'mcq', explanation: 'The Indian National Congress was founded in 1885. The other years mark the partition of Bengal, the Lucknow Pact and the start of the Non-Cooperation Movement.', source },
  { id: 'rrb-paramedical-ga-02-006', section: 'General Awareness', topic: 'Freedom Struggle', difficulty: 'medium', question: 'The Dandi March of 1930 was undertaken to protest against which measure?', options: ['The land revenue settlement', 'The tax on salt', 'The duty on cotton exports', 'The Rowlatt Act'], correctIndex: 1, answerType: 'mcq', explanation: 'The march to Dandi opened the Salt Satyagraha, a deliberate breach of the law that reserved salt manufacture to the government and taxed it. The Rowlatt Act had been the target of an earlier agitation in 1919.', source },
  { id: 'rrb-paramedical-ga-02-007', section: 'General Awareness', topic: 'Culture', difficulty: 'easy', question: 'Bharatanatyam is a classical dance form that originated in which Indian state?', options: ['Kerala', 'Karnataka', 'Tamil Nadu', 'Andhra Pradesh'], correctIndex: 2, answerType: 'mcq', explanation: 'Bharatanatyam originated in Tamil Nadu. Kathakali and Mohiniyattam belong to Kerala, Yakshagana to Karnataka, and Kuchipudi to Andhra Pradesh.', source },
  { id: 'rrb-paramedical-ga-02-008', section: 'General Awareness', topic: 'Indian Polity', difficulty: 'medium', question: 'Who administers the oath of office to the President of India?', options: ['The Prime Minister', 'The Vice-President', 'The Speaker of the Lok Sabha', 'The Chief Justice of India'], correctIndex: 3, answerType: 'mcq', explanation: 'Article 60 requires the oath to be made in the presence of the Chief Justice of India, or in the absence of the Chief Justice, the senior-most judge of the Supreme Court available.', source },
  { id: 'rrb-paramedical-ga-02-009', section: 'General Awareness', topic: 'Indian Economy', difficulty: 'medium', question: 'Which body administers the collection of direct taxes in India?', options: ['The Central Board of Direct Taxes', 'The Reserve Bank of India', 'The Securities and Exchange Board of India', 'The Comptroller and Auditor General'], correctIndex: 0, answerType: 'mcq', explanation: 'The Central Board of Direct Taxes, part of the Department of Revenue in the Ministry of Finance, administers direct taxes. The Reserve Bank handles monetary policy, SEBI regulates the securities market, and the Comptroller and Auditor General audits public accounts.', source },
  { id: 'rrb-paramedical-ga-02-010', section: 'General Awareness', topic: 'Environmental Issues', difficulty: 'medium', question: 'Which class of gases is chiefly responsible for depletion of the ozone layer?', options: ['Carbon dioxide', 'Chlorofluorocarbons', 'Methane', 'Sulphur dioxide'], correctIndex: 1, answerType: 'mcq', explanation: 'Chlorofluorocarbons release chlorine in the stratosphere, and each chlorine atom destroys many ozone molecules. Carbon dioxide and methane are greenhouse gases, and sulphur dioxide causes acid rain, but none of the three attacks ozone this way.', source },
];
