import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'RRB Paramedical Categories CEN 03/2025 official notification, CBT syllabus: General Arithmetic, General Intelligence and Reasoning',
  url: 'https://rrbsecunderabad.gov.in/wp-content/uploads/2025/08/Final-CEN-03_2025-English.pdf',
  checkedOn: '7 August 2026',
};

export const RRB_PARAMEDICAL_GENERAL_ARITHMETIC_REASONING_1: Question[] = [
  { id: 'rrb-pmed-gar-001', section: 'General Arithmetic, General Intelligence and Reasoning', topic: 'Percentages', difficulty: 'easy', question: 'What is 38% of 250?', options: ['91', '93', '95', '97'], correctIndex: 3, explanation: '38% of 250 = (38/100) × 250 = 95.', source },
  { id: 'rrb-pmed-gar-002', section: 'General Arithmetic, General Intelligence and Reasoning', topic: 'Ratio and Proportion', difficulty: 'medium', question: 'Divide ₹720 between A and B in the ratio 4:5. What is B\'s share?', options: ['₹380', '₹390', '₹400', '₹410'], correctIndex: 2, explanation: 'Total parts = 4 + 5 = 9. B\'s share = (5/9) × 720 = ₹400.', source },
  { id: 'rrb-pmed-gar-003', section: 'General Arithmetic, General Intelligence and Reasoning', topic: 'Time and Work', difficulty: 'medium', question: 'A can complete a task in 16 days and B can complete it in 24 days. Working together, how many days will they take?', options: ['9.2 days', '9.6 days', '10.2 days', '10.6 days'], correctIndex: 1, explanation: 'Combined rate = 1/16 + 1/24 = 3/48 + 2/48 = 5/48 per day. Time = 48/5 = 9.6 days.', source },
  { id: 'rrb-pmed-gar-004', section: 'General Arithmetic, General Intelligence and Reasoning', topic: 'Simple and Compound Interest', difficulty: 'medium', question: 'Find the simple interest on ₹7,200 at 6% per annum for 5 years.', options: ['₹1,980', '₹2,060', '₹2,160', '₹2,240'], correctIndex: 2, explanation: 'SI = (P × R × T) / 100 = (7200 × 6 × 5) / 100 = ₹2,160.', source },
  { id: 'rrb-pmed-gar-005', section: 'General Arithmetic, General Intelligence and Reasoning', topic: 'Profit and Loss', difficulty: 'medium', question: 'A trader buys an item for ₹560 and sells it for ₹644. Find the profit percentage.', options: ['12%', '15%', '18%', '20%'], correctIndex: 1, explanation: 'Profit = 644 − 560 = ₹84. Profit% = (84/560) × 100 = 15%.', source },
  { id: 'rrb-pmed-gar-006', section: 'General Arithmetic, General Intelligence and Reasoning', topic: 'Analogies', difficulty: 'easy', question: 'STETHOSCOPE is to DOCTOR as SYRINGE is to ?', options: ['Nurse', 'Teacher', 'Engineer', 'Pilot'], correctIndex: 0, explanation: 'A stethoscope is a tool primarily associated with a doctor, just as a syringe is a tool primarily associated with a nurse, so the relationship is one of tool to primary user.', source },
  { id: 'rrb-pmed-gar-007', section: 'General Arithmetic, General Intelligence and Reasoning', topic: 'Coding-Decoding', difficulty: 'medium', question: 'If NURSE is coded as OVSTF (each letter shifted one step forward), how would WARD be coded using the same rule?', options: ['XBSE', 'XBSD', 'XCSE', 'WBSE'], correctIndex: 0, explanation: 'Shifting each letter of WARD forward by one: W→X, A→B, R→S, D→E, giving XBSE.', source },
  { id: 'rrb-pmed-gar-008', section: 'General Arithmetic, General Intelligence and Reasoning', topic: 'Number Series', difficulty: 'medium', question: 'Find the next number in the series: 5, 10, 20, 40, ?', options: ['60', '70', '80', '90'], correctIndex: 2, explanation: 'Each term is double the previous term: 5×2=10, 10×2=20, 20×2=40, 40×2=80.', source },
  { id: 'rrb-pmed-gar-009', section: 'General Arithmetic, General Intelligence and Reasoning', topic: 'Blood Relations', difficulty: 'medium', question: "In a family, K is L's father, M is L's sister, and N is M's husband. How is N related to K?", options: ['Son', 'Son-in-law', 'Brother-in-law', 'Nephew'], correctIndex: 1, explanation: "M is K's daughter, and N is M's husband, which makes N the son-in-law of K.", source },
  { id: 'rrb-pmed-gar-010', section: 'General Arithmetic, General Intelligence and Reasoning', topic: 'Classification', difficulty: 'easy', question: 'Find the one that does not belong to the group: Nurse, Pharmacist, Radiographer, Clerk.', options: ['Nurse', 'Pharmacist', 'Radiographer', 'Clerk'], correctIndex: 3, explanation: 'Nurse, Pharmacist, and Radiographer are all paramedical roles, while Clerk is an administrative role, making it the odd one out.', source },
];
