import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'RRB Paramedical Categories CEN 03/2025 official notification, CBT syllabus: General Arithmetic and General Intelligence and Reasoning. Second set, built to the same difficulty mix as the first.',
  url: 'https://rrbsecunderabad.gov.in/wp-content/uploads/2025/08/Final-CEN-03_2025-English.pdf',
  checkedOn: '18 September 2026',
};

export const RRB_PARAMEDICAL_GENERAL_ARITHMETIC_REASONING_2: Question[] = [
  { id: 'rrb-paramedical-ar-02-001', section: 'General Arithmetic, General Intelligence and Reasoning', topic: 'Average', difficulty: 'easy', question: 'What is the average of 24, 36, 45, 51 and 54?', options: ['36', '40', '42', '45'], correctIndex: 2, answerType: 'mcq', explanation: 'The five numbers total 210, and 210 divided by 5 is 42.', source },
  { id: 'rrb-paramedical-ar-02-002', section: 'General Arithmetic, General Intelligence and Reasoning', topic: 'Time, Speed and Distance', difficulty: 'medium', question: 'A bus covers 270 km in 4 hours 30 minutes. What is its average speed in kilometres per hour?', options: ['45', '50', '55', '60'], correctIndex: 3, answerType: 'mcq', explanation: '4 hours 30 minutes is 4.5 hours, and 270 divided by 4.5 is 60 kilometres per hour.', source },
  { id: 'rrb-paramedical-ar-02-003', section: 'General Arithmetic, General Intelligence and Reasoning', topic: 'Simplification', difficulty: 'medium', question: 'Find the value of three-fifths of 250 added to two-sevenths of 189.', options: ['204', '210', '216', '230'], correctIndex: 0, answerType: 'mcq', explanation: 'Three-fifths of 250 is 150 and two-sevenths of 189 is 54, so the sum is 204.', source },
  { id: 'rrb-paramedical-ar-02-004', section: 'General Arithmetic, General Intelligence and Reasoning', topic: 'Percentage Increase', difficulty: 'medium', question: 'A monthly salary of ₹18,000 is increased by 15%. What is the new salary?', options: ['₹20,400', '₹20,700', '₹21,000', '₹21,600'], correctIndex: 1, answerType: 'mcq', explanation: 'An increase of 15% makes the salary 115% of ₹18,000, which is ₹20,700.', source },
  { id: 'rrb-paramedical-ar-02-005', section: 'General Arithmetic, General Intelligence and Reasoning', topic: 'Discount', difficulty: 'medium', question: 'An item marked at ₹1,800 is sold for ₹1,530. What is the rate of discount?', options: ['10%', '12%', '15%', '18%'], correctIndex: 2, answerType: 'mcq', explanation: 'The discount is ₹270 on a marked price of ₹1,800, and 270 as a percentage of 1,800 is 15%.', source },
  { id: 'rrb-paramedical-ar-02-006', section: 'General Arithmetic, General Intelligence and Reasoning', topic: 'Blood Relations', difficulty: 'easy', question: 'Pointing to a woman, a man said, "She is the daughter of the only son of my grandfather." How is the woman related to the man?', options: ['His daughter', 'His niece', 'His cousin', 'His sister'], correctIndex: 3, answerType: 'mcq', explanation: 'The only son of the man\'s grandfather is his own father, so the woman is his father\'s daughter, that is his sister.', source },
  { id: 'rrb-paramedical-ar-02-007', section: 'General Arithmetic, General Intelligence and Reasoning', topic: 'Direction Sense', difficulty: 'medium', question: 'A technician walks 4 km east, then 3 km north, then 4 km west. How far is the technician from the starting point?', options: ['3 km', '4 km', '5 km', '7 km'], correctIndex: 0, answerType: 'mcq', explanation: 'The eastward and westward walks cancel, leaving a net displacement of 3 km north, so the distance from the start is 3 km.', source },
  { id: 'rrb-paramedical-ar-02-008', section: 'General Arithmetic, General Intelligence and Reasoning', topic: 'Letter Series', difficulty: 'medium', question: 'Find the next letter in the series: B, E, H, K, ?', options: ['M', 'N', 'O', 'P'], correctIndex: 1, answerType: 'mcq', explanation: 'Each letter is three places after the one before it in the alphabet, and three places after K is N.', source },
  { id: 'rrb-paramedical-ar-02-009', section: 'General Arithmetic, General Intelligence and Reasoning', topic: 'Syllogism', difficulty: 'medium', question: 'Statements: All technicians are staff. Some staff are nurses. Conclusions: I. Some technicians are nurses. II. Some nurses are staff. Which conclusion follows?', options: ['Only conclusion I follows', 'Neither conclusion follows', 'Only conclusion II follows', 'Both conclusions follow'], correctIndex: 2, answerType: 'mcq', explanation: 'Conclusion II is simply the second statement read the other way round, so it follows. Conclusion I does not, because the staff who are nurses need not be among the technicians.', source },
  { id: 'rrb-paramedical-ar-02-010', section: 'General Arithmetic, General Intelligence and Reasoning', topic: 'Ranking and Order', difficulty: 'easy', question: 'In a row of 25 candidates, one candidate is ninth from the left end. What is that candidate\'s position from the right end?', options: ['14th', '15th', '16th', '17th'], correctIndex: 3, answerType: 'mcq', explanation: 'The position from the right is 25 − 9 + 1, which is 17th, since the candidate is counted in both directions.', source },
];
