import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'RRB Technician CEN 02/2025 official notification, CBT syllabus for Grade I Signal: Mathematics',
  url: 'https://rrbajmer.gov.in/Upload_PDF/Detailed%20CEN%202-2025_%20Technician%20Categories-638866538197092718.pdf',
  checkedOn: '7 August 2026',
};

export const RRB_TECHNICIAN_GRADE1_SIGNAL_MATHEMATICS_1: Question[] = [
  { id: 'rrb-tech-g1-math-001', section: 'Mathematics', topic: 'Number System', difficulty: 'easy', question: 'Which of the following is an irrational number?', options: ['√7', '4/9', '0.75', '-3'], correctIndex: 0, explanation: '√7 cannot be expressed as a ratio of two integers and its decimal expansion is non-terminating and non-repeating, making it irrational.', source },
  { id: 'rrb-tech-g1-math-002', section: 'Mathematics', topic: 'BODMAS', difficulty: 'easy', question: 'Simplify: 40 − (8 × 3) + 12 ÷ 4', options: ['19', '17', '21', '23'], correctIndex: 0, explanation: 'By BODMAS: 8 × 3 = 24, and 12 ÷ 4 = 3. Then 40 − 24 + 3 = 19.', source },
  { id: 'rrb-tech-g1-math-003', section: 'Mathematics', topic: 'Quadratic Equations', difficulty: 'medium', question: 'Find the roots of the quadratic equation x² − 7x + 12 = 0.', options: ['3, 4', '2, 6', '1, 12', '2, 5'], correctIndex: 0, explanation: 'Factoring: x² − 7x + 12 = (x−3)(x−4) = 0, giving roots x = 3 and x = 4.', source },
  { id: 'rrb-tech-g1-math-004', section: 'Mathematics', topic: 'Quadratic Equations', difficulty: 'medium', question: 'If one root of the quadratic equation x² − 9x + k = 0 is 5, find the value of k.', options: ['15', '18', '24', '20'], correctIndex: 3, explanation: 'If x=5 is a root: 25 − 45 + k = 0, so k = 20.', source },
  { id: 'rrb-tech-g1-math-005', section: 'Mathematics', topic: 'Arithmetic Progression', difficulty: 'medium', question: 'Find the 12th term of the arithmetic progression 5, 9, 13, 17, ...', options: ['47', '51', '53', '49'], correctIndex: 3, explanation: 'nth term = a + (n−1)d = 5 + 11×4 = 5 + 44 = 49.', source },
  { id: 'rrb-tech-g1-math-006', section: 'Mathematics', topic: 'Arithmetic Progression', difficulty: 'medium', question: 'Find the sum of the first 10 terms of the arithmetic progression 3, 7, 11, 15, ...', options: ['200', '220', '230', '210'], correctIndex: 3, explanation: 'Sum = n/2 × [2a + (n−1)d] = 10/2 × [6 + 9×4] = 5 × 42 = 210.', source },
  { id: 'rrb-tech-g1-math-007', section: 'Mathematics', topic: 'Similar Triangles', difficulty: 'medium', question: 'Two triangles are similar with a scale factor of 3:5. If the area of the smaller triangle is 27 sq cm, find the area of the larger triangle.', options: ['65 sq cm', '70 sq cm', '80 sq cm', '75 sq cm'], correctIndex: 3, explanation: 'The ratio of areas of similar triangles equals the square of the ratio of their sides: 3²:5² = 9:25. Area of larger triangle = 27 × (25/9) = 75 sq cm.', source },
  { id: 'rrb-tech-g1-math-008', section: 'Mathematics', topic: 'Pythagoras Theorem', difficulty: 'medium', question: 'A right-angled triangle has legs of 9 cm and 12 cm. Find the length of the hypotenuse.', options: ['13 cm', '14 cm', '16 cm', '15 cm'], correctIndex: 3, explanation: 'By the Pythagoras theorem, hypotenuse = √(9² + 12²) = √(81+144) = √225 = 15 cm.', source },
  { id: 'rrb-tech-g1-math-009', section: 'Mathematics', topic: 'Co-ordinate Geometry', difficulty: 'medium', question: 'Find the distance between the points (2, 3) and (6, 6) on a coordinate plane.', options: ['4 units', '5 units', '6 units', '7 units'], correctIndex: 1, explanation: 'Distance = √[(6−2)² + (6−3)²] = √(16+9) = √25 = 5 units.', source },
  { id: 'rrb-tech-g1-math-010', section: 'Mathematics', topic: 'Trigonometrical Ratios', difficulty: 'medium', question: 'What is the value of tan 45°?', options: ['0', '0.5', '1', '√3'], correctIndex: 2, explanation: 'tan 45° = 1, a standard trigonometric value.', source },
  { id: 'rrb-tech-g1-math-011', section: 'Mathematics', topic: 'Heights and Distances', difficulty: 'medium', question: 'A pole casts a shadow of 20 m when the sun\'s angle of elevation is 45°. Find the height of the pole.', options: ['15 m', '18 m', '20 m', '22 m'], correctIndex: 2, explanation: 'At a 45° angle of elevation, tan 45° = height/shadow = 1, so height equals the shadow length: 20 m.', source },
  { id: 'rrb-tech-g1-math-012', section: 'Mathematics', topic: 'Surface Area and Volume', difficulty: 'medium', question: 'Find the total surface area of a cube with side 8 cm.', options: ['364 sq cm', '374 sq cm', '384 sq cm', '394 sq cm'], correctIndex: 2, explanation: 'Total surface area of a cube = 6 × side² = 6 × 64 = 384 sq cm.', source },
  { id: 'rrb-tech-g1-math-013', section: 'Mathematics', topic: 'Surface Area and Volume', difficulty: 'medium', question: 'Find the volume of a cylinder with radius 14 cm and height 15 cm. (Use π = 22/7)', options: ['9,120 cubic cm', '9,240 cubic cm', '9,360 cubic cm', '9,480 cubic cm'], correctIndex: 1, explanation: 'Volume of cylinder = πr²h = (22/7) × 14² × 15 = (22/7) × 196 × 15 = 22 × 28 × 15 = 9,240 cubic cm.', source },
  { id: 'rrb-tech-g1-math-014', section: 'Mathematics', topic: 'Sets', difficulty: 'easy', question: 'If A = {2, 4, 6, 8} and B = {4, 8, 12}, find A ∩ B.', options: ['{2, 6}', '{4, 8}', '{2, 4, 6, 8, 12}', '{12}'], correctIndex: 1, explanation: 'The intersection A ∩ B contains elements common to both sets, which are 4 and 8.', source },
  { id: 'rrb-tech-g1-math-015', section: 'Mathematics', topic: 'Sets', difficulty: 'medium', question: 'If A = {1, 2, 3} and B = {3, 4, 5}, find A ∪ B.', options: ['{3}', '{1, 2, 3, 4, 5}', '{1, 2}', '{4, 5}'], correctIndex: 1, explanation: 'The union A ∪ B contains all elements that are in A, B, or both, which is {1, 2, 3, 4, 5}.', source },
  { id: 'rrb-tech-g1-math-016', section: 'Mathematics', topic: 'Statistics', difficulty: 'medium', question: 'Find the range of the data set: 12, 18, 7, 25, 14.', options: ['16', '17', '18', '19'], correctIndex: 2, explanation: 'Range = maximum value − minimum value = 25 − 7 = 18.', source },
  { id: 'rrb-tech-g1-math-017', section: 'Mathematics', topic: 'Statistics', difficulty: 'medium', question: 'Find the mean deviation about the mean for the data: 4, 6, 8, 10, 12.', options: ['2.0', '2.2', '2.4', '2.6'], correctIndex: 2, explanation: 'Mean = (4+6+8+10+12)/5 = 8. Absolute deviations from mean: 4,2,0,2,4, summing to 12. Mean deviation = 12/5 = 2.4.', source },
  { id: 'rrb-tech-g1-math-018', section: 'Mathematics', topic: 'Probability', difficulty: 'medium', question: 'A die is rolled once. What is the probability of getting a number greater than 4?', options: ['1/6', '1/3', '1/2', '2/3'], correctIndex: 1, explanation: 'Numbers greater than 4 on a die are 5 and 6, giving 2 favorable outcomes out of 6, so the probability is 2/6 = 1/3.', source },
  { id: 'rrb-tech-g1-math-019', section: 'Mathematics', topic: 'Probability', difficulty: 'medium', question: 'A bag contains 5 red balls and 3 blue balls. What is the probability of drawing a blue ball at random?', options: ['3/8', '3/5', '5/8', '1/3'], correctIndex: 0, explanation: 'There are 3 blue balls out of a total of 8 balls, so the probability of drawing a blue ball is 3/8.', source },
  { id: 'rrb-tech-g1-math-020', section: 'Mathematics', topic: 'Quadratic Equations', difficulty: 'hard', question: 'Using the quadratic formula, find the roots of 2x² − 5x − 3 = 0.', options: ['3, -0.5', '3, 0.5', '-3, 0.5', '-3, -0.5'], correctIndex: 0, explanation: 'Using x = [-b ± √(b²-4ac)] / 2a with a=2, b=-5, c=-3: discriminant = 25+24=49, √49=7. x = (5±7)/4, giving x=3 or x=-0.5.', source },
];
