import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'RRB Technician CEN 02/2025 official notification, CBT syllabus for Grade III: Mathematics',
  url: 'https://rrbajmer.gov.in/Upload_PDF/Detailed%20CEN%202-2025_%20Technician%20Categories-638866538197092718.pdf',
  checkedOn: '7 August 2026',
};

export const RRB_TECHNICIAN_GRADE3_MATHEMATICS_1: Question[] = [
  { id: 'rrb-tech-g3-math-001', section: 'Mathematics', topic: 'Number System', difficulty: 'easy', question: 'What is the sum of the first 30 natural numbers?', options: ['465', '435', '450', '480'], correctIndex: 0, explanation: 'Sum of first n natural numbers = n(n+1)/2 = 30 × 31 / 2 = 465.', source },
  { id: 'rrb-tech-g3-math-002', section: 'Mathematics', topic: 'BODMAS', difficulty: 'easy', question: 'Simplify: 36 ÷ (4 + 2) × 3 − 5', options: ['10', '13', '16', '19'], correctIndex: 1, explanation: 'By BODMAS: 4+2=6, then 36÷6=6, then 6×3=18, then 18−5=13.', source },
  { id: 'rrb-tech-g3-math-003', section: 'Mathematics', topic: 'Fractions and Decimals', difficulty: 'easy', question: 'What is 0.875 expressed as a fraction in its lowest terms?', options: ['5/8', '7/8', '3/4', '9/10'], correctIndex: 1, explanation: '0.875 = 875/1000, which simplifies (dividing by 125) to 7/8.', source },
  { id: 'rrb-tech-g3-math-004', section: 'Mathematics', topic: 'LCM and HCF', difficulty: 'medium', question: 'Find the LCM of 12 and 32.', options: ['96', '86', '90', '102'], correctIndex: 0, explanation: '12 = 2² × 3, 32 = 2⁵. LCM = 2⁵ × 3 = 96.', source },
  { id: 'rrb-tech-g3-math-005', section: 'Mathematics', topic: 'LCM and HCF', difficulty: 'medium', question: 'Find the HCF of 54 and 90.', options: ['16', '18', '20', '22'], correctIndex: 1, explanation: '54 = 2 × 3³, 90 = 2 × 3² × 5. HCF = 2 × 3² = 18.', source },
  { id: 'rrb-tech-g3-math-006', section: 'Mathematics', topic: 'Ratio and Proportion', difficulty: 'medium', question: 'Divide ₹960 between A and B in the ratio 3:5. What is A\'s share?', options: ['₹360', '₹340', '₹350', '₹370'], correctIndex: 0, explanation: 'Total parts = 3 + 5 = 8. A\'s share = (3/8) × 960 = ₹360.', source },
  { id: 'rrb-tech-g3-math-007', section: 'Mathematics', topic: 'Percentages', difficulty: 'easy', question: 'What is 32% of 275?', options: ['88', '84', '86', '90'], correctIndex: 0, explanation: '32% of 275 = (32/100) × 275 = 88.', source },
  { id: 'rrb-tech-g3-math-008', section: 'Mathematics', topic: 'Mensuration', difficulty: 'medium', question: 'Find the area of a rectangle with length 22 cm and breadth 7 cm.', options: ['154 sq cm', '144 sq cm', '150 sq cm', '160 sq cm'], correctIndex: 0, explanation: 'Area of rectangle = length × breadth = 22 × 7 = 154 sq cm.', source },
  { id: 'rrb-tech-g3-math-009', section: 'Mathematics', topic: 'Mensuration', difficulty: 'medium', question: 'Find the circumference of a circle with radius 14 cm. (Use π = 22/7)', options: ['84 cm', '88 cm', '92 cm', '96 cm'], correctIndex: 1, explanation: 'Circumference = 2πr = 2 × (22/7) × 14 = 88 cm.', source },
  { id: 'rrb-tech-g3-math-010', section: 'Mathematics', topic: 'Time and Work', difficulty: 'medium', question: 'A can complete a task in 20 days and B can complete it in 30 days. Working together, how many days will they take?', options: ['10 days', '11 days', '13 days', '12 days'], correctIndex: 3, explanation: 'Combined rate = 1/20 + 1/30 = 3/60 + 2/60 = 5/60 = 1/12 per day. Time = 12 days.', source },
  { id: 'rrb-tech-g3-math-011', section: 'Mathematics', topic: 'Time and Distance', difficulty: 'medium', question: 'A vehicle covers 225 km in 5 hours. What is its average speed?', options: ['40 km/h', '42 km/h', '48 km/h', '45 km/h'], correctIndex: 3, explanation: 'Speed = distance / time = 225 / 5 = 45 km/h.', source },
  { id: 'rrb-tech-g3-math-012', section: 'Mathematics', topic: 'Simple and Compound Interest', difficulty: 'medium', question: 'Find the simple interest on ₹9,000 at 5% per annum for 6 years.', options: ['₹2,500', '₹2,600', '₹2,800', '₹2,700'], correctIndex: 3, explanation: 'SI = (P × R × T) / 100 = (9000 × 5 × 6) / 100 = ₹2,700.', source },
  { id: 'rrb-tech-g3-math-013', section: 'Mathematics', topic: 'Profit and Loss', difficulty: 'medium', question: 'A trader buys an item for ₹640 and sells it for ₹768. Find the profit percentage.', options: ['16%', '18%', '22%', '20%'], correctIndex: 3, explanation: 'Profit = 768 − 640 = ₹128. Profit% = (128/640) × 100 = 20%.', source },
  { id: 'rrb-tech-g3-math-014', section: 'Mathematics', topic: 'Algebra', difficulty: 'medium', question: 'If 6y − 11 = 37, find the value of y.', options: ['6', '7', '9', '8'], correctIndex: 3, explanation: '6y = 37 + 11 = 48, so y = 48/6 = 8.', source },
  { id: 'rrb-tech-g3-math-015', section: 'Mathematics', topic: 'Geometry', difficulty: 'medium', question: 'In a triangle, two angles measure 62° and 58°. What is the third angle?', options: ['54°', '58°', '64°', '60°'], correctIndex: 3, explanation: 'Sum of angles in a triangle = 180°. Third angle = 180 − 62 − 58 = 60°.', source },
  { id: 'rrb-tech-g3-math-016', section: 'Mathematics', topic: 'Trigonometry', difficulty: 'medium', question: 'What is the value of cos 60° × 2?', options: ['0.5', '1', '1.5', '2'], correctIndex: 1, explanation: 'cos 60° = 0.5, so cos 60° × 2 = 0.5 × 2 = 1.', source },
  { id: 'rrb-tech-g3-math-017', section: 'Mathematics', topic: 'Elementary Statistics', difficulty: 'medium', question: 'Find the mean of the numbers 8, 14, 20, 26, 32.', options: ['18', '19', '20', '21'], correctIndex: 2, explanation: 'Mean = (8+14+20+26+32)/5 = 100/5 = 20.', source },
  { id: 'rrb-tech-g3-math-018', section: 'Mathematics', topic: 'Square Root', difficulty: 'easy', question: 'What is the square root of 784?', options: ['26', '27', '28', '29'], correctIndex: 2, explanation: '28 × 28 = 784, so √784 = 28.', source },
  { id: 'rrb-tech-g3-math-019', section: 'Mathematics', topic: 'Age Calculations', difficulty: 'medium', question: "A father's age is 5 times his son's age. After 8 years, the father will be 3 times as old as his son. Find the son's present age.", options: ['6 years', '7 years', '8 years', '9 years'], correctIndex: 2, explanation: "Let son's present age be x, so father's age = 5x. After 8 years: 5x+8 = 3(x+8), giving 5x+8 = 3x+24, so 2x=16, x=8 years.", source },
  { id: 'rrb-tech-g3-math-020', section: 'Mathematics', topic: 'Calendar and Clock', difficulty: 'medium', question: 'What is the angle between the hour and minute hands of a clock at 3:00?', options: ['80°', '85°', '90°', '95°'], correctIndex: 2, explanation: 'At 3:00, the hour hand is at 90° from 12, and the minute hand is at 0°, giving an angle of 90°.', source },
  { id: 'rrb-tech-g3-math-021', section: 'Mathematics', topic: 'Pipes and Cisterns', difficulty: 'medium', question: 'Pipe A can fill a tank in 15 hours and Pipe B can empty it in 25 hours. If both are opened together, how long will it take to fill the tank?', options: ['33.5 hours', '35.5 hours', '37.5 hours', '39.5 hours'], correctIndex: 2, explanation: 'Combined rate = 1/15 − 1/25 = 5/75 − 3/75 = 2/75 per hour. Time to fill = 75/2 = 37.5 hours.', source },
  { id: 'rrb-tech-g3-math-022', section: 'Mathematics', topic: 'Number System', difficulty: 'medium', question: 'What is the remainder when 187 is divided by 13?', options: ['5', '6', '7', '8'], correctIndex: 0, explanation: '13 × 14 = 182, and 187 − 182 = 5, so the remainder is 5.', source },
  { id: 'rrb-tech-g3-math-023', section: 'Mathematics', topic: 'Ratio and Proportion', difficulty: 'medium', question: 'If a machine produces 480 units in 8 hours, how many units will it produce in 5 hours at the same rate?', options: ['280', '290', '300', '310'], correctIndex: 2, explanation: 'Rate = 480/8 = 60 units per hour. In 5 hours: 60 × 5 = 300 units.', source },
  { id: 'rrb-tech-g3-math-024', section: 'Mathematics', topic: 'Profit and Loss', difficulty: 'medium', question: 'A trader marks an item 30% above its cost price and offers a 10% discount. Find the resulting profit percentage.', options: ['15%', '17%', '19%', '21%'], correctIndex: 1, explanation: 'Let cost price be 100. Marked price = 130. After 10% discount: 130 × 0.9 = 117. Profit = 117 − 100 = 17%.', source },
  { id: 'rrb-tech-g3-math-025', section: 'Mathematics', topic: 'Time and Work', difficulty: 'hard', question: 'A alone can complete a task in 20 days. A and B together complete it in 12 days. In how many days can B alone complete the task?', options: ['26 days', '28 days', '30 days', '32 days'], correctIndex: 2, explanation: "A's rate = 1/20. Combined rate = 1/12. B's rate = 1/12 − 1/20 = 5/60 − 3/60 = 2/60 = 1/30. B alone takes 30 days.", source },
];
