import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'RRB NTPC CEN 07/2025 official notification, CBT 1 syllabus — General Intelligence and Reasoning section',
  url: 'https://www.rrbchennai.gov.in/downloads/CEN-07-2025-NTPC-UnderGraduate-English.pdf',
  checkedOn: '10 August 2026',
};

export const RRB_NTPC_CBT1_REASONING_1: Question[] = [
  {
    id: 'rrb-ntpc-cbt1-reasoning-001',
    section: 'General Intelligence and Reasoning',
    topic: 'Analogy',
    difficulty: 'easy',
    question: 'Book is to Author as Painting is to ___?',
    options: ['Painter', 'Canvas', 'Brush', 'Gallery'],
    correctIndex: 0,
    explanation: 'An author creates a book; a painter creates a painting — the relationship is creator to creation.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-reasoning-002',
    section: 'General Intelligence and Reasoning',
    topic: 'Analogy',
    difficulty: 'easy',
    question: 'Gram is to Kilogram as Millilitre is to ___?',
    options: ['Metre', 'Litre', 'Second', 'Gram'],
    correctIndex: 1,
    explanation: 'A kilogram is 1,000 grams; a litre is 1,000 millilitres — both pairs relate a smaller unit to its larger equivalent.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-reasoning-003',
    section: 'General Intelligence and Reasoning',
    topic: 'Classification',
    difficulty: 'easy',
    question: 'Find the shape that does not belong: Triangle, Square, Circle, Cube.',
    options: ['Triangle', 'Square', 'Cube', 'Circle'],
    correctIndex: 2,
    explanation: 'Triangle, Square, and Circle are 2D shapes; a Cube is a 3D shape.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-reasoning-004',
    section: 'General Intelligence and Reasoning',
    topic: 'Classification',
    difficulty: 'easy',
    question: 'Which of the following does not belong to the group?',
    options: ['Rose', 'Lotus', 'Marigold', 'Mango'],
    correctIndex: 3,
    explanation: 'Rose, Lotus, and Marigold are flowers; Mango is a fruit.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-reasoning-005',
    section: 'General Intelligence and Reasoning',
    topic: 'Number series',
    difficulty: 'easy',
    question: 'Find the next number: 3, 6, 12, 24, ?',
    options: ['48', '36', '42', '54'],
    correctIndex: 0,
    explanation: 'Each term is double the previous one: 24 × 2 = 48.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-reasoning-006',
    section: 'General Intelligence and Reasoning',
    topic: 'Number series',
    difficulty: 'medium',
    question: 'Find the next number: 2, 6, 12, 20, 30, ?',
    options: ['36', '42', '40', '44'],
    correctIndex: 1,
    explanation: 'The differences between terms increase by 2 each time (4, 6, 8, 10, 12), so the next term is 30 + 12 = 42.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-reasoning-007',
    section: 'General Intelligence and Reasoning',
    topic: 'Alphabet series',
    difficulty: 'medium',
    question: 'Find the missing letter: A, D, G, J, ?',
    options: ['K', 'L', 'M', 'N'],
    correctIndex: 2,
    explanation: 'Each letter advances by 3 positions in the alphabet: A(1), D(4), G(7), J(10), so the next is M(13).',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-reasoning-008',
    section: 'General Intelligence and Reasoning',
    topic: 'Coding-decoding',
    difficulty: 'medium',
    question: 'If CAT is coded as DBU (each letter shifted forward by 1), how is DOG coded?',
    options: ['EPG', 'FPH', 'EPI', 'EPH'],
    correctIndex: 3,
    explanation: 'Shifting each letter forward by 1: D→E, O→P, G→H, giving EPH.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-reasoning-009',
    section: 'General Intelligence and Reasoning',
    topic: 'Coding-decoding',
    difficulty: 'medium',
    question: 'If GARDEN is coded as HBSEFO (each letter shifted forward by 1), how is FLOWER coded?',
    options: ['GMPXFS', 'GMQXFS', 'GMPXFT', 'HMPXFS'],
    correctIndex: 0,
    explanation: 'Shifting each letter forward by 1: F→G, L→M, O→P, W→X, E→F, R→S, giving GMPXFS.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-reasoning-010',
    section: 'General Intelligence and Reasoning',
    topic: 'Blood relations',
    difficulty: 'medium',
    question: "Pointing to a photograph, Ravi said, \"She is the daughter of my mother's only son.\" How is the girl related to Ravi?",
    options: ['Sister', 'Daughter', 'Niece', 'Wife'],
    correctIndex: 1,
    explanation: "Ravi's mother's only son is Ravi himself, so the girl is Ravi's daughter.",
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-reasoning-011',
    section: 'General Intelligence and Reasoning',
    topic: 'Blood relations',
    difficulty: 'easy',
    question: 'P is the brother of Q, and Q is the sister of R. How is P related to R?',
    options: ['Father', 'Uncle', 'Brother', 'Cousin'],
    correctIndex: 2,
    explanation: 'P, Q, and R are siblings. Since P is male (described as "brother"), P is R\'s brother.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-reasoning-012',
    section: 'General Intelligence and Reasoning',
    topic: 'Direction sense',
    difficulty: 'easy',
    question: 'A man walks 5 km towards north, then turns right and walks 3 km. Which direction is he facing now?',
    options: ['North', 'South', 'West', 'East'],
    correctIndex: 3,
    explanation: 'Facing north and turning right means he now faces east.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-reasoning-013',
    section: 'General Intelligence and Reasoning',
    topic: 'Direction sense',
    difficulty: 'medium',
    question: 'A man walks 4 km east, then 3 km north. How far is he from his starting point?',
    options: ['5 km', '6 km', '7 km', '8 km'],
    correctIndex: 0,
    explanation: 'The path forms a right triangle with legs 4 km and 3 km, so the direct distance is √(4² + 3²) = √25 = 5 km.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-reasoning-014',
    section: 'General Intelligence and Reasoning',
    topic: 'Syllogism',
    difficulty: 'medium',
    question: 'Statements: All pens are pencils. All pencils are erasers. Conclusion: All pens are erasers. Is this conclusion valid?',
    options: ['Invalid', 'Valid', 'Cannot be determined', 'Partially valid'],
    correctIndex: 1,
    explanation: 'This is a direct chain: all pens are pencils, and all pencils are erasers, so all pens must be erasers.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-reasoning-015',
    section: 'General Intelligence and Reasoning',
    topic: 'Syllogism',
    difficulty: 'medium',
    question: 'Statements: Some cats are dogs. All dogs are animals. Conclusion: Some cats are animals. Is this conclusion valid?',
    options: ['Invalid', 'Cannot be determined', 'Valid', 'Partially valid'],
    correctIndex: 2,
    explanation: 'Since some cats are dogs, and all dogs are animals, those same cats must be animals — so some cats are animals follows validly.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-reasoning-016',
    section: 'General Intelligence and Reasoning',
    topic: 'Mathematical operations',
    difficulty: 'medium',
    question: "If P means '+', Q means '−', R means '×', and S means '÷', what is 6 R 4 Q 2 P 5?",
    options: ['25', '26', '28', '27'],
    correctIndex: 3,
    explanation: 'Substituting symbols: 6 × 4 − 2 + 5. Following order of operations: 6 × 4 = 24, then 24 − 2 = 22, then 22 + 5 = 27.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-reasoning-017',
    section: 'General Intelligence and Reasoning',
    topic: 'Classification',
    difficulty: 'medium',
    question: 'Find the number that does not belong: 8, 27, 64, 100',
    options: ['100', '27', '64', '8'],
    correctIndex: 0,
    explanation: '8 = 2³, 27 = 3³, and 64 = 4³ are all perfect cubes, but 100 is not a perfect cube.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-reasoning-018',
    section: 'General Intelligence and Reasoning',
    topic: 'Alphabet test',
    difficulty: 'medium',
    question: 'How many letters are there between H and P in the English alphabet?',
    options: ['6', '7', '8', '9'],
    correctIndex: 1,
    explanation: 'The letters between H and P are I, J, K, L, M, N, and O — a total of 7 letters.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-reasoning-019',
    section: 'General Intelligence and Reasoning',
    topic: 'Classification',
    difficulty: 'easy',
    question: 'Which one of these is not like the other three?',
    options: ['Delhi', 'Mumbai', 'India', 'Kolkata'],
    correctIndex: 2,
    explanation: 'Delhi, Mumbai, and Kolkata are cities; India is a country.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-reasoning-020',
    section: 'General Intelligence and Reasoning',
    topic: 'Number series',
    difficulty: 'easy',
    question: 'Find the missing number: 5, 10, 20, 40, ?, 160',
    options: ['70', '75', '85', '80'],
    correctIndex: 3,
    explanation: 'Each term doubles the previous one: 40 × 2 = 80, and 80 × 2 = 160 (which matches the given last term).',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-reasoning-021',
    section: 'General Intelligence and Reasoning',
    topic: 'Analogy',
    difficulty: 'medium',
    question: 'Doctor is to Hospital as Teacher is to ___?',
    options: ['School', 'Book', 'Student', 'Classroom'],
    correctIndex: 0,
    explanation: 'A hospital is where a doctor works; a school is where a teacher works.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-reasoning-022',
    section: 'General Intelligence and Reasoning',
    topic: 'Classification',
    difficulty: 'medium',
    question: 'Identify the item that does not fit with the rest of the group.',
    options: ['Sparrow', 'Bat', 'Penguin', 'Eagle'],
    correctIndex: 1,
    explanation: 'Sparrow, Eagle, and Penguin are birds; a Bat is a mammal.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-reasoning-023',
    section: 'General Intelligence and Reasoning',
    topic: 'Number series',
    difficulty: 'hard',
    question: 'Find the next term: 1, 4, 9, 16, 25, ?',
    options: ['30', '32', '36', '34'],
    correctIndex: 2,
    explanation: 'The series is perfect squares (1², 2², 3², 4², 5²), so the next term is 6² = 36.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-reasoning-024',
    section: 'General Intelligence and Reasoning',
    topic: 'Coding-decoding',
    difficulty: 'hard',
    question: 'If TEACHER is coded as VGCEJGT (each letter shifted forward by 2), how is STUDENT coded?',
    options: ['UVWFGPU', 'UVWGFPV', 'UVWFHPV', 'UVWFGPV'],
    correctIndex: 3,
    explanation: 'Shifting each letter forward by 2: S→U, T→V, U→W, D→F, E→G, N→P, T→V, giving UVWFGPV.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-reasoning-025',
    section: 'General Intelligence and Reasoning',
    topic: 'Blood relations',
    difficulty: 'hard',
    question: 'A is the son of B. B is the sister of C. C is the father of D. How is A related to D?',
    options: ['Cousin', 'Brother', 'Nephew', 'Uncle'],
    correctIndex: 0,
    explanation: "B is C's sister, so B is D's aunt (C is D's father). A is B's son, making A the cousin of D.",
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-reasoning-026',
    section: 'General Intelligence and Reasoning',
    topic: 'Direction sense',
    difficulty: 'hard',
    question: 'A person starts from point X, walks 6 km towards south, then walks 8 km towards east. How far is he now from point X?',
    options: ['8 km', '10 km', '9 km', '12 km'],
    correctIndex: 1,
    explanation: 'The path forms a right triangle with legs 6 km and 8 km, so the direct distance is √(6² + 8²) = √100 = 10 km.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-reasoning-027',
    section: 'General Intelligence and Reasoning',
    topic: 'Alphabet series',
    difficulty: 'medium',
    question: 'Find the next term: Z, X, V, T, ?',
    options: ['Q', 'S', 'R', 'U'],
    correctIndex: 2,
    explanation: 'Each letter moves back 2 positions: Z(26), X(24), V(22), T(20), so the next is R(18).',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-reasoning-028',
    section: 'General Intelligence and Reasoning',
    topic: 'Ranking and order',
    difficulty: 'medium',
    question: 'In a class of 40 students, Ravi ranks 15th from the top. What is his rank from the bottom?',
    options: ['24', '25', '27', '26'],
    correctIndex: 3,
    explanation: 'Rank from the bottom = total students − rank from top + 1 = 40 − 15 + 1 = 26.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-reasoning-029',
    section: 'General Intelligence and Reasoning',
    topic: 'Syllogism',
    difficulty: 'medium',
    question: 'Statements: All doctors are educated. Some educated people are rich. Conclusion: Some doctors are rich. Is this conclusion valid?',
    options: ['Invalid', 'Valid', 'Cannot be determined', 'Partially valid'],
    correctIndex: 0,
    explanation: 'The "educated" group linking the two statements is not fully accounted for — the rich educated people are not confirmed to overlap with doctors, so the conclusion does not necessarily follow.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-reasoning-030',
    section: 'General Intelligence and Reasoning',
    topic: 'Number series',
    difficulty: 'medium',
    question: 'Find the next number: 100, 96, 89, 79, ?',
    options: ['63', '66', '64', '65'],
    correctIndex: 1,
    explanation: 'The differences between terms are −4, −7, −10 (each 3 more than the last), so the next difference is −13, giving 79 − 13 = 66.',
    source,
  },
];
