import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'RRB Technician CEN 02/2025 official notification, CBT syllabus for Grade I Signal: Basics of Computers and Applications',
  url: 'https://rrbajmer.gov.in/Upload_PDF/Detailed%20CEN%202-2025_%20Technician%20Categories-638866538197092718.pdf',
  checkedOn: '7 August 2026',
};

export const RRB_TECHNICIAN_GRADE1_SIGNAL_COMPUTERS_APPLICATIONS_1: Question[] = [
  { id: 'rrb-tech-g1-bca-001', section: 'Basics of Computers and Applications', topic: 'Computer Architecture', difficulty: 'easy', question: 'Which component of a computer is often called its "brain" because it carries out instructions?', options: ['RAM', 'Hard disk', 'CPU', 'Monitor'], correctIndex: 2, explanation: 'The Central Processing Unit (CPU) executes instructions and performs calculations, which is why it is often called the "brain" of the computer.', source },
  { id: 'rrb-tech-g1-bca-002', section: 'Basics of Computers and Applications', topic: 'Input and Output Devices', difficulty: 'easy', question: 'Among Printer, Monitor, Keyboard, and Speaker, which one is used to enter data into a computer rather than to produce output?', options: ['Printer', 'Monitor', 'Keyboard', 'Speaker'], correctIndex: 2, explanation: 'A keyboard is an input device used to enter data into a computer, unlike a printer, monitor, or speaker, which are all output devices.', source },
  { id: 'rrb-tech-g1-bca-003', section: 'Basics of Computers and Applications', topic: 'Storage Devices', difficulty: 'medium', question: 'Which type of computer memory is non-volatile, retaining data even when power is switched off?', options: ['RAM', 'Cache memory', 'ROM', 'Register'], correctIndex: 2, explanation: 'ROM (Read-Only Memory) is non-volatile memory that retains its data even after the power supply is switched off, unlike RAM.', source },
  { id: 'rrb-tech-g1-bca-004', section: 'Basics of Computers and Applications', topic: 'Storage Devices', difficulty: 'medium', question: 'What does the abbreviation "SSD" stand for in computer storage terminology?', options: ['Secondary Storage Drive', 'System Storage Device', 'Solid State Drive', 'Static Storage Disk'], correctIndex: 2, explanation: 'SSD stands for Solid State Drive, a storage device that uses flash memory with no moving parts, unlike a traditional hard disk drive.', source },
  { id: 'rrb-tech-g1-bca-005', section: 'Basics of Computers and Applications', topic: 'Networking', difficulty: 'medium', question: 'What does the abbreviation "LAN" stand for in computer networking?', options: ['Large Area Network', 'Linked Access Node', 'Long Access Network', 'Local Area Network'], correctIndex: 3, explanation: 'LAN stands for Local Area Network, a network that connects computers within a limited geographic area such as an office or building.', source },
  { id: 'rrb-tech-g1-bca-006', section: 'Basics of Computers and Applications', topic: 'Networking', difficulty: 'medium', question: 'Which device is used to connect multiple networks and direct data packets between them based on IP addresses?', options: ['Switch', 'Hub', 'Modem', 'Router'], correctIndex: 3, explanation: 'A router directs data packets between different networks based on IP addresses, unlike a switch or hub, which typically operate within a single network.', source },
  { id: 'rrb-tech-g1-bca-007', section: 'Basics of Computers and Applications', topic: 'Operating Systems', difficulty: 'medium', question: 'Which of the following is an open-source operating system?', options: ['Windows', 'macOS', 'Linux', 'iOS'], correctIndex: 2, explanation: 'Linux is an open-source operating system, meaning its source code is freely available for anyone to view, modify, and distribute.', source },
  { id: 'rrb-tech-g1-bca-008', section: 'Basics of Computers and Applications', topic: 'Operating Systems', difficulty: 'medium', question: 'What is the primary function of an operating system?', options: ['To create documents and spreadsheets', 'To browse the internet', 'To design graphics', 'To manage computer hardware and software resources'], correctIndex: 3, explanation: 'An operating system manages a computer\'s hardware and software resources, acting as an intermediary between the user and the hardware.', source },
  { id: 'rrb-tech-g1-bca-009', section: 'Basics of Computers and Applications', topic: 'MS Office', difficulty: 'easy', question: 'Which MS Office application is primarily used for creating spreadsheets?', options: ['MS Word', 'MS PowerPoint', 'MS Access', 'MS Excel'], correctIndex: 3, explanation: 'MS Excel is the MS Office application primarily used for creating and managing spreadsheets.', source },
  { id: 'rrb-tech-g1-bca-010', section: 'Basics of Computers and Applications', topic: 'MS Office', difficulty: 'medium', question: 'In MS Word, which keyboard shortcut is commonly used to save a document?', options: ['Ctrl+P', 'Ctrl+C', 'Ctrl+Z', 'Ctrl+S'], correctIndex: 3, explanation: 'Ctrl+S is the standard keyboard shortcut used to save a document in MS Word and most other applications.', source },
  { id: 'rrb-tech-g1-bca-011', section: 'Basics of Computers and Applications', topic: 'Data Representation', difficulty: 'medium', question: 'In computer data representation, one byte is equal to how many bits?', options: ['4 bits', '8 bits', '16 bits', '32 bits'], correctIndex: 1, explanation: 'One byte is equal to 8 bits, the standard unit for representing a single character in most computer systems.', source },
  { id: 'rrb-tech-g1-bca-012', section: 'Basics of Computers and Applications', topic: 'Data Representation', difficulty: 'medium', question: 'What is the binary equivalent of the decimal number 10?', options: ['1010', '1001', '1100', '1011'], correctIndex: 0, explanation: '10 in decimal equals 8+2, which is 1010 in binary (1×8 + 0×4 + 1×2 + 0×1 = 10).', source },
  { id: 'rrb-tech-g1-bca-013', section: 'Basics of Computers and Applications', topic: 'Internet and Email', difficulty: 'easy', question: 'What does the abbreviation "URL" stand for?', options: ['Uniform Resource Locator', 'Universal Reference Link', 'Unique Resource List', 'Uniform Reference Locator'], correctIndex: 0, explanation: 'URL stands for Uniform Resource Locator, the address used to locate a resource on the internet.', source },
  { id: 'rrb-tech-g1-bca-014', section: 'Basics of Computers and Applications', topic: 'Internet and Email', difficulty: 'medium', question: 'In an email address, what does the symbol "@" separate?', options: ['The subject from the body', 'The username from the domain name', 'The sender from the receiver', 'The date from the time'], correctIndex: 1, explanation: 'The "@" symbol in an email address separates the username from the domain name of the mail server.', source },
  { id: 'rrb-tech-g1-bca-015', section: 'Basics of Computers and Applications', topic: 'Websites and Web Browsers', difficulty: 'medium', question: 'Which of the following is a widely used web browser?', options: ['Google Chrome', 'MS Excel', 'Adobe Photoshop', 'VLC Media Player'], correctIndex: 0, explanation: 'Google Chrome is a widely used web browser used to access and navigate websites on the internet.', source },
  { id: 'rrb-tech-g1-bca-016', section: 'Basics of Computers and Applications', topic: 'Websites and Web Browsers', difficulty: 'medium', question: 'What does the abbreviation "HTTP" stand for in a website address?', options: ['HyperText Transfer Protocol', 'High Transfer Text Protocol', 'HyperText Transmission Process', 'Host Text Transfer Protocol'], correctIndex: 0, explanation: 'HTTP stands for HyperText Transfer Protocol, the protocol used for transferring web pages over the internet.', source },
  { id: 'rrb-tech-g1-bca-017', section: 'Basics of Computers and Applications', topic: 'Computer Virus', difficulty: 'medium', question: 'What is a computer virus?', options: ['A hardware component that speeds up processing', 'A malicious program that can replicate itself and harm a system', 'A type of antivirus software', 'A backup storage format'], correctIndex: 1, explanation: 'A computer virus is a malicious program designed to replicate itself and spread to other files or systems, often causing harm or disruption.', source },
  { id: 'rrb-tech-g1-bca-018', section: 'Basics of Computers and Applications', topic: 'Computer Virus', difficulty: 'medium', question: 'Which type of software is specifically designed to detect and remove computer viruses?', options: ['Antivirus software', 'Compiler', 'Operating system', 'Spreadsheet software'], correctIndex: 0, explanation: 'Antivirus software is specifically designed to detect, quarantine, and remove computer viruses and other malware.', source },
  { id: 'rrb-tech-g1-bca-019', section: 'Basics of Computers and Applications', topic: 'Computer Architecture', difficulty: 'medium', question: 'Which of the following best describes RAM in a computer system?', options: ['Permanent storage that never loses data', 'Temporary, volatile memory used for actively running programs', 'A type of printer', 'An output device'], correctIndex: 1, explanation: 'RAM (Random Access Memory) is volatile, temporary memory used to hold data for programs that are actively running, and it loses its contents when power is switched off.', source },
  { id: 'rrb-tech-g1-bca-020', section: 'Basics of Computers and Applications', topic: 'Operating Systems', difficulty: 'medium', question: 'Which of these operating systems is developed and maintained primarily as a Unix-like open-source system, distinct from Windows?', options: ['Windows 11', 'Unix/Linux', 'MS-DOS', 'Windows Server'], correctIndex: 1, explanation: 'Unix and its open-source derivative Linux are Unix-like operating systems, architecturally distinct from the Windows family.', source },
];
