import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'RRB Technician CEN 02/2025 official notification, CBT syllabus for Grade I Signal: General Awareness',
  url: 'https://rrbajmer.gov.in/Upload_PDF/Detailed%20CEN%202-2025_%20Technician%20Categories-638866538197092718.pdf',
  checkedOn: '23 August 2026',
};

export const RRB_TECHNICIAN_GRADE1_SIGNAL_GENERAL_AWARENESS_2: Question[] = [
  { id: 'rrb-tech-g1-ga2-001', section: 'General Awareness', topic: 'Culture', difficulty: 'easy', question: 'Bharatanatyam, one of the oldest classical dance forms of India, originated in which state?', options: ['Tamil Nadu', 'Kerala', 'Karnataka', 'Andhra Pradesh'], correctIndex: 0, explanation: 'Bharatanatyam is a classical dance form that originated in the temples of Tamil Nadu.', source },
  { id: 'rrb-tech-g1-ga2-002', section: 'General Awareness', topic: 'Current Affairs', difficulty: 'medium', question: "What is the primary aim of India's Production Linked Incentive (PLI) scheme?", options: ['To subsidize agricultural exports', 'To boost domestic manufacturing by rewarding incremental production', "To fund state governments' infrastructure directly", 'To regulate foreign portfolio investment'], correctIndex: 1, explanation: 'The PLI scheme offers financial incentives to companies for incremental sales of goods manufactured in India, boosting domestic manufacturing capacity.', source },
  { id: 'rrb-tech-g1-ga2-003', section: 'General Awareness', topic: 'Environmental Issues', difficulty: 'medium', question: 'The Ramsar Convention is an international treaty concerned with the conservation of what?', options: ['Coral reefs', 'Glaciers', 'Wetlands', 'Mangrove forests'], correctIndex: 2, explanation: 'The Ramsar Convention, signed in 1971, is an intergovernmental treaty for the conservation and wise use of wetlands.', source },
  { id: 'rrb-tech-g1-ga2-004', section: 'General Awareness', topic: 'Freedom Struggle', difficulty: 'medium', question: 'In which year did Mahatma Gandhi lead the Dandi March (Salt Satyagraha)?', options: ['1928', '1932', '1942', '1930'], correctIndex: 3, explanation: 'Mahatma Gandhi led the Dandi March, also called the Salt Satyagraha, in 1930 to protest the British salt tax.', source },
  { id: 'rrb-tech-g1-ga2-005', section: 'General Awareness', topic: 'Indian Economy', difficulty: 'medium', question: 'NITI Aayog, established in 2015, replaced which earlier planning body?', options: ['Planning Commission', 'Finance Commission', 'Tariff Commission', 'Investment Commission'], correctIndex: 0, explanation: 'NITI Aayog was formed in 2015 to replace the Planning Commission as the premier policy think tank of the Government of India.', source },
  { id: 'rrb-tech-g1-ga2-006', section: 'General Awareness', topic: 'Indian Geography', difficulty: 'medium', question: 'Which of the following is the highest peak located entirely within India?', options: ['Nanda Devi', 'Kangchenjunga', 'K2', 'Kamet'], correctIndex: 1, explanation: 'Kangchenjunga, on the Sikkim-Nepal border, is the highest peak that lies substantially within Indian territory and the highest in India.', source },
  { id: 'rrb-tech-g1-ga2-007', section: 'General Awareness', topic: 'Indian History', difficulty: 'medium', question: 'Who founded the Mughal Empire in India after defeating Ibrahim Lodi at the First Battle of Panipat (1526)?', options: ['Humayun', 'Akbar', 'Babur', 'Sher Shah Suri'], correctIndex: 2, explanation: 'Babur founded the Mughal Empire in India after his victory over Ibrahim Lodi at the First Battle of Panipat in 1526.', source },
  { id: 'rrb-tech-g1-ga2-008', section: 'General Awareness', topic: 'Indian Polity', difficulty: 'medium', question: 'The Right to Constitutional Remedies is guaranteed under which Article of the Indian Constitution?', options: ['Article 19', 'Article 21', 'Article 14', 'Article 32'], correctIndex: 3, explanation: 'Article 32 guarantees the Right to Constitutional Remedies, allowing citizens to move the Supreme Court to enforce their fundamental rights.', source },
  { id: 'rrb-tech-g1-ga2-009', section: 'General Awareness', topic: 'Science and Technology', difficulty: 'medium', question: "ISRO's Aditya-L1 mission, launched in 2023, is designed to study which celestial body?", options: ['The Sun', 'The Moon', 'Mars', 'Venus'], correctIndex: 0, explanation: 'Aditya-L1 is an ISRO mission placed near the L1 Lagrange point to study the Sun, particularly its outer atmosphere.', source },
  { id: 'rrb-tech-g1-ga2-010', section: 'General Awareness', topic: 'Sports', difficulty: 'easy', question: "The Major Dhyan Chand Khel Ratna Award is India's highest honour in which field?", options: ['Literature', 'Sports', 'Cinema', 'Science'], correctIndex: 1, explanation: 'The Major Dhyan Chand Khel Ratna Award, renamed from the Rajiv Gandhi Khel Ratna Award, is the highest sporting honour in India.', source },
];
