import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'RRB Assistant Loco Pilot CEN 01/2025 official notification, Second Stage CBT Part A syllabus: Mathematics',
  url: 'https://rrbbilaspur.gov.in/file/notice/Revised_CEN_01-2025_ALP.pdf',
  checkedOn: '23 August 2026',
};

export const RRB_ALP_CBT2_MATHEMATICS_2: Question[] = [
  { id: 'rrb-alp-cbt2-math2-001', section: 'Mathematics', topic: 'Number System', difficulty: 'easy', question: 'What is the sum of the first 30 natural numbers?', options: ['465', '460', '470', '455'], correctIndex: 0, explanation: 'Sum of first n natural numbers = n(n+1)/2 = 30 × 31 / 2 = 465.', source },
  { id: 'rrb-alp-cbt2-math2-002', section: 'Mathematics', topic: 'BODMAS', difficulty: 'easy', question: 'Simplify: 40 − (6 × 4) + 8 ÷ 2', options: ['18', '20', '22', '16'], correctIndex: 1, explanation: 'By BODMAS: 6 × 4 = 24, and 8 ÷ 2 = 4. Then 40 − 24 + 4 = 20.', source },
  { id: 'rrb-alp-cbt2-math2-003', section: 'Mathematics', topic: 'Fractions and Decimals', difficulty: 'easy', question: 'What is 0.45 expressed as a fraction in its lowest terms?', options: ['9/20', '9/25', '3/8', '7/20'], correctIndex: 0, explanation: '0.45 = 45/100, which simplifies (dividing by 5) to 9/20.', source },
  { id: 'rrb-alp-cbt2-math2-004', section: 'Mathematics', topic: 'LCM and HCF', difficulty: 'medium', question: 'Find the LCM of 20 and 45.', options: ['170', '190', '160', '180'], correctIndex: 3, explanation: '20 = 2² × 5, 45 = 3² × 5. LCM = 2² × 3² × 5 = 180.', source },
  { id: 'rrb-alp-cbt2-math2-005', section: 'Mathematics', topic: 'LCM and HCF', difficulty: 'medium', question: 'Find the HCF of 56 and 98.', options: ['16', '12', '14', '18'], correctIndex: 2, explanation: '56 = 2³ × 7, 98 = 2 × 7². HCF = 2 × 7 = 14.', source },
  { id: 'rrb-alp-cbt2-math2-006', section: 'Mathematics', topic: 'Ratio and Proportion', difficulty: 'medium', question: 'Divide ₹960 between A and B in the ratio 9:7. What is B\'s share?', options: ['₹400', '₹420', '₹440', '₹460'], correctIndex: 1, explanation: 'Total parts = 9 + 7 = 16. B\'s share = (7/16) × 960 = ₹420.', source },
  { id: 'rrb-alp-cbt2-math2-007', section: 'Mathematics', topic: 'Percentages', difficulty: 'easy', question: 'What is 55% of 280?', options: ['154', '148', '160', '142'], correctIndex: 0, explanation: '55% of 280 = (55/100) × 280 = 154.', source },
  { id: 'rrb-alp-cbt2-math2-008', section: 'Mathematics', topic: 'Mensuration', difficulty: 'medium', question: 'Find the area of a triangle with base 20 cm and height 13 cm.', options: ['125 sq cm', '135 sq cm', '120 sq cm', '130 sq cm'], correctIndex: 3, explanation: 'Area of triangle = (1/2) × base × height = (1/2) × 20 × 13 = 130 sq cm.', source },
  { id: 'rrb-alp-cbt2-math2-009', section: 'Mathematics', topic: 'Mensuration', difficulty: 'medium', question: 'Find the volume of a cube with side 9 cm.', options: ['719 cubic cm', '739 cubic cm', '729 cubic cm', '709 cubic cm'], correctIndex: 2, explanation: 'Volume of cube = side³ = 9³ = 729 cubic cm.', source },
  { id: 'rrb-alp-cbt2-math2-010', section: 'Mathematics', topic: 'Time and Work', difficulty: 'medium', question: 'A can finish a job in 18 days and B can finish it in 27 days. Working together, how many days will they take?', options: ['11.2 days', '10.8 days', '10.4 days', '11.6 days'], correctIndex: 1, explanation: 'Combined rate = 1/18 + 1/27 = 3/54 + 2/54 = 5/54 per day. Time = 54/5 = 10.8 days.', source },
  { id: 'rrb-alp-cbt2-math2-011', section: 'Mathematics', topic: 'Time and Distance', difficulty: 'medium', question: 'A train covers 396 km in 5.5 hours. What is its average speed?', options: ['72 km/h', '70 km/h', '74 km/h', '68 km/h'], correctIndex: 0, explanation: 'Speed = distance / time = 396 / 5.5 = 72 km/h.', source },
  { id: 'rrb-alp-cbt2-math2-012', section: 'Mathematics', topic: 'Simple and Compound Interest', difficulty: 'medium', question: 'Find the simple interest on ₹8,800 at 7% per annum for 3 years.', options: ['₹1,800', '₹1,880', '₹1,820', '₹1,848'], correctIndex: 3, explanation: 'SI = (P × R × T) / 100 = (8800 × 7 × 3) / 100 = ₹1,848.', source },
  { id: 'rrb-alp-cbt2-math2-013', section: 'Mathematics', topic: 'Profit and Loss', difficulty: 'medium', question: 'A shopkeeper buys an item for ₹720 and sells it for ₹828. Find the profit percentage.', options: ['12%', '18%', '15%', '20%'], correctIndex: 2, explanation: 'Profit = 828 − 720 = ₹108. Profit% = (108/720) × 100 = 15%.', source },
  { id: 'rrb-alp-cbt2-math2-014', section: 'Mathematics', topic: 'Algebra', difficulty: 'medium', question: 'If 7z + 4 = 46, find the value of z.', options: ['7', '6', '5', '8'], correctIndex: 1, explanation: '7z = 46 − 4 = 42, so z = 42/7 = 6.', source },
  { id: 'rrb-alp-cbt2-math2-015', section: 'Mathematics', topic: 'Geometry', difficulty: 'medium', question: 'In a triangle, two angles measure 38° and 82°. What is the third angle?', options: ['60°', '55°', '65°', '50°'], correctIndex: 0, explanation: 'Sum of angles in a triangle = 180°. Third angle = 180 − 38 − 82 = 60°.', source },
  { id: 'rrb-alp-cbt2-math2-016', section: 'Mathematics', topic: 'Trigonometry', difficulty: 'medium', question: 'What is the value of cos 0° + sin 0°?', options: ['0', '0.5', '2', '1'], correctIndex: 3, explanation: 'cos 0° = 1 and sin 0° = 0. Their sum is 1 + 0 = 1.', source },
  { id: 'rrb-alp-cbt2-math2-017', section: 'Mathematics', topic: 'Elementary Statistics', difficulty: 'medium', question: 'Find the mean of the numbers 18, 22, 26, 30, 34.', options: ['24', '28', '26', '22'], correctIndex: 2, explanation: 'Mean = (18+22+26+30+34)/5 = 130/5 = 26.', source },
  { id: 'rrb-alp-cbt2-math2-018', section: 'Mathematics', topic: 'Square Root', difficulty: 'easy', question: 'What is the square root of 784?', options: ['27', '28', '29', '26'], correctIndex: 1, explanation: '28 × 28 = 784, so √784 = 28.', source },
  { id: 'rrb-alp-cbt2-math2-019', section: 'Mathematics', topic: 'Age Calculations', difficulty: 'medium', question: 'A mother is 4 times as old as her daughter. After 8 years, the mother will be twice as old as her daughter. Find the daughter\'s present age.', options: ['4 years', '5 years', '6 years', '8 years'], correctIndex: 0, explanation: 'Let daughter\'s present age be x, so mother\'s age = 4x. After 8 years: 4x+8 = 2(x+8), giving 4x+8 = 2x+16, so x = 4 years.', source },
  { id: 'rrb-alp-cbt2-math2-020', section: 'Mathematics', topic: 'Calendar and Clock', difficulty: 'medium', question: 'What is the angle between the hour and minute hands of a clock at 3:00?', options: ['80°', '100°', '110°', '90°'], correctIndex: 3, explanation: 'At 3:00, the hour hand is at 90° from 12, and the minute hand is at 0°, giving an angle of 90°.', source },
  { id: 'rrb-alp-cbt2-math2-021', section: 'Mathematics', topic: 'Pipes and Cisterns', difficulty: 'medium', question: 'Pipe A can fill a tank in 10 hours and Pipe B can empty it in 15 hours. If both are opened together, how long will it take to fill the tank?', options: ['28 hours', '32 hours', '30 hours', '34 hours'], correctIndex: 2, explanation: 'Combined rate = 1/10 − 1/15 = 3/30 − 2/30 = 1/30 per hour. Time to fill = 30 hours.', source },
  { id: 'rrb-alp-cbt2-math2-022', section: 'Mathematics', topic: 'Number System', difficulty: 'medium', question: 'What is the remainder when 205 is divided by 9?', options: ['5', '7', '6', '8'], correctIndex: 1, explanation: '9 × 22 = 198, and 205 − 198 = 7, so the remainder is 7.', source },
  { id: 'rrb-alp-cbt2-math2-023', section: 'Mathematics', topic: 'Ratio and Proportion', difficulty: 'medium', question: 'If a train covers a distance in 9 hours at 50 km/h, at what speed must it travel to cover the same distance in 6 hours?', options: ['75 km/h', '70 km/h', '80 km/h', '85 km/h'], correctIndex: 0, explanation: 'Distance = 50 × 9 = 450 km. Speed needed for 6 hours = 450/6 = 75 km/h.', source },
  { id: 'rrb-alp-cbt2-math2-024', section: 'Mathematics', topic: 'Profit and Loss', difficulty: 'medium', question: 'A trader marks an item 30% above its cost price and offers a 10% discount. Find the resulting profit percentage.', options: ['15%', '20%', '13%', '17%'], correctIndex: 3, explanation: 'Let cost price be 100. Marked price = 130. After 10% discount: 130 × 0.9 = 117. Profit = 117 − 100 = 17%.', source },
  { id: 'rrb-alp-cbt2-math2-025', section: 'Mathematics', topic: 'Time and Work', difficulty: 'hard', question: 'A alone can complete a task in 15 days. A and B together complete it in 6 days. In how many days can B alone complete the task?', options: ['12 days', '9 days', '10 days', '11 days'], correctIndex: 2, explanation: 'A\'s rate = 1/15. Combined rate = 1/6. B\'s rate = 1/6 − 1/15 = 5/30 − 2/30 = 3/30 = 1/10. B alone takes 10 days.', source },
];
