import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'RRB Assistant Loco Pilot CEN 01/2025 official notification, First Stage CBT syllabus: Mathematics',
  url: 'https://rrbbilaspur.gov.in/file/notice/Revised_CEN_01-2025_ALP.pdf',
  checkedOn: '7 August 2026',
};

export const RRB_ALP_CBT1_MATHEMATICS_1: Question[] = [
  { id: 'rrb-alp-cbt1-math-001', section: 'Mathematics', topic: 'Number System', difficulty: 'easy', question: 'What is the sum of the first 15 natural numbers?', options: ['120', '110', '115', '125'], correctIndex: 0, explanation: 'Sum of first n natural numbers = n(n+1)/2 = 15 × 16 / 2 = 120.', source },
  { id: 'rrb-alp-cbt1-math-002', section: 'Mathematics', topic: 'BODMAS', difficulty: 'easy', question: 'Simplify: 24 − (6 + 2) × 2', options: ['8', '10', '12', '14'], correctIndex: 0, explanation: 'By BODMAS, the bracket is solved first: 6 + 2 = 8. Then multiplication: 8 × 2 = 16. Finally 24 − 16 = 8.', source },
  { id: 'rrb-alp-cbt1-math-003', section: 'Mathematics', topic: 'Fractions and Decimals', difficulty: 'easy', question: 'What is 0.375 expressed as a fraction in its lowest terms?', options: ['3/7', '3/8', '5/8', '3/10'], correctIndex: 1, explanation: '0.375 = 375/1000, which simplifies (dividing by 125) to 3/8.', source },
  { id: 'rrb-alp-cbt1-math-004', section: 'Mathematics', topic: 'LCM and HCF', difficulty: 'medium', question: 'Find the LCM of 16 and 24.', options: ['48', '40', '44', '52'], correctIndex: 0, explanation: '16 = 2⁴, 24 = 2³ × 3. LCM = 2⁴ × 3 = 48.', source },
  { id: 'rrb-alp-cbt1-math-005', section: 'Mathematics', topic: 'LCM and HCF', difficulty: 'medium', question: 'Find the HCF of 45 and 75.', options: ['15', '10', '12', '18'], correctIndex: 0, explanation: '45 = 3² × 5, 75 = 3 × 5². HCF = 3 × 5 = 15.', source },
  { id: 'rrb-alp-cbt1-math-006', section: 'Mathematics', topic: 'Ratio and Proportion', difficulty: 'medium', question: 'Divide ₹720 between A and B in the ratio 5:4. What is A\'s share?', options: ['₹400', '₹360', '₹380', '₹420'], correctIndex: 0, explanation: 'Total parts = 5 + 4 = 9. A\'s share = (5/9) × 720 = ₹400.', source },
  { id: 'rrb-alp-cbt1-math-007', section: 'Mathematics', topic: 'Percentages', difficulty: 'easy', question: 'What is 35% of 260?', options: ['81', '85', '96', '91'], correctIndex: 3, explanation: '35% of 260 = (35/100) × 260 = 91.', source },
  { id: 'rrb-alp-cbt1-math-008', section: 'Mathematics', topic: 'Mensuration', difficulty: 'medium', question: 'Find the area of a rectangle with length 18 cm and breadth 8 cm.', options: ['132 sq cm', '138 sq cm', '150 sq cm', '144 sq cm'], correctIndex: 3, explanation: 'Area of rectangle = length × breadth = 18 × 8 = 144 sq cm.', source },
  { id: 'rrb-alp-cbt1-math-009', section: 'Mathematics', topic: 'Mensuration', difficulty: 'medium', question: 'Find the perimeter of a square with side 21 cm.', options: ['76 cm', '80 cm', '88 cm', '84 cm'], correctIndex: 3, explanation: 'Perimeter of square = 4 × side = 4 × 21 = 84 cm.', source },
  { id: 'rrb-alp-cbt1-math-010', section: 'Mathematics', topic: 'Time and Work', difficulty: 'medium', question: 'A can finish a job in 12 days and B can finish it in 18 days. Working together, how many days will they take?', options: ['6.4 days', '7.2 days', '8 days', '9 days'], correctIndex: 1, explanation: 'Combined rate = 1/12 + 1/18 = 3/36 + 2/36 = 5/36 per day. Time = 36/5 = 7.2 days.', source },
  { id: 'rrb-alp-cbt1-math-011', section: 'Mathematics', topic: 'Time and Distance', difficulty: 'medium', question: 'A train covers 210 km in 3.5 hours. What is its average speed?', options: ['55 km/h', '58 km/h', '62 km/h', '60 km/h'], correctIndex: 3, explanation: 'Speed = distance / time = 210 / 3.5 = 60 km/h.', source },
  { id: 'rrb-alp-cbt1-math-012', section: 'Mathematics', topic: 'Simple and Compound Interest', difficulty: 'medium', question: 'Find the simple interest on ₹8,400 at 6% per annum for 5 years.', options: ['₹2,400', '₹2,460', '₹2,580', '₹2,520'], correctIndex: 3, explanation: 'SI = (P × R × T) / 100 = (8400 × 6 × 5) / 100 = ₹2,520.', source },
  { id: 'rrb-alp-cbt1-math-013', section: 'Mathematics', topic: 'Profit and Loss', difficulty: 'medium', question: 'A shopkeeper buys an item for ₹520 and sells it for ₹598. Find the profit percentage.', options: ['12%', '15%', '18%', '20%'], correctIndex: 1, explanation: 'Profit = 598 − 520 = ₹78. Profit% = (78/520) × 100 = 15%.', source },
  { id: 'rrb-alp-cbt1-math-014', section: 'Mathematics', topic: 'Algebra', difficulty: 'medium', question: 'If 4x − 7 = 21, find the value of x.', options: ['5', '6', '7', '8'], correctIndex: 2, explanation: '4x = 21 + 7 = 28, so x = 28/4 = 7.', source },
  { id: 'rrb-alp-cbt1-math-015', section: 'Mathematics', topic: 'Geometry', difficulty: 'medium', question: 'In a triangle, two angles measure 55° and 65°. What is the third angle?', options: ['55°', '60°', '65°', '70°'], correctIndex: 1, explanation: 'Sum of angles in a triangle = 180°. Third angle = 180 − 55 − 65 = 60°.', source },
  { id: 'rrb-alp-cbt1-math-016', section: 'Mathematics', topic: 'Elementary Statistics', difficulty: 'medium', question: 'Find the mean of the numbers 12, 18, 22, 24, 29.', options: ['19', '20', '21', '22'], correctIndex: 2, explanation: 'Mean = (12+18+22+24+29)/5 = 105/5 = 21.', source },
  { id: 'rrb-alp-cbt1-math-017', section: 'Mathematics', topic: 'Square Root', difficulty: 'easy', question: 'What is the square root of 529?', options: ['21', '22', '23', '24'], correctIndex: 2, explanation: '23 × 23 = 529, so √529 = 23.', source },
  { id: 'rrb-alp-cbt1-math-018', section: 'Mathematics', topic: 'Age Calculations', difficulty: 'medium', question: "A father is 4 times as old as his son. After 5 years, the father will be 3 times as old as his son. Find the son's present age.", options: ['8 years', '9 years', '10 years', '11 years'], correctIndex: 2, explanation: "Let son's present age be x, so father's age = 4x. After 5 years: 4x+5 = 3(x+5), giving 4x+5 = 3x+15, so x = 10 years.", source },
  { id: 'rrb-alp-cbt1-math-019', section: 'Mathematics', topic: 'Calendar and Clock', difficulty: 'medium', question: 'If 1 January of a leap year was a Sunday, what day of the week was 1 January of the following year?', options: ['Monday', 'Tuesday', 'Wednesday', 'Thursday'], correctIndex: 1, explanation: 'A leap year has 366 days, which is 52 weeks and 2 extra days, so the day of the week advances by 2: Sunday + 2 = Tuesday.', source },
  { id: 'rrb-alp-cbt1-math-020', section: 'Mathematics', topic: 'Pipes and Cisterns', difficulty: 'medium', question: 'Pipe A can fill a tank in 10 hours and Pipe B can empty it in 15 hours. If both are opened together, how long will it take to fill the tank?', options: ['25 hours', '28 hours', '30 hours', '32 hours'], correctIndex: 2, explanation: 'Combined rate = 1/10 − 1/15 = 3/30 − 2/30 = 1/30 per hour. Time to fill = 30 hours.', source },
];
