import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'RRB Assistant Loco Pilot CEN 01/2025 official notification, First Stage CBT syllabus: General Awareness',
  url: 'https://rrbbilaspur.gov.in/file/notice/Revised_CEN_01-2025_ALP.pdf',
  checkedOn: '7 August 2026',
};

export const RRB_ALP_CBT1_GENERAL_AWARENESS_1: Question[] = [
  { id: 'rrb-alp-cbt1-ga-001', section: 'General Awareness', topic: 'Indian Railways', difficulty: 'easy', question: 'Which ministry oversees the Railway Recruitment Boards in India?', options: ['Ministry of Railways', 'Ministry of Road Transport', 'Ministry of Civil Aviation', 'Ministry of Shipping'], correctIndex: 0, explanation: 'The Railway Recruitment Boards function under the Ministry of Railways, Government of India.', source },
  { id: 'rrb-alp-cbt1-ga-002', section: 'General Awareness', topic: 'Sports', difficulty: 'easy', question: 'How many players are there on a standard hockey team on the field at one time?', options: ['9', '10', '11', '12'], correctIndex: 2, explanation: 'A standard field hockey team fields 11 players at a time, similar to football.', source },
  { id: 'rrb-alp-cbt1-ga-003', section: 'General Awareness', topic: 'Culture', difficulty: 'easy', question: 'Bharatanatyam is a classical dance form that originated in which Indian state?', options: ['Tamil Nadu', 'Kerala', 'Odisha', 'Andhra Pradesh'], correctIndex: 0, explanation: 'Bharatanatyam is a classical dance form that originated in Tamil Nadu.', source },
  { id: 'rrb-alp-cbt1-ga-004', section: 'General Awareness', topic: 'Economics', difficulty: 'medium', question: 'What does GDP stand for in economics?', options: ['General Domestic Product', 'Gross Development Product', 'General Development Product', 'Gross Domestic Product'], correctIndex: 3, explanation: 'GDP stands for Gross Domestic Product, which measures the total monetary value of goods and services produced within a country in a given period.', source },
  { id: 'rrb-alp-cbt1-ga-005', section: 'General Awareness', topic: 'Polity', difficulty: 'medium', question: 'Who is the constitutional head of the Indian Railways in terms of administrative oversight?', options: ['President of India', 'Prime Minister', 'Minister of Railways', 'Chief Justice of India'], correctIndex: 2, explanation: 'The Minister of Railways heads the Ministry of Railways, which administers Indian Railways operations.', source },
  { id: 'rrb-alp-cbt1-ga-006', section: 'General Awareness', topic: 'Science and Technology', difficulty: 'medium', question: 'Which Indian organization is responsible for the country\'s space research programs?', options: ['DRDO', 'BARC', 'CSIR', 'ISRO'], correctIndex: 3, explanation: 'ISRO (Indian Space Research Organisation) is the national space agency responsible for India\'s space research and satellite programs.', source },
  { id: 'rrb-alp-cbt1-ga-007', section: 'General Awareness', topic: 'Personalities', difficulty: 'medium', question: 'Who is widely credited as the father of the Indian locomotive and railway engineering education movement, after whom several railway institutes are named?', options: ['Jamsetji Tata', 'Homi Bhabha', 'M. Visvesvaraya', 'Vikram Sarabhai'], correctIndex: 2, explanation: 'M. Visvesvaraya was a pioneering Indian engineer widely honored for his contributions to engineering education and infrastructure, and Engineers\' Day in India is celebrated on his birthday.', source },
  { id: 'rrb-alp-cbt1-ga-008', section: 'General Awareness', topic: 'Current Affairs', difficulty: 'medium', question: 'The "Kavach" system, deployed by Indian Railways, is primarily designed to do what?', options: ['Improve ticket booking speed', 'Prevent train collisions through automatic braking', 'Increase coach seating capacity', 'Reduce electricity consumption'], correctIndex: 1, explanation: 'Kavach is an indigenous Automatic Train Protection system that applies automatic brakes to prevent train collisions when a driver fails to control the train as per speed and signal requirements.', source },
  { id: 'rrb-alp-cbt1-ga-009', section: 'General Awareness', topic: 'Geography', difficulty: 'medium', question: 'Which is the longest railway platform in the world, located in India?', options: ['Kollam Junction', 'Gorakhpur Junction', 'Kharagpur Junction', 'Bilaspur Junction'], correctIndex: 1, explanation: 'Gorakhpur Junction in Uttar Pradesh holds the record for the longest railway platform in the world.', source },
  { id: 'rrb-alp-cbt1-ga-010', section: 'General Awareness', topic: 'History', difficulty: 'medium', question: 'In which year did India\'s first passenger train run between Bombay and Thane?', options: ['1851', '1853', '1857', '1861'], correctIndex: 1, explanation: 'India\'s first passenger train ran between Bombay (Bori Bunder) and Thane on 16 April 1853.', source },
];
