import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'RRB Assistant Loco Pilot CEN 01/2025 official notification, First Stage CBT syllabus: Mathematics',
  url: 'https://rrbbilaspur.gov.in/file/notice/Revised_CEN_01-2025_ALP.pdf',
  checkedOn: '23 August 2026',
};

export const RRB_ALP_CBT1_MATHEMATICS_2: Question[] = [
  { id: 'rrb-alp-cbt1-math2-001', section: 'Mathematics', topic: 'Number System', difficulty: 'easy', question: 'What is the sum of the first 18 natural numbers?', options: ['171', '170', '172', '169'], correctIndex: 0, explanation: 'Sum of first n natural numbers = n(n+1)/2 = 18 × 19 / 2 = 171.', source },
  { id: 'rrb-alp-cbt1-math2-002', section: 'Mathematics', topic: 'BODMAS', difficulty: 'easy', question: 'Simplify: 32 − (7 + 3) × 2', options: ['14', '16', '12', '10'], correctIndex: 2, explanation: 'By BODMAS, the bracket is solved first: 7 + 3 = 10. Then multiplication: 10 × 2 = 20. Finally 32 − 20 = 12.', source },
  { id: 'rrb-alp-cbt1-math2-003', section: 'Mathematics', topic: 'Fractions and Decimals', difficulty: 'easy', question: 'What is 0.875 expressed as a fraction in its lowest terms?', options: ['5/8', '7/8', '3/4', '7/10'], correctIndex: 1, explanation: '0.875 = 875/1000, which simplifies (dividing by 125) to 7/8.', source },
  { id: 'rrb-alp-cbt1-math2-004', section: 'Mathematics', topic: 'LCM and HCF', difficulty: 'medium', question: 'Find the LCM of 18 and 30.', options: ['90', '96', '84', '88'], correctIndex: 0, explanation: '18 = 2 × 3², 30 = 2 × 3 × 5. LCM = 2 × 3² × 5 = 90.', source },
  { id: 'rrb-alp-cbt1-math2-005', section: 'Mathematics', topic: 'LCM and HCF', difficulty: 'medium', question: 'Find the HCF of 60 and 84.', options: ['14', '16', '18', '12'], correctIndex: 3, explanation: '60 = 2² × 3 × 5, 84 = 2² × 3 × 7. HCF = 2² × 3 = 12.', source },
  { id: 'rrb-alp-cbt1-math2-006', section: 'Mathematics', topic: 'Ratio and Proportion', difficulty: 'medium', question: 'Divide ₹960 between A and B in the ratio 7:5. What is A\'s share?', options: ['₹520', '₹540', '₹560', '₹580'], correctIndex: 2, explanation: 'Total parts = 7 + 5 = 12. A\'s share = (7/12) × 960 = ₹560.', source },
  { id: 'rrb-alp-cbt1-math2-007', section: 'Mathematics', topic: 'Percentages', difficulty: 'easy', question: 'What is 28% of 350?', options: ['92', '98', '104', '88'], correctIndex: 1, explanation: '28% of 350 = (28/100) × 350 = 98.', source },
  { id: 'rrb-alp-cbt1-math2-008', section: 'Mathematics', topic: 'Mensuration', difficulty: 'medium', question: 'Find the area of a rectangle with length 24 cm and breadth 11 cm.', options: ['264 sq cm', '258 sq cm', '270 sq cm', '248 sq cm'], correctIndex: 0, explanation: 'Area of rectangle = length × breadth = 24 × 11 = 264 sq cm.', source },
  { id: 'rrb-alp-cbt1-math2-009', section: 'Mathematics', topic: 'Mensuration', difficulty: 'medium', question: 'Find the perimeter of a square with side 27 cm.', options: ['104 cm', '112 cm', '116 cm', '108 cm'], correctIndex: 3, explanation: 'Perimeter of square = 4 × side = 4 × 27 = 108 cm.', source },
  { id: 'rrb-alp-cbt1-math2-010', section: 'Mathematics', topic: 'Time and Work', difficulty: 'medium', question: 'A can finish a job in 16 days and B can finish it in 24 days. Working together, how many days will they take?', options: ['9 days', '10 days', '9.6 days', '8.5 days'], correctIndex: 2, explanation: 'Combined rate = 1/16 + 1/24 = 3/48 + 2/48 = 5/48 per day. Time = 48/5 = 9.6 days.', source },
  { id: 'rrb-alp-cbt1-math2-011', section: 'Mathematics', topic: 'Time and Distance', difficulty: 'medium', question: 'A train covers 245 km in 3.5 hours. What is its average speed?', options: ['65 km/h', '70 km/h', '75 km/h', '60 km/h'], correctIndex: 1, explanation: 'Speed = distance / time = 245 / 3.5 = 70 km/h.', source },
  { id: 'rrb-alp-cbt1-math2-012', section: 'Mathematics', topic: 'Simple and Compound Interest', difficulty: 'medium', question: 'Find the simple interest on ₹9,600 at 5% per annum for 4 years.', options: ['₹1,920', '₹1,860', '₹1,980', '₹1,900'], correctIndex: 0, explanation: 'SI = (P × R × T) / 100 = (9600 × 5 × 4) / 100 = ₹1,920.', source },
  { id: 'rrb-alp-cbt1-math2-013', section: 'Mathematics', topic: 'Profit and Loss', difficulty: 'medium', question: 'A shopkeeper buys an item for ₹450 and sells it for ₹549. Find the profit percentage.', options: ['20%', '24%', '18%', '22%'], correctIndex: 3, explanation: 'Profit = 549 − 450 = ₹99. Profit% = (99/450) × 100 = 22%.', source },
  { id: 'rrb-alp-cbt1-math2-014', section: 'Mathematics', topic: 'Algebra', difficulty: 'medium', question: 'If 6x − 9 = 27, find the value of x.', options: ['7', '8', '6', '5'], correctIndex: 2, explanation: '6x = 27 + 9 = 36, so x = 36/6 = 6.', source },
  { id: 'rrb-alp-cbt1-math2-015', section: 'Mathematics', topic: 'Geometry', difficulty: 'medium', question: 'In a triangle, two angles measure 42° and 68°. What is the third angle?', options: ['65°', '70°', '75°', '60°'], correctIndex: 1, explanation: 'Sum of angles in a triangle = 180°. Third angle = 180 − 42 − 68 = 70°.', source },
  { id: 'rrb-alp-cbt1-math2-016', section: 'Mathematics', topic: 'Elementary Statistics', difficulty: 'medium', question: 'Find the mean of the numbers 14, 20, 24, 28, 34.', options: ['24', '22', '26', '20'], correctIndex: 0, explanation: 'Mean = (14+20+24+28+34)/5 = 120/5 = 24.', source },
  { id: 'rrb-alp-cbt1-math2-017', section: 'Mathematics', topic: 'Square Root', difficulty: 'easy', question: 'What is the square root of 441?', options: ['22', '20', '23', '21'], correctIndex: 3, explanation: '21 × 21 = 441, so √441 = 21.', source },
  { id: 'rrb-alp-cbt1-math2-018', section: 'Mathematics', topic: 'Age Calculations', difficulty: 'medium', question: 'A father is 5 times as old as his son. After 4 years, the father will be 4 times as old as his son. Find the son\'s present age.', options: ['10 years', '14 years', '12 years', '8 years'], correctIndex: 2, explanation: 'Let son\'s present age be x, so father\'s age = 5x. After 4 years: 5x+4 = 4(x+4), giving 5x+4 = 4x+16, so x = 12 years.', source },
  { id: 'rrb-alp-cbt1-math2-019', section: 'Mathematics', topic: 'Calendar and Clock', difficulty: 'medium', question: 'If 1 January of a leap year was a Friday, what day of the week was 1 January of the following year?', options: ['Saturday', 'Sunday', 'Monday', 'Tuesday'], correctIndex: 1, explanation: 'A leap year has 366 days, which is 52 weeks and 2 extra days, so the day of the week advances by 2: Friday + 2 = Sunday.', source },
  { id: 'rrb-alp-cbt1-math2-020', section: 'Mathematics', topic: 'Pipes and Cisterns', difficulty: 'medium', question: 'Pipe A can fill a tank in 8 hours and Pipe B can empty it in 12 hours. If both are opened together, how long will it take to fill the tank?', options: ['20 hours', '28 hours', '30 hours', '24 hours'], correctIndex: 3, explanation: 'Combined rate = 1/8 − 1/12 = 3/24 − 2/24 = 1/24 per hour. Time to fill = 24 hours.', source },
];
