import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'RRB NTPC CEN 07/2025 official notification, CBT 1 syllabus — Mathematics section',
  url: 'https://www.rrbchennai.gov.in/downloads/CEN-07-2025-NTPC-UnderGraduate-English.pdf',
  checkedOn: '10 August 2026',
};

export const RRB_NTPC_CBT1_MATHEMATICS_1: Question[] = [
  {
    id: 'rrb-ntpc-cbt1-math-001',
    section: 'Mathematics',
    topic: 'Number system',
    difficulty: 'easy',
    question: 'What is the value of 7 × 8 − 6 × 5?',
    options: ['26', '24', '28', '30'],
    correctIndex: 0,
    explanation: '7 × 8 = 56 and 6 × 5 = 30, so 56 − 30 = 26.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-math-002',
    section: 'Mathematics',
    topic: 'Number system',
    difficulty: 'easy',
    question: 'Which of the following is a prime number?',
    options: ['51', '61', '57', '91'],
    correctIndex: 1,
    explanation: '51 = 3 × 17, 57 = 3 × 19, and 91 = 7 × 13, so all three are composite. 61 has no factors other than 1 and itself.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-math-003',
    section: 'Mathematics',
    topic: 'LCM and HCF',
    difficulty: 'easy',
    question: 'What is the LCM of 8 and 12?',
    options: ['16', '20', '24', '36'],
    correctIndex: 2,
    explanation: 'Multiples of 8: 8, 16, 24… Multiples of 12: 12, 24… The lowest common multiple is 24.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-math-004',
    section: 'Mathematics',
    topic: 'LCM and HCF',
    difficulty: 'medium',
    question: 'What is the HCF of 36, 60, and 84?',
    options: ['6', '18', '24', '12'],
    correctIndex: 3,
    explanation: '36 = 2² × 3², 60 = 2² × 3 × 5, 84 = 2² × 3 × 7. The common factors are 2² × 3 = 12.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-math-005',
    section: 'Mathematics',
    topic: 'Decimals and fractions',
    difficulty: 'easy',
    question: 'Simplify: 3/4 + 1/6',
    options: ['11/12', '5/6', '7/8', '13/12'],
    correctIndex: 0,
    explanation: 'The LCM of 4 and 6 is 12. 3/4 = 9/12 and 1/6 = 2/12, so the sum is 11/12.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-math-006',
    section: 'Mathematics',
    topic: 'Decimals and fractions',
    difficulty: 'medium',
    question: 'Arrange in ascending order: 0.65, 2/3, 0.7, 5/7',
    options: ['0.65, 0.7, 2/3, 5/7', '0.65, 2/3, 0.7, 5/7', '2/3, 0.65, 0.7, 5/7', '0.65, 2/3, 5/7, 0.7'],
    correctIndex: 1,
    explanation: 'As decimals: 0.65, 2/3 ≈ 0.667, 0.7, 5/7 ≈ 0.714. In ascending order: 0.65 < 2/3 < 0.7 < 5/7.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-math-007',
    section: 'Mathematics',
    topic: 'Ratio and proportion',
    difficulty: 'easy',
    question: 'Two numbers are in the ratio 4:7. If their sum is 143, what is the larger number?',
    options: ['77', '84', '91', '98'],
    correctIndex: 2,
    explanation: 'Total parts = 4 + 7 = 11. Each part = 143 ÷ 11 = 13. The larger number = 7 × 13 = 91.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-math-008',
    section: 'Mathematics',
    topic: 'Ratio and proportion',
    difficulty: 'medium',
    question: 'If a:b = 2:3 and b:c = 4:5, what is a:b:c?',
    options: ['2:3:5', '6:9:15', '8:15:12', '8:12:15'],
    correctIndex: 3,
    explanation: 'Scale a:b = 2:3 to 8:12 (×4) and b:c = 4:5 to 12:15 (×3) so both share b = 12. Combined, a:b:c = 8:12:15.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-math-009',
    section: 'Mathematics',
    topic: 'Percentage',
    difficulty: 'easy',
    question: '40% of a number is 68. What is the number?',
    options: ['170', '160', '180', '190'],
    correctIndex: 0,
    explanation: 'If 40% of the number is 68, the number = 68 ÷ 0.40 = 170.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-math-010',
    section: 'Mathematics',
    topic: 'Percentage',
    difficulty: 'medium',
    question: 'In an election with only two candidates, the winner got 55% of the votes and won by 4,000 votes. What was the total number of votes?',
    options: ['36,000', '40,000', '38,000', '42,000'],
    correctIndex: 1,
    explanation: 'The winning margin is 55% − 45% = 10% of the total. 10% of the total = 4,000, so the total = 40,000.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-math-011',
    section: 'Mathematics',
    topic: 'Mensuration',
    difficulty: 'easy',
    question: 'Find the area of a rectangle with length 15 cm and breadth 8 cm.',
    options: ['100 cm²', '110 cm²', '120 cm²', '130 cm²'],
    correctIndex: 2,
    explanation: 'Area of a rectangle = length × breadth = 15 × 8 = 120 cm².',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-math-012',
    section: 'Mathematics',
    topic: 'Mensuration',
    difficulty: 'medium',
    question: 'Find the area of a circle with radius 14 cm. (Use π = 22/7.)',
    options: ['588 cm²', '600 cm²', '628 cm²', '616 cm²'],
    correctIndex: 3,
    explanation: 'Area = πr² = (22/7) × 14 × 14 = 22 × 14 × 2 = 616 cm².',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-math-013',
    section: 'Mathematics',
    topic: 'Mensuration',
    difficulty: 'medium',
    question: 'The circumference of a circle is 88 cm. Find its radius. (Use π = 22/7.)',
    options: ['14 cm', '12 cm', '13 cm', '15 cm'],
    correctIndex: 0,
    explanation: 'Circumference = 2πr, so r = 88 ÷ (2 × 22/7) = 88 × 7 ÷ 44 = 14 cm.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-math-014',
    section: 'Mathematics',
    topic: 'Time and work',
    difficulty: 'medium',
    question: 'A can complete a piece of work in 12 days and B can complete it in 18 days. Working together, how many days will they take?',
    options: ['6.5 days', '7.2 days', '7 days', '7.5 days'],
    correctIndex: 1,
    explanation: 'Combined rate = 1/12 + 1/18 = 3/36 + 2/36 = 5/36 of the work per day, so the work takes 36/5 = 7.2 days.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-math-015',
    section: 'Mathematics',
    topic: 'Time and work',
    difficulty: 'hard',
    question: 'A alone can do a piece of work in 20 days. A and B together can finish it in 12 days. In how many days can B alone finish the work?',
    options: ['24 days', '28 days', '30 days', '32 days'],
    correctIndex: 2,
    explanation: "B's rate = 1/12 − 1/20 = 5/60 − 3/60 = 2/60 = 1/30, so B alone takes 30 days.",
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-math-016',
    section: 'Mathematics',
    topic: 'Time, speed and distance',
    difficulty: 'easy',
    question: 'A car travels 180 km in 3 hours. Find its speed.',
    options: ['50 km/h', '55 km/h', '65 km/h', '60 km/h'],
    correctIndex: 3,
    explanation: 'Speed = distance ÷ time = 180 ÷ 3 = 60 km/h.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-math-017',
    section: 'Mathematics',
    topic: 'Time, speed and distance',
    difficulty: 'medium',
    question: 'A train 150 m long crosses a pole in 15 seconds. Find its speed in km/h.',
    options: ['36 km/h', '30 km/h', '33 km/h', '40 km/h'],
    correctIndex: 0,
    explanation: 'Speed = 150 m ÷ 15 s = 10 m/s. Converting: 10 × 18/5 = 36 km/h.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-math-018',
    section: 'Mathematics',
    topic: 'Time, speed and distance',
    difficulty: 'hard',
    question: 'Two trains, 120 m and 180 m long, run in opposite directions on parallel tracks at 54 km/h and 36 km/h. Find the time they take to cross each other.',
    options: ['10 seconds', '12 seconds', '14 seconds', '16 seconds'],
    correctIndex: 1,
    explanation: 'Relative speed (opposite directions) = 54 + 36 = 90 km/h = 25 m/s. Total length = 120 + 180 = 300 m. Time = 300 ÷ 25 = 12 seconds.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-math-019',
    section: 'Mathematics',
    topic: 'Simple and compound interest',
    difficulty: 'easy',
    question: 'Find the simple interest on ₹6,000 at 5% per annum for 3 years.',
    options: ['₹800', '₹850', '₹900', '₹950'],
    correctIndex: 2,
    explanation: 'SI = (P × R × T) ÷ 100 = (6000 × 5 × 3) ÷ 100 = ₹900.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-math-020',
    section: 'Mathematics',
    topic: 'Simple and compound interest',
    difficulty: 'medium',
    question: 'Find the compound interest on ₹8,000 at 10% per annum for 2 years, compounded annually.',
    options: ['₹1,600', '₹1,700', '₹1,720', '₹1,680'],
    correctIndex: 3,
    explanation: 'Amount = 8000 × (1.1)² = 8000 × 1.21 = ₹9,680. Compound interest = 9680 − 8000 = ₹1,680.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-math-021',
    section: 'Mathematics',
    topic: 'Profit and loss',
    difficulty: 'easy',
    question: 'A shopkeeper buys an item for ₹450 and sells it for ₹540. Find the profit percentage.',
    options: ['20%', '15%', '18%', '22%'],
    correctIndex: 0,
    explanation: 'Profit = 540 − 450 = ₹90. Profit % = (90 ÷ 450) × 100 = 20%.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-math-022',
    section: 'Mathematics',
    topic: 'Profit and loss',
    difficulty: 'medium',
    question: 'By selling an article for ₹440, a man loses 12%. What is the cost price?',
    options: ['₹480', '₹500', '₹490', '₹510'],
    correctIndex: 1,
    explanation: 'Selling price is 88% of the cost price (100% − 12% loss). Cost price = 440 ÷ 0.88 = ₹500.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-math-023',
    section: 'Mathematics',
    topic: 'Elementary algebra',
    difficulty: 'medium',
    question: 'If x + 1/x = 5, find the value of x² + 1/x².',
    options: ['21', '22', '23', '24'],
    correctIndex: 2,
    explanation: '(x + 1/x)² = x² + 2 + 1/x², so x² + 1/x² = 5² − 2 = 23.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-math-024',
    section: 'Mathematics',
    topic: 'Elementary algebra',
    difficulty: 'easy',
    question: 'Solve for x: 3x − 7 = 2x + 5',
    options: ['10', '11', '13', '12'],
    correctIndex: 3,
    explanation: '3x − 2x = 5 + 7, so x = 12.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-math-025',
    section: 'Mathematics',
    topic: 'Elementary algebra',
    difficulty: 'medium',
    question: 'If a² + b² = 34 and ab = 15, find the value of (a + b)².',
    options: ['64', '54', '60', '68'],
    correctIndex: 0,
    explanation: '(a + b)² = a² + b² + 2ab = 34 + 2(15) = 34 + 30 = 64.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-math-026',
    section: 'Mathematics',
    topic: 'Geometry',
    difficulty: 'easy',
    question: 'What is the sum of the interior angles of a hexagon?',
    options: ['540°', '720°', '630°', '900°'],
    correctIndex: 1,
    explanation: 'Sum of interior angles = (n − 2) × 180°. For a hexagon, n = 6, so (6 − 2) × 180° = 720°.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-math-027',
    section: 'Mathematics',
    topic: 'Geometry',
    difficulty: 'medium',
    question: 'In a right triangle, the two legs are 9 cm and 12 cm. Find the hypotenuse.',
    options: ['13 cm', '14 cm', '15 cm', '16 cm'],
    correctIndex: 2,
    explanation: 'By the Pythagorean theorem, hypotenuse = √(9² + 12²) = √(81 + 144) = √225 = 15 cm.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-math-028',
    section: 'Mathematics',
    topic: 'Trigonometry',
    difficulty: 'easy',
    question: 'What is the value of sin 30° + cos 60°?',
    options: ['0.5', '1.5', '2', '1'],
    correctIndex: 3,
    explanation: 'sin 30° = 0.5 and cos 60° = 0.5, so their sum is 1.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-math-029',
    section: 'Mathematics',
    topic: 'Trigonometry',
    difficulty: 'medium',
    question: 'If tan θ = 3/4 and θ is acute, find the value of sin θ.',
    options: ['0.6', '0.5', '0.7', '0.75'],
    correctIndex: 0,
    explanation: 'A 3-4-5 right triangle gives tan θ = 3/4. Since the hypotenuse is 5, sin θ = opposite/hypotenuse = 3/5 = 0.6.',
    source,
  },
  {
    id: 'rrb-ntpc-cbt1-math-030',
    section: 'Mathematics',
    topic: 'Elementary statistics',
    difficulty: 'medium',
    question: 'Find the mean of the first 10 natural numbers.',
    options: ['5', '5.5', '6', '6.5'],
    correctIndex: 1,
    explanation: 'Sum of the first 10 natural numbers = 55. Mean = 55 ÷ 10 = 5.5.',
    source,
  },
];
