import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'RRB Paramedical Categories CEN 03/2025 official notification, CBT syllabus: General Awareness',
  url: 'https://rrbsecunderabad.gov.in/wp-content/uploads/2025/08/Final-CEN-03_2025-English.pdf',
  checkedOn: '7 August 2026',
};

export const RRB_PARAMEDICAL_GENERAL_AWARENESS_1: Question[] = [
  { id: 'rrb-pmed-ga-001', section: 'General Awareness', topic: 'Indian Polity', difficulty: 'medium', question: 'Which part of the Indian Constitution deals with the Directive Principles of State Policy?', options: ['Part III', 'Part V', 'Part IV', 'Part VI'], correctIndex: 2, explanation: 'Part IV of the Indian Constitution (Articles 36 to 51) contains the Directive Principles of State Policy.', source },
  { id: 'rrb-pmed-ga-002', section: 'General Awareness', topic: 'Indian Geography', difficulty: 'easy', question: 'Rajasthan, the largest Indian state by geographical area, shares an international border with which country?', options: ['Nepal', 'Bangladesh', 'Pakistan', 'Bhutan'], correctIndex: 2, explanation: 'Rajasthan, the largest Indian state by area, shares its western international border with Pakistan.', source },
  { id: 'rrb-pmed-ga-003', section: 'General Awareness', topic: 'Culture', difficulty: 'easy', question: 'Odissi is a classical dance form that originated in which Indian state?', options: ['Odisha', 'West Bengal', 'Bihar', 'Jharkhand'], correctIndex: 0, explanation: 'Odissi is a classical dance form that originated in the state of Odisha.', source },
  { id: 'rrb-pmed-ga-004', section: 'General Awareness', topic: 'Freedom Struggle', difficulty: 'medium', question: 'The Non-Cooperation Movement, launched by Mahatma Gandhi, began in which year?', options: ['1919', '1922', '1920', '1930'], correctIndex: 2, explanation: 'The Non-Cooperation Movement was launched by Mahatma Gandhi in 1920.', source },
  { id: 'rrb-pmed-ga-005', section: 'General Awareness', topic: 'Indian Economy', difficulty: 'medium', question: 'Which institution is responsible for regulating monetary policy in India?', options: ['SEBI', 'NITI Aayog', 'Finance Ministry', 'Reserve Bank of India'], correctIndex: 3, explanation: 'The Reserve Bank of India is responsible for formulating and regulating monetary policy in India.', source },
  { id: 'rrb-pmed-ga-006', section: 'General Awareness', topic: 'Environmental Issues', difficulty: 'medium', question: 'The Paris Agreement is an international treaty primarily aimed at addressing what?', options: ['Trade tariffs', 'Nuclear disarmament', 'Refugee resettlement', 'Climate change and global warming'], correctIndex: 3, explanation: 'The Paris Agreement is an international treaty focused on limiting global warming and addressing climate change.', source },
  { id: 'rrb-pmed-ga-007', section: 'General Awareness', topic: 'Sports', difficulty: 'easy', question: 'Which country has won the Davis Cup (men\'s tennis) the most times in history?', options: ['France', 'United States', 'Australia', 'United Kingdom'], correctIndex: 1, explanation: 'The United States has won the Davis Cup, the premier international team competition in men\'s tennis, more times than any other nation.', source },
  { id: 'rrb-pmed-ga-008', section: 'General Awareness', topic: 'Science and Technology', difficulty: 'medium', question: 'Which Indian agency is primarily responsible for the country\'s defence research and development?', options: ['ISRO', 'DRDO', 'BARC', 'CSIR'], correctIndex: 1, explanation: 'The Defence Research and Development Organisation (DRDO) is India\'s primary agency for defence research and development.', source },
  { id: 'rrb-pmed-ga-009', section: 'General Awareness', topic: 'Current Affairs', difficulty: 'medium', question: 'The "Ayushman Bharat" scheme primarily aims to provide what to eligible Indian citizens?', options: ['Free higher education', 'Health insurance coverage for hospitalization', 'Subsidized housing loans', 'Free public transport'], correctIndex: 1, explanation: 'Ayushman Bharat is a national health protection scheme that provides health insurance coverage for hospitalization to eligible economically vulnerable citizens.', source },
  { id: 'rrb-pmed-ga-010', section: 'General Awareness', topic: 'History', difficulty: 'medium', question: 'The Battle of Plassey, which established British influence in Bengal, was fought in which year?', options: ['1757', '1764', '1857', '1761'], correctIndex: 0, explanation: 'The Battle of Plassey was fought in 1757 between the British East India Company and the Nawab of Bengal.', source },
];
