import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'RRB Paramedical Categories CEN 03/2025 official notification, CBT syllabus: General Science (up to 10th standard CBSE). Second set, built to the same difficulty mix as the first.',
  url: 'https://rrbsecunderabad.gov.in/wp-content/uploads/2025/08/Final-CEN-03_2025-English.pdf',
  checkedOn: '18 September 2026',
};

export const RRB_PARAMEDICAL_GENERAL_SCIENCE_2: Question[] = [
  { id: 'rrb-paramedical-gs-02-001', section: 'General Science', topic: 'Physics', difficulty: 'easy', question: 'What is the SI unit of force?', options: ['Joule', 'Newton', 'Pascal', 'Watt'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Force is measured in newtons. The joule measures energy, the pascal pressure, and the watt power.', source },
  { id: 'rrb-paramedical-gs-02-002', section: 'General Science', topic: 'Physics', difficulty: 'medium', question: 'Which type of lens is used to correct myopia, or short-sightedness?', options: ['Convex lens', 'Cylindrical lens', 'Concave lens', 'Bifocal lens'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'A short-sighted eye brings distant images to a focus in front of the retina, so a diverging concave lens is used to push the focus back. A convex lens corrects long-sightedness and a cylindrical lens corrects astigmatism.', source },
  { id: 'rrb-paramedical-gs-02-003', section: 'General Science', topic: 'Chemistry', difficulty: 'easy', question: 'What is the chemical formula of common salt?', options: ['CaCO3', 'KCl', 'NaHCO3', 'NaCl'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Common salt is sodium chloride, NaCl. NaHCO3 is baking soda, CaCO3 is limestone, and KCl is potassium chloride.', source },
  { id: 'rrb-paramedical-gs-02-004', section: 'General Science', topic: 'Chemistry', difficulty: 'medium', question: 'Which acid is secreted by the glands of the human stomach?', options: ['Hydrochloric acid', 'Sulphuric acid', 'Nitric acid', 'Acetic acid'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The gastric glands secrete hydrochloric acid, which makes the stomach contents acidic enough for pepsin to work and kills many swallowed microbes.', source },
  { id: 'rrb-paramedical-gs-02-005', section: 'General Science', topic: 'Life Sciences', difficulty: 'easy', question: 'Which is the largest organ of the human body?', options: ['Liver', 'Skin', 'Lungs', 'Brain'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The skin is the largest organ by both surface area and weight. The liver is the largest internal organ.', source },
  { id: 'rrb-paramedical-gs-02-006', section: 'General Science', topic: 'Life Sciences', difficulty: 'medium', question: 'Deficiency of which vitamin causes scurvy?', options: ['Vitamin A', 'Vitamin B12', 'Vitamin C', 'Vitamin D'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Scurvy follows a lack of vitamin C, which the body needs to build collagen. Lack of vitamin A affects vision, of B12 causes anaemia, and of D causes rickets.', source },
  { id: 'rrb-paramedical-gs-02-007', section: 'General Science', topic: 'Life Sciences', difficulty: 'medium', question: 'What is the structural and functional unit of the kidney called?', options: ['Alveolus', 'Neuron', 'Hepatocyte', 'Nephron'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The kidney filters blood through about a million nephrons. The alveolus is the unit of gas exchange in the lung, the neuron of the nervous system, and the hepatocyte of the liver.', source },
  { id: 'rrb-paramedical-gs-02-008', section: 'General Science', topic: 'Life Sciences', difficulty: 'medium', question: 'What does an electrocardiogram record?', options: ['The electrical activity of the heart', 'The rate of blood flow through the arteries', 'The oxygen saturation of the blood', 'The pressure inside the heart chambers'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'An electrocardiogram traces the electrical signals that drive each heartbeat. Oxygen saturation is read by a pulse oximeter, and chamber pressures are measured by catheterisation.', source },
  { id: 'rrb-paramedical-gs-02-009', section: 'General Science', topic: 'Chemistry', difficulty: 'medium', question: 'Baking soda is the common name of which compound?', options: ['Sodium carbonate', 'Sodium bicarbonate', 'Sodium chloride', 'Sodium hydroxide'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Baking soda is sodium bicarbonate, NaHCO3. Sodium carbonate is washing soda, and sodium hydroxide is caustic soda.', source },
  { id: 'rrb-paramedical-gs-02-010', section: 'General Science', topic: 'Life Sciences', difficulty: 'medium', question: 'How many chambers does the human heart have?', options: ['Two', 'Three', 'Four', 'Six'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The human heart has four chambers: two atria that receive blood and two ventricles that pump it out.', source },
];
