import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'RRB Assistant Loco Pilot CEN 01/2025 official notification, First Stage CBT syllabus: General Science (10th standard level)',
  url: 'https://rrbbilaspur.gov.in/file/notice/Revised_CEN_01-2025_ALP.pdf',
  checkedOn: '7 August 2026',
};

export const RRB_ALP_CBT1_GENERAL_SCIENCE_1: Question[] = [
  { id: 'rrb-alp-cbt1-gs-001', section: 'General Science', topic: 'Physics', difficulty: 'easy', question: 'The ampere (A) is the SI unit for measuring which electrical quantity?', options: ['Electric current', 'Voltage', 'Resistance', 'Power'], correctIndex: 0, explanation: 'The ampere is the SI unit of electric current, named after André-Marie Ampère.', source },
  { id: 'rrb-alp-cbt1-gs-002', section: 'General Science', topic: 'Physics', difficulty: 'easy', question: 'Which of the following is a good conductor of electricity?', options: ['Copper', 'Rubber', 'Glass', 'Wood'], correctIndex: 0, explanation: 'Copper is a metal with free electrons that move easily, making it a good conductor of electricity, unlike rubber, glass, and wood, which are insulators.', source },
  { id: 'rrb-alp-cbt1-gs-003', section: 'General Science', topic: 'Physics', difficulty: 'medium', question: 'The force that opposes relative motion between two surfaces in contact is called what?', options: ['Friction', 'Gravity', 'Tension', 'Buoyancy'], correctIndex: 0, explanation: 'Friction is the force that resists the relative motion of two surfaces in contact.', source },
  { id: 'rrb-alp-cbt1-gs-004', section: 'General Science', topic: 'Physics', difficulty: 'medium', question: 'What is the unit of power in the SI system?', options: ['Joule', 'Newton', 'Watt', 'Pascal'], correctIndex: 2, explanation: 'The SI unit of power is the watt (W), which equals one joule of energy transferred per second.', source },
  { id: 'rrb-alp-cbt1-gs-005', section: 'General Science', topic: 'Physics', difficulty: 'medium', question: "Which law states that for every action there is an equal and opposite reaction?", options: ["Newton's First Law", "Newton's Second Law", "Newton's Third Law", "Law of Conservation of Energy"], correctIndex: 2, explanation: "Newton's Third Law of Motion states that for every action there is an equal and opposite reaction.", source },
  { id: 'rrb-alp-cbt1-gs-006', section: 'General Science', topic: 'Physics', difficulty: 'medium', question: 'What type of mirror is used as a rear-view mirror in vehicles?', options: ['Convex mirror', 'Concave mirror', 'Plane mirror', 'Parabolic mirror'], correctIndex: 0, explanation: 'A convex mirror gives a wider field of view and always produces an upright, diminished image, which is why it is used as a rear-view mirror.', source },
  { id: 'rrb-alp-cbt1-gs-007', section: 'General Science', topic: 'Chemistry', difficulty: 'easy', question: 'The symbol "Na" on the periodic table represents which element?', options: ['Nitrogen', 'Neon', 'Nickel', 'Sodium'], correctIndex: 3, explanation: 'Na is the chemical symbol for sodium, derived from its Latin name "natrium".', source },
  { id: 'rrb-alp-cbt1-gs-008', section: 'General Science', topic: 'Chemistry', difficulty: 'easy', question: 'Nitrogen makes up roughly what percentage of the Earth\'s atmosphere by volume?', options: ['21%', '48%', '78%', '95%'], correctIndex: 2, explanation: 'Nitrogen makes up about 78% of the Earth\'s atmosphere by volume, making it the most abundant atmospheric gas.', source },
  { id: 'rrb-alp-cbt1-gs-009', section: 'General Science', topic: 'Chemistry', difficulty: 'medium', question: 'What is the pH value of a neutral solution?', options: ['0', '10', '14', '7'], correctIndex: 3, explanation: 'A pH value of 7 indicates a neutral solution, neither acidic nor basic, as in pure water.', source },
  { id: 'rrb-alp-cbt1-gs-010', section: 'General Science', topic: 'Chemistry', difficulty: 'medium', question: 'Rust forms on iron due to which process?', options: ['Reduction', 'Sublimation', 'Distillation', 'Oxidation'], correctIndex: 3, explanation: 'Rust (iron oxide) forms when iron reacts with oxygen and moisture in the air, a process called oxidation.', source },
  { id: 'rrb-alp-cbt1-gs-011', section: 'General Science', topic: 'Chemistry', difficulty: 'medium', question: 'Which of the following is an example of a chemical change?', options: ['Melting of ice', 'Boiling of water', 'Dissolving sugar in water', 'Burning of paper'], correctIndex: 3, explanation: 'Burning paper produces new substances (ash, gases) and cannot be reversed, making it a chemical change, unlike melting, boiling, or dissolving, which are physical changes.', source },
  { id: 'rrb-alp-cbt1-gs-012', section: 'General Science', topic: 'Life Sciences', difficulty: 'easy', question: 'Which organ in the human body is primarily responsible for pumping blood?', options: ['Liver', 'Kidney', 'Heart', 'Lungs'], correctIndex: 2, explanation: 'The heart is a muscular organ that pumps blood throughout the human body via the circulatory system.', source },
  { id: 'rrb-alp-cbt1-gs-013', section: 'General Science', topic: 'Life Sciences', difficulty: 'easy', question: 'During photosynthesis, plants take in carbon dioxide from the air and release which gas?', options: ['Nitrogen', 'Hydrogen', 'Methane', 'Oxygen'], correctIndex: 3, explanation: 'Plants absorb carbon dioxide during photosynthesis and release oxygen as a byproduct.', source },
  { id: 'rrb-alp-cbt1-gs-014', section: 'General Science', topic: 'Life Sciences', difficulty: 'medium', question: 'Why is O negative blood referred to as the universal donor type?', options: ['It has the highest red blood cell count', 'It lacks the A, B, and Rh antigens, so it is compatible with most recipients', 'It clots faster than other blood types', 'It is the most common blood type worldwide'], correctIndex: 1, explanation: 'O negative blood lacks the A, B, and Rh antigens, so it can typically be given to patients of any blood group, making it the universal donor type.', source },
  { id: 'rrb-alp-cbt1-gs-015', section: 'General Science', topic: 'Life Sciences', difficulty: 'medium', question: 'Which part of the human body is primarily responsible for filtering blood and producing urine?', options: ['Liver', 'Kidney', 'Pancreas', 'Spleen'], correctIndex: 1, explanation: 'The kidneys filter waste products from the blood and produce urine as part of the excretory system.', source },
  { id: 'rrb-alp-cbt1-gs-016', section: 'General Science', topic: 'Life Sciences', difficulty: 'medium', question: 'Which vitamin deficiency commonly causes night blindness?', options: ['Vitamin A', 'Vitamin B12', 'Vitamin C', 'Vitamin D'], correctIndex: 0, explanation: 'A deficiency of Vitamin A impairs the eye\'s ability to adapt to low light, commonly causing night blindness.', source },
  { id: 'rrb-alp-cbt1-gs-017', section: 'General Science', topic: 'Physics', difficulty: 'medium', question: 'What is the process called when a liquid changes directly into a gas at any temperature?', options: ['Boiling', 'Evaporation', 'Condensation', 'Freezing'], correctIndex: 1, explanation: 'Evaporation is the process by which a liquid changes into a gas at any temperature, occurring at the surface of the liquid.', source },
  { id: 'rrb-alp-cbt1-gs-018', section: 'General Science', topic: 'Chemistry', difficulty: 'medium', question: 'Which of the following is used as a fuel in most diesel locomotives?', options: ['Petrol', 'Diesel oil', 'Kerosene', 'Compressed Natural Gas'], correctIndex: 1, explanation: 'Diesel locomotives are powered by diesel oil, which is burned in a diesel engine to generate mechanical power.', source },
  { id: 'rrb-alp-cbt1-gs-019', section: 'General Science', topic: 'Physics', difficulty: 'medium', question: 'What is the term for the resistance of a body to change its state of rest or motion?', options: ['Momentum', 'Inertia', 'Velocity', 'Acceleration'], correctIndex: 1, explanation: 'Inertia is the property of a body to resist any change in its state of rest or uniform motion.', source },
  { id: 'rrb-alp-cbt1-gs-020', section: 'General Science', topic: 'Life Sciences', difficulty: 'medium', question: 'Photosynthesis in plants primarily takes place in which part of the cell?', options: ['Mitochondria', 'Nucleus', 'Chloroplast', 'Ribosome'], correctIndex: 2, explanation: 'Chloroplasts contain chlorophyll, the pigment that captures light energy for photosynthesis, making them the site of this process.', source },
];
