import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'RRB Technician CEN 02/2025 official notification, CBT syllabus for Grade I Signal: General Awareness',
  url: 'https://rrbajmer.gov.in/Upload_PDF/Detailed%20CEN%202-2025_%20Technician%20Categories-638866538197092718.pdf',
  checkedOn: '7 August 2026',
};

export const RRB_TECHNICIAN_GRADE1_SIGNAL_GENERAL_AWARENESS_1: Question[] = [
  { id: 'rrb-tech-g1-ga-001', section: 'General Awareness', topic: 'Indian Geography', difficulty: 'easy', question: 'Which is the longest river entirely within India?', options: ['Ganga', 'Godavari', 'Yamuna', 'Narmada'], correctIndex: 0, explanation: 'The Ganga is the longest river flowing entirely within Indian territory.', source },
  { id: 'rrb-tech-g1-ga-002', section: 'General Awareness', topic: 'Indian Polity', difficulty: 'medium', question: 'How many fundamental duties are listed in the Indian Constitution?', options: ['9', '10', '11', '12'], correctIndex: 2, explanation: 'The Indian Constitution originally listed 10 fundamental duties under Article 51A; the 86th Amendment added an 11th, bringing the total to 11.', source },
  { id: 'rrb-tech-g1-ga-003', section: 'General Awareness', topic: 'Indian History', difficulty: 'medium', question: 'On which date was the Quit India Movement launched by Mahatma Gandhi?', options: ['26 January 1942', '15 August 1942', '8 August 1942', '2 October 1942'], correctIndex: 2, explanation: 'The Quit India Movement was launched by Mahatma Gandhi on 8 August 1942.', source },
  { id: 'rrb-tech-g1-ga-004', section: 'General Awareness', topic: 'Indian Economy', difficulty: 'medium', question: 'Which committee recommended the establishment of the Insolvency and Bankruptcy Code in India?', options: ['Bimal Jalan Committee', 'Y.V. Reddy Committee', 'T.K. Vishwanathan Committee', 'Raghuram Rajan Committee'], correctIndex: 2, explanation: 'The T.K. Vishwanathan Committee (Bankruptcy Law Reforms Committee) recommended the framework that became the Insolvency and Bankruptcy Code, 2016.', source },
  { id: 'rrb-tech-g1-ga-005', section: 'General Awareness', topic: 'Environmental Issues', difficulty: 'medium', question: 'The Montreal Protocol is an international agreement aimed at protecting what?', options: ['Ocean biodiversity', 'Tropical rainforests', 'Freshwater resources', 'The ozone layer'], correctIndex: 3, explanation: 'The Montreal Protocol is an international treaty designed to phase out substances that deplete the ozone layer.', source },
  { id: 'rrb-tech-g1-ga-006', section: 'General Awareness', topic: 'Sports', difficulty: 'easy', question: 'In badminton, how many points are needed to win a standard game?', options: ['15', '25', '30', '21'], correctIndex: 3, explanation: 'A standard badminton game is won by the first player or pair to reach 21 points (with a 2-point clear margin, subject to a cap).', source },
  { id: 'rrb-tech-g1-ga-007', section: 'General Awareness', topic: 'Science and Technology', difficulty: 'medium', question: 'Which Indian mission successfully achieved a soft landing near the lunar south pole in 2023?', options: ['Chandrayaan-2', 'Chandrayaan-3', 'Mangalyaan', 'Aditya-L1'], correctIndex: 1, explanation: 'Chandrayaan-3 achieved a successful soft landing near the lunar south pole in August 2023, making India the first country to do so.', source },
  { id: 'rrb-tech-g1-ga-008', section: 'General Awareness', topic: 'Culture', difficulty: 'medium', question: 'Kathakali is a classical dance-drama form that originated in which Indian state?', options: ['Kerala', 'Karnataka', 'Tamil Nadu', 'Andhra Pradesh'], correctIndex: 0, explanation: 'Kathakali is a classical dance-drama form that originated in the state of Kerala.', source },
  { id: 'rrb-tech-g1-ga-009', section: 'General Awareness', topic: 'Freedom Struggle', difficulty: 'medium', question: 'Who founded the Indian National Army (Azad Hind Fauj) in its reorganized form during World War II?', options: ['Bhagat Singh', 'Subhas Chandra Bose', 'Chandrashekhar Azad', 'Lala Lajpat Rai'], correctIndex: 1, explanation: 'Subhas Chandra Bose reorganized and led the Indian National Army (Azad Hind Fauj) during World War II.', source },
  { id: 'rrb-tech-g1-ga-010', section: 'General Awareness', topic: 'Current Affairs', difficulty: 'medium', question: 'India\'s "Digital India" initiative primarily aims to achieve what?', options: ['Privatize state-run banks', 'Transform India into a digitally empowered society and knowledge economy', 'Replace paper currency entirely', 'Build new international airports'], correctIndex: 1, explanation: 'Digital India is a flagship programme aimed at transforming India into a digitally empowered society and knowledge economy through improved digital infrastructure and services.', source },
];
