import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'RRB Group D CEN 09/2025 official notification, CBT syllabus — General Science section',
  url: 'https://www.rrbcdg.gov.in/uploads/2025/09-LVL1/092025-CEN.pdf',
  checkedOn: '4 August 2026',
};

export const RRB_GROUP_D_CBT_GENERAL_SCIENCE_1: Question[] = [
  { id: 'rrb-gd-cbt-gs-001', section: 'General Science', topic: 'Physics', difficulty: 'easy', question: 'What is the SI unit of electric current?', options: ['Ampere', 'Volt', 'Ohm', 'Watt'], correctIndex: 0, explanation: 'The ampere is the SI base unit of electric current.', source },
  { id: 'rrb-gd-cbt-gs-002', section: 'General Science', topic: 'Physics', difficulty: 'easy', question: 'What is the SI unit of frequency?', options: ['Joule', 'Hertz', 'Pascal', 'Newton'], correctIndex: 1, explanation: 'The hertz is the SI unit of frequency, representing one cycle per second.', source },
  { id: 'rrb-gd-cbt-gs-003', section: 'General Science', topic: 'Physics', difficulty: 'easy', question: 'What is the SI unit of energy?', options: ['Watt', 'Newton', 'Joule', 'Pascal'], correctIndex: 2, explanation: 'The joule is the SI unit of energy and work.', source },
  { id: 'rrb-gd-cbt-gs-004', section: 'General Science', topic: 'Physics', difficulty: 'medium', question: 'What is the SI unit of pressure?', options: ['Newton', 'Joule', 'Watt', 'Pascal'], correctIndex: 3, explanation: 'The pascal is the SI unit of pressure, defined as one newton per square metre.', source },
  { id: 'rrb-gd-cbt-gs-005', section: 'General Science', topic: 'Physics', difficulty: 'easy', question: 'At what temperature does water freeze under standard atmospheric pressure?', options: ['0°C', '4°C', '10°C', '−1°C'], correctIndex: 0, explanation: 'Water freezes at 0°C under standard atmospheric pressure.', source },
  { id: 'rrb-gd-cbt-gs-006', section: 'General Science', topic: 'Physics', difficulty: 'easy', question: 'At what temperature does water boil under standard atmospheric pressure?', options: ['90°C', '100°C', '110°C', '120°C'], correctIndex: 1, explanation: 'Water boils at 100°C under standard atmospheric pressure.', source },
  { id: 'rrb-gd-cbt-gs-007', section: 'General Science', topic: 'Physics', difficulty: 'medium', question: 'Sound travels fastest through which of the following media?', options: ['Gas', 'Liquid', 'Solid', 'Vacuum'], correctIndex: 2, explanation: 'Sound travels fastest through solids, where molecules are packed most closely together.', source },
  { id: 'rrb-gd-cbt-gs-008', section: 'General Science', topic: 'Physics', difficulty: 'medium', question: "Newton's First Law of Motion is also known as the Law of:", options: ['Motion', 'Action-Reaction', 'Gravitation', 'Inertia'], correctIndex: 3, explanation: "Newton's First Law, which states that an object remains at rest or in uniform motion unless acted upon by an external force, is also called the Law of Inertia.", source },
  { id: 'rrb-gd-cbt-gs-009', section: 'General Science', topic: 'Chemistry', difficulty: 'easy', question: 'What is the chemical symbol for potassium?', options: ['K', 'P', 'Pt', 'Po'], correctIndex: 0, explanation: 'Potassium\'s chemical symbol, K, comes from its Latin name "kalium".', source },
  { id: 'rrb-gd-cbt-gs-010', section: 'General Science', topic: 'Chemistry', difficulty: 'easy', question: 'What is the chemical formula of carbon dioxide?', options: ['CO', 'CO2', 'C2O', 'COO'], correctIndex: 1, explanation: 'Carbon dioxide is chemically represented as CO2, one carbon atom bonded to two oxygen atoms.', source },
  { id: 'rrb-gd-cbt-gs-011', section: 'General Science', topic: 'Chemistry', difficulty: 'medium', question: 'The rusting of iron is an example of which type of chemical reaction?', options: ['Reduction', 'Neutralisation', 'Oxidation', 'Sublimation'], correctIndex: 2, explanation: 'Rusting occurs when iron reacts with oxygen and moisture, making it an oxidation reaction.', source },
  { id: 'rrb-gd-cbt-gs-012', section: 'General Science', topic: 'Chemistry', difficulty: 'easy', question: 'Which is the hardest naturally occurring substance?', options: ['Quartz', 'Topaz', 'Corundum', 'Diamond'], correctIndex: 3, explanation: 'Diamond is the hardest naturally occurring substance, rated 10 on the Mohs hardness scale.', source },
  { id: 'rrb-gd-cbt-gs-013', section: 'General Science', topic: 'Chemistry', difficulty: 'medium', question: 'Which of the following is a noble gas?', options: ['Helium', 'Nitrogen', 'Oxygen', 'Chlorine'], correctIndex: 0, explanation: 'Helium is a noble gas, belonging to Group 18 of the periodic table.', source },
  { id: 'rrb-gd-cbt-gs-014', section: 'General Science', topic: 'Chemistry', difficulty: 'medium', question: 'Baking soda is chemically known as:', options: ['Sodium carbonate', 'Sodium bicarbonate', 'Sodium chloride', 'Sodium hydroxide'], correctIndex: 1, explanation: 'Baking soda is chemically sodium bicarbonate (NaHCO3).', source },
  { id: 'rrb-gd-cbt-gs-015', section: 'General Science', topic: 'Biology', difficulty: 'medium', question: 'Which blood group is known as the universal donor?', options: ['AB positive', 'A negative', 'O negative', 'B positive'], correctIndex: 2, explanation: 'O negative blood lacks A, B, and Rh antigens, allowing it to be safely given to recipients of most other blood types.', source },
  { id: 'rrb-gd-cbt-gs-016', section: 'General Science', topic: 'Biology', difficulty: 'medium', question: 'Which is the largest gland in the human body?', options: ['Kidney', 'Pancreas', 'Spleen', 'Liver'], correctIndex: 3, explanation: 'The liver is the largest gland in the human body.', source },
  { id: 'rrb-gd-cbt-gs-017', section: 'General Science', topic: 'Biology', difficulty: 'easy', question: 'What is the approximate normal body temperature of a healthy human?', options: ['37°C', '35°C', '39°C', '40°C'], correctIndex: 0, explanation: 'The normal human body temperature is approximately 37°C (98.6°F).', source },
  { id: 'rrb-gd-cbt-gs-018', section: 'General Science', topic: 'Biology', difficulty: 'medium', question: 'Photosynthesis in plants releases which gas as a byproduct?', options: ['Carbon dioxide', 'Oxygen', 'Nitrogen', 'Hydrogen'], correctIndex: 1, explanation: 'Photosynthesis releases oxygen as a byproduct while converting carbon dioxide and water into glucose.', source },
  { id: 'rrb-gd-cbt-gs-019', section: 'General Science', topic: 'Biology', difficulty: 'easy', question: 'What does DNA stand for?', options: ['Diribonucleic acid', 'Dioxyribose nucleic acid', 'Deoxyribonucleic acid', 'Denatured ribonucleic acid'], correctIndex: 2, explanation: 'DNA stands for Deoxyribonucleic acid, the molecule that carries genetic information.', source },
  { id: 'rrb-gd-cbt-gs-020', section: 'General Science', topic: 'Biology', difficulty: 'easy', question: 'How many teeth does a normal adult human typically have?', options: ['28', '30', '34', '32'], correctIndex: 3, explanation: 'A normal adult human typically has 32 teeth, including the wisdom teeth.', source },
  { id: 'rrb-gd-cbt-gs-021', section: 'General Science', topic: 'Biology', difficulty: 'medium', question: 'Which vitamin plays a key role in blood clotting?', options: ['Vitamin K', 'Vitamin A', 'Vitamin C', 'Vitamin D'], correctIndex: 0, explanation: 'Vitamin K is essential for the production of proteins involved in blood clotting.', source },
  { id: 'rrb-gd-cbt-gs-022', section: 'General Science', topic: 'Biology', difficulty: 'medium', question: 'What is the smallest bone in the human body?', options: ['Femur', 'Stapes', 'Radius', 'Tibia'], correctIndex: 1, explanation: 'The stapes, located in the middle ear, is the smallest bone in the human body.', source },
  { id: 'rrb-gd-cbt-gs-023', section: 'General Science', topic: 'Biology', difficulty: 'easy', question: 'Which organ produces bile?', options: ['Kidney', 'Pancreas', 'Liver', 'Spleen'], correctIndex: 2, explanation: 'The liver produces bile, which is stored in the gallbladder and aids digestion of fats.', source },
  { id: 'rrb-gd-cbt-gs-024', section: 'General Science', topic: 'Biology', difficulty: 'medium', question: 'Red blood cells are mainly produced in which part of the body?', options: ['Spleen', 'Liver', 'Lymph nodes', 'Bone marrow'], correctIndex: 3, explanation: 'Red blood cells are mainly produced in the bone marrow.', source },
  { id: 'rrb-gd-cbt-gs-025', section: 'General Science', topic: 'Physics', difficulty: 'easy', question: 'A see-saw is a classic example of which simple machine?', options: ['Lever', 'Pulley', 'Wheel and axle', 'Inclined plane'], correctIndex: 0, explanation: 'A see-saw is a class-1 lever, with the fulcrum positioned between the two ends.', source },
];
