import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'Original Digital SAT Math practice question in the Advanced Math domain style used in the official test.',
  url: 'https://satsuite.collegeboard.org/sat/whats-on-the-test/structure',
  checkedOn: '14 August 2026',
};

export const SAT_MATH_ADVANCED_MATH_1: Question[] = [
  { id: 'sat-math-advanced-01-001', section: 'Advanced Math', topic: 'Quadratic Equations', difficulty: 'medium', question: 'What is the larger root of x^2 - 5x + 6 = 0?', options: ['3', '2', '1', '4'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Factoring gives (x - 2)(x - 3) = 0, so the roots are 2 and 3, and the larger root is 3.', source },
  { id: 'sat-math-advanced-01-002', section: 'Advanced Math', topic: 'Polynomial Expressions', difficulty: 'easy', question: 'Which expression is equivalent to (x + 3)(x - 3)?', options: ['x^2 + 9', 'x^2 - 9', 'x^2 - 6x - 9', 'x^2 + 6x - 9'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'This is a difference of squares: (x + 3)(x - 3) = x^2 - 9.', source },
  { id: 'sat-math-advanced-01-003', section: 'Advanced Math', topic: 'Nonlinear Functions', difficulty: 'medium', question: 'If f(x) = x^2 - 4x + 1, what is the value of f(5)?', options: ['4', '5', '6', '7'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'f(5) = 25 - 20 + 1 = 6.', source },
  { id: 'sat-math-advanced-01-004', section: 'Advanced Math', topic: 'Exponential Equations', difficulty: 'medium', question: 'If 2^x = 32, what is the value of x?', options: ['4', '7', '6', '5'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: '32 = 2^5, so x = 5.', source },
  { id: 'sat-math-advanced-01-005', section: 'Advanced Math', topic: 'Quadratic Functions', difficulty: 'medium', question: 'For the function y = (x - 2)^2 + 3, what is the minimum value of y?', options: ['3', '2', '1', '4'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'A parabola in vertex form y = (x - h)^2 + k has minimum value k when the squared term is zero; here that minimum is 3.', source },
  { id: 'sat-math-advanced-01-006', section: 'Advanced Math', topic: 'Quadratic Equations', difficulty: 'easy', question: 'Which of the following is the correct factorization of x^2 + 7x + 10?', options: ['(x + 1)(x + 10)', '(x + 2)(x + 5)', '(x - 2)(x - 5)', '(x + 2)(x - 5)'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: '(x + 2)(x + 5) expands to x^2 + 7x + 10.', source },
  { id: 'sat-math-advanced-01-007', section: 'Advanced Math', topic: 'Quadratic Equations', difficulty: 'medium', question: 'What is the sum of both solutions to x^2 = 49?', options: ['-14', '7', '0', '14'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The solutions are x = 7 and x = -7, and their sum is 0.', source },
  { id: 'sat-math-advanced-01-008', section: 'Advanced Math', topic: 'Polynomial Expressions', difficulty: 'easy', question: 'Which expression is equivalent to (3x^2)(4x^3)?', options: ['7x^6', '12x^6', '7x^5', '12x^5'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Multiply coefficients (3 * 4 = 12) and add exponents (2 + 3 = 5) to get 12x^5.', source },
  { id: 'sat-math-advanced-01-009', section: 'Advanced Math', topic: 'Nonlinear Functions', difficulty: 'medium', question: 'If g(x) = 3x^2 - 2x, what is the value of g(-2)?', options: ['16', '12', '8', '20'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'g(-2) = 3(4) - 2(-2) = 12 + 4 = 16.', source },
  { id: 'sat-math-advanced-01-010', section: 'Advanced Math', topic: 'Quadratic Equations', difficulty: 'medium', question: 'What is the smaller root of x^2 - 9x + 20 = 0?', options: ['3', '4', '5', '6'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Factoring gives (x - 4)(x - 5) = 0, so the roots are 4 and 5, and the smaller root is 4.', source },
  { id: 'sat-math-advanced-01-011', section: 'Advanced Math', topic: 'Quadratic Equations', difficulty: 'medium', question: 'What is the value of x that solves x^2 - 6x + 9 = 0?', options: [], correctIndex: -1, correctValue: '3', answerType: 'numerical', marks: 1, negativeMarking: 0, explanation: 'x^2 - 6x + 9 = (x - 3)^2 = 0, giving the double root x = 3.', source },
  { id: 'sat-math-advanced-01-012', section: 'Advanced Math', topic: 'Radicals', difficulty: 'medium', question: 'When the square root of 72 is written in simplest radical form a * sqrt(b), where b has no perfect-square factors greater than 1, what is the value of a?', options: ['4', '8', '6', '12'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'sqrt(72) = sqrt(36 * 2) = 6 * sqrt(2), so a = 6.', source },
  { id: 'sat-math-advanced-01-013', section: 'Advanced Math', topic: 'Nonlinear Functions', difficulty: 'hard', question: 'If h(x) = 2x^3, what is the value of h(3) / h(1)?', options: ['9', '18', '36', '27'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'h(3) = 2(27) = 54 and h(1) = 2, so h(3)/h(1) = 54/2 = 27.', source },
  { id: 'sat-math-advanced-01-014', section: 'Advanced Math', topic: 'Exponential Equations', difficulty: 'medium', question: 'If 3^(x+1) = 27, what is the value of x?', options: ['2', '1', '3', '4'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: '27 = 3^3, so x + 1 = 3, and x = 2.', source },
  { id: 'sat-math-advanced-01-015', section: 'Advanced Math', topic: 'Quadratic Equations', difficulty: 'medium', question: 'The equation x^2 - 4x - 5 = 0 has two roots. What is the positive root?', options: [], correctIndex: -1, correctValue: '5', answerType: 'numerical', marks: 1, negativeMarking: 0, explanation: 'Factoring gives (x - 5)(x + 1) = 0, so the roots are 5 and -1, and the positive root is 5.', source },
];
