import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'Original Digital SAT Reading and Writing practice sentence and multiple-choice question in the Standard English Conventions domain style used in the official test.',
  url: 'https://satsuite.collegeboard.org/sat/whats-on-the-test/reading-writing',
  checkedOn: '14 August 2026',
};

const q = (text: string) => `${text}\n\nWhich choice completes the text so that it conforms to the conventions of Standard English?`;

export const SAT_READING_AND_WRITING_STANDARD_ENGLISH_CONVENTIONS_1: Question[] = [
  { id: 'sat-rw-conventions-01-001', section: 'Standard English Conventions', topic: 'Boundaries', difficulty: 'medium', question: q("The committee reviewed every proposal ______ only two were selected for funding."), options: ['; however,', ', and', 'however', ', however'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: "Two independent clauses joined by a conjunctive adverb like 'however' require a semicolon before it and a comma after it.", source },
  { id: 'sat-rw-conventions-01-002', section: 'Standard English Conventions', topic: 'Boundaries', difficulty: 'medium', question: q("The lecture hall, ______ had been renovated over the summer, reopened to students in September."), options: ['who', 'which', 'that', 'it'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: "'Which' correctly introduces a nonrestrictive clause describing a nonhuman noun (the lecture hall), set off by commas.", source },
  { id: 'sat-rw-conventions-01-003', section: 'Standard English Conventions', topic: 'Form, Structure, and Sense', difficulty: 'medium', question: q("Neither the manager nor the employees ______ aware of the policy change until the memo was sent."), options: ['was', 'is', 'were', 'has been'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: "With 'neither...nor,' the verb agrees with the nearer subject, 'employees' (plural), so 'were' is correct.", source },
  { id: 'sat-rw-conventions-01-004', section: 'Standard English Conventions', topic: 'Form, Structure, and Sense', difficulty: 'easy', question: q("By the time the rescue team arrived, the hikers ______ already found their own way down the mountain."), options: ['have', 'will have', 'has', 'had'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: "The past perfect 'had found' is needed to show an action completed before another past action (the team's arrival).", source },
  { id: 'sat-rw-conventions-01-005', section: 'Standard English Conventions', topic: 'Boundaries', difficulty: 'hard', question: q("Researchers collected samples from three separate lakes ______ each site was chosen for a different reason."), options: [', and', ',', '; and', ' so that'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: "Two independent clauses need a comma plus coordinating conjunction ('and'); a comma alone creates a comma splice, and a semicolon should not also carry 'and'.", source },
  { id: 'sat-rw-conventions-01-006', section: 'Standard English Conventions', topic: 'Form, Structure, and Sense', difficulty: 'medium', question: q("Each of the applicants ______ required to submit two letters of recommendation."), options: ['are', 'is', 'were', 'have been'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: "'Each' is singular, so the verb must agree in the singular: 'is required.'", source },
  { id: 'sat-rw-conventions-01-007', section: 'Standard English Conventions', topic: 'Form, Structure, and Sense', difficulty: 'medium', question: q("The professor gave the award to whoever ______ the strongest final project, regardless of seniority."), options: ['submit', 'submitting', 'submits', 'to submit'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: "'Whoever' is the subject of the clause and is singular, requiring the singular present-tense verb 'submits.'", source },
  { id: 'sat-rw-conventions-01-008', section: 'Standard English Conventions', topic: 'Form, Structure, and Sense', difficulty: 'medium', question: q("The company's new policy affects both ______ full-time employees and part-time contractors."), options: ['it\'s', 'his', 'their', 'its'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: "The possessive form 'its' (no apostrophe) correctly modifies 'policy,' referring to the company; 'it's' is a contraction of 'it is.'", source },
  { id: 'sat-rw-conventions-01-009', section: 'Standard English Conventions', topic: 'Boundaries', difficulty: 'medium', question: q("Having finished the marathon in record time ______ the runner collapsed from exhaustion at the finish line."), options: [',', ';', ':', ' and'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: "A comma is required after the introductory participial phrase 'Having finished the marathon in record time' before the main clause begins; a semicolon or colon is not used after an introductory phrase.", source },
  { id: 'sat-rw-conventions-01-010', section: 'Standard English Conventions', topic: 'Form, Structure, and Sense', difficulty: 'hard', question: q("The data ______ that the new treatment is more effective than the standard one, according to the trial's lead investigator."), options: ['suggests', 'suggest', 'is suggesting', 'has suggested'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: "In formal usage, 'data' is treated as a plural noun (the plural of 'datum'), requiring the plural verb 'suggest.'", source },
  { id: 'sat-rw-conventions-01-011', section: 'Standard English Conventions', topic: 'Form, Structure, and Sense', difficulty: 'medium', question: q("A skilled negotiator listens carefully, weighs each side's concerns, and ______ a compromise that satisfies both parties."), options: ['proposing', 'to propose', 'proposes', 'having proposed'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: "The sentence lists parallel present-tense verbs ('listens,' 'weighs'), so the third verb must also be 'proposes' to maintain parallel structure.", source },
  { id: 'sat-rw-conventions-01-012', section: 'Standard English Conventions', topic: 'Boundaries', difficulty: 'hard', question: "The museum's three wings, listing the natural history collection, the modern art collection, and a rotating exhibit space, each draw a distinct type of visitor.\n\nWhich choice most effectively sets off the nonessential list, which itself contains commas, from the rest of the sentence?", options: ['the natural history collection, the modern art collection, and a rotating exhibit space (no punctuation)', ', the natural history collection, the modern art collection, and a rotating exhibit space,', ': the natural history collection, the modern art collection, and a rotating exhibit space:', '—the natural history collection, the modern art collection, and a rotating exhibit space—'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Since the inserted list already contains commas, paired em dashes (or parentheses) set it off more clearly than commas, which would be ambiguous with the list\'s internal commas; a colon cannot be paired this way.', source },
  { id: 'sat-rw-conventions-01-013', section: 'Standard English Conventions', topic: 'Form, Structure, and Sense', difficulty: 'medium', question: q("If the shipment ______ on time, the store will run out of inventory before the weekend sale begins."), options: ['doesn\'t arrive', 'don\'t arrive', 'didn\'t arrive', 'won\'t arrive'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: "The conditional 'if' clause describing a future possibility uses present tense: 'doesn't arrive,' matching the singular subject 'shipment.'", source },
  { id: 'sat-rw-conventions-01-014', section: 'Standard English Conventions', topic: 'Form, Structure, and Sense', difficulty: 'hard', question: q("Of the two finalists, the judges agreed that Priya's presentation was the ______ prepared, citing her clear structure and confident delivery."), options: ['most', 'more', 'best', 'better'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: "Comparing exactly two finalists requires the comparative form 'more prepared,' not the superlative 'most.'", source },
];
