import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'Original Digital SAT Reading and Writing practice text and multiple-choice question in the Expression of Ideas domain style used in the official test.',
  url: 'https://satsuite.collegeboard.org/sat/whats-on-the-test/reading-writing',
  checkedOn: '14 August 2026',
};

export const SAT_READING_AND_WRITING_EXPRESSION_OF_IDEAS_1: Question[] = [
  { id: 'sat-rw-expression-01-001', section: 'Expression of Ideas', topic: 'Transitions', difficulty: 'medium', question: "The city had budgeted for a mild winter based on historical averages. ______ record snowfall in January forced an emergency increase in the road-maintenance budget.\n\nWhich choice completes the text with the most logical transition?", options: ['However,', 'For example,', 'Similarly,', 'In addition,'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: "The second sentence contradicts the expectation set up in the first, so 'However,' is the logical transition.", source },
  { id: 'sat-rw-expression-01-002', section: 'Expression of Ideas', topic: 'Transitions', difficulty: 'medium', question: "The new alloy resists corrosion better than standard steel. ______ it is roughly 30 percent lighter, making it attractive for aerospace applications.\n\nWhich choice completes the text with the most logical transition?", options: ['Nevertheless,', 'Moreover,', 'In contrast,', 'Instead,'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: "The second sentence adds another advantage of the alloy, so 'Moreover,' correctly signals an additional supporting point.", source },
  { id: 'sat-rw-expression-01-003', section: 'Expression of Ideas', topic: 'Transitions', difficulty: 'hard', question: "Early drafts of the treaty included strict enforcement penalties for violations. ______ the final version removed these penalties after several nations objected during negotiations.\n\nWhich choice completes the text with the most logical transition?", options: ['Consequently,', 'Likewise,', 'Ultimately,', 'Furthermore,'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: "'Ultimately,' signals the final outcome after a process (negotiations), fitting the shift from early drafts to the final version.", source },
  { id: 'sat-rw-expression-01-004', section: 'Expression of Ideas', topic: 'Transitions', difficulty: 'medium', question: "Most of the orchestra's musicians rehearse individually for hours each week. ______ the full ensemble meets together only twice before opening night.\n\nWhich choice completes the text with the most logical transition?", options: ['Similarly,', 'As a result,', 'Because', 'Yet'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: "The heavy individual practice contrasts with the surprisingly few full-ensemble rehearsals, so 'Yet' is the logical contrastive transition.", source },
  { id: 'sat-rw-expression-01-005', section: 'Expression of Ideas', topic: 'Transitions', difficulty: 'medium', question: "The startup's first product failed to attract customers within its planned six-month window. ______ the founders pivoted to a different market rather than shutting down entirely.\n\nWhich choice completes the text with the most logical transition?", options: ['In response,', 'Similarly,', 'For instance,', 'Regardless,'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: "The pivot is a direct reaction to the failed product launch, making 'In response,' the most logical transition.", source },
  { id: 'sat-rw-expression-01-006', section: 'Expression of Ideas', topic: 'Transitions', difficulty: 'hard', question: "The proposed dam would generate substantial renewable energy for the region. ______ it would also flood a valley that serves as habitat for an endangered fish species.\n\nWhich choice completes the text with the most logical transition?", options: ['Therefore,', 'However,', 'Specifically,', 'Similarly,'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: "The second sentence introduces a drawback that complicates the benefit described first, so 'However,' correctly signals this contrast.", source },
  { id: 'sat-rw-expression-01-007', section: 'Expression of Ideas', topic: 'Rhetorical Synthesis', difficulty: 'medium', question: "A student is writing about a local recycling program and has taken these notes:\n- The program started in 2018 with 5 participating neighborhoods.\n- By 2024, it had expanded to 40 neighborhoods.\n- The city reports an 18 percent reduction in landfill waste since the program began.\n\nThe student wants to emphasize how much the program has grown since it started. Which choice most effectively uses relevant information from the notes to accomplish this goal?", options: ['The recycling program has reduced landfill waste by 18 percent citywide.', 'The recycling program began in 2018 and continues to operate today.', 'The recycling program grew from 5 participating neighborhoods in 2018 to 40 by 2024.', 'The city reports positive results from its recycling program.'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Only this option directly states the growth in participating neighborhoods from 5 to 40, which is the specific goal described.', source },
  { id: 'sat-rw-expression-01-008', section: 'Expression of Ideas', topic: 'Rhetorical Synthesis', difficulty: 'medium', question: "A researcher has taken these notes on two bridge designs:\n- Design A costs $12 million and takes 18 months to build.\n- Design B costs $9 million and takes 24 months to build.\n- Design A can support heavier freight traffic than Design B.\n\nThe researcher wants to compare the two designs specifically in terms of construction cost. Which choice most effectively uses relevant information from the notes to accomplish this goal?", options: ['Design A can support heavier freight traffic than Design B.', 'Both designs were proposed for the same river crossing.', 'Design B takes longer to build than Design A.', 'Design A costs $12 million to build, while Design B costs $9 million.'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Only this option directly compares the two designs by construction cost, the specific goal stated.', source },
  { id: 'sat-rw-expression-01-009', section: 'Expression of Ideas', topic: 'Rhetorical Synthesis', difficulty: 'hard', question: "A student has taken these notes on a species of migratory bird:\n- The bird travels roughly 11,000 kilometers each year between breeding and wintering grounds.\n- It relies on wetlands as stopover sites to rest and feed.\n- Loss of wetland habitat has been linked to a 30 percent population decline since 2000.\n\nThe student wants to explain why wetland loss specifically threatens this bird's survival. Which choice most effectively uses relevant information from the notes to accomplish this goal?", options: ['Because the bird depends on wetlands as stopover sites, wetland loss has contributed to a 30 percent population decline since 2000.', 'The bird migrates 11,000 kilometers each year.', 'The bird has both breeding and wintering grounds.', 'Migratory birds face many threats to their survival.'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: "Only this option connects the bird's dependence on wetlands to the specific population decline, directly explaining the threat as asked.", source },
  { id: 'sat-rw-expression-01-010', section: 'Expression of Ideas', topic: 'Rhetorical Synthesis', difficulty: 'medium', question: "A student has taken these notes on two smartphone battery types:\n- Lithium-ion batteries charge faster but degrade after roughly 500 charge cycles.\n- Solid-state batteries charge slower but can last over 1,000 charge cycles.\n- Solid-state batteries are currently more expensive to manufacture.\n\nThe student wants to highlight a disadvantage of solid-state batteries specifically. Which choice most effectively uses relevant information from the notes to accomplish this goal?", options: ['Solid-state batteries can last over 1,000 charge cycles.', 'Solid-state batteries are currently more expensive to manufacture than lithium-ion batteries.', 'Lithium-ion batteries charge faster than solid-state batteries.', 'Both battery types are used in smartphones today.'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Only this option states a clear disadvantage specific to solid-state batteries: higher manufacturing cost.', source },
  { id: 'sat-rw-expression-01-011', section: 'Expression of Ideas', topic: 'Rhetorical Synthesis', difficulty: 'hard', question: "A student has taken these notes on a company's remote-work policy:\n- Employee surveys show 72 percent prefer working from home at least three days a week.\n- Office attendance dropped 40 percent after the policy was introduced.\n- The company's rental costs for office space have decreased by 15 percent as a result.\n\nThe student wants to explain a financial benefit the company gained from the policy. Which choice most effectively uses relevant information from the notes to accomplish this goal?", options: ['72 percent of employees prefer working from home at least three days a week.', 'Office attendance dropped 40 percent after the policy was introduced.', "The company's rental costs for office space decreased by 15 percent as a result of the policy.", 'The remote-work policy was introduced after an employee survey.'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'Only this option identifies a specific financial benefit, the 15 percent reduction in rental costs, directly answering the stated goal.', source },
];
