import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SBI Junior Associate (Customer Support & Sales) 2025-26 official advertisement (CRPD/CR/2025-26/06) — Mains, Reasoning Ability & Computer Aptitude section',
  url: 'https://sbi.bank.in/documents/77530/52947104/JA+2025+-Detailed+Advt.pdf',
  checkedOn: '29 August 2026',
};

const SEATING_PUZZLE =
  'Five friends F, G, H, I, and J are sitting in a row facing north, not necessarily in that order. H sits second to the left of J. I sits immediate right of H. F sits at one of the extreme ends. G sits immediate left of F.\n\n';

const BOX_PUZZLE =
  'Five boxes K, L, M, N, and O are stacked one above another, not necessarily in that order. N is at the bottom. M is just above N. K is above M. O is just above L. Exactly one box is between K and L.\n\n';

export const SBI_CLERK_MAINS_REASONING_COMPUTER_APTITUDE_2: Question[] = [
  { id: 'sbi-clerk-m2-rc-001', section: 'Reasoning Ability & Computer Aptitude', topic: 'Seating arrangement', difficulty: 'hard', question: `${SEATING_PUZZLE}Who sits at the middle (3rd from the left) position?`, options: ['J', 'G', 'H', 'I'], correctIndex: 0, marks: 1.2, negativeMarking: 0.3, explanation: 'Since F is at an extreme end and G is immediately left of F, F=5th, G=4th. From "H second to left of J" and "I immediate right of H", the only arrangement fitting positions 1-3 is H=1, I=2, J=3. So the order is H, I, J, G, F — J is at the middle.', source },
  { id: 'sbi-clerk-m2-rc-002', section: 'Reasoning Ability & Computer Aptitude', topic: 'Seating arrangement', difficulty: 'hard', question: `${SEATING_PUZZLE}Who sits immediately left of G?`, options: ['I', 'J', 'F', 'H'], correctIndex: 1, marks: 1.2, negativeMarking: 0.3, explanation: 'The final order is H, I, J, G, F. J (3rd position) sits immediately left of G (4th position).', source },
  { id: 'sbi-clerk-m2-rc-003', section: 'Reasoning Ability & Computer Aptitude', topic: 'Seating arrangement', difficulty: 'hard', question: `${SEATING_PUZZLE}How many people sit between I and F?`, options: ['0', '1', '2', '3'], correctIndex: 2, marks: 1.2, negativeMarking: 0.3, explanation: 'The final order is H, I, J, G, F. I is at position 2 and F is at position 5, so J and G (positions 3 and 4) sit between them — 2 people.', source },
  { id: 'sbi-clerk-m2-rc-004', section: 'Reasoning Ability & Computer Aptitude', topic: 'Seating arrangement', difficulty: 'medium', question: `${SEATING_PUZZLE}Who sits at the extreme left end?`, options: ['G', 'I', 'J', 'H'], correctIndex: 3, marks: 1.2, negativeMarking: 0.3, explanation: 'The final order is H, I, J, G, F. H is at position 1, the extreme left end.', source },
  { id: 'sbi-clerk-m2-rc-005', section: 'Reasoning Ability & Computer Aptitude', topic: 'Box-based puzzle', difficulty: 'hard', question: `${BOX_PUZZLE}Which box is at the top of the stack?`, options: ['K', 'O', 'L', 'M'], correctIndex: 0, marks: 1.2, negativeMarking: 0.3, explanation: 'With N at the bottom (5th) and M just above it (4th), K must be above M, occupying one of positions 1-3. Testing O-L as consecutive pairs within positions 1-3, only O=2, L=3, K=1 satisfies "exactly one box between K and L" (O sits between them). So from top: K, O, L, M, N — K is at the top.', source },
  { id: 'sbi-clerk-m2-rc-006', section: 'Reasoning Ability & Computer Aptitude', topic: 'Box-based puzzle', difficulty: 'hard', question: `${BOX_PUZZLE}Which box is immediately below O?`, options: ['N', 'L', 'K', 'M'], correctIndex: 1, marks: 1.2, negativeMarking: 0.3, explanation: 'The stack from top to bottom is K, O, L, M, N. L is immediately below O.', source },
  { id: 'sbi-clerk-m2-rc-007', section: 'Reasoning Ability & Computer Aptitude', topic: 'Syllogism', difficulty: 'medium', question: 'Statements: All coins are notes. No note is a cheque. Conclusions: I. No coin is a cheque. II. Some notes are coins. Which conclusion(s) follow?', options: ['Only I follows', 'Only II follows', 'Both I and II follow', 'Neither follows'], correctIndex: 2, marks: 1.2, negativeMarking: 0.3, explanation: 'Since all coins are notes and no note is a cheque, no coin can be a cheque (I follows). Since coins exist within notes, some notes are coins (II follows).', source },
  { id: 'sbi-clerk-m2-rc-008', section: 'Reasoning Ability & Computer Aptitude', topic: 'Syllogism', difficulty: 'medium', question: 'Statements: Some routers are switches. No switch is a modem. Conclusions: I. No router is a modem. II. Some routers are not modems. Which conclusion(s) follow?', options: ['Neither follows', 'Both follow', 'Only I follows', 'Only II follows'], correctIndex: 3, marks: 1.2, negativeMarking: 0.3, explanation: 'Since some routers are switches and no switch is a modem, those particular routers are not modems, so "some routers are not modems" (II) follows. It cannot be concluded that no router at all is a modem (I), since other routers outside the switch group are unaccounted for.', source },
  { id: 'sbi-clerk-m2-rc-009', section: 'Reasoning Ability & Computer Aptitude', topic: 'Syllogism', difficulty: 'medium', question: 'Statements: All ledgers are registers. All registers are documents. Conclusions: I. All ledgers are documents. II. Some documents are ledgers. Which conclusion(s) follow?', options: ['Both I and II follow', 'Only I follows', 'Only II follows', 'Neither follows'], correctIndex: 0, marks: 1.2, negativeMarking: 0.3, explanation: 'Since ledgers are a subset of registers, which are a subset of documents, all ledgers are documents (I follows), and since ledgers exist within documents, some documents are ledgers (II follows).', source },
  { id: 'sbi-clerk-m2-rc-010', section: 'Reasoning Ability & Computer Aptitude', topic: 'Syllogism', difficulty: 'hard', question: 'Statements: No printer is a scanner. Some scanners are copiers. Conclusions: I. No printer is a copier. II. Some copiers are not printers. Which conclusion(s) follow?', options: ['Neither follows', 'Only II follows', 'Only I follows', 'Both follow'], correctIndex: 1, marks: 1.2, negativeMarking: 0.3, explanation: 'Since some scanners are copiers and no printer is a scanner, those particular copiers are not printers, so "some copiers are not printers" (II) follows. It cannot be concluded that no copier at all is a printer (I), since copiers outside the scanner group are unaccounted for.', source },
  { id: 'sbi-clerk-m2-rc-011', section: 'Reasoning Ability & Computer Aptitude', topic: 'Blood relations', difficulty: 'hard', question: 'Pointing to a man, a woman said, "His father is the only son of my grandfather." How is the woman related to the man?', options: ['Daughter', 'Mother', 'Sister', 'Aunt'], correctIndex: 2, marks: 1.2, negativeMarking: 0.3, explanation: "The only son of the woman's grandfather is the woman's own father. So the man's father is the woman's father too, making the man and woman siblings — the woman is the man's sister.", source },
  { id: 'sbi-clerk-m2-rc-012', section: 'Reasoning Ability & Computer Aptitude', topic: 'Blood relations', difficulty: 'hard', question: 'A is the son of B, who is female. C is the brother of A. D is the father of C. How is D related to B?', options: ['Son', 'Father', 'Brother', 'Husband'], correctIndex: 3, marks: 1.2, negativeMarking: 0.3, explanation: "D is the father of C, and since C is the brother of A, D is also the father of A. Since B (female) is A's mother, D must be B's husband.", source },
  { id: 'sbi-clerk-m2-rc-013', section: 'Reasoning Ability & Computer Aptitude', topic: 'Blood relations', difficulty: 'medium', question: 'Introducing a girl, a boy said, "She is the daughter of the sister of my father." How is the girl related to the boy?', options: ['Cousin', 'Aunt', 'Sister', 'Niece'], correctIndex: 0, marks: 1.2, negativeMarking: 0.3, explanation: "The sister of the boy's father is his paternal aunt. The daughter of his paternal aunt is his cousin.", source },
  { id: 'sbi-clerk-m2-rc-014', section: 'Reasoning Ability & Computer Aptitude', topic: 'Direction sense', difficulty: 'medium', question: 'A man walks 9 km towards North, then turns left and walks 7 km, then turns left again and walks 9 km. How far is he from his starting point, and in which direction?', options: ['9 km, West', '7 km, West', '7 km, East', '16 km, West'], correctIndex: 1, marks: 1.2, negativeMarking: 0.3, explanation: 'North 9 km, then West 7 km (turn left from North faces West), then South 9 km (turn left from West faces South). The North and South legs cancel, leaving him 7 km West of the start.', source },
  { id: 'sbi-clerk-m2-rc-015', section: 'Reasoning Ability & Computer Aptitude', topic: 'Direction sense', difficulty: 'hard', question: 'Point A is 12 km east of point B. Point C is 16 km north of point A. Find the distance between B and C.', options: ['22 km', '18 km', '20 km', '16 km'], correctIndex: 2, marks: 1.2, negativeMarking: 0.3, explanation: 'B to A (12 km) and A to C (16 km) form a right angle. Distance BC = √(12² + 16²) = √400 = 20 km.', source },
  { id: 'sbi-clerk-m2-rc-016', section: 'Reasoning Ability & Computer Aptitude', topic: 'Direction sense', difficulty: 'medium', question: 'Priya starts from home and walks 6 km East, then turns right and walks 6 km, then turns right again and walks 6 km, then turns right again and walks 6 km. How far is she from her home now?', options: ['24 km', '6 km', '12 km', '0 km'], correctIndex: 3, marks: 1.2, negativeMarking: 0.3, explanation: 'East 6 km, South 6 km, West 6 km, North 6 km — this traces a complete square, bringing her back to the starting point, 0 km away.', source },
  { id: 'sbi-clerk-m2-rc-017', section: 'Reasoning Ability & Computer Aptitude', topic: 'Coding-decoding', difficulty: 'medium', question: "If in a certain code, 'RIVER' is written as 'SJWFS' (each letter shifted one place forward), how is 'CHAIR' written in the same code?", options: ['DIBJS', 'DJBJS', 'DIAJS', 'DIBJT'], correctIndex: 0, marks: 1.2, negativeMarking: 0.3, explanation: 'Shifting each letter forward by one: C→D, H→I, A→B, I→J, R→S, giving DIBJS.', source },
  { id: 'sbi-clerk-m2-rc-018', section: 'Reasoning Ability & Computer Aptitude', topic: 'Coding-decoding', difficulty: 'medium', question: "In a certain code, TRAIN is written as USBJO (each letter shifted one place forward). How is HOUSE written in the same code?", options: ['IQVTF', 'IPVTF', 'IPUTF', 'IPVTG'], correctIndex: 1, marks: 1.2, negativeMarking: 0.3, explanation: 'Shifting each letter forward by one: H→I, O→P, U→V, S→T, E→F, giving IPVTF.', source },
  { id: 'sbi-clerk-m2-rc-019', section: 'Reasoning Ability & Computer Aptitude', topic: 'Coding-decoding', difficulty: 'medium', question: "If X is coded as 24, Y as 25, and Z as 26 (using each letter's position in the alphabet), what is the code for the word 'DOG'?", options: ['4-15-8', '3-15-7', '4-15-7', '4-14-7'], correctIndex: 2, marks: 1.2, negativeMarking: 0.3, explanation: 'D=4, O=15, G=7, giving the code 4-15-7.', source },
  { id: 'sbi-clerk-m2-rc-020', section: 'Reasoning Ability & Computer Aptitude', topic: 'Coding-decoding', difficulty: 'hard', question: "In a code, 'MARKET' is written as 'LZQJDS' (each letter shifted one place backward). How is 'WINDOW' written in the same code?", options: ['VHMCNU', 'VGMCNV', 'VHNCNV', 'VHMCNV'], correctIndex: 3, marks: 1.2, negativeMarking: 0.3, explanation: 'Shifting each letter backward by one: W→V, I→H, N→M, D→C, O→N, W→V, giving VHMCNV.', source },
  { id: 'sbi-clerk-m2-rc-021', section: 'Reasoning Ability & Computer Aptitude', topic: 'Inequality', difficulty: 'medium', question: 'Statements: F > G ≥ H = I > J. Conclusions: I. F > I  II. G > J. Which conclusion(s) follow?', options: ['Both I and II follow', 'Only I follows', 'Only II follows', 'Neither follows'], correctIndex: 0, marks: 1.2, negativeMarking: 0.3, explanation: 'Since F > G ≥ H = I, it follows that F > I (I). Since G ≥ H = I > J, it follows that G > J (II).', source },
  { id: 'sbi-clerk-m2-rc-022', section: 'Reasoning Ability & Computer Aptitude', topic: 'Inequality', difficulty: 'hard', question: 'Statements: K ≥ L > M ≥ N. Conclusions: I. K > N  II. N ≥ K. Which conclusion(s) follow?', options: ['Both follow', 'Only I follows', 'Neither follows', 'Only II follows'], correctIndex: 1, marks: 1.2, negativeMarking: 0.3, explanation: 'The chain K ≥ L > M ≥ N contains a strict inequality (L > M), so K > N follows (I). Since K > N is established, N ≥ K is false (II does not follow).', source },
  { id: 'sbi-clerk-m2-rc-023', section: 'Reasoning Ability & Computer Aptitude', topic: 'Inequality', difficulty: 'hard', question: 'Statements: P < Q ≤ R < S. Conclusions: I. R ≤ P  II. S > P. Which conclusion(s) follow?', options: ['Neither follows', 'Only I follows', 'Only II follows', 'Both follow'], correctIndex: 2, marks: 1.2, negativeMarking: 0.3, explanation: 'Since P < Q ≤ R, P < R, so "R ≤ P" (I) is false. Since P < Q ≤ R < S, transitively P < S, so "S > P" (II) follows.', source },
  { id: 'sbi-clerk-m2-rc-024', section: 'Reasoning Ability & Computer Aptitude', topic: 'Alphanumeric series', difficulty: 'hard', question: 'Complete the series: A3, E12, I27, M48, ?', options: ['Q72', 'R75', 'Q70', 'Q75'], correctIndex: 3, marks: 1.2, negativeMarking: 0.3, explanation: 'The letters skip three each time (A, E, I, M, Q). The numbers follow 3n² for n=1,2,3,4,5: 3, 12, 27, 48, 75. Next term: Q75.', source },
  { id: 'sbi-clerk-m2-rc-025', section: 'Reasoning Ability & Computer Aptitude', topic: 'Alphanumeric series', difficulty: 'hard', question: 'Find the missing term: 2C4, 4G9, 6K16, 8O25, ?', options: ['10S36', '10S35', '10T36', '9S36'], correctIndex: 0, marks: 1.2, negativeMarking: 0.3, explanation: 'The leading numbers increase by 2 (2,4,6,8,10). The letters skip 3 each time (C,G,K,O,S). The trailing numbers are perfect squares (4,9,16,25,36). Next term: 10S36.', source },
  { id: 'sbi-clerk-m2-rc-026', section: 'Reasoning Ability & Computer Aptitude', topic: 'Alphanumeric series', difficulty: 'medium', question: "In the word 'COMPUTER', how many letters are there between the 3rd letter from the left and the 3rd letter from the right, as they appear in the word?", options: ['1', '2', '3', '4'], correctIndex: 1, marks: 1.2, negativeMarking: 0.3, explanation: "The word has 8 letters. The 3rd from the left is 'M' (position 3), and the 3rd from the right is 'T' (position 6). The letters between positions 4 and 5 (P, U) total 2.", source },
  { id: 'sbi-clerk-m2-rc-027', section: 'Reasoning Ability & Computer Aptitude', topic: 'Alphanumeric series', difficulty: 'medium', question: "If the letters of the word 'BUDGET' are arranged in alphabetical order, how many letters remain in the same position as in the original word?", options: ['1', '3', '2', '4'], correctIndex: 2, marks: 1.2, negativeMarking: 0.3, explanation: "Original: B-U-D-G-E-T. Alphabetical order: B-D-E-G-T-U. Comparing position by position, B (position 1) and G (position 4) remain in the same position — 2 letters.", source },
  { id: 'sbi-clerk-m2-rc-028', section: 'Reasoning Ability & Computer Aptitude', topic: 'Alphanumeric series', difficulty: 'medium', question: 'Find the missing term: Z30, W26, T22, Q18, ?', options: ['N15', 'O14', 'M14', 'N14'], correctIndex: 3, marks: 1.2, negativeMarking: 0.3, explanation: 'The letters move backward by 3 each time (Z, W, T, Q, N). The numbers decrease by 4 each time (30, 26, 22, 18, 14). Next term: N14.', source },
  { id: 'sbi-clerk-m2-rc-029', section: 'Reasoning Ability & Computer Aptitude', topic: 'Data sufficiency', difficulty: 'medium', question: "What is the age of Meena? Statement I: Meena is 6 years younger than her sister. Statement II: Meena's sister is 24 years old. Which statement(s) are sufficient to answer the question?", options: ['Both I and II together are necessary', 'Either I or II alone is sufficient', 'Statement I alone is sufficient', 'Statement II alone is sufficient'], correctIndex: 0, marks: 1.2, negativeMarking: 0.3, explanation: "Statement I alone gives only a relative age difference, not an actual age. Statement II alone gives the sister's age but not Meena's. Combined, Meena's age = 24 − 6 = 18, so both are needed together.", source },
  { id: 'sbi-clerk-m2-rc-030', section: 'Reasoning Ability & Computer Aptitude', topic: 'Data sufficiency', difficulty: 'medium', question: 'Is y divisible by 3? Statement I: y is divisible by 9. Statement II: y is divisible by 6. Which statement(s) are sufficient to answer the question?', options: ['Both together are necessary', 'Either I or II alone is sufficient', 'Only I is sufficient', 'Only II is sufficient'], correctIndex: 1, marks: 1.2, negativeMarking: 0.3, explanation: 'If y is divisible by 9, it must be divisible by 3 (Statement I alone is sufficient). If y is divisible by 6, it must also be divisible by 3, since 6 = 2 × 3 (Statement II alone is sufficient). So either statement alone answers the question.', source },
  { id: 'sbi-clerk-m2-rc-031', section: 'Reasoning Ability & Computer Aptitude', topic: 'Data sufficiency', difficulty: 'medium', question: 'What is the discount percentage on an article? Statement I: The marked price of the article is ₹1000. Statement II: The article was sold at ₹850. Which statement(s) are sufficient to answer the question?', options: ['Statement I alone is sufficient', 'Statement II alone is sufficient', 'Both I and II together are necessary', 'Either alone is sufficient'], correctIndex: 2, marks: 1.2, negativeMarking: 0.3, explanation: 'Statement I alone gives only the marked price, and Statement II alone gives only the selling price; neither alone can determine the discount percentage. Combined, discount % = ((1000−850)/1000) × 100 = 15%.', source },
  { id: 'sbi-clerk-m2-rc-032', section: 'Reasoning Ability & Computer Aptitude', topic: 'Ranking and order', difficulty: 'medium', question: 'In a class of 50 students, Aman ranks 21st from the top. What is his rank from the bottom?', options: ['31st', '28th', '29th', '30th'], correctIndex: 3, marks: 1.2, negativeMarking: 0.3, explanation: 'Rank from bottom = total students − rank from top + 1 = 50 − 21 + 1 = 30th.', source },
  { id: 'sbi-clerk-m2-rc-033', section: 'Reasoning Ability & Computer Aptitude', topic: 'Ranking and order', difficulty: 'medium', question: 'Sneha is 9th from the left and 14th from the right in a row of students. How many students are there in the row?', options: ['22', '21', '23', '20'], correctIndex: 0, marks: 1.2, negativeMarking: 0.3, explanation: 'Total students = (position from left) + (position from right) − 1 = 9 + 14 − 1 = 22.', source },
  { id: 'sbi-clerk-m2-rc-034', section: 'Reasoning Ability & Computer Aptitude', topic: 'Statement and conclusion', difficulty: 'medium', question: 'Statement: "All customers must present a valid ID before opening a new account." Assumptions: I. Some customers may attempt to open an account without ID. II. ID verification is part of the account-opening process. Which assumption(s) is/are implicit?', options: ['Only II is implicit', 'Both I and II are implicit', 'Neither is implicit', 'Only I is implicit'], correctIndex: 1, marks: 1.2, negativeMarking: 0.3, explanation: 'The instruction implies that some customers might otherwise attempt to open an account without ID (I), and it directly restates that ID verification is part of the process (II). Both are implicit.', source },
  { id: 'sbi-clerk-m2-rc-035', section: 'Reasoning Ability & Computer Aptitude', topic: 'Statement and conclusion', difficulty: 'medium', question: 'Statement: "Employees are advised to update their KYC details before the end of the month." Assumptions: I. Some employees may not update their KYC details without this advisory. II. KYC updation is part of the bank\'s compliance process. Which assumption(s) is/are implicit?', options: ['Neither is implicit', 'Only I is implicit', 'Both I and II are implicit', 'Only II is implicit'], correctIndex: 2, marks: 1.2, negativeMarking: 0.3, explanation: 'The advisory implies that some employees might not otherwise update their KYC details (I), and its purpose implies that KYC updation is part of the compliance process (II). Both are implicit.', source },
  { id: 'sbi-clerk-m2-rc-036', section: 'Reasoning Ability & Computer Aptitude', topic: 'Computer fundamentals', difficulty: 'easy', question: 'Which of the following is an example of secondary storage?', options: ['Register', 'RAM', 'Cache memory', 'Hard disk'], correctIndex: 3, marks: 1.2, negativeMarking: 0.3, explanation: 'A hard disk is a secondary (non-volatile) storage device, unlike RAM, cache memory, and registers, which are primary/temporary storage.', source },
  { id: 'sbi-clerk-m2-rc-037', section: 'Reasoning Ability & Computer Aptitude', topic: 'Networking', difficulty: 'medium', question: "What does 'WAN' stand for?", options: ['Wide Area Network', 'Wireless Area Network', 'Web Access Network', 'Wide Access Node'], correctIndex: 0, marks: 1.2, negativeMarking: 0.3, explanation: 'WAN stands for Wide Area Network, a network that spans a large geographic area, connecting multiple smaller networks.', source },
  { id: 'sbi-clerk-m2-rc-038', section: 'Reasoning Ability & Computer Aptitude', topic: 'Internet protocols', difficulty: 'medium', question: 'Which protocol allows a user to retrieve emails from a mail server while keeping a copy of them on the server?', options: ['FTP', 'IMAP', 'SNMP', 'POP3'], correctIndex: 1, marks: 1.2, negativeMarking: 0.3, explanation: 'IMAP (Internet Message Access Protocol) retrieves emails while keeping them synchronised on the server, unlike POP3, which typically downloads and removes them.', source },
  { id: 'sbi-clerk-m2-rc-039', section: 'Reasoning Ability & Computer Aptitude', topic: 'Software', difficulty: 'medium', question: 'Which of the following is an example of open-source software?', options: ['macOS', 'MS Office', 'Linux', 'Windows'], correctIndex: 2, marks: 1.2, negativeMarking: 0.3, explanation: 'Linux is open-source operating system software, freely available for anyone to view, modify, and distribute its source code.', source },
  { id: 'sbi-clerk-m2-rc-040', section: 'Reasoning Ability & Computer Aptitude', topic: 'Networking', difficulty: 'medium', question: 'Which device regenerates and amplifies a signal to extend the range of a network?', options: ['Switch', 'Bridge', 'Gateway', 'Repeater'], correctIndex: 3, marks: 1.2, negativeMarking: 0.3, explanation: 'A repeater regenerates and amplifies a weakened signal to extend the effective range of a network.', source },
  { id: 'sbi-clerk-m2-rc-041', section: 'Reasoning Ability & Computer Aptitude', topic: 'MS Office', difficulty: 'easy', question: 'Which shortcut key is used to save a document in MS Word?', options: ['Ctrl + S', 'Ctrl + N', 'Ctrl + O', 'Ctrl + P'], correctIndex: 0, marks: 1.2, negativeMarking: 0.3, explanation: 'Ctrl + S is the standard shortcut for saving a document in MS Word.', source },
  { id: 'sbi-clerk-m2-rc-042', section: 'Reasoning Ability & Computer Aptitude', topic: 'Computer security', difficulty: 'medium', question: 'The practice of tricking users into revealing confidential information through deceptive emails or messages is called:', options: ['Tokenization', 'Phishing', 'Encryption', 'Firewalling'], correctIndex: 1, marks: 1.2, negativeMarking: 0.3, explanation: 'Phishing uses deceptive emails or messages impersonating a trusted source to trick users into revealing confidential information.', source },
  { id: 'sbi-clerk-m2-rc-043', section: 'Reasoning Ability & Computer Aptitude', topic: 'Hardware', difficulty: 'medium', question: 'Which device is used to convert handwritten or printed text into digital form?', options: ['Speaker', 'Printer', 'Scanner', 'Modem'], correctIndex: 2, marks: 1.2, negativeMarking: 0.3, explanation: 'A scanner captures printed or handwritten text and converts it into a digital image or document.', source },
  { id: 'sbi-clerk-m2-rc-044', section: 'Reasoning Ability & Computer Aptitude', topic: 'Number systems', difficulty: 'medium', question: 'What is the hexadecimal equivalent of the decimal number 255?', options: ['EF', 'EE', 'FE', 'FF'], correctIndex: 3, marks: 1.2, negativeMarking: 0.3, explanation: '255 in hexadecimal is FF, since F represents 15 and 15×16 + 15 = 255.', source },
  { id: 'sbi-clerk-m2-rc-045', section: 'Reasoning Ability & Computer Aptitude', topic: 'Computer security', difficulty: 'medium', question: 'Gaining unauthorized access to a computer system or network with malicious intent is called:', options: ['Hacking', 'Booting', 'Formatting', 'Debugging'], correctIndex: 0, marks: 1.2, negativeMarking: 0.3, explanation: 'Hacking refers to gaining unauthorized access to a computer system or network, typically with malicious intent.', source },
  { id: 'sbi-clerk-m2-rc-046', section: 'Reasoning Ability & Computer Aptitude', topic: 'Computer fundamentals', difficulty: 'easy', question: "What does 'CPU' stand for?", options: ['Central Processor Utility', 'Central Processing Unit', 'Computer Processing Unit', 'Central Program Utility'], correctIndex: 1, marks: 1.2, negativeMarking: 0.3, explanation: 'CPU stands for Central Processing Unit, the primary component that executes instructions in a computer.', source },
  { id: 'sbi-clerk-m2-rc-047', section: 'Reasoning Ability & Computer Aptitude', topic: 'MS Office', difficulty: 'easy', question: 'In MS Excel, which function returns the largest value in a range of cells?', options: ['COUNT', 'MIN', 'MAX', 'SUM'], correctIndex: 2, marks: 1.2, negativeMarking: 0.3, explanation: 'The MAX function returns the largest numeric value within a specified range of cells.', source },
  { id: 'sbi-clerk-m2-rc-048', section: 'Reasoning Ability & Computer Aptitude', topic: 'Operating systems', difficulty: 'medium', question: 'Which type of operating system processes tasks within a strict time constraint, commonly used in embedded systems?', options: ['Multi-user operating system', 'Distributed operating system', 'Batch operating system', 'Real-time operating system'], correctIndex: 3, marks: 1.2, negativeMarking: 0.3, explanation: 'A real-time operating system processes and responds to inputs within a strict, guaranteed time constraint, commonly used in embedded and industrial control systems.', source },
  { id: 'sbi-clerk-m2-rc-049', section: 'Reasoning Ability & Computer Aptitude', topic: 'Computer fundamentals', difficulty: 'easy', question: 'The process of restarting a computer without turning off the power completely (e.g. via the operating system\'s restart option) is called a:', options: ['Cold boot', 'Warm boot', 'Hard boot', 'Shutdown'], correctIndex: 1, marks: 1.2, negativeMarking: 0.3, explanation: 'A warm boot restarts a computer without cutting power completely, unlike a cold boot, which starts the machine from a fully powered-off state.', source },
  { id: 'sbi-clerk-m2-rc-050', section: 'Reasoning Ability & Computer Aptitude', topic: 'Computer fundamentals', difficulty: 'easy', question: "What is the full form of 'URL'?", options: ['Universal Reference Link', 'Uniform Resource Locator', 'Universal Resource Link', 'Uniform Reference Locator'], correctIndex: 1, marks: 1.2, negativeMarking: 0.3, explanation: "'URL' stands for Uniform Resource Locator, the address used to locate a resource on the internet.", source },
];
