import type { Question } from '../questions';

const SOURCE = {
  kind: 'original' as const,
  reference: 'TakeMockTest original practice aligned to the SBI PO 2026 Mains English Language section',
  url: 'https://sbi.bank.in/web/careers/current-openings',
  checkedOn: '29 August 2026',
};

const MARKS = 20 / 40;
const PENALTY = MARKS / 4;

function question(
  id: string,
  topic: string,
  difficulty: 'easy' | 'medium' | 'hard',
  prompt: string,
  options: string[],
  correctIndex: number,
  explanation: string,
): Question {
  return {
    id,
    section: 'English Language',
    topic,
    difficulty,
    question: prompt,
    options,
    correctIndex,
    marks: MARKS,
    negativeMarking: PENALTY,
    explanation,
    source: SOURCE,
  };
}

const RC_PASSAGE =
  'Co-lending arrangements, where a bank and a non-banking financial company jointly fund a single loan, have expanded rapidly across India\'s retail and small-business credit market in recent years. The appeal for banks lies in reaching borrowers, particularly in smaller towns, that an NBFC partner already understands through years of local presence, without the bank having to build that distribution network itself. NBFCs, in turn, gain access to lower-cost bank funding that they could not raise as cheaply on their own. Regulators have permitted this model on the condition that the bank retains a meaningful share of the credit risk on each loan, rather than merely lending its name while an NBFC bears the underlying risk. Critics note that borrowers rarely know their loan is being funded by two separate institutions, since only one brand typically appears on their loan documents, raising questions about whether disclosure requirements have kept pace with how quickly the model has grown. Proponents counter that the arrangement has genuinely expanded credit access in areas banks previously found too costly to serve directly, and argue that disclosure to the borrower matters less than ensuring both institutions remain accountable for loan quality. ';

export const SBI_PO_MAINS_ENGLISH_2: Question[] = [
  question('sbi-po-m2-en-001', 'Reading comprehension', 'medium', RC_PASSAGE + 'According to the passage, what does a bank gain from a co-lending arrangement with an NBFC?', ['Access to borrowers an NBFC already understands, without building its own distribution network', 'Complete immunity from all credit risk', 'A guaranteed government subsidy', 'Full ownership of the NBFC partner'], 0, 'The passage states the appeal for banks lies in reaching borrowers an NBFC partner already understands, without the bank having to build that distribution network itself.'),
  question('sbi-po-m2-en-002', 'Reading comprehension', 'medium', RC_PASSAGE + 'What do NBFCs gain from co-lending, per the passage?', ['Ownership of the bank\'s brand name', 'Access to lower-cost bank funding they could not raise as cheaply alone', 'Complete control over the bank\'s operations', 'Exemption from all regulatory oversight'], 1, 'The passage states NBFCs gain access to lower-cost bank funding that they could not raise as cheaply on their own.'),
  question('sbi-po-m2-en-003', 'Reading comprehension', 'hard', RC_PASSAGE + 'What condition have regulators placed on the co-lending model, according to the passage?', ['Only government banks may participate', 'Loans must be disbursed within 24 hours', 'The bank must retain a meaningful share of the credit risk on each loan', 'NBFCs must be banned from the retail credit market'], 2, 'The passage states regulators have permitted the model on the condition that the bank retains a meaningful share of the credit risk, rather than merely lending its name.'),
  question('sbi-po-m2-en-004', 'Reading comprehension', 'medium', RC_PASSAGE + 'What concern do critics raise about co-lending, per the passage?', ['That interest rates are always higher under co-lending', 'That NBFCs have stopped lending entirely', 'That banks no longer earn any profit from these loans', 'That borrowers rarely know their loan is funded by two institutions, raising disclosure questions'], 3, 'The passage states critics note that borrowers rarely know their loan is funded by two separate institutions, raising questions about whether disclosure has kept pace.'),
  question('sbi-po-m2-en-005', 'Reading comprehension', 'hard', RC_PASSAGE + 'How do proponents respond to the disclosure concern, according to the passage?', ['They argue accountability for loan quality matters more than borrower disclosure', 'They deny that co-lending exists', 'They agree disclosure should be banned outright', 'They claim NBFCs should stop participating entirely'], 0, 'The passage states proponents argue that disclosure to the borrower matters less than ensuring both institutions remain accountable for loan quality.'),
  question('sbi-po-m2-en-006', 'Cloze test', 'medium', 'The committee has decided to _______ the agreement after reviewing the revised terms.', ['finalization', 'finalize', 'finalizing', 'finalized'], 1, '"Decided to" is followed by the base form of the verb ("to finalize"), making "finalize" grammatically correct.'),
  question('sbi-po-m2-en-007', 'Cloze test', 'medium', 'Despite the technical glitch, the transaction _______ successfully.', ['process', 'processes', 'processed', 'processing'], 2, 'The sentence describes a completed past event, so the simple past tense "processed" is correct.'),
  question('sbi-po-m2-en-008', 'Cloze test', 'hard', 'The new guideline, _______ was issued last month, requires additional borrower disclosures.', ['who', 'whom', 'whose', 'which'], 3, '"Which" is the correct relative pronoun to refer to a non-human antecedent like "guideline" in a non-restrictive clause.'),
  question('sbi-po-m2-en-009', 'Error spotting', 'medium', 'Identify the part with an error: (A) Neither of the two proposals / (B) were approved by / (C) the credit committee / (D) this quarter.', ['B', 'D', 'A', 'C'], 0, '"Neither" is singular and takes a singular verb, so it should be "was approved", not "were approved" — the error is in part B.'),
  question('sbi-po-m2-en-010', 'Error spotting', 'hard', 'Identify the part with an error: (A) The regulator, along with its regional offices, / (B) have issued / (C) a joint advisory / (D) on co-lending disclosures.', ['D', 'B', 'A', 'C'], 1, '"Along with" is a phrase, not a conjunction, so the verb should agree with the singular subject "the regulator": "has issued", not "have issued" — the error is in part B.'),
  question('sbi-po-m2-en-011', 'Sentence improvement', 'medium', 'Improve the underlined part: "The bank has announced that it will _partnering_ with an NBFC next quarter."', ['be partner', 'partnered', 'partner', 'partnering'], 2, 'After the modal "will", the base form of the verb is required: "will partner", not "will partnering".'),
  question('sbi-po-m2-en-012', 'Sentence improvement', 'medium', 'Improve the underlined part: "She is one of the analysts who _has_ consistently flagged the risk early."', ['has', 'having', 'had', 'have'], 3, '"One of the analysts who" takes a plural verb agreeing with "analysts" (the antecedent of "who"), so "have" is correct, not "has".'),
  question('sbi-po-m2-en-013', 'Para jumbles', 'hard', 'Arrange the sentences in logical order: P. This shift has forced smaller lenders to rethink their funding strategies. Q. Co-lending partnerships have grown rapidly over the past few years. R. Many have responded by seeking bank tie-ups of their own. S. As a result, more borrowers now access credit through joint funding structures.', ['QSPR', 'PQSR', 'QPRS', 'SQPR'], 0, 'The logical flow starts with the general trend (Q: co-lending growth), followed by its consequence (S: more borrowers accessing joint funding), then its impact on smaller lenders (P: forced to rethink strategies), and finally their response (R: seeking bank tie-ups): QSPR.'),
  question('sbi-po-m2-en-014', 'Para jumbles', 'hard', 'Arrange the sentences in logical order: P. This has led to increased scrutiny of loan disclosure practices. Q. Co-lending volumes have risen sharply this year. R. Regulators now have access to more detailed reporting than before. S. Authorities are eager to ensure borrowers understand who is funding their loan.', ['SQPR', 'QPSR', 'PQRS', 'QRPS'], 1, 'The order begins with the trend (Q: rising co-lending volumes), its consequence (P: increased scrutiny of disclosure), followed by the resulting effort (S: authorities ensuring borrower understanding), and finally the outcome (R: more detailed reporting): QPSR.'),
  question('sbi-po-m2-en-015', 'Fill in the blanks', 'medium', 'The auditor found several _______ in the co-lending agreement that required immediate clarification.', ['ambiguous', 'ambiguously', 'ambiguities', 'ambiguity'], 2, '"Several" requires a plural noun, and "ambiguities" (plural of ambiguity) correctly fits the sentence.'),
  question('sbi-po-m2-en-016', 'Fill in the blanks', 'medium', 'The revised disclosure norms will come into _______ from the first of next quarter.', ['affect', 'effective', 'affected', 'effect'], 3, '"Come into effect" is the correct idiomatic phrase meaning to become operative; "affect" is a verb, not used in this fixed expression.'),
  question('sbi-po-m2-en-017', 'Vocabulary in context', 'medium', 'The word "prudent" is closest in meaning to:', ['Wise and cautious in practical matters', 'Careless', 'Reckless', 'Indifferent'], 0, '"Prudent" means acting with or showing care and thought for the future, i.e., wise and cautious.'),
  question('sbi-po-m2-en-018', 'Vocabulary in context', 'medium', 'The word "transparent" is closest in meaning to:', ['Completely false', 'Open and easy to see through or understand', 'Hidden and unclear', 'Confidently stated'], 1, '"Transparent" means open, clear, and easy to perceive or understand, without concealment.'),
  question('sbi-po-m2-en-019', 'Vocabulary in context', 'hard', 'Choose the word most nearly OPPOSITE in meaning to "meticulous".', ['Precise', 'Thorough', 'Careless', 'Careful'], 2, '"Meticulous" means showing great attention to detail; its opposite is "careless", lacking attention or care.'),
  question('sbi-po-m2-en-020', 'One-word substitution', 'medium', 'A person who lends money, especially as a business, is called:', ['Debtor', 'Beneficiary', 'Trustee', 'Moneylender'], 3, 'A "moneylender" is a person or entity that lends money, especially as an ongoing business activity.'),
  question('sbi-po-m2-en-021', 'One-word substitution', 'medium', 'The act of making something known publicly, especially previously secret information, is called:', ['Disclosure', 'Speculation', 'Retraction', 'Concealment'], 0, '"Disclosure" refers to the act of making previously secret or private information known publicly.'),
  question('sbi-po-m2-en-022', 'Idioms and phrases', 'medium', 'What does the idiom "to foot the bill" mean?', ['To refuse a payment', 'To pay for something, especially an expense', 'To calculate a total', 'To walk to a meeting'], 1, '"To foot the bill" means to pay for something, typically an expense or cost incurred.'),
  question('sbi-po-m2-en-023', 'Idioms and phrases', 'hard', 'What does the idiom "to keep something under wraps" mean?', ['To finish a project quickly', 'To store documents safely', 'To keep something secret or hidden', 'To wrap a gift carefully'], 2, '"To keep something under wraps" means to keep it secret or hidden from others.'),
  question('sbi-po-m2-en-024', 'Sentence correction', 'hard', 'Choose the grammatically correct sentence.', ['Each of the borrowers have submitted their documents.', 'Each of the borrower have submit the documents.', 'Each of borrowers has submitted documents.', 'Each of the borrowers has submitted his or her documents.'], 3, '"Each" is singular and requires a singular verb ("has") and singular possessive pronoun ("his or her"), making the fourth option grammatically correct.'),
  question('sbi-po-m2-en-025', 'Sentence correction', 'medium', 'Identify the grammatically correct sentence.', ['Neither the bank nor the NBFCs were informed.', 'Neither the bank or the NBFCs were informed.', 'Neither bank nor NBFCs was informed.', 'Neither the bank nor the NBFCs was informed.'], 0, 'With "neither...nor", the verb agrees with the subject closer to it; since "NBFCs" (plural) is closer, the verb should be "were", making the second option correct.'),
  question('sbi-po-m2-en-026', 'Connectors', 'medium', 'The lender reported strong loan growth this quarter; _______, its provisioning costs also rose sharply.', ['therefore', 'moreover', 'nevertheless', 'consequently'], 1, '"Moreover" correctly adds a related, reinforcing point (rising provisioning costs alongside loan growth) rather than signalling contrast.'),
  question('sbi-po-m2-en-027', 'Connectors', 'medium', 'The regulator tightened disclosure norms _______ concerns about borrower awareness grew.', ['unless', 'whereas', 'because', 'although'], 2, '"Because" correctly introduces the reason (growing concerns about borrower awareness) for the regulator\'s action.'),
  question('sbi-po-m2-en-028', 'Reading comprehension', 'medium', RC_PASSAGE + 'According to the passage, where has co-lending genuinely expanded credit access?', ['Only in major metropolitan cities', 'Exclusively for large corporate borrowers', 'In countries outside India', 'In areas banks previously found too costly to serve directly'], 3, 'The passage states proponents argue the arrangement has genuinely expanded credit access in areas banks previously found too costly to serve directly.'),
  question('sbi-po-m2-en-029', 'Active and passive voice', 'medium', 'Choose the correct passive voice of: "The auditor reviewed the loan files."', ['The loan files were reviewed by the auditor.', 'The loan files had been reviewing by the auditor.', 'The loan files review by the auditor.', 'The loan files are reviewed by the auditor.'], 0, 'The original sentence is in simple past active voice, so the correct passive form is "The loan files were reviewed by the auditor."'),
  question('sbi-po-m2-en-030', 'Active and passive voice', 'hard', 'Choose the correct passive voice of: "They will implement the new disclosure norms next quarter."', ['The new disclosure norms were implemented next quarter.', 'The new disclosure norms will be implemented next quarter.', 'The new disclosure norms are implemented next quarter.', 'The new disclosure norms will implement next quarter.'], 1, 'The original sentence uses the future tense with "will", so the correct passive form retains that tense: "will be implemented".'),
  question('sbi-po-m2-en-031', 'Direct and indirect speech', 'medium', 'Convert to indirect speech: She said, "I will complete the audit by tomorrow."', ['She says that she would complete the audit tomorrow.', 'She said that she will complete the audit by tomorrow.', 'She said that she would complete the audit the next day.', 'She said that she completes the audit tomorrow.'], 2, 'In indirect speech, "will" changes to "would" and "tomorrow" changes to "the next day" when the reporting verb is in the past tense.'),
  question('sbi-po-m2-en-032', 'Direct and indirect speech', 'hard', 'Convert to indirect speech: He said, "I have reviewed the agreement."', ['He says that he reviewed the agreement.', 'He said that he reviews the agreement.', 'He said that he has reviewed the agreement.', 'He said that he had reviewed the agreement.'], 3, 'In indirect speech, present perfect ("have reviewed") changes to past perfect ("had reviewed") when the reporting verb is in the past tense.'),
  question('sbi-po-m2-en-033', 'Spelling', 'easy', 'Identify the correctly spelled word.', ['Receive', 'Recieve', 'Receeve', 'Receve'], 0, 'The correct spelling is "Receive", following the "i before e except after c" rule.'),
  question('sbi-po-m2-en-034', 'Spelling', 'easy', 'Select the word that is spelled correctly.', ['Priviledge', 'Privilege', 'Priviledg', 'Previlege'], 1, 'The correct spelling is "Privilege", with no "d" before the final "ge".'),
  question('sbi-po-m2-en-035', 'Word usage', 'hard', 'Choose the correct word to complete the sentence: "The revised norms will _______ affect smaller NBFCs more than larger ones."', ['effect', 'affect', 'effectively', 'affectively'], 2, '"Effectively" is an adverb modifying the verb "affect" (meaning "in an effective manner"), fitting grammatically before the verb.'),
  question('sbi-po-m2-en-036', 'Word usage', 'medium', 'Choose the correct word: "The two institutions decided to _______ their resources for the joint lending programme."', ['poll', 'pole', 'pull', 'pool'], 3, '"Pool" means to combine resources together, which fits the context of a joint programme; "poll" refers to voting, "pole" is a rod, and "pull" means to drag.'),
  question('sbi-po-m2-en-037', 'Reading comprehension', 'medium', RC_PASSAGE + 'What must both institutions remain, according to proponents in the passage?', ['Accountable for loan quality', 'Exempt from all regulation', 'Anonymous to the borrower', 'Independent of each other entirely'], 0, 'The passage states proponents argue both institutions must remain accountable for loan quality, which they consider more important than borrower-level disclosure.'),
  question('sbi-po-m2-en-038', 'Cloze test', 'medium', 'The board members _______ to revise the co-lending policy after new data emerged.', ['agree', 'agreed', 'agreeing', 'agreement'], 1, 'The sentence describes a completed past action, so the simple past tense "agreed" is correct.'),
  question('sbi-po-m2-en-039', 'Error spotting', 'medium', 'Identify the part with an error: (A) Each of the branch managers / (B) are required to submit / (C) their monthly compliance report / (D) by the fifth of every month.', ['D', 'A', 'B', 'C'], 2, '"Each" is singular and requires a singular verb, so it should be "is required", not "are required" — the error is in part B.'),
  question('sbi-po-m2-en-040', 'Sentence improvement', 'medium', 'Improve the underlined part: "The committee _decided_ to postponing the review until further notice."', ['decided to postponing', 'decided postponing', 'deciding to postpone', 'decided to postpone'], 3, '"Decided to" must be followed by the base form of the verb ("to postpone"), not the gerund ("postponing").'),
];
