import type { Question } from '../questions';

const SOURCE = {
  kind: 'original' as const,
  reference: 'TakeMockTest original practice aligned to the SBI PO 2026 Mains English Language section',
  url: 'https://sbi.bank.in/web/careers/current-openings',
  checkedOn: '26 August 2026',
};

const MARKS = 20 / 40;
const PENALTY = MARKS / 4;

function question(
  id: string,
  topic: string,
  difficulty: 'easy' | 'medium' | 'hard',
  prompt: string,
  options: string[],
  correctIndex: number,
  explanation: string,
): Question {
  return {
    id,
    section: 'English Language',
    topic,
    difficulty,
    question: prompt,
    options,
    correctIndex,
    marks: MARKS,
    negativeMarking: PENALTY,
    explanation,
    source: SOURCE,
  };
}

const RC_PASSAGE =
  'Digital banking has transformed how customers interact with financial institutions in India. What once required a visit to a branch and a lengthy queue can now be completed within minutes through a mobile application. However, this convenience has brought new challenges: cybersecurity threats have grown more sophisticated, and a segment of the population, particularly in rural areas, still lacks reliable internet access or the digital literacy needed to use these services confidently. Banks have responded by investing heavily in fraud-detection systems and by launching financial literacy campaigns aimed at bridging this digital divide. Industry experts argue that the next phase of banking transformation will depend less on adding new features and more on building trust: customers must feel confident that their money and data are safe before they fully embrace digital channels over traditional ones. ';

export const SBI_PO_MAINS_ENGLISH_1: Question[] = [
  question('sbi-po-m-en-001', 'Reading comprehension', 'medium', RC_PASSAGE + 'According to the passage, what has digital banking primarily replaced?', ['The need for financial literacy', 'Cybersecurity systems', 'Branch visits and long queues', 'Mobile applications'], 2, 'The passage states that what once required a branch visit and a lengthy queue can now be completed via a mobile app, indicating digital banking has replaced that process.'),
  question('sbi-po-m-en-002', 'Reading comprehension', 'medium', RC_PASSAGE + 'Which group does the passage identify as facing challenges with digital banking adoption?', ['Urban millennials', 'Bank employees', 'Rural populations lacking internet access or digital literacy', 'Cybersecurity experts'], 2, 'The passage specifically mentions that a segment of the population, particularly in rural areas, lacks reliable internet access or digital literacy.'),
  question('sbi-po-m-en-003', 'Reading comprehension', 'hard', RC_PASSAGE + 'What do industry experts believe will determine the next phase of banking transformation?', ['Adding more mobile app features', 'Reducing the number of physical branches', 'Building customer trust in safety and security', 'Increasing transaction fees'], 2, 'The passage states experts believe the next phase depends less on new features and more on building trust that money and data are safe.'),
  question('sbi-po-m-en-004', 'Reading comprehension', 'medium', RC_PASSAGE + 'How have banks responded to the digital divide mentioned in the passage?', ['By closing rural branches entirely', 'By increasing branch banking fees', 'By investing in fraud-detection systems and financial literacy campaigns', 'By ignoring rural customers'], 2, 'The passage states banks have responded by investing in fraud-detection systems and launching financial literacy campaigns to bridge the digital divide.'),
  question('sbi-po-m-en-005', 'Reading comprehension', 'hard', RC_PASSAGE + 'Which of the following best captures the overall tone of the passage?', ['Purely critical of digital banking', 'Dismissive of cybersecurity concerns', 'Balanced, acknowledging both benefits and challenges', 'Focused only on rural banking issues'], 2, 'The passage presents both the convenience digital banking offers and the genuine challenges it creates, reflecting a balanced tone rather than a one-sided view.'),
  question('sbi-po-m-en-006', 'Cloze test', 'medium', 'The committee has decided to _______ the proposal after considering all stakeholder feedback.', ['revising', 'revised', 'revision', 'revise'], 3, '"Decided to" is followed by the base form of the verb ("to revise"), making "revise" grammatically correct.'),
  question('sbi-po-m-en-007', 'Cloze test', 'medium', 'Despite the heavy rainfall, the shipment _______ on time.', ['arrive', 'arrives', 'arrived', 'arriving'], 2, 'The sentence describes a completed past event, so the simple past tense "arrived" is correct.'),
  question('sbi-po-m-en-008', 'Cloze test', 'hard', 'The new policy, _______ was announced last week, aims to improve customer service response times.', ['which', 'who', 'whom', 'whose'], 0, '"Which" is the correct relative pronoun to refer to a non-human antecedent like "policy" in a non-restrictive clause.'),
  question('sbi-po-m-en-009', 'Error spotting', 'medium', 'Identify the part with an error: (A) Neither of the two candidates / (B) were able to answer / (C) the interviewer\'s final question / (D) satisfactorily.', ['A', 'C', 'B', 'D'], 2, '"Neither" is singular and takes a singular verb, so it should be "was able to answer", not "were able to answer" — the error is in part B.'),
  question('sbi-po-m-en-010', 'Error spotting', 'hard', 'Identify the part with an error: (A) The manager, along with his team members, / (B) have completed / (C) the quarterly report / (D) ahead of schedule.', ['A', 'C', 'D', 'B'], 3, '"Along with" is a phrase, not a conjunction, so the verb should agree with the singular subject "the manager": "has completed", not "have completed" — the error is in part B.'),
  question('sbi-po-m-en-011', 'Sentence improvement', 'medium', 'Improve the underlined part: "The bank has announced that it will _launching_ a new savings scheme next month."', ['launching', 'be launch', 'launched', 'launch'], 3, 'After the modal "will", the base form of the verb is required: "will launch", not "will launching".'),
  question('sbi-po-m-en-012', 'Sentence improvement', 'medium', 'Improve the underlined part: "She is one of the employees who _has_ consistently exceeded their targets."', ['has', 'having', 'had', 'have'], 3, '"One of the employees who" takes a plural verb agreeing with "employees" (the antecedent of "who"), so "have" is correct, not "has".'),
  question('sbi-po-m-en-013', 'Para jumbles', 'hard', 'Arrange the sentences in logical order: P. This shift has forced traditional retailers to rethink their strategies. Q. E-commerce has grown rapidly over the past decade. R. Many have responded by building their own online platforms. S. As a result, more consumers now prefer shopping online over visiting physical stores.', ['QSPR', 'PQSR', 'QPRS', 'SQPR'], 0, 'The logical flow starts with the general trend (Q: e-commerce growth), followed by its consequence (S: consumers preferring online shopping), then its impact on retailers (P: forced to rethink), and finally their response (R: building online platforms): QSPR.'),
  question('sbi-po-m-en-014', 'Para jumbles', 'hard', 'Arrange the sentences in logical order: P. This has led to increased competition among lenders. Q. Interest rates on personal loans have fallen significantly this year. R. Borrowers now have access to more favourable terms than before. S. Banks are eager to attract customers with lower rates and flexible repayment options.', ['QPSR', 'PQRS', 'QRPS', 'SQPR'], 0, 'The order begins with the trend (Q: falling interest rates), its cause (P: increased competition), followed by the consequence for banks (S: eager to attract customers), and finally the benefit to borrowers (R: access to favourable terms): QPSR.'),
  question('sbi-po-m-en-015', 'Fill in the blanks', 'medium', 'The auditor found several _______ in the company\'s financial statements that required immediate correction.', ['discrepancies', 'discrepancy', 'discrepant', 'discrepantly'], 0, '"Several" requires a plural noun, and "discrepancies" (plural of discrepancy) correctly fits the sentence.'),
  question('sbi-po-m-en-016', 'Fill in the blanks', 'medium', 'The new regulations will come into _______ from the first of next month.', ['effect', 'affect', 'effective', 'affected'], 0, '"Come into effect" is the correct idiomatic phrase meaning to become operative; "affect" is a verb, not used in this fixed expression.'),
  question('sbi-po-m-en-017', 'Vocabulary in context', 'medium', 'The word "meticulous" is closest in meaning to:', ['Careless', 'Quick and hasty', 'Indifferent', 'Extremely careful and precise'], 3, '"Meticulous" means showing great attention to detail and being very careful and precise.'),
  question('sbi-po-m-en-018', 'Vocabulary in context', 'medium', 'The word "ambiguous" is closest in meaning to:', ['Clear and precise', 'Confidently stated', 'Completely false', 'Open to more than one interpretation'], 3, '"Ambiguous" means having more than one possible meaning or interpretation, causing uncertainty.'),
  question('sbi-po-m-en-019', 'Vocabulary in context', 'hard', 'Choose the word most nearly OPPOSITE in meaning to "reluctant".', ['Hesitant', 'Unwilling', 'Doubtful', 'Willing'], 3, '"Reluctant" means unwilling or hesitant; its opposite is "willing", indicating readiness to do something.'),
  question('sbi-po-m-en-020', 'One-word substitution', 'medium', 'A person who is unable to pay their debts is called:', ['Insolvent', 'Affluent', 'Frugal', 'Prudent'], 0, '"Insolvent" describes a person or entity unable to pay debts owed, matching the definition given.'),
  question('sbi-po-m-en-021', 'One-word substitution', 'medium', 'A statement that is deliberately vague or ambiguous, especially to deceive, is called:', ['Euphemism', 'Eulogy', 'Elocution', 'Equivocation'], 3, '"Equivocation" refers to the use of ambiguous language to conceal the truth or avoid committing to a definite meaning.'),
  question('sbi-po-m-en-022', 'Idioms and phrases', 'medium', 'What does the idiom "to cut corners" mean?', ['To take a shortcut, often sacrificing quality', 'To turn in a different direction', 'To reduce expenses drastically', 'To finish a task ahead of schedule'], 0, '"To cut corners" means to do something in the easiest or cheapest way, often at the expense of quality or thoroughness.'),
  question('sbi-po-m-en-023', 'Idioms and phrases', 'hard', 'What does the idiom "to read between the lines" mean?', ['To read a document very slowly', 'To skip over unimportant details', 'To read multiple documents at once', 'To understand the hidden or implied meaning'], 3, '"To read between the lines" means to understand the implied or hidden meaning of something, beyond what is explicitly stated.'),
  question('sbi-po-m-en-024', 'Sentence correction', 'hard', 'Choose the grammatically correct sentence.', ['Each of the applicants have submitted their documents.', 'Each of the applicant have submit the documents.', 'Each of applicants has submitted documents.', 'Each of the applicants has submitted his or her documents.'], 3, '"Each" is singular and requires a singular verb ("has") and singular possessive pronoun ("his or her"), making the second option grammatically correct.'),
  question('sbi-po-m-en-025', 'Sentence correction', 'medium', 'Identify the grammatically correct sentence.', ['Neither the manager nor the employees was informed.', 'Neither the manager nor the employees were informed.', 'Neither the manager or the employees were informed.', 'Neither manager nor employees was informed.'], 1, 'With "neither...nor", the verb agrees with the subject closer to it; since "employees" (plural) is closer, the verb should be "were", making the second option correct.'),
  question('sbi-po-m-en-026', 'Connectors', 'medium', 'The company reported strong quarterly earnings; _______, its stock price fell due to broader market concerns.', ['therefore', 'moreover', 'nevertheless', 'consequently'], 2, '"Nevertheless" correctly signals a contrast between the strong earnings and the unexpected fall in stock price.'),
  question('sbi-po-m-en-027', 'Connectors', 'medium', 'The bank increased its interest rates _______ inflation continued to rise.', ['because', 'although', 'unless', 'whereas'], 0, '"Because" correctly introduces the reason (rising inflation) for the bank\'s action (increasing rates).'),
  question('sbi-po-m-en-028', 'Reading comprehension', 'medium', RC_PASSAGE + 'Based on the passage, cybersecurity threats are described as:', ['Declining in sophistication', 'Growing more sophisticated', 'Completely eliminated by banks', 'Irrelevant to digital banking'], 1, 'The passage explicitly states that cybersecurity threats have grown more sophisticated alongside the rise of digital banking.'),
  question('sbi-po-m-en-029', 'Active and passive voice', 'medium', 'Choose the correct passive voice of: "The auditor reviewed the accounts."', ['The accounts are reviewed by the auditor.', 'The accounts were reviewed by the auditor.', 'The accounts had been reviewing by the auditor.', 'The accounts review by the auditor.'], 1, 'The original sentence is in simple past active voice, so the correct passive form is "The accounts were reviewed by the auditor."'),
  question('sbi-po-m-en-030', 'Active and passive voice', 'hard', 'Choose the correct passive voice of: "They will implement the new system next quarter."', ['The new system will be implemented next quarter.', 'The new system is implemented next quarter.', 'The new system will implement next quarter.', 'The new system was implemented next quarter.'], 0, 'The original sentence uses the future tense with "will", so the correct passive form retains that tense: "will be implemented".'),
  question('sbi-po-m-en-031', 'Direct and indirect speech', 'medium', 'Convert to indirect speech: She said, "I will complete the report by tomorrow."', ['She said that she will complete the report by tomorrow.', 'She said that she would complete the report the next day.', 'She said that she completes the report tomorrow.', 'She says that she would complete the report tomorrow.'], 1, 'In indirect speech, "will" changes to "would" and "tomorrow" changes to "the next day" when the reporting verb is in the past tense.'),
  question('sbi-po-m-en-032', 'Direct and indirect speech', 'hard', 'Convert to indirect speech: He said, "I have finished my work."', ['He said that he has finished his work.', 'He said that he had finished his work.', 'He says that he finished his work.', 'He said that he finishes his work.'], 1, 'In indirect speech, present perfect ("have finished") changes to past perfect ("had finished") when the reporting verb is in the past tense.'),
  question('sbi-po-m-en-033', 'Spelling', 'easy', 'Identify the correctly spelled word.', ['Accomodate', 'Accommodate', 'Acommodate', 'Accommadate'], 1, 'The correct spelling is "Accommodate", with double "c" and double "m".'),
  question('sbi-po-m-en-034', 'Spelling', 'easy', 'Select the word that is spelled correctly.', ['Occassion', 'Ocassion', 'Occasion', 'Occassionn'], 2, 'The correct spelling is "Occasion", with double "c" and a single "s".'),
  question('sbi-po-m-en-035', 'Word usage', 'hard', 'Choose the correct word to complete the sentence: "The new regulation will _______ affect small businesses more than large corporations."', ['effect', 'affect', 'effectively', 'affectively'], 2, '"Effectively" is an adverb modifying the verb "affect" (meaning "in an effective manner"), fitting grammatically before the verb.'),
  question('sbi-po-m-en-036', 'Word usage', 'medium', 'Choose the correct word: "The two companies decided to _______ their resources for the joint venture."', ['pool', 'poll', 'pole', 'pull'], 0, '"Pool" means to combine resources together, which fits the context of a joint venture; "poll" refers to voting, "pole" is a rod, and "pull" means to drag.'),
  question('sbi-po-m-en-037', 'Reading comprehension', 'medium', RC_PASSAGE + 'What must customers feel before fully embracing digital banking, according to the passage?', ['That digital banking is free of charge', 'That their money and data are safe', 'That branches will remain open', 'That mobile apps are entertaining'], 1, 'The passage states customers must feel confident their money and data are safe before fully embracing digital channels.'),
  question('sbi-po-m-en-038', 'Cloze test', 'medium', 'The board members _______ to reconsider the merger proposal after new financial data emerged.', ['agree', 'agreed', 'agreeing', 'agreement'], 1, 'The sentence describes a completed past action, so the simple past tense "agreed" is correct.'),
  question('sbi-po-m-en-039', 'Error spotting', 'medium', 'Identify the part with an error: (A) Each of the branch managers / (B) are required to submit / (C) their monthly performance report / (D) by the fifth of every month.', ['A', 'B', 'C', 'D'], 1, '"Each" is singular and requires a singular verb, so it should be "is required", not "are required" — the error is in part B.'),
  question('sbi-po-m-en-040', 'Sentence improvement', 'medium', 'Improve the underlined part: "The committee _decided_ to postponing the meeting until further notice."', ['decided to postponing', 'decided to postpone', 'decided postponing', 'deciding to postpone'], 1, '"Decided to" must be followed by the base form of the verb ("to postpone"), not the gerund ("postponing").'),
];
