import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SBI Junior Associate (Customer Support & Sales) 2025-26 official advertisement (CRPD/CR/2025-26/06) — Mains, Reasoning Ability & Computer Aptitude section',
  url: 'https://sbi.bank.in/documents/77530/52947104/JA+2025+-Detailed+Advt.pdf',
  checkedOn: '27 August 2026',
};

const SEATING_PUZZLE =
  'Five friends A, B, C, D, and E are sitting in a row facing north, not necessarily in that order. C sits second to the left of E. B sits immediate right of C. A sits at one of the extreme ends. D sits immediate left of A.\n\n';

const BOX_PUZZLE =
  'Five boxes P, Q, R, S, and T are stacked one above another, not necessarily in that order. R is at the bottom. Q is just above R. P is above Q. S is just above T. Exactly one box is between P and T.\n\n';

export const SBI_CLERK_MAINS_REASONING_COMPUTER_APTITUDE_1: Question[] = [
  { id: 'sbi-clerk-m1-rc-001', section: 'Reasoning Ability & Computer Aptitude', topic: 'Seating arrangement', difficulty: 'hard', question: `${SEATING_PUZZLE}Who sits at the middle (3rd from the left) position?`, options: ['E', 'B', 'C', 'D'], correctIndex: 0, marks: 1.2, negativeMarking: 0.3, explanation: 'Since A is at an extreme end and D is immediately left of A, A=5th, D=4th. From "C second to left of E" and "B immediate right of C", the only arrangement fitting positions 1-3 is C=1, B=2, E=3. So the order is C, B, E, D, A — E is at the middle.', source },
  { id: 'sbi-clerk-m1-rc-002', section: 'Reasoning Ability & Computer Aptitude', topic: 'Seating arrangement', difficulty: 'hard', question: `${SEATING_PUZZLE}Who sits immediately left of D?`, options: ['E', 'B', 'C', 'A'], correctIndex: 0, marks: 1.2, negativeMarking: 0.3, explanation: 'The final order is C, B, E, D, A. E (3rd position) sits immediately left of D (4th position).', source },
  { id: 'sbi-clerk-m1-rc-003', section: 'Reasoning Ability & Computer Aptitude', topic: 'Seating arrangement', difficulty: 'hard', question: `${SEATING_PUZZLE}How many people sit between B and A?`, options: ['2', '1', '3', '0'], correctIndex: 0, marks: 1.2, negativeMarking: 0.3, explanation: 'The final order is C, B, E, D, A. B is at position 2 and A is at position 5, so E and D (positions 3 and 4) sit between them — 2 people.', source },
  { id: 'sbi-clerk-m1-rc-004', section: 'Reasoning Ability & Computer Aptitude', topic: 'Seating arrangement', difficulty: 'medium', question: `${SEATING_PUZZLE}Who sits at the extreme left end?`, options: ['C', 'B', 'E', 'D'], correctIndex: 0, marks: 1.2, negativeMarking: 0.3, explanation: 'The final order is C, B, E, D, A. C is at position 1, the extreme left end.', source },
  { id: 'sbi-clerk-m1-rc-005', section: 'Reasoning Ability & Computer Aptitude', topic: 'Box-based puzzle', difficulty: 'hard', question: `${BOX_PUZZLE}Which box is at the top of the stack?`, options: ['P', 'S', 'T', 'Q'], correctIndex: 0, marks: 1.2, negativeMarking: 0.3, explanation: 'With R at the bottom (5th) and Q just above it (4th), P must be above Q, occupying one of positions 1-3. Testing S-T as consecutive pairs within positions 1-3, only S=2, T=3, P=1 satisfies "exactly one box between P and T" (S sits between them). So from top: P, S, T, Q, R — P is at the top.', source },
  { id: 'sbi-clerk-m1-rc-006', section: 'Reasoning Ability & Computer Aptitude', topic: 'Box-based puzzle', difficulty: 'hard', question: `${BOX_PUZZLE}Which box is immediately below S?`, options: ['T', 'Q', 'R', 'P'], correctIndex: 0, marks: 1.2, negativeMarking: 0.3, explanation: 'The stack from top to bottom is P, S, T, Q, R. T is immediately below S.', source },
  { id: 'sbi-clerk-m1-rc-007', section: 'Reasoning Ability & Computer Aptitude', topic: 'Syllogism', difficulty: 'medium', question: 'Statements: All keys are locks. No lock is a door. Conclusions: I. No key is a door. II. Some locks are keys. Which conclusion(s) follow?', options: ['Both I and II follow', 'Only I follows', 'Only II follows', 'Neither follows'], correctIndex: 0, marks: 1.2, negativeMarking: 0.3, explanation: 'Since all keys are locks and no lock is a door, no key can be a door (I follows). Since keys exist within locks, some locks are keys (II follows).', source },
  { id: 'sbi-clerk-m1-rc-008', section: 'Reasoning Ability & Computer Aptitude', topic: 'Syllogism', difficulty: 'medium', question: 'Statements: Some pens are pencils. No pencil is an eraser. Conclusions: I. No pen is an eraser. II. Some pens are not erasers. Which conclusion(s) follow?', options: ['Only II follows', 'Only I follows', 'Both follow', 'Neither follows'], correctIndex: 0, marks: 1.2, negativeMarking: 0.3, explanation: 'Since some pens are pencils and no pencil is an eraser, those particular pens are not erasers, so "some pens are not erasers" (II) follows. It cannot be concluded that no pen at all is an eraser (I), since other pens outside the pencil group are unaccounted for.', source },
  { id: 'sbi-clerk-m1-rc-009', section: 'Reasoning Ability & Computer Aptitude', topic: 'Syllogism', difficulty: 'medium', question: 'Statements: All squares are rectangles. All rectangles are quadrilaterals. Conclusions: I. All squares are quadrilaterals. II. Some quadrilaterals are squares. Which conclusion(s) follow?', options: ['Both I and II follow', 'Only I follows', 'Only II follows', 'Neither follows'], correctIndex: 0, marks: 1.2, negativeMarking: 0.3, explanation: 'Since squares are a subset of rectangles, which are a subset of quadrilaterals, all squares are quadrilaterals (I follows), and since squares exist within quadrilaterals, some quadrilaterals are squares (II follows).', source },
  { id: 'sbi-clerk-m1-rc-010', section: 'Reasoning Ability & Computer Aptitude', topic: 'Syllogism', difficulty: 'hard', question: 'Statements: No mobile is a laptop. Some laptops are tablets. Conclusions: I. No mobile is a tablet. II. Some tablets are not mobiles. Which conclusion(s) follow?', options: ['Only II follows', 'Only I follows', 'Both follow', 'Neither follows'], correctIndex: 0, marks: 1.2, negativeMarking: 0.3, explanation: 'Since some laptops are tablets and no mobile is a laptop, those particular tablets are not mobiles, so "some tablets are not mobiles" (II) follows. It cannot be concluded that no tablet at all is a mobile (I), since tablets outside the laptop group are unaccounted for.', source },
  { id: 'sbi-clerk-m1-rc-011', section: 'Reasoning Ability & Computer Aptitude', topic: 'Blood relations', difficulty: 'hard', question: 'Pointing to a man, a woman said, "His mother is the only daughter of my father." How is the woman related to the man?', options: ['Mother', 'Sister', 'Aunt', 'Daughter'], correctIndex: 0, marks: 1.2, negativeMarking: 0.3, explanation: "The only daughter of the woman's father is the woman herself. So the man's mother is the woman, meaning the woman is the man's mother.", source },
  { id: 'sbi-clerk-m1-rc-012', section: 'Reasoning Ability & Computer Aptitude', topic: 'Blood relations', difficulty: 'hard', question: 'A is the son of B, who is male. C is the sister of A. D is the mother of C. How is D related to B?', options: ['Wife', 'Mother', 'Sister', 'Daughter'], correctIndex: 0, marks: 1.2, negativeMarking: 0.3, explanation: 'D is the mother of C, and since C is the sister of A, D is also the mother of A. Since B (male) is also stated to be A\'s parent, B must be A\'s father, making D his wife.', source },
  { id: 'sbi-clerk-m1-rc-013', section: 'Reasoning Ability & Computer Aptitude', topic: 'Blood relations', difficulty: 'medium', question: 'Introducing a boy, a girl said, "He is the son of the brother of my mother." How is the boy related to the girl?', options: ['Cousin', 'Brother', 'Nephew', 'Uncle'], correctIndex: 0, marks: 1.2, negativeMarking: 0.3, explanation: "The brother of the girl's mother is her maternal uncle. The son of her maternal uncle is her cousin.", source },
  { id: 'sbi-clerk-m1-rc-014', section: 'Reasoning Ability & Computer Aptitude', topic: 'Direction sense', difficulty: 'medium', question: 'A man walks 8 km towards South, then turns left and walks 6 km, then turns left again and walks 8 km. How far is he from his starting point, and in which direction?', options: ['6 km, West', '6 km, East', '8 km, East', '10 km, East'], correctIndex: 1, marks: 1.2, negativeMarking: 0.3, explanation: 'South 8 km, then East 6 km (turn left from South faces East), then North 8 km (turn left from East faces North). The North and South legs cancel, leaving him 6 km East of the start.', source },
  { id: 'sbi-clerk-m1-rc-015', section: 'Reasoning Ability & Computer Aptitude', topic: 'Direction sense', difficulty: 'hard', question: 'Point A is 10 km west of point B. Point C is 24 km south of point A. Find the distance between B and C.', options: ['24 km', '28 km', '22 km', '26 km'], correctIndex: 3, marks: 1.2, negativeMarking: 0.3, explanation: 'B to A (10 km) and A to C (24 km) form a right angle. Distance BC = √(10² + 24²) = √676 = 26 km.', source },
  { id: 'sbi-clerk-m1-rc-016', section: 'Reasoning Ability & Computer Aptitude', topic: 'Direction sense', difficulty: 'medium', question: 'Ravi starts from home and walks 5 km North, then turns right and walks 5 km, then turns right again and walks 5 km, then turns right again and walks 5 km. How far is he from his home now?', options: ['5 km', '10 km', '0 km', '20 km'], correctIndex: 2, marks: 1.2, negativeMarking: 0.3, explanation: 'North 5 km, East 5 km, South 5 km, West 5 km — this traces a complete square, bringing him back to the starting point, 0 km away.', source },
  { id: 'sbi-clerk-m1-rc-017', section: 'Reasoning Ability & Computer Aptitude', topic: 'Coding-decoding', difficulty: 'medium', question: "If in a certain code, 'BANK' is written as 'CBOL' (each letter shifted one place forward), how is 'LOAN' written in the same code?", options: ['MPBN', 'MPBO', 'MPCO', 'LPBO'], correctIndex: 1, marks: 1.2, negativeMarking: 0.3, explanation: 'Shifting each letter forward by one: L→M, O→P, A→B, N→O, giving MPBO.', source },
  { id: 'sbi-clerk-m1-rc-018', section: 'Reasoning Ability & Computer Aptitude', topic: 'Coding-decoding', difficulty: 'medium', question: "In a certain code, MOUSE is written as NPVTF (each letter shifted one place forward). How is TIGER written in the same code?", options: ['UJHFR', 'UIHFS', 'UJGFS', 'UJHFS'], correctIndex: 3, marks: 1.2, negativeMarking: 0.3, explanation: 'Shifting each letter forward by one: T→U, I→J, G→H, E→F, R→S, giving UJHFS.', source },
  { id: 'sbi-clerk-m1-rc-019', section: 'Reasoning Ability & Computer Aptitude', topic: 'Coding-decoding', difficulty: 'medium', question: "If P is coded as 16, Q as 17, and R as 18 (using each letter's position in the alphabet), what is the code for the word 'CAT'?", options: ['3-1-19', '2-1-20', '3-1-20', '3-2-20'], correctIndex: 2, marks: 1.2, negativeMarking: 0.3, explanation: 'C=3, A=1, T=20, giving the code 3-1-20.', source },
  { id: 'sbi-clerk-m1-rc-020', section: 'Reasoning Ability & Computer Aptitude', topic: 'Coding-decoding', difficulty: 'hard', question: "In a code, 'GARDEN' is written as 'FZQCDM' (each letter shifted one place backward). How is 'FLOWER' written in the same code?", options: ['EKNVDP', 'EKNVDQ', 'ELNVDQ', 'EKMVDQ'], correctIndex: 1, marks: 1.2, negativeMarking: 0.3, explanation: 'Shifting each letter backward by one: F→E, L→K, O→N, W→V, E→D, R→Q, giving EKNVDQ.', source },
  { id: 'sbi-clerk-m1-rc-021', section: 'Reasoning Ability & Computer Aptitude', topic: 'Inequality', difficulty: 'medium', question: 'Statements: A > B ≥ C = D > E. Conclusions: I. A > D  II. B > E. Which conclusion(s) follow?', options: ['Only I follows', 'Only II follows', 'Neither follows', 'Both I and II follow'], correctIndex: 3, marks: 1.2, negativeMarking: 0.3, explanation: 'Since A > B ≥ C = D, it follows that A > D (I). Since B ≥ C = D > E, it follows that B > E (II).', source },
  { id: 'sbi-clerk-m1-rc-022', section: 'Reasoning Ability & Computer Aptitude', topic: 'Inequality', difficulty: 'hard', question: 'Statements: P ≥ Q > R ≥ S. Conclusions: I. P > S  II. S ≥ P. Which conclusion(s) follow?', options: ['Only II follows', 'Both follow', 'Only I follows', 'Neither follows'], correctIndex: 2, marks: 1.2, negativeMarking: 0.3, explanation: 'The chain P ≥ Q > R ≥ S contains a strict inequality (Q > R), so P > S follows (I). Since P > S is established, S ≥ P is false (II does not follow).', source },
  { id: 'sbi-clerk-m1-rc-023', section: 'Reasoning Ability & Computer Aptitude', topic: 'Inequality', difficulty: 'hard', question: 'Statements: X < Y ≤ Z < W. Conclusions: I. Z ≤ X  II. W > X. Which conclusion(s) follow?', options: ['Only I follows', 'Only II follows', 'Both follow', 'Neither follows'], correctIndex: 1, marks: 1.2, negativeMarking: 0.3, explanation: 'Since X < Y ≤ Z, X < Z, so "Z ≤ X" (I) is false. Since X < Y ≤ Z < W, transitively X < W, so "W > X" (II) follows.', source },
  { id: 'sbi-clerk-m1-rc-024', section: 'Reasoning Ability & Computer Aptitude', topic: 'Alphanumeric series', difficulty: 'hard', question: 'Complete the series: B2, D8, F18, H32, ?', options: ['J48', 'K50', 'J52', 'J50'], correctIndex: 3, marks: 1.2, negativeMarking: 0.3, explanation: 'The letters skip one each time (B, D, F, H, J). The numbers follow 2n² for n=1,2,3,4,5: 2, 8, 18, 32, 50. Next term: J50.', source },
  { id: 'sbi-clerk-m1-rc-025', section: 'Reasoning Ability & Computer Aptitude', topic: 'Alphanumeric series', difficulty: 'hard', question: 'Find the missing term: 3F9, 6K16, 9P25, 12U36, ?', options: ['15Y49', '15Z48', '15Z49', '16Z49'], correctIndex: 2, marks: 1.2, negativeMarking: 0.3, explanation: 'The leading numbers increase by 3 (3,6,9,12,15). The letters skip 4 each time (F,K,P,U,Z). The trailing numbers are perfect squares (9,16,25,36,49). Next term: 15Z49.', source },
  { id: 'sbi-clerk-m1-rc-026', section: 'Reasoning Ability & Computer Aptitude', topic: 'Alphanumeric series', difficulty: 'medium', question: "In the word 'PRODUCTIVE', how many letters are there between the 3rd letter from the left and the 3rd letter from the right, as they appear in the word?", options: ['3', '4', '5', '6'], correctIndex: 1, marks: 1.2, negativeMarking: 0.3, explanation: "The word has 10 letters. The 3rd from the left is 'O' (position 3), and the 3rd from the right is 'I' (position 8). The letters between positions 4 and 7 (D, U, C, T) total 4.", source },
  { id: 'sbi-clerk-m1-rc-027', section: 'Reasoning Ability & Computer Aptitude', topic: 'Alphanumeric series', difficulty: 'medium', question: "If the letters of the word 'CADET' are arranged in alphabetical order, how many letters remain in the same position as in the original word?", options: ['2', '4', '1', '3'], correctIndex: 3, marks: 1.2, negativeMarking: 0.3, explanation: "Original: C-A-D-E-T. Alphabetical order: A-C-D-E-T. Comparing position by position, D, E, and T remain in the same position (positions 3, 4, and 5) — 3 letters.", source },
  { id: 'sbi-clerk-m1-rc-028', section: 'Reasoning Ability & Computer Aptitude', topic: 'Alphanumeric series', difficulty: 'medium', question: 'Find the missing term: Z25, X22, V19, T16, ?', options: ['R12', 'S13', 'R13', 'R14'], correctIndex: 2, marks: 1.2, negativeMarking: 0.3, explanation: 'The letters move backward by 2 each time (Z, X, V, T, R). The numbers decrease by 3 each time (25, 22, 19, 16, 13). Next term: R13.', source },
  { id: 'sbi-clerk-m1-rc-029', section: 'Reasoning Ability & Computer Aptitude', topic: 'Data sufficiency', difficulty: 'medium', question: "What is the age of Ravi? Statement I: Ravi is 5 years older than his brother. Statement II: Ravi's brother is 20 years old. Which statement(s) are sufficient to answer the question?", options: ['Statement I alone is sufficient', 'Both I and II together are necessary', 'Statement II alone is sufficient', 'Either I or II alone is sufficient'], correctIndex: 1, marks: 1.2, negativeMarking: 0.3, explanation: "Statement I alone gives only a relative age difference, not an actual age. Statement II alone gives the brother's age but not Ravi's. Combined, Ravi's age = 20 + 5 = 25, so both are needed together.", source },
  { id: 'sbi-clerk-m1-rc-030', section: 'Reasoning Ability & Computer Aptitude', topic: 'Data sufficiency', difficulty: 'medium', question: 'Is x an even number? Statement I: x is divisible by 4. Statement II: x is divisible by 2. Which statement(s) are sufficient to answer the question?', options: ['Only I is sufficient', 'Only II is sufficient', 'Both together are necessary', 'Either I or II alone is sufficient'], correctIndex: 3, marks: 1.2, negativeMarking: 0.3, explanation: 'If x is divisible by 4, it must be even (Statement I alone is sufficient). If x is divisible by 2, it is even by definition (Statement II alone is sufficient). So either statement alone answers the question.', source },
  { id: 'sbi-clerk-m1-rc-031', section: 'Reasoning Ability & Computer Aptitude', topic: 'Data sufficiency', difficulty: 'medium', question: 'What is the profit percentage on an article? Statement I: The cost price of the article is ₹500. Statement II: The article was sold at ₹600. Which statement(s) are sufficient to answer the question?', options: ['Statement I alone is sufficient', 'Statement II alone is sufficient', 'Both I and II together are necessary', 'Either alone is sufficient'], correctIndex: 2, marks: 1.2, negativeMarking: 0.3, explanation: 'Statement I alone gives only the cost price, and Statement II alone gives only the selling price; neither alone can determine profit percentage. Combined, profit % = ((600−500)/500) × 100 = 20%.', source },
  { id: 'sbi-clerk-m1-rc-032', section: 'Reasoning Ability & Computer Aptitude', topic: 'Ranking and order', difficulty: 'medium', question: 'In a class of 45 students, Neha ranks 18th from the top. What is her rank from the bottom?', options: ['27th', '28th', '29th', '26th'], correctIndex: 1, marks: 1.2, negativeMarking: 0.3, explanation: 'Rank from bottom = total students − rank from top + 1 = 45 − 18 + 1 = 28th.', source },
  { id: 'sbi-clerk-m1-rc-033', section: 'Reasoning Ability & Computer Aptitude', topic: 'Ranking and order', difficulty: 'medium', question: 'Rohit is 8th from the left and 15th from the right in a row of students. How many students are there in the row?', options: ['21', '23', '20', '22'], correctIndex: 3, marks: 1.2, negativeMarking: 0.3, explanation: 'Total students = (position from left) + (position from right) − 1 = 8 + 15 − 1 = 22.', source },
  { id: 'sbi-clerk-m1-rc-034', section: 'Reasoning Ability & Computer Aptitude', topic: 'Statement and conclusion', difficulty: 'medium', question: 'Statement: "All employees must complete the training module before the deadline." Assumptions: I. Some employees may not have completed the module without this instruction. II. The training module is mandatory for all employees. Which assumption(s) is/are implicit?', options: ['Only I is implicit', 'Only II is implicit', 'Both I and II are implicit', 'Neither is implicit'], correctIndex: 2, marks: 1.2, negativeMarking: 0.3, explanation: 'The instruction implies that some employees might not otherwise complete the module (I), and it directly restates that completion is mandatory for all (II). Both are implicit.', source },
  { id: 'sbi-clerk-m1-rc-035', section: 'Reasoning Ability & Computer Aptitude', topic: 'Statement and conclusion', difficulty: 'medium', question: 'Statement: "Customers are advised to carry a valid ID proof while visiting the branch." Assumptions: I. Some customers may not carry ID proof without this advisory. II. ID proof verification is part of the branch\'s process. Which assumption(s) is/are implicit?', options: ['Only I is implicit', 'Both I and II are implicit', 'Only II is implicit', 'Neither is implicit'], correctIndex: 1, marks: 1.2, negativeMarking: 0.3, explanation: 'The advisory implies that some customers might not otherwise carry ID proof (I), and its purpose implies that ID verification is part of the branch process (II). Both are implicit.', source },
  { id: 'sbi-clerk-m1-rc-036', section: 'Reasoning Ability & Computer Aptitude', topic: 'Computer fundamentals', difficulty: 'easy', question: 'Which of the following is a volatile memory?', options: ['ROM', 'Hard disk', 'SSD', 'RAM'], correctIndex: 3, marks: 1.2, negativeMarking: 0.3, explanation: 'RAM (Random Access Memory) is volatile, losing its data when power is switched off, unlike ROM, hard disks, and SSDs.', source },
  { id: 'sbi-clerk-m1-rc-037', section: 'Reasoning Ability & Computer Aptitude', topic: 'Networking', difficulty: 'medium', question: "What is the full form of 'LAN'?", options: ['Large Area Network', 'Local Access Network', 'Local Area Network', 'Linked Area Network'], correctIndex: 2, marks: 1.2, negativeMarking: 0.3, explanation: 'LAN stands for Local Area Network, a network confined to a small geographic area such as an office or building.', source },
  { id: 'sbi-clerk-m1-rc-038', section: 'Reasoning Ability & Computer Aptitude', topic: 'Internet protocols', difficulty: 'medium', question: 'Which protocol is primarily used to send emails?', options: ['HTTP', 'SMTP', 'FTP', 'SNMP'], correctIndex: 1, marks: 1.2, negativeMarking: 0.3, explanation: 'SMTP (Simple Mail Transfer Protocol) is the standard protocol used for sending emails.', source },
  { id: 'sbi-clerk-m1-rc-039', section: 'Reasoning Ability & Computer Aptitude', topic: 'Software', difficulty: 'medium', question: 'Which of the following is an example of system software?', options: ['MS Excel', 'Photoshop', 'Tally', 'Operating System'], correctIndex: 3, marks: 1.2, negativeMarking: 0.3, explanation: 'An Operating System is system software that manages hardware and provides a platform for application software to run; the others are application software.', source },
  { id: 'sbi-clerk-m1-rc-040', section: 'Reasoning Ability & Computer Aptitude', topic: 'Networking', difficulty: 'medium', question: "What does 'IP' stand for in networking?", options: ['Internal Protocol', 'Information Protocol', 'Internet Protocol', 'Internet Process'], correctIndex: 2, marks: 1.2, negativeMarking: 0.3, explanation: 'IP stands for Internet Protocol, the set of rules governing how data is addressed and routed across networks.', source },
  { id: 'sbi-clerk-m1-rc-041', section: 'Reasoning Ability & Computer Aptitude', topic: 'MS Office', difficulty: 'easy', question: 'Which shortcut key is used to open a new document in MS Word?', options: ['Ctrl + O', 'Ctrl + N', 'Ctrl + S', 'Ctrl + P'], correctIndex: 1, marks: 1.2, negativeMarking: 0.3, explanation: 'Ctrl + N is the standard shortcut for creating a new document in MS Word.', source },
  { id: 'sbi-clerk-m1-rc-042', section: 'Reasoning Ability & Computer Aptitude', topic: 'Computer security', difficulty: 'medium', question: 'What is the primary function of a firewall?', options: ['To increase internet speed', 'To compress files', 'To design web pages', 'To monitor and control network traffic based on security rules'], correctIndex: 3, marks: 1.2, negativeMarking: 0.3, explanation: 'A firewall monitors and controls incoming and outgoing network traffic based on predetermined security rules.', source },
  { id: 'sbi-clerk-m1-rc-043', section: 'Reasoning Ability & Computer Aptitude', topic: 'Hardware', difficulty: 'medium', question: 'Which of the following devices converts digital signals to analog and vice versa for internet connectivity?', options: ['Router', 'Switch', 'Modem', 'Hub'], correctIndex: 2, marks: 1.2, negativeMarking: 0.3, explanation: 'A modem (modulator-demodulator) converts digital signals to analog for transmission and back to digital for the receiving device.', source },
  { id: 'sbi-clerk-m1-rc-044', section: 'Reasoning Ability & Computer Aptitude', topic: 'Number systems', difficulty: 'medium', question: 'Which number system is used internally by computers to represent data?', options: ['Decimal', 'Binary', 'Octal', 'Hexadecimal'], correctIndex: 1, marks: 1.2, negativeMarking: 0.3, explanation: 'Computers internally represent and process data using the binary (base-2) number system.', source },
  { id: 'sbi-clerk-m1-rc-045', section: 'Reasoning Ability & Computer Aptitude', topic: 'Computer security', difficulty: 'medium', question: 'Which of the following spreads across a network without needing to attach itself to a host program?', options: ['Virus', 'Trojan', 'Spyware', 'Worm'], correctIndex: 3, marks: 1.2, negativeMarking: 0.3, explanation: 'A worm is a self-replicating malicious program that spreads across networks independently, unlike a virus, which needs to attach to a host program.', source },
  { id: 'sbi-clerk-m1-rc-046', section: 'Reasoning Ability & Computer Aptitude', topic: 'Computer fundamentals', difficulty: 'easy', question: "What does 'GUI' stand for?", options: ['General User Interface', 'Graphic Utility Interface', 'Graphical User Interface', 'Global User Interface'], correctIndex: 2, marks: 1.2, negativeMarking: 0.3, explanation: 'GUI stands for Graphical User Interface, a visual way of interacting with a computer using icons and menus.', source },
  { id: 'sbi-clerk-m1-rc-047', section: 'Reasoning Ability & Computer Aptitude', topic: 'MS Office', difficulty: 'easy', question: 'In MS Excel, which function is used to add a range of numbers?', options: ['ADD', 'SUM', 'TOTAL', 'PLUS'], correctIndex: 1, marks: 1.2, negativeMarking: 0.3, explanation: 'The SUM function is used in MS Excel to add up a range of numbers.', source },
  { id: 'sbi-clerk-m1-rc-048', section: 'Reasoning Ability & Computer Aptitude', topic: 'Operating systems', difficulty: 'easy', question: 'Which of the following is NOT an example of an operating system?', options: ['Windows', 'Linux', 'macOS', 'MS Word'], correctIndex: 3, marks: 1.2, negativeMarking: 0.3, explanation: 'MS Word is application software, not an operating system; Windows, Linux, and macOS are all operating systems.', source },
  { id: 'sbi-clerk-m1-rc-049', section: 'Reasoning Ability & Computer Aptitude', topic: 'Computer fundamentals', difficulty: 'easy', question: 'What is the standard file extension for a PDF document?', options: ['.doc', '.txt', '.pdf', '.exe'], correctIndex: 2, marks: 1.2, negativeMarking: 0.3, explanation: 'The standard file extension for a PDF (Portable Document Format) file is .pdf.', source },
  { id: 'sbi-clerk-m1-rc-050', section: 'Reasoning Ability & Computer Aptitude', topic: 'Computer fundamentals', difficulty: 'medium', question: 'Which key combination is used to permanently delete a file without sending it to the Recycle Bin in Windows?', options: ['Ctrl + Delete', 'Shift + Delete', 'Alt + Delete', 'Delete'], correctIndex: 1, marks: 1.2, negativeMarking: 0.3, explanation: 'Shift + Delete permanently deletes a file in Windows, bypassing the Recycle Bin.', source },
];
