import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SEBI Officer Grade A (Assistant Manager) Recruitment 2025 official notification — Phase II, Paper 2, General Stream (Management, deeper/analytical tier)',
  url: 'https://www.sebi.gov.in/sebi_data/careerfiles/oct-2025/1761782417659.pdf',
  checkedOn: '27 August 2026',
};

export const SEBI_GRADE_A_PHASE_2_PAPER_2_MANAGEMENT_1: Question[] = [
  { id: 'sebi-ph2-p2-mgmt-001', section: 'Management', topic: 'BCG Matrix', difficulty: 'hard', question: 'In the Boston Consulting Group (BCG) Growth-Share Matrix, a business unit with a high market share in a high-growth market is classified as a:', options: ['Dog', 'Question Mark', 'Star', 'Cash Cow'], correctIndex: 2, explanation: 'The BCG Matrix classifies a business unit with high relative market share in a high-growth market as a "Star" — one that typically requires heavy investment but has strong future potential.', source },
  { id: 'sebi-ph2-p2-mgmt-002', section: 'Management', topic: 'BCG Matrix', difficulty: 'hard', question: 'In the BCG Growth-Share Matrix, a business unit with a high market share in a low-growth, mature market — one that generates more cash than it needs for reinvestment — is classified as a:', options: ['Star', 'Cash Cow', 'Question Mark', 'Dog'], correctIndex: 1, explanation: 'A "Cash Cow" has a high market share in a low-growth market; it generates surplus cash that a firm typically uses to fund other business units, such as Stars or Question Marks.', source },
  { id: 'sebi-ph2-p2-mgmt-003', section: 'Management', topic: 'Ansoff Matrix', difficulty: 'hard', question: 'In the Ansoff Matrix, a growth strategy of selling more of an existing product to an existing market — for example, through increased marketing effort — is called:', options: ['Market Development', 'Product Development', 'Market Penetration', 'Diversification'], correctIndex: 2, explanation: 'Market Penetration, in the Ansoff Matrix, is the strategy of increasing sales of existing products in existing markets, typically through more aggressive marketing, pricing, or distribution.', source },
  { id: 'sebi-ph2-p2-mgmt-004', section: 'Management', topic: 'Ansoff Matrix', difficulty: 'hard', question: 'In the Ansoff Matrix, a growth strategy of launching an entirely new product into an entirely new market is called:', options: ['Market Penetration', 'Product Development', 'Market Development', 'Diversification'], correctIndex: 3, explanation: 'Diversification, in the Ansoff Matrix, is the highest-risk growth strategy: introducing a new product into a new market, with no direct link to the firm\'s existing products or customers.', source },
  { id: 'sebi-ph2-p2-mgmt-005', section: 'Management', topic: 'McGregor\'s Theory X and Y', difficulty: 'hard', question: "Douglas McGregor's Theory X assumes that the average employee:", options: ['Enjoys work and seeks responsibility naturally', 'Is inherently lazy, dislikes work, and must be closely controlled and directed', 'Is intrinsically motivated by self-actualisation alone', 'Requires no supervision whatsoever'], correctIndex: 1, explanation: "McGregor's Theory X takes a pessimistic view of employees, assuming they are inherently lazy, dislike work, and must be closely controlled, directed, or coerced to achieve organisational goals.", source },
  { id: 'sebi-ph2-p2-mgmt-006', section: 'Management', topic: 'McGregor\'s Theory X and Y', difficulty: 'hard', question: "Douglas McGregor's Theory Y, in contrast to Theory X, assumes that the average employee:", options: ['Must always be closely supervised to perform', 'Views work as a natural activity and can be self-directed and creative when properly motivated', 'Is motivated only by fear of punishment', 'Avoids responsibility whenever possible, without exception'], correctIndex: 1, explanation: "McGregor's Theory Y takes an optimistic view of employees, assuming they view work as natural, can exercise self-direction and self-control, and often seek and accept responsibility when properly motivated.", source },
  { id: 'sebi-ph2-p2-mgmt-007', section: 'Management', topic: "Vroom's Expectancy Theory", difficulty: 'hard', question: "According to Vroom's Expectancy Theory of motivation, an individual's motivation to exert effort depends jointly on:", options: ['Only the reward offered, regardless of effort required', "Expectancy (effort leads to performance), Instrumentality (performance leads to reward), and Valence (the value placed on the reward)", 'Only the hierarchy of needs being satisfied in sequence', 'Only whether hygiene factors are present'], correctIndex: 1, explanation: "Vroom's Expectancy Theory holds that motivation is a function of Expectancy (belief that effort leads to performance), Instrumentality (belief that performance leads to a reward), and Valence (how much the individual values that reward).", source },
  { id: 'sebi-ph2-p2-mgmt-008', section: 'Management', topic: 'Hersey-Blanchard Situational Leadership', difficulty: 'hard', question: "In the Hersey-Blanchard Situational Leadership model, the highly directive 'Telling' leadership style is considered most appropriate for followers who have:", options: ['Low competence and low/variable commitment (low maturity/readiness)', 'High competence and high commitment', 'High competence but low commitment', 'Moderate competence and high commitment'], correctIndex: 0, explanation: "The Hersey-Blanchard model recommends a highly directive 'Telling' style for followers with low readiness or maturity — low competence and low or variable commitment — who need clear, specific instruction rather than delegation.", source },
  { id: 'sebi-ph2-p2-mgmt-009', section: 'Management', topic: "Mintzberg's Managerial Roles", difficulty: 'hard', question: "In Henry Mintzberg's classification of managerial roles, the 'Figurehead' role — performing ceremonial and symbolic duties on behalf of the organisation — belongs to which category of roles?", options: ['Interpersonal', 'Informational', 'Decisional', 'Technical'], correctIndex: 0, explanation: "Mintzberg classifies the Figurehead role (performing ceremonial/symbolic duties) under the Interpersonal category of managerial roles, alongside Leader and Liaison.", source },
  { id: 'sebi-ph2-p2-mgmt-010', section: 'Management', topic: "Mintzberg's Managerial Roles", difficulty: 'hard', question: "In Mintzberg's classification of managerial roles, the 'Disseminator' role — passing information received from outside or from subordinates on to other members of the organisation — belongs to which category?", options: ['Interpersonal', 'Decisional', 'Ceremonial', 'Informational'], correctIndex: 3, explanation: "Mintzberg classifies the Disseminator role under the Informational category of managerial roles, alongside Monitor and Spokesperson.", source },
  { id: 'sebi-ph2-p2-mgmt-011', section: 'Management', topic: 'Management by Objectives', difficulty: 'hard', question: 'The core principle of Management by Objectives (MBO), as a management approach, is that:', options: ['Objectives are set unilaterally by top management and imposed downward without discussion', 'Objectives are never quantified or measured', 'Managers and subordinates jointly set specific, measurable objectives and periodically review progress against them', 'It applies only to financial targets'], correctIndex: 2, explanation: 'Management by Objectives (MBO) is built on managers and subordinates jointly setting specific, measurable objectives, then periodically reviewing and assessing performance against those mutually agreed objectives.', source },
  { id: 'sebi-ph2-p2-mgmt-012', section: 'Management', topic: 'Organisational Structure', difficulty: 'hard', question: 'A Matrix organisational structure is characterised primarily by:', options: ['A single, strict chain of command with no overlap', 'The complete absence of any formal hierarchy', 'Decision-making concentrated entirely at the top, with no delegation', 'Employees reporting to two managers simultaneously — typically a functional manager and a project/product manager'], correctIndex: 3, explanation: 'A Matrix structure is distinguished by dual reporting relationships, where an employee reports simultaneously to a functional manager (e.g., by department) and a project or product manager, combining functional and project-based lines of authority.', source },
  { id: 'sebi-ph2-p2-mgmt-013', section: 'Management', topic: 'Balanced Scorecard', difficulty: 'hard', question: "The Balanced Scorecard framework evaluates organisational performance across four perspectives: Financial, Customer, Internal Business Process, and:", options: ['Learning and Growth', 'Legal and Compliance', 'Environmental and Social', 'Shareholder Activism'], correctIndex: 0, explanation: 'The Balanced Scorecard, developed by Kaplan and Norton, evaluates performance across four linked perspectives: Financial, Customer, Internal Business Process, and Learning and Growth (organisational capacity to innovate and improve).', source },
  { id: 'sebi-ph2-p2-mgmt-014', section: 'Management', topic: 'PESTLE Analysis', difficulty: 'hard', question: 'A PESTLE analysis is used to examine the macro-environmental factors affecting an organisation across which six dimensions?', options: ['Political, Economic, Social, Technological, Legal, Environmental', 'Production, Employment, Sales, Trade, Logistics, Exports', 'Planning, Executing, Staffing, Training, Leading, Evaluating', 'Physical, Emotional, Social, Technical, Legal, Environmental'], correctIndex: 0, explanation: 'A PESTLE analysis examines macro-environmental factors under six dimensions: Political, Economic, Social, Technological, Legal, and Environmental.', source },
];
