import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SEBI Officer Grade A (Assistant Manager) Recruitment 2025 official notification — Phase I, Paper 2, General Stream (Accountancy)',
  url: 'https://www.sebi.gov.in/sebi_data/careerfiles/oct-2025/1761782417659.pdf',
  checkedOn: '24 August 2026',
};

export const SEBI_GRADE_A_PHASE_1_PAPER_2_ACCOUNTANCY_2: Question[] = [
  { id: 'sebi-ga-p2-acc2-001', section: 'Accountancy', topic: 'Depreciation', difficulty: 'medium', question: 'Under the Written Down Value (WDV) method of depreciation, depreciation is calculated on:', options: ['The reducing book value of the asset each year', 'The original cost of the asset every year', 'The market value of the asset', 'The scrap value of the asset'], correctIndex: 0, explanation: 'Under the Written Down Value method, depreciation each year is calculated on the reducing (written down) book value of the asset, not its original cost.', source },
  { id: 'sebi-ga-p2-acc2-002', section: 'Accountancy', topic: 'Classification of Accounts', difficulty: 'medium', question: 'Under the traditional classification, an account related to a person or organisation (such as a Debtors Account) is classified as a:', options: ['Real Account', 'Personal Account', 'Nominal Account', 'Suspense Account'], correctIndex: 1, explanation: 'Accounts related to persons, firms, or organisations are classified as Personal Accounts under the traditional classification.', source },
  { id: 'sebi-ga-p2-acc2-003', section: 'Accountancy', topic: 'Journal and Ledger', difficulty: 'medium', question: 'The process of transferring entries from the Journal to individual accounts in the Ledger is called:', options: ['Casting', 'Balancing', 'Posting', 'Vouching'], correctIndex: 2, explanation: 'Posting is the process of transferring journal entries into their respective accounts in the Ledger.', source },
  { id: 'sebi-ga-p2-acc2-004', section: 'Accountancy', topic: 'Final Accounts', difficulty: 'medium', question: 'The Trading Account of a business is primarily prepared to ascertain:', options: ['Net Profit or Net Loss', 'The value of fixed assets', "The firm's total liabilities", 'Gross Profit or Gross Loss'], correctIndex: 3, explanation: "A Trading Account is prepared primarily to ascertain a business's Gross Profit or Gross Loss for a period.", source },
  { id: 'sebi-ga-p2-acc2-005', section: 'Accountancy', topic: 'Accounting Equation', difficulty: 'medium', question: "If a business's total assets are ₹8,00,000 and total liabilities are ₹3,00,000, its capital is:", options: ['₹5,00,000', '₹11,00,000', '₹4,50,000', '₹5,50,000'], correctIndex: 0, explanation: 'From the accounting equation, Capital = Assets − Liabilities = 8,00,000 − 3,00,000 = ₹5,00,000.', source },
  { id: 'sebi-ga-p2-acc2-006', section: 'Accountancy', topic: 'Trial Balance', difficulty: 'medium', question: 'If the total of the debit column of a Trial Balance does not match the total of the credit column, the difference is temporarily placed in a:', options: ['Nominal Account', 'Suspense Account', 'Contra Account', 'Capital Account'], correctIndex: 1, explanation: 'A mismatch between the debit and credit totals of a Trial Balance is temporarily posted to a Suspense Account until the error is located and corrected.', source },
  { id: 'sebi-ga-p2-acc2-007', section: 'Accountancy', topic: 'Bank Reconciliation', difficulty: 'medium', question: 'A cheque issued by a business but not yet presented for payment at the bank is known, in bank reconciliation, as a:', options: ['Dishonoured cheque', 'Post-dated cheque', 'Unpresented cheque', 'Stale cheque'], correctIndex: 2, explanation: "An unpresented cheque is one that has been issued by the business but has not yet been presented at the bank for payment, causing a temporary difference between the cash book and passbook balances.", source },
];
