import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SEBI Officer Grade A (Assistant Manager) Recruitment 2025 official notification — Phase II, Paper 2, General Stream (Economics, deeper/analytical tier)',
  url: 'https://www.sebi.gov.in/sebi_data/careerfiles/oct-2025/1761782417659.pdf',
  checkedOn: '27 August 2026',
};

export const SEBI_GRADE_A_PHASE_2_PAPER_2_ECONOMICS_1: Question[] = [
  { id: 'sebi-ph2-p2-eco-001', section: 'Economics', topic: 'Fiscal Multiplier', difficulty: 'hard', question: 'If the Marginal Propensity to Consume (MPC) in an economy is 0.8, the simple fiscal (spending) multiplier is:', options: ['0.8', '1.25', '4', '5'], correctIndex: 3, explanation: 'The simple multiplier = 1 ÷ (1 − MPC) = 1 ÷ (1 − 0.8) = 1 ÷ 0.2 = 5.', source },
  { id: 'sebi-ph2-p2-eco-002', section: 'Economics', topic: 'Price Elasticity of Demand', difficulty: 'hard', question: 'When the price of a good rises from ₹100 to ₹110 (a 10% increase), the quantity demanded falls from 200 units to 170 units (a 15% decrease). The Price Elasticity of Demand is:', options: ['0.67 (inelastic)', '1.0 (unit elastic)', '1.5 (elastic)', '2.5 (highly elastic)'], correctIndex: 2, explanation: 'Price Elasticity of Demand = % change in Quantity Demanded ÷ % change in Price = 15% ÷ 10% = 1.5, indicating elastic demand (greater than 1).', source },
  { id: 'sebi-ph2-p2-eco-003', section: 'Economics', topic: 'GDP Deflator', difficulty: 'hard', question: "An economy's Nominal GDP is ₹12,00,000 crore and its Real GDP (at constant prices) is ₹10,00,000 crore. The GDP Deflator for this period is:", options: ['83.3', '100', '110', '120'], correctIndex: 3, explanation: 'GDP Deflator = (Nominal GDP ÷ Real GDP) × 100 = (12,00,000 ÷ 10,00,000) × 100 = 120, indicating the overall price level has risen by 20% relative to the base year.', source },
  { id: 'sebi-ph2-p2-eco-004', section: 'Economics', topic: 'Cash Reserve Ratio', difficulty: 'hard', question: "The Cash Reserve Ratio (CRR), a monetary policy tool used by the Reserve Bank of India, refers to:", options: ['The rate at which the RBI lends to commercial banks against government securities', 'The minimum percentage of a bank\'s Net Demand and Time Liabilities that it must maintain as cash reserves with the RBI', "The minimum percentage of a bank's deposits it must invest in approved government securities", 'The interest rate the RBI pays banks on their surplus funds'], correctIndex: 1, explanation: 'CRR is the minimum percentage of a bank\'s Net Demand and Time Liabilities (NDTL) that it must keep as cash reserves with the RBI, earning no interest; raising CRR reduces the funds available with banks for lending, tightening money supply.', source },
  { id: 'sebi-ph2-p2-eco-005', section: 'Economics', topic: 'Statutory Liquidity Ratio', difficulty: 'hard', question: 'The Statutory Liquidity Ratio (SLR), unlike the Cash Reserve Ratio (CRR), requires banks to maintain a minimum percentage of Net Demand and Time Liabilities in the form of:', options: ['Cash reserves with the RBI only', 'Approved liquid assets such as cash, gold, and specified government securities, held by the bank itself', 'Foreign exchange reserves', 'Loans to the priority sector'], correctIndex: 1, explanation: 'SLR requires banks to maintain a minimum percentage of NDTL in approved liquid assets (cash, gold, and specified government securities), held by the bank itself, unlike CRR, which must be parked with the RBI.', source },
  { id: 'sebi-ph2-p2-eco-006', section: 'Economics', topic: 'Repo Rate Transmission', difficulty: 'hard', question: 'When the Reserve Bank of India raises the Repo Rate, the immediate transmission effect is generally that:', options: ['Commercial banks find it cheaper to borrow from the RBI, so lending rates fall', "Commercial banks' cost of borrowing from the RBI rises, which typically pushes up lending rates and reduces credit growth", 'The Repo Rate has no effect on commercial bank lending rates', 'Inflation immediately falls to zero'], correctIndex: 1, explanation: "A higher Repo Rate raises the cost at which commercial banks borrow short-term funds from the RBI, which typically feeds through to higher lending rates for businesses and consumers, moderating credit growth and demand — the RBI's usual tool to rein in inflation.", source },
  { id: 'sebi-ph2-p2-eco-007', section: 'Economics', topic: 'Reverse Repo Rate', difficulty: 'hard', question: 'The Reverse Repo Rate is the rate at which:', options: ['The RBI borrows funds from commercial banks, absorbing excess liquidity from the banking system', 'Commercial banks lend to each other overnight', 'The RBI lends long-term funds to the government', 'Commercial banks lend to non-banking financial companies'], correctIndex: 0, explanation: 'The Reverse Repo Rate is the rate at which the RBI borrows funds from commercial banks (against government securities), used to absorb excess liquidity from the banking system.', source },
  { id: 'sebi-ph2-p2-eco-008', section: 'Economics', topic: 'International Trade', difficulty: 'hard', question: "According to Ricardo's theory of Comparative Advantage, two countries can gain from trade even if one country is more efficient at producing every good than the other, provided each country:", options: ['Produces only the good it is absolutely most efficient at', 'Specialises in the good for which it has the lowest opportunity cost relative to the other country', 'Imposes tariffs to protect all domestic industries', 'Refuses to trade with less efficient countries'], correctIndex: 1, explanation: "Ricardo's theory of Comparative Advantage shows that mutual gains from trade arise when each country specialises in producing the good for which it has the lowest opportunity cost, even if one country holds an absolute advantage in producing every good.", source },
  { id: 'sebi-ph2-p2-eco-009', section: 'Economics', topic: 'Fiscal Deficit', difficulty: 'hard', question: "A government's Fiscal Deficit is defined as:", options: ['Total Expenditure minus Total Receipts, excluding borrowings', 'Total Revenue Receipts minus Total Revenue Expenditure', 'Total Expenditure minus Tax Revenue only', 'Capital Expenditure minus Capital Receipts'], correctIndex: 0, explanation: 'Fiscal Deficit is the excess of total expenditure over total receipts, excluding borrowings — i.e., the amount the government must borrow to bridge the gap between spending and non-borrowed receipts.', source },
  { id: 'sebi-ph2-p2-eco-010', section: 'Economics', topic: 'Revenue Deficit', difficulty: 'hard', question: "A government's Revenue Deficit is defined as:", options: ['Revenue Expenditure minus Revenue Receipts', 'Capital Expenditure minus Capital Receipts', 'Fiscal Deficit minus Interest Payments', 'Total Expenditure minus Total Revenue'], correctIndex: 0, explanation: 'Revenue Deficit is the excess of Revenue Expenditure over Revenue Receipts, indicating that the government\'s day-to-day (revenue account) spending exceeds its revenue income.', source },
  { id: 'sebi-ph2-p2-eco-011', section: 'Economics', topic: 'Primary Deficit', difficulty: 'hard', question: "A government's Primary Deficit is defined as:", options: ['Fiscal Deficit minus Interest Payments on past borrowings', 'Fiscal Deficit plus Interest Payments', 'Revenue Deficit minus Capital Expenditure', 'Total borrowings for the year, including interest'], correctIndex: 0, explanation: 'Primary Deficit = Fiscal Deficit − Interest Payments, and it reflects the government\'s borrowing requirement for current-year expenditure alone, excluding the burden of servicing past debt.', source },
  { id: 'sebi-ph2-p2-eco-012', section: 'Economics', topic: 'Phillips Curve', difficulty: 'hard', question: 'The (short-run) Phillips Curve depicts:', options: ['A direct/positive relationship between inflation and unemployment', 'No relationship at all between inflation and unemployment', 'A relationship between GDP growth and exports only', 'An inverse relationship between inflation and unemployment'], correctIndex: 3, explanation: 'The short-run Phillips Curve depicts an inverse (trade-off) relationship between the rate of inflation and the rate of unemployment: lower unemployment tends to be associated with higher inflation, and vice versa.', source },
  { id: 'sebi-ph2-p2-eco-013', section: 'Economics', topic: 'Goods and Services Tax', difficulty: 'hard', question: "Under India's GST structure, a supply of goods or services within the same state attracts:", options: ['Only Integrated GST (IGST)', 'Only Central GST (CGST), with no state-level component', 'Central GST (CGST) and State GST (SGST), levied concurrently by the Centre and the State', 'Customs Duty in addition to GST'], correctIndex: 2, explanation: 'An intra-state supply under India\'s GST structure attracts both Central GST (CGST, collected by the Centre) and State GST (SGST, collected by the State) concurrently, whereas an inter-state supply attracts Integrated GST (IGST).', source },
  { id: 'sebi-ph2-p2-eco-014', section: 'Economics', topic: 'FRBM Act', difficulty: 'hard', question: 'The Fiscal Responsibility and Budget Management (FRBM) Act was enacted in India with the primary objective of:', options: ['Regulating the stock market', 'Setting minimum wage levels across states', 'Instituting fiscal discipline by setting targets to reduce fiscal and revenue deficits over time', 'Regulating foreign direct investment inflows'], correctIndex: 2, explanation: "The FRBM Act was enacted to institute fiscal discipline in government finances, setting targets to progressively reduce the fiscal deficit and revenue deficit and improve overall macroeconomic management.", source },
];
