import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SEBI Officer Grade A (Assistant Manager) Recruitment 2025 official notification — Phase II, Paper 2, General Stream (Finance, deeper/analytical tier)',
  url: 'https://www.sebi.gov.in/sebi_data/careerfiles/oct-2025/1761782417659.pdf',
  checkedOn: '27 August 2026',
};

export const SEBI_GRADE_A_PHASE_2_PAPER_2_FINANCE_1: Question[] = [
  { id: 'sebi-ph2-p2-fin-001', section: 'Finance', topic: 'Net Present Value', difficulty: 'hard', question: 'A project requires an initial investment of ₹2,00,000. It is expected to generate cash inflows of ₹1,10,000 at the end of Year 1 and ₹1,21,000 at the end of Year 2. At a discount rate of 10% per annum, the project\'s Net Present Value is closest to:', options: ['₹0', '₹21,000', '₹31,000', '−₹10,000'], correctIndex: 0, explanation: 'PV of Year 1 inflow = 1,10,000 ÷ 1.10 = ₹1,00,000. PV of Year 2 inflow = 1,21,000 ÷ 1.21 = ₹1,00,000. Total PV = ₹2,00,000, exactly equal to the initial investment, so NPV ≈ ₹0.', source },
  { id: 'sebi-ph2-p2-fin-002', section: 'Finance', topic: 'Internal Rate of Return', difficulty: 'hard', question: "A project has an IRR of 15%, while the company's cost of capital (hurdle rate) is 12%. Based on the IRR decision rule, the company should:", options: ['Reject the project, since IRR exceeds the cost of capital', 'Accept the project, since IRR exceeds the cost of capital', 'Accept the project only if its payback period is under 2 years', 'Remain indifferent, since IRR and cost of capital are unrelated to acceptance'], correctIndex: 1, explanation: "Under the IRR decision rule, a project is accepted when its IRR exceeds the firm's cost of capital (hurdle rate), since it is then expected to earn a return above what investors require. Here 15% > 12%, so the project should be accepted.", source },
  { id: 'sebi-ph2-p2-fin-003', section: 'Finance', topic: 'Weighted Average Cost of Capital', difficulty: 'hard', question: 'A company is financed 60% by equity (cost of equity 15%) and 40% by debt (post-tax cost of debt 7%). Its Weighted Average Cost of Capital (WACC) is:', options: ['9.8%', '11.0%', '11.8%', '15.0%'], correctIndex: 2, explanation: 'WACC = (0.60 × 15%) + (0.40 × 7%) = 9.0% + 2.8% = 11.8%.', source },
  { id: 'sebi-ph2-p2-fin-004', section: 'Finance', topic: 'Operating Leverage', difficulty: 'hard', question: "A company's Contribution is ₹80,000 and its EBIT (Earnings Before Interest and Tax) is ₹40,000. Its Degree of Operating Leverage (DOL) is:", options: ['0.5', '1.0', '2.0', '4.0'], correctIndex: 2, explanation: 'DOL = Contribution ÷ EBIT = 80,000 ÷ 40,000 = 2.0, meaning a 1% change in sales produces roughly a 2% change in EBIT.', source },
  { id: 'sebi-ph2-p2-fin-005', section: 'Finance', topic: 'Financial Leverage', difficulty: 'hard', question: "A company's EBIT is ₹40,000 and its annual interest expense is ₹15,000, giving EBT (Earnings Before Tax) of ₹25,000. Its Degree of Financial Leverage (DFL) is:", options: ['0.625', '1.6', '2.5', '4.0'], correctIndex: 1, explanation: 'DFL = EBIT ÷ EBT = 40,000 ÷ 25,000 = 1.6, meaning a 1% change in EBIT produces roughly a 1.6% change in earnings available to equity shareholders.', source },
  { id: 'sebi-ph2-p2-fin-006', section: 'Finance', topic: 'Combined Leverage', difficulty: 'hard', question: 'A company has Contribution of ₹1,00,000, EBIT of ₹50,000, and EBT of ₹25,000. Its Degree of Combined Leverage (DCL) is:', options: ['1.0', '2.0', '4.0', '5.0'], correctIndex: 2, explanation: 'DCL = Contribution ÷ EBT = 1,00,000 ÷ 25,000 = 4.0. This equals DOL × DFL = (1,00,000 ÷ 50,000) × (50,000 ÷ 25,000) = 2 × 2 = 4.', source },
  { id: 'sebi-ph2-p2-fin-007', section: 'Finance', topic: 'EBIT-EPS Analysis', difficulty: 'hard', question: 'The level of EBIT at which Earnings Per Share (EPS) is the same regardless of whether a company finances a project through additional equity or additional debt is called the:', options: ['Break-even point', 'EBIT-EPS indifference point', 'Margin of safety', 'Operating break-even level'], correctIndex: 1, explanation: 'The EBIT-EPS indifference point is the EBIT level at which EPS is identical under alternative financing plans (e.g., all-equity versus debt-equity mix), used to guide capital structure decisions.', source },
  { id: 'sebi-ph2-p2-fin-008', section: 'Finance', topic: 'Quick Ratio', difficulty: 'hard', question: "A company has Current Assets of ₹9,00,000 (including Inventory of ₹3,00,000 and Prepaid Expenses of ₹60,000) and Current Liabilities of ₹3,00,000. Its Quick Ratio (Acid-Test Ratio) is closest to:", options: ['1.2', '1.8', '2.4', '3.0'], correctIndex: 1, explanation: 'Quick Assets = Current Assets − Inventory − Prepaid Expenses = 9,00,000 − 3,00,000 − 60,000 = 5,40,000. Quick Ratio = 5,40,000 ÷ 3,00,000 = 1.8.', source },
  { id: 'sebi-ph2-p2-fin-009', section: 'Finance', topic: 'Debt-Equity Ratio', difficulty: 'hard', question: "A company has long-term debt of ₹6,00,000 and shareholders' equity of ₹4,00,000. Its Debt-Equity ratio is:", options: ['0.67:1', '1:1', '1.5:1', '2.4:1'], correctIndex: 2, explanation: 'Debt-Equity Ratio = Long-term Debt ÷ Shareholders\' Equity = 6,00,000 ÷ 4,00,000 = 1.5:1.', source },
  { id: 'sebi-ph2-p2-fin-010', section: 'Finance', topic: 'Return on Equity (DuPont)', difficulty: 'hard', question: 'Using the DuPont three-factor decomposition, a company has a Net Profit Margin of 10%, an Asset Turnover of 1.5 times, and an Equity Multiplier of 2. Its Return on Equity (ROE) is:', options: ['15%', '20%', '35%', '30%'], correctIndex: 3, explanation: 'DuPont ROE = Net Profit Margin × Asset Turnover × Equity Multiplier = 10% × 1.5 × 2 = 30%.', source },
  { id: 'sebi-ph2-p2-fin-011', section: 'Finance', topic: 'Payback Period', difficulty: 'medium', question: 'A project requires an initial investment of ₹5,00,000 and generates a uniform annual cash inflow of ₹1,25,000. Its Payback Period is:', options: ['4 years', '2 years', '3 years', '5 years'], correctIndex: 0, explanation: 'Payback Period = Initial Investment ÷ Annual Cash Inflow = 5,00,000 ÷ 1,25,000 = 4 years.', source },
  { id: 'sebi-ph2-p2-fin-012', section: 'Finance', topic: 'Discounted Payback Period', difficulty: 'medium', question: 'Unlike the simple Payback Period, the Discounted Payback Period method:', options: ['Discounts future cash flows to present value before computing the recovery period, so it always shows a period at least as long as the simple payback', 'Ignores the time value of money entirely', 'Can only be used for projects with a single cash flow', 'Is identical to the Accounting Rate of Return method'], correctIndex: 0, explanation: 'The Discounted Payback Period discounts each future cash inflow to its present value before determining how long it takes to recover the initial investment, so it always takes at least as long as the simple (undiscounted) payback period.', source },
  { id: 'sebi-ph2-p2-fin-013', section: 'Finance', topic: 'Forward Contracts', difficulty: 'hard', question: 'An investor holds a long forward contract on a commodity at a contracted (forward) price of ₹80 per unit. If the spot price at maturity is ₹85 per unit, the payoff to the long position is:', options: ['−₹5 per unit', '₹0 per unit', '+₹80 per unit', '+₹5 per unit'], correctIndex: 3, explanation: 'The payoff to a long forward position at maturity is Spot Price − Forward Price = 85 − 80 = +₹5 per unit; the long position gains when the spot price exceeds the contracted forward price.', source },
  { id: 'sebi-ph2-p2-fin-014', section: 'Finance', topic: 'Options', difficulty: 'hard', question: 'A call option has a strike price of ₹100. If the spot price of the underlying at expiry is ₹115, the intrinsic value of the call option is:', options: ['₹0', '₹100', '₹115', '₹15'], correctIndex: 3, explanation: 'The intrinsic value of a call option is max(Spot Price − Strike Price, 0) = max(115 − 100, 0) = ₹15.', source },
  { id: 'sebi-ph2-p2-fin-015', section: 'Finance', topic: 'Put-Call Parity', difficulty: 'hard', question: 'The Put-Call Parity relationship for European options on a non-dividend-paying stock states that:', options: ['Call Premium + Present Value of Strike Price = Put Premium + Spot Price', 'Call Premium = Put Premium, always, regardless of strike or spot price', 'Put Premium is always greater than Call Premium', 'The relationship holds only for American options'], correctIndex: 0, explanation: 'Put-Call Parity states that Call Premium + PV(Strike Price) = Put Premium + Spot Price, linking the prices of a call and a put with the same strike and expiry on a non-dividend-paying underlying.', source },
  { id: 'sebi-ph2-p2-fin-016', section: 'Finance', topic: 'Bond Pricing', difficulty: 'medium', question: 'As market interest rates rise, the price of an existing fixed-coupon bond, all else equal:', options: ['Rises', 'Remains unchanged', 'Becomes undefined', 'Falls'], correctIndex: 3, explanation: "Bond prices and market interest rates move inversely: as market rates rise, the present value of a bond's fixed future coupon and principal payments falls, so its price falls.", source },
];
