import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SEBI Officer Grade A (Assistant Manager) Recruitment 2025 official notification — Phase I, Paper 2, General Stream (Economics)',
  url: 'https://www.sebi.gov.in/sebi_data/careerfiles/oct-2025/1761782417659.pdf',
  checkedOn: '6 August 2026',
};

export const SEBI_GRADE_A_PHASE_1_PAPER_2_ECONOMICS_1: Question[] = [
  { id: 'sebi-ga-p2-eco-001', section: 'Economics', topic: 'Demand and Supply', difficulty: 'medium', question: 'The Law of Demand states that, other factors remaining constant, as the price of a good rises, the quantity demanded:', options: ['Falls', 'Rises', 'Remains unchanged', 'Rises then falls'], correctIndex: 0, explanation: "The Law of Demand states that, ceteris paribus, there is an inverse relationship between a good's price and the quantity demanded — as price rises, quantity demanded falls.", source },
  { id: 'sebi-ga-p2-eco-002', section: 'Economics', topic: 'National Income', difficulty: 'medium', question: 'Which of the following best defines Gross Domestic Product (GDP)?', options: ['The total value of all final goods and services produced within a country in a given period', 'Only the value of exports', 'Only government spending', 'The total money supply in an economy'], correctIndex: 0, explanation: 'GDP measures the total monetary value of all final goods and services produced within a country\'s borders during a given period.', source },
  { id: 'sebi-ga-p2-eco-003', section: 'Economics', topic: 'Inflation', difficulty: 'medium', question: 'A sustained increase in the general price level of goods and services in an economy over time is called:', options: ['Deflation', 'Inflation', 'Stagflation', 'Recession'], correctIndex: 1, explanation: 'Inflation refers to a sustained rise in the general price level of goods and services in an economy over a period of time.', source },
  { id: 'sebi-ga-p2-eco-004', section: 'Economics', topic: 'Fiscal and Monetary Policy', difficulty: 'medium', question: 'Government policy relating to taxation and public spending, used to influence the economy, is called:', options: ['Monetary Policy', 'Fiscal Policy', 'Trade Policy', 'Industrial Policy'], correctIndex: 1, explanation: 'Fiscal Policy refers to government decisions on taxation and public spending used to influence overall economic activity, as distinct from monetary policy which is managed by the central bank.', source },
  { id: 'sebi-ga-p2-eco-005', section: 'Economics', topic: 'Elasticity', difficulty: 'medium', question: 'If a small change in price causes a proportionately larger change in quantity demanded, the demand is said to be:', options: ['Unitary elastic', 'Inelastic', 'Elastic', 'Perfectly inelastic'], correctIndex: 2, explanation: 'Demand is described as elastic when a proportionately small change in price leads to a proportionately larger change in quantity demanded.', source },
  { id: 'sebi-ga-p2-eco-006', section: 'Economics', topic: 'Unemployment', difficulty: 'medium', question: "Unemployment that occurs due to a mismatch between workers' skills and the skills required by available jobs is called:", options: ['Cyclical Unemployment', 'Frictional Unemployment', 'Structural Unemployment', 'Seasonal Unemployment'], correctIndex: 2, explanation: "Structural Unemployment arises from a mismatch between the skills workers possess and the skills demanded by available jobs, often due to technological or industrial change.", source },
  { id: 'sebi-ga-p2-eco-007', section: 'Economics', topic: 'International Trade', difficulty: 'medium', question: "A country's Balance of Payments is a systematic record of:", options: ['Only foreign direct investment inflows', 'Only the country\'s export earnings', 'Only the government\'s foreign debt', 'All economic transactions between a country\'s residents and the rest of the world'], correctIndex: 3, explanation: "A country's Balance of Payments is a systematic record of all economic transactions between its residents and the rest of the world over a given period.", source },
];
