import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SEBI Officer Grade A (Assistant Manager) Recruitment 2025 official notification — Phase II, Paper 2, General Stream (Commerce, deeper/analytical tier)',
  url: 'https://www.sebi.gov.in/sebi_data/careerfiles/oct-2025/1761782417659.pdf',
  checkedOn: '27 August 2026',
};

export const SEBI_GRADE_A_PHASE_2_PAPER_2_COMMERCE_1: Question[] = [
  { id: 'sebi-ph2-p2-com-001', section: 'Commerce', topic: 'Mergers and Acquisitions', difficulty: 'hard', question: 'A merger between two companies operating in the same industry, at the same stage of production and selling similar products (e.g., two cement manufacturers), is called a:', options: ['Vertical Merger', 'Horizontal Merger', 'Conglomerate Merger', 'Reverse Merger'], correctIndex: 1, explanation: 'A Horizontal Merger combines two companies that are direct competitors, operating in the same industry and at the same stage of the production/value chain.', source },
  { id: 'sebi-ph2-p2-com-002', section: 'Commerce', topic: 'Mergers and Acquisitions', difficulty: 'hard', question: 'A merger between a manufacturing company and one of its raw-material suppliers is an example of a:', options: ['Horizontal Merger', 'Vertical Merger (backward integration)', 'Conglomerate Merger', 'Congeneric Merger'], correctIndex: 1, explanation: 'A Vertical Merger combines firms at different stages of the same supply chain; a merger with a supplier is specifically backward integration, extending the acquirer\'s control upstream.', source },
  { id: 'sebi-ph2-p2-com-003', section: 'Commerce', topic: 'Mergers and Acquisitions', difficulty: 'hard', question: 'A merger between two companies operating in entirely unrelated industries, with no common customers, suppliers, or products, is called a:', options: ['Horizontal Merger', 'Vertical Merger', 'Conglomerate Merger', 'Market-extension Merger'], correctIndex: 2, explanation: 'A Conglomerate Merger combines companies in entirely unrelated lines of business, primarily for diversification rather than any operational or market synergy.', source },
  { id: 'sebi-ph2-p2-com-004', section: 'Commerce', topic: 'Initial Public Offering', difficulty: 'hard', question: 'The IPO pricing process in which the issue price is discovered through a bidding process, with investors submitting bids within a specified price band, is known as:', options: ['Fixed Price Method', 'Book Building Process', 'Rights Issue', 'Private Placement'], correctIndex: 1, explanation: 'The Book Building Process is a price-discovery mechanism in which the final issue price is determined based on bids submitted by investors within a specified price band, as opposed to the Fixed Price Method, where the issue price is set in advance.', source },
  { id: 'sebi-ph2-p2-com-005', section: 'Commerce', topic: 'Underwriting', difficulty: 'hard', question: 'In the context of a securities issue, "underwriting" refers to an arrangement in which:', options: ['A company guarantees dividend payments to preference shareholders', 'A financial institution or intermediary agrees to subscribe to any portion of an issue not taken up by the public, for a fee', 'Investors are guaranteed a fixed return on equity shares', 'A company insures its physical assets against loss'], correctIndex: 1, explanation: 'Underwriting is an arrangement in which an underwriter (typically a financial institution or intermediary) agrees, for a commission, to subscribe to any part of a securities issue that is not taken up by the public, reducing the issuer\'s risk of under-subscription.', source },
  { id: 'sebi-ph2-p2-com-006', section: 'Commerce', topic: 'Depository System', difficulty: 'hard', question: "In India's securities market, entities such as NSDL and CDSL, which hold investors' securities in electronic (dematerialised) form, are known as:", options: ['Stock Exchanges', 'Clearing Corporations', 'Merchant Bankers', 'Depositories'], correctIndex: 3, explanation: 'NSDL (National Securities Depository Limited) and CDSL (Central Depository Services Limited) are Depositories — institutions that hold securities in electronic (dematerialised) form on behalf of investors and facilitate their transfer.', source },
  { id: 'sebi-ph2-p2-com-007', section: 'Commerce', topic: 'Dematerialisation', difficulty: 'hard', question: 'The primary purpose of opening a Demat Account is to:', options: ['Obtain a loan against physical share certificates', 'Open a fixed deposit with a bank', 'Hold securities such as shares and bonds in electronic form instead of physical certificates', 'Register a company with the Registrar of Companies'], correctIndex: 2, explanation: 'A Demat (Dematerialised) Account allows an investor to hold securities such as shares, bonds, and mutual fund units in electronic form, eliminating the risks and inconvenience associated with physical share certificates.', source },
  { id: 'sebi-ph2-p2-com-008', section: 'Commerce', topic: 'Types of Preference Shares', difficulty: 'hard', question: 'Preference shares on which unpaid dividend, if not paid in a particular year due to insufficient profits, accumulates and is carried forward to be paid in a subsequent profitable year are known as:', options: ['Cumulative Preference Shares', 'Non-Cumulative Preference Shares', 'Participating Preference Shares', 'Redeemable Preference Shares'], correctIndex: 0, explanation: 'Cumulative Preference Shares carry the right to accumulate unpaid dividends from a loss-making year and receive them in a later year before any dividend is paid to equity shareholders.', source },
  { id: 'sebi-ph2-p2-com-009', section: 'Commerce', topic: 'Types of Preference Shares', difficulty: 'hard', question: 'Preference shares on which unpaid dividend does NOT accumulate or carry forward to future years are called:', options: ['Cumulative Preference Shares', 'Convertible Preference Shares', 'Participating Preference Shares', 'Non-Cumulative Preference Shares'], correctIndex: 3, explanation: 'Non-Cumulative Preference Shares carry no right to unpaid dividends from a year in which the company does not declare a dividend; that year\'s dividend is simply forfeited, not carried forward.', source },
  { id: 'sebi-ph2-p2-com-010', section: 'Commerce', topic: 'Types of Preference Shares', difficulty: 'hard', question: 'Preference shares that carry, in addition to a fixed dividend, the right to participate in any surplus profit left after paying dividends to equity shareholders are called:', options: ['Non-Participating Preference Shares', 'Non-Cumulative Preference Shares', 'Participating Preference Shares', 'Irredeemable Preference Shares'], correctIndex: 2, explanation: 'Participating Preference Shares entitle holders to a fixed preferential dividend and, in addition, a share of any surplus profit distributed after equity shareholders are paid, over and above the fixed rate.', source },
  { id: 'sebi-ph2-p2-com-011', section: 'Commerce', topic: 'Stock Exchange Mechanisms', difficulty: 'hard', question: 'A "circuit breaker" imposed by a stock exchange refers to a mechanism that:', options: ['Temporarily halts trading market-wide (or in a specific security) when prices move beyond a specified percentage limit, to curb excessive volatility', 'Permanently halts trading in a scrip after a scam is detected', 'Automatically executes all pending buy orders at market open', 'Prevents any company from ever being delisted'], correctIndex: 0, explanation: 'A circuit breaker temporarily halts trading — either market-wide or for a specific security — once price movement crosses a pre-defined percentage threshold, giving the market a cooling-off period to curb panic-driven volatility.', source },
  { id: 'sebi-ph2-p2-com-012', section: 'Commerce', topic: 'Settlement Cycle', difficulty: 'hard', question: 'A "T+1 settlement cycle" in the Indian securities market means that:', options: ['A trade must be cancelled within 1 day if not settled', 'A trader has 1 year to settle a trade', 'Only 1 unit of a security can be traded per transaction', 'Securities and funds are exchanged (settled) one trading day after the transaction (trade) date'], correctIndex: 3, explanation: "T+1 settlement means the transfer of securities and funds between buyer and seller is completed one trading day (T+1) after the trade date (T), the standard settlement cycle for India's equity cash market.", source },
  { id: 'sebi-ph2-p2-com-013', section: 'Commerce', topic: 'Insurance', difficulty: 'hard', question: 'When an insurer transfers a portion of its own insurance risk to another insurer, in order to reduce its exposure on a large risk, this arrangement is called:', options: ['Co-insurance', 'Double Insurance', 'Reinsurance', 'Subrogation'], correctIndex: 2, explanation: 'Reinsurance is an arrangement in which one insurer (the "ceding" insurer) transfers part of its own risk to another insurer (the "reinsurer"), reducing the exposure it carries on any single large risk.', source },
  { id: 'sebi-ph2-p2-com-014', section: 'Commerce', topic: 'Insurance', difficulty: 'hard', question: 'When two or more insurers jointly insure the same risk under a single policy, with each insurer bearing an agreed proportion of the risk and premium, this arrangement is called:', options: ['Co-insurance', 'Reinsurance', 'Over-insurance', 'Contribution'], correctIndex: 0, explanation: 'Co-insurance is an arrangement in which two or more insurers jointly cover the same risk under a single policy, each bearing an agreed share of both the risk and the premium.', source },
  { id: 'sebi-ph2-p2-com-015', section: 'Commerce', topic: 'Holding and Subsidiary Companies', difficulty: 'hard', question: "Under the Companies Act, 2013, a company is generally treated as a 'subsidiary' of another (the holding company) when the holding company:", options: ['Merely purchases goods from the other company', 'Shares the same registered office address as the other company', "Has the same auditor as the other company", 'Controls the composition of the Board of Directors, or holds more than one-half of the total voting power, of the other company'], correctIndex: 3, explanation: 'Under the Companies Act, 2013, a company is a subsidiary of another if the holding company controls the composition of its Board of Directors, or holds (alone or with other subsidiaries) more than one-half of its total voting power.', source },
  { id: 'sebi-ph2-p2-com-016', section: 'Commerce', topic: 'Corporate Governance', difficulty: 'hard', question: 'The SEBI (Listing Obligations and Disclosure Requirements) Regulations, commonly referred to as SEBI LODR, primarily govern:', options: ['Continuous disclosure obligations and corporate governance norms for companies listed on stock exchanges', 'The taxation of listed companies', 'The minimum wages payable by listed companies', 'The import-export policy of listed companies'], correctIndex: 0, explanation: 'The SEBI (LODR) Regulations lay down the continuous disclosure obligations and corporate governance requirements (such as board composition, related-party transaction norms, and periodic financial disclosures) applicable to companies whose securities are listed on a recognised stock exchange.', source },
];
