import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SEBI Officer Grade A (Assistant Manager) Recruitment 2025 official notification — Phase I, Paper 2, General Stream (Management)',
  url: 'https://www.sebi.gov.in/sebi_data/careerfiles/oct-2025/1761782417659.pdf',
  checkedOn: '24 August 2026',
};

export const SEBI_GRADE_A_PHASE_1_PAPER_2_MANAGEMENT_2: Question[] = [
  { id: 'sebi-ga-p2-mgmt2-001', section: 'Management', topic: 'Functions of Management', difficulty: 'medium', question: 'The management function concerned with setting objectives in advance and deciding the course of action to achieve them is called:', options: ['Staffing', 'Directing', 'Controlling', 'Planning'], correctIndex: 3, explanation: 'Planning is the management function of setting objectives in advance and deciding the course of action needed to achieve them.', source },
  { id: 'sebi-ga-p2-mgmt2-002', section: 'Management', topic: 'Motivation Theory', difficulty: 'medium', question: "According to Herzberg's Two-Factor Theory, factors such as salary and working conditions that prevent dissatisfaction but do not motivate on their own are called:", options: ['Hygiene factors', 'Motivator factors', 'Growth factors', 'Esteem factors'], correctIndex: 0, explanation: "In Herzberg's Two-Factor Theory, hygiene factors (such as salary and working conditions) prevent dissatisfaction but do not themselves motivate employees.", source },
  { id: 'sebi-ga-p2-mgmt2-003', section: 'Management', topic: 'Organisational Structure', difficulty: 'medium', question: 'A tall organisational structure, as opposed to a flat one, is characterised by:', options: ['Many levels of hierarchy and a narrow span of control', 'Few levels of hierarchy and a wide span of control', 'No formal hierarchy at all', 'Equal authority shared among all employees'], correctIndex: 0, explanation: 'A tall organisational structure has many levels of hierarchy, each manager typically supervising a narrow span of control.', source },
  { id: 'sebi-ga-p2-mgmt2-004', section: 'Management', topic: 'Leadership', difficulty: 'medium', question: 'A leadership style in which the leader allows subordinates a high degree of freedom in decision-making, offering minimal direction, is known as:', options: ['Autocratic leadership', 'Democratic leadership', 'Laissez-faire leadership', 'Bureaucratic leadership'], correctIndex: 2, explanation: 'Laissez-faire leadership allows subordinates a high degree of freedom in decision-making, with the leader providing minimal direct guidance.', source },
  { id: 'sebi-ga-p2-mgmt2-005', section: 'Management', topic: 'Strategic Analysis', difficulty: 'medium', question: "Porter's Five Forces framework is primarily used to analyse:", options: ["An individual employee's performance", "A company's advertising budget", 'The competitive intensity and attractiveness of an industry', "A single project's timeline"], correctIndex: 2, explanation: "Porter's Five Forces framework analyses the competitive intensity and overall attractiveness of an industry.", source },
  { id: 'sebi-ga-p2-mgmt2-006', section: 'Management', topic: 'Decision Making', difficulty: 'medium', question: 'A decision made in response to a unique, unstructured situation with no established procedure to follow is called a:', options: ['Programmed decision', 'Non-programmed decision', 'Routine decision', 'Operational decision'], correctIndex: 1, explanation: 'A non-programmed decision addresses a unique, unstructured situation for which no established rule or procedure exists.', source },
  { id: 'sebi-ga-p2-mgmt2-007', section: 'Management', topic: 'Functions of Management', difficulty: 'medium', question: 'The management function that involves recruiting, selecting, training, and developing personnel within an organisation is called:', options: ['Organising', 'Staffing', 'Coordinating', 'Controlling'], correctIndex: 1, explanation: 'Staffing is the management function concerned with recruiting, selecting, training, and developing personnel within an organisation.', source },
];
