import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SEBI Officer Grade A (Assistant Manager) Recruitment 2025 official notification — Phase I, Paper 2, General Stream (Finance)',
  url: 'https://www.sebi.gov.in/sebi_data/careerfiles/oct-2025/1761782417659.pdf',
  checkedOn: '24 August 2026',
};

export const SEBI_GRADE_A_PHASE_1_PAPER_2_FINANCE_2: Question[] = [
  { id: 'sebi-ga-p2-fin2-001', section: 'Finance', topic: 'Capital Budgeting', difficulty: 'medium', question: "The Internal Rate of Return (IRR) of a project is the discount rate at which:", options: ["The project's total revenue equals total cost", "The project's payback period is shortest", "The project's fixed costs equal variable costs", "The project's Net Present Value equals zero"], correctIndex: 3, explanation: "The IRR is the discount rate at which a project's Net Present Value (NPV) becomes exactly zero.", source },
  { id: 'sebi-ga-p2-fin2-002', section: 'Finance', topic: 'Working Capital', difficulty: 'medium', question: 'Gross Working Capital, as distinct from Net Working Capital, refers to:', options: ["The firm's total investment in current assets alone", 'Current Assets minus Current Liabilities', "The firm's total fixed assets", 'Long-term debt minus equity'], correctIndex: 0, explanation: "Gross Working Capital refers to a firm's total investment in current assets, while Net Working Capital is Current Assets minus Current Liabilities.", source },
  { id: 'sebi-ga-p2-fin2-003', section: 'Finance', topic: 'Cost of Capital', difficulty: 'medium', question: 'The Weighted Average Cost of Capital (WACC) combines the cost of a firm\'s different sources of finance, weighted by:', options: ['Their maturity period alone', 'Their proportion in the firm\'s capital structure', 'Their year of issuance', "The credit rating of the firm's bonds only"], correctIndex: 1, explanation: "WACC combines the cost of each source of finance (debt, equity, etc.), weighted according to their proportion in the firm's overall capital structure.", source },
  { id: 'sebi-ga-p2-fin2-004', section: 'Finance', topic: 'Financial Leverage', difficulty: 'medium', question: 'Operating Leverage, unlike Financial Leverage, arises primarily from a firm\'s use of:', options: ['Fixed operating costs in its cost structure', 'Debt in its capital structure', 'Preference share capital', 'Retained earnings alone'], correctIndex: 0, explanation: "Operating Leverage arises from a firm's use of fixed operating costs, whereas Financial Leverage arises from its use of debt (fixed financial charges) in its capital structure.", source },
  { id: 'sebi-ga-p2-fin2-005', section: 'Finance', topic: 'Sources of Finance', difficulty: 'medium', question: 'Which of the following is a source of short-term finance for a company?', options: ['Debentures', 'Equity Shares', 'Commercial Paper', 'Term Loans'], correctIndex: 2, explanation: 'Commercial Paper is a short-term, unsecured money market instrument used by companies for short-term financing, unlike debentures, equity, and term loans, which are longer-term sources.', source },
  { id: 'sebi-ga-p2-fin2-006', section: 'Finance', topic: 'Ratio Analysis', difficulty: 'medium', question: 'The Debt-Equity Ratio is calculated as:', options: ["Current Assets ÷ Current Liabilities", 'Total Debt ÷ Total Equity', 'Net Profit ÷ Total Equity', 'Total Assets ÷ Total Debt'], correctIndex: 1, explanation: "The Debt-Equity Ratio, a measure of a firm's financial leverage, is calculated as Total Debt divided by Total Equity.", source },
  { id: 'sebi-ga-p2-fin2-007', section: 'Finance', topic: 'Dividend Policy', difficulty: 'medium', question: 'A stable dividend policy, in which a company pays a fixed or steadily growing dividend regardless of short-term profit fluctuations, is primarily intended to:', options: ['Maximise short-term tax liabilities', 'Reduce shareholder confidence in the company', 'Provide predictability and build investor confidence', 'Eliminate the need for retained earnings entirely'], correctIndex: 2, explanation: 'A stable dividend policy aims to provide shareholders with predictable income and build long-term investor confidence in the company.', source },
  { id: 'sebi-ga-p2-fin2-008', section: 'Finance', topic: 'Capital Budgeting', difficulty: 'medium', question: 'The Payback Period method of capital budgeting evaluates a project based on:', options: ['The total profit earned over the project\'s entire life', 'The discounted present value of all future cash flows', "The project's internal rate of return", 'The time required to recover the initial investment from net cash inflows'], correctIndex: 3, explanation: 'The Payback Period method measures the time required to recover the initial investment from a project\'s net cash inflows.', source },
];
