import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SEBI Officer Grade A (Assistant Manager) Recruitment 2025 official notification — Phase I, Paper 2, General Stream (Costing)',
  url: 'https://www.sebi.gov.in/sebi_data/careerfiles/oct-2025/1761782417659.pdf',
  checkedOn: '24 August 2026',
};

export const SEBI_GRADE_A_PHASE_1_PAPER_2_COSTING_2: Question[] = [
  { id: 'sebi-ga-p2-cost2-001', section: 'Costing', topic: 'Cost Classification', difficulty: 'medium', question: 'Costs that vary in direct proportion to the level of production or output are called:', options: ['Variable Costs', 'Fixed Costs', 'Semi-variable Costs', 'Sunk Costs'], correctIndex: 0, explanation: 'Variable costs change in direct proportion to the level of production or output, unlike fixed costs, which remain constant.', source },
  { id: 'sebi-ga-p2-cost2-002', section: 'Costing', topic: 'Break-Even Analysis', difficulty: 'medium', question: 'The Margin of Safety in break-even analysis refers to the excess of:', options: ['Fixed costs over variable costs', 'Actual (or budgeted) sales over the break-even sales level', 'Total revenue over total cost at the break-even point', 'Variable costs over contribution'], correctIndex: 1, explanation: 'The Margin of Safety is the excess of actual or budgeted sales over the break-even sales level, indicating how much sales can drop before a loss occurs.', source },
  { id: 'sebi-ga-p2-cost2-003', section: 'Costing', topic: 'Marginal Costing', difficulty: 'medium', question: 'Under marginal costing, fixed costs are treated as:', options: ['Product costs, absorbed into inventory valuation', 'Costs that vary with output', 'Period costs, charged fully against the period\'s revenue', 'Costs ignored entirely in decision-making'], correctIndex: 2, explanation: 'Under marginal costing, fixed costs are treated as period costs, charged fully against the revenue of the period in which they are incurred, rather than absorbed into inventory.', source },
  { id: 'sebi-ga-p2-cost2-004', section: 'Costing', topic: 'Standard Costing', difficulty: 'medium', question: 'The difference between a standard cost and the corresponding actual cost incurred is called a:', options: ['Sunk Cost', 'Opportunity Cost', 'Variance', 'Budgeted Cost'], correctIndex: 2, explanation: 'A Variance is the difference between a predetermined standard cost and the actual cost incurred, analysed to identify causes of deviation.', source },
  { id: 'sebi-ga-p2-cost2-005', section: 'Costing', topic: 'Cost Sheet', difficulty: 'medium', question: 'In a Cost Sheet, "Prime Cost" refers to the total of:', options: ['Direct Material, Direct Labour, and Direct Expenses', 'Only indirect factory overheads', 'Selling and distribution expenses only', 'Office and administration overheads only'], correctIndex: 0, explanation: 'Prime Cost is the sum of Direct Material, Direct Labour, and Direct Expenses — the direct costs traceable to a specific unit of production.', source },
  { id: 'sebi-ga-p2-cost2-006', section: 'Costing', topic: 'Contribution', difficulty: 'medium', question: 'If sales revenue is ₹5,00,000 and variable costs are ₹3,20,000, the contribution is:', options: ['₹1,20,000', '₹1,80,000', '₹2,00,000', '₹8,20,000'], correctIndex: 1, explanation: 'Contribution = Sales − Variable Costs = 5,00,000 − 3,20,000 = ₹1,80,000.', source },
  { id: 'sebi-ga-p2-cost2-007', section: 'Costing', topic: 'Absorption Costing', difficulty: 'medium', question: 'Under Absorption Costing, when closing stock exists, reported profit compared to Marginal Costing is generally:', options: ['Lower, since fixed overheads are excluded from stock value', 'Always identical under both methods', 'Impossible to determine without additional data', 'Higher, since some fixed overheads are carried forward in closing stock value'], correctIndex: 3, explanation: 'Under Absorption Costing, a portion of fixed overheads is carried forward in the value of closing stock, so reported profit is generally higher than under Marginal Costing when closing stock exists.', source },
];
