import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SEBI Officer Grade A (Assistant Manager) Recruitment 2025 official notification — Phase I, Paper 1, Quantitative Aptitude section',
  url: 'https://www.sebi.gov.in/sebi_data/careerfiles/oct-2025/1761782417659.pdf',
  checkedOn: '6 August 2026',
};

export const SEBI_GRADE_A_PHASE_1_PAPER_1_QUANTITATIVE_APTITUDE_1: Question[] = [
  { id: 'sebi-ga-p1-qa-001', section: 'Quantitative Aptitude', topic: 'Percentage', difficulty: 'medium', question: 'A stock priced at ₹250 rises by 12%. Find the new price.', options: ['₹280', '₹275', '₹285', '₹270'], correctIndex: 0, explanation: 'New price = 250 × 1.12 = ₹280.', source },
  { id: 'sebi-ga-p1-qa-002', section: 'Quantitative Aptitude', topic: 'Ratio and Proportion', difficulty: 'medium', question: 'An investment portfolio worth ₹12,00,000 is split between equity and debt in the ratio 7:3. Find the amount invested in equity.', options: ['₹8,40,000', '₹8,20,000', '₹8,00,000', '₹8,60,000'], correctIndex: 0, explanation: 'Total parts = 7+3 = 10. Equity share = (7/10) × 12,00,000 = ₹8,40,000.', source },
  { id: 'sebi-ga-p1-qa-003', section: 'Quantitative Aptitude', topic: 'Average', difficulty: 'medium', question: "A brokerage's average daily turnover over 4 days was ₹45 crore. If the turnover for the first 3 days totalled ₹125 crore, find the turnover on the 4th day.", options: ['₹50 crore', '₹55 crore', '₹60 crore', '₹65 crore'], correctIndex: 1, explanation: 'Total turnover over 4 days = 45×4 = ₹180 crore. 4th day turnover = 180 − 125 = ₹55 crore.', source },
  { id: 'sebi-ga-p1-qa-004', section: 'Quantitative Aptitude', topic: 'Simple Interest', difficulty: 'medium', question: 'An investor deposits ₹60,000 in a fixed deposit at 6% per annum simple interest for 3 years. Find the interest earned.', options: ['₹10,800', '₹10,200', '₹11,000', '₹9,800'], correctIndex: 0, explanation: 'SI = (60,000 × 6 × 3)/100 = ₹10,800.', source },
  { id: 'sebi-ga-p1-qa-005', section: 'Quantitative Aptitude', topic: 'Compound Interest', difficulty: 'hard', question: 'Find the compound interest on ₹32,000 at 5% per annum for 2 years, compounded annually.', options: ['₹3,280', '₹3,000', '₹3,200', '₹3,100'], correctIndex: 0, explanation: 'Amount = 32,000 × (1.05)² = 32,000 × 1.1025 = ₹35,280. CI = 35,280 − 32,000 = ₹3,280.', source },
  { id: 'sebi-ga-p1-qa-006', section: 'Quantitative Aptitude', topic: 'Time and Work', difficulty: 'medium', question: 'A team of 8 analysts can complete a compliance audit in 15 days. How many analysts are needed to complete it in 10 days?', options: ['10', '12', '14', '16'], correctIndex: 1, explanation: 'Total work = 8×15 = 120 analyst-days. Analysts needed for 10 days = 120/10 = 12.', source },
  { id: 'sebi-ga-p1-qa-007', section: 'Quantitative Aptitude', topic: 'Time and Distance', difficulty: 'medium', question: 'A courier travels 180 km to deliver signed documents, covering the first half of the distance at 60 km/h and the second half at 45 km/h. Find the total time taken.', options: ['3 hours', '3.25 hours', '3.75 hours', '3.5 hours'], correctIndex: 3, explanation: 'Half distance = 90 km. Time for first half = 90/60 = 1.5 hours. Time for second half = 90/45 = 2 hours. Total = 3.5 hours.', source },
  { id: 'sebi-ga-p1-qa-008', section: 'Quantitative Aptitude', topic: 'Profit and Loss', difficulty: 'medium', question: 'A broker buys a block of shares at ₹480 each and sells them at ₹552 each. Find the profit percentage.', options: ['12%', '15%', '18%', '20%'], correctIndex: 1, explanation: 'Profit = 552 − 480 = ₹72. Profit % = (72/480) × 100 = 15%.', source },
  { id: 'sebi-ga-p1-qa-009', section: 'Quantitative Aptitude', topic: 'Number System', difficulty: 'medium', question: 'Find the sum of the first 30 natural numbers.', options: ['450', '460', '470', '465'], correctIndex: 3, explanation: 'Sum = n(n+1)/2 = 30×31/2 = 465.', source },
  { id: 'sebi-ga-p1-qa-010', section: 'Quantitative Aptitude', topic: 'Data Interpretation', difficulty: 'medium', question: "A mutual fund's Assets Under Management (AUM) grew from ₹800 crore to ₹960 crore over four years. Find the percentage increase.", options: ['15%', '18%', '25%', '20%'], correctIndex: 3, explanation: 'Percentage increase = ((960 − 800)/800) × 100 = (160/800) × 100 = 20%.', source },
  { id: 'sebi-ga-p1-qa-011', section: 'Quantitative Aptitude', topic: 'Mensuration', difficulty: 'medium', question: 'Find the area of a rectangular trading floor measuring 40 metres by 25 metres.', options: ['900 m²', '950 m²', '1,050 m²', '1,000 m²'], correctIndex: 3, explanation: 'Area = 40 × 25 = 1,000 m².', source },
  { id: 'sebi-ga-p1-qa-012', section: 'Quantitative Aptitude', topic: 'Ratio and Proportion', difficulty: 'medium', question: 'In an asset management company with 60 employees, the ratio of analysts to support staff is 5:7. How many analysts work there?', options: ['20', '25', '30', '35'], correctIndex: 1, explanation: 'Total parts = 5+7 = 12. Analysts = (5/12) × 60 = 25.', source },
  { id: 'sebi-ga-p1-qa-013', section: 'Quantitative Aptitude', topic: 'Percentage', difficulty: 'medium', question: 'The number of active demat accounts with a depository participant increased from 5,00,000 to 6,25,000 over a year. Find the percentage increase.', options: ['20%', '22%', '28%', '25%'], correctIndex: 3, explanation: 'Percentage increase = ((6,25,000 − 5,00,000)/5,00,000) × 100 = (1,25,000/5,00,000) × 100 = 25%.', source },
  { id: 'sebi-ga-p1-qa-014', section: 'Quantitative Aptitude', topic: 'Average', difficulty: 'medium', question: 'The average annual return of 5 mutual fund schemes is 12%. If the average return of the first 3 schemes is 10%, find the average return of the remaining 2 schemes.', options: ['13%', '14%', '15%', '16%'], correctIndex: 2, explanation: 'Total return (5 schemes) = 12×5 = 60. Total return (first 3) = 10×3 = 30. Total return (remaining 2) = 60 − 30 = 30. Average = 30/2 = 15%.', source },
  { id: 'sebi-ga-p1-qa-015', section: 'Quantitative Aptitude', topic: 'Time and Work', difficulty: 'hard', question: 'A and B can complete a portfolio reconciliation task together in 10 days. A alone can complete it in 15 days. In how many days can B alone complete it?', options: ['25 days', '28 days', '30 days', '32 days'], correctIndex: 2, explanation: "Combined rate = 1/10. A's rate = 1/15. B's rate = 1/10 − 1/15 = 3/30 − 2/30 = 1/30, so B alone takes 30 days.", source },
  { id: 'sebi-ga-p1-qa-016', section: 'Quantitative Aptitude', topic: 'Simple Interest', difficulty: 'medium', question: 'At what rate of simple interest per annum will a sum of money triple itself in 20 years?', options: ['8%', '9%', '10%', '12%'], correctIndex: 2, explanation: 'For the sum to triple, SI = 2 × Principal. Using SI = PRT/100: 2P = P×R×20/100, so R = 200/20 = 10%.', source },
  { id: 'sebi-ga-p1-qa-017', section: 'Quantitative Aptitude', topic: 'Number System', difficulty: 'medium', question: 'Find the LCM of 16 and 20.', options: ['80', '64', '84', '96'], correctIndex: 0, explanation: '16 = 2⁴, 20 = 2²×5. LCM = 2⁴×5 = 80.', source },
  { id: 'sebi-ga-p1-qa-018', section: 'Quantitative Aptitude', topic: 'Profit and Loss', difficulty: 'medium', question: 'A trader sells a bond at a loss of 8%. Had it been sold for ₹1,200 more, there would have been a profit of 4%. Find the cost price of the bond.', options: ['₹9,000', '₹9,500', '₹10,000', '₹10,500'], correctIndex: 2, explanation: 'Let cost price be x. Loss of 8% gives 0.92x; profit of 4% gives 1.04x. Difference = 0.12x = 1,200, so x = ₹10,000.', source },
  { id: 'sebi-ga-p1-qa-019', section: 'Quantitative Aptitude', topic: 'Data Interpretation', difficulty: 'medium', question: "A pie chart shows a bank's loan portfolio: Retail 35%, Corporate 30%, Agriculture 20%, Others 15%. If the total portfolio is ₹40,000 crore, find the value of Corporate loans.", options: ['₹10,000 crore', '₹11,000 crore', '₹12,000 crore', '₹13,000 crore'], correctIndex: 2, explanation: '30% of ₹40,000 crore = 0.30 × 40,000 = ₹12,000 crore.', source },
  { id: 'sebi-ga-p1-qa-020', section: 'Quantitative Aptitude', topic: 'Time and Distance', difficulty: 'medium', question: 'Two trains start from the same station and travel in opposite directions at 55 km/h and 65 km/h. After how many hours will they be 360 km apart?', options: ['2.5 hours', '3 hours', '3.5 hours', '4 hours'], correctIndex: 1, explanation: 'Since they move in opposite directions, relative speed = 55+65 = 120 km/h. Time = 360/120 = 3 hours.', source },
];
