import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SEBI Officer Grade A (Assistant Manager) Recruitment 2025 official notification — Phase I, Paper 1, General Awareness section',
  url: 'https://www.sebi.gov.in/sebi_data/careerfiles/oct-2025/1761782417659.pdf',
  checkedOn: '6 August 2026',
};

export const SEBI_GRADE_A_PHASE_1_PAPER_1_GENERAL_AWARENESS_1: Question[] = [
  { id: 'sebi-ga-p1-ga-001', section: 'General Awareness', topic: 'SEBI', difficulty: 'medium', question: 'SEBI was first set up as a non-statutory body in 1988 and later given statutory powers through which legislation?', options: ['The Companies Act, 1956', 'The Securities Contracts (Regulation) Act, 1956', 'The SEBI Act, 1992', 'The Depositories Act, 1996'], correctIndex: 2, explanation: 'SEBI functioned as a non-statutory body from 1988 and was given statutory powers on 30 January 1992 through the SEBI Act, 1992.', source },
  { id: 'sebi-ga-p1-ga-002', section: 'General Awareness', topic: 'SEBI', difficulty: 'easy', question: 'Where is the head office of the Securities and Exchange Board of India (SEBI) located?', options: ['New Delhi', 'Chennai', 'Mumbai', 'Kolkata'], correctIndex: 2, explanation: "SEBI's head office, SEBI Bhavan, is located in the Bandra Kurla Complex, Mumbai.", source },
  { id: 'sebi-ga-p1-ga-003', section: 'General Awareness', topic: 'Stock Exchanges', difficulty: 'medium', question: 'The Bombay Stock Exchange (BSE), one of the oldest stock exchanges in Asia, traces its origins to which year?', options: ['1875', '1908', '1935', '1956'], correctIndex: 0, explanation: 'The BSE traces its origins to 1875, when it began as "The Native Share and Stock Brokers Association", making it one of the oldest stock exchanges in Asia.', source },
  { id: 'sebi-ga-p1-ga-004', section: 'General Awareness', topic: 'Stock Exchanges', difficulty: 'medium', question: 'The National Stock Exchange (NSE) of India was incorporated in which year?', options: ['1988', '1996', '1992', '2000'], correctIndex: 2, explanation: 'The National Stock Exchange (NSE) was incorporated in 1992 and began operations shortly after.', source },
  { id: 'sebi-ga-p1-ga-005', section: 'General Awareness', topic: 'Stock Market Indices', difficulty: 'medium', question: 'Nifty 50, the benchmark stock market index, is maintained by which exchange?', options: ['Bombay Stock Exchange', 'Multi Commodity Exchange', 'National Stock Exchange', 'Metropolitan Stock Exchange'], correctIndex: 2, explanation: 'Nifty 50 is the benchmark index of the National Stock Exchange (NSE), tracking 50 large, liquid Indian companies.', source },
  { id: 'sebi-ga-p1-ga-006', section: 'General Awareness', topic: 'Depositories', difficulty: 'medium', question: "Which of the following was India's first securities depository, established in 1996?", options: ['CDSL', 'CCIL', 'NSDL', 'CIBIL'], correctIndex: 2, explanation: 'The National Securities Depository Limited (NSDL), established in 1996, was the first securities depository set up in India.', source },
  { id: 'sebi-ga-p1-ga-007', section: 'General Awareness', topic: 'Depositories', difficulty: 'medium', question: 'CDSL, the second securities depository established in India, was set up in which year?', options: ['1996', '2010', '2003', '1999'], correctIndex: 3, explanation: 'The Central Depository Services Limited (CDSL) was established in 1999 as the second securities depository in India.', source },
  { id: 'sebi-ga-p1-ga-008', section: 'General Awareness', topic: 'Market Regulation', difficulty: 'medium', question: 'A market-wide circuit breaker that halts trading across the exchanges is typically triggered by index movements of which magnitude?', options: ['2%, 4%, and 6%', '25%, 35%, and 50%', '5%, 10%, and 15%', '10%, 15%, and 20%'], correctIndex: 3, explanation: 'Index-based market-wide circuit breakers in India are triggered at three stages of movement — 10%, 15%, and 20% — with the trading halt duration increasing at each stage.', source },
  { id: 'sebi-ga-p1-ga-009', section: 'General Awareness', topic: 'Mutual Funds', difficulty: 'medium', question: 'Mutual funds in India are primarily regulated under which SEBI regulations?', options: ['SEBI (Mutual Funds) Regulations, 1996', 'SEBI (Portfolio Managers) Regulations, 2020', 'SEBI (Depositories and Participants) Regulations, 2018', 'SEBI (Credit Rating Agencies) Regulations, 1999'], correctIndex: 0, explanation: 'Mutual funds in India are primarily governed by the SEBI (Mutual Funds) Regulations, 1996.', source },
  { id: 'sebi-ga-p1-ga-010', section: 'General Awareness', topic: 'Credit Rating', difficulty: 'medium', question: 'Which of the following is a SEBI-registered credit rating agency in India?', options: ['NPCI', 'IRDAI', 'NABARD', 'CRISIL'], correctIndex: 3, explanation: 'CRISIL (Credit Rating Information Services of India Limited) is one of the SEBI-registered credit rating agencies operating in India.', source },
  { id: 'sebi-ga-p1-ga-011', section: 'General Awareness', topic: 'Market Regulation', difficulty: 'medium', question: 'Trading based on unpublished price-sensitive information by persons connected to a company is prohibited under which SEBI regulations?', options: ['SEBI (Prohibition of Insider Trading) Regulations, 2015', 'SEBI (Listing Obligations and Disclosure Requirements) Regulations, 2015', 'SEBI (Issue of Capital and Disclosure Requirements) Regulations, 2018', 'SEBI (Investment Advisers) Regulations, 2013'], correctIndex: 0, explanation: 'Insider trading — trading based on unpublished price-sensitive information — is prohibited under the SEBI (Prohibition of Insider Trading) Regulations, 2015.', source },
  { id: 'sebi-ga-p1-ga-012', section: 'General Awareness', topic: 'Mutual Funds', difficulty: 'easy', question: 'A Systematic Investment Plan (SIP) allows an investor to do which of the following?', options: ['Withdraw funds only once a year', 'Bypass KYC requirements for mutual fund investment', 'Trade only in government securities', 'Invest a fixed amount at regular intervals in a mutual fund scheme'], correctIndex: 3, explanation: 'A Systematic Investment Plan (SIP) allows an investor to invest a fixed amount at regular intervals (such as monthly) into a mutual fund scheme.', source },
  { id: 'sebi-ga-p1-ga-013', section: 'General Awareness', topic: 'Market Instruments', difficulty: 'medium', question: 'Real Estate Investment Trusts (REITs), which allow investors to invest in income-generating real estate, are regulated in India by:', options: ['SEBI', 'RBI', 'IRDAI', 'NHB'], correctIndex: 0, explanation: 'REITs in India are regulated by SEBI under the SEBI (Real Estate Investment Trusts) Regulations, 2014.', source },
  { id: 'sebi-ga-p1-ga-014', section: 'General Awareness', topic: 'Market Regulation', difficulty: 'medium', question: 'SEBI has phased in a T+1 settlement cycle for Indian equity markets, meaning trades are settled:', options: ['On the same day as the trade', 'One calendar month after the trade', 'Three working days after the trade', 'One working day after the trade'], correctIndex: 3, explanation: 'Under the T+1 settlement cycle, trades are settled one working day after the transaction date, reducing settlement risk and time compared to the earlier T+2 cycle.', source },
  { id: 'sebi-ga-p1-ga-015', section: 'General Awareness', topic: 'Investor Grievances', difficulty: 'medium', question: 'SCORES, the online platform through which investors can lodge complaints against listed companies and market intermediaries, is operated by:', options: ['RBI', 'SEBI', 'Ministry of Corporate Affairs', 'NPCI'], correctIndex: 1, explanation: 'SCORES (SEBI Complaints Redress System) is an online platform operated by SEBI for investors to lodge and track complaints against listed companies and registered intermediaries.', source },
  { id: 'sebi-ga-p1-ga-016', section: 'General Awareness', topic: 'Foreign Investment', difficulty: 'medium', question: 'Overseas entities investing in Indian securities markets through routes such as stocks and bonds are registered and regulated by SEBI as:', options: ['Foreign Portfolio Investors (FPIs)', 'Foreign Direct Investors (FDIs)', 'Non-Resident External account holders', 'Qualified Institutional Buyers only'], correctIndex: 0, explanation: 'Overseas entities investing in Indian securities markets are registered with SEBI as Foreign Portfolio Investors (FPIs) under the SEBI (FPI) Regulations, 2019.', source },
  { id: 'sebi-ga-p1-ga-017', section: 'General Awareness', topic: 'Financial Regulators', difficulty: 'medium', question: 'The Financial Stability and Development Council (FSDC), which coordinates among India\'s financial sector regulators, is chaired by:', options: ['The Governor of RBI', 'The Union Finance Minister', 'The Chairman of SEBI', 'The Cabinet Secretary'], correctIndex: 1, explanation: 'The Financial Stability and Development Council (FSDC) is chaired by the Union Finance Minister and includes the heads of RBI, SEBI, IRDAI, and PFRDA among its members.', source },
  { id: 'sebi-ga-p1-ga-018', section: 'General Awareness', topic: 'Market Instruments', difficulty: 'medium', question: 'An Initial Public Offering (IPO) refers to the process by which a company:', options: ['Buys back its own shares from existing shareholders', 'Offers its shares to the public for the first time to raise capital', 'Delists its shares from a stock exchange', 'Merges with another listed company'], correctIndex: 1, explanation: 'An Initial Public Offering (IPO) is the process through which a company offers its shares to the public for the first time to raise capital and get listed on a stock exchange.', source },
  { id: 'sebi-ga-p1-ga-019', section: 'General Awareness', topic: 'Market Instruments', difficulty: 'medium', question: 'Investors who are large institutions such as mutual funds, banks, and insurance companies, treated separately in the IPO allotment process, are collectively known as:', options: ['Retail Individual Investors', 'Qualified Institutional Buyers (QIBs)', 'Anchor Retailers', 'Non-Institutional Individuals'], correctIndex: 1, explanation: 'Large institutional investors such as mutual funds, banks, and insurance companies are collectively referred to as Qualified Institutional Buyers (QIBs) in the IPO allotment process.', source },
  { id: 'sebi-ga-p1-ga-020', section: 'General Awareness', topic: 'Market Instruments', difficulty: 'medium', question: 'A derivative contract that gives the buyer the right, but not the obligation, to buy or sell an underlying asset at a predetermined price is known as a(n):', options: ['Future', 'Option', 'Bond', 'Debenture'], correctIndex: 1, explanation: 'An option is a derivative contract that gives the buyer the right, but not the obligation, to buy (call option) or sell (put option) an underlying asset at a predetermined price.', source },
];
