import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SEBI Officer Grade A (Assistant Manager) Recruitment 2025 official notification — Phase I, Paper 1, English Language section',
  url: 'https://www.sebi.gov.in/sebi_data/careerfiles/oct-2025/1761782417659.pdf',
  checkedOn: '6 August 2026',
};

export const SEBI_GRADE_A_PHASE_1_PAPER_1_ENGLISH_LANGUAGE_1: Question[] = [
  { id: 'sebi-ga-p1-en-001', section: 'English Language', topic: 'Synonyms', difficulty: 'easy', question: 'Choose the word most similar in meaning to "TENACIOUS".', options: ['Easily discouraged', 'Persistent and determined', 'Careless', 'Indecisive'], correctIndex: 1, explanation: '"Tenacious" describes someone who is persistent and determined, holding firmly to a course of action.', source },
  { id: 'sebi-ga-p1-en-002', section: 'English Language', topic: 'Antonyms', difficulty: 'easy', question: 'Choose the word most opposite in meaning to "VOLATILE" (as used to describe markets).', options: ['Unstable', 'Erratic', 'Fluctuating', 'Stable'], correctIndex: 3, explanation: '"Volatile" describes something prone to sudden, unpredictable change; its opposite is "stable".', source },
  { id: 'sebi-ga-p1-en-003', section: 'English Language', topic: 'Fill in the Blanks', difficulty: 'easy', question: 'Fill in the blank: "The regulator ___ new disclosure norms for listed companies last year."', options: ['introduce', 'introducing', 'introduces', 'introduced'], correctIndex: 3, explanation: 'The sentence describes a completed past action ("last year"), so the simple past tense "introduced" is correct.', source },
  { id: 'sebi-ga-p1-en-004', section: 'English Language', topic: 'Fill in the Blanks', difficulty: 'easy', question: 'Fill in the blank: "Investors should rely ___ verified information before making trading decisions."', options: ['at', 'on', 'for', 'with'], correctIndex: 1, explanation: 'The correct preposition idiom is "rely on" something.', source },
  { id: 'sebi-ga-p1-en-005', section: 'English Language', topic: 'Spot the Error', difficulty: 'medium', question: 'Identify the segment with an error: "Each of the applicants / were asked / to submit / their KYC documents."', options: ['Each of the applicants', 'their KYC documents', 'were asked', 'to submit'], correctIndex: 2, explanation: '"Each" is singular and takes a singular verb, so it should be "was asked", not "were asked".', source },
  { id: 'sebi-ga-p1-en-006', section: 'English Language', topic: 'Spot the Error', difficulty: 'medium', question: 'Identify the segment with an error: "The number of complaints registered on the portal / have declined sharply / since the / new grievance system was launched."', options: ['The number of complaints registered on the portal', 'since the', 'have declined sharply', 'new grievance system was launched'], correctIndex: 2, explanation: '"The number of" takes a singular verb, so it should be "has declined sharply", not "have declined sharply".', source },
  { id: 'sebi-ga-p1-en-007', section: 'English Language', topic: 'Cloze Test', difficulty: 'medium', question: 'Fill in the blank: "The analyst carefully ___ the company\'s quarterly results before publishing the report."', options: ['review', 'reviews', 'reviewed', 'reviewing'], correctIndex: 2, explanation: 'The sentence describes a completed past action, so the simple past tense "reviewed" is correct.', source },
  { id: 'sebi-ga-p1-en-008', section: 'English Language', topic: 'Cloze Test', difficulty: 'medium', question: 'Fill in the blank: "Shareholders were advised to ___ their proxy forms before the annual general meeting."', options: ['submit', 'submitted', 'submitting', 'submits'], correctIndex: 0, explanation: 'After "advised to", the base form of the verb is used: "to submit their proxy forms".', source },
  { id: 'sebi-ga-p1-en-009', section: 'English Language', topic: 'One Word Substitution', difficulty: 'medium', question: 'Choose the one word for: "A person who buys and sells securities on behalf of clients for a commission".', options: ['Broker', 'Underwriter', 'Custodian', 'Auditor'], correctIndex: 0, explanation: 'A "broker" is a person or firm that buys and sells securities on behalf of clients in exchange for a commission.', source },
  { id: 'sebi-ga-p1-en-010', section: 'English Language', topic: 'One Word Substitution', difficulty: 'medium', question: 'Choose the one word for: "The formal, detailed document a company issues to inform potential investors before an IPO".', options: ['Prospectus', 'Ledger', 'Voucher', 'Circular'], correctIndex: 0, explanation: 'A "prospectus" is the formal legal document a company issues to inform potential investors about an offering, typically before an IPO.', source },
  { id: 'sebi-ga-p1-en-011', section: 'English Language', topic: 'Idioms and Phrases', difficulty: 'medium', question: 'Choose the meaning of the idiom: "To read between the lines".', options: ['To read a document twice for accuracy', 'To understand a hidden or implied meaning beyond what is literally stated', 'To skip unimportant parts of a report', 'To highlight key figures in a report'], correctIndex: 1, explanation: '"To read between the lines" means to understand the hidden or implied meaning of something beyond its literal words.', source },
  { id: 'sebi-ga-p1-en-012', section: 'English Language', topic: 'Idioms and Phrases', difficulty: 'medium', question: 'Choose the meaning of the idiom: "Back to square one".', options: ['Having to start something again from the very beginning', 'Reaching the final stage of a plan', 'Achieving success through teamwork', 'Avoiding all forms of risk'], correctIndex: 0, explanation: '"Back to square one" means having to start a task or plan again from the very beginning, usually after an attempt has failed.', source },
  { id: 'sebi-ga-p1-en-013', section: 'English Language', topic: 'Active and Passive Voice', difficulty: 'medium', question: 'Choose the correct passive voice of: "The board approved the merger proposal yesterday."', options: ['The merger proposal is approved by the board yesterday.', 'The merger proposal will be approved by the board yesterday.', 'The merger proposal has been approved by the board yesterday.', 'The merger proposal was approved by the board yesterday.'], correctIndex: 3, explanation: 'The simple past active "approved" becomes "was approved" in the passive voice.', source },
  { id: 'sebi-ga-p1-en-014', section: 'English Language', topic: 'Active and Passive Voice', difficulty: 'medium', question: 'Choose the correct passive voice of: "The committee will review the compliance report next month."', options: ['The compliance report is reviewed by the committee next month.', 'The compliance report has been reviewed by the committee next month.', 'The compliance report was reviewed by the committee next month.', 'The compliance report will be reviewed by the committee next month.'], correctIndex: 3, explanation: 'The future active "will review" becomes "will be reviewed" in the passive voice.', source },
  { id: 'sebi-ga-p1-en-015', section: 'English Language', topic: 'Direct and Indirect Speech', difficulty: 'medium', question: 'Choose the correct indirect speech: The officer said, "I will verify the documents tomorrow."', options: ['The officer said that he will verify the documents tomorrow.', 'The officer said that he verified the documents tomorrow.', 'The officer says that he would verify the documents tomorrow.', 'The officer said that he would verify the documents the next day.'], correctIndex: 3, explanation: 'In indirect speech, "will" shifts to "would" and "tomorrow" shifts to "the next day".', source },
  { id: 'sebi-ga-p1-en-016', section: 'English Language', topic: 'Spelling Correction', difficulty: 'easy', question: 'Pick the option below that shows the word spelled without any error.', options: ['Recieve', 'Receive', 'Receeve', 'Receve'], correctIndex: 1, explanation: 'The correct spelling is "Receive".', source },
  { id: 'sebi-ga-p1-en-017', section: 'English Language', topic: 'Spelling Correction', difficulty: 'easy', question: 'Identify the word among the choices that carries no spelling mistake.', options: ['Comission', 'Commision', 'Commission', 'Comissoin'], correctIndex: 2, explanation: 'The correct spelling is "Commission".', source },
  { id: 'sebi-ga-p1-en-018', section: 'English Language', topic: 'Synonyms', difficulty: 'medium', question: 'Choose the word most similar in meaning to "TRANSPARENT" (in a governance context).', options: ['Concealed', 'Open and easily understood', 'Ambiguous', 'Restricted'], correctIndex: 1, explanation: '"Transparent" in a governance context means open, clear, and easily understood, without anything hidden.', source },
  { id: 'sebi-ga-p1-en-019', section: 'English Language', topic: 'Antonyms', difficulty: 'medium', question: 'Choose the word most opposite in meaning to "SOLVENT".', options: ['Liquid', 'Stable', 'Insolvent', 'Secure'], correctIndex: 2, explanation: '"Solvent" means having enough money to pay debts; the direct opposite is "insolvent" — unable to pay one\'s debts.', source },
  { id: 'sebi-ga-p1-en-020', section: 'English Language', topic: 'Sentence Improvement', difficulty: 'medium', question: 'Improve the underlined part: "The audit report was more accurate than any report submitted before it."', options: ['more accurate than any other report submitted before it', 'the most accurate than any report submitted before it', 'more accuratest than any report submitted before it', 'no improvement needed'], correctIndex: 0, explanation: 'When comparing one item to the rest of a group it belongs to, "any other" must be used instead of "any" — otherwise the report is illogically compared with itself.', source },
];
