import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SIDBI Officers Grade A & B (General and Specialist Stream) Recruitment 2025-26 official notification — Phase I, Computer Knowledge section',
  url: 'https://www.sidbi.in/head/uploads/career_document/SIDBI_DETAILED_WEB_ADVT_2025.pdf',
  checkedOn: '6 August 2026',
};

export const SIDBI_GRADE_A_B_PHASE_1_COMPUTER_KNOWLEDGE_1: Question[] = [
  { id: 'sidbi-p1-ck-001', section: 'Computer Knowledge', topic: 'Networking', difficulty: 'medium', question: 'Which networking device connects multiple devices within a LAN and forwards data only to the intended recipient device based on its MAC address?', options: ['Switch', 'Hub', 'Repeater', 'Modem'], correctIndex: 0, explanation: 'A switch connects devices within a LAN and intelligently forwards data only to the specific device it is addressed to, based on MAC address.', source },
  { id: 'sidbi-p1-ck-002', section: 'Computer Knowledge', topic: 'Networking', difficulty: 'medium', question: "Which device converts a computer's digital signals into analog signals for transmission over telephone lines, and converts them back on the receiving end?", options: ['Router', 'Switch', 'Modem', 'Bridge'], correctIndex: 2, explanation: 'A modem (modulator-demodulator) converts digital signals to analog for transmission and back to digital at the receiving end.', source },
  { id: 'sidbi-p1-ck-003', section: 'Computer Knowledge', topic: 'Database Concepts', difficulty: 'medium', question: 'Which type of key in a relational database is used to establish a link between two tables?', options: ['Primary Key', 'Composite Index', 'Candidate Key', 'Foreign Key'], correctIndex: 3, explanation: "A foreign key is a column (or set of columns) in one table that refers to the primary key of another table, establishing a link between them.", source },
  { id: 'sidbi-p1-ck-004', section: 'Computer Knowledge', topic: 'Database Concepts', difficulty: 'medium', question: "Which SQL command is used to permanently remove a table's entire structure from a database?", options: ['DELETE', 'TRUNCATE', 'DROP', 'REMOVE'], correctIndex: 2, explanation: 'The DROP command removes a table\'s entire structure from the database, unlike DELETE or TRUNCATE, which only remove rows while keeping the structure.', source },
  { id: 'sidbi-p1-ck-005', section: 'Computer Knowledge', topic: 'Number Systems', difficulty: 'medium', question: 'How many unique symbols are used in the hexadecimal number system?', options: ['8', '10', '16', '32'], correctIndex: 2, explanation: 'The hexadecimal number system uses 16 unique symbols: 0-9 and A-F.', source },
  { id: 'sidbi-p1-ck-006', section: 'Computer Knowledge', topic: 'Generations of Computers', difficulty: 'medium', question: 'Which generation of computers is primarily associated with the use of Integrated Circuits (ICs)?', options: ['First generation', 'Second generation', 'Third generation', 'Fourth generation'], correctIndex: 2, explanation: 'The third generation of computers (mid-1960s to early 1970s) is defined by the use of Integrated Circuits, replacing individual transistors.', source },
  { id: 'sidbi-p1-ck-007', section: 'Computer Knowledge', topic: 'Software Types', difficulty: 'easy', question: 'Antivirus software, disk defragmenters, and file compression tools are examples of which type of software?', options: ['Application software', 'Middleware', 'Firmware', 'Utility software'], correctIndex: 3, explanation: 'Utility software performs maintenance and support tasks for a computer system, such as antivirus scanning, disk defragmentation, and file compression.', source },
  { id: 'sidbi-p1-ck-008', section: 'Computer Knowledge', topic: 'Internet Fundamentals', difficulty: 'medium', question: 'Which internet service translates human-readable domain names into numerical IP addresses?', options: ['DHCP', 'SMTP', 'FTP', 'DNS'], correctIndex: 3, explanation: 'The Domain Name System (DNS) translates human-readable domain names, such as a website address, into the numerical IP addresses computers use to identify each other.', source },
  { id: 'sidbi-p1-ck-009', section: 'Computer Knowledge', topic: 'Internet Fundamentals', difficulty: 'medium', question: "Small text files stored on a user's browser by websites, used to remember preferences and login sessions, are called:", options: ['Cookies', 'Cache', 'Bookmarks', 'Plugins'], correctIndex: 0, explanation: "Cookies are small text files that websites store on a user's browser to remember preferences, login sessions, and browsing activity.", source },
  { id: 'sidbi-p1-ck-010', section: 'Computer Knowledge', topic: 'Digital Payments', difficulty: 'medium', question: "Which payment system in India enables instant, 24x7 interbank fund transfers of typically smaller amounts, commonly accessed through mobile banking apps?", options: ['RTGS', 'Cheque Truncation System', 'Demand Draft', 'IMPS'], correctIndex: 3, explanation: 'IMPS (Immediate Payment Service) enables instant, round-the-clock interbank electronic fund transfers, commonly used for smaller-value transactions via mobile banking.', source },
  { id: 'sidbi-p1-ck-011', section: 'Computer Knowledge', topic: 'Cybersecurity', difficulty: 'medium', question: 'The fraudulent practice of sending emails or messages pretending to be from a reputable source, to trick recipients into revealing sensitive information, is called:', options: ['Phishing', 'Spoofing', 'Spamming', 'Hacking'], correctIndex: 0, explanation: 'Phishing is a fraudulent attempt to obtain sensitive information by disguising as a trustworthy source in electronic communication.', source },
  { id: 'sidbi-p1-ck-012', section: 'Computer Knowledge', topic: 'Cybersecurity', difficulty: 'medium', question: "Malicious software that encrypts a victim's files and demands payment for the decryption key is known as:", options: ['Adware', 'Bloatware', 'Spyware', 'Ransomware'], correctIndex: 3, explanation: "Ransomware is malicious software that encrypts a victim's files, demanding a ransom payment in exchange for the decryption key.", source },
  { id: 'sidbi-p1-ck-013', section: 'Computer Knowledge', topic: 'MS Excel', difficulty: 'medium', question: 'Which Excel function calculates the arithmetic mean of a range of numeric values?', options: ['SUM()', 'AVERAGE()', 'COUNT()', 'MEDIAN()'], correctIndex: 1, explanation: 'The AVERAGE() function in Excel calculates the arithmetic mean of the numeric values in a specified range.', source },
  { id: 'sidbi-p1-ck-014', section: 'Computer Knowledge', topic: 'MS Excel', difficulty: 'medium', question: 'Which Excel function counts the number of cells within a range that meet a specified condition?', options: ['COUNT()', 'COUNTIF()', 'SUMIF()', 'IFERROR()'], correctIndex: 1, explanation: 'The COUNTIF() function counts the number of cells within a range that satisfy a single specified condition.', source },
  { id: 'sidbi-p1-ck-015', section: 'Computer Knowledge', topic: 'Computer Memory', difficulty: 'easy', question: 'Which type of computer memory is volatile, losing its stored contents when the power is switched off?', options: ['ROM', 'RAM', 'Flash memory', 'Hard disk'], correctIndex: 1, explanation: 'RAM (Random Access Memory) is volatile memory, meaning its stored data is lost when the power supply is switched off.', source },
  { id: 'sidbi-p1-ck-016', section: 'Computer Knowledge', topic: 'Data Storage Units', difficulty: 'easy', question: 'Approximately how many gigabytes make up one terabyte?', options: ['512', '1,024', '2,048', '4,096'], correctIndex: 1, explanation: 'One terabyte is approximately equal to 1,024 gigabytes, following the standard binary storage convention.', source },
  { id: 'sidbi-p1-ck-017', section: 'Computer Knowledge', topic: 'Operating Systems', difficulty: 'medium', question: 'The core component of an operating system that manages hardware resources and mediates communication between hardware and software is called the:', options: ['Kernel', 'Compiler', 'Shell', 'BIOS'], correctIndex: 0, explanation: 'The kernel is the core component of an operating system, managing hardware resources and mediating communication between hardware and software.', source },
  { id: 'sidbi-p1-ck-018', section: 'Computer Knowledge', topic: 'Digital Security', difficulty: 'medium', question: 'A digital signature attached to an electronic document is primarily used to verify:', options: ['The file size of the document', 'The authenticity and integrity of the document', 'The document\'s storage location', 'The document\'s font formatting'], correctIndex: 1, explanation: "A digital signature verifies the authenticity of the sender and the integrity of the document, confirming it has not been altered.", source },
  { id: 'sidbi-p1-ck-019', section: 'Computer Knowledge', topic: 'Email', difficulty: 'medium', question: 'In an email, which field allows a recipient to receive a copy of the message without other recipients seeing their email address?', options: ['To', 'CC', 'BCC', 'Subject'], correctIndex: 2, explanation: 'BCC (Blind Carbon Copy) allows a recipient to receive a copy of an email without their address being visible to the other recipients.', source },
  { id: 'sidbi-p1-ck-020', section: 'Computer Knowledge', topic: 'Cloud Computing', difficulty: 'medium', question: 'The on-demand delivery of computing resources such as storage and processing power over the internet, without direct active management by the user, is known as:', options: ['Cloud Computing', 'Edge Computing', 'Grid Computing', 'Quantum Computing'], correctIndex: 0, explanation: 'Cloud Computing refers to the on-demand delivery of computing resources such as storage, servers, and processing power over the internet.', source },
];
