import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SIDBI Officers Grade A & B (General and Specialist Stream) Recruitment 2025-26 official notification — Phase I, Reasoning Aptitude section',
  url: 'https://www.sidbi.in/head/uploads/career_document/SIDBI_DETAILED_WEB_ADVT_2025.pdf',
  checkedOn: '6 August 2026',
};

export const SIDBI_GRADE_A_B_PHASE_1_REASONING_APTITUDE_1: Question[] = [
  { id: 'sidbi-p1-re-001', section: 'Reasoning Aptitude', topic: 'Syllogism', difficulty: 'medium', question: 'Statements: All lenders are creditors. Some creditors are auditors. Conclusions: I. Some auditors are lenders. II. Some creditors are lenders. Which conclusion(s) logically follow?', options: ['Only I', 'Only II', 'Both I and II', 'Neither I nor II'], correctIndex: 1, explanation: '"All lenders are creditors" can be converted to "Some creditors are lenders", so Conclusion II follows. Conclusion I does not follow, since no direct link is established between auditors and lenders.', source },
  { id: 'sidbi-p1-re-002', section: 'Reasoning Aptitude', topic: 'Blood Relations', difficulty: 'medium', question: 'Pointing to a man, Neha said, "He is the son of my father\'s only sister." How is the man related to Neha?', options: ['Brother', 'Cousin', 'Nephew', 'Uncle'], correctIndex: 1, explanation: "Neha's father's sister is Neha's paternal aunt. The aunt's son is Neha's cousin.", source },
  { id: 'sidbi-p1-re-003', section: 'Reasoning Aptitude', topic: 'Direction Sense', difficulty: 'medium', question: 'A field officer walks 6 km North, then 8 km East. Find the straight-line distance from the starting point.', options: ['14 km', '10 km', '2 km', '6 km'], correctIndex: 1, explanation: 'Using the Pythagorean theorem: distance = √(6² + 8²) = √(36 + 64) = √100 = 10 km.', source },
  { id: 'sidbi-p1-re-004', section: 'Reasoning Aptitude', topic: 'Coding-Decoding', difficulty: 'medium', question: 'In a certain code, "CREDIT" is written as "DSFEJU". Using the same coding rule, how would "LOANS" be written?', options: ['MPBOS', 'MPBOT', 'MPCOT', 'NPBOT'], correctIndex: 1, explanation: 'Each letter is shifted forward by one position: C→D, R→S, E→F, D→E, I→J, T→U. Applying the same rule to LOANS: L→M, O→P, A→B, N→O, S→T, giving MPBOT.', source },
  { id: 'sidbi-p1-re-005', section: 'Reasoning Aptitude', topic: 'Number Series', difficulty: 'medium', question: 'Find the next number in the series: 5, 12, 26, 54, 110, ?', options: ['218', '220', '224', '222'], correctIndex: 3, explanation: 'Each term is double the previous term plus 2: 5×2+2=12, 12×2+2=26, 26×2+2=54, 54×2+2=110, 110×2+2=222.', source },
  { id: 'sidbi-p1-re-006', section: 'Reasoning Aptitude', topic: 'Ranking and Order', difficulty: 'medium', question: 'In a batch of 45 trainees, Arjun is ranked 15th from the top. What is his rank from the bottom?', options: ['29', '30', '32', '31'], correctIndex: 3, explanation: 'Rank from bottom = Total trainees − Rank from top + 1 = 45 − 15 + 1 = 31.', source },
  { id: 'sidbi-p1-re-007', section: 'Reasoning Aptitude', topic: 'Classification', difficulty: 'easy', question: 'Pick the odd one out from the group below.', options: ['SIDBI', 'NABARD', 'RBI', 'BSE'], correctIndex: 3, explanation: 'SIDBI, NABARD, and RBI are all development or regulatory banking institutions, while BSE is a stock exchange, not a bank.', source },
  { id: 'sidbi-p1-re-008', section: 'Reasoning Aptitude', topic: 'Inequality', difficulty: 'medium', question: 'Statements: A > B ≥ C > D. Conclusions: I. A > D. II. B > D. Which conclusion(s) logically follow?', options: ['Only I follows', 'Only II follows', 'Both I and II follow', 'Neither follows'], correctIndex: 2, explanation: 'From the chain A > B ≥ C > D, we get A > D directly. Also, since B ≥ C and C > D, it follows that B > D. Both conclusions hold.', source },
  { id: 'sidbi-p1-re-009', section: 'Reasoning Aptitude', topic: 'Seating Arrangement', difficulty: 'hard', question: 'Five officers — P, Q, R, S, T — sit in a row facing north. R sits immediately to the left of P. S sits second to the right of P. T sits at the extreme right end. Q sits immediately to the left of S. Who sits at the extreme left end?', options: ['P', 'Q', 'R', 'S'], correctIndex: 2, explanation: 'Let P be at position 2. Then R (immediately left of P) is at position 1, Q (immediately left of S) is at position 3, S (second right of P) is at position 4, and T (extreme right) is at position 5. This is the only arrangement consistent with all four clues, so R sits at the extreme left end.', source },
  { id: 'sidbi-p1-re-010', section: 'Reasoning Aptitude', topic: 'Alphanumeric Series', difficulty: 'medium', question: 'Find the missing term in the series: B2Y, D4W, F6U, H8S, ?', options: ['J10Q', 'J10R', 'I10Q', 'J9Q'], correctIndex: 0, explanation: 'The first letters advance by 2 (B, D, F, H, J), the numbers advance by 2 (2, 4, 6, 8, 10), and the last letters move backward by 2 from Z (Y, W, U, S, Q). The next term is J10Q.', source },
  { id: 'sidbi-p1-re-011', section: 'Reasoning Aptitude', topic: 'Data Sufficiency', difficulty: 'hard', question: 'What is the profit percentage earned on an item? Statement I: The cost price is ₹4,000 and the selling price is ₹4,800. Statement II: The profit earned is ₹800.', options: ['Statement I alone is sufficient', 'Statement II alone is sufficient', 'Both statements together are needed', 'Neither statement is sufficient'], correctIndex: 0, explanation: 'Statement I gives both the cost price and selling price, so profit % can be computed directly: (800/4,000)×100 = 20%. Statement II alone gives only the absolute profit, not the cost price, so profit percentage cannot be determined from it alone.', source },
  { id: 'sidbi-p1-re-012', section: 'Reasoning Aptitude', topic: 'Coding-Decoding', difficulty: 'medium', question: 'In a certain code, "LOAN" is written as "NQCP". Using the same coding rule, how would "BANK" be written?', options: ['DCPM', 'DCPN', 'DBPM', 'DCOM'], correctIndex: 0, explanation: 'Each letter is shifted forward by two positions: L→N, O→Q, A→C, N→P. Applying the same rule to BANK: B→D, A→C, N→P, K→M, giving DCPM.', source },
  { id: 'sidbi-p1-re-013', section: 'Reasoning Aptitude', topic: 'Blood Relations', difficulty: 'medium', question: 'Introducing a man, a woman said, "His mother is the only daughter of my mother." How is the man related to the woman?', options: ['Son', 'Nephew', 'Brother', 'Father'], correctIndex: 0, explanation: 'Since the woman is her mother\'s only daughter, "the only daughter of my mother" refers to the woman herself, so the man is her son.', source },
  { id: 'sidbi-p1-re-014', section: 'Reasoning Aptitude', topic: 'Direction Sense', difficulty: 'medium', question: 'A cyclist starts from point X, travels 10 km South, then 10 km West, then 10 km North. How far is he from X, and in which direction?', options: ['10 km West', '10 km East', '20 km West', '0 km'], correctIndex: 0, explanation: 'The 10 km South and 10 km North movements cancel out. Only the 10 km West movement remains, so he is 10 km West of the starting point.', source },
  { id: 'sidbi-p1-re-015', section: 'Reasoning Aptitude', topic: 'Number Series', difficulty: 'medium', question: 'Find the missing number in the series: 4, 10, 22, 46, 94, ?', options: ['186', '188', '190', '192'], correctIndex: 2, explanation: 'Each term is double the previous term plus 2: 4×2+2=10, 10×2+2=22, 22×2+2=46, 46×2+2=94, 94×2+2=190.', source },
  { id: 'sidbi-p1-re-016', section: 'Reasoning Aptitude', topic: 'Ranking and Order', difficulty: 'medium', question: 'In a merit list of 60 candidates, Priya is ranked 18th from the bottom. What is her rank from the top?', options: ['41', '42', '43', '44'], correctIndex: 2, explanation: 'Rank from top = Total candidates − Rank from bottom + 1 = 60 − 18 + 1 = 43.', source },
  { id: 'sidbi-p1-re-017', section: 'Reasoning Aptitude', topic: 'Classification', difficulty: 'easy', question: 'Select the option that does not fit with the rest.', options: ['Term Loan', 'Working Capital', 'Overdraft', 'Balance Sheet'], correctIndex: 3, explanation: 'Term Loan, Working Capital, and Overdraft are all types of credit facilities, while a Balance Sheet is a financial statement, not a credit facility.', source },
  { id: 'sidbi-p1-re-018', section: 'Reasoning Aptitude', topic: 'Inequality', difficulty: 'medium', question: 'Statements: W ≤ X < Y; Z > Y. Conclusions: I. Z > W. II. X < Z. Which conclusion(s) logically follow?', options: ['Only I follows', 'Only II follows', 'Neither follows', 'Both I and II follow'], correctIndex: 3, explanation: 'Combining the statements gives the chain W ≤ X < Y < Z. Since X < Y < Z, Conclusion II (X < Z) follows directly. Since W ≤ X < Z, W must also be strictly less than Z, so Conclusion I (Z > W) follows too.', source },
  { id: 'sidbi-p1-re-019', section: 'Reasoning Aptitude', topic: 'Puzzle', difficulty: 'hard', question: 'Five loan files — J, K, L, M, N — are processed one after another. K is processed immediately after J. N is processed immediately before M. L is processed last. J is processed first. In what position is file M processed?', options: ['2nd', '3rd', '4th', '5th'], correctIndex: 2, explanation: 'J is 1st and K (immediately after J) is 2nd. L is processed last, so L is 5th. The remaining positions 3rd and 4th must hold N immediately before M, so N is 3rd and M is 4th.', source },
  { id: 'sidbi-p1-re-020', section: 'Reasoning Aptitude', topic: 'Data Sufficiency', difficulty: 'hard', question: 'How many employees work in the credit department of a branch? Statement I: The ratio of male to female employees in the department is 3:2. Statement II: There are 12 male employees in the department.', options: ['Statement I alone is sufficient', 'Statement II alone is sufficient', 'Both statements together are needed', 'Neither statement is sufficient'], correctIndex: 2, explanation: 'Statement I alone gives only a ratio, not an absolute count. Statement II alone gives only the male count. Combined, the ratio 3:2 with 12 males gives 8 females, so total = 20 — both statements together are needed.', source },
  { id: 'sidbi-p1-re-021', section: 'Reasoning Aptitude', topic: 'Syllogism', difficulty: 'medium', question: 'Statements: No banks are NBFCs. Some NBFCs are lenders. Conclusions: I. No lenders are banks. II. Some lenders are not banks. Which conclusion(s) logically follow?', options: ['Only I follows', 'Only II follows', 'Both follow', 'Neither follows'], correctIndex: 1, explanation: 'Since no banks are NBFCs, and some NBFCs are lenders, those specific lenders (which are NBFCs) cannot be banks — so Conclusion II follows. Conclusion I, a universal claim about all lenders, is too strong to be guaranteed and does not follow.', source },
  { id: 'sidbi-p1-re-022', section: 'Reasoning Aptitude', topic: 'Number Series', difficulty: 'medium', question: 'Find the missing number in the series: 8, 11, 16, 23, 32, ?', options: ['41', '43', '45', '47'], correctIndex: 2, explanation: 'The differences between consecutive terms increase by 2 each time (3, 5, 7, 9, 11): 8+3=11, 11+5=16, 16+7=23, 23+9=32, 32+11=45.', source },
  { id: 'sidbi-p1-re-023', section: 'Reasoning Aptitude', topic: 'Ranking and Order', difficulty: 'medium', question: 'In a queue of 25 customers at a bank counter, Vikram is 9th from the front. How many customers are behind him (excluding himself)?', options: ['15', '16', '17', '18'], correctIndex: 1, explanation: 'Customers behind Vikram = Total customers − his position = 25 − 9 = 16.', source },
  { id: 'sidbi-p1-re-024', section: 'Reasoning Aptitude', topic: 'Direction Sense', difficulty: 'medium', question: 'A person walks 12 km East, then 5 km South. Find the straight-line distance from the starting point.', options: ['13 km', '15 km', '17 km', '10 km'], correctIndex: 0, explanation: 'Using the Pythagorean theorem: distance = √(12² + 5²) = √(144 + 25) = √169 = 13 km.', source },
  { id: 'sidbi-p1-re-025', section: 'Reasoning Aptitude', topic: 'Classification', difficulty: 'easy', question: 'Find the one that does not belong to the group.', options: ['Debenture', 'Equity Share', 'Term Deposit', 'Prospectus'], correctIndex: 3, explanation: 'Debenture, Equity Share, and Term Deposit are all financial instruments, while a Prospectus is a disclosure document, not an instrument.', source },
];
