import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SIDBI Officers Grade A & B (General and Specialist Stream) Recruitment 2025-26 official notification — Phase I, Reasoning Aptitude section',
  url: 'https://www.sidbi.in/head/uploads/career_document/SIDBI_DETAILED_WEB_ADVT_2025.pdf',
  checkedOn: '24 August 2026',
};

export const SIDBI_GRADE_A_B_PHASE_1_REASONING_APTITUDE_2: Question[] = [
  { id: 'sidbi-p1-re2-001', section: 'Reasoning Aptitude', topic: 'Syllogism', difficulty: 'medium', question: 'Statements: All financiers are institutions. Some institutions are regulators. Conclusions: I. Some regulators are financiers. II. Some institutions are financiers. Which conclusion(s) logically follow?', options: ['Only II follows', 'Only I follows', 'Both I and II follow', 'Neither I nor II follows'], correctIndex: 0, explanation: 'Conclusion II follows by simple conversion of the first premise. Conclusion I does not necessarily follow, since regulators overlapping with institutions need not be financiers.', source },
  { id: 'sidbi-p1-re2-002', section: 'Reasoning Aptitude', topic: 'Blood Relations', difficulty: 'medium', question: 'Pointing to a woman, Rohan said, "She is the daughter of my mother\'s only brother." How is the woman related to Rohan?', options: ['Sister', 'Cousin', 'Niece', 'Aunt'], correctIndex: 1, explanation: "Rohan's mother's brother is Rohan's maternal uncle. The uncle's daughter is Rohan's cousin.", source },
  { id: 'sidbi-p1-re2-003', section: 'Reasoning Aptitude', topic: 'Direction Sense', difficulty: 'medium', question: 'A branch officer walks 9 km South, then 12 km East. Find the straight-line distance from the starting point.', options: ['20 km', '18 km', '21 km', '15 km'], correctIndex: 3, explanation: 'Using the Pythagorean theorem: distance = √(9² + 12²) = √(81 + 144) = √225 = 15 km.', source },
  { id: 'sidbi-p1-re2-004', section: 'Reasoning Aptitude', topic: 'Coding-Decoding', difficulty: 'medium', question: 'In a certain code, "MARKET" is written as "NBSLFU". Using the same coding rule, how would "FUNDS" be written?', options: ['GVOET', 'GVOEU', 'GVPET', 'HVOET'], correctIndex: 0, explanation: 'Each letter is shifted forward by one position: M→N, A→B, R→S, K→L, E→F, T→U. Applying the same rule to FUNDS: F→G, U→V, N→O, D→E, S→T, giving GVOET.', source },
  { id: 'sidbi-p1-re2-005', section: 'Reasoning Aptitude', topic: 'Number Series', difficulty: 'medium', question: 'Find the next number in the series: 6, 13, 27, 55, 111, ?', options: ['221', '225', '223', '227'], correctIndex: 2, explanation: 'Each term is double the previous term plus 1: 6×2+1=13, 13×2+1=27, 27×2+1=55, 55×2+1=111, 111×2+1=223.', source },
  { id: 'sidbi-p1-re2-006', section: 'Reasoning Aptitude', topic: 'Ranking and Order', difficulty: 'medium', question: 'In a batch of 52 trainees, Deepa is ranked 19th from the top. What is her rank from the bottom?', options: ['32', '34', '35', '33'], correctIndex: 1, explanation: 'Rank from bottom = Total trainees − Rank from top + 1 = 52 − 19 + 1 = 34.', source },
  { id: 'sidbi-p1-re2-007', section: 'Reasoning Aptitude', topic: 'Classification', difficulty: 'easy', question: 'Pick the odd one out from the group below.', options: ['Term Loan', 'Overdraft', 'Cash Credit', 'Provisioning'], correctIndex: 3, explanation: 'Term Loan, Overdraft, and Cash Credit are all types of credit facilities, while Provisioning is an accounting practice, not a credit facility.', source },
  { id: 'sidbi-p1-re2-008', section: 'Reasoning Aptitude', topic: 'Inequality', difficulty: 'medium', question: 'Statements: M > N ≥ O > P. Conclusions: I. M > P. II. N > P. Which conclusion(s) logically follow?', options: ['Only I follows', 'Only II follows', 'Both I and II follow', 'Neither follows'], correctIndex: 2, explanation: 'From the chain M > N ≥ O > P, we get M > P directly. Also, since N ≥ O and O > P, it follows that N > P. Both conclusions hold.', source },
  { id: 'sidbi-p1-re2-009', section: 'Reasoning Aptitude', topic: 'Seating Arrangement', difficulty: 'hard', question: 'Five officers — A, B, C, D, E — sit in a row facing north. B sits immediately to the left of A. D sits second to the right of A. E sits at the extreme right end. C sits immediately to the left of D. Who sits at the extreme left end?', options: ['A', 'B', 'C', 'D'], correctIndex: 1, explanation: 'Let A be at position 2. Then B (immediately left of A) is at position 1, C (immediately left of D) is at position 3, D (second right of A) is at position 4, and E (extreme right) is at position 5. This is the only arrangement consistent with all four clues, so B sits at the extreme left end.', source },
  { id: 'sidbi-p1-re2-010', section: 'Reasoning Aptitude', topic: 'Alphanumeric Series', difficulty: 'medium', question: 'Find the missing term in the series: C3Z, F6W, I9T, L12Q, ?', options: ['O15N', 'O15M', 'N15N', 'O14N'], correctIndex: 0, explanation: 'The first letters advance by 3 (C, F, I, L, O), the numbers advance by 3 (3, 6, 9, 12, 15), and the last letters move backward by 3 from Z (Z, W, T, Q, N). The next term is O15N.', source },
  { id: 'sidbi-p1-re2-011', section: 'Reasoning Aptitude', topic: 'Data Sufficiency', difficulty: 'hard', question: 'What is the interest earned on a deposit? Statement I: The principal is ₹6,000 and the rate of interest is 7% per annum for 2 years. Statement II: The interest earned is ₹840.', options: ['Statement I alone is sufficient', 'Statement II alone is sufficient', 'Both statements together are needed', 'Neither statement is sufficient'], correctIndex: 0, explanation: 'Statement I gives the principal, rate, and time, so simple interest can be computed directly: (6,000×7×2)/100 = ₹840. Statement II alone merely states the answer without independently deriving it, so it is not "sufficient" in the sense of providing the underlying data needed to compute it from scratch.', source },
  { id: 'sidbi-p1-re2-012', section: 'Reasoning Aptitude', topic: 'Coding-Decoding', difficulty: 'medium', question: 'In a certain code, "TRUST" is written as "VTWUV". Using the same coding rule, how would "GRANT" be written?', options: ['ITCPV', 'ITCPU', 'ITBPV', 'HTCPV'], correctIndex: 0, explanation: 'Each letter is shifted forward by two positions: T→V, R→T, U→W, S→U, T→V. Applying the same rule to GRANT: G→I, R→T, A→C, N→P, T→V, giving ITCPV.', source },
  { id: 'sidbi-p1-re2-013', section: 'Reasoning Aptitude', topic: 'Blood Relations', difficulty: 'medium', question: 'Introducing a woman, a man said, "Her father is the only son of my father." How is the woman related to the man?', options: ['Daughter', 'Niece', 'Sister', 'Mother'], correctIndex: 0, explanation: 'Since the man is his father\'s only son, "the only son of my father" refers to the man himself, so the woman is his daughter.', source },
  { id: 'sidbi-p1-re2-014', section: 'Reasoning Aptitude', topic: 'Direction Sense', difficulty: 'medium', question: 'A cyclist starts from point Y, travels 8 km North, then 8 km East, then 8 km South. How far is he from Y, and in which direction?', options: ['8 km East', '16 km East', '0 km', '8 km West'], correctIndex: 0, explanation: 'The 8 km North and 8 km South movements cancel out. Only the 8 km East movement remains, so he is 8 km East of the starting point.', source },
  { id: 'sidbi-p1-re2-015', section: 'Reasoning Aptitude', topic: 'Number Series', difficulty: 'medium', question: 'Find the missing number in the series: 3, 9, 21, 45, 93, ?', options: ['185', '187', '189', '191'], correctIndex: 2, explanation: 'Each term is double the previous term plus 3: 3×2+3=9, 9×2+3=21, 21×2+3=45, 45×2+3=93, 93×2+3=189.', source },
  { id: 'sidbi-p1-re2-016', section: 'Reasoning Aptitude', topic: 'Ranking and Order', difficulty: 'medium', question: 'In a merit list of 70 candidates, Karan is ranked 22nd from the bottom. What is his rank from the top?', options: ['47', '48', '50', '49'], correctIndex: 3, explanation: 'Rank from top = Total candidates − Rank from bottom + 1 = 70 − 22 + 1 = 49.', source },
  { id: 'sidbi-p1-re2-017', section: 'Reasoning Aptitude', topic: 'Classification', difficulty: 'easy', question: 'Select the option that does not fit with the rest.', options: ['Debenture', 'Equity Share', 'Bond', 'Ledger'], correctIndex: 3, explanation: 'Debenture, Equity Share, and Bond are all financial instruments, while a Ledger is an accounting record, not a financial instrument.', source },
  { id: 'sidbi-p1-re2-018', section: 'Reasoning Aptitude', topic: 'Inequality', difficulty: 'medium', question: 'Statements: X ≤ Y < Z; W > Z. Conclusions: I. W > X. II. Y < W. Which conclusion(s) logically follow?', options: ['Only I follows', 'Only II follows', 'Neither follows', 'Both I and II follow'], correctIndex: 3, explanation: 'Combining the statements gives the chain X ≤ Y < Z < W. Since Y < Z < W, Conclusion II (Y < W) follows directly. Since X ≤ Y < W, X must also be strictly less than W, so Conclusion I (W > X) follows too.', source },
  { id: 'sidbi-p1-re2-019', section: 'Reasoning Aptitude', topic: 'Puzzle', difficulty: 'hard', question: 'Five credit files — P, Q, R, S, T — are processed one after another. Q is processed immediately after P. T is processed immediately before S. R is processed last. P is processed first. In what position is file S processed?', options: ['2nd', '3rd', '5th', '4th'], correctIndex: 3, explanation: 'P is 1st and Q (immediately after P) is 2nd. R is processed last, so R is 5th. The remaining positions 3rd and 4th must hold T immediately before S, so T is 3rd and S is 4th.', source },
  { id: 'sidbi-p1-re2-020', section: 'Reasoning Aptitude', topic: 'Data Sufficiency', difficulty: 'hard', question: 'How many staff members work in the recovery department of a branch? Statement I: The ratio of officers to clerks in the department is 2:3. Statement II: There are 8 officers in the department.', options: ['Statement I alone is sufficient', 'Statement II alone is sufficient', 'Both statements together are needed', 'Neither statement is sufficient'], correctIndex: 2, explanation: 'Statement I alone gives only a ratio, not an absolute count. Statement II alone gives only the officer count. Combined, the ratio 2:3 with 8 officers gives 12 clerks, so total = 20 — both statements together are needed.', source },
  { id: 'sidbi-p1-re2-021', section: 'Reasoning Aptitude', topic: 'Syllogism', difficulty: 'medium', question: 'Statements: No trusts are companies. Some companies are borrowers. Conclusions: I. No borrowers are trusts. II. Some borrowers are not trusts. Which conclusion(s) logically follow?', options: ['Only I follows', 'Only II follows', 'Both follow', 'Neither follows'], correctIndex: 1, explanation: 'Since no trusts are companies, and some companies are borrowers, those specific borrowers (which are companies) cannot be trusts — so Conclusion II follows. Conclusion I, a universal claim about all borrowers, is too strong to be guaranteed and does not follow.', source },
  { id: 'sidbi-p1-re2-022', section: 'Reasoning Aptitude', topic: 'Number Series', difficulty: 'medium', question: 'Find the missing number in the series: 7, 10, 15, 22, 31, ?', options: ['40', '42', '44', '46'], correctIndex: 1, explanation: 'The differences between consecutive terms increase by 2 each time (3, 5, 7, 9, 11): 7+3=10, 10+5=15, 15+7=22, 22+9=31, 31+11=42.', source },
  { id: 'sidbi-p1-re2-023', section: 'Reasoning Aptitude', topic: 'Ranking and Order', difficulty: 'medium', question: 'In a queue of 30 customers at a service counter, Meera is 11th from the front. How many customers are behind her (excluding herself)?', options: ['18', '19', '20', '17'], correctIndex: 1, explanation: 'Customers behind Meera = Total customers − her position = 30 − 11 = 19.', source },
  { id: 'sidbi-p1-re2-024', section: 'Reasoning Aptitude', topic: 'Direction Sense', difficulty: 'medium', question: 'A person walks 15 km East, then 8 km South. Find the straight-line distance from the starting point.', options: ['19 km', '23 km', '17 km', '21 km'], correctIndex: 2, explanation: 'Using the Pythagorean theorem: distance = √(15² + 8²) = √(225 + 64) = √289 = 17 km.', source },
  { id: 'sidbi-p1-re2-025', section: 'Reasoning Aptitude', topic: 'Classification', difficulty: 'easy', question: 'Find the one that does not belong to the group.', options: ['Prospectus', 'Memorandum of Association', 'Ledger', 'Articles of Association'], correctIndex: 2, explanation: 'Prospectus, Memorandum of Association, and Articles of Association are all constitutional/disclosure documents of a company, while a Ledger is an accounting record.', source },
];
