import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SIDBI Officers Grade A & B (General and Specialist Stream) Recruitment 2025-26 official notification — Phase I, Computer Knowledge section',
  url: 'https://www.sidbi.in/head/uploads/career_document/SIDBI_DETAILED_WEB_ADVT_2025.pdf',
  checkedOn: '24 August 2026',
};

export const SIDBI_GRADE_A_B_PHASE_1_COMPUTER_KNOWLEDGE_2: Question[] = [
  { id: 'sidbi-p1-ck2-001', section: 'Computer Knowledge', topic: 'Networking', difficulty: 'medium', question: 'Which networking device operates at the network layer and routes data packets between different networks based on IP addresses?', options: ['Router', 'Hub', 'Repeater', 'Switch'], correctIndex: 0, explanation: 'A router operates at the network layer and forwards data packets between different networks by examining IP addresses.', source },
  { id: 'sidbi-p1-ck2-002', section: 'Computer Knowledge', topic: 'Networking', difficulty: 'medium', question: 'A network confined to a small geographic area, such as a single office or building, is called a:', options: ['WAN', 'MAN', 'PAN', 'LAN'], correctIndex: 3, explanation: 'A Local Area Network (LAN) is confined to a small geographic area, such as an office or building.', source },
  { id: 'sidbi-p1-ck2-003', section: 'Computer Knowledge', topic: 'Database Concepts', difficulty: 'medium', question: 'A column or set of columns that uniquely identifies each record in a database table is called a:', options: ['Foreign Key', 'Composite Index', 'Candidate Key', 'Primary Key'], correctIndex: 3, explanation: 'A primary key is a column or set of columns that uniquely identifies each record in a database table.', source },
  { id: 'sidbi-p1-ck2-004', section: 'Computer Knowledge', topic: 'Database Concepts', difficulty: 'medium', question: 'Which SQL command is used to retrieve data from one or more database tables?', options: ['INSERT', 'UPDATE', 'SELECT', 'DELETE'], correctIndex: 2, explanation: 'The SELECT command is used to retrieve and query data from one or more database tables.', source },
  { id: 'sidbi-p1-ck2-005', section: 'Computer Knowledge', topic: 'Number Systems', difficulty: 'medium', question: 'What is the binary equivalent of the decimal number 27?', options: ['11011', '11010', '11001', '10111'], correctIndex: 0, explanation: '27 in binary is 11011, since 16+8+0+2+1 = 27 (1×16 + 1×8 + 0×4 + 1×2 + 1×1).', source },
  { id: 'sidbi-p1-ck2-006', section: 'Computer Knowledge', topic: 'Generations of Computers', difficulty: 'medium', question: 'Which generation of computers used transistors instead of vacuum tubes, making machines smaller and more reliable?', options: ['First generation', 'Second generation', 'Third generation', 'Fourth generation'], correctIndex: 1, explanation: 'The second generation of computers (late 1950s to mid-1960s) used transistors instead of vacuum tubes, making machines smaller, faster, and more reliable.', source },
  { id: 'sidbi-p1-ck2-007', section: 'Computer Knowledge', topic: 'Software Types', difficulty: 'easy', question: 'Device drivers, which allow the operating system to communicate with hardware components, are examples of which type of software?', options: ['Application software', 'System software', 'Middleware', 'Firmware only, never software'], correctIndex: 1, explanation: 'Device drivers are a type of system software that enable the operating system to communicate with hardware components.', source },
  { id: 'sidbi-p1-ck2-008', section: 'Computer Knowledge', topic: 'Internet Fundamentals', difficulty: 'medium', question: 'Which protocol assigns IP addresses automatically to devices on a network?', options: ['DNS', 'SMTP', 'FTP', 'DHCP'], correctIndex: 3, explanation: 'DHCP (Dynamic Host Configuration Protocol) automatically assigns IP addresses and other network configuration to devices on a network.', source },
  { id: 'sidbi-p1-ck2-009', section: 'Computer Knowledge', topic: 'Internet Fundamentals', difficulty: 'medium', question: 'Temporary internet files stored locally to speed up subsequent access to the same web page are called:', options: ['Cache', 'Cookies', 'Bookmarks', 'Plugins'], correctIndex: 0, explanation: 'A cache stores temporary copies of web content locally, speeding up subsequent access to the same page.', source },
  { id: 'sidbi-p1-ck2-010', section: 'Computer Knowledge', topic: 'Digital Payments', difficulty: 'medium', question: 'Which payment system processes high-value interbank fund transfers in India on a real-time, transaction-by-transaction basis, unlike the batch-processed NEFT?', options: ['IMPS', 'Demand Draft', 'Cheque Truncation System', 'RTGS'], correctIndex: 3, explanation: 'RTGS (Real Time Gross Settlement) processes high-value fund transfers individually and in real time, unlike NEFT, which is settled in batches.', source },
  { id: 'sidbi-p1-ck2-011', section: 'Computer Knowledge', topic: 'Cybersecurity', difficulty: 'medium', question: 'A network security system that monitors and controls incoming and outgoing traffic based on predetermined security rules is called a:', options: ['Firewall', 'Cache', 'Cookie', 'Proxy server (alone)'], correctIndex: 0, explanation: 'A firewall monitors and filters incoming and outgoing network traffic based on predetermined security rules, blocking unauthorised access.', source },
  { id: 'sidbi-p1-ck2-012', section: 'Computer Knowledge', topic: 'Cybersecurity', difficulty: 'medium', question: 'Malicious software that disguises itself as legitimate software but performs harmful actions once installed is called a:', options: ['Firewall', 'Trojan horse', 'Cache', 'Cookie'], correctIndex: 1, explanation: 'A Trojan horse disguises itself as legitimate or useful software while secretly performing malicious actions once installed.', source },
  { id: 'sidbi-p1-ck2-013', section: 'Computer Knowledge', topic: 'MS Excel', difficulty: 'medium', question: 'Which Excel function returns the largest value in a selected range of cells?', options: ['MIN()', 'MAX()', 'COUNT()', 'AVERAGE()'], correctIndex: 1, explanation: 'The MAX() function in Excel returns the largest numeric value in a specified range of cells.', source },
  { id: 'sidbi-p1-ck2-014', section: 'Computer Knowledge', topic: 'MS Excel', difficulty: 'medium', question: 'Which Excel function searches for a value in the first column of a range and returns a value from another column in the same row?', options: ['VLOOKUP()', 'SORT()', 'IFERROR()', 'CONCATENATE()'], correctIndex: 0, explanation: 'VLOOKUP() searches for a specified value in the first column of a range and returns a corresponding value from another column in the same row.', source },
  { id: 'sidbi-p1-ck2-015', section: 'Computer Knowledge', topic: 'Computer Memory', difficulty: 'easy', question: 'Which type of computer memory is non-volatile and retains its stored content even when the power supply is switched off?', options: ['RAM', 'Cache memory', 'Register', 'ROM'], correctIndex: 3, explanation: 'ROM (Read-Only Memory) is non-volatile, meaning it retains stored data even without power.', source },
  { id: 'sidbi-p1-ck2-016', section: 'Computer Knowledge', topic: 'Data Storage Units', difficulty: 'easy', question: 'Approximately how many megabytes make up one gigabyte?', options: ['128', '256', '1,024', '512'], correctIndex: 2, explanation: 'One gigabyte is approximately equal to 1,024 megabytes, following the standard binary storage convention.', source },
  { id: 'sidbi-p1-ck2-017', section: 'Computer Knowledge', topic: 'Operating Systems', difficulty: 'medium', question: 'The program that starts an operating system when a computer is switched on, before the operating system fully loads, is called the:', options: ['Kernel', 'Compiler', 'Boot loader', 'Shell'], correctIndex: 2, explanation: 'The boot loader is the program that initiates the operating system loading process when a computer is switched on.', source },
  { id: 'sidbi-p1-ck2-018', section: 'Computer Knowledge', topic: 'Digital Security', difficulty: 'medium', question: 'Two-factor authentication (2FA) enhances account security primarily by:', options: ['Requiring only a stronger single password', 'Requiring two independent forms of verification before granting access', 'Disabling passwords entirely', 'Allowing unlimited login attempts'], correctIndex: 1, explanation: 'Two-factor authentication enhances security by requiring two independent forms of verification, such as a password and a one-time code, before granting access.', source },
  { id: 'sidbi-p1-ck2-019', section: 'Computer Knowledge', topic: 'Email', difficulty: 'medium', question: 'In an email, which field is used to enter the main recipient(s) of the message?', options: ['CC', 'BCC', 'To', 'Subject'], correctIndex: 2, explanation: 'The "To" field is used to enter the primary, intended recipient(s) of an email message.', source },
  { id: 'sidbi-p1-ck2-020', section: 'Computer Knowledge', topic: 'Cloud Computing', difficulty: 'medium', question: 'A cloud service model that provides users with virtualised computing infrastructure, such as servers and storage, over the internet is known as:', options: ['Software as a Service (SaaS)', 'Platform as a Service (PaaS)', 'Infrastructure as a Service (IaaS)', 'Function as a Service (FaaS)'], correctIndex: 2, explanation: 'Infrastructure as a Service (IaaS) provides users with virtualised computing infrastructure, such as servers and storage, delivered over the internet.', source },
];
