import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SIDBI Officers Grade A & B (General and Specialist Stream) Recruitment 2025-26 official notification — Phase I, General Awareness section',
  url: 'https://www.sidbi.in/head/uploads/career_document/SIDBI_DETAILED_WEB_ADVT_2025.pdf',
  checkedOn: '6 August 2026',
};

export const SIDBI_GRADE_A_B_PHASE_1_GENERAL_AWARENESS_1: Question[] = [
  { id: 'sidbi-p1-ga-001', section: 'General Awareness', topic: 'SIDBI', difficulty: 'medium', question: 'SIDBI (Small Industries Development Bank of India) was established on 2 April 1990 under which legislation?', options: ['The Companies Act, 1956', 'The SIDBI Act, 1989', 'The Banking Regulation Act, 1949', 'The Industries (Development and Regulation) Act, 1951'], correctIndex: 1, explanation: 'SIDBI was established on 2 April 1990 under the Small Industries Development Bank of India Act, 1989.', source },
  { id: 'sidbi-p1-ga-002', section: 'General Awareness', topic: 'SIDBI', difficulty: 'easy', question: 'Where is the head office of SIDBI located?', options: ['New Delhi', 'Mumbai', 'Chennai', 'Lucknow'], correctIndex: 3, explanation: "SIDBI's head office is located in Lucknow, Uttar Pradesh.", source },
  { id: 'sidbi-p1-ga-003', section: 'General Awareness', topic: 'MSME Classification', difficulty: 'medium', question: 'As per the MSME classification revised with effect from 1 April 2025, a Micro Enterprise is one with investment up to what amount?', options: ['₹1 crore', '₹1.5 crore', '₹2 crore', '₹2.5 crore'], correctIndex: 3, explanation: 'Under the classification revised effective 1 April 2025, a Micro Enterprise is one with investment up to ₹2.5 crore and turnover up to ₹10 crore.', source },
  { id: 'sidbi-p1-ga-004', section: 'General Awareness', topic: 'Credit Guarantee', difficulty: 'medium', question: 'The Credit Guarantee Fund Trust for Micro and Small Enterprises (CGTMSE), which provides collateral-free credit guarantees, was jointly set up in 2000 by the Government of India and:', options: ['NABARD', 'RBI', 'SIDBI', 'SEBI'], correctIndex: 2, explanation: 'CGTMSE was jointly set up in 2000 by the Ministry of MSME, Government of India, and SIDBI, to catalyse collateral-free credit to micro and small enterprises.', source },
  { id: 'sidbi-p1-ga-005', section: 'General Awareness', topic: 'Government Schemes', difficulty: 'medium', question: 'Under the Pradhan Mantri MUDRA Yojana (PMMY), loans up to ₹50,000 to non-corporate, non-farm micro enterprises are categorised under which scheme?', options: ['Tarun Plus', 'Kishor', 'Tarun', 'Shishu'], correctIndex: 3, explanation: 'The Shishu category under PMMY covers loans up to ₹50,000, while Kishor covers ₹50,001 to ₹5 lakh and Tarun covers ₹5 lakh to ₹10 lakh.', source },
  { id: 'sidbi-p1-ga-006', section: 'General Awareness', topic: 'SIDBI', difficulty: 'medium', question: 'MUDRA (Micro Units Development and Refinance Agency), set up in April 2015, was established as a wholly owned subsidiary of which institution?', options: ['RBI', 'NABARD', 'SIDBI', 'SBI'], correctIndex: 2, explanation: 'MUDRA was set up on 8 April 2015 as a wholly owned subsidiary of SIDBI, to refinance micro-finance institutions and other lenders extending credit to micro enterprises.', source },
  { id: 'sidbi-p1-ga-007', section: 'General Awareness', topic: 'Banking Regulation', difficulty: 'medium', question: 'As per RBI norms, a loan account is classified as a Non-Performing Asset (NPA) when interest or principal repayment remains overdue for a period of:', options: ['30 days', '60 days', '90 days', '120 days'], correctIndex: 2, explanation: 'As per RBI norms, a loan account is classified as a Non-Performing Asset when interest or principal repayment remains overdue for more than 90 days.', source },
  { id: 'sidbi-p1-ga-008', section: 'General Awareness', topic: 'Priority Sector Lending', difficulty: 'medium', question: "Lending to the MSME sector by scheduled commercial banks falls under a mandatory RBI-mandated category known as:", options: ['Priority Sector Lending', 'Statutory Liquidity Requirement', 'Cash Reserve Requirement', 'Marginal Standing Facility'], correctIndex: 0, explanation: 'MSME lending is a mandatory category under RBI\'s Priority Sector Lending (PSL) norms, alongside agriculture, export credit, and other specified sectors.', source },
  { id: 'sidbi-p1-ga-009', section: 'General Awareness', topic: 'Startup India', difficulty: 'medium', question: 'A DPIIT-recognised startup under the Startup India initiative is eligible for a tax exemption on profits for how many years, out of its first ten years since incorporation?', options: ['2 consecutive years', 'All 10 years', '5 consecutive years', '3 consecutive years'], correctIndex: 3, explanation: 'Eligible DPIIT-recognised startups can avail a tax exemption on profits for any 3 consecutive assessment years out of their first 10 years since incorporation, subject to conditions.', source },
  { id: 'sidbi-p1-ga-010', section: 'General Awareness', topic: 'Financial Regulators', difficulty: 'medium', question: 'Non-Banking Financial Companies (NBFCs) in India are primarily regulated by:', options: ['SEBI', 'IRDAI', 'RBI', 'Ministry of Corporate Affairs'], correctIndex: 2, explanation: 'Non-Banking Financial Companies (NBFCs) in India are primarily regulated by the Reserve Bank of India.', source },
  { id: 'sidbi-p1-ga-011', section: 'General Awareness', topic: 'Taxation', difficulty: 'medium', question: 'Under the standard GST Composition Scheme for goods, a business is eligible if its annual turnover does not exceed:', options: ['₹75 lakh', '₹1 crore', '₹1.5 crore', '₹2 crore'], correctIndex: 2, explanation: 'The standard GST Composition Scheme for goods is available to businesses with an annual turnover of up to ₹1.5 crore (₹75 lakh for special category states).', source },
  { id: 'sidbi-p1-ga-012', section: 'General Awareness', topic: 'Banking Regulation', difficulty: 'medium', question: 'The Basel III norms, which prescribe capital adequacy and liquidity requirements for banks globally, were developed by the:', options: ['International Monetary Fund', 'Financial Stability Board', 'World Bank', 'Basel Committee on Banking Supervision'], correctIndex: 3, explanation: 'The Basel III norms were developed by the Basel Committee on Banking Supervision (BCBS) in response to the global financial crisis.', source },
  { id: 'sidbi-p1-ga-013', section: 'General Awareness', topic: 'Monetary Policy', difficulty: 'medium', question: "The percentage of a bank's total deposits that it must maintain as reserves with the RBI, earning no interest, is called the:", options: ['Statutory Liquidity Ratio', 'Cash Reserve Ratio', 'Repo Rate', 'Bank Rate'], correctIndex: 1, explanation: 'The Cash Reserve Ratio (CRR) is the percentage of a bank\'s total deposits that it must maintain as reserves with the RBI, without earning interest.', source },
  { id: 'sidbi-p1-ga-014', section: 'General Awareness', topic: 'SIDBI', difficulty: 'medium', question: 'SIDBI Venture Capital Limited (SVCL), a subsidiary of SIDBI, primarily provides which form of financing to MSMEs?', options: ['Working capital overdraft', 'Venture capital / equity funding', 'Trade credit insurance', 'Gold loans'], correctIndex: 1, explanation: 'SIDBI Venture Capital Limited (SVCL) primarily provides venture capital and equity funding support to MSMEs and startups, complementing SIDBI\'s debt-financing role.', source },
  { id: 'sidbi-p1-ga-015', section: 'General Awareness', topic: 'SIDBI', difficulty: 'medium', question: "SIDBI's SMILE scheme, launched in 2015 under the 'Make in India' initiative, primarily provides MSMEs with:", options: ['Quasi-equity and soft term loans', 'Free equipment grants', 'Interest-free overdraft facilities', 'Export insurance cover'], correctIndex: 0, explanation: "SMILE (SIDBI Make in India Soft Loan Fund for Enterprises), launched in 2015, provides quasi-equity and soft term loans to help MSMEs meet debt-equity ratio norms and pursue growth opportunities.", source },
  { id: 'sidbi-p1-ga-016', section: 'General Awareness', topic: 'MSME Registration', difficulty: 'medium', question: 'Udyam Registration, launched on 1 July 2020, is the online system used for:', options: ['Registering and classifying enterprises as MSMEs', 'Filing income tax returns for companies', 'Registering trademarks and patents', 'Applying for an Import Export Code'], correctIndex: 0, explanation: 'Udyam Registration is the online system, effective from 1 July 2020, for registering and classifying enterprises as Micro, Small, or Medium Enterprises, replacing the earlier Udyog Aadhaar Memorandum system.', source },
  { id: 'sidbi-p1-ga-017', section: 'General Awareness', topic: 'SIDBI', difficulty: 'medium', question: 'SIDBI is best described as a:', options: ['Retail commercial bank accepting public savings deposits', 'Development Financial Institution for the MSME sector', 'Payments bank', 'Cooperative credit society'], correctIndex: 1, explanation: 'SIDBI functions as the principal Development Financial Institution (DFI) for the promotion, financing, and development of the MSME sector, rather than as a retail commercial bank.', source },
  { id: 'sidbi-p1-ga-018', section: 'General Awareness', topic: 'Startup Finance', difficulty: 'medium', question: "SIDBI acts as the operating agency for the Government of India's Fund of Funds for Startups (FFS), which is monitored by:", options: ['NITI Aayog', 'Department for Promotion of Industry and Internal Trade (DPIIT)', 'Ministry of Finance', 'RBI'], correctIndex: 1, explanation: 'The Fund of Funds for Startups (FFS) is monitored by the Department for Promotion of Industry and Internal Trade (DPIIT), with SIDBI acting as the operating agency, investing in SEBI-registered Alternative Investment Funds.', source },
  { id: 'sidbi-p1-ga-019', section: 'General Awareness', topic: 'Financial Institutions', difficulty: 'medium', question: 'Which of the following is a Development Financial Institution focused specifically on the agriculture and rural development sector, distinct from SIDBI\'s MSME focus?', options: ['NABARD', 'IRDAI', 'PFRDA', 'IFCI'], correctIndex: 0, explanation: 'NABARD (National Bank for Agriculture and Rural Development) is the apex Development Financial Institution for agriculture and rural development, distinct from SIDBI\'s focus on the MSME sector.', source },
  { id: 'sidbi-p1-ga-020', section: 'General Awareness', topic: 'Credit Instruments', difficulty: 'medium', question: 'A financing arrangement in which a lender purchases a business\'s unpaid invoices at a discount to provide immediate working capital is known as:', options: ['Factoring', 'Underwriting', 'Securitisation', 'Hypothecation'], correctIndex: 0, explanation: 'Factoring is a financing arrangement in which a business sells its unpaid invoices (receivables) to a lender at a discount in exchange for immediate cash.', source },
];
