import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SSC MTS & Havaldar (CBIC & CBN) Examination 2025 official scheme, Session 1 — Numerical and Mathematical Ability section',
  url: 'https://ssc.gov.in/api/attachment/uploads/masterData/NoticeBoards/writeup_mts_03082026.pdf',
  checkedOn: '4 August 2026',
};

export const SSC_MTS_CBT_NUMERICAL_MATHEMATICAL_ABILITY_1: Question[] = [
  { id: 'ssc-mts-cbt-na-001', section: 'Numerical and Mathematical Ability', topic: 'Percentage', difficulty: 'easy', question: '15% of 480 = ?', options: ['72', '70', '75', '68'], correctIndex: 0, negativeMarking: 0, explanation: '15% of 480 = (15/100) × 480 = 72.', source },
  { id: 'ssc-mts-cbt-na-002', section: 'Numerical and Mathematical Ability', topic: 'Simplification', difficulty: 'easy', question: '240 ÷ 6 = ?', options: ['36', '40', '44', '48'], correctIndex: 1, negativeMarking: 0, explanation: '240 ÷ 6 = 40.', source },
  { id: 'ssc-mts-cbt-na-003', section: 'Numerical and Mathematical Ability', topic: 'Simplification', difficulty: 'easy', question: '(7 × 9) − (4 × 8) = ?', options: ['27', '29', '31', '33'], correctIndex: 2, negativeMarking: 0, explanation: '7 × 9 = 63 and 4 × 8 = 32; 63 − 32 = 31.', source },
  { id: 'ssc-mts-cbt-na-004', section: 'Numerical and Mathematical Ability', topic: 'Simplification', difficulty: 'easy', question: '√169 + √196 = ?', options: ['25', '26', '29', '27'], correctIndex: 3, negativeMarking: 0, explanation: '√169 = 13 and √196 = 14; 13 + 14 = 27.', source },
  { id: 'ssc-mts-cbt-na-005', section: 'Numerical and Mathematical Ability', topic: 'Ratio and Proportion', difficulty: 'easy', question: 'Two numbers are in the ratio 2:3 and their sum is 75. Find the larger number.', options: ['45', '30', '50', '40'], correctIndex: 0, negativeMarking: 0, explanation: 'The parts total 5 units, so each unit = 75 ÷ 5 = 15. The larger number is 3 × 15 = 45.', source },
  { id: 'ssc-mts-cbt-na-006', section: 'Numerical and Mathematical Ability', topic: 'Average', difficulty: 'easy', question: 'Find the average of 10, 20, 30, 40, and 50.', options: ['25', '30', '35', '20'], correctIndex: 1, negativeMarking: 0, explanation: 'Sum = 150, and 150 ÷ 5 = 30.', source },
  { id: 'ssc-mts-cbt-na-007', section: 'Numerical and Mathematical Ability', topic: 'Profit and Loss', difficulty: 'medium', question: 'A trader buys an item for ₹450 and sells it for ₹540. Find the profit percentage.', options: ['15%', '18%', '20%', '25%'], correctIndex: 2, negativeMarking: 0, explanation: 'Profit = 540 − 450 = ₹90. Profit% = (90 ÷ 450) × 100 = 20%.', source },
  { id: 'ssc-mts-cbt-na-008', section: 'Numerical and Mathematical Ability', topic: 'Simple Interest', difficulty: 'medium', question: 'Find the simple interest on ₹4,000 at 5% per annum for 4 years.', options: ['700', '750', '850', '800'], correctIndex: 3, negativeMarking: 0, explanation: 'SI = (Principal × Rate × Time) ÷ 100 = (4000 × 5 × 4) ÷ 100 = ₹800.', source },
  { id: 'ssc-mts-cbt-na-009', section: 'Numerical and Mathematical Ability', topic: 'Time and Work', difficulty: 'medium', question: 'A can complete a task in 10 days and B can complete it in 15 days. Working together, how many days will they take?', options: ['6', '7', '5', '8'], correctIndex: 0, negativeMarking: 0, explanation: 'Combined rate = 1/10 + 1/15 = 1/6 of the task per day, so together they take 6 days.', source },
  { id: 'ssc-mts-cbt-na-010', section: 'Numerical and Mathematical Ability', topic: 'Time, Speed and Distance', difficulty: 'easy', question: 'A car covers 180 km in 3 hours. Find its speed.', options: ['55 km/h', '60 km/h', '65 km/h', '50 km/h'], correctIndex: 1, negativeMarking: 0, explanation: 'Speed = Distance ÷ Time = 180 ÷ 3 = 60 km/h.', source },
  { id: 'ssc-mts-cbt-na-011', section: 'Numerical and Mathematical Ability', topic: 'Number Series', difficulty: 'medium', question: 'Find the next number in the series: 2, 5, 10, 17, 26, ?', options: ['35', '36', '37', '39'], correctIndex: 2, negativeMarking: 0, explanation: 'The differences increase by 2 each time (+3, +5, +7, +9, +11): 26 + 11 = 37.', source },
  { id: 'ssc-mts-cbt-na-012', section: 'Numerical and Mathematical Ability', topic: 'Mensuration', difficulty: 'easy', question: 'Find the area of a rectangle with length 12 cm and breadth 7 cm.', options: ['80', '82', '88', '84'], correctIndex: 3, negativeMarking: 0, explanation: 'Area = length × breadth = 12 × 7 = 84 cm².', source },
  { id: 'ssc-mts-cbt-na-013', section: 'Numerical and Mathematical Ability', topic: 'Fractions', difficulty: 'easy', question: '2/3 + 1/6 = ?', options: ['5/6', '3/4', '7/9', '2/3'], correctIndex: 0, negativeMarking: 0, explanation: '2/3 = 4/6, so 4/6 + 1/6 = 5/6.', source },
  { id: 'ssc-mts-cbt-na-014', section: 'Numerical and Mathematical Ability', topic: 'LCM and HCF', difficulty: 'easy', question: 'Find the LCM of 4 and 6.', options: ['10', '12', '14', '16'], correctIndex: 1, negativeMarking: 0, explanation: 'The multiples of 4 and 6 first coincide at 12, so the LCM is 12.', source },
  { id: 'ssc-mts-cbt-na-015', section: 'Numerical and Mathematical Ability', topic: 'Algebra', difficulty: 'medium', question: 'If x² − 7 = 18, find the positive value of x.', options: ['3', '4', '5', '6'], correctIndex: 2, negativeMarking: 0, explanation: 'x² = 18 + 7 = 25, so x = 5 (taking the positive root).', source },
  { id: 'ssc-mts-cbt-na-016', section: 'Numerical and Mathematical Ability', topic: 'Percentage', difficulty: 'easy', question: '25% of a number is 50. Find the number.', options: ['150', '175', '225', '200'], correctIndex: 3, negativeMarking: 0, explanation: 'If the number is x, 0.25x = 50, so x = 50 ÷ 0.25 = 200.', source },
  { id: 'ssc-mts-cbt-na-017', section: 'Numerical and Mathematical Ability', topic: 'Simplification', difficulty: 'medium', question: '(12 × 12) − (6 × 6) = ?', options: ['108', '98', '118', '100'], correctIndex: 0, negativeMarking: 0, explanation: '12 × 12 = 144 and 6 × 6 = 36; 144 − 36 = 108.', source },
  { id: 'ssc-mts-cbt-na-018', section: 'Numerical and Mathematical Ability', topic: 'Profit and Loss', difficulty: 'easy', question: 'An item marked at ₹800 is sold at a discount of 10%. Find the selling price.', options: ['700', '720', '740', '760'], correctIndex: 1, negativeMarking: 0, explanation: 'Discount = 10% of 800 = ₹80. Selling price = 800 − 80 = ₹720.', source },
  { id: 'ssc-mts-cbt-na-019', section: 'Numerical and Mathematical Ability', topic: 'LCM and HCF', difficulty: 'medium', question: 'Find the smallest number exactly divisible by both 6 and 8.', options: ['16', '20', '24', '28'], correctIndex: 2, negativeMarking: 0, explanation: 'The LCM of 6 and 8 is 24, the smallest number divisible by both.', source },
  { id: 'ssc-mts-cbt-na-020', section: 'Numerical and Mathematical Ability', topic: 'Time and Work', difficulty: 'medium', question: '8 men can complete a task in 12 days. How many days will 6 men take to complete the same task?', options: ['12', '14', '18', '16'], correctIndex: 3, negativeMarking: 0, explanation: 'Total work = 8 × 12 = 96 man-days. With 6 men, days = 96 ÷ 6 = 16.', source },
];
