import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SSC CGL 2026 official notice, paragraph 13.10.4 (English Comprehension syllabus)',
  url: 'https://ssc.gov.in/api/attachment/uploads/masterData/NoticeBoards/Notice_of_adv_cgl_2026.pdf',
  checkedOn: '30 July 2026',
};

const passage =
  'Many people assume that taking frequent breaks reduces productivity. Research on focused work suggests the opposite: short, planned pauses can restore attention and reduce careless errors. The benefit depends on keeping breaks brief and returning to the task at a fixed time.';

export const SSC_CGL_TIER1_ENGLISH_2: Question[] = [
  {
    id: 'ssc-cgl-t1-en2-001',
    section: 'English Comprehension',
    topic: 'Synonym',
    difficulty: 'medium',
    question: 'Choose the word that is closest in meaning to “pragmatic”.',
    options: ['Practical', 'Idealistic', 'Careless', 'Uncertain'],
    correctIndex: 0,
    explanation: '“Pragmatic” means dealing with problems in a practical and realistic way.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en2-002',
    section: 'English Comprehension',
    topic: 'Synonym',
    difficulty: 'easy',
    question: 'Choose the word that is closest in meaning to “obsolete”.',
    options: ['Popular', 'Outdated', 'Expensive', 'Useful'],
    correctIndex: 1,
    explanation: '“Obsolete” describes something that is no longer used because it has been replaced or is outdated.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en2-003',
    section: 'English Comprehension',
    topic: 'Antonym',
    difficulty: 'easy',
    question: 'Choose the word that is opposite in meaning to “expand”.',
    options: ['Extend', 'Increase', 'Contract', 'Develop'],
    correctIndex: 2,
    explanation: '“Expand” means to become larger, while “contract” means to become smaller.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en2-004',
    section: 'English Comprehension',
    topic: 'Antonym',
    difficulty: 'easy',
    question: 'Choose the word that is opposite in meaning to “transparent”.',
    options: ['Clear', 'Visible', 'Bright', 'Opaque'],
    correctIndex: 3,
    explanation: 'An opaque material does not allow light to pass through and is the opposite of transparent.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en2-005',
    section: 'English Comprehension',
    topic: 'Spelling',
    difficulty: 'easy',
    question: 'Which option correctly spells the word meaning a special right or advantage?',
    options: ['Privilege', 'Privelege', 'Priviledge', 'Privillage'],
    correctIndex: 0,
    explanation: '“Privilege” is the correct spelling.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en2-006',
    section: 'English Comprehension',
    topic: 'Spelling',
    difficulty: 'medium',
    question: 'Which option correctly spells the word meaning an event or incident?',
    options: ['Occurence', 'Occurrence', 'Ocurrence', 'Occurrance'],
    correctIndex: 1,
    explanation: '“Occurrence” is spelled with two c’s and two r’s.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en2-007',
    section: 'English Comprehension',
    topic: 'One-word substitution',
    difficulty: 'medium',
    question: 'Choose the one-word substitute for “government by a small group of powerful people”.',
    options: ['Democracy', 'Monarchy', 'Oligarchy', 'Anarchy'],
    correctIndex: 2,
    explanation: 'An oligarchy is a form of government in which power is held by a small group.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en2-008',
    section: 'English Comprehension',
    topic: 'One-word substitution',
    difficulty: 'medium',
    question: 'Choose the one-word substitute for “a person or behaviour that cannot be corrected”.',
    options: ['Incredible', 'Infallible', 'Invisible', 'Incorrigible'],
    correctIndex: 3,
    explanation: '“Incorrigible” means not able to be corrected, improved or reformed.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en2-009',
    section: 'English Comprehension',
    topic: 'Idioms and phrases',
    difficulty: 'easy',
    question: 'What does the idiom “spill the beans” mean?',
    options: ['To reveal a secret', 'To waste food', 'To make a mess', 'To lose money'],
    correctIndex: 0,
    explanation: '“Spill the beans” means to disclose information that was meant to remain secret.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en2-010',
    section: 'English Comprehension',
    topic: 'Idioms and phrases',
    difficulty: 'easy',
    question: 'What does the phrase “under the weather” mean?',
    options: ['Outdoors', 'Feeling ill', 'Very busy', 'Unprepared'],
    correctIndex: 1,
    explanation: 'To feel “under the weather” means to feel unwell.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en2-011',
    section: 'English Comprehension',
    topic: 'Subject-verb agreement',
    difficulty: 'medium',
    question: 'Which sentence uses the expression “one of the students” correctly?',
    options: [
      'One of the students have submitted the assignment.',
      'One of the student has submitted the assignment.',
      'One of the students has submitted the assignment.',
      'One of the students were submitting the assignment.',
    ],
    correctIndex: 2,
    explanation: 'The subject “one” is singular and takes “has”; the noun after “of the” is plural.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en2-012',
    section: 'English Comprehension',
    topic: 'Correlative conjunctions',
    difficulty: 'medium',
    question: 'Complete the sentence correctly: “No sooner had the bell rung ___ the students left the room.”',
    options: ['when', 'then', 'as', 'than'],
    correctIndex: 3,
    explanation: 'The standard correlative construction is “no sooner … than”.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en2-013',
    section: 'English Comprehension',
    topic: 'Tense',
    difficulty: 'medium',
    question: 'Fill in the blank: “By 8 p.m., they ___ the report.”',
    options: ['will have finished', 'will finish', 'are finishing', 'finished'],
    correctIndex: 0,
    explanation: 'The future perfect tense describes an action completed before a specified future time.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en2-014',
    section: 'English Comprehension',
    topic: 'Preposition',
    difficulty: 'easy',
    question: 'Fill in the blank: “She insisted ___ paying the bill.”',
    options: ['at', 'on', 'for', 'with'],
    correctIndex: 1,
    explanation: 'The verb “insist” is followed by the preposition “on” before a gerund.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en2-015',
    section: 'English Comprehension',
    topic: 'Articles',
    difficulty: 'easy',
    question: 'Fill in the blank: “He studies at ___ university in Delhi.”',
    options: ['an', 'the', 'a', 'no article'],
    correctIndex: 2,
    explanation: '“University” begins with the consonant sound /y/, so the correct article is “a”.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en2-016',
    section: 'English Comprehension',
    topic: 'Conditional',
    difficulty: 'easy',
    question: 'Choose the correct completion: “Unless you hurry, you ___ the bus.”',
    options: ['missed', 'would miss', 'had missed', 'will miss'],
    correctIndex: 3,
    explanation: 'A real future condition uses the present tense after “unless” and “will” in the main clause.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en2-017',
    section: 'English Comprehension',
    topic: 'Preposition',
    difficulty: 'easy',
    question: 'Choose the correct replacement for “different than mine” in the sentence: “Your approach is different than mine.”',
    options: ['different from mine', 'different to mine', 'more different than mine', 'No replacement required'],
    correctIndex: 0,
    explanation: 'In standard exam usage, “different” is followed by “from”.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en2-018',
    section: 'English Comprehension',
    topic: 'Voice',
    difficulty: 'easy',
    question: 'Choose the correct passive form of “People speak English in many countries.”',
    options: [
      'English spoke in many countries.',
      'English is spoken in many countries.',
      'English was spoken by many countries.',
      'Many countries are spoken in English.',
    ],
    correctIndex: 1,
    explanation: 'The simple present active verb “speak” becomes “is spoken” in the passive voice.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en2-019',
    section: 'English Comprehension',
    topic: 'Narration',
    difficulty: 'medium',
    question: 'Choose the correct indirect form of: He said, “I have completed the task.”',
    options: [
      'He said that I have completed the task.',
      'He says that he completed the task.',
      'He said that he had completed the task.',
      'He told that he has completed the task.',
    ],
    correctIndex: 2,
    explanation: 'The pronoun changes to “he”, and present perfect normally shifts to past perfect after “said”.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en2-020',
    section: 'English Comprehension',
    topic: 'Sentence arrangement',
    difficulty: 'medium',
    question: 'Arrange the sentences logically: P. The alarm rang. Q. Mira left the building. R. She noticed smoke in the corridor. S. She called the fire service.',
    options: ['R, P, Q, S', 'P, Q, R, S', 'R, S, P, Q', 'R, P, S, Q'],
    correctIndex: 3,
    explanation: 'Mira notices smoke, the alarm rings, she calls the fire service, and then leaves the building.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en2-021',
    section: 'English Comprehension',
    topic: 'Reading comprehension',
    difficulty: 'medium',
    question: `Read the passage and answer the question. “${passage}” What is the main idea?`,
    options: [
      'Short, planned breaks can support focused work.',
      'Every break reduces productivity.',
      'Long breaks are essential after every task.',
      'Focused work should never be interrupted.',
    ],
    correctIndex: 0,
    explanation: 'The passage argues that brief, planned breaks can restore attention and reduce errors.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en2-022',
    section: 'English Comprehension',
    topic: 'Reading comprehension',
    difficulty: 'easy',
    question: `Read the passage and answer the question. “${passage}” What benefit of planned pauses is mentioned?`,
    options: ['They eliminate all difficult work.', 'They can restore attention.', 'They make deadlines unnecessary.', 'They lengthen every task.'],
    correctIndex: 1,
    explanation: 'The passage directly states that short, planned pauses can restore attention.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en2-023',
    section: 'English Comprehension',
    topic: 'Reading comprehension',
    difficulty: 'medium',
    question: `Read the passage and answer the question. “${passage}” Which statement is supported by the passage?`,
    options: [
      'Breaks should continue for as long as possible.',
      'Productivity depends only on working longer.',
      'A break is most useful when it is brief and time-bound.',
      'Careless errors cannot be reduced.',
    ],
    correctIndex: 2,
    explanation: 'The passage says the benefit depends on keeping breaks brief and returning at a fixed time.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en2-024',
    section: 'English Comprehension',
    topic: 'Fill in the blank',
    difficulty: 'easy',
    question: 'Fill in the blank: “After checking the figures twice, she approved the report ___ hesitation.”',
    options: ['by', 'at', 'for', 'without'],
    correctIndex: 3,
    explanation: 'The natural expression is “without hesitation”.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en2-025',
    section: 'English Comprehension',
    topic: 'Punctuation',
    difficulty: 'medium',
    question: 'Which sentence correctly punctuates Ravi’s question before leaving?',
    options: [
      'Before leaving, Ravi asked, “Have you locked the door?”',
      'Before leaving Ravi asked “Have you locked the door”?',
      'Before leaving, Ravi asked “Have you locked the door”.',
      'Before leaving Ravi asked, “Have you locked the door”.',
    ],
    correctIndex: 0,
    explanation: 'The introductory phrase and reporting clause take commas, and the question mark belongs inside the quotation marks.',
    source,
  },
];
