import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SSC MTS & Havaldar (CBIC & CBN) Examination 2025 official scheme, Session 2 — English Language and Comprehension section',
  url: 'https://ssc.gov.in/api/attachment/uploads/masterData/NoticeBoards/writeup_mts_03082026.pdf',
  checkedOn: '4 August 2026',
};

export const SSC_MTS_CBT_ENGLISH_LANGUAGE_COMPREHENSION_1: Question[] = [
  { id: 'ssc-mts-cbt-en-001', section: 'English Language and Comprehension', topic: 'Synonym', difficulty: 'easy', question: 'Choose the word closest in meaning to "happy".', options: ['Glad', 'Sad', 'Angry', 'Tired'], correctIndex: 0, negativeMarking: 1, explanation: '"Happy" means feeling pleasure or contentment; "Glad" is the closest synonym.', source },
  { id: 'ssc-mts-cbt-en-002', section: 'English Language and Comprehension', topic: 'Synonym', difficulty: 'easy', question: 'Choose the word closest in meaning to "begin".', options: ['End', 'Start', 'Stop', 'Pause'], correctIndex: 1, negativeMarking: 1, explanation: '"Begin" means to start something; "Start" is the closest synonym.', source },
  { id: 'ssc-mts-cbt-en-003', section: 'English Language and Comprehension', topic: 'Synonym', difficulty: 'easy', question: 'Choose the word closest in meaning to "quick".', options: ['Slow', 'Late', 'Fast', 'Lazy'], correctIndex: 2, negativeMarking: 1, explanation: '"Quick" means moving fast; "Fast" is the closest synonym.', source },
  { id: 'ssc-mts-cbt-en-004', section: 'English Language and Comprehension', topic: 'Synonym', difficulty: 'easy', question: 'Choose the word closest in meaning to "little".', options: ['Huge', 'Wide', 'Long', 'Small'], correctIndex: 3, negativeMarking: 1, explanation: '"Little" means not big in size; "Small" is the closest synonym.', source },
  { id: 'ssc-mts-cbt-en-005', section: 'English Language and Comprehension', topic: 'Antonym', difficulty: 'easy', question: 'Choose the word opposite in meaning to "hot".', options: ['Cold', 'Warm', 'Mild', 'Humid'], correctIndex: 0, negativeMarking: 1, explanation: 'The opposite of "hot" is "cold".', source },
  { id: 'ssc-mts-cbt-en-006', section: 'English Language and Comprehension', topic: 'Antonym', difficulty: 'easy', question: 'Choose the word opposite in meaning to "difficult".', options: ['Hard', 'Easy', 'Tough', 'Complex'], correctIndex: 1, negativeMarking: 1, explanation: 'The opposite of "difficult" (hard) is "easy".', source },
  { id: 'ssc-mts-cbt-en-007', section: 'English Language and Comprehension', topic: 'Antonym', difficulty: 'easy', question: 'Choose the word opposite in meaning to "true".', options: ['Correct', 'Honest', 'False', 'Real'], correctIndex: 2, negativeMarking: 1, explanation: 'The opposite of "true" is "false".', source },
  { id: 'ssc-mts-cbt-en-008', section: 'English Language and Comprehension', topic: 'Antonym', difficulty: 'easy', question: 'Choose the word opposite in meaning to "buy".', options: ['Purchase', 'Gain', 'Own', 'Sell'], correctIndex: 3, negativeMarking: 1, explanation: 'The opposite of "buy" is "sell".', source },
  { id: 'ssc-mts-cbt-en-009', section: 'English Language and Comprehension', topic: 'Spelling', difficulty: 'easy', question: 'Choose the option with no spelling mistake.', options: ['Beautiful', 'Beautifull', 'Beutiful', 'Byootiful'], correctIndex: 0, negativeMarking: 1, explanation: '"Beautiful" is the correct spelling.', source },
  { id: 'ssc-mts-cbt-en-010', section: 'English Language and Comprehension', topic: 'Spelling', difficulty: 'easy', question: 'Pick the correctly spelled word from the options.', options: ['Feburary', 'February', 'Febuary', 'Febraury'], correctIndex: 1, negativeMarking: 1, explanation: '"February" is the correct spelling.', source },
  { id: 'ssc-mts-cbt-en-011', section: 'English Language and Comprehension', topic: 'Spelling', difficulty: 'easy', question: 'Choose the word without any spelling error.', options: ['Twelv', 'Twelfe', 'Twelve', 'Twelvee'], correctIndex: 2, negativeMarking: 1, explanation: '"Twelve" is the correct spelling.', source },
  { id: 'ssc-mts-cbt-en-012', section: 'English Language and Comprehension', topic: 'One-word substitution', difficulty: 'medium', question: 'Choose the word that means "a person who cannot hear".', options: ['Blind', 'Mute', 'Lame', 'Deaf'], correctIndex: 3, negativeMarking: 1, explanation: 'A "deaf" person is one who cannot hear.', source },
  { id: 'ssc-mts-cbt-en-013', section: 'English Language and Comprehension', topic: 'One-word substitution', difficulty: 'medium', question: 'Choose the word that means "a place where books are kept for reading".', options: ['Library', 'Museum', 'Gallery', 'Academy'], correctIndex: 0, negativeMarking: 1, explanation: 'A "library" is a place where books are kept for people to read or borrow.', source },
  { id: 'ssc-mts-cbt-en-014', section: 'English Language and Comprehension', topic: 'Preposition', difficulty: 'easy', question: 'Choose the correct preposition: She is sitting ___ the chair.', options: ['in', 'on', 'at', 'by'], correctIndex: 1, negativeMarking: 1, explanation: '"On the chair" is the correct preposition for something resting on a surface.', source },
  { id: 'ssc-mts-cbt-en-015', section: 'English Language and Comprehension', topic: 'Preposition', difficulty: 'easy', question: 'Choose the correct preposition: He was born ___ 1998.', options: ['at', 'on', 'in', 'since'], correctIndex: 2, negativeMarking: 1, explanation: '"In" is used with a year; "on" is used with specific dates and "at" with clock times.', source },
  { id: 'ssc-mts-cbt-en-016', section: 'English Language and Comprehension', topic: 'Tense', difficulty: 'easy', question: 'Choose the correct completion: She ___ to school every day.', options: ['go', 'going', 'gone', 'goes'], correctIndex: 3, negativeMarking: 1, explanation: 'The third-person singular subject "She" requires the simple present form "goes".', source },
  { id: 'ssc-mts-cbt-en-017', section: 'English Language and Comprehension', topic: 'Tense', difficulty: 'medium', question: 'Choose the correct completion: They ___ dinner when I called.', options: ['are having', 'were having', 'have had', 'had have'], correctIndex: 1, negativeMarking: 1, explanation: 'An ongoing past action interrupted by another past action uses the past continuous tense: "were having".', source },
  { id: 'ssc-mts-cbt-en-018', section: 'English Language and Comprehension', topic: 'Articles', difficulty: 'easy', question: 'Choose the correct article: He is ___ honest boy.', options: ['a', 'an', 'the', 'some'], correctIndex: 1, negativeMarking: 1, explanation: '"Honest" begins with a vowel sound, so it takes the article "an".', source },
  { id: 'ssc-mts-cbt-en-019', section: 'English Language and Comprehension', topic: 'Articles', difficulty: 'easy', question: 'Choose the correct article: I saw ___ elephant at the zoo.', options: ['a', 'some', 'an', 'the'], correctIndex: 2, negativeMarking: 1, explanation: '"Elephant" begins with a vowel sound, so it takes the article "an".', source },
  { id: 'ssc-mts-cbt-en-020', section: 'English Language and Comprehension', topic: 'Idioms', difficulty: 'medium', question: 'What does the idiom "to hit the books" mean?', options: ['To relax', 'To fight', 'To study hard', 'To read a novel'], correctIndex: 2, negativeMarking: 1, explanation: '"To hit the books" means to study hard, especially for an exam.', source },
  { id: 'ssc-mts-cbt-en-021', section: 'English Language and Comprehension', topic: 'Idioms', difficulty: 'medium', question: 'What does the idiom "to keep an eye on" mean?', options: ['To watch carefully', 'To ignore', 'To close eyes', 'To look away'], correctIndex: 0, negativeMarking: 1, explanation: '"To keep an eye on" means to watch someone or something carefully.', source },
  { id: 'ssc-mts-cbt-en-022', section: 'English Language and Comprehension', topic: 'Cloze test', difficulty: 'easy', question: 'Choose the correct word: Please ___ the door before leaving.', options: ['closing', 'close', 'closed', 'closes'], correctIndex: 1, negativeMarking: 1, explanation: 'A polite imperative request uses the base form of the verb: "close".', source },
  { id: 'ssc-mts-cbt-en-023', section: 'English Language and Comprehension', topic: 'Cloze test', difficulty: 'easy', question: 'Choose the correct word: She ___ her homework yesterday.', options: ['complete', 'completing', 'completed', 'completes'], correctIndex: 2, negativeMarking: 1, explanation: '"Yesterday" indicates a completed past action, requiring the simple past tense "completed".', source },
  { id: 'ssc-mts-cbt-en-024', section: 'English Language and Comprehension', topic: 'Sentence improvement', difficulty: 'medium', question: 'Improve the underlined part: "He don\'t like tea."', options: ["don't like", 'not liking', "didn't likes", "doesn't like"], correctIndex: 3, negativeMarking: 1, explanation: 'The third-person singular subject "He" requires "doesn\'t", not "don\'t".', source },
  { id: 'ssc-mts-cbt-en-025', section: 'English Language and Comprehension', topic: 'Sentence improvement', difficulty: 'medium', question: 'Improve the underlined part: "She go to market every day."', options: ['goes to market', 'go to market', 'going to market', 'gone to market'], correctIndex: 0, negativeMarking: 1, explanation: 'The third-person singular subject "She" requires the simple present form "goes to market".', source },
];
