import type { Question, QuestionSource } from '../questions';

const checkedOn = '3 August 2026';
const source = (reference: string, url: string): QuestionSource => ({ kind: 'original', reference, url, checkedOn });

const constitution = source('Constitution of India 2026, Legislative Department, Government of India', 'https://www.legislative.gov.in/documents/constitution-of-india/constitution-of-india-AjN2EjMtQWa?pageTitle=Constitution-of-India');
const permanentSettlement = source('NCERT, Our Pasts III - Ruling the Countryside', 'https://www.ncert.nic.in/textbook/pdf/hess203.pdf');
const sanchi = source('Buddhist Monuments at Sanchi, UNESCO World Heritage Centre', 'https://whc.unesco.org/en/list/524/');
const ajanta = source('Ajanta Caves, UNESCO World Heritage Centre', 'https://whc.unesco.org/en/list/242/');
const fatehpurSikri = source('Fatehpur Sikri, UNESCO World Heritage Centre', 'https://whc.unesco.org/en/list/255/');
const physicalFeatures = source('NCERT, Contemporary India I - Physical Features of India', 'https://www.ncert.nic.in/textbook/pdf/iess102.pdf');
const acidsBases = source('NCERT Science - Acids, Bases and Salts', 'https://www.ncert.nic.in/textbook/pdf/jesc102.pdf');
const electricity = source('NCERT Science - Electricity', 'https://www.ncert.nic.in/textbook/pdf/jesc111.pdf');
const vitamins = source('NCERT Chemistry - Biomolecules', 'https://www.ncert.nic.in/textbook/pdf/lech205.pdf');
const navigation = source('Navigation FAQ, Indian Space Research Organisation', 'https://www.isro.gov.in/ISRO_EN/FAQ_Navigation.html');
const spacecraft = source('Spacecraft Missions, Indian Space Research Organisation', 'https://www.isro.gov.in/ISRO_EN/SpacecraftMissions.html');
const monetaryPolicy = source('Monetary policy instruments overview, Reserve Bank of India', 'https://systemhealth.rbi.org.in/Scripts/FS_Overview2752.aspx.html');

function question(id: string, topic: string, difficulty: 'easy' | 'medium' | 'hard', prompt: string, options: string[], correctIndex: number, explanation: string, provenance: QuestionSource): Question {
  return { id, section: 'General Awareness', topic, difficulty, question: prompt, options, correctIndex, explanation, source: provenance };
}

export const SSC_CGL_TIER2_GENERAL_AWARENESS_3: Question[] = [
  question('ssc-cgl-t2-ga3-001', 'Indian polity', 'easy', 'Under Article 76, who appoints the Attorney-General for India?', ['The President of India', 'The Prime Minister', 'The Chief Justice of India', 'The Speaker of the Lok Sabha'], 0, 'Article 76 provides that the President appoints the Attorney-General for India.', constitution),
  question('ssc-cgl-t2-ga3-002', 'Indian polity', 'medium', 'Which constitutional Article provides for a Finance Commission constituted by the President?', ['Article 148', 'Article 280', 'Article 324', 'Article 356'], 1, 'Article 280 requires the President to constitute a Finance Commission.', constitution),
  question('ssc-cgl-t2-ga3-003', 'Indian polity', 'easy', 'The superintendence, direction and control of elections are vested in the Election Commission by which Article?', ['Article 280', 'Article 312', 'Article 324', 'Article 368'], 2, 'Article 324 vests these election-related powers in the Election Commission.', constitution),
  question('ssc-cgl-t2-ga3-004', 'Indian polity', 'medium', 'Which constitutional body recommends how certain tax proceeds should be distributed between the Union and the States?', ['Election Commission', 'Union Public Service Commission', 'Comptroller and Auditor-General', 'Finance Commission'], 3, 'The Finance Commission makes recommendations on specified financial distributions between the Union and the States.', constitution),
  question('ssc-cgl-t2-ga3-005', 'Indian polity', 'easy', 'The duty to develop scientific temper, humanism and the spirit of inquiry appears in which Article?', ['Article 51A', 'Article 32', 'Article 44', 'Article 110'], 0, 'Article 51A lists the Fundamental Duties, including developing scientific temper, humanism and inquiry.', constitution),
  question('ssc-cgl-t2-ga3-006', 'Modern Indian history', 'easy', 'The Permanent Settlement fixed the revenue that zamindars had to pay to which authority?', ['Village panchayats', 'The East India Company', 'The Mughal emperor', 'Local cooperatives'], 1, 'Under the Permanent Settlement, zamindars collected rent and paid a fixed revenue to the East India Company.', permanentSettlement),
  question('ssc-cgl-t2-ga3-007', 'Ancient Indian history', 'easy', 'Sanchi is principally associated with the monuments of which religion?', ['Jainism', 'Sikhism', 'Buddhism', 'Zoroastrianism'], 2, 'Sanchi is an important complex of Buddhist monuments.', sanchi),
  question('ssc-cgl-t2-ga3-008', 'Art and culture', 'medium', 'The paintings and sculptures at the Ajanta Caves are predominantly associated with which tradition?', ['Roman', 'Islamic', 'Sikh', 'Buddhist'], 3, 'Ajanta is renowned for Buddhist cave monuments, paintings and sculptures.', ajanta),
  question('ssc-cgl-t2-ga3-009', 'Medieval Indian history', 'easy', 'Fatehpur Sikri served briefly as the capital of which empire?', ['The Mughal Empire', 'The Mauryan Empire', 'The Gupta Empire', 'The Chola Empire'], 0, 'Akbar built Fatehpur Sikri as a Mughal capital in the sixteenth century.', fatehpurSikri),
  question('ssc-cgl-t2-ga3-010', 'Art and culture', 'medium', 'The Great Stupa is a prominent monument at which UNESCO World Heritage site?', ['Ajanta Caves', 'Sanchi', 'Fatehpur Sikri', 'Elephanta Caves'], 1, 'The Great Stupa is the best-known monument in the Buddhist complex at Sanchi.', sanchi),
  question('ssc-cgl-t2-ga3-011', 'Indian geography', 'easy', 'Which lake is identified by NCERT as an important feature along India\'s eastern coast?', ['Sambhar Lake', 'Wular Lake', 'Chilika Lake', 'Loktak Lake'], 2, 'NCERT identifies Chilika Lake as an important feature along the eastern coast.', physicalFeatures),
  question('ssc-cgl-t2-ga3-012', 'Indian geography', 'medium', 'What is the southern stretch of India\'s western coastal plain called?', ['Konkan Coast', 'Northern Circar', 'Coromandel Coast', 'Malabar Coast'], 3, 'NCERT calls the southern stretch of the western coastal plain the Malabar Coast.', physicalFeatures),
  question('ssc-cgl-t2-ga3-013', 'Indian geography', 'easy', 'The eastern coastal plain south of the Northern Circar is known as the:', ['Coromandel Coast', 'Konkan Coast', 'Malabar Coast', 'Kannad Plain'], 0, 'The southern portion of the eastern coastal plain is called the Coromandel Coast.', physicalFeatures),
  question('ssc-cgl-t2-ga3-014', 'Indian geography', 'easy', 'The Indian Desert lies mainly to the west of which hills?', ['Vindhya Hills', 'Aravalli Hills', 'Satpura Hills', 'Nilgiri Hills'], 1, 'NCERT places the Indian Desert towards the western margins of the Aravalli Hills.', physicalFeatures),
  question('ssc-cgl-t2-ga3-015', 'Indian geography', 'medium', 'Why do many streams in the Indian Desert disappear into the sand?', ['They are blocked by glaciers', 'They flow only underground from their source', 'They lack enough water to reach the sea', 'They enter the Bay of Bengal'], 2, 'The streams are seasonal and generally lack sufficient water to reach the sea.', physicalFeatures),
  question('ssc-cgl-t2-ga3-016', 'Chemistry', 'easy', 'What colour does blue litmus paper turn in an acidic solution?', ['Blue', 'Green', 'Yellow', 'Red'], 3, 'Acids turn blue litmus red.', acidsBases),
  question('ssc-cgl-t2-ga3-017', 'Physics', 'easy', 'What is the SI unit of electric power?', ['Watt', 'Ohm', 'Volt', 'Ampere'], 0, 'Electric power is measured in watts.', electricity),
  question('ssc-cgl-t2-ga3-018', 'Physics', 'medium', 'Which relation correctly represents electric power in terms of voltage and current?', ['P = V/I', 'P = VI', 'P = I/V', 'P = V + I'], 1, 'Electric power equals potential difference multiplied by current: P = VI.', electricity),
  question('ssc-cgl-t2-ga3-019', 'Biology', 'easy', 'Prolonged deficiency of vitamin C causes which disease?', ['Rickets', 'Night blindness', 'Scurvy', 'Beri-beri'], 2, 'Vitamin C deficiency causes scurvy.', vitamins),
  question('ssc-cgl-t2-ga3-020', 'Chemistry', 'easy', 'A neutral aqueous solution has a pH of approximately:', ['1', '5', '10', '7'], 3, 'At ordinary conditions, a neutral aqueous solution has pH 7.', acidsBases),
  question('ssc-cgl-t2-ga3-021', 'Space science', 'medium', 'NavIC is best described as what kind of navigation system?', ['An independent regional navigation system', 'A global weather satellite network', 'A lunar communication system', 'A deep-space telescope'], 0, 'ISRO describes NavIC as an independent regional navigation system serving India and its surrounding region.', navigation),
  question('ssc-cgl-t2-ga3-022', 'Space science', 'easy', 'Which launch vehicle carried India\'s Mars Orbiter Mission?', ['GSLV Mk III', 'PSLV-C25', 'PSLV-C11', 'SSLV-D1'], 1, 'ISRO records PSLV-C25 as the launch vehicle for the Mars Orbiter Mission.', spacecraft),
  question('ssc-cgl-t2-ga3-023', 'Indian economy', 'medium', 'Cash Reserve Ratio requires a bank to maintain a prescribed balance with which institution?', ['SEBI', 'The Ministry of Finance', 'The Reserve Bank of India', 'NABARD'], 2, 'CRR is the balance a bank must maintain with the Reserve Bank as a percentage of its NDTL.', monetaryPolicy),
  question('ssc-cgl-t2-ga3-024', 'Indian economy', 'medium', 'Which group contains assets typically used by banks to maintain the Statutory Liquidity Ratio?', ['Only corporate shares', 'Only foreign currency', 'Only immovable property', 'Government securities, cash and gold'], 3, 'RBI notes that SLR assets typically include unencumbered government securities, cash and gold.', monetaryPolicy),
  question('ssc-cgl-t2-ga3-025', 'Indian economy', 'medium', 'An outright purchase of government securities by RBI under open market operations generally does what?', ['Injects durable liquidity into the banking system', 'Raises the income-tax rate', 'Reduces the number of bank accounts', 'Sets the exchange rate permanently'], 0, 'An RBI purchase pays funds into the banking system and therefore injects durable liquidity.', monetaryPolicy),
];
