import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SSC Phase XIV/2026 Selection Posts official notification, Matriculation-level CBE syllabus',
  url: 'https://ssc.gov.in/api/attachment/uploads/masterData/NoticeBoards/Notice_of_RHQ_2026_phase_xiv.pdf',
  checkedOn: '23 August 2026',
};

type Difficulty = 'easy' | 'medium' | 'hard';
type Row = [section: string, topic: string, difficulty: Difficulty, question: string, answer: string, distractors: [string, string, string], explanation: string];

const rows: Row[] = [
  ['General Intelligence', 'Number series', 'easy', 'Find the next term: 5, 11, 17, 23, ?', '29', ['27', '28', '30'], 'Each term increases by 6, so 23 + 6 = 29.'],
  ['General Intelligence', 'Analogy', 'easy', 'Fish is to Water as Bird is to what?', 'Sky', ['Nest', 'Tree', 'Cage'], 'A fish lives in water, while a bird lives and flies in the sky.'],
  ['General Intelligence', 'Classification', 'easy', 'Which item does not belong with Gold, Silver, Platinum and Wood?', 'Wood', ['Gold', 'Silver', 'Platinum'], 'Gold, silver and platinum are metals; wood is not a metal.'],
  ['General Intelligence', 'Coding-decoding', 'medium', 'If each letter is moved one place forward, how is PLANT coded?', 'QMBOU', ['QMBOT', 'QMANU', 'PMBOU'], 'P, L, A, N and T move forward to Q, M, B, O and U.'],
  ['General Intelligence', 'Blood relations', 'easy', 'Sonu is the son of Meena. Meena is the sister of Raj. How is Raj related to Sonu?', 'Uncle', ['Father', 'Brother', 'Cousin'], "Meena's brother Raj is Sonu's maternal uncle."],
  ['General Intelligence', 'Direction sense', 'medium', 'A person walks 8 m south and then 6 m west. What is the shortest distance from the starting point?', '10 m', ['12 m', '13 m', '14 m'], 'The path forms a 6-8-10 right triangle.'],
  ['General Intelligence', 'Ranking', 'medium', 'Priya is 8th from the front and 15th from the back in a queue. How many people are in the queue?', '22', ['20', '21', '23'], 'Total = 8 + 15 - 1 = 22.'],
  ['General Intelligence', 'Alphabet series', 'easy', 'Complete the letter series: C, G, K, O, ?', 'S', ['R', 'T', 'U'], 'The letters advance by four positions each time.'],
  ['General Intelligence', 'Number analogy', 'medium', '6 is related to 36 in the same way as 8 is related to what?', '64', ['56', '72', '48'], '36 is 6 squared, so the matching value is 8 squared, or 64.'],
  ['General Intelligence', 'Syllogism', 'medium', 'Statements: All pens are tools. All tools are objects. Which conclusion follows?', 'All pens are objects', ['No pen is an object', 'Some objects are not pens', 'Only pens are objects'], 'The two universal statements form a direct logical chain.'],
  ['General Intelligence', 'Odd number', 'easy', 'Select the number that differs from 9, 16, 25 and 30.', '30', ['9', '16', '25'], '9, 16 and 25 are perfect squares; 30 is not.'],
  ['General Intelligence', 'Calendar', 'medium', 'If 1 June is a Wednesday, what day is 10 June?', 'Friday', ['Thursday', 'Saturday', 'Sunday'], 'Nine days after Wednesday is Friday.'],
  ['General Intelligence', 'Venn reasoning', 'medium', 'Which relation is correct for Cats, Mammals and Animals?', 'Cats are within Mammals, and Mammals are within Animals', ['All animals are cats', 'Mammals and animals do not overlap', 'Only some cats are mammals'], 'Every cat is a mammal and every mammal is an animal.'],
  ['General Intelligence', 'Word formation', 'easy', 'Which word cannot be formed using the letters of MOUNTAIN?', 'PAINT', ['NATION', 'MAIN', 'TAINT'], 'PAINT requires a P, which does not occur in MOUNTAIN.'],
  ['General Intelligence', 'Arithmetic reasoning', 'easy', 'If six pens cost Rs 90, what do ten pens cost at the same rate?', 'Rs 150', ['Rs 130', 'Rs 140', 'Rs 160'], 'One pen costs Rs 15, so ten cost Rs 150.'],
  ['General Intelligence', 'Statement and conclusion', 'medium', 'Statement: The ground is slippery. Conclusion: It has just rained. Is the conclusion certain?', 'No, another cause is possible', ['Yes, rain is the only cause', 'Yes, but only in summer', 'No, ground cannot be slippery'], 'Spilled water, oil or another cause could also make the ground slippery.'],
  ['General Intelligence', 'Number series', 'medium', 'Complete the pattern: 3, 7, 15, 31, ?', '63', ['59', '61', '65'], 'Each term follows the rule (previous term x 2) + 1: 31x2+1 = 63.'],
  ['General Intelligence', 'Direction sense', 'easy', 'Facing south, Karan turns left and then left again. Which direction does he face?', 'North', ['East', 'South', 'West'], 'Two left turns reverse the original direction, so south becomes north.'],
  ['General Intelligence', 'Analogy', 'medium', 'Doctor is to Stethoscope as Carpenter is to what?', 'Hammer', ['Syringe', 'Chalk', 'Needle'], 'A doctor commonly uses a stethoscope; a carpenter commonly uses a hammer.'],
  ['General Intelligence', 'Age reasoning', 'medium', 'Meera is 5 years older than Ria. Their ages total 35 years. How old is Meera?', '20 years', ['15 years', '17 years', '22 years'], 'Let Ria be x; x + x + 5 = 35, so Meera is 20.'],
  ['General Intelligence', 'Classification', 'easy', 'Choose the odd pair: Knife-Cutting, Pen-Writing, Brush-Painting, Table-Walking.', 'Table-Walking', ['Knife-Cutting', 'Pen-Writing', 'Brush-Painting'], 'A table is not used for walking; the other objects match their usual functions.'],
  ['General Intelligence', 'Coding-decoding', 'medium', 'In a code, each letter is shifted three places forward in the alphabet, so CAT is written as FDW. How is DOG written?', 'GRJ', ['GRI', 'GQJ', 'FRJ'], 'Shifting each letter three places forward: D→G, O→R, G→J, so DOG is written as GRJ.'],
  ['General Intelligence', 'Ordering', 'easy', 'Arrange from smallest to largest: country, village, district, state.', 'Village, district, state, country', ['District, village, state, country', 'Village, state, district, country', 'Country, state, district, village'], 'A village lies within a district, a district within a state, and a state within a country.'],
  ['General Intelligence', 'Clock reasoning', 'hard', 'What is the smaller angle between the clock hands at 6:00?', '180 degrees', ['150 degrees', '160 degrees', '170 degrees'], 'At 6:00, the hands point to 12 and 6, which are exactly opposite, or 180 degrees apart.'],
  ['General Intelligence', 'Missing number', 'medium', 'If 4 + 2 = 12 and 6 + 3 = 24, following the same rule, what does 5 + 4 = ?', '25', ['20', '22', '28'], 'The rule is a + b = (a x b) + a: 4x2+4=12, 6x3+6=24, so 5x4+5=25.'],

  ['General Awareness', 'Indian polity', 'easy', 'Which Article of the Indian Constitution guarantees the Right to Equality?', 'Article 14', ['Article 19', 'Article 21', 'Article 32'], 'Article 14 guarantees equality before the law and equal protection of the laws.'],
  ['General Awareness', 'Geography', 'easy', 'Which river is the longest river flowing entirely within India?', 'Ganga', ['Godavari', 'Narmada', 'Kaveri'], 'The Ganga is the longest river that flows entirely within Indian territory.'],
  ['General Awareness', 'Science', 'easy', 'Which gas do plants absorb from the air during photosynthesis?', 'Carbon dioxide', ['Oxygen', 'Nitrogen', 'Hydrogen'], 'Plants absorb carbon dioxide during photosynthesis and release oxygen.'],
  ['General Awareness', 'History', 'medium', 'Who was the first ruler of the Mughal Empire in India?', 'Babur', ['Humayun', 'Akbar', 'Shah Jahan'], 'Babur founded the Mughal Empire in India in 1526.'],
  ['General Awareness', 'Biology', 'easy', 'Which organ is primarily responsible for filtering waste from the blood in the human body?', 'Kidney', ['Liver', 'Heart', 'Lung'], 'The kidneys filter waste products from the blood and excrete them as urine.'],
  ['General Awareness', 'Indian polity', 'medium', 'The Directive Principles of State Policy are contained in which part of the Constitution?', 'Part IV', ['Part II', 'Part III', 'Part V'], 'Part IV of the Constitution contains the Directive Principles of State Policy.'],
  ['General Awareness', 'Geography', 'easy', 'Which is the largest desert in India?', 'Thar Desert', ['Kutch Desert', 'Ladakh Desert', 'Rajasthan Plain'], 'The Thar Desert, located mainly in Rajasthan, is the largest desert in India.'],
  ['General Awareness', 'Physics', 'easy', 'What is the SI unit of force?', 'Newton', ['Joule', 'Watt', 'Pascal'], 'The newton is the SI unit of force.'],
  ['General Awareness', 'Culture', 'medium', 'Odissi, a classical dance form, originated in which Indian state?', 'Odisha', ['Kerala', 'Gujarat', 'Punjab'], 'Odissi is a classical dance form that originated in Odisha.'],
  ['General Awareness', 'Economics', 'easy', 'What does inflation measure?', 'A general and sustained rise in the price level of goods and services', ['A fall in government revenue', 'A rise in currency reserves', 'A decrease in exports'], 'Inflation measures a general and sustained rise in the overall price level over time.'],
  ['General Awareness', 'Chemistry', 'easy', 'What is the chemical formula for water?', 'H2O', ['CO2', 'NaCl', 'O2'], 'Water is composed of two hydrogen atoms and one oxygen atom, giving the formula H2O.'],
  ['General Awareness', 'History', 'medium', 'Who gave the famous slogan "Jai Hind"?', 'Subhas Chandra Bose', ['Bhagat Singh', 'Lala Lajpat Rai', 'Chandrashekhar Azad'], 'Subhas Chandra Bose popularised the slogan "Jai Hind".'],
  ['General Awareness', 'Sports', 'easy', 'How many players from one team are on the field in kabaddi at the start of play?', '7', ['5', '6', '9'], 'A kabaddi team fields seven players on the mat at a time.'],
  ['General Awareness', 'Environment', 'medium', 'Which layer of the atmosphere protects the Earth from harmful ultraviolet radiation?', 'Ozone layer', ['Troposphere', 'Mesosphere', 'Thermosphere'], 'The ozone layer, located in the stratosphere, absorbs most harmful ultraviolet radiation.'],
  ['General Awareness', 'Indian polity', 'easy', 'Who appoints the Chief Justice of India?', 'The President', ['The Prime Minister', 'The Parliament', 'The Law Minister'], 'The President of India appoints the Chief Justice of India.'],
  ['General Awareness', 'Biology', 'medium', 'A deficiency of which vitamin is known to cause night blindness?', 'Vitamin A', ['Vitamin B12', 'Vitamin C', 'Vitamin K'], 'A deficiency of Vitamin A is commonly associated with night blindness.'],
  ['General Awareness', 'Geography', 'medium', 'Which is the largest continent by area?', 'Asia', ['Africa', 'Europe', 'North America'], 'Asia is the largest continent by both area and population.'],
  ['General Awareness', 'History', 'easy', 'Who built the Red Fort in Delhi?', 'Shah Jahan', ['Akbar', 'Aurangzeb', 'Babur'], 'The Red Fort in Delhi was built by the Mughal emperor Shah Jahan.'],
  ['General Awareness', 'Sports', 'easy', 'Wimbledon is a major tournament associated with which sport?', 'Tennis', ['Badminton', 'Squash', 'Table Tennis'], 'Wimbledon is one of the four Grand Slam tournaments in tennis.'],
  ['General Awareness', 'Environment', 'medium', 'Which gas is considered the primary greenhouse gas contributing to global warming?', 'Carbon dioxide', ['Nitrogen', 'Argon', 'Hydrogen'], 'Carbon dioxide is one of the primary greenhouse gases that trap heat, contributing to global warming.'],
  ['General Awareness', 'Institutions', 'medium', 'Where is the headquarters of the United Nations located?', 'New York', ['Geneva', 'Washington D.C.', 'Vienna'], 'The headquarters of the United Nations is located in New York, United States.'],
  ['General Awareness', 'Agriculture', 'medium', 'Rice is mainly classified as which seasonal crop in India?', 'Kharif crop', ['Rabi crop', 'Zaid crop', 'Plantation crop'], 'Rice is generally sown with the onset of monsoon and harvested in autumn as a kharif crop.'],
  ['General Awareness', 'Space', 'easy', 'Which planet is commonly known as the Red Planet?', 'Mars', ['Venus', 'Jupiter', 'Mercury'], 'Mars is known as the Red Planet because of the iron oxide on its surface.'],
  ['General Awareness', 'Constitution', 'medium', 'Who is often referred to as the "Father of the Indian Constitution"?', 'B.R. Ambedkar', ['Jawaharlal Nehru', 'Rajendra Prasad', 'Sardar Patel'], 'Dr. B.R. Ambedkar, as chairman of the Drafting Committee, is often called the Father of the Indian Constitution.'],
  ['General Awareness', 'Neighbouring countries', 'easy', 'Kathmandu is the capital of which country neighbouring India?', 'Nepal', ['Bhutan', 'Myanmar', 'Sri Lanka'], 'Kathmandu is the capital city of Nepal, which shares a border with India.'],

  ['Quantitative Aptitude', 'Percentage', 'easy', 'What is 40% of 180?', '72', ['64', '68', '76'], '40% of 180 = 0.40 x 180 = 72.'],
  ['Quantitative Aptitude', 'Fractions', 'easy', 'Simplify 5/6 + 1/3.', '7/6', ['5/9', '6/9', '8/9'], '1/3 equals 2/6, and 5/6 + 2/6 = 7/6.'],
  ['Quantitative Aptitude', 'Ratio', 'easy', 'The ratio of red to blue balls is 2:3. If there are 27 blue balls, how many red balls are there?', '18', ['15', '20', '24'], 'One ratio unit is 9, so red balls = 2 x 9 = 18.'],
  ['Quantitative Aptitude', 'Average', 'easy', 'Find the average of 12, 16, 20 and 24.', '18', ['16', '17', '19'], 'The sum is 72, and 72 divided by 4 is 18.'],
  ['Quantitative Aptitude', 'Profit and loss', 'medium', 'An article costs Rs 500 and is sold for Rs 600. What is the profit percentage?', '20%', ['15%', '18%', '25%'], 'Profit is Rs 100; 100/500 x 100 = 20%.'],
  ['Quantitative Aptitude', 'Simple interest', 'medium', 'Find the simple interest on Rs 3,000 at 5% per year for 4 years.', 'Rs 600', ['Rs 500', 'Rs 550', 'Rs 650'], 'SI = 3000 x 5 x 4 / 100 = Rs 600.'],
  ['Quantitative Aptitude', 'Time and work', 'medium', 'A can finish a job in 10 days and B in 15 days. How long will they take together?', '6 days', ['5 days', '7 days', '8 days'], 'Their combined daily work is 1/10 + 1/15 = 5/30 = 1/6, so time is 6 days.'],
  ['Quantitative Aptitude', 'Speed and distance', 'easy', 'A bus travels 180 km in 4 hours. What is its average speed?', '45 km/h', ['40 km/h', '42 km/h', '48 km/h'], 'Speed = 180/4 = 45 km/h.'],
  ['Quantitative Aptitude', 'HCF', 'easy', 'Find the HCF of 24 and 36.', '12', ['6', '8', '18'], 'The greatest number dividing both 24 and 36 is 12.'],
  ['Quantitative Aptitude', 'LCM', 'easy', 'What is the least positive number divisible by both 6 and 8?', '24', ['12', '16', '48'], 'The least common multiple of 6 and 8 is 24.'],
  ['Quantitative Aptitude', 'Decimals', 'easy', 'What is 3.25 + 1.75?', '5.00', ['4.80', '4.90', '5.10'], 'Aligning decimal places gives 3.25 + 1.75 = 5.00.'],
  ['Quantitative Aptitude', 'Discount', 'medium', 'An item marked Rs 800 is sold at a 10% discount. Find the selling price.', 'Rs 720', ['Rs 680', 'Rs 700', 'Rs 740'], 'The discount is Rs 80, leaving Rs 720.'],
  ['Quantitative Aptitude', 'Mensuration', 'easy', 'Find the perimeter of a rectangle measuring 10 cm by 6 cm.', '32 cm', ['28 cm', '30 cm', '34 cm'], 'Perimeter = 2 x (10 + 6) = 32 cm.'],
  ['Quantitative Aptitude', 'Unitary method', 'easy', 'Five books cost Rs 250. What is the cost of eight books?', 'Rs 400', ['Rs 360', 'Rs 380', 'Rs 420'], 'Each book costs Rs 50, so eight cost Rs 400.'],
  ['Quantitative Aptitude', 'Time', 'medium', 'A train leaves at 09:15 and arrives at 13:40. How long is the journey?', '4 hours 25 minutes', ['4 hours 15 minutes', '4 hours 35 minutes', '4 hours 45 minutes'], 'From 09:15 to 13:40 is 4 hours 25 minutes.'],
  ['Quantitative Aptitude', 'Number system', 'easy', 'What is the smallest prime number greater than 20?', '23', ['21', '22', '24'], '23 has no positive divisors other than 1 and 23.'],
  ['Quantitative Aptitude', 'Percentage change', 'medium', 'A quantity rises from 50 to 65. What is the percentage increase?', '30%', ['25%', '28%', '35%'], 'The increase is 15, and 15/50 x 100 = 30%.'],
  ['Quantitative Aptitude', 'Mixture', 'medium', 'A 15-litre mixture contains milk and water in the ratio 2:1. How much milk is present?', '10 litres', ['5 litres', '7 litres', '12 litres'], 'Milk is 2/3 of 15 litres, which equals 10 litres.'],
  ['Quantitative Aptitude', 'Algebra', 'medium', 'If 3x - 5 = 16, what is x?', '7', ['6', '8', '9'], '3x = 21, so x = 7.'],
  ['Quantitative Aptitude', 'Area', 'easy', 'What is the area of a triangle with base 12 cm and height 8 cm?', '48 sq cm', ['40 sq cm', '44 sq cm', '52 sq cm'], 'Area = 1/2 x 12 x 8 = 48 sq cm.'],
  ['Quantitative Aptitude', 'Work and wages', 'medium', 'Four workers earn Rs 800 equally for a day. How much does each receive?', 'Rs 200', ['Rs 150', 'Rs 175', 'Rs 225'], 'Rs 800 divided equally among four workers is Rs 200 each.'],
  ['Quantitative Aptitude', 'Data interpretation', 'medium', 'A shop sold 15, 20 and 25 books on three days. What was the total sale?', '60 books', ['55 books', '58 books', '62 books'], '15 + 20 + 25 = 60.'],
  ['Quantitative Aptitude', 'Squares', 'easy', 'Evaluate 15 squared minus 9 squared.', '144', ['126', '132', '156'], 'Using a squared minus b squared: (15-9)(15+9) = 6 x 24 = 144.'],
  ['Quantitative Aptitude', 'Pipes and cisterns', 'hard', 'A tap fills a tank in 10 hours. What fraction of the tank does it fill in 4 hours?', '2/5', ['1/5', '3/10', '3/5'], 'At a constant rate it fills 1/10 per hour, so in 4 hours it fills 4/10, or 2/5.'],
  ['Quantitative Aptitude', 'Division', 'easy', 'What remainder is left when 200 is divided by 13?', '5', ['3', '4', '7'], '13 x 15 = 195, and 200 - 195 = 5.'],

  ['English Language', 'Synonym', 'easy', "Choose the synonym of 'brave'.", 'Courageous', ['Timid', 'Weak', 'Careless'], 'Brave means courageous or fearless.'],
  ['English Language', 'Antonym', 'easy', "Select the antonym of 'genuine'.", 'Fake', ['Honest', 'Real', 'Sincere'], 'Fake is opposite in meaning to genuine.'],
  ['English Language', 'Spelling', 'easy', 'Which word is spelled correctly?', 'Definitely', ['Definately', 'Definitly', 'Defenitely'], 'Definitely is the correct spelling.'],
  ['English Language', 'Fill in the blank', 'easy', 'The birds ___ singing in the morning.', 'are', ['is', 'was', 'has'], 'The plural subject birds takes are.'],
  ['English Language', 'Articles', 'easy', 'She has ___ honest friend.', 'an', ['a', 'the one', 'no article'], 'Honest begins with a vowel sound, so an is used.'],
  ['English Language', 'Preposition', 'easy', 'The cat is sleeping ___ the table.', 'under', ['during', 'since', 'until'], 'Under correctly describes the location of the cat.'],
  ['English Language', 'Subject-verb agreement', 'medium', 'Which sentence uses the correct verb after "each"?', 'Each of the girls is ready.', ['Each of the girls are ready.', 'Each of the girl are ready.', 'Each girls is ready.'], 'Each is singular and therefore takes is.'],
  ['English Language', 'Tense', 'medium', 'By tomorrow, I ___ finished the book.', 'will have', ['finished', 'will finishing', 'have finish'], 'The future perfect describes an action completed before a future time.'],
  ['English Language', 'One-word substitution', 'easy', 'A person who loves and collects books is called what?', 'Bibliophile', ['Immigrant', 'Introvert', 'Invalid'], 'Bibliophile means a person who loves and collects books.'],
  ['English Language', 'Idiom', 'medium', "What does 'to break the ice' mean?", 'To start a conversation in an awkward situation', ['To cause an accident', 'To end a friendship', 'To finish a task quickly'], 'The idiom means to ease tension or begin conversation in a socially uncomfortable setting.'],
  ['English Language', 'Voice', 'medium', "Choose the passive form of 'The chef cooked the meal.'", 'The meal was cooked by the chef.', ['The meal is cooked by the chef.', 'The chef was cooked by the meal.', 'The meal had cooking by the chef.'], 'Simple past active becomes was cooked in the passive.'],
  ['English Language', 'Narration', 'medium', "Change to indirect speech: Sam said, 'I am happy.'", 'Sam said that he was happy.', ['Sam said that I am happy.', 'Sam says he is happy.', 'Sam said that he has happy.'], 'The pronoun and tense shift in reported speech.'],
  ['English Language', 'Sentence correction', 'medium', 'Identify the correct form: She does not ___ tea.', 'like', ['likes', 'liked', 'liking'], 'After does not, the base form like is required.'],
  ['English Language', 'Vocabulary', 'easy', "What does 'ancient' mean?", 'Very old', ['Very costly', 'Brightly coloured', 'Hard to carry'], 'Ancient describes something belonging to a very distant past.'],
  ['English Language', 'Plural', 'easy', "What is the plural of 'child'?", 'Children', ['Childs', 'Childes', 'Childrens'], "Child has the irregular plural children."],
  ['English Language', 'Pronoun', 'medium', 'Neither Tom nor his friends ___ coming today.', 'are', ['is', 'was', 'has'], 'With neither...nor, the verb agrees with the nearer subject, "friends", which is plural.'],
  ['English Language', 'Conjunction', 'easy', 'I left early ___ I was tired.', 'because', ['unless', 'although', 'until'], 'Because introduces the reason for leaving early.'],
  ['English Language', 'Error spotting', 'medium', 'Which part contains the error: He / go / to school / every day?', 'go', ['He', 'to school', 'every day'], 'The singular subject he requires goes, not go.'],
  ['English Language', 'Synonym', 'medium', "Choose the word closest in meaning to 'huge'.", 'Enormous', ['Tiny', 'Narrow', 'Faint'], 'Huge means very large in size, closest to enormous.'],
  ['English Language', 'Antonym', 'medium', "Choose the opposite of 'increase'.", 'Decrease', ['Expand', 'Extend', 'Enlarge'], 'Decrease means to become smaller, the opposite of increase.'],
  ['English Language', 'Sentence order', 'medium', 'Choose the logical order: P: the teacher entered; Q: the class; R: stood up; S: and greeted her.', 'P-Q-R-S', ['Q-P-S-R', 'R-Q-P-S', 'P-R-S-Q'], 'The sentence reads: The teacher entered the class; students stood up and greeted her.'],
  ['English Language', 'Homophone', 'easy', 'Choose the correct word: I want to ___ a letter.', 'write', ['right', 'rite', 'wright'], 'Write means to form words on a surface.'],
  ['English Language', 'Degree of comparison', 'medium', 'Which option correctly compares the widths of two roads?', 'This road is wider than that one.', ['This road is more wide than that one.', 'This road is widest than that one.', 'This road is wider then that one.'], 'Wider than is the correct comparative construction.'],
  ['English Language', 'Comprehension', 'medium', 'A notice says, "The office will remain closed on Monday for renovation." Why will it close?', 'For renovation', ['For a holiday', 'For an inspection', 'For staff training'], 'The reason is stated directly in the notice.'],
  ['English Language', 'Punctuation', 'hard', 'Which option correctly punctuates the introductory phrase "After school"?', 'After school, we went home.', ['After school we, went home.', 'After school we went, home.', 'After school; we went, home.'], 'An introductory phrase is correctly followed by a comma.'],
];

function placeAnswer(answer: string, distractors: [string, string, string], index: number) {
  const options = [...distractors];
  options.splice(index, 0, answer);
  return options;
}

export const SSC_SELECTION_POST_MATRICULATION_CBE_2: Question[] = rows.map(
  ([section, topic, difficulty, question, answer, distractors, explanation], index) => ({
    id: `ssc-sp-mat2-${String(index + 1).padStart(3, '0')}`,
    section,
    topic,
    difficulty,
    question,
    options: placeAnswer(answer, distractors, index % 4),
    correctIndex: index % 4,
    explanation,
    source,
  }),
);
