import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SSC CHSL 2026 official notification, Tier 2 syllabus — Section 2, Module I: English Language and Comprehension',
  url: 'https://ssc.gov.in/for-candidates/cgl-exam/s40d16nackd16h0',
  checkedOn: '27 August 2026',
};

const RC_PASSAGE =
  'Access to reliable electricity has long been a challenge for many rural communities in India, where extending the traditional power grid to remote villages is often costly and logistically difficult. In recent years, decentralized solar microgrids have emerged as a practical alternative, allowing villages to generate and distribute their own electricity without waiting for grid connections that may take years to materialize. These microgrids typically combine solar panels, battery storage, and a local distribution network, enabling households to power lights, fans, and small appliances, while also supporting local businesses such as flour mills and cold storage units. Beyond improving quality of life, reliable electricity access has been linked to longer study hours for children, extended working hours for local shops, and reduced dependence on kerosene lamps and diesel generators. However, sustaining these microgrids requires ongoing maintenance, trained local technicians, and a viable payment model that keeps the system financially self-sufficient over time. Villages that have paired solar microgrids with a clear community-led maintenance plan tend to see their systems remain operational far longer than those that rely solely on external support.';

export const SSC_CHSL_TIER2_ENGLISH_LANGUAGE_COMPREHENSION_1: Question[] = [
  { id: 'ssc-chsl-t2-en-001', section: 'English Language and Comprehension', topic: 'Reading comprehension', difficulty: 'medium', question: `${RC_PASSAGE}\n\nAccording to the passage, what is the main reason decentralized solar microgrids have become popular in rural India?`, options: ['Extending the traditional grid to remote villages is costly and logistically difficult', 'Solar panels are cheaper than traditional grid infrastructure everywhere', 'The government has banned diesel generators', 'Rural communities prefer renewable energy for environmental reasons'], correctIndex: 0, explanation: 'The passage states that extending the traditional power grid to remote villages is often costly and logistically difficult, which is why microgrids emerged as a practical alternative.', source },
  { id: 'ssc-chsl-t2-en-002', section: 'English Language and Comprehension', topic: 'Reading comprehension', difficulty: 'easy', question: `${RC_PASSAGE}\n\nWhich three components do solar microgrids typically combine, according to the passage?`, options: ['Solar panels, battery storage, and a local distribution network', 'Solar panels, diesel generators, and transmission towers', 'Wind turbines, battery storage, and transformers', 'Solar panels, battery storage, and long-distance transmission lines'], correctIndex: 0, explanation: 'The passage states that these microgrids typically combine solar panels, battery storage, and a local distribution network.', source },
  { id: 'ssc-chsl-t2-en-003', section: 'English Language and Comprehension', topic: 'Reading comprehension', difficulty: 'medium', question: `${RC_PASSAGE}\n\nBased on the passage, what is required to sustain solar microgrids over the long term?`, options: ['Ongoing maintenance, trained local technicians, and a viable payment model', 'Continuous government subsidies alone', 'Replacing solar panels every year', 'A permanent connection to the national grid'], correctIndex: 0, explanation: 'The passage states that sustaining these microgrids requires ongoing maintenance, trained local technicians, and a viable payment model.', source },
  { id: 'ssc-chsl-t2-en-004', section: 'English Language and Comprehension', topic: 'Reading comprehension', difficulty: 'medium', question: `${RC_PASSAGE}\n\nWhat does the passage suggest about villages that pair solar microgrids with a community-led maintenance plan?`, options: ['Their systems tend to remain operational for longer', 'They no longer need battery storage', 'They receive free electricity from the government', 'Their systems operate only during the day'], correctIndex: 0, explanation: 'The passage states that villages pairing microgrids with a community-led maintenance plan see their systems remain operational far longer than those relying solely on external support.', source },
  { id: 'ssc-chsl-t2-en-005', section: 'English Language and Comprehension', topic: 'Cloze test', difficulty: 'medium', question: 'The new policy will _______ into effect from next month.', options: ['come', 'comes', 'coming', 'came'], correctIndex: 0, explanation: 'After the modal "will", the verb must be in its base form: "will come".', source },
  { id: 'ssc-chsl-t2-en-006', section: 'English Language and Comprehension', topic: 'Cloze test', difficulty: 'easy', question: 'She has been working in this company _______ five years.', options: ['for', 'since', 'from', 'during'], correctIndex: 0, explanation: '"For" is used with a duration of time (five years), while "since" is used with a specific point in time.', source },
  { id: 'ssc-chsl-t2-en-007', section: 'English Language and Comprehension', topic: 'Cloze test', difficulty: 'medium', question: 'He was too tired _______ continue the journey.', options: ['to', 'that', 'so', 'for'], correctIndex: 0, explanation: 'The construction "too...to" is used to show that something is not possible due to an excessive degree.', source },
  { id: 'ssc-chsl-t2-en-008', section: 'English Language and Comprehension', topic: 'Cloze test', difficulty: 'medium', question: 'If it rains tomorrow, we _______ the picnic.', options: ['will cancel', 'cancel', 'canceled', 'would cancel'], correctIndex: 0, explanation: 'This is a first conditional sentence: "If + present simple, will + base verb" describes a likely future outcome.', source },
  { id: 'ssc-chsl-t2-en-009', section: 'English Language and Comprehension', topic: 'Error spotting', difficulty: 'medium', question: 'Identify the part with an error: (A) The team of players / (B) are practicing hard / (C) for the upcoming / (D) championship match.', options: ['A', 'B', 'C', 'D'], correctIndex: 1, explanation: '"Team" is a singular collective noun here, so it should be "is practicing", not "are practicing" — the error is in part B.', source },
  { id: 'ssc-chsl-t2-en-010', section: 'English Language and Comprehension', topic: 'Error spotting', difficulty: 'medium', question: 'Identify the part with an error: (A) Neither of the answers / (B) were correct / (C) according to / (D) the teacher.', options: ['A', 'B', 'C', 'D'], correctIndex: 1, explanation: '"Neither" is singular and takes a singular verb, so it should be "was correct", not "were correct" — the error is in part B.', source },
  { id: 'ssc-chsl-t2-en-011', section: 'English Language and Comprehension', topic: 'Error spotting', difficulty: 'easy', question: 'Identify the part with an error: (A) She don\'t like / (B) to attend meetings / (C) that start / (D) early in the morning.', options: ['A', 'B', 'C', 'D'], correctIndex: 0, explanation: 'With the third-person singular subject "She", the correct form is "doesn\'t like", not "don\'t like" — the error is in part A.', source },
  { id: 'ssc-chsl-t2-en-012', section: 'English Language and Comprehension', topic: 'Error spotting', difficulty: 'medium', question: 'Identify the part with an error: (A) Each of the students / (B) have submitted / (C) their assignment / (D) on time.', options: ['A', 'B', 'C', 'D'], correctIndex: 1, explanation: '"Each" is singular and takes a singular verb, so it should be "has submitted", not "have submitted" — the error is in part B.', source },
  { id: 'ssc-chsl-t2-en-013', section: 'English Language and Comprehension', topic: 'Sentence improvement', difficulty: 'medium', question: 'Improve the underlined part: "He is used to _work_ late at night."', options: ['working', 'work', 'worked', 'works'], correctIndex: 0, explanation: '"Used to" as an adjective phrase meaning "accustomed to" must be followed by a gerund: "used to working".', source },
  { id: 'ssc-chsl-t2-en-014', section: 'English Language and Comprehension', topic: 'Sentence improvement', difficulty: 'hard', question: 'Improve the underlined part: "Neither the manager nor the employees _was present_."', options: ['was present', 'has been present', 'is present', 'were present'], correctIndex: 3, explanation: 'With "neither...nor", the verb agrees with the nearer subject; since "employees" (plural) is closer, the verb should be "were present".', source },
  { id: 'ssc-chsl-t2-en-015', section: 'English Language and Comprehension', topic: 'Sentence improvement', difficulty: 'medium', question: 'Improve the underlined part: "The number of accidents _have increased_ this year."', options: ['have increased', 'having increased', 'has increased', 'had increase'], correctIndex: 2, explanation: '"The number of" is treated as singular, so the verb should be "has increased", not "have increased".', source },
  { id: 'ssc-chsl-t2-en-016', section: 'English Language and Comprehension', topic: 'Fill in the blanks', difficulty: 'easy', question: "The manager was _______ with the team's performance this quarter.", options: ['please', 'pleased', 'pleasing', 'pleasure'], correctIndex: 1, explanation: 'The adjective "pleased" (meaning satisfied) correctly follows "was".', source },
  { id: 'ssc-chsl-t2-en-017', section: 'English Language and Comprehension', topic: 'Fill in the blanks', difficulty: 'medium', question: 'It is important to _______ the instructions carefully before starting the exam.', options: ['reading', 'reads', 'readable', 'read'], correctIndex: 3, explanation: 'After "to" (infinitive marker), the base form of the verb is used: "to read".', source },
  { id: 'ssc-chsl-t2-en-018', section: 'English Language and Comprehension', topic: 'Fill in the blanks', difficulty: 'medium', question: 'The committee _______ several proposals before reaching a decision.', options: ['review', 'reviewing', 'reviewed', 'reviews'], correctIndex: 2, explanation: 'The phrase "before reaching a decision" indicates a completed past action, requiring the simple past tense "reviewed".', source },
  { id: 'ssc-chsl-t2-en-019', section: 'English Language and Comprehension', topic: 'Synonym', difficulty: 'medium', question: 'Choose the word closest in meaning to "vigilant".', options: ['Careless', 'Watchful', 'Hasty', 'Indifferent'], correctIndex: 1, explanation: '"Vigilant" means alert and watchful for possible danger, closest in meaning to "Watchful".', source },
  { id: 'ssc-chsl-t2-en-020', section: 'English Language and Comprehension', topic: 'Synonym', difficulty: 'medium', question: 'Choose the word closest in meaning to "candid".', options: ['Deceptive', 'Secretive', 'Vague', 'Frank'], correctIndex: 3, explanation: '"Candid" means truthful and straightforward, closest in meaning to "Frank".', source },
  { id: 'ssc-chsl-t2-en-021', section: 'English Language and Comprehension', topic: 'Synonym', difficulty: 'easy', question: 'Choose the word closest in meaning to "abundant".', options: ['Scarce', 'Limited', 'Plentiful', 'Rare'], correctIndex: 2, explanation: '"Abundant" means existing in large quantities, closest in meaning to "Plentiful".', source },
  { id: 'ssc-chsl-t2-en-022', section: 'English Language and Comprehension', topic: 'Antonym', difficulty: 'medium', question: 'Choose the word most nearly OPPOSITE in meaning to "punctual".', options: ['Prompt', 'Late', 'Timely', 'Early'], correctIndex: 1, explanation: '"Punctual" means arriving or doing something at the correct time; its opposite is "Late".', source },
  { id: 'ssc-chsl-t2-en-023', section: 'English Language and Comprehension', topic: 'Antonym', difficulty: 'medium', question: 'Choose the word most nearly OPPOSITE in meaning to "generous".', options: ['Kind', 'Charitable', 'Giving', 'Stingy'], correctIndex: 3, explanation: '"Generous" means willing to give freely; its opposite is "Stingy".', source },
  { id: 'ssc-chsl-t2-en-024', section: 'English Language and Comprehension', topic: 'Antonym', difficulty: 'easy', question: 'Choose the word most nearly OPPOSITE in meaning to "genuine".', options: ['Authentic', 'Real', 'Fake', 'Sincere'], correctIndex: 2, explanation: '"Genuine" means real or authentic; its opposite is "Fake".', source },
  { id: 'ssc-chsl-t2-en-025', section: 'English Language and Comprehension', topic: 'Idioms', difficulty: 'medium', question: 'What does the idiom "to burn the midnight oil" mean?', options: ['To start a fire accidentally', 'To study or work late into the night', 'To waste time', 'To finish work early'], correctIndex: 1, explanation: '"To burn the midnight oil" means to work or study late into the night.', source },
  { id: 'ssc-chsl-t2-en-026', section: 'English Language and Comprehension', topic: 'Idioms', difficulty: 'easy', question: 'What does the idiom "a piece of cake" mean?', options: ['A dessert item', 'A difficult task', 'A small reward', 'Something very easy to do'], correctIndex: 3, explanation: '"A piece of cake" is an idiom meaning something that is very easy to accomplish.', source },
  { id: 'ssc-chsl-t2-en-027', section: 'English Language and Comprehension', topic: 'Idioms', difficulty: 'hard', question: 'What does the idiom "to hit the nail on the head" mean?', options: ['To fail at a task', 'To work with tools', 'To describe exactly what is causing a situation', 'To argue unnecessarily'], correctIndex: 2, explanation: '"To hit the nail on the head" means to describe exactly the cause of a problem or situation.', source },
  { id: 'ssc-chsl-t2-en-028', section: 'English Language and Comprehension', topic: 'One-word substitution', difficulty: 'medium', question: 'A person who studies the stars and planets scientifically is called:', options: ['Astrologer', 'Astronomer', 'Geologist', 'Meteorologist'], correctIndex: 1, explanation: 'An "astronomer" is a scientist who studies celestial objects such as stars and planets.', source },
  { id: 'ssc-chsl-t2-en-029', section: 'English Language and Comprehension', topic: 'One-word substitution', difficulty: 'medium', question: 'A statement that cannot be believed is called:', options: ['Credible', 'Plausible', 'Reliable', 'Incredible'], correctIndex: 3, explanation: '"Incredible" describes something that is impossible or hard to believe.', source },
  { id: 'ssc-chsl-t2-en-030', section: 'English Language and Comprehension', topic: 'One-word substitution', difficulty: 'easy', question: 'A place where books are kept for reading or borrowing is called:', options: ['Bookstore', 'Archive', 'Library', 'Museum'], correctIndex: 2, explanation: 'A "library" is a place where books are collected and made available for reading or borrowing.', source },
  { id: 'ssc-chsl-t2-en-031', section: 'English Language and Comprehension', topic: 'Active and passive voice', difficulty: 'medium', question: 'Choose the correct passive voice of: "The manager approved the request."', options: ['The request is approved by the manager.', 'The request was approved by the manager.', 'The request had been approving by the manager.', 'The request approves by the manager.'], correctIndex: 1, explanation: 'The original sentence is in simple past active voice, so the correct passive form is "The request was approved by the manager."', source },
  { id: 'ssc-chsl-t2-en-032', section: 'English Language and Comprehension', topic: 'Active and passive voice', difficulty: 'hard', question: 'Choose the correct passive voice of: "They are building a new bridge."', options: ['A new bridge was built by them.', 'A new bridge has been building by them.', 'A new bridge builds by them.', 'A new bridge is being built by them.'], correctIndex: 3, explanation: 'The original sentence is in present continuous active voice, so the correct passive form is "A new bridge is being built by them."', source },
  { id: 'ssc-chsl-t2-en-033', section: 'English Language and Comprehension', topic: 'Active and passive voice', difficulty: 'hard', question: 'Choose the correct passive voice of: "She will complete the project by Friday."', options: ['The project is completed by her by Friday.', 'The project was completed by her by Friday.', 'The project will be completed by her by Friday.', 'The project will complete by her by Friday.'], correctIndex: 2, explanation: 'The original sentence uses the future tense with "will", so the correct passive form retains that tense: "will be completed".', source },
  { id: 'ssc-chsl-t2-en-034', section: 'English Language and Comprehension', topic: 'Direct and indirect speech', difficulty: 'medium', question: 'Convert to indirect speech: She said, "I am reading a book."', options: ['She said that she is reading a book.', 'She said that she was reading a book.', 'She says that she was reading a book.', 'She said that she read a book.'], correctIndex: 1, explanation: 'In indirect speech, the present continuous tense ("am reading") changes to past continuous ("was reading") when the reporting verb is in the past tense.', source },
  { id: 'ssc-chsl-t2-en-035', section: 'English Language and Comprehension', topic: 'Direct and indirect speech', difficulty: 'hard', question: 'Convert to indirect speech: He said, "I will call you tomorrow."', options: ['He said that he will call me tomorrow.', 'He says that he would call me tomorrow.', 'He said that he would call me tomorrow.', 'He said that he would call me the next day.'], correctIndex: 3, explanation: 'In indirect speech, "will" changes to "would" and "tomorrow" changes to "the next day" when the reporting verb is in the past tense.', source },
  { id: 'ssc-chsl-t2-en-036', section: 'English Language and Comprehension', topic: 'Direct and indirect speech', difficulty: 'medium', question: 'Convert to indirect speech: The teacher said, "Submit your assignments on time."', options: ['The teacher said the students to submit their assignments on time.', 'The teacher told the students submitting their assignments on time.', 'The teacher told the students to submit their assignments on time.', 'The teacher tells the students to submit their assignments on time.'], correctIndex: 2, explanation: 'An imperative sentence in indirect speech is reported using "told...to" followed by the base verb.', source },
  { id: 'ssc-chsl-t2-en-037', section: 'English Language and Comprehension', topic: 'Spelling', difficulty: 'medium', question: 'Choose the correctly spelled word.', options: ['Accomodate', 'Acommodate', 'Accommodatte', 'Accommodate'], correctIndex: 3, explanation: '"Accommodate" is spelled with double "c" and double "m".', source },
  { id: 'ssc-chsl-t2-en-038', section: 'English Language and Comprehension', topic: 'Spelling', difficulty: 'medium', question: 'Select the correctly spelled word from the options below.', options: ['Occurence', 'Ocurrence', 'Occurrence', 'Occurrance'], correctIndex: 2, explanation: '"Occurrence" is spelled with double "c" and double "r", ending in "-ence".', source },
  { id: 'ssc-chsl-t2-en-039', section: 'English Language and Comprehension', topic: 'Para jumbles', difficulty: 'hard', question: 'Arrange the sentences in the correct order to form a meaningful paragraph:\nP. As a result, more people began working from home.\nQ. The pandemic changed the way many companies operated.\nR. This shift led to a growing demand for reliable home internet connections.\nS. Offices reduced their physical staff to limit the spread of infection.', options: ['QPSR', 'SQPR', 'QSRP', 'QSPR'], correctIndex: 3, explanation: 'The logical order is: the pandemic changed operations (Q), offices reduced staff (S), more people worked from home (P), which increased demand for home internet (R).', source },
  { id: 'ssc-chsl-t2-en-040', section: 'English Language and Comprehension', topic: 'Para jumbles', difficulty: 'hard', question: 'Arrange the sentences in the correct order to form a meaningful paragraph:\nP. This made the fruit an important source of income for local farmers.\nQ. Mangoes have been cultivated in India for thousands of years.\nR. Today, India is the largest producer of mangoes in the world.\nS. Over time, cultivation techniques improved crop yield significantly.', options: ['QPSR', 'SQPR', 'QSPR', 'QRSP'], correctIndex: 2, explanation: 'The logical order is: mangoes have been cultivated for a long time (Q), techniques improved yield (S), which made it an income source (P), leading to India being the top producer today (R).', source },
];
