import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SSC Phase XIV/2026 Selection Posts official notification, Graduation-and-above CBE syllabus',
  url: 'https://ssc.gov.in/api/attachment/uploads/masterData/NoticeBoards/Notice_of_RHQ_2026_phase_xiv.pdf',
  checkedOn: '9 August 2026',
};

type Difficulty = 'easy' | 'medium' | 'hard';
type Row = [section: string, topic: string, difficulty: Difficulty, question: string, answer: string, distractors: [string, string, string], explanation: string];

const rows: Row[] = [
  ['General Intelligence', 'Number series', 'medium', 'Continue this doubling-plus-one series: 5, 11, 23, 47, 95, ?', '191', ['187', '189', '193'], 'Each term is twice the previous term plus 1.'],
  ['General Intelligence', 'Semantic analogy', 'medium', 'Constitution is to Government as Blueprint is to what?', 'Building', ['Architect', 'Paper', 'Measurement'], 'A constitution guides a government; a blueprint guides construction of a building.'],
  ['General Intelligence', 'Classification', 'medium', 'Select the odd item: Hypothesis, Experiment, Observation, Superstition.', 'Superstition', ['Hypothesis', 'Experiment', 'Observation'], 'The first three belong to scientific inquiry; superstition does not.'],
  ['General Intelligence', 'Coding-decoding', 'hard', 'In a code, each consonant moves two places forward and each vowel one place backward. How is MIND coded?', 'OHPF', ['OJPF', 'NHMF', 'OHPE'], 'M-O, I-H, N-P and D-F, giving OHPF.'],
  ['General Intelligence', 'Blood relations', 'medium', 'Pointing to a photograph, Arun said, "She is the daughter of the only son of my grandfather." How is she related to Arun?', 'Sister', ['Mother', 'Aunt', 'Cousin'], 'The grandfather\'s only son is Arun\'s father; his daughter is Arun\'s sister.'],
  ['General Intelligence', 'Direction and distance', 'medium', 'A surveyor walks 9 km north, 12 km east, and 9 km south. How far and in which direction is the final point from the start?', '12 km east', ['9 km east', '12 km west', '15 km east'], 'North and south cancel, leaving 12 km east.'],
  ['General Intelligence', 'Ranking', 'medium', 'In a merit list, A is 14 places above B. B is 39th. What is A\'s rank?', '25th', ['24th', '26th', '53rd'], '39 - 14 = 25.'],
  ['General Intelligence', 'Syllogism', 'hard', 'Statements: All analysts are graduates. Some graduates are writers. Which conclusion is definitely valid?', 'All analysts are graduates', ['Some analysts are writers', 'All writers are analysts', 'No graduate is a writer'], 'Only the first conclusion restates a guaranteed relation.'],
  ['General Intelligence', 'Statement and inference', 'hard', 'A city report says bus ridership rose after service frequency increased, while fares stayed unchanged. Which inference is best supported?', 'More frequent service may have encouraged ridership', ['Lower fares caused the increase', 'Every resident stopped using cars', 'The city added no buses'], 'The stated change associated with the rise is increased frequency, not fares.'],
  ['General Intelligence', 'Number analogy', 'medium', '18 : 342 :: 14 : ?', '210', ['196', '204', '224'], 'The rule is n x (n + 1): 18 x 19 = 342 and 14 x 15 = 210.'],
  ['General Intelligence', 'Alphabet coding', 'medium', 'If POLICY is arranged in reverse alphabetical order, which letter is third?', 'O', ['Y', 'P', 'L'], 'Reverse alphabetical order is Y, P, O, L, I, C.'],
  ['General Intelligence', 'Calendar', 'hard', 'If 15 August is a Tuesday, what day is 2 September of the same year?', 'Saturday', ['Thursday', 'Friday', 'Sunday'], 'Eighteen days later advances by four weekdays, from Tuesday to Saturday.'],
  ['General Intelligence', 'Data sufficiency', 'hard', 'Is integer n divisible by 12? I: n is divisible by 3. II: n is divisible by 4.', 'Both statements together are sufficient', ['Statement I alone is sufficient', 'Statement II alone is sufficient', 'Even together they are insufficient'], 'Divisibility by both 3 and 4 guarantees divisibility by 12.'],
  ['General Intelligence', 'Word building', 'medium', 'Which word cannot be made from CHARACTERISTIC using available letters?', 'ARCHITECTURE', ['STATIC', 'REACT', 'CRITIC'], 'ARCHITECTURE requires U, which is absent from CHARACTERISTIC.'],
  ['General Intelligence', 'Symbolic operations', 'medium', 'If % means minus, & means divide, and $ means plus, evaluate 30 & 5 $ 8 % 3.', '11', ['7', '13', '17'], 'Substitution gives 30/5 + 8 - 3 = 11.'],
  ['General Intelligence', 'Seating arrangement', 'hard', 'Six people sit in a row. F is at the left end. A sits immediately right of C. B sits immediately left of D. E is not beside F. If C is third, who is fourth?', 'A', ['B', 'D', 'E'], 'A must sit immediately to the right of C, so A is fourth.'],
  ['General Intelligence', 'Series', 'medium', 'Complete the sequence: 2, 5, 14, 41, 122, ?', '365', ['343', '363', '367'], 'Each term is three times the previous term minus 1.'],
  ['General Intelligence', 'Clock', 'hard', 'What is the smaller angle between the clock hands at 4:20?', '10 degrees', ['0 degrees', '20 degrees', '30 degrees'], 'The minute hand is at 120 degrees; the hour hand is at 130 degrees.'],
  ['General Intelligence', 'Logical order', 'easy', 'Arrange the research steps: Analysis, Data collection, Question formulation, Conclusion.', 'Question formulation, Data collection, Analysis, Conclusion', ['Data collection, Conclusion, Analysis, Question formulation', 'Analysis, Data collection, Question formulation, Conclusion', 'Conclusion, Question formulation, Analysis, Data collection'], 'A question precedes data collection, analysis and conclusion.'],
  ['General Intelligence', 'Decision making', 'medium', 'A dataset contains personal identifiers that are unnecessary for your assigned analysis. What is the best first action?', 'Use a de-identified copy or request removal of the identifiers', ['Publish the identifiers with the findings', 'Share the raw file widely', 'Ignore the privacy risk'], 'Data minimisation reduces unnecessary privacy exposure.'],
  ['General Intelligence', 'Venn reasoning', 'medium', 'Some researchers are teachers and all teachers are readers. Which conclusion follows?', 'Some researchers are readers', ['All researchers are readers', 'No reader is a researcher', 'All readers are teachers'], 'The researchers who are teachers must also be readers.'],
  ['General Intelligence', 'Analogy', 'medium', 'Evidence is to Conclusion as Premise is to what?', 'Inference', ['Opinion', 'Question', 'Contradiction'], 'Evidence supports a conclusion; a premise supports an inference.'],
  ['General Intelligence', 'Pattern', 'hard', 'Find the missing number: 4, 10, 22, 46, 94, ?', '190', ['178', '186', '194'], 'Each term is twice the previous term plus 2.'],
  ['General Intelligence', 'Age problem', 'medium', 'The ratio of A\'s age to B\'s is 5:7. After 8 years it will be 7:9. What is A\'s present age?', '20 years', ['16 years', '24 years', '28 years'], 'Let ages be 5x and 7x; (5x+8)/(7x+8)=7/9 gives x=4.'],
  ['General Intelligence', 'Small and capital coding', 'medium', 'A code changes every lowercase letter to uppercase and shifts it one place backward. How is data coded?', 'CZSZ', ['EBUB', 'CZTZ', 'DZSZ'], 'd-c, a-z, t-s and a-z, all written in uppercase.'],

  ['General Awareness', 'Constitution', 'medium', 'Which constitutional body recommends how certain tax revenues should be shared between the Union and states?', 'Finance Commission', ['Election Commission', 'NITI Aayog', 'Inter-State Council'], 'The Finance Commission recommends tax devolution and grants.'],
  ['General Awareness', 'Modern history', 'medium', 'The Ilbert Bill controversy occurred during the tenure of which Viceroy?', 'Lord Ripon', ['Lord Lytton', 'Lord Curzon', 'Lord Minto'], 'The Ilbert Bill was introduced during Lord Ripon\'s tenure.'],
  ['General Awareness', 'Geography', 'medium', 'Which river system forms the Sundarbans delta?', 'Ganga-Brahmaputra-Meghna', ['Narmada-Tapi', 'Godavari-Krishna', 'Mahanadi-Brahmani'], 'The Sundarbans lies in the Ganga-Brahmaputra-Meghna delta.'],
  ['General Awareness', 'Biology', 'medium', 'Which organelle is the main site of aerobic respiration in a cell?', 'Mitochondrion', ['Golgi apparatus', 'Lysosome', 'Nucleolus'], 'Most aerobic ATP production occurs in mitochondria.'],
  ['General Awareness', 'Economics', 'hard', 'If nominal GDP grows by 8% while the general price level grows by 5%, real GDP growth is approximately what?', '3%', ['5%', '8%', '13%'], 'For small rates, real growth is approximately nominal growth minus inflation.'],
  ['General Awareness', 'Physics', 'medium', 'Why does a pencil appear bent when partly immersed in water?', 'Refraction of light', ['Reflection of sound', 'Diffusion', 'Magnetic induction'], 'Light changes direction when moving between water and air.'],
  ['General Awareness', 'Art and culture', 'medium', 'The Ajanta caves are especially known for paintings associated mainly with which tradition?', 'Buddhism', ['Jainism only', 'Sikhism', 'Zoroastrianism'], 'Most celebrated Ajanta paintings depict Buddhist themes.'],
  ['General Awareness', 'Indian polity', 'hard', 'Which writ directs a public authority to perform a legal duty?', 'Mandamus', ['Habeas corpus', 'Certiorari', 'Quo warranto'], 'Mandamus commands performance of a public legal duty.'],
  ['General Awareness', 'Chemistry', 'medium', 'Oxidation involves which change in terms of electrons?', 'Loss of electrons', ['Gain of electrons', 'No electron transfer', 'Gain of neutrons'], 'Oxidation is loss of electrons.'],
  ['General Awareness', 'Geography', 'medium', 'Western disturbances that bring winter rain to north-western India generally originate near which region?', 'The Mediterranean region', ['The South China Sea', 'The Bay of Bengal', 'The equatorial Pacific'], 'These extra-tropical systems generally originate around the Mediterranean region.'],
  ['General Awareness', 'Ancient history', 'medium', 'The inscriptions of Ashoka were deciphered in the nineteenth century chiefly by whom?', 'James Prinsep', ['Alexander Cunningham', 'William Jones', 'John Marshall'], 'James Prinsep deciphered Brahmi inscriptions, including Ashokan edicts.'],
  ['General Awareness', 'Environment', 'hard', 'Biomagnification refers to what?', 'Increasing concentration of a persistent pollutant at higher trophic levels', ['Rapid growth of all organisms', 'Breakdown of rocks by roots', 'Conversion of nitrogen gas into nitrates'], 'Persistent pollutants can become more concentrated up a food chain.'],
  ['General Awareness', 'Space science', 'medium', 'A geostationary satellite appears fixed because its orbital period matches what?', 'Earth\'s rotation period', ['Earth\'s revolution period', 'The Moon\'s rotation period', 'The Sun\'s rotation period'], 'It orbits once per sidereal day in the equatorial plane.'],
  ['General Awareness', 'Sports', 'easy', 'The term deuce is used in which sport?', 'Tennis', ['Hockey', 'Cricket', 'Kabaddi'], 'Deuce describes a tied score near the end of a tennis game.'],
  ['General Awareness', 'Constitution', 'medium', 'Which Schedule contains the recognised languages of the Indian Constitution?', 'Eighth Schedule', ['Fifth Schedule', 'Seventh Schedule', 'Tenth Schedule'], 'The Eighth Schedule lists recognised languages.'],
  ['General Awareness', 'Biology', 'hard', 'Which enzyme begins protein digestion in the human stomach?', 'Pepsin', ['Amylase', 'Lipase', 'Trypsin'], 'Pepsin begins protein digestion in the acidic stomach.'],
  ['General Awareness', 'Economics', 'medium', 'Open market operations by the Reserve Bank of India involve transactions in what?', 'Government securities', ['Agricultural land', 'Foreign passports', 'Corporate inventories'], 'RBI buys or sells government securities to influence liquidity.'],
  ['General Awareness', 'Literature', 'medium', 'Who wrote the novel Godan?', 'Munshi Premchand', ['Harivansh Rai Bachchan', 'Mahadevi Varma', 'Jaishankar Prasad'], 'Godan is a major Hindi novel by Premchand.'],
  ['General Awareness', 'Geography', 'medium', 'Which Indian pass connects Srinagar with Leh?', 'Zoji La', ['Nathu La', 'Palghat Gap', 'Bhor Ghat'], 'Zoji La provides a route between the Kashmir Valley and Ladakh.'],
  ['General Awareness', 'Physics', 'medium', 'Which electromagnetic waves have the shortest wavelength?', 'Gamma rays', ['Radio waves', 'Microwaves', 'Visible light'], 'Gamma rays occupy the shortest-wavelength end of the spectrum.'],
  ['General Awareness', 'Freedom movement', 'medium', 'The Poona Pact of 1932 was an agreement involving Mahatma Gandhi and whom?', 'B. R. Ambedkar', ['Subhas Chandra Bose', 'Jawaharlal Nehru', 'Bal Gangadhar Tilak'], 'Gandhi and Ambedkar negotiated the Poona Pact on representation.'],
  ['General Awareness', 'Chemistry', 'medium', 'Which catalyst is used in the Haber process for ammonia production?', 'Iron', ['Nickel', 'Platinum', 'Copper'], 'Finely divided iron is the principal catalyst in the Haber process.'],
  ['General Awareness', 'International organisations', 'easy', 'Where is the headquarters of UNESCO?', 'Paris', ['Geneva', 'Vienna', 'Rome'], 'UNESCO is headquartered in Paris.'],
  ['General Awareness', 'Parliament', 'hard', 'A joint sitting of Parliament is presided over by whom?', 'Speaker of the Lok Sabha', ['Chairman of the Rajya Sabha', 'President of India', 'Prime Minister'], 'The Lok Sabha Speaker presides over a joint sitting.'],
  ['General Awareness', 'Agriculture', 'medium', 'Which bacterium is commonly associated with nitrogen fixation in legume root nodules?', 'Rhizobium', ['Lactobacillus', 'Vibrio', 'Salmonella'], 'Rhizobium forms nitrogen-fixing symbioses with legumes.'],

  ['Quantitative Aptitude', 'Percentage', 'medium', 'A salary is raised by 12% and then reduced by 10%. What is the net percentage change?', '0.8% increase', ['2% increase', '1.2% decrease', '2.8% increase'], 'The factor is 1.12 x 0.90 = 1.008, a 0.8% increase.'],
  ['Quantitative Aptitude', 'Ratio', 'medium', 'If a:b = 4:7 and b:c = 14:15, find a:b:c.', '8:14:15', ['4:14:15', '8:7:15', '8:14:30'], 'Scale the first ratio by 2 so both values of b equal 14.'],
  ['Quantitative Aptitude', 'Average', 'medium', 'The average of 12 observations is 35. One value 53 was recorded as 35. What is the corrected average?', '36.5', ['35.5', '36', '37'], 'Correct total rises by 18; average rises by 18/12 = 1.5.'],
  ['Quantitative Aptitude', 'Profit and loss', 'medium', 'A retailer marks an item 25% above cost and gives a 10% discount. What is the profit percentage?', '12.5%', ['10%', '15%', '17.5%'], 'Selling factor is 1.25 x 0.9 = 1.125.'],
  ['Quantitative Aptitude', 'Compound interest', 'medium', 'What is the compound interest on Rs 8,000 at 5% per annum for 2 years?', 'Rs 820', ['Rs 800', 'Rs 810', 'Rs 840'], 'Amount is 8000 x 1.05 squared = 8820, so interest is Rs 820.'],
  ['Quantitative Aptitude', 'Time and work', 'hard', 'A and B together finish work in 8 days. A alone takes 12 days. How long does B alone take?', '24 days', ['18 days', '20 days', '30 days'], 'B\'s rate is 1/8 - 1/12 = 1/24.'],
  ['Quantitative Aptitude', 'Boats and streams', 'medium', 'A boat travels at 15 km/h in still water and the stream is 3 km/h. How long does it take to travel 54 km downstream?', '3 hours', ['3.5 hours', '4 hours', '4.5 hours'], 'Downstream speed is 18 km/h, so time is 54/18 = 3 hours.'],
  ['Quantitative Aptitude', 'Algebra', 'hard', 'If the roots of x squared - 9x + 20 = 0 are alpha and beta, find alpha squared + beta squared.', '41', ['31', '39', '49'], 'Alpha+beta=9 and alpha beta=20, so squares sum = 81 - 40 = 41.'],
  ['Quantitative Aptitude', 'Geometry', 'medium', 'A chord subtends 60 degrees at the centre of a circle of radius 10 cm. What is the chord length?', '10 cm', ['5 cm', '10sqrt(2) cm', '20 cm'], 'Chord = 2r sin(30 degrees) = 10 cm.'],
  ['Quantitative Aptitude', 'Mensuration', 'medium', 'Find the volume of a cone with radius 3 cm and height 7 cm using pi = 22/7.', '66 cubic cm', ['44 cubic cm', '88 cubic cm', '198 cubic cm'], 'Volume = 1/3 x 22/7 x 9 x 7 = 66.'],
  ['Quantitative Aptitude', 'Trigonometry', 'medium', 'If tan theta = 3/4 for an acute angle, what is sin theta?', '3/5', ['4/5', '3/4', '5/4'], 'A 3-4-5 triangle gives sin theta = opposite/hypotenuse = 3/5.'],
  ['Quantitative Aptitude', 'Partnership', 'medium', 'A invests Rs 20,000 for 9 months and B invests Rs 15,000 for 12 months. What is their profit ratio?', '1:1', ['4:3', '3:4', '2:1'], 'Both capital-time products equal Rs 180,000-months.'],
  ['Quantitative Aptitude', 'Mixture', 'hard', 'In what ratio should rice at Rs 40/kg be mixed with rice at Rs 55/kg to obtain a mixture worth Rs 46/kg?', '3:2', ['2:3', '4:5', '5:4'], 'By alligation, cheaper:dearer = (55-46):(46-40) = 9:6 = 3:2.'],
  ['Quantitative Aptitude', 'Linear equations', 'medium', 'If 2x + 3y = 19 and x - y = 2, find y.', '3', ['2', '4', '5'], 'x = y + 2; substitution gives 5y + 4 = 19, so y = 3.'],
  ['Quantitative Aptitude', 'Number theory', 'medium', 'What is the least number greater than 9 that leaves remainder 3 when divided by 5, 7 and 9?', '318', ['312', '315', '633'], 'LCM(5,7,9)=315; adding remainder 3 gives 318, the first such value greater than 9.'],
  ['Quantitative Aptitude', 'Discount', 'medium', 'A marked price of Rs 2,400 is reduced to Rs 1,836 after two discounts. If the first is 10%, what is the second?', '15%', ['12%', '18%', '20%'], 'After 10%, price is 2160; 1836 is 85% of 2160.'],
  ['Quantitative Aptitude', 'Data interpretation', 'medium', 'A category rises from 120 units to 168 units. By what percentage did it rise?', '40%', ['35%', '38%', '48%'], 'Increase is 48; 48/120 x 100 = 40%.'],
  ['Quantitative Aptitude', 'Surds', 'medium', 'Rationalise 5/sqrt(5).', 'sqrt(5)', ['1', '5sqrt(5)', '25'], 'Multiply numerator and denominator by sqrt(5), giving sqrt(5).'],
  ['Quantitative Aptitude', 'Relative speed', 'medium', 'A 150 m train crosses a 250 m platform in 20 seconds. Find its speed.', '72 km/h', ['60 km/h', '65 km/h', '75 km/h'], 'It covers 400 m in 20 s = 20 m/s = 72 km/h.'],
  ['Quantitative Aptitude', 'Sphere', 'hard', 'Find the surface area of a sphere of radius 7 cm using pi = 22/7.', '616 sq cm', ['308 sq cm', '462 sq cm', '1,232 sq cm'], 'Surface area = 4 x 22/7 x 49 = 616 sq cm.'],
  ['Quantitative Aptitude', 'Statistics', 'medium', 'The mean of 5, 7, x, 12 and 16 is 10. Find x.', '10', ['8', '9', '11'], 'The required total is 50; known values total 40, so x = 10.'],
  ['Quantitative Aptitude', 'Pipes', 'hard', 'A pipe fills a tank in 10 hours and a leak empties it in 15 hours. How long will the tank take to fill?', '30 hours', ['20 hours', '25 hours', '35 hours'], 'Net rate is 1/10 - 1/15 = 1/30.'],
  ['Quantitative Aptitude', 'Coordinate geometry', 'medium', 'Find the midpoint of the line segment joining (-2, 5) and (6, -1).', '(2, 2)', ['(4, 4)', '(2, 3)', '(-4, 6)'], 'Average corresponding coordinates: ((-2+6)/2, (5-1)/2) = (2,2).'],
  ['Quantitative Aptitude', 'Probability', 'medium', 'A fair die is rolled once. What is the probability of getting a prime number?', '1/2', ['1/3', '2/3', '5/6'], 'Prime outcomes are 2, 3 and 5: three of six outcomes.'],
  ['Quantitative Aptitude', 'Remainders', 'hard', 'What is the remainder when 2 to the power 20 is divided by 7?', '4', ['1', '2', '6'], 'Powers of 2 modulo 7 repeat 2,4,1; exponent 20 corresponds to remainder 4.'],

  ['English Language', 'Error spotting', 'medium', 'Which part contains the error: The information / provided by the offices / were incomplete / and inconsistent?', 'were incomplete', ['The information', 'provided by the offices', 'and inconsistent'], 'Information is singular and requires was incomplete.'],
  ['English Language', 'Synonym', 'medium', "Choose the closest synonym of 'pragmatic'.", 'Practical', ['Idealistic', 'Careless', 'Decorative'], 'Pragmatic means practical and focused on workable results.'],
  ['English Language', 'Antonym', 'medium', "Select the antonym of 'concise'.", 'Verbose', ['Brief', 'Compact', 'Succinct'], 'Verbose means using more words than needed.'],
  ['English Language', 'Spelling', 'medium', 'Which spelling is correct?', 'Accommodate', ['Acommodate', 'Accomodate', 'Acomoddate'], 'Accommodate has double c and double m.'],
  ['English Language', 'Idiom', 'medium', "What does 'move the goalposts' mean?", 'Change the rules or expectations unfairly', ['Complete a sports event', 'Set a clear target', 'Avoid all competition'], 'The idiom refers to changing conditions after work has begun.'],
  ['English Language', 'One-word substitution', 'medium', 'What is a person who deliberately sets fire to property called?', 'Arsonist', ['Archivist', 'Atheist', 'Artisan'], 'An arsonist deliberately commits arson.'],
  ['English Language', 'Voice', 'medium', "Choose the passive form of 'The panel is reviewing the proposal.'", 'The proposal is being reviewed by the panel.', ['The proposal has reviewed the panel.', 'The proposal was being reviewed by the panel.', 'The panel is being reviewed by the proposal.'], 'Present continuous passive uses is being reviewed.'],
  ['English Language', 'Narration', 'medium', "Report the question: The officer asked Ravi, 'Why did you leave early?'", 'The officer asked Ravi why he had left early.', ['The officer asked Ravi why did he leave early.', 'The officer asked Ravi why he leaves early.', 'The officer said Ravi why had he left early.'], 'Reported questions use statement order, a clear pronoun reference and backshift the earlier action.'],
  ['English Language', 'Fill in the blank', 'medium', 'The new evidence is consistent ___ the earlier findings.', 'with', ['to', 'for', 'at'], 'Consistent with is the standard collocation.'],
  ['English Language', 'Sentence improvement', 'medium', 'Improve: The policy aims to reduce waste and improving efficiency.', 'The policy aims to reduce waste and improve efficiency.', ['The policy aims reducing waste and improve efficiency.', 'The policy aim to reduce waste and improving efficiency.', 'No improvement'], 'Parallel infinitives require reduce and improve.'],
  ['English Language', 'Cloze', 'medium', 'Complete logically: The audit identified the error before it could ___ the final report.', 'affect', ['effect', 'infected', 'affection'], 'Affect is the verb meaning influence.'],
  ['English Language', 'Vocabulary in context', 'hard', "In 'The committee gave a qualified approval', what does qualified mean?", 'Limited by conditions', ['Given by an expert only', 'Entirely enthusiastic', 'Legally invalid'], 'A qualified approval is conditional or limited.'],
  ['English Language', 'Para-jumble', 'hard', 'Arrange logically: P: the data were verified; Q: the report was published; R: inconsistencies were corrected; S: after collection.', 'S-P-R-Q', ['P-S-Q-R', 'S-R-P-Q', 'Q-P-R-S'], 'After collection, data are verified, inconsistencies corrected, and the report published.'],
  ['English Language', 'Preposition', 'medium', 'The decision was based ___ evidence submitted during the inquiry.', 'on', ['at', 'from', 'into'], 'The correct collocation is based on.'],
  ['English Language', 'Tense', 'medium', 'By the time the inspection begins, the team ___ all records.', 'will have organised', ['organised', 'has organising', 'will organise yesterday'], 'Future perfect marks completion before a future event.'],
  ['English Language', 'Conditional', 'hard', 'Had the warning been issued earlier, the delay ___ avoided.', 'could have been', ['can be', 'will have', 'was being'], 'An unreal past condition takes could have been plus past participle.'],
  ['English Language', 'Comprehension', 'medium', 'A memo says remote work improved output but made informal mentoring harder. Which statement reflects the memo?', 'Remote work had both a benefit and a drawback', ['Remote work reduced all output', 'Mentoring became unnecessary', 'The memo recommends closing offices'], 'The memo identifies one positive and one negative effect.'],
  ['English Language', 'Vocabulary', 'medium', "What does 'mitigate' mean?", 'Make less severe', ['Make permanent', 'Measure precisely', 'Reject completely'], 'To mitigate is to reduce severity or harm.'],
  ['English Language', 'Subject-verb agreement', 'hard', 'Choose the correct sentence.', 'A series of consultations has been scheduled.', ['A series of consultations have been scheduled.', 'A series of consultation have been scheduled.', 'A series consultations has scheduled.'], 'The singular head noun series takes has.'],
  ['English Language', 'Phrasal verb', 'medium', "What does 'phase out an obsolete system' mean?", 'Withdraw it gradually', ['Repair it immediately', 'Expand it rapidly', 'Copy it exactly'], 'Phase out means discontinue gradually.'],
  ['English Language', 'Antonym', 'medium', "Choose the antonym of 'arbitrary'.", 'Reasoned', ['Random', 'Capricious', 'Unrestrained'], 'A reasoned decision follows logic, unlike an arbitrary one.'],
  ['English Language', 'Grammar', 'medium', 'Choose the correct form: Not only the files but also the register ___ missing.', 'was', ['were', 'have', 'are being'], 'With not only...but also, the verb agrees with the nearer singular subject register.'],
  ['English Language', 'Punctuation', 'medium', 'Which option correctly punctuates the interrupting word "however"?', 'The findings, however, require further verification.', ['The findings however require, further verification.', 'The findings however, require further verification.', 'The findings; however require further verification.'], 'The interrupting adverb however is enclosed by commas.'],
  ['English Language', 'Sentence transformation', 'hard', 'Choose the equivalent sentence: Despite the shortage of time, the team completed the review.', 'Although time was short, the team completed the review.', ['Because time was short, the team abandoned the review.', 'The team completed the review before time became short.', 'Without a shortage, the review was incomplete.'], 'Despite introduces a contrast preserved by although.'],
  ['English Language', 'Inference', 'hard', 'A study found a correlation between training hours and accuracy but did not control for prior experience. What is the safest conclusion?', 'Training and accuracy were associated, but causation is not established', ['Training certainly caused all improvement', 'Prior experience had no effect', 'Accuracy caused additional training'], 'Correlation without controlling alternatives does not prove causation.'],
];

function placeAnswer(answer: string, distractors: [string, string, string], index: number) {
  const options = [...distractors];
  options.splice(index, 0, answer);
  return options;
}

export const SSC_SELECTION_POST_GRADUATION_CBE_1: Question[] = rows.map(
  ([section, topic, difficulty, question, answer, distractors, explanation], index) => ({
    id: `ssc-sp-grad-${String(index + 1).padStart(3, '0')}`,
    section,
    topic,
    difficulty,
    question,
    options: placeAnswer(answer, distractors, index % 4),
    correctIndex: index % 4,
    explanation,
    source,
  }),
);
