import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SSC CGL 2026 official notice, paragraph 13.10.4 (English Comprehension syllabus)',
  url: 'https://ssc.gov.in/api/attachment/uploads/masterData/NoticeBoards/Notice_of_adv_cgl_2026.pdf',
  checkedOn: '3 August 2026',
};

const passage =
  'A public library is useful only when people can reach and use its resources easily. Extending opening hours may help working adults, while clear signs and a simple catalogue help every visitor. Technology can improve access, but trained staff remain essential because they guide readers and maintain reliable collections.';

export const SSC_CGL_TIER1_ENGLISH_3: Question[] = [
  {
    id: 'ssc-cgl-t1-en3-001',
    section: 'English Comprehension',
    topic: 'Synonym',
    difficulty: 'easy',
    question: 'Choose the word that is closest in meaning to "meticulous".',
    options: ['Careful', 'Hasty', 'Ordinary', 'Noisy'],
    correctIndex: 0,
    explanation: '"Meticulous" means showing great attention to detail, so "careful" is the closest option.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en3-002',
    section: 'English Comprehension',
    topic: 'Antonym',
    difficulty: 'easy',
    question: 'Choose the word that is opposite in meaning to "scarce".',
    options: ['Rare', 'Abundant', 'Limited', 'Costly'],
    correctIndex: 1,
    explanation: '"Scarce" means insufficient or hard to find, while "abundant" means plentiful.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en3-003',
    section: 'English Comprehension',
    topic: 'Spelling',
    difficulty: 'easy',
    question: 'Which option is correctly spelled?',
    options: ['Acommodate', 'Accomodate', 'Accommodate', 'Acommodete'],
    correctIndex: 2,
    explanation: '"Accommodate" is spelled with two c\'s and two m\'s.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en3-004',
    section: 'English Comprehension',
    topic: 'One-word substitution',
    difficulty: 'medium',
    question: 'Choose the one-word substitute for "a person who writes or compiles a dictionary".',
    options: ['Biographer', 'Calligrapher', 'Cartographer', 'Lexicographer'],
    correctIndex: 3,
    explanation: 'A lexicographer writes, edits or compiles dictionaries.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en3-005',
    section: 'English Comprehension',
    topic: 'Idioms and phrases',
    difficulty: 'easy',
    question: 'What does the idiom "hit the nail on the head" mean?',
    options: ['To describe the exact cause of a problem', 'To work carelessly', 'To hurt someone accidentally', 'To avoid a difficult subject'],
    correctIndex: 0,
    explanation: 'The idiom means to identify or express something exactly correctly.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en3-006',
    section: 'English Comprehension',
    topic: 'Idioms and phrases',
    difficulty: 'medium',
    question: 'What does the phrase "at sixes and sevens" mean?',
    options: ['In complete agreement', 'In confusion or disorder', 'At the correct time', 'In equal groups'],
    correctIndex: 1,
    explanation: '"At sixes and sevens" describes a state of confusion or disorganisation.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en3-007',
    section: 'English Comprehension',
    topic: 'Subject-verb agreement',
    difficulty: 'medium',
    question: 'Which sentence correctly uses "each of"?',
    options: ['Each of the players have a locker.', 'Each of the player has a locker.', 'Each of the players has a locker.', 'Each of the players are having a locker.'],
    correctIndex: 2,
    explanation: '"Each" is singular and takes "has"; the noun after "of the" is plural.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en3-008',
    section: 'English Comprehension',
    topic: 'Error correction',
    difficulty: 'easy',
    question: 'Choose the correct replacement for "were" in: "Neither of the answers were correct."',
    options: ['are', 'have been', 'is being', 'was'],
    correctIndex: 3,
    explanation: '"Neither" is singular, so the singular past-tense verb "was" is required.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en3-009',
    section: 'English Comprehension',
    topic: 'Tense',
    difficulty: 'medium',
    question: 'Fill in the blank: "The train ___ before we reached the station."',
    options: ['had left', 'has left', 'leaves', 'was leaving'],
    correctIndex: 0,
    explanation: 'The train departed before another action in the past, so the past perfect "had left" is appropriate.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en3-010',
    section: 'English Comprehension',
    topic: 'Preposition',
    difficulty: 'easy',
    question: 'Fill in the blank: "Meera is capable ___ solving the puzzle."',
    options: ['for', 'of', 'at', 'with'],
    correctIndex: 1,
    explanation: 'The adjective "capable" is followed by the preposition "of".',
    source,
  },
  {
    id: 'ssc-cgl-t1-en3-011',
    section: 'English Comprehension',
    topic: 'Articles',
    difficulty: 'easy',
    question: 'Fill in the blank: "She gave me ___ honest answer."',
    options: ['a', 'the', 'an', 'no article'],
    correctIndex: 2,
    explanation: '"Honest" begins with a vowel sound because the h is silent, so it takes "an".',
    source,
  },
  {
    id: 'ssc-cgl-t1-en3-012',
    section: 'English Comprehension',
    topic: 'Conjunction',
    difficulty: 'easy',
    question: 'Fill in the blank: "He continued working ___ he was tired."',
    options: ['because', 'unless', 'so', 'although'],
    correctIndex: 3,
    explanation: '"Although" correctly introduces the contrast between being tired and continuing to work.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en3-013',
    section: 'English Comprehension',
    topic: 'Voice',
    difficulty: 'easy',
    question: 'Choose the correct passive form of: "They will announce the results tomorrow."',
    options: ['The results will be announced tomorrow.', 'The results are announced tomorrow.', 'Tomorrow announced the results.', 'The results will announce tomorrow.'],
    correctIndex: 0,
    explanation: 'The future active form "will announce" becomes "will be announced" in the passive voice.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en3-014',
    section: 'English Comprehension',
    topic: 'Narration',
    difficulty: 'medium',
    question: 'Choose the correct indirect form of: She said, "I am reading now."',
    options: ['She said that I am reading now.', 'She said that she was reading then.', 'She says that she was reading now.', 'She told that she had read then.'],
    correctIndex: 1,
    explanation: 'The pronoun changes to "she", present continuous shifts to past continuous, and "now" changes to "then".',
    source,
  },
  {
    id: 'ssc-cgl-t1-en3-015',
    section: 'English Comprehension',
    topic: 'Conditional',
    difficulty: 'medium',
    question: 'Complete the sentence: "If I had known about the delay, I ___ earlier."',
    options: ['will leave', 'would leave', 'would have left', 'had left'],
    correctIndex: 2,
    explanation: 'A third conditional uses "if + past perfect" with "would have + past participle".',
    source,
  },
  {
    id: 'ssc-cgl-t1-en3-016',
    section: 'English Comprehension',
    topic: 'Sentence improvement',
    difficulty: 'easy',
    question: 'Choose the best replacement for "discuss about the issue" in: "The committee will discuss about the issue tomorrow."',
    options: ['discuss on the issue', 'discuss over the issue', 'discuss regarding the issue', 'discuss the issue'],
    correctIndex: 3,
    explanation: '"Discuss" is transitive and takes a direct object, so no preposition is needed before "the issue".',
    source,
  },
  {
    id: 'ssc-cgl-t1-en3-017',
    section: 'English Comprehension',
    topic: 'Sentence arrangement',
    difficulty: 'medium',
    question: 'Arrange the events logically: P. They opened the map. Q. They selected the shortest route. R. They began the journey. S. They reached the village.',
    options: ['P, Q, R, S', 'Q, P, S, R', 'R, P, Q, S', 'P, R, S, Q'],
    correctIndex: 0,
    explanation: 'They first open the map, choose a route, begin travelling and finally reach the village.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en3-018',
    section: 'English Comprehension',
    topic: 'Gerund',
    difficulty: 'medium',
    question: 'Fill in the blank: "I look forward to ___ you next week."',
    options: ['meet', 'meeting', 'met', 'have met'],
    correctIndex: 1,
    explanation: 'In "look forward to", "to" is a preposition and is followed by the gerund "meeting".',
    source,
  },
  {
    id: 'ssc-cgl-t1-en3-019',
    section: 'English Comprehension',
    topic: 'Reading comprehension',
    difficulty: 'medium',
    question: `Read the passage and answer the question. "${passage}" What is the central idea of the passage?`,
    options: ['Libraries should replace all printed books with technology.', 'Only working adults benefit from public libraries.', 'Libraries are most useful when resources and guidance are accessible.', 'Trained staff make catalogues unnecessary.'],
    correctIndex: 2,
    explanation: 'The passage focuses on practical access to resources and the continuing value of trained staff.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en3-020',
    section: 'English Comprehension',
    topic: 'Reading comprehension',
    difficulty: 'medium',
    question: `Read the passage and answer the question. "${passage}" Which statement is supported by the passage?`,
    options: ['Technology makes library staff unnecessary.', 'Longer hours help only schoolchildren.', 'A catalogue is useful only when it is complex.', 'Technology and trained staff can both improve library access.'],
    correctIndex: 3,
    explanation: 'The passage says technology can improve access while trained staff remain essential.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en3-021',
    section: 'English Comprehension',
    topic: 'Vocabulary in context',
    difficulty: 'easy',
    question: `In the passage, what does "access" most nearly mean? "${passage}"`,
    options: ['The ability to reach and use something', 'A fee charged for borrowing books', 'The process of writing a catalogue', 'A private collection of books'],
    correctIndex: 0,
    explanation: 'The first sentence explains access as being able to reach and use library resources easily.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en3-022',
    section: 'English Comprehension',
    topic: 'Punctuation',
    difficulty: 'medium',
    question: 'Which sentence is punctuated correctly?',
    options: ['After the meeting the chairperson said "We will vote tomorrow."', 'After the meeting, the chairperson said, "We will vote tomorrow."', 'After the meeting, the chairperson said "We will vote tomorrow".', 'After the meeting the chairperson, said, "We will vote tomorrow".'],
    correctIndex: 1,
    explanation: 'The introductory phrase and reporting clause take commas, and the full stop belongs inside the quotation marks.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en3-023',
    section: 'English Comprehension',
    topic: 'Question tag',
    difficulty: 'easy',
    question: 'Choose the correct question tag: "You are coming with us, ___?"',
    options: ['are you', 'do you', 'aren\'t you', 'won\'t you'],
    correctIndex: 2,
    explanation: 'A positive statement with "are" takes the negative tag "aren\'t you?".',
    source,
  },
  {
    id: 'ssc-cgl-t1-en3-024',
    section: 'English Comprehension',
    topic: 'Error correction',
    difficulty: 'easy',
    question: 'Choose the correct replacement for "are" in: "The news are encouraging."',
    options: ['were', 'have been', 'be', 'is'],
    correctIndex: 3,
    explanation: '"News" is treated as a singular uncountable noun and therefore takes "is".',
    source,
  },
  {
    id: 'ssc-cgl-t1-en3-025',
    section: 'English Comprehension',
    topic: 'Synonym',
    difficulty: 'easy',
    question: 'Choose the word that is closest in meaning to "concise".',
    options: ['Brief', 'Unclear', 'Lengthy', 'Decorative'],
    correctIndex: 0,
    explanation: '"Concise" means giving information clearly in few words, so "brief" is the closest option.',
    source,
  },
];
