import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SSC CGL 2026 official notice, paragraph 13.10.4 (English Comprehension syllabus)',
  url: 'https://ssc.gov.in/api/attachment/uploads/masterData/NoticeBoards/Notice_of_adv_cgl_2026.pdf',
  checkedOn: '30 July 2026',
};

export const SSC_CGL_TIER1_ENGLISH_1: Question[] = [
  {
    id: 'ssc-cgl-t1-en-001',
    section: 'English Comprehension',
    topic: 'Synonym',
    difficulty: 'easy',
    question: 'Choose the word that is closest in meaning to “candid”.',
    options: ['Frank', 'Careless', 'Secretive', 'Doubtful'],
    correctIndex: 0,
    explanation: '“Candid” means truthful and straightforward, so “frank” is the closest synonym.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en-002',
    section: 'English Comprehension',
    topic: 'Synonym',
    difficulty: 'medium',
    question: 'Choose the word that is closest in meaning to “mitigate”.',
    options: ['Increase', 'Postpone', 'Lessen', 'Measure'],
    correctIndex: 2,
    explanation: '“Mitigate” means to make something less severe, serious or painful.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en-003',
    section: 'English Comprehension',
    topic: 'Antonym',
    difficulty: 'easy',
    question: 'Choose the word that is opposite in meaning to “scarce”.',
    options: ['Limited', 'Costly', 'Useful', 'Abundant'],
    correctIndex: 3,
    explanation: '“Scarce” means insufficient or hard to find; “abundant” means available in large quantities.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en-004',
    section: 'English Comprehension',
    topic: 'Antonym',
    difficulty: 'easy',
    question: 'Choose the word that is opposite in meaning to “rigid”.',
    options: ['Flexible', 'Solid', 'Strict', 'Stable'],
    correctIndex: 0,
    explanation: '“Rigid” means stiff or inflexible, so “flexible” is its opposite.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en-005',
    section: 'English Comprehension',
    topic: 'Spelling',
    difficulty: 'easy',
    question: 'Choose the correct spelling of the word meaning “to provide enough space for”.',
    options: ['Acommodate', 'Accomodate', 'Accommodate', 'Acommoddate'],
    correctIndex: 2,
    explanation: '“Accommodate” is spelled with two c’s and two m’s.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en-006',
    section: 'English Comprehension',
    topic: 'Spelling',
    difficulty: 'medium',
    question: 'Choose the correct spelling of the word meaning “a person’s moral sense of right and wrong”.',
    options: ['Conscience', 'Concience', 'Consciense', 'Consceince'],
    correctIndex: 0,
    explanation: '“Conscience” is the correct spelling of the word meaning a person’s moral sense of right and wrong.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en-007',
    section: 'English Comprehension',
    topic: 'One-word substitution',
    difficulty: 'easy',
    question: 'Choose the one-word substitute for “a person who can speak several languages”.',
    options: ['Linguist', 'Orator', 'Polyglot', 'Translator'],
    correctIndex: 2,
    explanation: 'A polyglot is a person who knows and can use several languages.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en-008',
    section: 'English Comprehension',
    topic: 'One-word substitution',
    difficulty: 'medium',
    question: 'Choose the one-word substitute for “a speech delivered without previous preparation”.',
    options: ['Dialogue', 'Extempore', 'Monologue', 'Prologue'],
    correctIndex: 1,
    explanation: 'An extempore speech is delivered without prior preparation.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en-009',
    section: 'English Comprehension',
    topic: 'Idioms and phrases',
    difficulty: 'easy',
    question: 'What does the idiom “hit the nail on the head” mean?',
    options: ['To damage something', 'To work very slowly', 'To avoid a difficult subject', 'To describe exactly what is causing a situation'],
    correctIndex: 3,
    explanation: 'The idiom means to identify or describe a problem or situation exactly.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en-010',
    section: 'English Comprehension',
    topic: 'Idioms and phrases',
    difficulty: 'easy',
    question: 'What does the phrase “once in a blue moon” mean?',
    options: ['At night', 'Without warning', 'Twice a month', 'Very rarely'],
    correctIndex: 3,
    explanation: '“Once in a blue moon” refers to something that happens very rarely.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en-011',
    section: 'English Comprehension',
    topic: 'Subject-verb agreement',
    difficulty: 'easy',
    question: 'Choose the grammatically correct sentence.',
    options: [
      'Each of the players have submitted the form.',
      'Each of the player have submitted the form.',
      'Each of the players were submitting the form.',
      'Each of the players has submitted the form.',
    ],
    correctIndex: 3,
    explanation: 'The subject “each” is singular and therefore takes the singular verb “has”.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en-012',
    section: 'English Comprehension',
    topic: 'Subject-verb agreement',
    difficulty: 'medium',
    question: 'Choose the correct replacement for “was willing” in the sentence: “Neither the manager nor the employees was willing to stay late.”',
    options: ['were willing', 'is willing', 'has been willing', 'No replacement required'],
    correctIndex: 0,
    explanation: 'With “neither…nor”, the verb agrees with the nearer subject. “Employees” is plural, so “were willing” is correct.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en-013',
    section: 'English Comprehension',
    topic: 'Tense',
    difficulty: 'medium',
    question: 'Fill in the blank: “By next month, she ___ the training programme.”',
    options: ['completes', 'completed', 'will have completed', 'has completed'],
    correctIndex: 2,
    explanation: 'The future perfect tense describes an action that will be complete before a stated future time.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en-014',
    section: 'English Comprehension',
    topic: 'Preposition',
    difficulty: 'easy',
    question: 'Fill in the blank: “The analyst is proficient ___ spreadsheet modelling.”',
    options: ['at', 'on', 'with', 'in'],
    correctIndex: 3,
    explanation: 'The adjective “proficient” is normally followed by “in” when referring to a subject or activity.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en-015',
    section: 'English Comprehension',
    topic: 'Articles',
    difficulty: 'easy',
    question: 'Fill in the blank: “She gave ___ honest account of the incident.”',
    options: ['a', 'an', 'the', 'no article'],
    correctIndex: 1,
    explanation: '“Honest” begins with a vowel sound because the h is silent, so the correct article is “an”.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en-016',
    section: 'English Comprehension',
    topic: 'Conditionals',
    difficulty: 'medium',
    question: 'Choose the correct completion: “If I had known about the change, I ___ you.”',
    options: ['will inform', 'would inform', 'would have informed', 'had informed'],
    correctIndex: 2,
    explanation: 'A past unreal condition uses “if + past perfect” and “would have + past participle”.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en-017',
    section: 'English Comprehension',
    topic: 'Sentence improvement',
    difficulty: 'easy',
    question: 'Choose the correct replacement for “senior than me” in the sentence: “Arun is senior than me.”',
    options: ['senior to me', 'more senior than me', 'senior from me', 'No replacement required'],
    correctIndex: 0,
    explanation: 'The adjective “senior” takes the preposition “to”, not “than”.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en-018',
    section: 'English Comprehension',
    topic: 'Active and passive voice',
    difficulty: 'easy',
    question: 'Choose the correct passive form of “The committee approved the proposal.”',
    options: [
      'The proposal had approved the committee.',
      'The proposal was approved by the committee.',
      'The proposal is approved by the committee.',
      'The committee was approved by the proposal.',
    ],
    correctIndex: 1,
    explanation: 'The simple past active verb “approved” becomes “was approved” in the passive voice.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en-019',
    section: 'English Comprehension',
    topic: 'Direct and indirect speech',
    difficulty: 'medium',
    question: 'Choose the correct indirect form of: Riya said, “I am tired.”',
    options: [
      'Riya said that I am tired.',
      'Riya said that she was tired.',
      'Riya says that she is tired.',
      'Riya told that she had tired.',
    ],
    correctIndex: 1,
    explanation: 'The pronoun changes from “I” to “she”, and the present tense normally shifts to the past after “said”.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en-020',
    section: 'English Comprehension',
    topic: 'Sentence ordering',
    difficulty: 'medium',
    question: 'Arrange the sentences in a logical order: P. Meera opened the instruction booklet. Q. She read each rule carefully. R. She signed the declaration. S. She began the test.',
    options: ['P, Q, R, S', 'Q, P, S, R', 'P, R, Q, S', 'R, P, Q, S'],
    correctIndex: 0,
    explanation: 'Meera opens the booklet, reads the rules, signs the declaration and then begins the test.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en-021',
    section: 'English Comprehension',
    topic: 'Reading comprehension',
    difficulty: 'medium',
    question: 'Read the passage and answer the question. “Cities often respond to traffic congestion by building wider roads. Yet additional road capacity can encourage more people to drive, and congestion soon returns. Reliable public transport and safe walking routes can reduce dependence on private cars.” What is the main idea of the passage?',
    options: [
      'All roads should be closed to cars.',
      'Wider roads are always the best solution to congestion.',
      'Road expansion alone may not solve congestion, so alternatives are needed.',
      'Walking routes cause traffic congestion.',
    ],
    correctIndex: 2,
    explanation: 'The passage argues that wider roads may attract more traffic and that transport alternatives can reduce car dependence.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en-022',
    section: 'English Comprehension',
    topic: 'Reading comprehension',
    difficulty: 'easy',
    question: 'Read the passage and answer the question. “Cities often respond to traffic congestion by building wider roads. Yet additional road capacity can encourage more people to drive, and congestion soon returns. Reliable public transport and safe walking routes can reduce dependence on private cars.” According to the passage, why can congestion return after roads are widened?',
    options: [
      'Public transport becomes free.',
      'More people may choose to drive.',
      'Walking routes become unsafe.',
      'Roads become shorter.',
    ],
    correctIndex: 1,
    explanation: 'The passage directly states that added road capacity can encourage more people to drive.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en-023',
    section: 'English Comprehension',
    topic: 'Reading comprehension',
    difficulty: 'medium',
    question: 'Read the passage and answer the question. “Cities often respond to traffic congestion by building wider roads. Yet additional road capacity can encourage more people to drive, and congestion soon returns. Reliable public transport and safe walking routes can reduce dependence on private cars.” Which statement is supported by the passage?',
    options: [
      'Transport planning should offer practical alternatives to private cars.',
      'Every commuter prefers to walk.',
      'Public transport always removes congestion completely.',
      'Wider roads reduce the number of drivers permanently.',
    ],
    correctIndex: 0,
    explanation: 'The passage supports reliable public transport and safe walking routes as alternatives that can reduce dependence on private cars.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en-024',
    section: 'English Comprehension',
    topic: 'Cloze completion',
    difficulty: 'easy',
    question: 'Fill in the blank: “Despite the heavy rain, the match continued ___ interruption.”',
    options: ['at', 'by', 'for', 'without'],
    correctIndex: 3,
    explanation: 'The natural expression is “continued without interruption”.',
    source,
  },
  {
    id: 'ssc-cgl-t1-en-025',
    section: 'English Comprehension',
    topic: 'Punctuation',
    difficulty: 'medium',
    question: 'Choose the correctly punctuated sentence.',
    options: [
      'After the meeting the chairperson said “We will review the proposal tomorrow”.',
      'After the meeting, the chairperson said, “We will review the proposal tomorrow.”',
      'After the meeting, the chairperson said “We will review the proposal tomorrow”.',
      'After the meeting the chairperson said, “We will review the proposal tomorrow”.',
    ],
    correctIndex: 1,
    explanation: 'The introductory phrase takes a comma, the reporting clause uses a comma before the quotation, and the full stop belongs inside the closing quotation mark.',
    source,
  },
];
