import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SSC CHSL 2025 official notification, Tier 1 syllabus — General Awareness section',
  url: 'https://ssc.gov.in/for-candidates/cgl-exam/s40d16nackd16h0',
  checkedOn: '4 August 2026',
};

export const SSC_CHSL_TIER1_GENERAL_AWARENESS_1: Question[] = [
  { id: 'ssc-chsl-t1-ga-001', section: 'General Awareness', topic: 'National symbols', difficulty: 'easy', question: 'What is the national tree of India?', options: ['Banyan', 'Peepal', 'Neem', 'Mango'], correctIndex: 0, explanation: 'The Banyan tree is the national tree of India.', source },
  { id: 'ssc-chsl-t1-ga-002', section: 'General Awareness', topic: 'National symbols', difficulty: 'medium', question: 'What is the national aquatic animal of India?', options: ['Ganges Shark', 'Gangetic River Dolphin', 'Indian Otter', 'Gharial'], correctIndex: 1, explanation: 'The Gangetic River Dolphin is the national aquatic animal of India.', source },
  { id: 'ssc-chsl-t1-ga-003', section: 'General Awareness', topic: 'Static GK', difficulty: 'medium', question: 'In which year was the symbol for the Indian Rupee (₹) officially adopted?', options: ['2008', '2009', '2010', '2012'], correctIndex: 2, explanation: 'The Indian Rupee symbol (₹), designed by D. Udaya Kumar, was officially adopted in 2010.', source },
  { id: 'ssc-chsl-t1-ga-004', section: 'General Awareness', topic: 'Polity', difficulty: 'medium', question: 'How many states does India currently have?', options: ['26', '27', '29', '28'], correctIndex: 3, explanation: 'India currently has 28 states, following the 2019 reorganisation of Jammu and Kashmir into union territories.', source },
  { id: 'ssc-chsl-t1-ga-005', section: 'General Awareness', topic: 'Polity', difficulty: 'medium', question: 'How many union territories does India currently have?', options: ['8', '7', '9', '6'], correctIndex: 0, explanation: 'India currently has 8 union territories.', source },
  { id: 'ssc-chsl-t1-ga-006', section: 'General Awareness', topic: 'Geography', difficulty: 'easy', question: 'Which is the largest continent in the world?', options: ['Africa', 'Asia', 'North America', 'Europe'], correctIndex: 1, explanation: 'Asia is the largest continent in the world by both area and population.', source },
  { id: 'ssc-chsl-t1-ga-007', section: 'General Awareness', topic: 'Geography', difficulty: 'medium', question: 'Which is the smallest continent in the world?', options: ['Antarctica', 'Europe', 'Australia', 'South America'], correctIndex: 2, explanation: 'Australia is the smallest continent in the world.', source },
  { id: 'ssc-chsl-t1-ga-008', section: 'General Awareness', topic: 'Geography', difficulty: 'easy', question: 'Which is the highest mountain peak in the world?', options: ['K2', 'Kangchenjunga', 'Lhotse', 'Mount Everest'], correctIndex: 3, explanation: 'Mount Everest, located in the Himalayas, is the highest mountain peak in the world.', source },
  { id: 'ssc-chsl-t1-ga-009', section: 'General Awareness', topic: 'Geography', difficulty: 'medium', question: 'Which is the highest mountain peak located within India?', options: ['Kangchenjunga', 'K2', 'Nanda Devi', 'Everest'], correctIndex: 0, explanation: 'Kangchenjunga is the highest mountain peak located within India; K2 lies in Pakistan-administered territory and Everest lies on the Nepal-China border.', source },
  { id: 'ssc-chsl-t1-ga-010', section: 'General Awareness', topic: 'Static GK', difficulty: 'easy', question: 'Which is the longest wall in the world?', options: ['Wall of Jericho', 'Great Wall of China', "Hadrian's Wall", 'Berlin Wall'], correctIndex: 1, explanation: 'The Great Wall of China is the longest wall in the world.', source },
  { id: 'ssc-chsl-t1-ga-011', section: 'General Awareness', topic: 'Geography', difficulty: 'easy', question: 'Which is the largest hot desert in the world?', options: ['Gobi', 'Kalahari', 'Sahara', 'Thar'], correctIndex: 2, explanation: 'The Sahara is the largest hot desert in the world.', source },
  { id: 'ssc-chsl-t1-ga-012', section: 'General Awareness', topic: 'Static GK', difficulty: 'easy', question: 'Which Indian city is popularly known as the "Pink City"?', options: ['Udaipur', 'Jodhpur', 'Jaisalmer', 'Jaipur'], correctIndex: 3, explanation: 'Jaipur is popularly known as the "Pink City" because of the pink-coloured buildings in its old quarter.', source },
  { id: 'ssc-chsl-t1-ga-013', section: 'General Awareness', topic: 'Static GK', difficulty: 'easy', question: 'Which Indian city is popularly known as the "City of Lakes"?', options: ['Udaipur', 'Jaipur', 'Jodhpur', 'Ajmer'], correctIndex: 0, explanation: 'Udaipur is popularly known as the "City of Lakes" for its several artificial and natural lakes.', source },
  { id: 'ssc-chsl-t1-ga-014', section: 'General Awareness', topic: 'History', difficulty: 'medium', question: 'Who was the first Indian to travel to space?', options: ['Kalpana Chawla', 'Rakesh Sharma', 'Sunita Williams', 'Vikram Sarabhai'], correctIndex: 1, explanation: 'Rakesh Sharma became the first Indian to travel to space in 1984, aboard a Soviet spacecraft.', source },
  { id: 'ssc-chsl-t1-ga-015', section: 'General Awareness', topic: 'History', difficulty: 'medium', question: "Who was India's first woman President?", options: ['Indira Gandhi', 'Sarojini Naidu', 'Pratibha Patil', 'Droupadi Murmu'], correctIndex: 2, explanation: "Pratibha Patil served as India's first woman President, from 2007 to 2012.", source },
  { id: 'ssc-chsl-t1-ga-016', section: 'General Awareness', topic: 'History', difficulty: 'easy', question: 'Who is popularly known as the "Iron Man of India"?', options: ['Jawaharlal Nehru', 'Subhas Chandra Bose', 'B. R. Ambedkar', 'Sardar Vallabhbhai Patel'], correctIndex: 3, explanation: 'Sardar Vallabhbhai Patel is popularly known as the "Iron Man of India" for his role in unifying the princely states.', source },
  { id: 'ssc-chsl-t1-ga-017', section: 'General Awareness', topic: 'General science', difficulty: 'easy', question: 'What is the chemical formula of water?', options: ['H2O', 'HO2', 'H2O2', 'OH'], correctIndex: 0, explanation: 'Water is chemically represented as H2O — two hydrogen atoms bonded to one oxygen atom.', source },
  { id: 'ssc-chsl-t1-ga-018', section: 'General Awareness', topic: 'General science', difficulty: 'easy', question: 'What is the chemical formula of common table salt?', options: ['NaCO3', 'NaCl', 'Na2O', 'NaOH'], correctIndex: 1, explanation: 'Common table salt is sodium chloride, chemically represented as NaCl.', source },
  { id: 'ssc-chsl-t1-ga-019', section: 'General Awareness', topic: 'General science', difficulty: 'medium', question: 'How many bones are there in a normal adult human body?', options: ['196', '201', '206', '212'], correctIndex: 2, explanation: 'A normal adult human body has 206 bones.', source },
  { id: 'ssc-chsl-t1-ga-020', section: 'General Awareness', topic: 'General science', difficulty: 'easy', question: 'Which organ pumps blood throughout the human body?', options: ['Lungs', 'Kidney', 'Liver', 'Heart'], correctIndex: 3, explanation: 'The heart pumps blood throughout the human body via the circulatory system.', source },
  { id: 'ssc-chsl-t1-ga-021', section: 'General Awareness', topic: 'History', difficulty: 'medium', question: "Who was independent India's first Education Minister?", options: ['Maulana Abul Kalam Azad', 'Jawaharlal Nehru', 'Sardar Patel', 'Rajendra Prasad'], correctIndex: 0, explanation: "Maulana Abul Kalam Azad served as independent India's first Education Minister.", source },
  { id: 'ssc-chsl-t1-ga-022', section: 'General Awareness', topic: 'Static GK', difficulty: 'easy', question: 'Which Indian city is popularly known as the "City of Nawabs"?', options: ['Kanpur', 'Lucknow', 'Agra', 'Varanasi'], correctIndex: 1, explanation: 'Lucknow is popularly known as the "City of Nawabs" for its history under the Nawabs of Awadh.', source },
  { id: 'ssc-chsl-t1-ga-023', section: 'General Awareness', topic: 'Static GK', difficulty: 'easy', question: 'The Gateway of India monument is located in which city?', options: ['Delhi', 'Kolkata', 'Mumbai', 'Chennai'], correctIndex: 2, explanation: 'The Gateway of India monument is located in Mumbai, overlooking the Arabian Sea.', source },
  { id: 'ssc-chsl-t1-ga-024', section: 'General Awareness', topic: 'Geography', difficulty: 'easy', question: 'Which is the largest ocean in the world?', options: ['Atlantic', 'Indian', 'Arctic', 'Pacific'], correctIndex: 3, explanation: 'The Pacific Ocean is the largest and deepest ocean in the world.', source },
  { id: 'ssc-chsl-t1-ga-025', section: 'General Awareness', topic: 'Geography', difficulty: 'medium', question: 'Which is the smallest ocean in the world?', options: ['Arctic', 'Indian', 'Atlantic', 'Southern'], correctIndex: 0, explanation: 'The Arctic Ocean is the smallest and shallowest of the world\'s oceans.', source },
];
