import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SSC CGL 2026 official notice, paragraph 13.11.2 (Tier 2 Reasoning and General Intelligence syllabus)',
  url: 'https://ssc.gov.in/api/attachment/uploads/masterData/NoticeBoards/Notice_of_adv_cgl_2026.pdf',
  checkedOn: '3 August 2026',
};

export const SSC_CGL_TIER2_REASONING_1: Question[] = [
  {
    id: 'ssc-cgl-t2-re1-001',
    section: 'Reasoning and General Intelligence',
    topic: 'Semantic analogy',
    difficulty: 'easy',
    question: 'Sapling is related to tree in the same way as calf is related to:',
    options: ['Cow', 'Goat', 'Horse', 'Deer'],
    correctIndex: 0,
    explanation: 'A sapling is the young form of a tree, while a calf is the young form of a cow.',
    source,
  },
  {
    id: 'ssc-cgl-t2-re1-002',
    section: 'Reasoning and General Intelligence',
    topic: 'Number analogy',
    difficulty: 'medium',
    question: 'Select the number related to 12 in the same way that 72 is related to 8.',
    options: ['144', '156', '132', '168'],
    correctIndex: 1,
    explanation: 'The relation is n x (n + 1). Thus 8 x 9 = 72 and 12 x 13 = 156.',
    source,
  },
  {
    id: 'ssc-cgl-t2-re1-003',
    section: 'Reasoning and General Intelligence',
    topic: 'Classification',
    difficulty: 'easy',
    question: 'Which one is different from the other three?',
    options: ['Copper', 'Iron', 'Brass', 'Silver'],
    correctIndex: 2,
    explanation: 'Copper, iron and silver are elements. Brass is an alloy, so it is the odd one out.',
    source,
  },
  {
    id: 'ssc-cgl-t2-re1-004',
    section: 'Reasoning and General Intelligence',
    topic: 'Number series',
    difficulty: 'easy',
    question: 'Find the next term in the series: 3, 8, 18, 38, 78, ___.',
    options: ['148', '154', '156', '158'],
    correctIndex: 3,
    explanation: 'Each term is twice the previous term plus 2. Therefore 78 x 2 + 2 = 158.',
    source,
  },
  {
    id: 'ssc-cgl-t2-re1-005',
    section: 'Reasoning and General Intelligence',
    topic: 'Coding and decoding',
    difficulty: 'easy',
    question: 'If DELHI is coded as EFMIJ by moving each letter one place forward, how is MUMBAI coded?',
    options: ['NVNCBJ', 'NVMCBJ', 'OVNCBJ', 'NVNCAJ'],
    correctIndex: 0,
    explanation: 'Moving M, U, M, B, A and I one place forward gives N, V, N, C, B and J: NVNCBJ.',
    source,
  },
  {
    id: 'ssc-cgl-t2-re1-006',
    section: 'Reasoning and General Intelligence',
    topic: 'Direction sense',
    difficulty: 'easy',
    question: 'Riya walks 8 km north, 6 km east and then 8 km south. Where is she from her starting point?',
    options: ['6 km west', '6 km east', '8 km north', '8 km south'],
    correctIndex: 1,
    explanation: 'The northward and southward movements cancel, leaving Riya 6 km east of the starting point.',
    source,
  },
  {
    id: 'ssc-cgl-t2-re1-007',
    section: 'Reasoning and General Intelligence',
    topic: 'Blood relations',
    difficulty: 'medium',
    question: 'P is the mother of Q. Q is the brother of R. R is the father of S. How is P related to S?',
    options: ['Maternal aunt', 'Mother', 'Paternal grandmother', 'Sister'],
    correctIndex: 2,
    explanation: 'Q and R are siblings and P is their mother. Since R is S\'s father, P is S\'s paternal grandmother.',
    source,
  },
  {
    id: 'ssc-cgl-t2-re1-008',
    section: 'Reasoning and General Intelligence',
    topic: 'Ranking',
    difficulty: 'easy',
    question: 'Aman is 18th from the top and 25th from the bottom in a class. How many students are in the class?',
    options: ['41', '43', '40', '42'],
    correctIndex: 3,
    explanation: 'Total students = 18 + 25 - 1 = 42 because Aman is counted in both positions.',
    source,
  },
  {
    id: 'ssc-cgl-t2-re1-009',
    section: 'Reasoning and General Intelligence',
    topic: 'Syllogism',
    difficulty: 'medium',
    question: 'Statements: All roses are flowers. Some flowers are red. Conclusions: I. All roses are flowers. II. Some roses are red. Which conclusion follows?',
    options: ['Only I follows', 'Only II follows', 'Both follow', 'Neither follows'],
    correctIndex: 0,
    explanation: 'Conclusion I directly repeats the first statement. The red flowers are not necessarily roses, so conclusion II does not follow.',
    source,
  },
  {
    id: 'ssc-cgl-t2-re1-010',
    section: 'Reasoning and General Intelligence',
    topic: 'Inequalities',
    difficulty: 'easy',
    question: 'If A > B, B is greater than or equal to C, and C = D, which relation is definitely true?',
    options: ['A = D', 'A > D', 'B < D', 'A < C'],
    correctIndex: 1,
    explanation: 'Because B is at least C and C equals D, B is at least D. Since A is greater than B, A must be greater than D.',
    source,
  },
  {
    id: 'ssc-cgl-t2-re1-011',
    section: 'Reasoning and General Intelligence',
    topic: 'Venn diagrams',
    difficulty: 'medium',
    question: 'In a group, 80 people know English, 50 know Hindi and 20 know both. How many know at least one of the two languages?',
    options: ['130', '100', '110', '150'],
    correctIndex: 2,
    explanation: 'Using inclusion-exclusion, the number knowing at least one language is 80 + 50 - 20 = 110.',
    source,
  },
  {
    id: 'ssc-cgl-t2-re1-012',
    section: 'Reasoning and General Intelligence',
    topic: 'Statement and assumption',
    difficulty: 'medium',
    question: 'Statement: Use a password manager to maintain a different strong password for every account. Which assumption is implicit?',
    options: ['Every account is already secure.', 'Strong passwords never need changing.', 'Only businesses need password managers.', 'Remembering many different strong passwords can be difficult.'],
    correctIndex: 3,
    explanation: 'The advice assumes that safely remembering many unique strong passwords is difficult and that a password manager can help.',
    source,
  },
  {
    id: 'ssc-cgl-t2-re1-013',
    section: 'Reasoning and General Intelligence',
    topic: 'Linear arrangement',
    difficulty: 'medium',
    question: 'Five people stand in a row. Q is immediately right of P, R is immediately right of Q, S is left of P, and T is right of R. Who is in the middle?',
    options: ['Q', 'P', 'R', 'S'],
    correctIndex: 0,
    explanation: 'The only possible order is S-P-Q-R-T, so Q occupies the middle position.',
    source,
  },
  {
    id: 'ssc-cgl-t2-re1-014',
    section: 'Reasoning and General Intelligence',
    topic: 'Alphabet test',
    difficulty: 'easy',
    question: 'If the letters of BANKING are arranged in alphabetical order, which letter is fifth?',
    options: ['I', 'K', 'N', 'G'],
    correctIndex: 1,
    explanation: 'The alphabetical order is A, B, G, I, K, N, N. The fifth letter is K.',
    source,
  },
  {
    id: 'ssc-cgl-t2-re1-015',
    section: 'Reasoning and General Intelligence',
    topic: 'Word building',
    difficulty: 'medium',
    question: 'Which word cannot be formed from the letters of EDUCATION without using any letter more often than it appears?',
    options: ['CAUTION', 'ACTION', 'INDICATE', 'DONATE'],
    correctIndex: 2,
    explanation: 'INDICATE requires two Is, but EDUCATION contains only one I. Each of the other words can be formed from the available letters.',
    source,
  },
  {
    id: 'ssc-cgl-t2-re1-016',
    section: 'Reasoning and General Intelligence',
    topic: 'Calendar',
    difficulty: 'easy',
    question: 'If 1 March is a Wednesday, what day of the week is 22 March of the same year?',
    options: ['Monday', 'Tuesday', 'Friday', 'Wednesday'],
    correctIndex: 3,
    explanation: 'The dates are 21 days apart, which is exactly three weeks, so 22 March is also a Wednesday.',
    source,
  },
  {
    id: 'ssc-cgl-t2-re1-017',
    section: 'Reasoning and General Intelligence',
    topic: 'Clock reasoning',
    difficulty: 'medium',
    question: 'What is the smaller angle between the hands of a clock at 5:20?',
    options: ['40 degrees', '50 degrees', '30 degrees', '60 degrees'],
    correctIndex: 0,
    explanation: 'At 5:20 the minute hand is at 120 degrees and the hour hand is at 160 degrees. Their difference is 40 degrees.',
    source,
  },
  {
    id: 'ssc-cgl-t2-re1-018',
    section: 'Reasoning and General Intelligence',
    topic: 'Dice',
    difficulty: 'easy',
    question: 'On a standard die, opposite faces add up to 7. Which face is opposite the face numbered 2?',
    options: ['4', '5', '3', '6'],
    correctIndex: 1,
    explanation: 'Opposite faces total 7, so the face opposite 2 is 7 - 2 = 5.',
    source,
  },
  {
    id: 'ssc-cgl-t2-re1-019',
    section: 'Reasoning and General Intelligence',
    topic: 'Symbolic operations',
    difficulty: 'easy',
    question: 'If + means multiplication and - means addition, what is the value of 8 + 3 - 4?',
    options: ['20', '24', '28', '36'],
    correctIndex: 2,
    explanation: 'Replacing the symbols gives 8 x 3 + 4 = 24 + 4 = 28.',
    source,
  },
  {
    id: 'ssc-cgl-t2-re1-020',
    section: 'Reasoning and General Intelligence',
    topic: 'Dictionary order',
    difficulty: 'medium',
    question: 'When Apple, Application, Apply and Aptitude are arranged in dictionary order, which word is third?',
    options: ['Apple', 'Application', 'Aptitude', 'Apply'],
    correctIndex: 3,
    explanation: 'The order is Apple, Application, Apply, Aptitude. Therefore Apply is third.',
    source,
  },
  {
    id: 'ssc-cgl-t2-re1-021',
    section: 'Reasoning and General Intelligence',
    topic: 'Cause and effect',
    difficulty: 'easy',
    question: 'Event I: Heavy rain continued throughout the night. Event II: The river level rose sharply by morning. What is the most reasonable relation?',
    options: ['Event I is a likely cause of Event II.', 'Event II caused Event I.', 'The events must be unrelated.', 'Both events were caused by road traffic.'],
    correctIndex: 0,
    explanation: 'Sustained heavy rainfall can add water to the river catchment, making Event I a reasonable cause of Event II.',
    source,
  },
  {
    id: 'ssc-cgl-t2-re1-022',
    section: 'Reasoning and General Intelligence',
    topic: 'Drawing inferences',
    difficulty: 'medium',
    question: 'All registered participants received an access code. Meera did not receive an access code. What follows logically?',
    options: ['Meera lost her code.', 'Meera was not a registered participant.', 'No participant received a code.', 'Meera registered twice.'],
    correctIndex: 1,
    explanation: 'If every registered participant received a code, then someone who did not receive a code cannot be in the registered group.',
    source,
  },
  {
    id: 'ssc-cgl-t2-re1-023',
    section: 'Reasoning and General Intelligence',
    topic: 'Logical conclusions',
    difficulty: 'medium',
    question: 'Statements: Some books are journals. All journals are indexed. Which conclusion definitely follows?',
    options: ['All books are indexed.', 'No book is indexed.', 'Some books are indexed.', 'All indexed items are journals.'],
    correctIndex: 2,
    explanation: 'The books that are journals must be indexed because all journals are indexed. Therefore some books are indexed.',
    source,
  },
  {
    id: 'ssc-cgl-t2-re1-024',
    section: 'Reasoning and General Intelligence',
    topic: 'Emotional intelligence',
    difficulty: 'easy',
    question: 'During a disagreement, which response best demonstrates emotional intelligence?',
    options: ['Interrupt to defend your position.', 'Avoid the person permanently.', 'Raise your voice to end the discussion.', 'Listen carefully and clarify the concern before responding.'],
    correctIndex: 3,
    explanation: 'Listening and clarifying before responding shows self-control, empathy and constructive communication.',
    source,
  },
  {
    id: 'ssc-cgl-t2-re1-025',
    section: 'Reasoning and General Intelligence',
    topic: 'Social intelligence',
    difficulty: 'easy',
    question: 'A new teammate remains quiet during a group discussion. What is the most socially intelligent response?',
    options: ['Invite their view without putting them under pressure.', 'Assume they have nothing useful to add.', 'Speak for them without asking.', 'Exclude them from the next meeting.'],
    correctIndex: 0,
    explanation: 'A respectful invitation creates space for participation while recognising that the teammate may need time or encouragement.',
    source,
  },
  {
    id: 'ssc-cgl-t2-re1-026',
    section: 'Reasoning and General Intelligence',
    topic: 'Data sufficiency',
    difficulty: 'medium',
    question: 'What is x? Statement I: x + y = 10. Statement II: y = 4. Which information is sufficient?',
    options: ['Statement I alone', 'Both statements together', 'Statement II alone', 'Either statement alone'],
    correctIndex: 1,
    explanation: 'Neither statement alone fixes x. Together they give x + 4 = 10, so x = 6.',
    source,
  },
  {
    id: 'ssc-cgl-t2-re1-027',
    section: 'Reasoning and General Intelligence',
    topic: 'Ordering',
    difficulty: 'easy',
    question: 'A is older than B but younger than C. D is younger than B. Who is the oldest?',
    options: ['A', 'B', 'C', 'D'],
    correctIndex: 2,
    explanation: 'The order is C older than A, A older than B, and B older than D. Therefore C is the oldest.',
    source,
  },
  {
    id: 'ssc-cgl-t2-re1-028',
    section: 'Reasoning and General Intelligence',
    topic: 'Cube and dice',
    difficulty: 'hard',
    question: 'A cube is painted on all six faces and cut into 27 equal smaller cubes. How many smaller cubes have exactly two painted faces?',
    options: ['8', '6', '24', '12'],
    correctIndex: 3,
    explanation: 'Each of the 12 edges contributes one non-corner cube with exactly two painted faces when the cube is divided 3 x 3 x 3. The answer is 12.',
    source,
  },
  {
    id: 'ssc-cgl-t2-re1-029',
    section: 'Reasoning and General Intelligence',
    topic: 'Space orientation',
    difficulty: 'medium',
    question: 'A person faces north, turns 225 degrees clockwise and then 45 degrees anticlockwise. Which direction is the person facing?',
    options: ['South', 'West', 'South-west', 'East'],
    correctIndex: 0,
    explanation: 'The net clockwise turn is 225 - 45 = 180 degrees. A 180-degree turn from north points south.',
    source,
  },
  {
    id: 'ssc-cgl-t2-re1-030',
    section: 'Reasoning and General Intelligence',
    topic: 'Order arrangement',
    difficulty: 'easy',
    question: 'Three boxes—red, blue and green—are placed in a row. Red is left of blue, and green is right of blue. Which box is in the middle?',
    options: ['Red', 'Blue', 'Green', 'Cannot be determined'],
    correctIndex: 1,
    explanation: 'The conditions give the order red-blue-green, so the blue box is in the middle.',
    source,
  },
];
