import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SSC CGL 2026 official notice, paragraph 13.10.3 (Quantitative Aptitude syllabus)',
  url: 'https://ssc.gov.in/api/attachment/uploads/masterData/NoticeBoards/Notice_of_adv_cgl_2026.pdf',
  checkedOn: '3 August 2026',
};

export const SSC_CGL_TIER1_QUANTITATIVE_3: Question[] = [
  {
    id: 'ssc-cgl-t1-qa3-001',
    section: 'Quantitative Aptitude',
    topic: 'Percentage',
    difficulty: 'easy',
    question: 'What is 35% of 840?',
    options: ['294', '284', '304', '314'],
    correctIndex: 0,
    explanation: '35% of 840 = 35/100 x 840 = 294.',
    source,
  },
  {
    id: 'ssc-cgl-t1-qa3-002',
    section: 'Quantitative Aptitude',
    topic: 'Ratio and proportion',
    difficulty: 'easy',
    question: 'Two numbers are in the ratio 7:9 and their sum is 128. What is the smaller number?',
    options: ['48', '56', '63', '72'],
    correctIndex: 1,
    explanation: 'The 16 ratio-parts equal 128, so one part is 8. The smaller number is 7 x 8 = 56.',
    source,
  },
  {
    id: 'ssc-cgl-t1-qa3-003',
    section: 'Quantitative Aptitude',
    topic: 'Average',
    difficulty: 'easy',
    question: 'What is the average of the first nine positive multiples of 4?',
    options: ['16', '18', '20', '22'],
    correctIndex: 2,
    explanation: 'The multiples form an arithmetic sequence from 4 to 36. Its average is (4 + 36) / 2 = 20.',
    source,
  },
  {
    id: 'ssc-cgl-t1-qa3-004',
    section: 'Quantitative Aptitude',
    topic: 'Profit and loss',
    difficulty: 'easy',
    question: 'An article is sold for Rs 960 at a profit of 20%. What is its cost price?',
    options: ['Rs 720', 'Rs 760', 'Rs 840', 'Rs 800'],
    correctIndex: 3,
    explanation: 'Selling price is 120% of cost price. Cost price = 960 / 1.20 = Rs 800.',
    source,
  },
  {
    id: 'ssc-cgl-t1-qa3-005',
    section: 'Quantitative Aptitude',
    topic: 'Discount',
    difficulty: 'easy',
    question: 'A shop offers a 15% discount on an item marked at Rs 1,600. What is the selling price?',
    options: ['Rs 1,360', 'Rs 1,340', 'Rs 1,380', 'Rs 1,400'],
    correctIndex: 0,
    explanation: 'The discount is 15% of 1,600 = Rs 240. The selling price is 1,600 - 240 = Rs 1,360.',
    source,
  },
  {
    id: 'ssc-cgl-t1-qa3-006',
    section: 'Quantitative Aptitude',
    topic: 'Simple interest',
    difficulty: 'easy',
    question: 'Find the simple interest on Rs 7,500 at 8% per annum for 3 years.',
    options: ['Rs 1,600', 'Rs 1,800', 'Rs 2,000', 'Rs 2,200'],
    correctIndex: 1,
    explanation: 'Simple interest = 7,500 x 8 x 3 / 100 = Rs 1,800.',
    source,
  },
  {
    id: 'ssc-cgl-t1-qa3-007',
    section: 'Quantitative Aptitude',
    topic: 'Compound interest',
    difficulty: 'medium',
    question: 'What is the compound interest on Rs 5,000 at 10% per annum for 2 years, compounded annually?',
    options: ['Rs 1,000', 'Rs 1,100', 'Rs 1,050', 'Rs 1,150'],
    correctIndex: 2,
    explanation: 'Amount = 5,000 x 1.1 squared = Rs 6,050. Compound interest = 6,050 - 5,000 = Rs 1,050.',
    source,
  },
  {
    id: 'ssc-cgl-t1-qa3-008',
    section: 'Quantitative Aptitude',
    topic: 'Time and work',
    difficulty: 'medium',
    question: 'A can complete a job in 12 days and B in 18 days. How long will they take together?',
    options: ['6 days', '8 days', '9 days', '7.2 days'],
    correctIndex: 3,
    explanation: 'Their combined daily work is 1/12 + 1/18 = 5/36. Time required = 36/5 = 7.2 days.',
    source,
  },
  {
    id: 'ssc-cgl-t1-qa3-009',
    section: 'Quantitative Aptitude',
    topic: 'Pipes and cisterns',
    difficulty: 'medium',
    question: 'One pipe fills a tank in 15 minutes and another fills it in 10 minutes. How long do they take together?',
    options: ['6 minutes', '5 minutes', '7.5 minutes', '12 minutes'],
    correctIndex: 0,
    explanation: 'Their combined rate is 1/15 + 1/10 = 1/6 tank per minute, so they take 6 minutes.',
    source,
  },
  {
    id: 'ssc-cgl-t1-qa3-010',
    section: 'Quantitative Aptitude',
    topic: 'Time and distance',
    difficulty: 'easy',
    question: 'A car covers 360 km in 4 hours 30 minutes. What is its average speed?',
    options: ['75 km/h', '80 km/h', '85 km/h', '90 km/h'],
    correctIndex: 1,
    explanation: '4 hours 30 minutes is 4.5 hours. Average speed = 360 / 4.5 = 80 km/h.',
    source,
  },
  {
    id: 'ssc-cgl-t1-qa3-011',
    section: 'Quantitative Aptitude',
    topic: 'Trains',
    difficulty: 'easy',
    question: 'A 180-metre train passes a pole in 9 seconds. What is its speed?',
    options: ['60 km/h', '64 km/h', '72 km/h', '80 km/h'],
    correctIndex: 2,
    explanation: 'Speed = 180/9 = 20 m/s. Converting to km/h gives 20 x 18/5 = 72 km/h.',
    source,
  },
  {
    id: 'ssc-cgl-t1-qa3-012',
    section: 'Quantitative Aptitude',
    topic: 'Boats and streams',
    difficulty: 'medium',
    question: 'A boat travels at 18 km/h downstream and 10 km/h upstream. What is the speed of the stream?',
    options: ['3 km/h', '5 km/h', '14 km/h', '4 km/h'],
    correctIndex: 3,
    explanation: 'Stream speed = (downstream speed - upstream speed) / 2 = (18 - 10) / 2 = 4 km/h.',
    source,
  },
  {
    id: 'ssc-cgl-t1-qa3-013',
    section: 'Quantitative Aptitude',
    topic: 'Mixture',
    difficulty: 'medium',
    question: 'A 40-litre mixture contains milk and water in the ratio 3:2. How much water must be added to make the ratio 1:1?',
    options: ['8 litres', '6 litres', '10 litres', '12 litres'],
    correctIndex: 0,
    explanation: 'The mixture has 24 L milk and 16 L water. Water must become 24 L, so 8 L is added.',
    source,
  },
  {
    id: 'ssc-cgl-t1-qa3-014',
    section: 'Quantitative Aptitude',
    topic: 'Percentage comparison',
    difficulty: 'medium',
    question: 'If A is 25% more than B, then B is what percent less than A?',
    options: ['16%', '20%', '25%', '30%'],
    correctIndex: 1,
    explanation: 'Let B = 100, so A = 125. The shortfall is 25 out of 125, which is 20%.',
    source,
  },
  {
    id: 'ssc-cgl-t1-qa3-015',
    section: 'Quantitative Aptitude',
    topic: 'HCF',
    difficulty: 'easy',
    question: 'What is the HCF of 252 and 198?',
    options: ['9', '12', '18', '36'],
    correctIndex: 2,
    explanation: '252 = 14 x 18 and 198 = 11 x 18, so their highest common factor is 18.',
    source,
  },
  {
    id: 'ssc-cgl-t1-qa3-016',
    section: 'Quantitative Aptitude',
    topic: 'LCM',
    difficulty: 'easy',
    question: 'Find the least positive number that is exactly divisible by 12, 15 and 20.',
    options: ['30', '40', '120', '60'],
    correctIndex: 3,
    explanation: '12 = 2 squared x 3, 15 = 3 x 5 and 20 = 2 squared x 5. Their LCM is 2 squared x 3 x 5 = 60.',
    source,
  },
  {
    id: 'ssc-cgl-t1-qa3-017',
    section: 'Quantitative Aptitude',
    topic: 'Remainders',
    difficulty: 'medium',
    question: 'What is the remainder when 2 to the power 10 is divided by 7?',
    options: ['2', '1', '3', '4'],
    correctIndex: 0,
    explanation: '2 to the power 10 = 1,024, and 1,024 = 7 x 146 + 2. The remainder is 2.',
    source,
  },
  {
    id: 'ssc-cgl-t1-qa3-018',
    section: 'Quantitative Aptitude',
    topic: 'Linear equations',
    difficulty: 'medium',
    question: 'If x/3 + x/4 = 35, what is x?',
    options: ['48', '60', '72', '84'],
    correctIndex: 1,
    explanation: '7x/12 = 35, so x = 35 x 12 / 7 = 60.',
    source,
  },
  {
    id: 'ssc-cgl-t1-qa3-019',
    section: 'Quantitative Aptitude',
    topic: 'Quadratic equations',
    difficulty: 'medium',
    question: 'What is the larger root of x squared - 11x + 28 = 0?',
    options: ['4', '6', '7', '8'],
    correctIndex: 2,
    explanation: 'The expression factors as (x - 4)(x - 7) = 0. The roots are 4 and 7, so the larger root is 7.',
    source,
  },
  {
    id: 'ssc-cgl-t1-qa3-020',
    section: 'Quantitative Aptitude',
    topic: 'Geometry',
    difficulty: 'hard',
    question: 'What is the area of a triangle whose side lengths are 13 cm, 14 cm and 15 cm?',
    options: ['72 square cm', '78 square cm', '90 square cm', '84 square cm'],
    correctIndex: 3,
    explanation: 'The semiperimeter is 21. By Heron\'s formula, area = square root of (21 x 8 x 7 x 6) = square root of 7,056 = 84 square cm.',
    source,
  },
  {
    id: 'ssc-cgl-t1-qa3-021',
    section: 'Quantitative Aptitude',
    topic: 'Circle',
    difficulty: 'easy',
    question: 'Using pi = 3.14, what is the circumference of a circle with radius 10 cm?',
    options: ['62.8 cm', '31.4 cm', '64.8 cm', '314 cm'],
    correctIndex: 0,
    explanation: 'Circumference = 2 x pi x radius = 2 x 3.14 x 10 = 62.8 cm.',
    source,
  },
  {
    id: 'ssc-cgl-t1-qa3-022',
    section: 'Quantitative Aptitude',
    topic: 'Mensuration',
    difficulty: 'medium',
    question: 'Using pi = 22/7, what is the volume of a cylinder with radius 7 cm and height 10 cm?',
    options: ['1,320 cubic cm', '1,540 cubic cm', '1,760 cubic cm', '3,080 cubic cm'],
    correctIndex: 1,
    explanation: 'Volume = pi x radius squared x height = 22/7 x 49 x 10 = 1,540 cubic cm.',
    source,
  },
  {
    id: 'ssc-cgl-t1-qa3-023',
    section: 'Quantitative Aptitude',
    topic: 'Trigonometry',
    difficulty: 'medium',
    question: 'If tan theta = 3/4 and theta is acute, what is sec theta?',
    options: ['3/5', '4/5', '5/4', '5/3'],
    correctIndex: 2,
    explanation: 'A right triangle with opposite side 3 and adjacent side 4 has hypotenuse 5. Therefore sec theta = 5/4.',
    source,
  },
  {
    id: 'ssc-cgl-t1-qa3-024',
    section: 'Quantitative Aptitude',
    topic: 'Data interpretation',
    difficulty: 'easy',
    question: 'A shop sold 120, 150, 180, 210 and 240 units over five months. What was the average monthly sale?',
    options: ['160 units', '170 units', '190 units', '180 units'],
    correctIndex: 3,
    explanation: 'Total sales = 900 units. Average = 900 / 5 = 180 units.',
    source,
  },
  {
    id: 'ssc-cgl-t1-qa3-025',
    section: 'Quantitative Aptitude',
    topic: 'Probability',
    difficulty: 'easy',
    question: 'A fair die is rolled once. What is the probability of getting a number greater than 4?',
    options: ['1/3', '1/6', '1/2', '2/3'],
    correctIndex: 0,
    explanation: 'The favourable outcomes are 5 and 6, so the probability is 2/6 = 1/3.',
    source,
  },
];
