import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SSC CGL 2026 official notice, paragraph 13.11.2 (Tier 2 Reasoning and General Intelligence syllabus)',
  url: 'https://ssc.gov.in/api/attachment/uploads/masterData/NoticeBoards/Notice_of_adv_cgl_2026.pdf',
  checkedOn: '3 August 2026',
};

function question(id: string, topic: string, difficulty: 'easy' | 'medium' | 'hard', prompt: string, options: string[], correctIndex: number, explanation: string): Question {
  return { id, section: 'Reasoning and General Intelligence', topic, difficulty, question: prompt, options, correctIndex, explanation, source };
}

export const SSC_CGL_TIER2_REASONING_3: Question[] = [
  question('ssc-cgl-t2-re3-001', 'Semantic analogy', 'easy', 'Thermometer is related to temperature in the same way as barometer is related to:', ['Atmospheric pressure', 'Rainfall', 'Wind direction', 'Humidity'], 0, 'A thermometer measures temperature, while a barometer measures atmospheric pressure.'),
  question('ssc-cgl-t2-re3-002', 'Number analogy', 'easy', 'Select the number related to 9 in the same way that 30 is related to 5.', ['81', '90', '72', '99'], 1, 'The relation is n x (n + 1). Thus 5 x 6 = 30 and 9 x 10 = 90.'),
  question('ssc-cgl-t2-re3-003', 'Classification', 'easy', 'Which number differs from the other three?', ['121', '144', '180', '169'], 2, '121, 144 and 169 are perfect squares. 180 is not a perfect square.'),
  question('ssc-cgl-t2-re3-004', 'Number series', 'easy', 'Find the next term in the series: 2, 6, 12, 20, 30, ___.', ['36', '38', '40', '42'], 3, 'The terms are n x (n + 1) for n = 1, 2, 3, 4 and 5. The next is 6 x 7 = 42.'),
  question('ssc-cgl-t2-re3-005', 'Coding and decoding', 'medium', 'In a code, each letter is replaced by its opposite in the alphabet, so A becomes Z and B becomes Y. If CAT is coded as XZG, how is DOG coded?', ['WLT', 'DMT', 'WOG', 'ELU'], 0, 'Using opposite letters gives D to W, O to L and G to T, producing WLT.'),
  question('ssc-cgl-t2-re3-006', 'Direction sense', 'easy', 'A person faces east and turns 270 degrees clockwise. Which direction is the person now facing?', ['West', 'North', 'South', 'Northeast'], 1, 'A 270-degree clockwise turn from east passes south and west, ending at north.'),
  question('ssc-cgl-t2-re3-007', 'Blood relations', 'medium', 'K is the mother of L. M is K\'s husband, and N is M\'s sister. How is N related to L?', ['Mother', 'Grandmother', 'Aunt', 'Sister'], 2, 'N is the sister of L\'s father M, so N is L\'s aunt.'),
  question('ssc-cgl-t2-re3-008', 'Ranking', 'easy', 'Rohan is 9th from the left and 17th from the right in a row. How many people are in the row?', ['24', '26', '27', '25'], 3, 'Total people = 9 + 17 - 1 = 25 because Rohan is counted from both ends.'),
  question('ssc-cgl-t2-re3-009', 'Syllogism', 'medium', 'Statements: All laptops are machines. Some machines are portable. Conclusions: I. All laptops are machines. II. Some laptops are portable. Which conclusion follows?', ['Only I follows', 'Only II follows', 'Both follow', 'Neither follows'], 0, 'Conclusion I repeats the first statement. The portable machines need not be laptops, so conclusion II does not follow.'),
  question('ssc-cgl-t2-re3-010', 'Inequalities', 'medium', 'If A < B, B is less than or equal to C, and C < D, which relation is definitely true?', ['A = D', 'A < D', 'B = D', 'D < A'], 1, 'A is less than B, B is at most C, and C is less than D. Therefore A < D.'),
  question('ssc-cgl-t2-re3-011', 'Venn diagrams', 'easy', 'In a group, 70 people drink tea, 55 drink coffee and 25 drink both. How many drink at least one of the two?', ['125', '110', '100', '95'], 2, 'Using inclusion-exclusion, 70 + 55 - 25 = 100 people drink at least one.'),
  question('ssc-cgl-t2-re3-012', 'Statement and assumption', 'easy', 'Statement: Wear a helmet while riding a two-wheeler. Which assumption is most directly implicit?', ['Helmets make vehicles faster', 'Every road is empty', 'Only passengers face danger', 'A helmet can reduce the risk of head injury'], 3, 'The safety advice assumes that wearing a helmet can reduce the risk or severity of head injury.'),
  question('ssc-cgl-t2-re3-013', 'Circular arrangement', 'medium', 'Four people A, B, C and D sit around a square table facing the centre. A sits opposite C, and B sits immediately to the right of A. Who sits opposite B?', ['D', 'A', 'C', 'B'], 0, 'With A opposite C, the two remaining seats are occupied by B and D. Therefore B and D are opposite each other.'),
  question('ssc-cgl-t2-re3-014', 'Alphabet test', 'easy', 'Which letter is fourth to the right of M in the English alphabet?', ['P', 'Q', 'R', 'S'], 1, 'Counting four places after M gives N, O, P and Q.'),
  question('ssc-cgl-t2-re3-015', 'Word building', 'hard', 'Which word cannot be formed from the letters of ADMINISTRATION without using any letter more often than it appears?', ['STATION', 'RATIO', 'NOMINATION', 'TRAIN'], 2, 'NOMINATION needs three Ns and two Os, while ADMINISTRATION contains only two Ns and one O. The other options can be formed.'),
  question('ssc-cgl-t2-re3-016', 'Calendar', 'medium', 'In a leap year, 1 February is a Tuesday. What day of the week is 1 March?', ['Monday', 'Tuesday', 'Thursday', 'Wednesday'], 3, 'February has 29 days in a leap year. Since 29 leaves remainder 1 when divided by 7, 1 March is one weekday later: Wednesday.'),
  question('ssc-cgl-t2-re3-017', 'Clock reasoning', 'medium', 'What is the smaller angle between the hands of a clock at 3:40?', ['130 degrees', '120 degrees', '140 degrees', '150 degrees'], 0, 'At 3:40, the minute hand is at 240 degrees and the hour hand is at 110 degrees. The difference is 130 degrees.'),
  question('ssc-cgl-t2-re3-018', 'Dice', 'easy', 'On a standard die, opposite faces add up to 7. Which face is opposite the face numbered 3?', ['2', '4', '5', '6'], 1, 'The number opposite 3 is 4 because 3 + 4 = 7.'),
  question('ssc-cgl-t2-re3-019', 'Symbolic operations', 'easy', 'If $ means multiplication and % means addition, what is the value of 6 $ 5 % 4?', ['24', '30', '34', '44'], 2, 'Replacing the symbols gives 6 x 5 + 4 = 30 + 4 = 34.'),
  question('ssc-cgl-t2-re3-020', 'Dictionary order', 'medium', 'When Preach, Precise, Predict and Prefer are arranged in dictionary order, which word comes fourth?', ['Preach', 'Precise', 'Predict', 'Prefer'], 3, 'The order is Preach, Precise, Predict, Prefer. Therefore Prefer comes fourth.'),
  question('ssc-cgl-t2-re3-021', 'Cause and effect', 'easy', 'Event I: The temperature fell below freezing overnight. Event II: Water in exposed pipes froze. What is the most reasonable relation?', ['Event I is a cause of Event II', 'Event II is a cause of Event I', 'The events are unrelated', 'Both events are effects of the pipes'], 0, 'Below-freezing temperature can cause exposed water to freeze, so Event I reasonably causes Event II.'),
  question('ssc-cgl-t2-re3-022', 'Drawing inferences', 'easy', 'Every approved voucher carries an authorised signature. This voucher has been approved. What follows logically?', ['It has expired', 'It carries an authorised signature', 'It was rejected earlier', 'It contains no amount'], 1, 'The voucher is approved, and every approved voucher has the signature. Therefore this voucher carries an authorised signature.'),
  question('ssc-cgl-t2-re3-023', 'Logical conclusions', 'medium', 'Statements: Some artists are teachers. No teacher is a pilot. Which conclusion definitely follows?', ['All artists are teachers', 'No artist is a pilot', 'Some artists are not pilots', 'Some pilots are artists'], 2, 'The artists who are teachers cannot be pilots, so some artists are not pilots.'),
  question('ssc-cgl-t2-re3-024', 'Emotional intelligence', 'easy', 'You receive unexpected negative feedback on a completed task. Which response best demonstrates emotional intelligence?', ['Dismiss the feedback immediately', 'Blame another person', 'Avoid the reviewer permanently', 'Ask for specific examples and reflect before responding'], 3, 'Seeking examples and pausing to reflect manages the emotional reaction while using the feedback constructively.'),
  question('ssc-cgl-t2-re3-025', 'Social intelligence', 'easy', 'Two group members repeatedly interrupt each other. What is the most socially intelligent response from the facilitator?', ['Set a turn-taking rule and invite each person to finish', 'Choose one person and silence the other', 'End the discussion without explanation', 'Ignore the interruptions'], 0, 'A clear turn-taking process treats both people fairly and helps the group hear each view.'),
  question('ssc-cgl-t2-re3-026', 'Data sufficiency', 'medium', 'What is x? Statement I: x - y = 4. Statement II: x + y = 10. Which information is sufficient?', ['Statement I alone', 'Both statements together', 'Statement II alone', 'Either statement alone'], 1, 'Neither statement alone fixes x. Adding both equations gives 2x = 14, so together they give x = 7.'),
  question('ssc-cgl-t2-re3-027', 'Ordering', 'easy', 'A is faster than B. C is slower than B. D is faster than A. Who is the fastest?', ['A', 'B', 'D', 'C'], 2, 'D is faster than A, while A is faster than B and C is slower than B. Therefore D is fastest.'),
  question('ssc-cgl-t2-re3-028', 'Cube and dice', 'medium', 'A cube is painted on all six faces and cut into 125 equal smaller cubes. How many smaller cubes have exactly three painted faces?', ['4', '12', '20', '8'], 3, 'The cube is divided 5 x 5 x 5. Only the eight corner cubes have exactly three painted faces.'),
  question('ssc-cgl-t2-re3-029', 'Space orientation', 'medium', 'A person faces south, turns 225 degrees clockwise and then 45 degrees anticlockwise. Which direction is the person facing?', ['North', 'Northeast', 'West', 'Southwest'], 0, 'The net turn is 180 degrees clockwise. A half-turn from south leads to north.'),
  question('ssc-cgl-t2-re3-030', 'Order arrangement', 'easy', 'Five books A, B, C, D and E are arranged in a row. A is left of B, C is right of B, D is left of A, and E is right of C. Which book is fourth from the left?', ['B', 'C', 'D', 'E'], 1, 'The only order satisfying all relations is D, A, B, C, E. Therefore C is fourth from the left.'),
];
