import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SSC CGL 2026 official notice, paragraph 13.11.3 (Tier 2 English Language and Comprehension syllabus)',
  url: 'https://ssc.gov.in/api/attachment/uploads/masterData/NoticeBoards/Notice_of_adv_cgl_2026.pdf',
  checkedOn: '3 August 2026',
};

function question(
  id: string,
  topic: string,
  difficulty: 'easy' | 'medium' | 'hard',
  prompt: string,
  options: string[],
  correctIndex: number,
  explanation: string,
): Question {
  return { id, section: 'English Language and Comprehension', topic, difficulty, question: prompt, options, correctIndex, explanation, source };
}

const COMMUNITY_RADIO =
  'A coastal town created a community-radio network to strengthen storm preparedness. Trained volunteers translated official weather bulletins into local languages and broadcast them at fixed times. Fishers also shared observations from the coast, but the station clearly separated these reports from forecasts issued by the weather department. Regular drills helped residents learn evacuation routes and shelter locations. When a severe storm arrived, the network did not replace official warnings; it helped those warnings reach people quickly and in familiar language.';

const CROP_ROTATION =
  'For years, many farmers in a dry district planted the same crop because its market and cultivation routine were familiar. The practice offered predictable short-term returns, but repeated pest attacks and declining soil quality increased costs. A cooperative then tested rotations involving legumes and millets on small plots, recording yields, rainfall and input expenses. Results were mixed in the first season. After three years, however, several farms used less fertiliser and handled irregular rainfall better. The cooperative did not prescribe one universal rotation; it asked farmers to adapt the evidence to local soil, water and market conditions.';

const BUS_FARE_PILOT =
  'A city transport authority piloted a mobile fare application on selected bus routes. Boarding became faster for many smartphone users, but some older passengers and people without reliable internet found the change confusing. The authority therefore retained paper passes and staffed counters, while conductors were trained to explain both payment methods. During the six-month pilot, the team collected boarding-time data and passenger feedback. It planned to revise the system before any wider launch. The stated goal was to add a convenient option, not to force every passenger into one method.';

export const SSC_CGL_TIER2_ENGLISH_3: Question[] = [
  question('ssc-cgl-t2-en3-001', 'Synonyms', 'easy', 'Choose the word closest in meaning to "lucid".', ['Clear', 'Confusing', 'Lengthy', 'Secret'], 0, 'Lucid means clear and easy to understand.'),
  question('ssc-cgl-t2-en3-002', 'Antonyms', 'easy', 'Choose the word opposite in meaning to "hostile".', ['Aggressive', 'Friendly', 'Uncertain', 'Distant'], 1, 'Hostile means unfriendly or antagonistic; friendly is its opposite.'),
  question('ssc-cgl-t2-en3-003', 'Homophones', 'easy', 'Choose the correct word: The city ___ met to discuss the new park.', ['counsel', 'counsul', 'council', 'counsil'], 2, 'Council means an elected or appointed group that meets to make decisions. Counsel means advice.'),
  question('ssc-cgl-t2-en3-004', 'Spellings', 'easy', 'Select the correctly spelled word for an event that takes place.', ['occurence', 'ocurrence', 'occurrance', 'occurrence'], 3, 'Occurrence is spelled with two cs and two rs.'),
  question('ssc-cgl-t2-en3-005', 'Synonyms', 'medium', 'Choose the word closest in meaning to "mitigate".', ['Reduce', 'Intensify', 'Ignore', 'Predict'], 0, 'Mitigate means to make something harmful or unpleasant less severe.'),
  question('ssc-cgl-t2-en3-006', 'Subject-verb agreement', 'easy', 'Choose the correct completion: Either of these routes ___ suitable for the journey.', ['are', 'is', 'have been', 'were'], 1, 'Either is singular here, so it takes the singular verb is.'),
  question('ssc-cgl-t2-en3-007', 'Spot the error', 'medium', 'Identify the part containing an error: The list / of selected candidates / were displayed / yesterday.', ['The list', 'of selected candidates', 'were displayed', 'yesterday'], 2, 'The subject list is singular, so were displayed should be was displayed.'),
  question('ssc-cgl-t2-en3-008', 'Fill in the blanks', 'easy', 'Choose the correct completion: Unless you hurry, you ___ the train.', ['missed', 'had missed', 'would miss', 'will miss'], 3, 'In this real future condition, unless takes the present tense and the result clause uses will miss.'),
  question('ssc-cgl-t2-en3-009', 'Articles', 'easy', 'Choose the correct article: She studies at ___ European university.', ['a', 'an', 'the', 'no article'], 0, 'European begins with the consonant sound "y", so it takes a.'),
  question('ssc-cgl-t2-en3-010', 'Prepositions', 'easy', 'Choose the correct preposition: The driver was accused ___ reckless driving.', ['for', 'of', 'with', 'by'], 1, 'The standard construction is accused of an offence or action.'),
  question('ssc-cgl-t2-en3-011', 'Idioms and phrases', 'easy', 'What does the expression "under the weather" mean?', ['Outdoors', 'Unprepared', 'Slightly ill', 'Very successful'], 2, 'Under the weather means feeling slightly ill or unwell.'),
  question('ssc-cgl-t2-en3-012', 'Idioms and phrases', 'medium', 'What does the idiom "cut corners" mean?', ['Draw a straight line', 'Reduce travel time safely', 'Complete every detail', 'Do something cheaply or carelessly by skipping steps'], 3, 'To cut corners is to save time or money by omitting necessary steps or quality.'),
  question('ssc-cgl-t2-en3-013', 'One-word substitution', 'easy', 'Choose the one-word substitute for "a person who loves and collects books".', ['Bibliophile', 'Philatelist', 'Numismatist', 'Linguist'], 0, 'A bibliophile is a person who loves or collects books.'),
  question('ssc-cgl-t2-en3-014', 'One-word substitution', 'easy', 'Choose the word meaning "having no known name or identity".', ['Ambiguous', 'Anonymous', 'Audible', 'Authentic'], 1, 'Anonymous means not identified by name.'),
  question('ssc-cgl-t2-en3-015', 'One-word substitution', 'easy', 'A person\'s life story written by that person is called:', ['A biography', 'A diary entry', 'An autobiography', 'An anthology'], 2, 'An autobiography is an account of a person\'s life written by that person.'),
  question('ssc-cgl-t2-en3-016', 'Sentence improvement', 'easy', 'Choose the correct replacement for: "I prefer tea than coffee."', ['prefer tea over than coffee', 'am preferring tea than coffee', 'prefer more tea than coffee', 'prefer tea to coffee'], 3, 'The standard construction is prefer one thing to another.'),
  question('ssc-cgl-t2-en3-017', 'Active and passive voice', 'easy', 'Choose the passive form of: "People speak English in many countries."', ['English is spoken in many countries.', 'English was speaking in many countries.', 'Many countries have spoken English.', 'People are spoken by English.'], 0, 'The simple present passive uses is + past participle: is spoken.'),
  question('ssc-cgl-t2-en3-018', 'Active and passive voice', 'easy', 'Choose the active form of: "The bridge was designed by a local architect."', ['A local architect has designed the bridge.', 'A local architect designed the bridge.', 'A local architect designs the bridge.', 'The bridge designed a local architect.'], 1, 'The simple past passive was designed becomes the simple past active designed.'),
  question('ssc-cgl-t2-en3-019', 'Direct and indirect speech', 'medium', 'Choose the indirect form of: Mohan said, "I have completed the report."', ['Mohan said that I have completed the report.', 'Mohan says that he completed the report.', 'Mohan said that he had completed the report.', 'Mohan said that he has completed the report.'], 2, 'With the past reporting verb said, have completed changes to had completed and I changes to he.'),
  question('ssc-cgl-t2-en3-020', 'Sentence improvement', 'easy', 'Choose the correct replacement: "Each boys have submitted the form."', ['Each boys submitted the form.', 'Every boys have submitted the form.', 'Each boy have submitted the form.', 'Each boy has submitted the form.'], 3, 'Each takes a singular noun and a singular verb: Each boy has submitted.'),
  question('ssc-cgl-t2-en3-021', 'Sentence parts', 'easy', 'Arrange the parts into a correct sentence: P. after the final inspection; Q. the building; R. was opened to the public.', ['Q-R-P', 'P-Q-R', 'R-P-Q', 'Q-P-R'], 0, 'The correct sentence is: The building was opened to the public after the final inspection.'),
  question('ssc-cgl-t2-en3-022', 'Sentence ordering', 'medium', 'Arrange the sentences logically. P. The seed absorbs water. Q. Its outer coat then softens. R. A root begins to grow downward. S. Finally, a shoot emerges above the soil.', ['Q-P-R-S', 'P-Q-R-S', 'P-R-Q-S', 'R-P-S-Q'], 1, 'Water absorption begins the process, followed by softening, root growth and then the emerging shoot.'),
  question('ssc-cgl-t2-en3-023', 'Sentence parts', 'medium', 'Choose the correctly ordered sentence.', ['Only understood she after the explanation the rule.', 'She the rule understood only after explanation.', 'She understood the rule only after the explanation.', 'The rule only she after explanation understood.'], 2, 'The third option follows normal subject-verb-object order and places the limiting phrase naturally.'),
  question('ssc-cgl-t2-en3-024', 'Word usage', 'easy', 'Choose the correct word: The committee decided to ___ the revised policy.', ['adapted', 'adaption', 'adapt', 'adopt'], 3, 'Adopt means formally accept or begin using a policy. Adapt means modify.'),
  question('ssc-cgl-t2-en3-025', 'Punctuation', 'easy', 'Which sentence is correctly punctuated?', ['The teacher asked, "Are you ready?"', 'The teacher asked "Are you ready"?', 'The teacher, asked "Are you ready?"', 'The teacher asked; "Are you ready?"'], 0, 'A comma introduces the direct question, and the question mark belongs inside the quotation marks.'),
  question('ssc-cgl-t2-en3-026', 'Cloze passage', 'easy', 'Complete the passage: Reliable public transport ___ traffic pollution.', ['increases', 'reduces', 'ignores', 'measures'], 1, 'Reduces fits the idea that dependable shared transport can lower traffic pollution.'),
  question('ssc-cgl-t2-en3-027', 'Cloze passage', 'easy', 'Complete the passage: Regular cycling also ___ physical fitness.', ['limits', 'prevents', 'improves', 'hides'], 2, 'Improves agrees with the singular subject cycling and fits the meaning.'),
  question('ssc-cgl-t2-en3-028', 'Cloze passage', 'easy', 'Complete the passage: Cities must ___ safe routes for walkers and cyclists.', ['remove', 'delay', 'oppose', 'provide'], 3, 'Provide means make the safe routes available.'),
  question('ssc-cgl-t2-en3-029', 'Cloze passage', 'medium', 'Complete the passage: Together, these measures make daily travel more ___.', ['accessible', 'careless', 'expensive', 'distant'], 0, 'Accessible means easier for people to reach or use, which fits the context.'),
  question('ssc-cgl-t2-en3-030', 'Cloze passage', 'medium', 'Complete the passage: Long-term success depends ___ regular maintenance.', ['at', 'on', 'from', 'by'], 1, 'The verb phrase is depends on.'),
  question('ssc-cgl-t2-en3-031', 'Reading comprehension', 'easy', `${COMMUNITY_RADIO}\n\nWhy were official bulletins translated into local languages?`, ['To change their scientific meaning', 'To replace evacuation drills', 'To help warnings reach residents in familiar language', 'To prevent fishers from sharing observations'], 2, 'The translations made official warnings easier for local residents to receive and understand.'),
  question('ssc-cgl-t2-en3-032', 'Reading comprehension', 'easy', `${COMMUNITY_RADIO}\n\nWhat did the radio network explicitly avoid doing?`, ['Training volunteers', 'Broadcasting at fixed times', 'Sharing official bulletins', 'Replacing forecasts and warnings from official agencies'], 3, 'The passage states that the network relayed rather than replaced official warnings and forecasts.'),
  question('ssc-cgl-t2-en3-033', 'Reading comprehension', 'medium', `${COMMUNITY_RADIO}\n\nWhich description best fits the network?`, ['Collaborative and practical', 'Secretive and unplanned', 'Commercial and entertainment-focused', 'Independent of all official information'], 0, 'It combined trained volunteers, community observations, official information and regular drills for a practical purpose.'),
  question('ssc-cgl-t2-en3-034', 'Reading comprehension', 'easy', `${COMMUNITY_RADIO}\n\nWhat did residents learn during the drills?`, ['How to forecast every storm', 'Evacuation routes and shelter locations', 'How to repair radio transmitters', 'Where to sell fishing equipment'], 1, 'The passage directly links the drills to learning evacuation routes and shelter locations.'),
  question('ssc-cgl-t2-en3-035', 'Reading comprehension', 'medium', `${COMMUNITY_RADIO}\n\nWhich inference is best supported by the passage?`, ['Community reports should replace scientific forecasts.', 'Warnings are useful only when broadcast nationally.', 'Local participation can improve the last-mile delivery of official warnings.', 'Storm drills are unnecessary when a radio station exists.'], 2, 'The network made official information faster and easier to understand through local participation.'),
  question('ssc-cgl-t2-en3-036', 'Reading comprehension', 'medium', `${CROP_ROTATION}\n\nWhat is the main idea of the passage?`, ['Millets always produce the highest return.', 'Farmers should abandon market information.', 'One crop is safest under every condition.', 'Locally tested crop rotation can improve resilience over time.'], 3, 'The passage describes a measured, local trial whose longer-term results improved resilience and reduced some inputs.'),
  question('ssc-cgl-t2-en3-037', 'Reading comprehension', 'easy', `${CROP_ROTATION}\n\nWhich word is closest in meaning to "resilient" in this context?`, ['Able to withstand and recover', 'Expensive to operate', 'Quick to disappear', 'Unwilling to change'], 0, 'Resilient describes the ability to withstand difficult conditions and recover.'),
  question('ssc-cgl-t2-en3-038', 'Reading comprehension', 'medium', `${CROP_ROTATION}\n\nWhy did the cooperative record yields, rainfall and input expenses?`, ['To avoid comparing the plots', 'To evaluate results using several relevant measures', 'To guarantee success in the first season', 'To prescribe one crop to every farmer'], 1, 'Recording several measures allowed the cooperative to compare outcomes and costs across conditions.'),
  question('ssc-cgl-t2-en3-039', 'Reading comprehension', 'easy', `${CROP_ROTATION}\n\nWhich problem was linked to repeatedly planting one crop?`, ['Lower familiarity with cultivation', 'Immediate loss in every season', 'Pest attacks and declining soil quality', 'Excessive rainfall in all fields'], 2, 'The passage identifies repeated pest attacks and declining soil quality as growing problems.'),
  question('ssc-cgl-t2-en3-040', 'Reading comprehension', 'medium', `${CROP_ROTATION}\n\nWhich conclusion best reflects the passage?`, ['One season is enough to judge every farming method.', 'Local conditions should be ignored when following evidence.', 'Every farm should use an identical rotation.', 'Long-term evidence should be adapted to local soil, water and markets.'], 3, 'The cooperative used multi-year evidence but asked farmers to adapt it to their own conditions.'),
  question('ssc-cgl-t2-en3-041', 'Reading comprehension', 'medium', `${BUS_FARE_PILOT}\n\nWhat is the central idea of the passage?`, ['A pilot can improve a digital service while preserving non-digital access.', 'Paper passes should be removed immediately.', 'Smartphone users were the only passengers consulted.', 'The authority had already completed a citywide launch.'], 0, 'The authority tested a digital option, retained alternatives and planned revision based on evidence.'),
  question('ssc-cgl-t2-en3-042', 'Reading comprehension', 'easy', `${BUS_FARE_PILOT}\n\nWho experienced difficulty with the mobile application?`, ['Only conductors', 'Some older passengers and people without reliable internet', 'Every smartphone user', 'Only staff at ticket counters'], 1, 'The passage directly identifies those two groups as finding the change confusing.'),
  question('ssc-cgl-t2-en3-043', 'Reading comprehension', 'easy', `${BUS_FARE_PILOT}\n\nWhy were conductors trained?`, ['To stop accepting all fares', 'To remove staffed counters', 'To explain both available payment methods', 'To shorten the pilot to one month'], 2, 'Conductors were trained so they could help passengers understand both payment options.'),
  question('ssc-cgl-t2-en3-044', 'Reading comprehension', 'medium', `${BUS_FARE_PILOT}\n\nWhat did the authority plan to do before a wider launch?`, ['Ignore passenger feedback', 'End all data collection', 'Make the pilot permanent without review', 'Revise the system using pilot evidence'], 3, 'The passage says the system would be revised after analysing data and passenger feedback.'),
  question('ssc-cgl-t2-en3-045', 'Reading comprehension', 'medium', `${BUS_FARE_PILOT}\n\nWhich word best describes the authority\'s approach?`, ['Inclusive and evidence-based', 'Rigid and hurried', 'Secretive and punitive', 'Indifferent to access'], 0, 'The authority retained choice, trained staff, gathered evidence and planned revisions.'),
];
