import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SSC Phase XIV/2026 Selection Posts official notification, Higher Secondary-level CBE syllabus',
  url: 'https://ssc.gov.in/api/attachment/uploads/masterData/NoticeBoards/Notice_of_RHQ_2026_phase_xiv.pdf',
  checkedOn: '9 August 2026',
};

type Difficulty = 'easy' | 'medium' | 'hard';
type Row = [section: string, topic: string, difficulty: Difficulty, question: string, answer: string, distractors: [string, string, string], explanation: string];

const rows: Row[] = [
  ['General Intelligence', 'Number series', 'medium', 'Complete the series: 11, 18, 32, 53, 81, ?', '116', ['109', '114', '118'], 'The differences are 7, 14, 21, 28 and then 35; 81 + 35 = 116.'],
  ['General Intelligence', 'Letter analogy', 'medium', 'ACE is related to BDF. In the same way, MOQ is related to what?', 'NPR', ['NQR', 'OPR', 'NPQ'], 'Each letter moves one position forward: M-N, O-P and Q-R.'],
  ['General Intelligence', 'Classification', 'easy', 'Which word is unlike the others: Inch, Kilogram, Metre, Centimetre?', 'Kilogram', ['Inch', 'Metre', 'Centimetre'], 'Kilogram measures mass; the others measure length.'],
  ['General Intelligence', 'Coding-decoding', 'medium', 'If letters are moved alternately one place forward and one place backward, how does PLAN become?', 'QKBM', ['QMBM', 'OKZM', 'QKBO'], 'P+1=Q, L-1=K, A+1=B and N-1=M.'],
  ['General Intelligence', 'Blood relations', 'medium', 'A woman says, "His mother is the only daughter of my mother." How is the man related to the woman?', 'Son', ['Brother', 'Nephew', 'Father'], 'The only daughter of the woman\'s mother is the woman herself, so the man is her son.'],
  ['General Intelligence', 'Direction sense', 'medium', 'Karan walks 5 km east, 4 km south, then 5 km west. Where is he from the starting point?', '4 km south', ['4 km north', '5 km east', '5 km west'], 'The east and west movements cancel, leaving 4 km south.'],
  ['General Intelligence', 'Ranking', 'medium', 'In a class of 42, Dev ranks 17th from the top. What is his rank from the bottom?', '26th', ['24th', '25th', '27th'], 'Rank from bottom = 42 - 17 + 1 = 26.'],
  ['General Intelligence', 'Syllogism', 'hard', 'Statements: Some books are journals. No journal is a newspaper. Which conclusion must follow?', 'Some books are not newspapers', ['No book is a newspaper', 'All books are journals', 'Some newspapers are books'], 'The books that are journals cannot be newspapers.'],
  ['General Intelligence', 'Venn diagram', 'medium', 'Which relation best fits Women doctors, Doctors and Medical professionals?', 'Women doctors are within Doctors, and Doctors are within Medical professionals', ['All medical professionals are women doctors', 'Doctors and medical professionals do not overlap', 'Women doctors are outside Doctors'], 'Every woman doctor is a doctor, and every doctor is a medical professional.'],
  ['General Intelligence', 'Number analogy', 'medium', '15 : 240 :: 12 : ?', '156', ['132', '144', '168'], 'The relation is n x (n + 1): 15 x 16 = 240 and 12 x 13 = 156.'],
  ['General Intelligence', 'Alphabet arrangement', 'medium', 'If the letters of COMPUTER are arranged alphabetically, which letter is fifth?', 'P', ['M', 'O', 'R'], 'Alphabetical order is C, E, M, O, P, R, T, U; the fifth letter is P.'],
  ['General Intelligence', 'Calendar', 'medium', 'A 31-day month begins on Thursday. On which day does the next month begin?', 'Sunday', ['Friday', 'Saturday', 'Monday'], '31 leaves a remainder of 3 on division by 7, so Thursday advances to Sunday.'],
  ['General Intelligence', 'Statement and assumption', 'hard', 'Statement: "Carry an umbrella; the forecast predicts rain." Which assumption is implicit?', 'An umbrella can provide protection from rain', ['Forecasts are always wrong', 'Rain occurs only at night', 'Umbrellas cause rain'], 'The advice assumes an umbrella is useful if it rains.'],
  ['General Intelligence', 'Word formation', 'easy', 'Which word can be formed from ADMINISTRATION without repeating a letter more often than available?', 'TRAIN', ['MOTIONED', 'STATIONARY', 'DRAINING'], 'TRAIN uses letters that are all available in ADMINISTRATION.'],
  ['General Intelligence', 'Mathematical operations', 'medium', 'If @ means addition and # means multiplication, what is 6 # 4 @ 3?', '27', ['42', '36', '21'], 'Replace the symbols: 6 x 4 + 3 = 27.'],
  ['General Intelligence', 'Seating arrangement', 'medium', 'Five people P, Q, R, S and T sit in a row. R is in the middle, P is immediately left of R, and T is at the right end. Who sits second from the left?', 'P', ['Q', 'S', 'T'], 'R is third, so P is immediately left in the second position.'],
  ['General Intelligence', 'Number series', 'medium', 'Find the missing term: 3, 8, 18, 38, ?, 158.', '78', ['68', '76', '80'], 'Each term is previous term x 2 + 2.'],
  ['General Intelligence', 'Mirror reasoning', 'medium', 'A clock shows 2:35. What time would its mirror image show?', '9:25', ['8:25', '9:35', '10:25'], 'Mirror time on a 12-hour clock is 11:60 - 2:35 = 9:25.'],
  ['General Intelligence', 'Logical order', 'easy', 'Arrange these stages logically: Seed, Fruit, Flower, Plant.', 'Seed, Plant, Flower, Fruit', ['Plant, Seed, Fruit, Flower', 'Flower, Seed, Plant, Fruit', 'Seed, Flower, Plant, Fruit'], 'A seed grows into a plant, which flowers and then bears fruit.'],
  ['General Intelligence', 'Decision making', 'medium', 'You find an unattended identity card in an examination centre. What is the most appropriate action?', 'Hand it to the authorised centre staff', ['Keep it for later', 'Post its details publicly', 'Leave it where it is'], 'Authorised staff can securely identify and return the card.'],
  ['General Intelligence', 'Data sufficiency', 'hard', 'What is x? I: x is an even number. II: x is greater than 6 but less than 10.', 'Both statements together are sufficient', ['Statement I alone is sufficient', 'Statement II alone is sufficient', 'Even together they are insufficient'], 'Together the statements identify the only even integer between 6 and 10: x = 8.'],
  ['General Intelligence', 'Analogy', 'easy', 'Island is to Ocean as Oasis is to what?', 'Desert', ['Forest', 'River', 'Mountain'], 'An island lies in an ocean, and an oasis lies in a desert.'],
  ['General Intelligence', 'Embedded relation', 'medium', 'All squares are rectangles, but not all rectangles are squares. Which statement is true?', 'Every square has four right angles', ['Every rectangle has four equal sides', 'No square is a rectangle', 'Some squares have three sides'], 'A square is a rectangle with four right angles and equal sides.'],
  ['General Intelligence', 'Age reasoning', 'medium', 'Five years ago, Mira was twice Rohan\'s age. Mira is now 25. How old is Rohan now?', '15', ['10', '12', '20'], 'Five years ago Mira was 20, so Rohan was 10 then and is 15 now.'],
  ['General Intelligence', 'Symbol sequence', 'medium', 'Complete the pattern: A1, C4, F9, J16, ?', 'O25', ['N20', 'O20', 'P25'], 'Letter gaps are +2, +3, +4, +5, while numbers are consecutive squares.'],

  ['General Awareness', 'Constitution', 'medium', 'Which Article abolishes untouchability?', 'Article 17', ['Article 14', 'Article 19', 'Article 21'], 'Article 17 abolishes untouchability.'],
  ['General Awareness', 'History', 'medium', 'Identify the year in which the Battle of Plassey took place.', '1757', ['1761', '1764', '1773'], 'The Battle of Plassey took place in 1757.'],
  ['General Awareness', 'Geography', 'easy', 'Among Indian states, which one has the greatest coastline length?', 'Gujarat', ['Odisha', 'Tamil Nadu', 'Andhra Pradesh'], 'Gujarat has the longest coastline among Indian states.'],
  ['General Awareness', 'Biology', 'medium', 'Which part of a cell contains genetic material in most eukaryotes?', 'Nucleus', ['Ribosome', 'Vacuole', 'Cell wall'], 'Most eukaryotic DNA is housed in the nucleus.'],
  ['General Awareness', 'Economics', 'medium', 'Inflation refers to what?', 'A sustained rise in the general price level', ['A fall in total population', 'A rise in rainfall', 'A reduction in money supply only'], 'Inflation is a broad and sustained increase in prices.'],
  ['General Awareness', 'Physics', 'medium', 'Which law states that every action has an equal and opposite reaction?', 'Newton\'s third law', ['Newton\'s first law', 'Ohm\'s law', 'Boyle\'s law'], 'This is Newton\'s third law of motion.'],
  ['General Awareness', 'Culture', 'easy', 'Kathakali is a classical dance form associated with which state?', 'Kerala', ['Assam', 'Rajasthan', 'Odisha'], 'Kathakali developed in Kerala.'],
  ['General Awareness', 'Indian polity', 'medium', 'The constitutional appointment of India\'s Comptroller and Auditor General is made by whom?', 'The President of India', ['The Prime Minister alone', 'The Chief Justice of India', 'The Speaker of Lok Sabha'], 'The President appoints the CAG under the Constitution.'],
  ['General Awareness', 'Chemistry', 'easy', 'Which metal is liquid at ordinary room temperature?', 'Mercury', ['Aluminium', 'Copper', 'Iron'], 'Mercury is liquid at ordinary room temperature.'],
  ['General Awareness', 'Geography', 'medium', 'Count the Indian states crossed by the Tropic of Cancer.', '8', ['6', '7', '9'], 'The Tropic of Cancer passes through eight Indian states.'],
  ['General Awareness', 'History', 'medium', 'Who introduced the Permanent Settlement in Bengal?', 'Lord Cornwallis', ['Lord Curzon', 'Lord Ripon', 'Lord Dalhousie'], 'Lord Cornwallis introduced the Permanent Settlement in 1793.'],
  ['General Awareness', 'Environment', 'easy', 'Which gas is the largest contributor to the natural greenhouse effect?', 'Water vapour', ['Oxygen', 'Argon', 'Neon'], 'Water vapour contributes most to Earth\'s natural greenhouse effect.'],
  ['General Awareness', 'Space', 'medium', 'Which planet has the shortest orbital period around the Sun?', 'Mercury', ['Venus', 'Earth', 'Mars'], 'Mercury completes an orbit in about 88 Earth days.'],
  ['General Awareness', 'Sports', 'easy', 'In cricket, how many legal balls make one over?', '6', ['5', '7', '8'], 'A standard cricket over contains six legal deliveries.'],
  ['General Awareness', 'Constitution', 'medium', 'The Directive Principles of State Policy were inspired mainly by the Constitution of which country?', 'Ireland', ['United States', 'Canada', 'France'], 'India drew the Directive Principles largely from the Irish Constitution.'],
  ['General Awareness', 'Biology', 'medium', 'Which blood cells primarily fight infection?', 'White blood cells', ['Red blood cells', 'Platelets', 'Plasma only'], 'White blood cells form a major part of immune defence.'],
  ['General Awareness', 'Institutions', 'medium', 'Which organisation publishes India\'s national income estimates?', 'National Statistical Office', ['Election Commission of India', 'Finance Commission', 'Central Vigilance Commission'], 'The National Statistical Office compiles national income estimates.'],
  ['General Awareness', 'Literature', 'easy', 'Who wrote Gitanjali?', 'Rabindranath Tagore', ['Premchand', 'Mulk Raj Anand', 'R. K. Narayan'], 'Rabindranath Tagore wrote Gitanjali.'],
  ['General Awareness', 'Geography', 'medium', 'Which soil is especially suitable for cotton cultivation?', 'Black soil', ['Laterite soil', 'Desert soil', 'Mountain soil'], 'Black soil retains moisture and is well suited to cotton.'],
  ['General Awareness', 'Physics', 'medium', 'Power is expressed in which SI unit?', 'Watt', ['Joule', 'Pascal', 'Newton'], 'Power is measured in watts.'],
  ['General Awareness', 'Freedom movement', 'medium', 'In which year did the Indian National Congress launch the Quit India Movement?', '1942', ['1930', '1935', '1946'], 'The Quit India Movement began in August 1942.'],
  ['General Awareness', 'Chemistry', 'medium', 'Which element has atomic number 6?', 'Carbon', ['Boron', 'Nitrogen', 'Oxygen'], 'Carbon has six protons and atomic number 6.'],
  ['General Awareness', 'Neighbouring countries', 'easy', 'What is the capital of Bhutan?', 'Thimphu', ['Kathmandu', 'Dhaka', 'Male'], 'Thimphu is the capital of Bhutan.'],
  ['General Awareness', 'Government', 'medium', 'A Money Bill can be introduced only in which House of Parliament?', 'Lok Sabha', ['Rajya Sabha', 'Either House', 'A joint sitting only'], 'A Money Bill can originate only in the Lok Sabha.'],
  ['General Awareness', 'Agriculture', 'medium', 'Which irrigation method supplies water directly near plant roots through pipes or tubes?', 'Drip irrigation', ['Canal irrigation', 'Tank irrigation', 'Flood irrigation'], 'Drip irrigation delivers small amounts of water close to roots.'],

  ['Quantitative Aptitude', 'Simplification', 'easy', 'Evaluate 48 divided by 6 + 7 x 3.', '29', ['25', '27', '31'], 'Division and multiplication first give 8 + 21 = 29.'],
  ['Quantitative Aptitude', 'Percentage', 'medium', 'A number is increased by 20% and becomes 540. What was the original number?', '450', ['420', '432', '480'], 'The original is 540/1.20 = 450.'],
  ['Quantitative Aptitude', 'Ratio', 'medium', 'Divide Rs 1,260 in the ratio 2:3:4. What is the largest share?', 'Rs 560', ['Rs 420', 'Rs 480', 'Rs 600'], 'Nine parts equal Rs 1,260, so four parts equal Rs 560.'],
  ['Quantitative Aptitude', 'Average', 'medium', 'The average of six numbers is 28. If five total 130, what is the sixth number?', '38', ['34', '36', '40'], 'All six total 168; 168 - 130 = 38.'],
  ['Quantitative Aptitude', 'Profit and loss', 'medium', 'An item is sold for Rs 816 at a 15% loss. Find its cost price.', 'Rs 960', ['Rs 900', 'Rs 940', 'Rs 980'], 'Selling price is 85% of cost, so cost = 816/0.85 = Rs 960.'],
  ['Quantitative Aptitude', 'Compound interest', 'medium', 'Find the amount on Rs 5,000 at 10% compound interest for 2 years.', 'Rs 6,050', ['Rs 5,950', 'Rs 6,000', 'Rs 6,100'], 'Amount = 5000 x 1.1 squared = Rs 6,050.'],
  ['Quantitative Aptitude', 'Time and work', 'medium', 'A completes a task in 15 days. After working alone for 5 days, what fraction remains?', '2/3', ['1/3', '1/2', '3/5'], 'A completes 5/15 = 1/3, leaving 2/3.'],
  ['Quantitative Aptitude', 'Trains', 'medium', 'A 180 m train passes a pole in 12 seconds. What is its speed?', '54 km/h', ['45 km/h', '50 km/h', '60 km/h'], 'Speed = 15 m/s, which equals 54 km/h.'],
  ['Quantitative Aptitude', 'Algebra', 'medium', 'If x + 1/x = 5, find x squared + 1/x squared.', '23', ['21', '25', '27'], 'Square the relation: x squared + 2 + 1/x squared = 25.'],
  ['Quantitative Aptitude', 'Geometry', 'easy', 'A triangle has angles proportional to 2, 3 and 4. Determine its greatest angle.', '80 degrees', ['60 degrees', '70 degrees', '90 degrees'], 'Nine parts equal 180 degrees, so four parts equal 80 degrees.'],
  ['Quantitative Aptitude', 'Mensuration', 'medium', 'Find the area of a circle of radius 7 cm using pi = 22/7.', '154 sq cm', ['144 sq cm', '148 sq cm', '164 sq cm'], 'Area = 22/7 x 7 x 7 = 154 sq cm.'],
  ['Quantitative Aptitude', 'Trigonometry', 'easy', 'What is the value of sin 30 degrees?', '1/2', ['0', '1/sqrt(2)', '1'], 'The standard value of sin 30 degrees is 1/2.'],
  ['Quantitative Aptitude', 'Partnership', 'medium', 'A invests Rs 8,000 for 12 months and B invests Rs 12,000 for 8 months. In what ratio is profit divided?', '1:1', ['2:3', '3:2', '4:3'], 'Both capital-time products equal 96,000.'],
  ['Quantitative Aptitude', 'Mixture', 'medium', 'How much water must be added to 30 L of milk to make the milk-water ratio 3:1?', '10 L', ['8 L', '12 L', '15 L'], 'If milk is three parts or 30 L, one part of water is 10 L.'],
  ['Quantitative Aptitude', 'Linear equations', 'medium', 'Solve: 3x + 2y = 16 and x + y = 6. Find x.', '4', ['2', '3', '5'], 'From y = 6 - x, substitution gives x = 4.'],
  ['Quantitative Aptitude', 'HCF and LCM', 'medium', 'Two numbers have HCF 6 and LCM 180. If one number is 30, find the other.', '36', ['24', '42', '60'], 'Product of numbers = HCF x LCM, so other = 1080/30 = 36.'],
  ['Quantitative Aptitude', 'Discount', 'medium', 'Two successive discounts of 10% and 20% are equal to what single discount?', '28%', ['26%', '30%', '32%'], 'Net price factor is 0.9 x 0.8 = 0.72, so discount is 28%.'],
  ['Quantitative Aptitude', 'Data interpretation', 'medium', 'A pie chart sector is 72 degrees. What percentage of the total does it represent?', '20%', ['18%', '22%', '25%'], '72/360 x 100 = 20%.'],
  ['Quantitative Aptitude', 'Surds', 'medium', 'Simplify sqrt(72).', '6sqrt(2)', ['4sqrt(3)', '8sqrt(2)', '12sqrt(2)'], 'sqrt(72) = sqrt(36 x 2) = 6sqrt(2).'],
  ['Quantitative Aptitude', 'Time and distance', 'medium', 'Two cars start 300 km apart and move toward each other at 70 and 80 km/h. When do they meet?', '2 hours', ['1.5 hours', '2.5 hours', '3 hours'], 'Relative speed is 150 km/h, so time = 300/150 = 2 hours.'],
  ['Quantitative Aptitude', 'Cylinder', 'hard', 'Find the curved surface area of a cylinder with radius 3.5 cm and height 10 cm using pi = 22/7.', '220 sq cm', ['110 sq cm', '210 sq cm', '240 sq cm'], 'Curved area = 2 x 22/7 x 3.5 x 10 = 220 sq cm.'],
  ['Quantitative Aptitude', 'Statistics', 'medium', 'Find the median of 7, 12, 5, 18, 9.', '9', ['7', '10', '12'], 'Ordered values are 5, 7, 9, 12, 18; the middle is 9.'],
  ['Quantitative Aptitude', 'Pipes', 'hard', 'One pipe fills a tank in 12 hours and another in 18 hours. What fraction is filled in 4 hours together?', '5/9', ['4/9', '2/3', '7/9'], 'Four hours at rate 1/12 + 1/18 = 5/36 fills 20/36 = 5/9.'],
  ['Quantitative Aptitude', 'Coordinate geometry', 'medium', 'What is the distance between (2, 3) and (2, 11)?', '8 units', ['6 units', '7 units', '9 units'], 'The x-coordinates match, so distance is 11 - 3 = 8.'],
  ['Quantitative Aptitude', 'Remainders', 'medium', 'What is the remainder when 3 to the power 5 is divided by 7?', '5', ['3', '4', '6'], '3 to the power 5 is 243, and 243 leaves remainder 5 on division by 7.'],

  ['English Language', 'Error spotting', 'medium', 'Which part contains the error: Neither the manager / nor the assistants / was available / at noon?', 'was available', ['Neither the manager', 'nor the assistants', 'at noon'], 'The verb agrees with the nearer plural subject: were available.'],
  ['English Language', 'Synonym', 'medium', "Choose the synonym of 'abrupt'.", 'Sudden', ['Gradual', 'Polite', 'Distant'], 'Abrupt means sudden or unexpected.'],
  ['English Language', 'Antonym', 'medium', "Select the antonym of 'scarce'.", 'Abundant', ['Rare', 'Limited', 'Insufficient'], 'Abundant is opposite to scarce.'],
  ['English Language', 'Spelling', 'easy', 'Select the standard spelling of the word meaning upkeep.', 'Maintenance', ['Maintainance', 'Maintenence', 'Maintanance'], 'Maintenance is the correct spelling.'],
  ['English Language', 'Idiom', 'medium', "What does 'hit the nail on the head' mean?", 'State something exactly right', ['Damage a tool', 'Work very slowly', 'Avoid the main issue'], 'The idiom means identifying or stating the exact point.'],
  ['English Language', 'One-word substitution', 'medium', 'What is a person who studies plants called?', 'Botanist', ['Geologist', 'Zoologist', 'Physicist'], 'A botanist studies plants.'],
  ['English Language', 'Voice', 'medium', "Choose the passive form of 'They will announce the result tomorrow.'", 'The result will be announced tomorrow.', ['The result is announced tomorrow.', 'The result was announced tomorrow.', 'Tomorrow will announce the result.'], 'Future simple passive uses will be plus past participle.'],
  ['English Language', 'Narration', 'medium', "Report the request: She said to me, 'Please open the window.'", 'She requested me to open the window.', ['She said me open the window.', 'She requested that I opened the window.', 'She asks me that open the window.'], 'A polite imperative is reported with requested plus object plus infinitive.'],
  ['English Language', 'Fill in the blank', 'easy', 'The committee has not arrived ___ a decision.', 'at', ['on to', 'for', 'with'], 'The fixed expression is arrive at a decision.'],
  ['English Language', 'Sentence improvement', 'medium', 'Improve: He is senior than me.', 'He is senior to me.', ['He is senior from me.', 'He is more senior than me.', 'No improvement'], 'Senior takes the preposition to, not than.'],
  ['English Language', 'Cloze', 'medium', 'Complete logically: Regular practice ___ confidence and reduces hesitation.', 'builds', ['breaks', 'borrows', 'divides'], 'Builds correctly expresses development of confidence.'],
  ['English Language', 'Homonym', 'medium', 'Choose the correct word: The new rule will ___ all applicants.', 'affect', ['effect', 'affecting on', 'effectuate to'], 'Affect is the verb meaning influence.'],
  ['English Language', 'Para-jumble', 'hard', 'Arrange logically: P: the alarm sounded; Q: everyone left calmly; R: the drill began; S: through the marked exits.', 'R-P-Q-S', ['P-R-S-Q', 'Q-S-R-P', 'R-Q-P-S'], 'The drill begins, the alarm sounds, and everyone leaves through the exits.'],
  ['English Language', 'Preposition', 'easy', 'The report is divided ___ four sections.', 'into', ['among', 'between', 'by'], 'Divide into is used for parts of a whole.'],
  ['English Language', 'Tense', 'medium', 'When I reached the station, the train ___.', 'had left', ['has left', 'leaves', 'will leave'], 'The train left before the later past action, so past perfect is used.'],
  ['English Language', 'Conditional', 'medium', 'If you had informed me, I ___ helped you.', 'would have', ['will have', 'would', 'had'], 'A third conditional uses would have plus past participle.'],
  ['English Language', 'Comprehension', 'medium', 'A circular states that applications received after 5 p.m. will not be accepted. What happens to an application received at 5:10 p.m.?', 'It is not accepted', ['It is accepted normally', 'It is accepted with priority', 'It is automatically corrected'], 'The circular excludes every application received after 5 p.m.'],
  ['English Language', 'Vocabulary', 'medium', "In the phrase 'a feasible plan', what does feasible mean?", 'Practical and possible', ['Expensive and risky', 'Secret and complex', 'Final and compulsory'], 'Feasible means capable of being done.'],
  ['English Language', 'Subject-verb agreement', 'medium', 'Which sentence correctly agrees with the singular subject "quality"?', 'The quality of these products is improving.', ['The quality of these products are improving.', 'The quality of this products is improving.', 'The qualities of these products is improving.'], 'The head subject quality is singular and takes is.'],
  ['English Language', 'Phrasal verb', 'medium', "What does 'look into the complaint' mean?", 'Investigate the complaint', ['Ignore the complaint', 'Copy the complaint', 'Withdraw the complaint'], 'Look into means investigate.'],
  ['English Language', 'Antonym', 'easy', "Choose the opposite of 'transparent'.", 'Opaque', ['Visible', 'Clear', 'Plain'], 'Opaque does not allow light through and is the opposite of transparent.'],
  ['English Language', 'Grammar', 'medium', 'Choose the correct form: It is time we ___ home.', 'went', ['go', 'will go', 'have go'], 'After it is time, a past form commonly expresses present necessity.'],
  ['English Language', 'Punctuation', 'easy', 'Which sentence uses the apostrophe correctly?', "The students' books were collected.", ["The student's books were collected from all of them.", 'The students books were collected.', "The studentss' books were collected."], 'The plural possessive of students places the apostrophe after s.'],
  ['English Language', 'Sentence transformation', 'medium', 'Choose the correct transformation: As soon as the gate opened, the crowd entered.', 'No sooner did the gate open than the crowd entered.', ['No sooner the gate opened when the crowd entered.', 'No sooner did the gate opened than the crowd entered.', 'No sooner had the gate open when the crowd entered.'], 'No sooner takes inversion and than.'],
  ['English Language', 'Reading inference', 'hard', 'A report says output rose despite fewer working hours because equipment was upgraded. What caused the higher output?', 'Improved equipment', ['Longer working hours', 'More employees', 'Lower demand'], 'The report directly attributes the rise to upgraded equipment.'],
];

function placeAnswer(answer: string, distractors: [string, string, string], index: number) {
  const options = [...distractors];
  options.splice(index, 0, answer);
  return options;
}

export const SSC_SELECTION_POST_HIGHER_SECONDARY_CBE_1: Question[] = rows.map(
  ([section, topic, difficulty, question, answer, distractors, explanation], index) => ({
    id: `ssc-sp-hs-${String(index + 1).padStart(3, '0')}`,
    section,
    topic,
    difficulty,
    question,
    options: placeAnswer(answer, distractors, index % 4),
    correctIndex: index % 4,
    explanation,
    source,
  }),
);
