import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SSC MTS & Havaldar (CBIC & CBN) Examination 2025 official scheme, Session 2 — English Language and Comprehension section',
  url: 'https://ssc.gov.in/api/attachment/uploads/masterData/NoticeBoards/writeup_mts_03082026.pdf',
  checkedOn: '22 August 2026',
};

export const SSC_MTS_CBT_ENGLISH_LANGUAGE_COMPREHENSION_2: Question[] = [
  { id: 'ssc-mts-cbt-en2-001', section: 'English Language and Comprehension', topic: 'Synonym', difficulty: 'easy', question: 'Choose the word closest in meaning to "brave".', options: ['Courageous', 'Timid', 'Weak', 'Fearful'], correctIndex: 0, negativeMarking: 1, explanation: '"Brave" means showing courage; "Courageous" is the closest synonym.', source },
  { id: 'ssc-mts-cbt-en2-002', section: 'English Language and Comprehension', topic: 'Synonym', difficulty: 'easy', question: 'Choose the word closest in meaning to "huge".', options: ['Tiny', 'Enormous', 'Small', 'Narrow'], correctIndex: 1, negativeMarking: 1, explanation: '"Huge" means very large; "Enormous" is the closest synonym.', source },
  { id: 'ssc-mts-cbt-en2-003', section: 'English Language and Comprehension', topic: 'Synonym', difficulty: 'medium', question: 'Choose the word closest in meaning to "genuine".', options: ['Authentic', 'Fake', 'False', 'Artificial'], correctIndex: 0, negativeMarking: 1, explanation: '"Genuine" means real or authentic; "Authentic" is the closest synonym.', source },
  { id: 'ssc-mts-cbt-en2-004', section: 'English Language and Comprehension', topic: 'Synonym', difficulty: 'medium', question: 'Choose the word closest in meaning to "diligent".', options: ['Lazy', 'Careless', 'Slow', 'Hardworking'], correctIndex: 3, negativeMarking: 1, explanation: '"Diligent" means showing care and effort; "Hardworking" is the closest synonym.', source },
  { id: 'ssc-mts-cbt-en2-005', section: 'English Language and Comprehension', topic: 'Antonym', difficulty: 'easy', question: 'Choose the word most opposite in meaning to "ancient".', options: ['Old', 'Historic', 'Modern', 'Aged'], correctIndex: 2, negativeMarking: 1, explanation: '"Ancient" means very old, the opposite of which is "Modern".', source },
  { id: 'ssc-mts-cbt-en2-006', section: 'English Language and Comprehension', topic: 'Antonym', difficulty: 'easy', question: 'Choose the word most opposite in meaning to "generous".', options: ['Kind', 'Stingy', 'Giving', 'Charitable'], correctIndex: 1, negativeMarking: 1, explanation: '"Generous" means willing to give freely, the opposite of which is "Stingy".', source },
  { id: 'ssc-mts-cbt-en2-007', section: 'English Language and Comprehension', topic: 'Antonym', difficulty: 'medium', question: 'Choose the word most opposite in meaning to "abundant".', options: ['Scarce', 'Plentiful', 'Ample', 'Rich'], correctIndex: 0, negativeMarking: 1, explanation: '"Abundant" means existing in large quantities, the opposite of which is "Scarce".', source },
  { id: 'ssc-mts-cbt-en2-008', section: 'English Language and Comprehension', topic: 'Antonym', difficulty: 'medium', question: 'Choose the word most opposite in meaning to "victory".', options: ['Triumph', 'Success', 'Win', 'Defeat'], correctIndex: 3, negativeMarking: 1, explanation: '"Victory" means success in a contest, the opposite of which is "Defeat".', source },
  { id: 'ssc-mts-cbt-en2-009', section: 'English Language and Comprehension', topic: 'Spelling', difficulty: 'easy', question: 'Choose the correctly spelled word.', options: ['Definately', 'Definitly', 'Definitely', 'Definetly'], correctIndex: 2, negativeMarking: 1, explanation: '"Definitely" is the correct spelling.', source },
  { id: 'ssc-mts-cbt-en2-010', section: 'English Language and Comprehension', topic: 'Spelling', difficulty: 'medium', question: 'Identify the correctly spelled word.', options: ['Occassion', 'Occasion', 'Ocasion', 'Ocassion'], correctIndex: 1, negativeMarking: 1, explanation: '"Occasion" is the correct spelling, with a double "c" and single "s".', source },
  { id: 'ssc-mts-cbt-en2-011', section: 'English Language and Comprehension', topic: 'Spelling', difficulty: 'medium', question: 'Select the correctly spelled word.', options: ['Necessary', 'Neccessary', 'Necesary', 'Neccesary'], correctIndex: 0, negativeMarking: 1, explanation: '"Necessary" is the correct spelling, with a single "c" and double "s".', source },
  { id: 'ssc-mts-cbt-en2-012', section: 'English Language and Comprehension', topic: 'Articles', difficulty: 'easy', question: 'Choose the correct article: ___ honest man is respected by all.', options: ['A', 'The', 'No article needed', 'An'], correctIndex: 3, negativeMarking: 1, explanation: '"Honest" begins with a silent "h", so it is pronounced with a vowel sound, requiring the article "An".', source },
  { id: 'ssc-mts-cbt-en2-013', section: 'English Language and Comprehension', topic: 'Articles', difficulty: 'medium', question: 'Choose the correct article: She is ___ best student in the class.', options: ['a', 'an', 'the', 'no article needed'], correctIndex: 2, negativeMarking: 1, explanation: 'Superlative adjectives like "best" are typically preceded by the definite article "the".', source },
  { id: 'ssc-mts-cbt-en2-014', section: 'English Language and Comprehension', topic: 'Preposition', difficulty: 'easy', question: 'Choose the correct preposition: The book is ___ the table.', options: ['at', 'on', 'into', 'by'], correctIndex: 1, negativeMarking: 1, explanation: '"On" is the correct preposition to show that the book is resting on the surface of the table.', source },
  { id: 'ssc-mts-cbt-en2-015', section: 'English Language and Comprehension', topic: 'Preposition', difficulty: 'medium', question: 'Choose the correct preposition: He has been working here ___ 2018.', options: ['since', 'for', 'from', 'at'], correctIndex: 0, negativeMarking: 1, explanation: '"Since" is used with a specific point in time (2018) to indicate the start of a continuing action.', source },
  { id: 'ssc-mts-cbt-en2-016', section: 'English Language and Comprehension', topic: 'Tense', difficulty: 'easy', question: 'Choose the correct form of the verb: She ___ to school every day.', options: ['go', 'going', 'gone', 'goes'], correctIndex: 3, negativeMarking: 1, explanation: 'For a third-person singular subject ("She") in the simple present tense, the verb takes an "-s/-es" ending: "goes".', source },
  { id: 'ssc-mts-cbt-en2-017', section: 'English Language and Comprehension', topic: 'Tense', difficulty: 'medium', question: 'Choose the correct form of the verb: By next year, he ___ his degree.', options: ['will complete', 'completes', 'will have completed', 'is completing'], correctIndex: 2, negativeMarking: 1, explanation: '"By next year" indicates an action that will be completed before a future point, requiring the future perfect tense: "will have completed".', source },
  { id: 'ssc-mts-cbt-en2-018', section: 'English Language and Comprehension', topic: 'Idioms', difficulty: 'medium', question: 'Choose the meaning of the idiom "to hit the nail on the head".', options: ['To make a mistake', 'To say something exactly right', 'To hurt someone', 'To finish a task quickly'], correctIndex: 1, negativeMarking: 1, explanation: '"To hit the nail on the head" means to say or do something exactly right.', source },
  { id: 'ssc-mts-cbt-en2-019', section: 'English Language and Comprehension', topic: 'Idioms', difficulty: 'medium', question: 'Choose the meaning of the idiom "to burn the midnight oil".', options: ['To work or study late into the night', 'To waste time', 'To cause a fire', 'To relax completely'], correctIndex: 0, negativeMarking: 1, explanation: '"To burn the midnight oil" means to work or study late into the night.', source },
  { id: 'ssc-mts-cbt-en2-020', section: 'English Language and Comprehension', topic: 'One-word substitution', difficulty: 'medium', question: 'Choose the one word for: "A person who knows everything".', options: ['Scholar', 'Genius', 'Know-all', 'Intellectual'], correctIndex: 2, negativeMarking: 1, explanation: 'A person who claims or appears to know everything is called a "know-all".', source },
  { id: 'ssc-mts-cbt-en2-021', section: 'English Language and Comprehension', topic: 'One-word substitution', difficulty: 'medium', question: 'Choose the one word for: "A person who loves books".', options: ['Philanthropist', 'Bibliographer', 'Bibliophile', 'Librarian'], correctIndex: 2, negativeMarking: 1, explanation: 'A person who loves books is called a "bibliophile".', source },
  { id: 'ssc-mts-cbt-en2-022', section: 'English Language and Comprehension', topic: 'Sentence improvement', difficulty: 'medium', question: 'Improve the underlined part: "He don\'t like to travel alone."', options: ['do not like', 'doesn\'t like', 'not liking', 'No improvement needed'], correctIndex: 1, negativeMarking: 1, explanation: 'For the third-person singular subject "He", the correct negative form is "doesn\'t like", not "don\'t like".', source },
  { id: 'ssc-mts-cbt-en2-023', section: 'English Language and Comprehension', topic: 'Sentence improvement', difficulty: 'medium', question: 'Improve the underlined part: "Neither of the answers were correct."', options: ['was correct', 'were being correct', 'have been correct', 'No improvement needed'], correctIndex: 0, negativeMarking: 1, explanation: '"Neither" is singular and takes a singular verb, so the correct form is "was correct", not "were correct".', source },
  { id: 'ssc-mts-cbt-en2-024', section: 'English Language and Comprehension', topic: 'Cloze test', difficulty: 'medium', question: 'Fill in the blank: Despite the heavy rain, the players continued ___ the match.', options: ['play', 'to played', 'plays', 'playing'], correctIndex: 3, negativeMarking: 1, explanation: '"Continued" is followed by a gerund ("playing") or an infinitive; among the given options, "playing" correctly completes the sentence.', source },
  { id: 'ssc-mts-cbt-en2-025', section: 'English Language and Comprehension', topic: 'Cloze test', difficulty: 'medium', question: 'Fill in the blank: The manager insisted ___ punctuality from all employees.', options: ['at', 'for', 'on', 'with'], correctIndex: 2, negativeMarking: 1, explanation: '"Insist on" is the correct idiomatic verb-preposition combination meaning to demand something firmly.', source },
];
