import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SSC Combined Hindi Translators Examination 2026 official notification, Paper I General English syllabus',
  url: 'https://ssc.gov.in/api/attachment/uploads/masterData/NoticeBoards/Notice_of_adv_cht_2026.pdf',
  checkedOn: '9 August 2026',
};

type Difficulty = 'easy' | 'medium' | 'hard';
type Row = [topic: string, difficulty: Difficulty, question: string, answer: string, distractors: [string, string, string], explanation: string];

const passageA = 'A good translator does not replace words mechanically. The translator first identifies the purpose, tone, and audience of the source text. A legal instruction demands precision, while a public notice must also remain easy to understand. When an exact equivalent is unavailable, the translator chooses an expression that preserves the intended meaning without adding a personal opinion.';
const passageB = 'Digital archives have made government records easier to search, but digitisation alone does not guarantee access. Old documents may contain faded text, inconsistent spelling, or handwritten notes that automated systems cannot read accurately. Human review therefore remains necessary. A carefully checked digital record saves time later because users can trust both the text and its descriptive labels.';

const rows: Row[] = [
  ['Synonym', 'medium', "Which word is closest in meaning to 'assiduous'?", 'Diligent', ['Careless', 'Intermittent', 'Reluctant'], '“Assiduous” means showing persistent care and effort, so “diligent” is the closest synonym.'],
  ['Synonym', 'easy', "Select the synonym of 'lucid'.", 'Clear', ['Cloudy', 'Lengthy', 'Rigid'], '“Lucid” means clear and easy to understand.'],
  ['Synonym', 'medium', "Choose the word nearest in meaning to 'terse'.", 'Concise', ['Polite', 'Ambiguous', 'Elaborate'], '“Terse” means brief and concise in expression.'],
  ['Synonym', 'easy', "What is the closest synonym of 'benign'?", 'Harmless', ['Hostile', 'Severe', 'Uncertain'], '“Benign” means gentle or not harmful.'],
  ['Synonym', 'medium', "Identify a synonym for 'obsolete'.", 'Outdated', ['Current', 'Useful', 'Portable'], 'Something obsolete is no longer in use and is outdated.'],
  ['Synonym', 'medium', "Which option best matches the meaning of 'resilient'?", 'Quick to recover', ['Easy to deceive', 'Hard to notice', 'Slow to respond'], 'A resilient person or system recovers quickly after difficulty.'],
  ['Synonym', 'medium', "Choose the synonym of 'prudent'.", 'Cautious', ['Reckless', 'Noisy', 'Generous'], '“Prudent” means showing careful and sensible judgment.'],
  ['Synonym', 'hard', "Which expression is synonymous with 'sporadic'?", 'Occasional', ['Continuous', 'Predictable', 'Immediate'], '“Sporadic” describes something occurring at irregular or occasional intervals.'],
  ['Synonym', 'hard', "Select the closest meaning of the verb 'corroborate'.", 'Confirm', ['Contradict', 'Conceal', 'Postpone'], 'To corroborate a statement is to confirm it with supporting evidence.'],
  ['Synonym', 'medium', "Which word can replace 'alleviate' without changing its meaning?", 'Relieve', ['Intensify', 'Ignore', 'Measure'], 'To alleviate pain or difficulty is to relieve it.'],
  ['Synonym', 'easy', "Identify the synonym of 'impartial'.", 'Unbiased', ['Indifferent', 'Uncertain', 'Unprepared'], 'An impartial person is fair and unbiased.'],
  ['Synonym', 'hard', "What is the nearest meaning of 'clandestine'?", 'Secret', ['Official', 'Routine', 'Public'], '“Clandestine” means kept secret, often because an activity is unauthorized.'],

  ['Antonym', 'easy', "Choose the antonym of 'explicit'.", 'Vague', ['Direct', 'Definite', 'Clear'], '“Explicit” means clearly stated; “vague” is its opposite.'],
  ['Antonym', 'medium', "Which word is opposite in meaning to 'augment'?", 'Reduce', ['Increase', 'Extend', 'Strengthen'], 'To augment is to increase, while to reduce is to make smaller.'],
  ['Antonym', 'medium', "Select the antonym of 'transient'.", 'Permanent', ['Brief', 'Passing', 'Temporary'], '“Transient” means temporary; “permanent” is the opposite.'],
  ['Antonym', 'medium', "What is the opposite of 'docile'?", 'Defiant', ['Gentle', 'Obedient', 'Submissive'], 'A docile person is easily controlled, while a defiant person resists control.'],
  ['Antonym', 'hard', "Choose the word opposite in meaning to 'meticulous'.", 'Careless', ['Exact', 'Thorough', 'Attentive'], '“Meticulous” means very careful and precise; “careless” is its antonym.'],
  ['Antonym', 'medium', "Identify the antonym of 'plausible'.", 'Unbelievable', ['Credible', 'Likely', 'Reasonable'], '“Plausible” means believable or reasonable.'],
  ['Antonym', 'hard', "Which verb is the opposite of 'converge'?", 'Diverge', ['Combine', 'Gather', 'Meet'], 'To converge is to come together; to diverge is to move apart.'],
  ['Antonym', 'hard', "Select the antonym of 'acquiesce'.", 'Resist', ['Consent', 'Accept', 'Comply'], 'To acquiesce is to accept without protest; to resist is the opposite.'],
  ['Antonym', 'medium', "Which word is opposite in meaning to 'lavish'?", 'Economical', ['Extravagant', 'Abundant', 'Generous'], '“Lavish” suggests excessive spending; “economical” suggests careful spending.'],
  ['Antonym', 'medium', "Choose the antonym of 'orthodox'.", 'Unconventional', ['Traditional', 'Accepted', 'Established'], '“Orthodox” means conventional or traditional.'],
  ['Antonym', 'easy', "What is the opposite of 'vigilant'?", 'Negligent', ['Watchful', 'Alert', 'Attentive'], 'A vigilant person is watchful, while a negligent person fails to take proper care.'],
  ['Antonym', 'easy', "Identify the antonym of 'mandatory'.", 'Optional', ['Binding', 'Required', 'Compulsory'], '“Mandatory” means required; “optional” means left to choice.'],

  ['Idioms and Phrases', 'easy', "What does the phrase 'at the eleventh hour' mean?", 'At the last possible moment', ['At eleven o’clock', 'After a long delay', 'Before the appointed day'], '“At the eleventh hour” means at the latest possible moment.'],
  ['Idioms and Phrases', 'medium', "Choose the correct meaning of 'to call a spade a spade'.", 'To speak plainly', ['To insult a worker', 'To begin digging', 'To avoid a dispute'], 'The idiom means to describe facts directly and honestly.'],
  ['Idioms and Phrases', 'medium', "In the sentence 'The revised rule took everyone by surprise', what does 'by surprise' convey?", 'Unexpectedly', ['With approval', 'In confidence', 'Without difficulty'], 'To take someone by surprise is to happen unexpectedly.'],
  ['Idioms and Phrases', 'easy', "What is meant by 'a blessing in disguise'?", 'Something beneficial that first seemed harmful', ['A concealed reward', 'An openly generous act', 'A religious ceremony'], 'The phrase describes an apparent problem that later proves beneficial.'],
  ['Idioms and Phrases', 'hard', "Select the meaning of 'to draw a blank'.", 'To fail to remember or obtain an answer', ['To design an empty form', 'To cancel an appointment', 'To refuse to speak publicly'], 'To draw a blank is to get no result or fail to remember an answer.'],
  ['Idioms and Phrases', 'medium', "What does 'to read between the lines' require?", 'Understanding an implied meaning', ['Reading every alternate line', 'Correcting printed errors', 'Translating word for word'], 'The idiom means discovering a meaning that is suggested rather than directly stated.'],
  ['Idioms and Phrases', 'medium', "Choose the meaning of 'to keep someone in the dark'.", 'To withhold information', ['To protect someone at night', 'To make someone wait outside', 'To provide secret training'], 'Keeping someone in the dark means not giving that person relevant information.'],
  ['Idioms and Phrases', 'hard', "The phrase 'a storm in a teacup' refers to what?", 'Much excitement over a trivial matter', ['A sudden natural disaster', 'A heated formal debate', 'A dangerous domestic accident'], 'The phrase describes disproportionate excitement or anger about something minor.'],
  ['Idioms and Phrases', 'easy', "What does 'on the same wavelength' mean?", 'Sharing similar ideas or understanding', ['Using the same device', 'Speaking at the same volume', 'Working in one office'], 'People on the same wavelength understand or think like one another.'],
  ['Idioms and Phrases', 'medium', "Select the meaning of 'to turn a deaf ear'.", 'To ignore deliberately', ['To become unable to hear', 'To listen with sympathy', 'To misunderstand accidentally'], 'To turn a deaf ear is to refuse deliberately to listen.'],

  ['One-word Substitution', 'easy', 'Which one word means “a person who compiles a dictionary”?', 'Lexicographer', ['Biographer', 'Calligrapher', 'Cartographer'], 'A lexicographer writes or compiles dictionaries.'],
  ['One-word Substitution', 'medium', 'Choose one word for “a statement capable of more than one interpretation”.', 'Ambiguous', ['Audible', 'Authentic', 'Anonymous'], 'An ambiguous statement can be interpreted in more than one way.'],
  ['One-word Substitution', 'medium', 'What is a person who knows and uses several languages called?', 'Polyglot', ['Patriot', 'Pedant', 'Pilgrim'], 'A polyglot can speak or use several languages.'],
  ['One-word Substitution', 'easy', 'Select one word for “a speech delivered without preparation”.', 'Impromptu', ['Inaugural', 'Verbose', 'Posthumous'], 'An impromptu speech is made without prior preparation.'],
  ['One-word Substitution', 'hard', 'Which word describes “a person who can use both hands equally well”?', 'Ambidextrous', ['Ambivalent', 'Anonymous', 'Autonomous'], 'An ambidextrous person can use either hand with equal skill.'],
  ['One-word Substitution', 'medium', 'Choose one word for “the study of the origin and history of words”.', 'Etymology', ['Entomology', 'Epidemiology', 'Ethnology'], 'Etymology studies the origin and historical development of words.'],
  ['One-word Substitution', 'easy', 'What is a remedy for all diseases or difficulties called?', 'Panacea', ['Placebo', 'Sedative', 'Antidote'], 'A panacea is a supposed cure or solution for every problem.'],
  ['One-word Substitution', 'hard', 'Select one word for “incapable of being expressed in words”.', 'Ineffable', ['Infallible', 'Illegible', 'Inevitable'], 'Something ineffable is too great or extreme to be expressed in words.'],
  ['One-word Substitution', 'medium', 'Which word means “a person appointed to settle a dispute”?', 'Arbitrator', ['Auditor', 'Curator', 'Narrator'], 'An arbitrator hears a dispute and gives a decision.'],
  ['One-word Substitution', 'hard', 'Choose one word for “a word formed from the initial letters of a name or phrase”.', 'Acronym', ['Antonym', 'Homonym', 'Eponym'], 'An acronym is formed from the initial letters of a multiword expression.'],

  ['Error Spotting', 'medium', 'Identify the erroneous part: “Neither the translator nor the editors (A) / was willing (B) / to approve the altered wording (C) / without a fresh review. (D)”', 'Part B', ['Part A', 'Part C', 'No error'], 'With “neither...nor”, the verb agrees with the nearer subject “editors”, so “were willing” is required.'],
  ['Error Spotting', 'medium', 'Find the error: “The committee has discussed (A) / the proposal in detail (B) / yesterday afternoon. (C) / No error (D)”', 'Part A', ['Part B', 'Part C', 'No error'], 'A definite past-time expression requires the simple past: “discussed”, not “has discussed”.'],
  ['Error Spotting', 'hard', 'Locate the incorrect part: “Had the notice been clearer, (A) / fewer applicants would have made (B) / mistakes while they fill (C) / the online form. (D)”', 'Part C', ['Part A', 'Part B', 'No error'], 'The past unreal condition requires “while they filled” in this context.'],
  ['Error Spotting', 'easy', 'Which part contains an error? “Each of the translated pages (A) / were checked (B) / by a second reviewer (C) / before publication. (D)”', 'Part B', ['Part A', 'Part C', 'No error'], '“Each” is singular, so the verb should be “was checked”.'],
  ['Error Spotting', 'hard', 'Spot the error in this sentence: “No sooner did the meeting begin (A) / when the power supply failed (B) / and the display went blank. (C) / No error (D)”', 'Part B', ['Part A', 'Part C', 'No error'], 'The correct correlative construction is “no sooner...than”, not “no sooner...when”.'],
  ['Error Spotting', 'medium', 'Identify the faulty segment: “The revised guidelines are (A) / more clearer than (B) / the version issued last year. (C) / No error (D)”', 'Part B', ['Part A', 'Part C', 'No error'], '“Clearer” is already comparative, so “more” must be removed.'],
  ['Error Spotting', 'medium', 'Find the incorrect part: “The officer demanded (A) / that the note was rewritten (B) / before it entered the official record. (C) / No error (D)”', 'Part B', ['Part A', 'Part C', 'No error'], 'After “demanded that”, the mandative form “be rewritten” is required.'],
  ['Error Spotting', 'hard', 'Locate the error: “Scarcely had she completed the translation (A) / than another urgent file (B) / arrived on her desk. (C) / No error (D)”', 'Part B', ['Part A', 'Part C', 'No error'], '“Scarcely” pairs with “when”, not “than”.'],
  ['Error Spotting', 'medium', 'Which segment is wrong? “One of the reasons for the delay (A) / were the absence (B) / of a verified source document. (C) / No error (D)”', 'Part B', ['Part A', 'Part C', 'No error'], 'The subject is singular, “one”, so the verb should be “was”.'],
  ['Error Spotting', 'hard', 'Spot the faulty part: “The report not only identifies the error (A) / but also suggesting (B) / a practical method of correction. (C) / No error (D)”', 'Part B', ['Part A', 'Part C', 'No error'], 'Parallel structure requires “but also suggests” to match “identifies”.'],
  ['Error Spotting', 'easy', 'Identify the error: “She is senior than me (A) / in service, but she always (B) / asks for my opinion. (C) / No error (D)”', 'Part A', ['Part B', 'Part C', 'No error'], '“Senior” takes the preposition “to”, not “than”.'],
  ['Error Spotting', 'medium', 'Find the erroneous part: “The number of bilingual applications (A) / have increased steadily (B) / during the last three years. (C) / No error (D)”', 'Part B', ['Part A', 'Part C', 'No error'], '“The number of” takes a singular verb, so “has increased” is correct.'],

  ['Fill in the Blanks', 'easy', 'The final translation must be consistent ___ the terminology used in the Act.', 'with', ['to', 'by', 'from'], 'The adjective “consistent” takes the preposition “with”.'],
  ['Fill in the Blanks', 'medium', 'If the reviewer ___ the ambiguity earlier, the notice would have been corrected before publication.', 'had noticed', ['noticed', 'would notice', 'has noticed'], 'A third conditional uses the past perfect in the if-clause.'],
  ['Fill in the Blanks', 'easy', 'The committee reached its decision ___ examining both versions of the document.', 'after', ['until', 'during', 'beside'], '“After” correctly shows that the examination preceded the decision.'],
  ['Fill in the Blanks', 'medium', 'The officer asked whether the Hindi draft was faithful ___ the English original.', 'to', ['with', 'for', 'upon'], 'The standard expression is “faithful to” a source or original.'],
  ['Fill in the Blanks', 'hard', 'Hardly had the corrigendum been uploaded ___ users began reporting the corrected figures.', 'when', ['than', 'then', 'while'], 'The correct correlative construction is “hardly...when”.'],
  ['Fill in the Blanks', 'easy', 'Every candidate must carry an identity document ___ the examination centre.', 'to', ['at', 'for', 'upon'], 'Movement towards a place is expressed with “to”.'],
  ['Fill in the Blanks', 'medium', 'The revised passage is shorter, ___ it preserves every essential qualification.', 'yet', ['because', 'unless', 'therefore'], '“Yet” correctly contrasts brevity with complete preservation of meaning.'],
  ['Fill in the Blanks', 'hard', 'The draft was returned so that its technical terms ___ verified once more.', 'could be', ['can have', 'were being to', 'will have'], '“Could be verified” correctly expresses purpose in a past context and uses the passive voice.'],
  ['Fill in the Blanks', 'medium', 'No applicant is exempt ___ following the instructions printed on the admission certificate.', 'from', ['of', 'with', 'at'], 'The adjective “exempt” takes the preposition “from”.'],
  ['Fill in the Blanks', 'easy', 'The notice remained online ___ the replacement file was ready.', 'until', ['since', 'among', 'despite'], '“Until” marks the endpoint of the notice remaining online.'],

  ['Active and Passive Voice', 'easy', 'Change into passive voice: “The translator revised the disputed paragraph.”', 'The disputed paragraph was revised by the translator.', ['The disputed paragraph is revised by the translator.', 'The translator was revised by the disputed paragraph.', 'The disputed paragraph had revised the translator.'], 'A simple-past active sentence becomes “was/were + past participle” in the passive.'],
  ['Active and Passive Voice', 'medium', 'Choose the passive form of “The committee will examine every objection.”', 'Every objection will be examined by the committee.', ['Every objection is examined by the committee.', 'Every objection will examine the committee.', 'The committee will be examined by every objection.'], 'The future passive uses “will be + past participle”.'],
  ['Active and Passive Voice', 'medium', 'Convert to passive voice: “They have not published the final key.”', 'The final key has not been published.', ['The final key was not published.', 'The final key had not published.', 'The final key has not published them.'], 'The present-perfect passive uses “has/have been + past participle”.'],
  ['Active and Passive Voice', 'hard', 'Select the passive equivalent of “Who prepared this bilingual glossary?”', 'By whom was this bilingual glossary prepared?', ['Who was prepared by this bilingual glossary?', 'By whom did this bilingual glossary prepare?', 'Whom prepared this bilingual glossary?'], 'An interrogative simple-past passive takes “by whom + was/were + subject + past participle”.'],
  ['Active and Passive Voice', 'easy', 'Choose the active form of “The application was rejected by the scrutiny team.”', 'The scrutiny team rejected the application.', ['The scrutiny team was rejecting the application.', 'The application rejected the scrutiny team.', 'The scrutiny team has rejected by the application.'], 'The simple-past passive converts to a simple-past active sentence with the agent as subject.'],
  ['Active and Passive Voice', 'medium', 'Change into passive voice: “Please verify both language versions.”', 'Let both language versions be verified.', ['Both language versions verified please.', 'Let both language versions verify.', 'Both language versions have been verifying.'], 'A formal imperative can be passivised as “let + object + be + past participle”.'],
  ['Active and Passive Voice', 'hard', 'Identify the passive form of “People believe that the manuscript is authentic.”', 'The manuscript is believed to be authentic.', ['The manuscript believes to be authentic.', 'It has believed the manuscript authentic.', 'The manuscript was believing authenticity.'], 'The reporting passive is formed as “subject + is believed + to-infinitive”.'],
  ['Active and Passive Voice', 'medium', 'Select the passive form of “The panel is reviewing the disputed answers.”', 'The disputed answers are being reviewed by the panel.', ['The disputed answers have been reviewed by the panel.', 'The disputed answers were being reviewed by the panel.', 'The panel is being reviewed by the disputed answers.'], 'The present-continuous passive uses “am/is/are being + past participle”.'],

  ['Direct and Indirect Speech', 'easy', 'Change into indirect speech: Rina said, “I am checking the Hindi draft.”', 'Rina said that she was checking the Hindi draft.', ['Rina said that I am checking the Hindi draft.', 'Rina says that she checked the Hindi draft.', 'Rina said that she has checked the Hindi draft.'], 'With a past reporting verb, “I am checking” changes to “she was checking”.'],
  ['Direct and Indirect Speech', 'medium', 'Report the question: The officer said to me, “Have you signed both pages?”', 'The officer asked me whether I had signed both pages.', ['The officer asked me have I signed both pages.', 'The officer told me whether I signed both pages.', 'The officer asked that I had signed both pages.'], 'A yes/no question takes “asked whether” and backshifts the present perfect to past perfect.'],
  ['Direct and Indirect Speech', 'medium', 'Choose the indirect form: She said, “Do not alter the quoted sentence.”', 'She instructed them not to alter the quoted sentence.', ['She said them do not alter the quoted sentence.', 'She asked that they did not alter the quoted sentence.', 'She instructed them to not altered the quoted sentence.'], 'A negative command is reported with “instructed + object + not to + verb”.'],
  ['Direct and Indirect Speech', 'hard', 'Convert to indirect speech: Arun said, “I completed this translation yesterday.”', 'Arun said that he had completed that translation the previous day.', ['Arun said that he completed this translation yesterday.', 'Arun said he has completed that translation the next day.', 'Arun says that he had completed this translation before.'], 'The simple past backshifts to past perfect; “this” becomes “that” and “yesterday” becomes “the previous day”.'],
  ['Direct and Indirect Speech', 'easy', 'Report the request: The candidate said to the officer, “Please explain the correction window.”', 'The candidate requested the officer to explain the correction window.', ['The candidate said please explain the correction window.', 'The candidate requested that explain the correction window.', 'The candidate told whether the correction window was explained.'], 'A polite request is commonly reported with “requested + object + to-infinitive”.'],
  ['Direct and Indirect Speech', 'medium', 'Select the reported form: The reviewer said, “The sentence may have two meanings.”', 'The reviewer said that the sentence might have two meanings.', ['The reviewer said that the sentence may had two meanings.', 'The reviewer says the sentence might has two meanings.', 'The reviewer said that the sentence has two meanings yesterday.'], 'In reported speech after a past reporting verb, “may” normally changes to “might”.'],
  ['Direct and Indirect Speech', 'hard', 'Change into indirect speech: He said to her, “Why did you omit the heading?”', 'He asked her why she had omitted the heading.', ['He asked her why did she omit the heading.', 'He told her why she omitted the heading?', 'He asked that why she had omitted the heading.'], 'A reported wh-question uses statement order and backshifts the simple past to past perfect.'],
  ['Direct and Indirect Speech', 'medium', 'Report the advice: The mentor said, “You should compare the source and target texts.”', 'The mentor advised us to compare the source and target texts.', ['The mentor advised that compare the source and target texts.', 'The mentor said us should compare both texts.', 'The mentor asked whether we compare both texts.'], 'Advice can be reported with “advised + object + to-infinitive”.'],

  ['Sentence Improvement', 'easy', 'Improve the underlined idea in: “The instructions are applicable for all candidates.”', 'applicable to all candidates', ['applicable with all candidates', 'applicable upon all candidates', 'applicable at all candidates'], 'The adjective “applicable” takes the preposition “to”.'],
  ['Sentence Improvement', 'medium', 'Choose the best correction: “She is working here since 2022.”', 'She has been working here since 2022.', ['She was working here since 2022.', 'She works here from 2022.', 'She had worked here since 2022 now.'], 'An action beginning in the past and continuing now takes the present perfect continuous.'],
  ['Sentence Improvement', 'medium', 'Improve the sentence: “The new glossary is superior than the old one.”', 'The new glossary is superior to the old one.', ['The new glossary is superior from the old one.', 'The new glossary is more superior than the old one.', 'The new glossary is superior over the old one.'], '“Superior” takes “to”, not “than”.'],
  ['Sentence Improvement', 'hard', 'Select the best revision: “Despite of being concise, the notice was complete.”', 'Despite being concise, the notice was complete.', ['Despite it was concise, the notice was complete.', 'In despite of concise, the notice was complete.', 'Despite being concisely, the notice was complete.'], '“Despite” is not followed by “of”; it can directly precede a gerund phrase.'],
  ['Sentence Improvement', 'easy', 'Correct the sentence: “There are less errors in the revised copy.”', 'There are fewer errors in the revised copy.', ['There is lesser errors in the revised copy.', 'There are few error in the revised copy.', 'There have less errors in the revised copy.'], 'Use “fewer” with countable plural nouns such as “errors”.'],
  ['Sentence Improvement', 'medium', 'Choose the clearest version: “The reason is because the source file was incomplete.”', 'The reason is that the source file was incomplete.', ['The reason because the source file was incomplete.', 'The reason was due because the source file was incomplete.', 'The reason is being the source file was incomplete.'], '“The reason is that” avoids the redundant construction “the reason is because”.'],
  ['Sentence Improvement', 'hard', 'Improve the parallel structure: “The role requires accuracy, patience, and to understand context.”', 'The role requires accuracy, patience, and an understanding of context.', ['The role requires accurate, patience, and understanding context.', 'The role requires accuracy, patiently, and context.', 'The role requires being accurate, patience, and to understand context.'], 'All three items should have parallel noun forms.'],
  ['Sentence Improvement', 'medium', 'Select the grammatically complete revision: “Not only the wording was inaccurate but also misleading.”', 'The wording was not only inaccurate but also misleading.', ['Not only was inaccurate the wording but misleading also.', 'The wording not only was inaccurate and also misleading.', 'The wording was inaccurate not only but misleading.'], 'Placing “not only” before the first coordinated adjective creates a complete parallel structure.'],

  ['Reading Comprehension', 'medium', `${passageA}\n\nWhy does the passage reject mechanical word replacement?`, 'Because translation must preserve purpose, tone, and meaning', ['Because dictionaries contain too few words', 'Because legal texts never use equivalent terms', 'Because audiences prefer longer sentences'], 'The opening sentences state that translation requires attention to purpose, tone, audience, and intended meaning.'],
  ['Reading Comprehension', 'easy', `${passageA}\n\nAccording to the passage, what does a legal instruction require most directly?`, 'Precision', ['Humour', 'Personal opinion', 'Decorative language'], 'The passage explicitly says that a legal instruction demands precision.'],
  ['Reading Comprehension', 'medium', `${passageA}\n\nWhat additional quality should a public notice possess?`, 'Ease of understanding', ['Literary complexity', 'Technical ambiguity', 'Emotional intensity'], 'The passage says that a public notice must also remain easy to understand.'],
  ['Reading Comprehension', 'hard', `${passageA}\n\nWhat should a translator do when no exact equivalent exists?`, 'Use an expression that preserves the intended meaning', ['Leave the phrase untranslated', 'Insert a personal explanation into the text', 'Choose the longest available expression'], 'The final sentence gives this approach directly.'],
  ['Reading Comprehension', 'hard', `${passageA}\n\nWhich principle is most strongly supported by the passage?`, 'Faithfulness involves meaning as well as words', ['Every source word needs one fixed equivalent', 'Legal and public texts should use the same tone', 'A translator may improve the author’s opinion'], 'The passage contrasts mechanical replacement with preservation of purpose, tone, and intended meaning.'],
  ['Reading Comprehension', 'easy', `${passageB}\n\nWhat benefit of digital archives is mentioned first?`, 'Government records become easier to search', ['Handwriting becomes clearer automatically', 'Old spelling is corrected instantly', 'Human review is no longer needed'], 'The first sentence states that digital archives make records easier to search.'],
  ['Reading Comprehension', 'medium', `${passageB}\n\nWhy may automated systems misread old documents?`, 'The documents may have faded text, inconsistent spelling, or handwriting', ['The records are always legally restricted', 'The files contain too many descriptive labels', 'Users search with incorrect dates'], 'The passage lists faded text, inconsistent spelling, and handwritten notes as obstacles.'],
  ['Reading Comprehension', 'easy', `${passageB}\n\nWhat does the passage say remains necessary after digitisation?`, 'Human review', ['Manual filing only', 'Printing every record', 'Removing all old documents'], 'The third sentence explicitly says that human review remains necessary.'],
  ['Reading Comprehension', 'medium', `${passageB}\n\nWhy does careful checking save time later?`, 'Users can trust the text and its labels', ['Scanners work faster after review', 'Every document becomes shorter', 'Spelling variations disappear from history'], 'The final sentence links careful checking with reliable text and descriptive labels.'],
  ['Reading Comprehension', 'hard', `${passageB}\n\nWhich statement best summarizes the passage?`, 'Digitisation improves access only when accuracy is also checked', ['Digital archives should replace every physical record immediately', 'Automated reading is more reliable than human review', 'Descriptive labels matter more than document text'], 'The passage balances the search benefit of digitisation with the continuing need for human accuracy checks.'],
];

function placeAnswer(answer: string, distractors: [string, string, string], index: number) {
  const options = [...distractors];
  options.splice(index, 0, answer);
  return options;
}

export const SSC_CHT_PAPER_1_GENERAL_ENGLISH_1: Question[] = rows.map(
  ([topic, difficulty, question, answer, distractors, explanation], index) => ({
    id: `ssc-cht-en-${String(index + 1).padStart(3, '0')}`,
    section: 'General English',
    topic,
    difficulty,
    question,
    options: placeAnswer(answer, distractors, index % 4),
    correctIndex: index % 4,
    explanation,
    source,
  }),
);
