import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SSC CHSL 2025 official notification, Tier 1 syllabus — Quantitative Aptitude section',
  url: 'https://ssc.gov.in/for-candidates/cgl-exam/s40d16nackd16h0',
  checkedOn: '4 August 2026',
};

export const SSC_CHSL_TIER1_QUANTITATIVE_APTITUDE_1: Question[] = [
  { id: 'ssc-chsl-t1-qa-001', section: 'Quantitative Aptitude', topic: 'Percentage', difficulty: 'easy', question: 'What is 15% of 240?', options: ['36', '32', '34', '38'], correctIndex: 0, explanation: '15% of 240 = (15/100) × 240 = 36.', source },
  { id: 'ssc-chsl-t1-qa-002', section: 'Quantitative Aptitude', topic: 'Number system', difficulty: 'easy', question: 'What is the square root of 169?', options: ['12', '13', '14', '15'], correctIndex: 1, explanation: '13 × 13 = 169, so the square root of 169 is 13.', source },
  { id: 'ssc-chsl-t1-qa-003', section: 'Quantitative Aptitude', topic: 'Number system', difficulty: 'easy', question: 'What is the value of 12 × 13?', options: ['144', '150', '156', '160'], correctIndex: 2, explanation: '12 × 13 = 156.', source },
  { id: 'ssc-chsl-t1-qa-004', section: 'Quantitative Aptitude', topic: 'Ratio and proportion', difficulty: 'medium', question: 'Two numbers are in the ratio 3:5. If their sum is 64, what is the larger number?', options: ['36', '38', '42', '40'], correctIndex: 3, explanation: 'Total parts = 3 + 5 = 8. Each part = 64 ÷ 8 = 8. The larger number = 5 × 8 = 40.', source },
  { id: 'ssc-chsl-t1-qa-005', section: 'Quantitative Aptitude', topic: 'Average', difficulty: 'easy', question: 'Find the average of 12, 18, 24, 30, and 36.', options: ['24', '22', '26', '20'], correctIndex: 0, explanation: 'Average = (12 + 18 + 24 + 30 + 36) / 5 = 120 / 5 = 24.', source },
  { id: 'ssc-chsl-t1-qa-006', section: 'Quantitative Aptitude', topic: 'Simple interest', difficulty: 'medium', question: 'Find the simple interest on ₹4,000 at 6% per annum for 3 years.', options: ['₹700', '₹720', '₹740', '₹760'], correctIndex: 1, explanation: 'SI = (P × R × T) / 100 = (4000 × 6 × 3) / 100 = ₹720.', source },
  { id: 'ssc-chsl-t1-qa-007', section: 'Quantitative Aptitude', topic: 'Compound interest', difficulty: 'medium', question: 'Find the compound interest on ₹5,000 at 10% per annum for 2 years, compounded annually.', options: ['₹1,000', '₹1,020', '₹1,050', '₹1,100'], correctIndex: 2, explanation: 'Amount = 5000 × (1.1)² = ₹6,050. Compound interest = 6050 − 5000 = ₹1,050.', source },
  { id: 'ssc-chsl-t1-qa-008', section: 'Quantitative Aptitude', topic: 'Profit and loss', difficulty: 'easy', question: 'A shopkeeper buys an item for ₹320 and sells it for ₹400. Find the profit percentage.', options: ['20%', '22%', '24%', '25%'], correctIndex: 3, explanation: 'Profit = 400 − 320 = ₹80. Profit % = (80 ÷ 320) × 100 = 25%.', source },
  { id: 'ssc-chsl-t1-qa-009', section: 'Quantitative Aptitude', topic: 'Profit and loss', difficulty: 'easy', question: 'A shopkeeper buys an item for ₹500 and sells it for ₹425. Find the loss percentage.', options: ['15%', '12%', '18%', '10%'], correctIndex: 0, explanation: 'Loss = 500 − 425 = ₹75. Loss % = (75 ÷ 500) × 100 = 15%.', source },
  { id: 'ssc-chsl-t1-qa-010', section: 'Quantitative Aptitude', topic: 'Time, speed and distance', difficulty: 'easy', question: 'A car travels 240 km in 4 hours. What is its speed?', options: ['50 km/h', '60 km/h', '65 km/h', '55 km/h'], correctIndex: 1, explanation: 'Speed = Distance / Time = 240 / 4 = 60 km/h.', source },
  { id: 'ssc-chsl-t1-qa-011', section: 'Quantitative Aptitude', topic: 'Time, speed and distance', difficulty: 'medium', question: 'A train 180 m long crosses a pole in 12 seconds. Find its speed in km/h.', options: ['48 km/h', '50 km/h', '54 km/h', '60 km/h'], correctIndex: 2, explanation: 'Speed = 180 m ÷ 12 s = 15 m/s. Converting: 15 × 18/5 = 54 km/h.', source },
  { id: 'ssc-chsl-t1-qa-012', section: 'Quantitative Aptitude', topic: 'Time and work', difficulty: 'medium', question: 'A can complete a piece of work in 15 days and B can complete it in 10 days. Working together, how many days will they take?', options: ['5 days', '7 days', '8 days', '6 days'], correctIndex: 3, explanation: 'Combined rate = 1/15 + 1/10 = 2/30 + 3/30 = 5/30 = 1/6 of the work per day, so the work takes 6 days.', source },
  { id: 'ssc-chsl-t1-qa-013', section: 'Quantitative Aptitude', topic: 'Mensuration', difficulty: 'easy', question: 'Find the area of a rectangle with length 18 cm and breadth 12 cm.', options: ['216 cm²', '208 cm²', '220 cm²', '210 cm²'], correctIndex: 0, explanation: 'Area of a rectangle = length × breadth = 18 × 12 = 216 cm².', source },
  { id: 'ssc-chsl-t1-qa-014', section: 'Quantitative Aptitude', topic: 'Mensuration', difficulty: 'medium', question: 'Find the area of a circle with radius 7 cm. (Use π = 22/7.)', options: ['144 cm²', '154 cm²', '164 cm²', '150 cm²'], correctIndex: 1, explanation: 'Area = πr² = (22/7) × 7 × 7 = 22 × 7 = 154 cm².', source },
  { id: 'ssc-chsl-t1-qa-015', section: 'Quantitative Aptitude', topic: 'Mensuration', difficulty: 'easy', question: 'Find the perimeter of a square with side 9 cm.', options: ['32 cm', '34 cm', '36 cm', '40 cm'], correctIndex: 2, explanation: 'Perimeter of a square = 4 × side = 4 × 9 = 36 cm.', source },
  { id: 'ssc-chsl-t1-qa-016', section: 'Quantitative Aptitude', topic: 'Elementary algebra', difficulty: 'easy', question: 'Solve for x: 2x + 5 = 17', options: ['4', '5', '7', '6'], correctIndex: 3, explanation: '2x = 17 − 5 = 12, so x = 12 / 2 = 6.', source },
  { id: 'ssc-chsl-t1-qa-017', section: 'Quantitative Aptitude', topic: 'Elementary algebra', difficulty: 'easy', question: 'If x² = 144, what is the positive value of x?', options: ['12', '11', '13', '14'], correctIndex: 0, explanation: '12 × 12 = 144, so the positive value of x is 12.', source },
  { id: 'ssc-chsl-t1-qa-018', section: 'Quantitative Aptitude', topic: 'Number system', difficulty: 'easy', question: 'What is the LCM of 6 and 8?', options: ['16', '24', '32', '48'], correctIndex: 1, explanation: 'Multiples of 6: 6, 12, 18, 24... Multiples of 8: 8, 16, 24... The LCM is 24.', source },
  { id: 'ssc-chsl-t1-qa-019', section: 'Quantitative Aptitude', topic: 'Number system', difficulty: 'easy', question: 'What is the HCF of 24 and 36?', options: ['6', '8', '12', '18'], correctIndex: 2, explanation: 'The largest number dividing both 24 and 36 is 12.', source },
  { id: 'ssc-chsl-t1-qa-020', section: 'Quantitative Aptitude', topic: 'Percentage', difficulty: 'medium', question: '40% of a number is 92. What is the number?', options: ['220', '225', '228', '230'], correctIndex: 3, explanation: 'If 40% of the number is 92, the number = 92 ÷ 0.40 = 230.', source },
  { id: 'ssc-chsl-t1-qa-021', section: 'Quantitative Aptitude', topic: 'Percentage', difficulty: 'medium', question: 'An item marked at ₹600 is sold for ₹480. What is the discount percentage?', options: ['20%', '15%', '25%', '18%'], correctIndex: 0, explanation: 'Discount = 600 − 480 = ₹120. Discount % = (120 ÷ 600) × 100 = 20%.', source },
  { id: 'ssc-chsl-t1-qa-022', section: 'Quantitative Aptitude', topic: 'Profit and loss', difficulty: 'medium', question: 'A trader buys an item for ₹240 and wants a profit of 20%. At what price should the item be sold?', options: ['₹280', '₹288', '₹290', '₹300'], correctIndex: 1, explanation: 'Selling price = Cost price × (1 + profit%) = 240 × 1.20 = ₹288.', source },
  { id: 'ssc-chsl-t1-qa-023', section: 'Quantitative Aptitude', topic: 'Time, speed and distance', difficulty: 'medium', question: 'A car travels at 60 km/h for 2 hours and then at 90 km/h for 1 hour. What is its average speed for the whole journey?', options: ['65 km/h', '68 km/h', '70 km/h', '75 km/h'], correctIndex: 2, explanation: 'Total distance = (60 × 2) + (90 × 1) = 210 km. Total time = 3 hours. Average speed = 210 / 3 = 70 km/h.', source },
  { id: 'ssc-chsl-t1-qa-024', section: 'Quantitative Aptitude', topic: 'Time and work', difficulty: 'medium', question: 'A can complete a piece of work in 20 days and B can complete it in 30 days. Working together, how many days will they take?', options: ['10 days', '11 days', '13 days', '12 days'], correctIndex: 3, explanation: 'Combined rate = 1/20 + 1/30 = 3/60 + 2/60 = 5/60 = 1/12 of the work per day, so the work takes 12 days.', source },
  { id: 'ssc-chsl-t1-qa-025', section: 'Quantitative Aptitude', topic: 'Ratio and proportion', difficulty: 'easy', question: 'Simplify the ratio 45:60 to its lowest terms.', options: ['3 : 4', '4 : 5', '2 : 3', '5 : 6'], correctIndex: 0, explanation: 'Dividing both terms by their HCF, 15, gives 45:60 = 3:4.', source },
];
