import type { Question, QuestionSource } from '../questions';

const checkedOn = '3 August 2026';

const source = (reference: string, url: string): QuestionSource => ({
  kind: 'original',
  reference,
  url,
  checkedOn,
});

const constitution = source(
  'Constitution of India, Legislative Department, Government of India',
  'https://www.legislative.gov.in/documents/constitution-of-india/constitution-of-india-AjN2EjMtQWa?pageTitle=Constitution-of-India',
);
const tradeTerritory = source(
  'NCERT, Our Pasts III - From Trade to Territory',
  'https://www.ncert.nic.in/textbook/pdf/hess202.pdf',
);
const dholavira = source(
  'Dholavira: a Harappan City, UNESCO World Heritage Centre',
  'https://whc.unesco.org/en/list/1645/',
);
const khajuraho = source(
  'Khajuraho Group of Monuments, UNESCO World Heritage Centre',
  'https://whc.unesco.org/en/list/240/',
);
const sattriya = source(
  'Sattriya Dance cultural package, Centre for Cultural Resources and Training, Government of India',
  'https://ccrtindia.gov.in/publication-and-audio-visual-productions/cultural-packages/',
);
const indiaLocation = source(
  'NCERT, Contemporary India I - India: Size and Location',
  'https://www.ncert.nic.in/textbook/pdf/iess101.pdf',
);
const physicalFeatures = source(
  'NCERT, Contemporary India I - Physical Features of India',
  'https://www.ncert.nic.in/textbook/pdf/iess102.pdf',
);
const soils = source(
  'NCERT, Contemporary India II - Resources and Development',
  'https://www.ncert.nic.in/textbook/pdf/jess101.pdf',
);
const drainage = source(
  'NCERT, Contemporary India I - Drainage',
  'https://www.ncert.nic.in/textbook/pdf/iess103.pdf',
);
const rbiMonetaryPolicy = source(
  'Reserve Bank of India - Monetary Policy: Overview and Instruments',
  'https://www.rbi.org.in/Scripts/FS_Overview.aspx?fn=2752',
);
const kelvin = source(
  'SI base unit: kelvin, International Bureau of Weights and Measures',
  'https://www.bipm.org/en/si-base-units/kelvin',
);
const biomolecules = source(
  'NCERT Chemistry - Biomolecules',
  'https://ncert.nic.in/textbook/pdf/lech205.pdf',
);
const sound = source(
  'Anatomy of an Electromagnetic Wave, NASA Science',
  'https://science.nasa.gov/ems/02_anatomy/',
);
const aditya = source(
  'Aditya-L1 mission, Indian Space Research Organisation',
  'https://www.isro.gov.in/ISRO_EN/Aditya_L1.html',
);

export const SSC_CGL_TIER1_GENERAL_AWARENESS_3: Question[] = [
  {
    id: 'ssc-cgl-t1-ga3-001',
    section: 'General Awareness',
    topic: 'Indian Polity',
    difficulty: 'easy',
    question: 'Which article of the Constitution guarantees the right to move the Supreme Court for enforcement of Fundamental Rights?',
    options: ['Article 32', 'Article 19', 'Article 21', 'Article 226'],
    correctIndex: 0,
    explanation: 'Article 32 guarantees the right to move the Supreme Court for enforcement of Fundamental Rights.',
    source: constitution,
  },
  {
    id: 'ssc-cgl-t1-ga3-002',
    section: 'General Awareness',
    topic: 'Indian Polity',
    difficulty: 'easy',
    question: 'What is the normal term of office of the President of India?',
    options: ['Four years', 'Five years', 'Six years', 'Seven years'],
    correctIndex: 1,
    explanation: 'Article 56 provides that the President holds office for a term of five years from entering office.',
    source: constitution,
  },
  {
    id: 'ssc-cgl-t1-ga3-003',
    section: 'General Awareness',
    topic: 'Indian Polity',
    difficulty: 'medium',
    question: 'What is the maximum number of members that the Rajya Sabha may have under the Constitution?',
    options: ['238', '245', '250', '252'],
    correctIndex: 2,
    explanation: 'Article 80 provides for up to 238 representatives of states and union territories plus 12 nominated members, for a maximum of 250.',
    source: constitution,
  },
  {
    id: 'ssc-cgl-t1-ga3-004',
    section: 'General Awareness',
    topic: 'Indian Polity',
    difficulty: 'medium',
    question: 'Who normally presides over a joint sitting of the two Houses of Parliament?',
    options: ['The President', 'The Vice-President', 'The Prime Minister', 'The Speaker of the Lok Sabha'],
    correctIndex: 3,
    explanation: 'The Speaker of the Lok Sabha normally presides over a joint sitting of Parliament.',
    source: constitution,
  },
  {
    id: 'ssc-cgl-t1-ga3-005',
    section: 'General Awareness',
    topic: 'Indian Polity',
    difficulty: 'medium',
    question: 'Which article provides for the Comptroller and Auditor-General of India?',
    options: ['Article 148', 'Article 124', 'Article 280', 'Article 324'],
    correctIndex: 0,
    explanation: 'Article 148 provides for the Comptroller and Auditor-General of India.',
    source: constitution,
  },
  {
    id: 'ssc-cgl-t1-ga3-006',
    section: 'General Awareness',
    topic: 'Modern History',
    difficulty: 'easy',
    question: 'In which year was the Battle of Plassey fought?',
    options: ['1764', '1757', '1773', '1784'],
    correctIndex: 1,
    explanation: 'The Battle of Plassey was fought in 1757 and was followed by a major expansion of East India Company power in Bengal.',
    source: tradeTerritory,
  },
  {
    id: 'ssc-cgl-t1-ga3-007',
    section: 'General Awareness',
    topic: 'Modern History',
    difficulty: 'medium',
    question: 'The Doctrine of Lapse is most closely associated with which Governor-General?',
    options: ['Lord Wellesley', 'Lord Cornwallis', 'Lord Dalhousie', 'Lord Ripon'],
    correctIndex: 2,
    explanation: 'Lord Dalhousie used the Doctrine of Lapse to annex Indian kingdoms where the ruler was considered to have no natural male heir.',
    source: tradeTerritory,
  },
  {
    id: 'ssc-cgl-t1-ga3-008',
    section: 'General Awareness',
    topic: 'Ancient History',
    difficulty: 'easy',
    question: 'The Harappan city of Dholavira is located in which present-day Indian state?',
    options: ['Rajasthan', 'Punjab', 'Haryana', 'Gujarat'],
    correctIndex: 3,
    explanation: 'Dholavira is situated on Khadir island in the Kachchh district of Gujarat.',
    source: dholavira,
  },
  {
    id: 'ssc-cgl-t1-ga3-009',
    section: 'General Awareness',
    topic: 'Art and Culture',
    difficulty: 'easy',
    question: 'The Khajuraho Group of Monuments is located in which state?',
    options: ['Madhya Pradesh', 'Uttar Pradesh', 'Rajasthan', 'Chhattisgarh'],
    correctIndex: 0,
    explanation: 'The Khajuraho Group of Monuments is located in the Chhatarpur district of Madhya Pradesh.',
    source: khajuraho,
  },
  {
    id: 'ssc-cgl-t1-ga3-010',
    section: 'General Awareness',
    topic: 'Art and Culture',
    difficulty: 'easy',
    question: 'Sattriya is a classical dance tradition from which state?',
    options: ['Manipur', 'Assam', 'Odisha', 'Kerala'],
    correctIndex: 1,
    explanation: 'Sattriya developed in Assam and is associated with the Vaishnava tradition introduced by Shrimanta Shankaradeva.',
    source: sattriya,
  },
  {
    id: 'ssc-cgl-t1-ga3-011',
    section: 'General Awareness',
    topic: 'Indian Geography',
    difficulty: 'medium',
    question: 'Which coordinates broadly describe the latitudinal extent of mainland India?',
    options: ['6 degrees 45 minutes N to 35 degrees 30 minutes N', '10 degrees N to 40 degrees N', '8 degrees 4 minutes N to 37 degrees 6 minutes N', '12 degrees N to 32 degrees N'],
    correctIndex: 2,
    explanation: 'Mainland India extends from 8 degrees 4 minutes north to 37 degrees 6 minutes north latitude.',
    source: indiaLocation,
  },
  {
    id: 'ssc-cgl-t1-ga3-012',
    section: 'General Awareness',
    topic: 'Indian Geography',
    difficulty: 'easy',
    question: 'The Lakshadweep island group lies in which body of water?',
    options: ['Bay of Bengal', 'Gulf of Mannar', 'Andaman Sea', 'Arabian Sea'],
    correctIndex: 3,
    explanation: 'Lakshadweep lies off India\'s southwestern coast in the Arabian Sea.',
    source: indiaLocation,
  },
  {
    id: 'ssc-cgl-t1-ga3-013',
    section: 'General Awareness',
    topic: 'Indian Geography',
    difficulty: 'medium',
    question: 'Which statement correctly compares the Western Ghats with the Eastern Ghats?',
    options: ['The Western Ghats are generally higher and more continuous.', 'The Eastern Ghats are higher and completely continuous.', 'Both ranges have the same average height and continuity.', 'The Western Ghats lie along the Bay of Bengal coast.'],
    correctIndex: 0,
    explanation: 'The Western Ghats are generally higher and more continuous than the discontinuous Eastern Ghats.',
    source: physicalFeatures,
  },
  {
    id: 'ssc-cgl-t1-ga3-014',
    section: 'General Awareness',
    topic: 'Indian Geography',
    difficulty: 'easy',
    question: 'Which is the most widespread soil type in India?',
    options: ['Black soil', 'Alluvial soil', 'Laterite soil', 'Arid soil'],
    correctIndex: 1,
    explanation: 'Alluvial soil is India\'s most widespread and important soil type, covering much of the northern plains and river valleys.',
    source: soils,
  },
  {
    id: 'ssc-cgl-t1-ga3-015',
    section: 'General Awareness',
    topic: 'Indian Geography',
    difficulty: 'medium',
    question: 'By what name is the Brahmaputra known when it enters India through Arunachal Pradesh?',
    options: ['Teesta', 'Lohit', 'Dihang', 'Subansiri'],
    correctIndex: 2,
    explanation: 'The Brahmaputra enters Arunachal Pradesh as the Dihang and is joined by tributaries including the Dibang and Lohit.',
    source: drainage,
  },
  {
    id: 'ssc-cgl-t1-ga3-016',
    section: 'General Awareness',
    topic: 'Indian Economy',
    difficulty: 'easy',
    question: 'How many members constitute the Monetary Policy Committee of India?',
    options: ['Three', 'Four', 'Five', 'Six'],
    correctIndex: 3,
    explanation: 'Section 45ZB of the Reserve Bank of India Act provides for a six-member Monetary Policy Committee.',
    source: rbiMonetaryPolicy,
  },
  {
    id: 'ssc-cgl-t1-ga3-017',
    section: 'General Awareness',
    topic: 'Indian Economy',
    difficulty: 'medium',
    question: 'What does the policy repo rate represent?',
    options: ['The rate at which the RBI provides liquidity against approved securities', 'The rate of income tax paid by banks', 'The interest paid on all savings accounts', 'The rate at which companies issue shares'],
    correctIndex: 0,
    explanation: 'The repo rate is the rate at which the RBI provides liquidity under the liquidity adjustment facility against government and other approved securities.',
    source: rbiMonetaryPolicy,
  },
  {
    id: 'ssc-cgl-t1-ga3-018',
    section: 'General Awareness',
    topic: 'Indian Economy',
    difficulty: 'medium',
    question: 'Open Market Operations by the Reserve Bank of India involve the outright purchase or sale of what?',
    options: ['Foreign company shares', 'Government securities', 'Agricultural commodities', 'Corporate income-tax receipts'],
    correctIndex: 1,
    explanation: 'Open Market Operations are outright purchases or sales of government securities used to inject or absorb durable liquidity.',
    source: rbiMonetaryPolicy,
  },
  {
    id: 'ssc-cgl-t1-ga3-019',
    section: 'General Awareness',
    topic: 'Indian Economy',
    difficulty: 'medium',
    question: 'Which combination consists of assets commonly used by banks to maintain the Statutory Liquidity Ratio?',
    options: ['Only foreign currency and company shares', 'Only loans issued to customers', 'Government securities, cash and gold', 'Only balances held outside India'],
    correctIndex: 2,
    explanation: 'The SLR is maintained in specified liquid assets, typically unencumbered government securities, cash and gold.',
    source: rbiMonetaryPolicy,
  },
  {
    id: 'ssc-cgl-t1-ga3-020',
    section: 'General Awareness',
    topic: 'Indian Economy',
    difficulty: 'easy',
    question: 'What is the primary objective of monetary policy in India?',
    options: ['To maximise customs revenue', 'To fix prices of agricultural goods', 'To determine corporate salaries', 'To maintain price stability while keeping growth in mind'],
    correctIndex: 3,
    explanation: 'The RBI Act states that monetary policy primarily aims to maintain price stability while keeping in mind the objective of growth.',
    source: rbiMonetaryPolicy,
  },
  {
    id: 'ssc-cgl-t1-ga3-021',
    section: 'General Awareness',
    topic: 'Physics',
    difficulty: 'easy',
    question: 'What is the SI base unit of thermodynamic temperature?',
    options: ['Kelvin', 'Degree Celsius', 'Joule', 'Watt'],
    correctIndex: 0,
    explanation: 'The kelvin, with symbol K, is the SI base unit of thermodynamic temperature.',
    source: kelvin,
  },
  {
    id: 'ssc-cgl-t1-ga3-022',
    section: 'General Awareness',
    topic: 'Biology',
    difficulty: 'easy',
    question: 'Which substance is a predominant constituent of the cell wall of plants?',
    options: ['Glycogen', 'Cellulose', 'Haemoglobin', 'Cholesterol'],
    correctIndex: 1,
    explanation: 'Cellulose is a structural polysaccharide and a predominant constituent of plant cell walls.',
    source: biomolecules,
  },
  {
    id: 'ssc-cgl-t1-ga3-023',
    section: 'General Awareness',
    topic: 'Biology',
    difficulty: 'easy',
    question: 'Deficiency of vitamin B1 can cause which disease?',
    options: ['Scurvy', 'Rickets', 'Beriberi', 'Night blindness'],
    correctIndex: 2,
    explanation: 'Vitamin B1, or thiamine, deficiency is associated with beriberi.',
    source: biomolecules,
  },
  {
    id: 'ssc-cgl-t1-ga3-024',
    section: 'General Awareness',
    topic: 'Physics',
    difficulty: 'easy',
    question: 'Through which medium can sound not travel?',
    options: ['Steel', 'Water', 'Air', 'Vacuum'],
    correctIndex: 3,
    explanation: 'Sound is a mechanical wave and requires a material medium, so it cannot travel through a vacuum.',
    source: sound,
  },
  {
    id: 'ssc-cgl-t1-ga3-025',
    section: 'General Awareness',
    topic: 'Space Science',
    difficulty: 'easy',
    question: 'Aditya-L1 observes the Sun from a halo orbit around which point in the Sun-Earth system?',
    options: ['The first Lagrange point, L1', 'The second Lagrange point, L2', 'Low Earth orbit', 'Geostationary orbit'],
    correctIndex: 0,
    explanation: 'Aditya-L1 operates in a halo orbit around the first Sun-Earth Lagrange point, about 1.5 million kilometres from Earth.',
    source: aditya,
  },
];
