import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'SSC CGL 2026 official notice, paragraph 13.10.1 (General Intelligence and Reasoning syllabus)',
  url: 'https://ssc.gov.in/api/attachment/uploads/masterData/NoticeBoards/Notice_of_adv_cgl_2026.pdf',
  checkedOn: '30 July 2026',
};

export const SSC_CGL_TIER1_REASONING_1: Question[] = [
  {
    id: 'ssc-cgl-t1-gi-001',
    section: 'General Intelligence and Reasoning',
    topic: 'Number series',
    difficulty: 'easy',
    question: 'Complete the series: 3, 8, 15, 24, 35, ?',
    options: ['46', '47', '48', '49'],
    correctIndex: 2,
    explanation: 'The differences are 5, 7, 9 and 11. The next difference is 13, so 35 + 13 = 48.',
    source,
  },
  {
    id: 'ssc-cgl-t1-gi-002',
    section: 'General Intelligence and Reasoning',
    topic: 'Number series',
    difficulty: 'easy',
    question: 'Complete the series: 2, 6, 12, 20, 30, ?',
    options: ['36', '40', '42', '44'],
    correctIndex: 2,
    explanation: 'The terms follow n × (n + 1): 1×2, 2×3, 3×4, 4×5 and 5×6. The next term is 6×7 = 42.',
    source,
  },
  {
    id: 'ssc-cgl-t1-gi-003',
    section: 'General Intelligence and Reasoning',
    topic: 'Letter series',
    difficulty: 'easy',
    question: 'Complete the series: A, C, F, J, O, ?',
    options: ['T', 'V', 'W', 'U'],
    correctIndex: 3,
    explanation: 'The forward jumps are 2, 3, 4 and 5 letters. A jump of 6 letters after O gives U.',
    source,
  },
  {
    id: 'ssc-cgl-t1-gi-004',
    section: 'General Intelligence and Reasoning',
    topic: 'Number analogy',
    difficulty: 'easy',
    question: '49 is related to 7 in the same way that 121 is related to:',
    options: ['9', '10', '11', '12'],
    correctIndex: 2,
    explanation: 'The second number is the positive square root of the first. √121 = 11.',
    source,
  },
  {
    id: 'ssc-cgl-t1-gi-005',
    section: 'General Intelligence and Reasoning',
    topic: 'Semantic analogy',
    difficulty: 'easy',
    question: 'Bird is related to Nest in the same way that Bee is related to:',
    options: ['Cave', 'Web', 'Burrow', 'Hive'],
    correctIndex: 3,
    explanation: 'A nest is the home of a bird, and a hive is the home of a bee colony.',
    source,
  },
  {
    id: 'ssc-cgl-t1-gi-006',
    section: 'General Intelligence and Reasoning',
    topic: 'Classification',
    difficulty: 'easy',
    question: 'Which month is different from the other three?',
    options: ['January', 'March', 'May', 'June'],
    correctIndex: 3,
    explanation: 'January, March and May have 31 days. June has 30 days.',
    source,
  },
  {
    id: 'ssc-cgl-t1-gi-007',
    section: 'General Intelligence and Reasoning',
    topic: 'Number classification',
    difficulty: 'easy',
    question: 'Find the number that does not belong with the others.',
    options: ['16', '25', '49', '63'],
    correctIndex: 3,
    explanation: '16, 25 and 49 are perfect squares. 63 is not a perfect square.',
    source,
  },
  {
    id: 'ssc-cgl-t1-gi-008',
    section: 'General Intelligence and Reasoning',
    topic: 'Coding-decoding',
    difficulty: 'easy',
    question: 'In a code, each letter is moved two places forward in the alphabet. If MIND is coded as OKPF, how is COLD coded?',
    options: ['EQNF', 'EPNF', 'FQOG', 'DPME'],
    correctIndex: 0,
    explanation: 'Moving each letter two places forward gives C→E, O→Q, L→N and D→F, so the code is EQNF.',
    source,
  },
  {
    id: 'ssc-cgl-t1-gi-009',
    section: 'General Intelligence and Reasoning',
    topic: 'Alphabet coding',
    difficulty: 'medium',
    question: 'If A = 26, B = 25, C = 24 and so on in reverse alphabetical order, what is the value of CAB?',
    options: ['72', '73', '74', '75'],
    correctIndex: 3,
    explanation: 'C = 24, A = 26 and B = 25. Their total is 24 + 26 + 25 = 75.',
    source,
  },
  {
    id: 'ssc-cgl-t1-gi-010',
    section: 'General Intelligence and Reasoning',
    topic: 'Direction sense',
    difficulty: 'easy',
    question: 'Rohan walks 8 metres north, then 6 metres east, and then 8 metres south. Where is he from his starting point?',
    options: ['6 metres east', '6 metres west', '8 metres north', '8 metres south'],
    correctIndex: 0,
    explanation: 'The north and south movements cancel each other. Rohan is 6 metres east of the starting point.',
    source,
  },
  {
    id: 'ssc-cgl-t1-gi-011',
    section: 'General Intelligence and Reasoning',
    topic: 'Direction sense',
    difficulty: 'easy',
    question: 'A person faces west, turns right, turns right again, and then turns left. Which direction is the person facing?',
    options: ['North', 'South', 'East', 'West'],
    correctIndex: 0,
    explanation: 'From west: right gives north, another right gives east, and then left gives north.',
    source,
  },
  {
    id: 'ssc-cgl-t1-gi-012',
    section: 'General Intelligence and Reasoning',
    topic: 'Blood relations',
    difficulty: 'easy',
    question: 'Kavita has two children, Amit and Riya. Amit is the brother of Riya. How is Riya related to Kavita?',
    options: ['Sister', 'Niece', 'Mother', 'Daughter'],
    correctIndex: 3,
    explanation: 'Riya is one of Kavita’s children and is female, so she is Kavita’s daughter.',
    source,
  },
  {
    id: 'ssc-cgl-t1-gi-013',
    section: 'General Intelligence and Reasoning',
    topic: 'Blood relations',
    difficulty: 'medium',
    question: 'Pointing to a man, Neha says, “He is the only son of my mother’s mother.” How is the man related to Neha?',
    options: ['Father', 'Brother', 'Maternal uncle', 'Paternal uncle'],
    correctIndex: 2,
    explanation: 'Neha’s mother’s mother is her maternal grandmother. That grandmother’s son is Neha’s maternal uncle.',
    source,
  },
  {
    id: 'ssc-cgl-t1-gi-014',
    section: 'General Intelligence and Reasoning',
    topic: 'Ranking',
    difficulty: 'easy',
    question: 'Meera is 18th from the top in a class of 45 students. What is her rank from the bottom?',
    options: ['26th', '27th', '28th', '29th'],
    correctIndex: 2,
    explanation: 'Rank from the bottom = 45 − 18 + 1 = 28.',
    source,
  },
  {
    id: 'ssc-cgl-t1-gi-015',
    section: 'General Intelligence and Reasoning',
    topic: 'Linear arrangement',
    difficulty: 'medium',
    question: 'Five people P, Q, R, S and T sit in a row. R is in the middle, P is immediately to the left of R, T is at the right end, and Q is not next to T. Who sits at the left end?',
    options: ['P', 'Q', 'R', 'S'],
    correctIndex: 1,
    explanation: 'R is third, P is second and T is fifth. Q cannot be fourth because that is next to T, so Q must be first.',
    source,
  },
  {
    id: 'ssc-cgl-t1-gi-016',
    section: 'General Intelligence and Reasoning',
    topic: 'Syllogism',
    difficulty: 'easy',
    question: 'Statements: All roses are flowers. No flower is a stone. Which conclusion follows?',
    options: ['No rose is a stone', 'Some stones are roses', 'All stones are flowers', 'Some flowers are stones'],
    correctIndex: 0,
    explanation: 'Every rose is a flower, and no flower is a stone. Therefore, no rose can be a stone.',
    source,
  },
  {
    id: 'ssc-cgl-t1-gi-017',
    section: 'General Intelligence and Reasoning',
    topic: 'Syllogism',
    difficulty: 'medium',
    question: 'Statements: Some books are novels. All novels are fiction. Conclusions: I. Some books are fiction. II. All books are fiction.',
    options: ['Only conclusion I follows', 'Only conclusion II follows', 'Both conclusions follow', 'Neither conclusion follows'],
    correctIndex: 0,
    explanation: 'The books that are novels must be fiction, so conclusion I follows. Nothing states that every book is fiction, so conclusion II does not follow.',
    source,
  },
  {
    id: 'ssc-cgl-t1-gi-018',
    section: 'General Intelligence and Reasoning',
    topic: 'Logical sequence',
    difficulty: 'easy',
    question: 'Arrange these events in a logical order: 1. Appointment 2. Examination 3. Application 4. Result',
    options: ['3, 2, 4, 1', '2, 3, 4, 1', '3, 4, 2, 1', '2, 4, 3, 1'],
    correctIndex: 0,
    explanation: 'A candidate applies first, takes the examination, receives the result and is then appointed.',
    source,
  },
  {
    id: 'ssc-cgl-t1-gi-019',
    section: 'General Intelligence and Reasoning',
    topic: 'Venn diagrams',
    difficulty: 'medium',
    question: 'In a group of 40 students, 22 like tea, 18 like coffee and 8 like both. How many like neither tea nor coffee?',
    options: ['6', '8', '10', '12'],
    correctIndex: 1,
    explanation: 'Students who like at least one = 22 + 18 − 8 = 32. Therefore, 40 − 32 = 8 like neither.',
    source,
  },
  {
    id: 'ssc-cgl-t1-gi-020',
    section: 'General Intelligence and Reasoning',
    topic: 'Mathematical operations',
    difficulty: 'easy',
    question: 'If “+” means multiplication and “−” means addition, what is the value of 8 + 3 − 4?',
    options: ['24', '28', '32', '36'],
    correctIndex: 1,
    explanation: 'Replace the symbols as stated: 8 × 3 + 4 = 24 + 4 = 28.',
    source,
  },
  {
    id: 'ssc-cgl-t1-gi-021',
    section: 'General Intelligence and Reasoning',
    topic: 'Calendar',
    difficulty: 'medium',
    question: 'In a non-leap year, 1 January is a Monday. What day is 1 February?',
    options: ['Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    correctIndex: 2,
    explanation: 'January has 31 days, which is three days more than four complete weeks. Monday shifted by three days is Thursday.',
    source,
  },
  {
    id: 'ssc-cgl-t1-gi-022',
    section: 'General Intelligence and Reasoning',
    topic: 'Clock',
    difficulty: 'medium',
    question: 'What is the smaller angle between the hour hand and minute hand at 3:30?',
    options: ['60°', '75°', '90°', '105°'],
    correctIndex: 1,
    explanation: 'At 3:30, the minute hand is at 180° and the hour hand is at 105°. The difference is 75°.',
    source,
  },
  {
    id: 'ssc-cgl-t1-gi-023',
    section: 'General Intelligence and Reasoning',
    topic: 'Alphabetical arrangement',
    difficulty: 'easy',
    question: 'If the letters of BRAVE are arranged in alphabetical order, which letter is in the middle?',
    options: ['B', 'E', 'R', 'V'],
    correctIndex: 1,
    explanation: 'The alphabetical order is A, B, E, R, V. The middle letter is E.',
    source,
  },
  {
    id: 'ssc-cgl-t1-gi-024',
    section: 'General Intelligence and Reasoning',
    topic: 'Dictionary order',
    difficulty: 'medium',
    question: 'Which word comes second when these words are arranged in dictionary order: Precise, Predict, Prefer, Prepare?',
    options: ['Precise', 'Predict', 'Prefer', 'Prepare'],
    correctIndex: 1,
    explanation: 'The order is Precise, Predict, Prefer, Prepare because the differing letters are c, d, f and p.',
    source,
  },
  {
    id: 'ssc-cgl-t1-gi-025',
    section: 'General Intelligence and Reasoning',
    topic: 'Order and comparison',
    difficulty: 'easy',
    question: 'A is older than B. B is older than C. D is younger than C. Who is the oldest?',
    options: ['A', 'B', 'C', 'D'],
    correctIndex: 0,
    explanation: 'The order is A older than B, B older than C, and C older than D. Therefore, A is the oldest.',
    source,
  },
];
