import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'Original Territorial Army practice questions in the official 4-option multiple-choice format, covering Reasoning and English from the Territorial Army written examination syllabus.',
  url: 'https://territorialarmy.in/page/5',
  checkedOn: '16 August 2026',
};

export const TERRITORIAL_ARMY_REASONING_AND_ENGLISH_1: Question[] = [
  { id: 'territorial-army-reasoning-and-english-01-001', section: 'Reasoning', topic: 'Number Series', difficulty: 'medium', question: 'Find the next term: 5, 11, 23, 47, ?', options: ['90', '95', '98', '100'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'Each term follows the rule ×2+1: 47 × 2 + 1 = 95.', source },
  { id: 'territorial-army-reasoning-and-english-01-002', section: 'Reasoning', topic: 'Analogy', difficulty: 'easy', question: 'Doctor is to Hospital as Teacher is to ?', options: ['Hospital', 'School', 'Clinic', 'College'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'A doctor works in a hospital, just as a teacher works in a school.', source },
  { id: 'territorial-army-reasoning-and-english-01-003', section: 'Reasoning', topic: 'Coding-Decoding', difficulty: 'medium', question: 'If ROSE is coded as SPTF (each letter shifted one place forward in the alphabet), how is BIRD coded using the same rule?', options: ['CJTE', 'CKSE', 'CJSE', 'BJSE'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'Shifting each letter forward by one: B→C, I→J, R→S, D→E, giving CJSE.', source },
  { id: 'territorial-army-reasoning-and-english-01-004', section: 'Reasoning', topic: 'Blood Relations', difficulty: 'medium', question: 'Pointing to a girl, a woman said, "She is the daughter of my husband\'s sister." How is the girl related to the woman?', options: ['Daughter', 'Sister', 'Cousin', 'Niece'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'The woman\'s husband\'s sister is her sister-in-law, and the sister-in-law\'s daughter is the woman\'s niece.', source },
  { id: 'territorial-army-reasoning-and-english-01-005', section: 'Reasoning', topic: 'Direction Sense', difficulty: 'easy', question: 'A person walks 6 km east, then 8 km north. How far is he from his starting point?', options: ['10 km', '12 km', '14 km', '8 km'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'The path forms a right triangle with legs 6 km and 8 km, so the distance is √(6²+8²) = 10 km.', source },
  { id: 'territorial-army-reasoning-and-english-01-006', section: 'Reasoning', topic: 'Classification', difficulty: 'easy', question: 'Which of the following does not belong with the others?', options: ['Triangle', 'Wood', 'Square', 'Circle'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'Triangle, Square, and Circle are shapes, while Wood is a material.', source },
  { id: 'territorial-army-reasoning-and-english-01-007', section: 'Reasoning', topic: 'Syllogism', difficulty: 'medium', question: 'Statements: All pens are pencils. All pencils are erasers. Conclusion: All pens are erasers. Does the conclusion follow?', options: ['Does not follow', 'Follows only sometimes', 'Follows definitely', 'Cannot be determined'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'Since all pens are pencils and all pencils are erasers, by transitivity all pens are erasers, so the conclusion follows definitely.', source },
  { id: 'territorial-army-reasoning-and-english-01-008', section: 'Reasoning', topic: 'Ranking and Sequence', difficulty: 'easy', question: 'In a class, Meera ranks 15th from the top and 21st from the bottom. How many students are in the class?', options: ['30', '32', '34', '35'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'Total students = (rank from top) + (rank from bottom) − 1 = 15 + 21 − 1 = 35.', source },
  { id: 'territorial-army-reasoning-and-english-01-009', section: 'Reasoning', topic: 'Alphabet Test', difficulty: 'medium', question: 'Which letter is 4th to the right of the 9th letter from the left in the English alphabet?', options: ['M', 'L', 'N', 'K'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'The 9th letter from the left is I. Counting 4 letters to the right: J, K, L, M. The answer is M.', source },
  { id: 'territorial-army-reasoning-and-english-01-010', section: 'Reasoning', topic: 'Ranking and Sequence', difficulty: 'easy', question: 'A patrol of volunteers stands in a single row. Dev is 9th from the left and 14th from the right. How many volunteers are in the row?', options: ['20', '21', '22', '23'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'Total volunteers = rank from the left + rank from the right − 1 = 9 + 14 − 1 = 22.', source },
  { id: 'territorial-army-reasoning-and-english-01-011', section: 'Reasoning', topic: 'Syllogism', difficulty: 'medium', question: 'Statements: All doctors are educated. Some educated people are wealthy. Conclusion: Some doctors are wealthy. Does this conclusion follow?', options: ['Follows definitely', 'Follows only in reverse', 'Does not follow necessarily', 'Data insufficient'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'The wealthy people among the educated need not include any doctors, so the conclusion does not necessarily follow.', source },
  { id: 'territorial-army-reasoning-and-english-01-012', section: 'Reasoning', topic: 'Classification', difficulty: 'medium', question: 'Find the odd one out: 121, 144, 169, 200.', options: ['121', '144', '169', '200'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: '121 = 11², 144 = 12², and 169 = 13² are perfect squares, but 200 is not.', source },
  { id: 'territorial-army-reasoning-and-english-01-013', section: 'English', topic: 'Synonyms', difficulty: 'easy', question: 'Choose the word closest in meaning to "Ambiguous".', options: ['Unclear', 'Clear', 'Certain', 'Precise'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: '"Ambiguous" means open to more than one interpretation, closest to "Unclear".', source },
  { id: 'territorial-army-reasoning-and-english-01-014', section: 'English', topic: 'Antonyms', difficulty: 'easy', question: 'Choose the word opposite in meaning to "Genuine".', options: ['Authentic', 'Fake', 'Real', 'Sincere'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: '"Genuine" means real and authentic; its opposite is "Fake".', source },
  { id: 'territorial-army-reasoning-and-english-01-015', section: 'English', topic: 'Prepositions', difficulty: 'easy', question: 'Fill in the blank: He apologized ___ his mistake.', options: ['with', 'to', 'for', 'of'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'The correct idiomatic preposition is "for": He apologized for his mistake.', source },
  { id: 'territorial-army-reasoning-and-english-01-016', section: 'English', topic: 'Spelling', difficulty: 'easy', question: 'Choose the correctly spelled word.', options: ['Embarass', 'Embarras', 'Emberrass', 'Embarrass'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'The correct spelling is "Embarrass", with double "r" and double "s".', source },
  { id: 'territorial-army-reasoning-and-english-01-017', section: 'English', topic: 'One-Word Substitution', difficulty: 'medium', question: 'Choose the word that means "a place where weapons and military equipment are stored".', options: ['Arsenal', 'Museum', 'Warehouse', 'Factory'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'An "Arsenal" is a place where weapons and military equipment are stored.', source },
  { id: 'territorial-army-reasoning-and-english-01-018', section: 'English', topic: 'Reported Speech', difficulty: 'medium', question: 'Convert to reported speech: She said, "I am tired." → She said that she ___ tired.', options: ['is', 'was', 'were', 'be'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'In reported speech, present tense "am" shifts back to past tense "was".', source },
  { id: 'territorial-army-reasoning-and-english-01-019', section: 'English', topic: 'Idioms and Phrases', difficulty: 'easy', question: 'What does the idiom "to be under the weather" mean?', options: ['To feel very happy', 'To feel very angry', 'To feel slightly ill', 'To feel very hungry'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: '"To be under the weather" means to feel slightly unwell or ill.', source },
  { id: 'territorial-army-reasoning-and-english-01-020', section: 'English', topic: 'Conjunctions', difficulty: 'medium', question: 'Fill in the blank: ___ he was late, he missed the train.', options: ['Although', 'Unless', 'However', 'Since'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: '"Since" correctly introduces the causal reason for missing the train.', source },
  { id: 'territorial-army-reasoning-and-english-01-021', section: 'English', topic: 'Spelling', difficulty: 'easy', question: 'Identify the correctly spelled word from the options below.', options: ['Occurrence', 'Occurence', 'Occurrance', 'Ocurrence'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'The correct spelling is "Occurrence", with double "c" and double "r".', source },
];
