import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'Original Territorial Army practice questions in the official 4-option multiple-choice format, covering Reasoning and English from the Territorial Army written examination syllabus.',
  url: 'https://territorialarmy.in/page/5',
  checkedOn: '16 August 2026',
};

export const TERRITORIAL_ARMY_REASONING_AND_ENGLISH_2: Question[] = [
  { id: 'territorial-army-reasoning-and-english-02-001', section: 'Reasoning', topic: 'Number Series', difficulty: 'medium', question: 'Find the next term: 3, 6, 12, 24, ?', options: ['48', '36', '42', '30'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'Each term is double the previous one, so the next term is 24 × 2 = 48.', source },
  { id: 'territorial-army-reasoning-and-english-02-002', section: 'Reasoning', topic: 'Analogy', difficulty: 'easy', question: 'Judge is to Courtroom as Chef is to ?', options: ['Menu', 'Kitchen', 'Restaurant', 'Recipe'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'A judge works in a courtroom; the corresponding workplace for a chef is a kitchen. A restaurant is the wider establishment, not the workplace itself.', source },
  { id: 'territorial-army-reasoning-and-english-02-003', section: 'Reasoning', topic: 'Coding-Decoding', difficulty: 'medium', question: 'If TANK is coded as UBOL (each letter shifted one place forward in the alphabet), how is GUN coded?', options: ['FTM', 'HVN', 'HVO', 'GVO'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'Shifting each letter one place forward gives G to H, U to V and N to O, producing HVO.', source },
  { id: 'territorial-army-reasoning-and-english-02-004', section: 'Reasoning', topic: 'Blood Relations', difficulty: 'medium', question: 'Pointing to a man, a boy said, "He is the brother of my mother\'s only sister." How is the man related to the boy?', options: ['Father', 'Brother', 'Cousin', 'Maternal uncle'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'The brother of the mother\'s sister is also the mother\'s brother, and the mother\'s brother is the boy\'s maternal uncle.', source },
  { id: 'territorial-army-reasoning-and-english-02-005', section: 'Reasoning', topic: 'Direction Sense', difficulty: 'easy', question: 'A soldier walks 5 km north, turns right and walks 12 km. How far is he from his starting point?', options: ['13 km', '17 km', '7 km', '15 km'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'The two legs are at right angles, so the distance is √(5² + 12²) = √169 = 13 km.', source },
  { id: 'territorial-army-reasoning-and-english-02-006', section: 'Reasoning', topic: 'Classification', difficulty: 'easy', question: 'Which of the following does not belong with the others?', options: ['Rifle', 'Helmet', 'Pistol', 'Revolver'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'A rifle, a pistol and a revolver are all firearms. A helmet is protective equipment, so it is the odd one out.', source },
  { id: 'territorial-army-reasoning-and-english-02-007', section: 'Reasoning', topic: 'Syllogism', difficulty: 'medium', question: 'Statements: All soldiers are brave. Some brave people are officers. Conclusion: Some soldiers are officers. Does the conclusion follow?', options: ['Yes, it follows', 'It follows only if all officers are brave', 'No, it does not follow', 'The statements contradict each other'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'The brave people who are officers need not be among the soldiers, so no overlap between soldiers and officers is forced. This is an undistributed middle.', source },
  { id: 'territorial-army-reasoning-and-english-02-008', section: 'Reasoning', topic: 'Ranking and Sequence', difficulty: 'easy', question: 'In a row of 40 cadets, Arjun is 12th from the left end. What is his position from the right end?', options: ['27th', '30th', '28th', '29th'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'Position from the right = total − position from the left + 1 = 40 − 12 + 1 = 29th.', source },
  { id: 'territorial-army-reasoning-and-english-02-009', section: 'Reasoning', topic: 'Alphabet Test', difficulty: 'medium', question: 'Which letter is 5th to the left of the 20th letter from the left in the English alphabet?', options: ['O', 'P', 'N', 'M'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'The 20th letter from the left is T. Counting 5 places to its left gives the 15th letter, which is O.', source },
  { id: 'territorial-army-reasoning-and-english-02-010', section: 'Reasoning', topic: 'Ranking and Sequence', difficulty: 'medium', question: 'Among five friends, P is taller than Q but shorter than R. S is taller than R. T is the shortest of all. Who is the tallest?', options: ['R', 'S', 'P', 'Q'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'The order from tallest is S, R, P, Q, T, so S is the tallest.', source },
  { id: 'territorial-army-reasoning-and-english-02-011', section: 'Reasoning', topic: 'Number Series', difficulty: 'medium', question: 'Find the missing term: 2, 6, 12, 20, 30, ?', options: ['36', '40', '42', '38'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'The differences are 4, 6, 8 and 10, increasing by 2 each time, so the next difference is 12 and the next term is 30 + 12 = 42.', source },
  { id: 'territorial-army-reasoning-and-english-02-012', section: 'Reasoning', topic: 'Coding-Decoding', difficulty: 'hard', question: 'In a certain code, ARMY is written as 1-18-13-25 using the position of each letter in the alphabet. How is NAVY written in that code?', options: ['13-1-22-25', '14-1-21-25', '14-2-22-25', '14-1-22-25'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'N is the 14th letter, A the 1st, V the 22nd and Y the 25th, giving 14-1-22-25.', source },
  { id: 'territorial-army-reasoning-and-english-02-013', section: 'English', topic: 'Synonyms', difficulty: 'easy', question: 'Choose the word closest in meaning to "Valiant".', options: ['Courageous', 'Cowardly', 'Careless', 'Cautious'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: '"Valiant" means showing courage or determination, closest to "Courageous".', source },
  { id: 'territorial-army-reasoning-and-english-02-014', section: 'English', topic: 'Antonyms', difficulty: 'easy', question: 'Choose the word opposite in meaning to "Scarce".', options: ['Rare', 'Abundant', 'Limited', 'Sparse'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: '"Scarce" means in short supply; its opposite is "Abundant". Rare, limited and sparse are all close in sense to scarce.', source },
  { id: 'territorial-army-reasoning-and-english-02-015', section: 'English', topic: 'Prepositions', difficulty: 'easy', question: 'Fill in the blank: The soldier was accused ___ negligence.', options: ['for', 'with', 'of', 'about'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'The verb "accuse" takes the preposition "of": accused of negligence.', source },
  { id: 'territorial-army-reasoning-and-english-02-016', section: 'English', topic: 'Spelling', difficulty: 'easy', question: 'Choose the correctly spelled word from the options below.', options: ['Reconaissance', 'Reconnaisance', 'Reconnaissence', 'Reconnaissance'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'The correct spelling is "Reconnaissance", with double "n", double "s" and the ending "-ance".', source },
  { id: 'territorial-army-reasoning-and-english-02-017', section: 'English', topic: 'One-Word Substitution', difficulty: 'medium', question: 'Choose the word that means "a person who has served in the armed forces and is now retired".', options: ['Veteran', 'Recruit', 'Cadet', 'Conscript'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'A "Veteran" is a former member of the armed forces. A recruit, a cadet and a conscript are all people at the start of service, not after it.', source },
  { id: 'territorial-army-reasoning-and-english-02-018', section: 'English', topic: 'Idioms and Phrases', difficulty: 'easy', question: 'What does the idiom "to stand one\'s ground" mean?', options: ['To retreat quickly', 'To refuse to give way under pressure', 'To remain silent', 'To change one\'s opinion'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: '"To stand one\'s ground" means to hold a position or opinion despite pressure to abandon it.', source },
  { id: 'territorial-army-reasoning-and-english-02-019', section: 'English', topic: 'Conjunctions', difficulty: 'medium', question: 'Fill in the blank: ___ the orders were clear, the unit still hesitated.', options: ['Because', 'Since', 'Although', 'Unless'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'The clause contrasts clear orders with hesitation, so it needs the concessive conjunction "Although".', source },
  { id: 'territorial-army-reasoning-and-english-02-020', section: 'English', topic: 'Reported Speech', difficulty: 'medium', question: 'Convert to reported speech: The officer said, "We will march at dawn." → The officer said that they ___ march at dawn.', options: ['will', 'shall', 'can', 'would'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: 'In reported speech after a past reporting verb, "will" shifts back to "would".', source },
  { id: 'territorial-army-reasoning-and-english-02-021', section: 'English', topic: 'Antonyms', difficulty: 'medium', question: 'Choose the word opposite in meaning to "Retreat".', options: ['Advance', 'Withdraw', 'Retire', 'Recede'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0.33, explanation: '"Retreat" means to move back; its opposite is "Advance". Withdraw, retire and recede all carry the same backward sense as retreat.', source },
];
