import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'Original TOEFL iBT Reading practice text and multiple-choice question in the Read in Daily Life task-type style used in the official 2026 TOEFL iBT Reading section.',
  url: 'https://www.ets.org/toefl/test-takers/ibt/about/content/reading.html',
  checkedOn: '14 August 2026',
};

const read = (text: string, q: string) => `Read the text and answer the question that follows.\n\n${text}\n\nQuestion: ${q}`;

export const TOEFL_READING_READ_IN_DAILY_LIFE_1: Question[] = [
  { id: 'toefl-reading-read-in-daily-life-01-001', section: 'Read in Daily Life', topic: 'Detail', difficulty: 'easy', question: read('Riverside Parking Garage: Rates are $3 per hour for the first three hours, then a flat $15 for any stay beyond three hours. Monthly permit holders park free at any time. Lost ticket holders are charged the maximum daily rate of $15.', 'How much does a four-hour stay cost for a driver without a monthly permit?'), options: ['$15', '$12', '$9', '$18'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: "A stay beyond three hours is charged the flat $15 rate, regardless of the exact length.", source },
  { id: 'toefl-reading-read-in-daily-life-01-002', section: 'Read in Daily Life', topic: 'Detail', difficulty: 'easy', question: read('Notice from Maple Street Library: Borrowed items are due 21 days after checkout. Items returned late incur a fine of 25 cents per day, capped at $5 per item. Items more than 30 days overdue are considered lost and billed at full replacement cost.', 'What happens to an item that is 35 days overdue?'), options: ['It is fined 25 cents per day with no cap', 'It is billed at full replacement cost as lost', 'It is automatically renewed', 'It is fined the maximum $5 only'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The notice states items more than 30 days overdue are considered lost and billed at full replacement cost.', source },
  { id: 'toefl-reading-read-in-daily-life-01-003', section: 'Read in Daily Life', topic: 'Main Idea', difficulty: 'easy', question: read('Sunrise Apartments Recycling Schedule: Paper and cardboard are collected every Monday. Glass and plastic are collected every Thursday. Bulk items such as furniture require a separate pickup request submitted at least 48 hours in advance through the building office.', 'What is the main purpose of this notice?'), options: ['To announce a rent increase', 'To advertise a furniture sale', 'To inform residents of recycling collection days and bulk-item procedures', 'To explain a change in building management'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The notice communicates specific collection days and the procedure for bulk-item pickup, both informational rather than promotional or administrative-change content.', source },
  { id: 'toefl-reading-read-in-daily-life-01-004', section: 'Read in Daily Life', topic: 'Detail', difficulty: 'medium', question: read('Confirmation: Your table for four at Cedar Grove Bistro is booked for 7:30 p.m. on Saturday. Reservations are held for 15 minutes past the booked time; after that, the table may be released to walk-in guests. Please call ahead if you expect to arrive later than 7:45 p.m.', 'By what time must the party arrive to be guaranteed their table without calling ahead?'), options: ['7:30 p.m.', '8:15 p.m.', '8:00 p.m.', '7:45 p.m.'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The reservation is held 15 minutes past 7:30 p.m., meaning until 7:45 p.m., matching the stated call-ahead threshold.', source },
  { id: 'toefl-reading-read-in-daily-life-01-005', section: 'Read in Daily Life', topic: 'Inference', difficulty: 'medium', question: read('Notice at Fit Zone Gym: The 6 a.m. spin class on Wednesday is cancelled this week due to instructor illness. Members may attend the 6 a.m. spin class on Friday instead, or use any other scheduled class this week at no extra charge.', 'What can be inferred about Fit Zone Gym\'s policy toward cancelled classes?'), options: ['Members are offered a substitute option rather than losing the session entirely', 'Members receive no alternative if a class is cancelled', 'Members must pay extra to attend a different class', 'The gym closes entirely when an instructor is unavailable'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The notice offers a Friday substitute or any other class at no extra charge, implying the gym compensates members for a cancelled session rather than simply cancelling it outright.', source },
  { id: 'toefl-reading-read-in-daily-life-01-006', section: 'Read in Daily Life', topic: 'Detail', difficulty: 'easy', question: read('Shipping update: Your order has left the warehouse and is expected to arrive within 3 to 5 business days. Weekend days are not counted as business days. If your order has not arrived within 7 business days, contact customer support for a replacement or refund.', 'What should a customer do if the order has not arrived within 7 business days?'), options: ['Wait an additional 7 business days before taking action', 'Contact customer support for a replacement or refund', 'Assume the order was cancelled automatically', 'Return the order to the warehouse in person'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The update states that if the order has not arrived within 7 business days, the customer should contact customer support for a replacement or refund.', source },
  { id: 'toefl-reading-read-in-daily-life-01-007', section: 'Read in Daily Life', topic: 'Detail', difficulty: 'medium', question: read('Westview University Housing Office: Returning students must submit their housing application by March 1 to keep their current room assignment. Applications submitted between March 2 and March 15 are placed in a general waitlist pool. No applications are accepted after March 15.', 'A returning student who applies on March 10 will be:'), options: ['Automatically assigned their current room', 'Rejected outright', 'Placed in the general waitlist pool', 'Given priority over new students'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'March 10 falls between March 2 and March 15, the window explicitly described as resulting in waitlist placement.', source },
  { id: 'toefl-reading-read-in-daily-life-01-008', section: 'Read in Daily Life', topic: 'Detail', difficulty: 'easy', question: read('Trail Advisory: Pine Ridge Trail is closed above the 2,000-metre marker due to snow and ice. The lower loop, up to the marker, remains open and is considered suitable for most hikers. Check conditions again before any visit after significant rainfall.', 'What portion of Pine Ridge Trail remains open according to the advisory?'), options: ['The entire trail', 'Only the section above 2,000 metres', 'No part of the trail', 'The lower loop up to the 2,000-metre marker'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The advisory states the lower loop, up to the marker, remains open, while the section above 2,000 metres is closed.', source },
  { id: 'toefl-reading-read-in-daily-life-01-009', section: 'Read in Daily Life', topic: 'Detail', difficulty: 'medium', question: read('Paws & Play Daycare: Drop-off is accepted between 7 a.m. and 9:30 a.m. Pick-up must occur before 6 p.m.; a late fee of $10 applies for every 15 minutes past closing. Same-day drop-offs after 9:30 a.m. require advance approval from staff.', 'What is required for a pet owner who wants to drop off their pet at 10 a.m. the same day?'), options: ['Advance approval from staff', 'Nothing extra; drop-off is always accepted until 6 p.m.', 'Payment of the late fee in advance', 'A doctor\'s note confirming the pet is healthy'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The notice states same-day drop-offs after 9:30 a.m. require advance approval from staff.', source },
  { id: 'toefl-reading-read-in-daily-life-01-010', section: 'Read in Daily Life', topic: 'Main Idea', difficulty: 'easy', question: read('Riverside Farmers Market Vendor Rules: All vendors must arrive by 6:30 a.m. to set up before the 7 a.m. opening. Vendors selling prepared food must display a current health permit at their stall. Stalls left unattended for more than 20 minutes may be reassigned.', 'What is this notice primarily about?'), options: ['Advertising the market to shoppers', 'Setting requirements and rules for vendors', 'Announcing the market\'s permanent closure', 'Recruiting new market staff'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The notice lists arrival times, permit requirements, and stall-attendance rules, all directed at vendors rather than shoppers or staff recruitment.', source },
  { id: 'toefl-reading-read-in-daily-life-01-011', section: 'Read in Daily Life', topic: 'Detail', difficulty: 'medium', question: read('Fire Safety Notice, Oakwood Office Tower: A mandatory fire drill will occur on the third Tuesday of every month at 10 a.m. Employees must use the stairwells, not the elevators, and gather at the designated assembly point in the north parking lot.', 'According to the notice, what should employees avoid using during the drill?'), options: ['Stairwells', 'The north parking lot', 'Elevators', 'Fire extinguishers'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The notice specifies employees must use the stairwells, not the elevators.', source },
  { id: 'toefl-reading-read-in-daily-life-01-012', section: 'Read in Daily Life', topic: 'Detail', difficulty: 'medium', question: read('Coupon Terms: This 20% discount applies to a single regularly priced item and cannot be combined with any other offer. The coupon expires 30 days from the date of issue and has no cash value. One coupon per customer per visit.', 'Can this coupon be used together with another store promotion?'), options: ['Yes, always', 'Yes, but only on regularly priced items', 'Only if the customer asks a manager', 'No, it cannot be combined with any other offer'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The terms explicitly state the discount cannot be combined with any other offer.', source },
  { id: 'toefl-reading-read-in-daily-life-01-013', section: 'Read in Daily Life', topic: 'Inference', difficulty: 'medium', question: read('Notice: Your free trial of CloudNote Premium ends in 5 days. After the trial, your account will automatically switch to a paid monthly subscription unless you cancel before the trial ends. You can cancel anytime from the account settings page.', 'What can be inferred if a user takes no action before the trial ends?'), options: ['The user will be charged for a paid subscription automatically', 'The account will be deleted permanently', 'The trial will simply restart for another 5 days', 'Nothing will change and the trial continues indefinitely'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The notice states the account automatically switches to a paid subscription unless cancelled before the trial ends.', source },
  { id: 'toefl-reading-read-in-daily-life-01-014', section: 'Read in Daily Life', topic: 'Detail', difficulty: 'easy', question: read('Lost and Found, Central Station: A blue backpack was found on Platform 3 on Tuesday morning. It is being held at the station office for 14 days. After that period, unclaimed items are donated to a local charity.', 'What happens to the backpack if it remains unclaimed after 14 days?'), options: ['It is thrown away', 'It is donated to a local charity', 'It is returned to Platform 3', 'It is sold at auction'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The notice states unclaimed items are donated to a local charity after the 14-day holding period.', source },
  { id: 'toefl-reading-read-in-daily-life-01-015', section: 'Read in Daily Life', topic: 'Detail', difficulty: 'medium', question: read('Community Pool Safety Rules: Children under 8 must be accompanied by an adult at all times in the water. Diving is permitted only in the marked deep-end area. The pool closes for 10 minutes every hour for a scheduled safety check.', 'Where is diving permitted according to the rules?'), options: ['Anywhere in the pool', 'Only during the scheduled safety check', 'Only in the marked deep-end area', 'Diving is not permitted at all'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The rules state diving is permitted only in the marked deep-end area.', source },
];
