import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'Original TOEFL iBT Reading academic passage and multiple-choice questions in the Read an Academic Passage task-type style used in the official 2026 TOEFL iBT Reading section.',
  url: 'https://www.ets.org/toefl/test-takers/ibt/about/content/reading.html',
  checkedOn: '14 August 2026',
};

const POTATO_PASSAGE = `The potato was first domesticated in the Andean highlands of present-day Peru and Bolivia more than seven thousand years ago, developed by indigenous farmers from wild tuber-bearing plants that grew at high altitude. Early varieties were adapted to cold nights and thin soil, conditions unsuitable for most cereal crops, which made the potato a reliable food source in a region where grain agriculture struggled. Spanish colonizers encountered the crop in the sixteenth century and transported it to Europe, where it spread slowly at first: many Europeans regarded it with suspicion, associating unfamiliar tubers with poison or disease. Adoption accelerated through the eighteenth century as governments recognized the potato's high caloric yield per unit of land, promoting it during periods of grain shortage. By the nineteenth century, the potato had become a dietary staple across much of Northern Europe, though this reliance carried risk: a single fungal disease, potato blight, could devastate an entire region's food supply, as it did in Ireland in the 1840s. Modern agricultural science has since developed blight-resistant varieties and diversified potato cultivation across many countries, reducing the danger of a single-crop failure repeating on the same scale.`;

const REEF_PASSAGE = `Coral reefs support a disproportionately large share of marine tourism revenue relative to the small fraction of ocean floor they cover. Snorkeling and diving operators depend on reef health to attract visitors, and in many coastal economies, reef-based tourism generates far more annual income than fishing conducted in the same waters. This economic reality has prompted some conservation groups to argue that protecting reefs is not only an ecological priority but a sound financial one, since a degraded reef with reduced fish diversity and coral cover draws fewer visitors over time. Studies comparing protected and unprotected reef sites have generally found that marine protected areas, where fishing and anchoring are restricted, retain higher coral cover and larger fish populations than similar unprotected sites nearby, benefits which appear to translate into more repeat tourist visits. However, tourism itself is not free of impact: excessive visitor traffic, careless anchoring, and pollution from coastal development can offset conservation gains if left unmanaged. Several destinations have responded by capping daily visitor numbers or requiring certified guides, aiming to balance continued economic benefit against the ecological carrying capacity of a given reef site.`;

const ICE_CORE_PASSAGE = `Researchers studying long-term climate change rely heavily on ice cores, cylindrical samples drilled from glaciers and ice sheets that preserve a chronological record of atmospheric conditions stretching back tens or even hundreds of thousands of years. As snow accumulates and compacts into ice over time, it traps small bubbles of the atmosphere present at that moment, along with dust, volcanic ash, and other particles. By analyzing the chemical composition of these trapped bubbles layer by layer, scientists can reconstruct past concentrations of gases such as carbon dioxide and methane, as well as estimate historical temperatures using the ratio of different oxygen isotopes present in the ice itself. Glacial retreat, the shrinking of a glacier's mass over time, complicates this research in two ways: it can physically destroy older ice layers before they are sampled, and it signals a warming trend that itself becomes part of the very record scientists are trying to measure. Some research teams have prioritized drilling at rapidly retreating sites specifically to recover ice cores before the oldest layers are lost, treating certain glaciers as an archive under an active deadline rather than a permanent resource.`;

const read = (passage: string, q: string) => `Read the passage and answer the question that follows.\n\n${passage}\n\nQuestion: ${q}`;

export const TOEFL_READING_READ_AN_ACADEMIC_PASSAGE_1: Question[] = [
  { id: 'toefl-reading-read-an-academic-passage-01-001', section: 'Read an Academic Passage', topic: 'Main Idea', difficulty: 'easy', question: read(POTATO_PASSAGE, 'What is the main focus of the passage?'), options: ['The potato\'s domestication, spread, and the risks of relying on it as a staple crop', 'The nutritional content of the potato compared with grain crops', 'The chemical process of potato blight infection', 'A comparison of Andean and European farming techniques in general'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage traces domestication in the Andes, spread to Europe, and the risk illustrated by the Irish famine, covering the full arc described in this option.', source },
  { id: 'toefl-reading-read-an-academic-passage-01-002', section: 'Read an Academic Passage', topic: 'Detail', difficulty: 'easy', question: read(POTATO_PASSAGE, 'Where was the potato first domesticated?'), options: ['Coastal regions of Spain', 'The Andean highlands of present-day Peru and Bolivia', 'Lowland river valleys in Ireland', 'Northern European plains'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage states the potato "was first domesticated in the Andean highlands of present-day Peru and Bolivia."', source },
  { id: 'toefl-reading-read-an-academic-passage-01-003', section: 'Read an Academic Passage', topic: 'Detail', difficulty: 'medium', question: read(POTATO_PASSAGE, 'Why was the potato well suited to its region of origin, according to the passage?'), options: ['It required warm nights and rich soil', 'It grew only in coastal climates', 'It was adapted to cold nights and thin soil, unlike most cereal crops', 'It needed constant irrigation to survive'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage states early varieties "were adapted to cold nights and thin soil, conditions unsuitable for most cereal crops."', source },
  { id: 'toefl-reading-read-an-academic-passage-01-004', section: 'Read an Academic Passage', topic: 'Detail', difficulty: 'medium', question: read(POTATO_PASSAGE, 'Why did the potato spread slowly in Europe at first?'), options: ['It could not survive the European climate', 'It was too expensive to import', 'European governments banned its cultivation', 'Many Europeans associated unfamiliar tubers with poison or disease'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage states many Europeans "regarded it with suspicion, associating unfamiliar tubers with poison or disease."', source },
  { id: 'toefl-reading-read-an-academic-passage-01-005', section: 'Read an Academic Passage', topic: 'Detail', difficulty: 'medium', question: read(POTATO_PASSAGE, 'What historical event illustrates the risk of relying on a single crop, according to the passage?'), options: ['The Irish famine caused by potato blight in the 1840s', 'The Spanish colonization of the Andes', 'The eighteenth-century European grain shortage', 'The development of blight-resistant varieties'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage cites potato blight devastating an entire region\'s food supply "as it did in Ireland in the 1840s."', source },
  { id: 'toefl-reading-read-an-academic-passage-01-006', section: 'Read an Academic Passage', topic: 'Main Idea', difficulty: 'easy', question: read(REEF_PASSAGE, 'What is the passage mainly about?'), options: ['The biology of coral reproduction', 'The economic case for coral reef conservation and the risks tourism itself poses', 'A history of scuba diving as a sport', 'Government funding formulas for marine parks'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage discusses reef tourism revenue, the financial argument for conservation, supporting research, and the risks tourism itself can pose, matching this option.', source },
  { id: 'toefl-reading-read-an-academic-passage-01-007', section: 'Read an Academic Passage', topic: 'Detail', difficulty: 'medium', question: read(REEF_PASSAGE, 'According to the passage, how does reef-based tourism income compare with fishing income in many coastal economies?'), options: ['Fishing generates far more income than reef tourism', 'The two generate roughly identical income', 'Reef tourism generates far more annual income than fishing in the same waters', 'Fishing income cannot be compared to tourism income'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage states reef-based tourism "generates far more annual income than fishing conducted in the same waters."', source },
  { id: 'toefl-reading-read-an-academic-passage-01-008', section: 'Read an Academic Passage', topic: 'Detail', difficulty: 'medium', question: read(REEF_PASSAGE, 'What argument do some conservation groups make, according to the passage?'), options: ['That reef protection is only an ecological concern, not a financial one', 'That fishing should replace tourism as the primary reef-based industry', 'That reef tourism should be banned entirely', 'That protecting reefs is both an ecological priority and a sound financial decision'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage states these groups argue protecting reefs "is not only an ecological priority but a sound financial one."', source },
  { id: 'toefl-reading-read-an-academic-passage-01-009', section: 'Read an Academic Passage', topic: 'Detail', difficulty: 'medium', question: read(REEF_PASSAGE, 'What did studies comparing protected and unprotected reef sites generally find?'), options: ['Protected sites retained higher coral cover and larger fish populations', 'Protected sites had lower coral cover and fewer fish', 'No measurable difference between the two types of sites', 'Unprotected sites attracted more repeat tourist visits'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage states marine protected areas "retain higher coral cover and larger fish populations than similar unprotected sites nearby."', source },
  { id: 'toefl-reading-read-an-academic-passage-01-010', section: 'Read an Academic Passage', topic: 'Inference', difficulty: 'hard', question: read(REEF_PASSAGE, 'What can be inferred about tourism itself as a factor in reef health?'), options: ['Tourism always helps reef health with no downside', 'Unmanaged tourism can offset conservation gains through overcrowding, anchoring damage, and pollution', 'Tourism has no measurable impact on reefs at all', 'Tourism is entirely separate from reef conservation efforts'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage states "tourism itself is not free of impact: excessive visitor traffic, careless anchoring, and pollution... can offset conservation gains if left unmanaged."', source },
  { id: 'toefl-reading-read-an-academic-passage-01-011', section: 'Read an Academic Passage', topic: 'Main Idea', difficulty: 'medium', question: read(ICE_CORE_PASSAGE, 'What is the main purpose of the passage?'), options: ['To explain how snow forms in the atmosphere', 'To argue that glaciers should be protected as tourist attractions', 'To describe how ice cores are used to study past climate and the challenges glacial retreat poses to that research', 'To compare drilling equipment used in different countries'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage explains what ice cores reveal about past climate and how glacial retreat complicates this research, matching this summary.', source },
  { id: 'toefl-reading-read-an-academic-passage-01-012', section: 'Read an Academic Passage', topic: 'Detail', difficulty: 'easy', question: read(ICE_CORE_PASSAGE, 'What do ice cores preserve, according to the passage?'), options: ['A record limited to the last ten years', 'A record of ocean temperatures only', 'A visual timeline drawn by researchers', 'A chronological record of atmospheric conditions, trapped in bubbles within the ice'], correctIndex: 3, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage states ice cores "preserve a chronological record of atmospheric conditions" through trapped bubbles.', source },
  { id: 'toefl-reading-read-an-academic-passage-01-013', section: 'Read an Academic Passage', topic: 'Detail', difficulty: 'medium', question: read(ICE_CORE_PASSAGE, 'How do scientists estimate historical temperatures from ice cores?'), options: ['By using the ratio of different oxygen isotopes present in the ice', 'By measuring the thickness of each ice layer only', 'By counting the number of dust particles trapped in the ice', 'By comparing ice core samples to modern weather station data only'], correctIndex: 0, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage states scientists "estimate historical temperatures using the ratio of different oxygen isotopes present in the ice itself."', source },
  { id: 'toefl-reading-read-an-academic-passage-01-014', section: 'Read an Academic Passage', topic: 'Detail', difficulty: 'hard', question: read(ICE_CORE_PASSAGE, 'In what two ways does glacial retreat complicate ice-core research, according to the passage?'), options: ['It only makes drilling equipment more expensive', 'It destroys older ice layers before sampling, and it is itself part of the warming record being measured', 'It has no real effect on the research process', 'It causes researchers to stop studying glaciers entirely'], correctIndex: 1, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: "The passage states retreat \"can physically destroy older ice layers before they are sampled, and it signals a warming trend that itself becomes part of the very record scientists are trying to measure.\"", source },
  { id: 'toefl-reading-read-an-academic-passage-01-015', section: 'Read an Academic Passage', topic: 'Inference', difficulty: 'hard', question: read(ICE_CORE_PASSAGE, 'Why have some research teams prioritized drilling at rapidly retreating glacier sites?'), options: ['To avoid the expense of researching stable glaciers', 'Because rapidly retreating glaciers are easier to access', 'To recover ice cores before the oldest layers are lost to melting', 'Because those sites require less specialized equipment'], correctIndex: 2, answerType: 'mcq', marks: 1, negativeMarking: 0, explanation: 'The passage states these teams treat certain glaciers "as an archive under an active deadline," prioritizing sites to recover cores before the oldest layers are lost.', source },
];
