import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'Civil Services Examination, 2026 official notification (Examination Notice No. 05/2026-CSE) — Preliminary Examination, CSAT (General Studies Paper II) syllabus: Comprehension',
  url: 'https://www.upsc.gov.in/sites/default/files/Notif-CSP-2026-Engl-060226Rev.pdf',
  checkedOn: '5 August 2026',
};

const urbanPassage = 'Rapid urbanization in developing countries has placed enormous strain on municipal infrastructure, particularly in the areas of water supply, waste management, and public transport. Unlike planned urban expansion, much of this growth has been unplanned, leading to the proliferation of informal settlements that often lack basic services. Policymakers increasingly argue that addressing this challenge requires not merely building new infrastructure, but also strengthening the institutional capacity of local governments to plan, finance, and maintain it over the long term.';
const energyPassage = 'Solar and wind power have become the cheapest sources of new electricity generation in many parts of the world, a dramatic shift from a decade ago when they were dismissed as prohibitively expensive. This cost decline has been driven primarily by manufacturing scale, technological improvement, and falling battery storage costs, which help address the intermittency problem inherent in relying on sunlight and wind. However, integrating large shares of variable renewable energy into existing electricity grids still requires substantial investment in transmission infrastructure and grid flexibility.';
const healthPassage = "The overuse and misuse of antimicrobial drugs in both humans and livestock has accelerated the emergence of drug-resistant pathogens, a phenomenon public health experts now regard as one of the most serious long-term threats to global health. Unlike a single disease outbreak, antimicrobial resistance undermines the effectiveness of medicine broadly, making routine surgeries and common infections increasingly dangerous to treat. Addressing it requires coordinated action across human health, animal health, and environmental sectors, an approach often referred to as 'One Health.'";
const educationPassage = 'Enrollment in primary education has risen sharply across most developing countries over the past two decades, yet learning outcomes have often failed to keep pace. Surveys repeatedly find that a significant proportion of children who complete several years of schooling remain unable to read a simple text or perform basic arithmetic appropriate to their grade level. This gap between access and actual learning has prompted a shift in policy focus, from measuring enrollment and infrastructure alone toward directly assessing foundational literacy and numeracy.';
const spacePassage = 'The declining cost of launching satellites into orbit, driven substantially by reusable rocket technology, has opened space to a much wider range of commercial and scientific applications than were feasible even a decade ago. Small satellite constellations now support global internet connectivity, agricultural monitoring, and disaster response, areas once dominated exclusively by a handful of national space agencies. This democratization of access to space, however, has also raised new concerns about orbital congestion and the long-term sustainability of the space environment.';
const waterPassage = 'Agriculture accounts for the largest share of freshwater withdrawals in most countries, yet a substantial portion of this water is lost to inefficient irrigation practices before it ever reaches crops. Drip irrigation and other precision methods can reduce water use significantly while often improving yields, but their adoption remains limited among smallholder farmers, who frequently lack the capital needed for upfront investment. Expanding access to affordable financing, alongside targeted extension services, is increasingly seen as essential to scaling up water-efficient agriculture.';

export const UPSC_CSE_PAPER_2_COMPREHENSION_1: Question[] = [
  { id: 'upsc-cse-p2-comp-001', section: 'Comprehension', topic: 'Reading Comprehension', difficulty: 'medium', question: `${urbanPassage}\n\nAccording to the passage, informal settlements typically arise mainly because of:`, options: ['Unplanned urban growth', 'A deliberate government policy to house the urban poor', 'A shortage of building materials', 'Excessive municipal spending on transport'], correctIndex: 0, explanation: 'The passage states that unplanned growth, unlike planned urban expansion, leads to the proliferation of informal settlements.', source },
  { id: 'upsc-cse-p2-comp-002', section: 'Comprehension', topic: 'Reading Comprehension', difficulty: 'medium', question: `${urbanPassage}\n\nThe passage suggests that effectively addressing urban infrastructure strain requires:`, options: ['Stronger institutional capacity of local governments alongside new infrastructure', 'New infrastructure alone', 'Reducing the rate of urban population growth', 'Shifting all municipal services to private companies'], correctIndex: 0, explanation: 'The passage argues that addressing the challenge requires not merely new infrastructure but also stronger institutional capacity in local governments.', source },
  { id: 'upsc-cse-p2-comp-003', section: 'Comprehension', topic: 'Reading Comprehension', difficulty: 'hard', question: `${urbanPassage}\n\nWhich of the following best captures the central idea of the passage?`, options: ['Rapid, unplanned urbanization strains infrastructure and calls for stronger local governance, not construction alone', 'Urban infrastructure problems are caused entirely by a lack of funding', 'Informal settlements are a minor and temporary feature of urban growth', 'Municipal infrastructure planning is primarily a national, not local, responsibility'], correctIndex: 0, explanation: 'The passage centres on how unplanned urbanization strains infrastructure and argues that solving this needs stronger local institutional capacity, not just new construction.', source },
  { id: 'upsc-cse-p2-comp-004', section: 'Comprehension', topic: 'Reading Comprehension', difficulty: 'medium', question: `${energyPassage}\n\nAccording to the passage, the fall in the cost of solar and wind power is mainly attributed to:`, options: ['Government subsidies alone', 'A decline in global electricity demand', 'Manufacturing scale, technological improvement, and falling battery storage costs', 'The exhaustion of fossil fuel reserves'], correctIndex: 2, explanation: 'The passage attributes the cost decline primarily to manufacturing scale, technological improvement, and falling battery storage costs.', source },
  { id: 'upsc-cse-p2-comp-005', section: 'Comprehension', topic: 'Reading Comprehension', difficulty: 'medium', question: `${energyPassage}\n\nAccording to the passage, what challenge remains even as renewable energy costs fall?`, options: ['Renewable energy remains more expensive than fossil fuels', 'Solar and wind technologies have stopped improving', 'Integrating variable renewable energy into grids requires investment in transmission and flexibility', 'Battery storage costs continue to rise'], correctIndex: 2, explanation: 'The passage notes that integrating large shares of variable renewable energy into grids still requires substantial investment in transmission infrastructure and grid flexibility.', source },
  { id: 'upsc-cse-p2-comp-006', section: 'Comprehension', topic: 'Reading Comprehension', difficulty: 'hard', question: `${energyPassage}\n\nIn the passage, the word "intermittency" most nearly refers to:`, options: ['The high cost of renewable energy technology', 'The slow pace of grid infrastructure investment', 'The inconsistent, variable availability of sunlight and wind', 'The declining efficiency of battery storage'], correctIndex: 2, explanation: 'In context, "intermittency" refers to the variable, inconsistent availability of sunlight and wind as energy sources.', source },
  { id: 'upsc-cse-p2-comp-007', section: 'Comprehension', topic: 'Reading Comprehension', difficulty: 'medium', question: `${healthPassage}\n\nAccording to the passage, antimicrobial resistance is considered particularly serious because it:`, options: ['Affects only livestock and not humans', 'Is limited to a small number of countries', 'Undermines the effectiveness of medicine broadly, not just one disease', 'Can be fully solved by a single new vaccine'], correctIndex: 2, explanation: 'The passage states that, unlike a single disease outbreak, antimicrobial resistance undermines the effectiveness of medicine broadly.', source },
  { id: 'upsc-cse-p2-comp-008', section: 'Comprehension', topic: 'Reading Comprehension', difficulty: 'medium', question: `${healthPassage}\n\nBesides human health, which two sectors does the passage identify as relevant to antimicrobial resistance?`, options: ['Education and transport', 'Tourism and manufacturing', 'Finance and trade', 'Animal health and the environment'], correctIndex: 3, explanation: 'The passage identifies animal health and environmental sectors, alongside human health, as relevant to addressing antimicrobial resistance.', source },
  { id: 'upsc-cse-p2-comp-009', section: 'Comprehension', topic: 'Reading Comprehension', difficulty: 'hard', question: `${healthPassage}\n\nAs used in the passage, the term "One Health" refers to:`, options: ['A single global health insurance scheme', 'A method for ranking countries by health outcomes', 'A World Health Organization vaccination programme', 'A coordinated approach spanning human, animal, and environmental health'], correctIndex: 3, explanation: 'The passage defines "One Health" as a coordinated approach spanning human health, animal health, and environmental sectors.', source },
  { id: 'upsc-cse-p2-comp-010', section: 'Comprehension', topic: 'Reading Comprehension', difficulty: 'medium', question: `${educationPassage}\n\nThe central problem highlighted in the passage is:`, options: ['Declining school enrollment in developing countries', 'Falling government spending on education', 'A shortage of school buildings', 'A persistent gap between rising enrollment and actual learning outcomes'], correctIndex: 3, explanation: 'The passage centres on how learning outcomes have failed to keep pace with rising enrollment, creating an access-learning gap.', source },
  { id: 'upsc-cse-p2-comp-011', section: 'Comprehension', topic: 'Reading Comprehension', difficulty: 'medium', question: `${educationPassage}\n\nAccording to the passage, policy focus has increasingly shifted toward:`, options: ['Measuring enrollment and infrastructure alone', 'Privatizing all primary schools', 'Reducing the number of years of compulsory schooling', 'Directly assessing foundational literacy and numeracy'], correctIndex: 3, explanation: 'The passage notes a shift in policy focus from enrollment/infrastructure metrics toward directly assessing foundational literacy and numeracy.', source },
  { id: 'upsc-cse-p2-comp-012', section: 'Comprehension', topic: 'Reading Comprehension', difficulty: 'hard', question: `${educationPassage}\n\nWhich of the following can most reasonably be inferred from the passage?`, options: ['All children who enroll in school eventually become literate', 'Completing several years of schooling does not guarantee basic literacy or numeracy', 'Learning outcomes are unrelated to school enrollment rates', 'Developing countries no longer face challenges in primary education'], correctIndex: 1, explanation: 'The passage explicitly states that a significant share of children completing several years of schooling remain unable to read simple text or do basic arithmetic — supporting this inference.', source },
  { id: 'upsc-cse-p2-comp-013', section: 'Comprehension', topic: 'Reading Comprehension', difficulty: 'medium', question: `${spacePassage}\n\nAccording to the passage, the falling cost of satellite launches is mainly attributed to:`, options: ['Increased government funding for space agencies', 'Reusable rocket technology', 'A decline in demand for satellite services', 'International treaties reducing launch fees'], correctIndex: 1, explanation: 'The passage attributes the declining cost of satellite launches substantially to reusable rocket technology.', source },
  { id: 'upsc-cse-p2-comp-014', section: 'Comprehension', topic: 'Reading Comprehension', difficulty: 'medium', question: `${spacePassage}\n\nAccording to the passage, wider access to space has raised new concerns about:`, options: ['Orbital congestion and long-term sustainability of the space environment', 'A global shortage of satellite engineers', 'Declining scientific interest in space exploration', 'The high price of internet connectivity'], correctIndex: 0, explanation: 'The passage notes that democratized access to space has raised concerns about orbital congestion and the long-term sustainability of the space environment.', source },
  { id: 'upsc-cse-p2-comp-015', section: 'Comprehension', topic: 'Reading Comprehension', difficulty: 'medium', question: `${spacePassage}\n\nWhich applications does the passage mention as now supported by small satellite constellations?`, options: ['Global internet connectivity, agricultural monitoring, and disaster response', 'Deep-space exploration only', 'Weather forecasting exclusively', 'Military reconnaissance only'], correctIndex: 0, explanation: 'The passage mentions global internet connectivity, agricultural monitoring, and disaster response as applications now supported by small satellite constellations.', source },
  { id: 'upsc-cse-p2-comp-016', section: 'Comprehension', topic: 'Reading Comprehension', difficulty: 'medium', question: `${waterPassage}\n\nAccording to the passage, why does a large share of agricultural water fail to reach crops?`, options: ['Excessive rainfall washes it away', 'Inefficient irrigation practices cause water loss', 'Crops are grown only in water-scarce regions', 'Farmers deliberately divert water to other uses'], correctIndex: 1, explanation: 'The passage states that a substantial portion of water is lost to inefficient irrigation practices before reaching crops.', source },
  { id: 'upsc-cse-p2-comp-017', section: 'Comprehension', topic: 'Reading Comprehension', difficulty: 'medium', question: `${waterPassage}\n\nAccording to the passage, what limits the adoption of precision irrigation methods among smallholder farmers?`, options: ['A lack of scientific awareness only', 'A lack of capital for upfront investment', 'Government bans on drip irrigation', 'Poor soil quality in most regions'], correctIndex: 1, explanation: 'The passage identifies a lack of capital for upfront investment as a key barrier limiting smallholder adoption of precision irrigation.', source },
  { id: 'upsc-cse-p2-comp-018', section: 'Comprehension', topic: 'Reading Comprehension', difficulty: 'hard', question: `${waterPassage}\n\nAccording to the passage, scaling up water-efficient agriculture requires:`, options: ['Banning traditional irrigation methods outright', 'Affordable financing alongside targeted extension services', 'Reducing the total area under cultivation', 'Relying solely on rainfall rather than irrigation'], correctIndex: 1, explanation: 'The passage states that expanding access to affordable financing, alongside targeted extension services, is seen as essential to scaling up water-efficient agriculture.', source },
];
