import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'Civil Services Examination, 2026 official notification (Examination Notice No. 05/2026-CSE) — Preliminary Examination, General Studies Paper I syllabus: History of India and Indian National Movement',
  url: 'https://www.upsc.gov.in/sites/default/files/Notif-CSP-2026-Engl-060226Rev.pdf',
  checkedOn: '5 August 2026',
};

export const UPSC_CSE_PAPER_1_HISTORY_1: Question[] = [
  { id: 'upsc-cse-p1-hist-001', section: 'History of India and Indian National Movement', topic: 'Ancient History', difficulty: 'easy', question: 'Which ancient Indian city is famous for the archaeological remains of the "Great Bath," a structure associated with the Indus Valley Civilization?', options: ['Harappa', 'Mohenjo-daro', 'Lothal', 'Dholavira'], correctIndex: 1, explanation: 'The Great Bath, a large watertight brick structure believed to have been used for ritual bathing, was excavated at Mohenjo-daro.', source },
  { id: 'upsc-cse-p1-hist-002', section: 'History of India and Indian National Movement', topic: 'Ancient History', difficulty: 'easy', question: 'Which of the following is the oldest of the four Vedas?', options: ['Yajurveda', 'Samaveda', 'Rigveda', 'Atharvaveda'], correctIndex: 2, explanation: 'The Rigveda, a collection of hymns, is considered the oldest of the four Vedas.', source },
  { id: 'upsc-cse-p1-hist-003', section: 'History of India and Indian National Movement', topic: 'Ancient History', difficulty: 'medium', question: 'Gautama Buddha is said to have delivered his first sermon, the Dharmachakra Pravartana, at which of the following places?', options: ['Bodh Gaya', 'Sarnath', 'Kushinagar', 'Lumbini'], correctIndex: 1, explanation: 'Buddha delivered his first sermon at Sarnath, near Varanasi, after attaining enlightenment at Bodh Gaya.', source },
  { id: 'upsc-cse-p1-hist-004', section: 'History of India and Indian National Movement', topic: 'Ancient History', difficulty: 'medium', question: "The Kalinga War, often cited as a turning point in Emperor Ashoka's approach to governance, is generally dated to around which year BCE?", options: ['321 BCE', '232 BCE', '185 BCE', '261 BCE'], correctIndex: 3, explanation: 'The Kalinga War is generally dated to around 261 BCE, after which Ashoka is said to have embraced Buddhist principles of non-violence.', source },
  { id: 'upsc-cse-p1-hist-005', section: 'History of India and Indian National Movement', topic: 'Ancient History', difficulty: 'hard', question: "The Chinese pilgrim Fa-Hien's visit to India, which provides valuable eyewitness detail on Gupta-era society, is most closely associated with the reign of which ruler?", options: ['Samudragupta', 'Chandragupta I', 'Chandragupta II', 'Kumaragupta'], correctIndex: 2, explanation: 'Fa-Hien visited India during the reign of Chandragupta II (Vikramaditya), roughly between 399 and 414 CE.', source },
  { id: 'upsc-cse-p1-hist-006', section: 'History of India and Indian National Movement', topic: 'Medieval History', difficulty: 'medium', question: "Akbar's syncretic religious order, which sought to blend elements of the faiths practised across his empire, was known as?", options: ['Din-i-Ilahi', 'Sulh-i-Kul', 'Ibadat Khana', 'Din-i-Sufi'], correctIndex: 0, explanation: 'Akbar founded the Din-i-Ilahi in 1582 as a syncretic order drawing on multiple religious traditions of his empire.', source },
  { id: 'upsc-cse-p1-hist-007', section: 'History of India and Indian National Movement', topic: 'Medieval History', difficulty: 'hard', question: 'The Third Battle of Panipat (1761), which ended in a major Maratha defeat, was fought against which power?', options: ['The Mughals', 'The British East India Company', "Ahmad Shah Abdali's Durrani forces", 'The Nizam of Hyderabad'], correctIndex: 2, explanation: "The Third Battle of Panipat in 1761 was fought between the Maratha Confederacy and Ahmad Shah Abdali's Durrani forces, ending in a heavy Maratha defeat.", source },
  { id: 'upsc-cse-p1-hist-008', section: 'History of India and Indian National Movement', topic: 'Modern History', difficulty: 'medium', question: "Whose act of defiance at Barrackpore in March 1857 is widely seen as an early spark preceding the wider revolt that broke out at Meerut two months later?", options: ['Mangal Pandey', 'Tantia Tope', 'Nana Saheb', 'Rani Lakshmibai'], correctIndex: 0, explanation: "Mangal Pandey's mutiny at Barrackpore in March 1857 is widely regarded as an early spark that preceded the wider revolt which broke out at Meerut in May 1857.", source },
  { id: 'upsc-cse-p1-hist-009', section: 'History of India and Indian National Movement', topic: 'Freedom Movement', difficulty: 'medium', question: 'The first session of the Indian National Congress, held in December 1885 and presided over by W. C. Bonnerjee, took place in which city?', options: ['Calcutta', 'Bombay', 'Madras', 'Allahabad'], correctIndex: 1, explanation: 'The first session of the Indian National Congress was held in Bombay in December 1885, presided over by W. C. Bonnerjee.', source },
  { id: 'upsc-cse-p1-hist-010', section: 'History of India and Indian National Movement', topic: 'Freedom Movement', difficulty: 'medium', question: "Lord Curzon's partition of Bengal, which triggered the Swadeshi Movement, was implemented in which year?", options: ['1899', '1911', '1909', '1905'], correctIndex: 3, explanation: "Lord Curzon's partition of Bengal took effect in 1905 and sparked widespread protest, giving rise to the Swadeshi Movement.", source },
  { id: 'upsc-cse-p1-hist-011', section: 'History of India and Indian National Movement', topic: 'Freedom Movement', difficulty: 'medium', question: "Mahatma Gandhi's first major Satyagraha movement within India, launched in 1917 to support indigo cultivators, took place in which region?", options: ['Kheda', 'Bardoli', 'Champaran', 'Ahmedabad'], correctIndex: 2, explanation: "Gandhi's first Satyagraha in India was the Champaran Satyagraha of 1917, launched in support of indigo cultivators in Bihar.", source },
  { id: 'upsc-cse-p1-hist-012', section: 'History of India and Indian National Movement', topic: 'Freedom Movement', difficulty: 'hard', question: 'Who was the Lieutenant Governor of Punjab at the time of the Jallianwala Bagh massacre in April 1919?', options: ['Michael O\'Dwyer', 'Reginald Dyer', 'Lord Chelmsford', 'James Bourdillon'], correctIndex: 0, explanation: 'Michael O\'Dwyer was the Lieutenant Governor of Punjab at the time of the Jallianwala Bagh massacre; General Reginald Dyer was the officer who ordered the firing.', source },
  { id: 'upsc-cse-p1-hist-013', section: 'History of India and Indian National Movement', topic: 'Freedom Movement', difficulty: 'medium', question: 'The Civil Disobedience Movement of 1930 was launched by Mahatma Gandhi with which act of defiance against the British salt tax?', options: ['The Champaran Satyagraha', 'The Dandi March', 'The Chauri Chaura incident', 'The Quit India resolution'], correctIndex: 1, explanation: 'Gandhi launched the Civil Disobedience Movement in 1930 with the Dandi March, a march to the coast to produce salt in defiance of the salt tax.', source },
  { id: 'upsc-cse-p1-hist-014', section: 'History of India and Indian National Movement', topic: 'Freedom Movement', difficulty: 'hard', question: "Which of the following was a genuinely new feature introduced by the Government of India Act of 1935, distinguishing it from the earlier Act of 1919?", options: ['Separate electorates for Muslims', 'A bicameral central legislature', 'Dyarchy at the provincial level', 'Provincial autonomy'], correctIndex: 3, explanation: 'The Government of India Act of 1935 introduced provincial autonomy, replacing the dyarchy at the provincial level that the 1919 Act had established.', source },
  { id: 'upsc-cse-p1-hist-015', section: 'History of India and Indian National Movement', topic: 'Freedom Movement', difficulty: 'hard', question: 'The Cripps Mission, sent by the British government in 1942 to negotiate Indian political cooperation during the Second World War, was headed by which British statesman?', options: ['Stafford Cripps', 'Lord Wavell', 'Lord Pethick-Lawrence', 'Lord Linlithgow'], correctIndex: 0, explanation: 'The Cripps Mission of 1942 was headed by Stafford Cripps, a senior member of the British War Cabinet.', source },
];
