import type { Question } from '../questions';

const source = {
  kind: 'original' as const,
  reference: 'Civil Services Examination, 2026 official notification (Examination Notice No. 05/2026-CSE) — Preliminary Examination, General Studies Paper I syllabus: Current events of national and international importance',
  url: 'https://www.upsc.gov.in/sites/default/files/Notif-CSP-2026-Engl-060226Rev.pdf',
  checkedOn: '5 August 2026',
};

export const UPSC_CSE_PAPER_1_CURRENT_AFFAIRS_1: Question[] = [
  { id: 'upsc-cse-p1-ca-001', section: 'Current events of national and international importance', topic: 'International Organizations', difficulty: 'easy', question: 'The headquarters of the World Health Organization (WHO) is located in which city?', options: ['Geneva', 'New York', 'Vienna', 'Paris'], correctIndex: 0, explanation: 'The World Health Organization is headquartered in Geneva, Switzerland.', source },
  { id: 'upsc-cse-p1-ca-002', section: 'Current events of national and international importance', topic: 'India and the World', difficulty: 'medium', question: 'The International Day of Yoga, proposed by India and adopted by the United Nations, is observed on which date each year?', options: ['21 June', '5 June', '15 August', '2 October'], correctIndex: 0, explanation: 'The International Day of Yoga is observed on 21 June every year, following a UN resolution adopted in 2014 after being proposed by India.', source },
  { id: 'upsc-cse-p1-ca-003', section: 'Current events of national and international importance', topic: 'India and the World', difficulty: 'medium', question: "India's presidency of the G20 grouping ran for which period?", options: ['December 2022 to November 2023', 'December 2021 to November 2022', 'January 2023 to December 2023', 'December 2023 to November 2024'], correctIndex: 0, explanation: "India held the G20 presidency from December 2022 to November 2023, culminating in the New Delhi Summit in September 2023.", source },
  { id: 'upsc-cse-p1-ca-004', section: 'Current events of national and international importance', topic: 'India and the World', difficulty: 'hard', question: 'The African Union was admitted as a permanent member of the G20 grouping at the New Delhi Summit in September 2023, during which country\'s presidency?', options: ['India', 'Indonesia', 'Brazil', 'Italy'], correctIndex: 0, explanation: 'The African Union was admitted as a permanent member of the G20 at the New Delhi Summit in September 2023, during India\'s G20 presidency.', source },
  { id: 'upsc-cse-p1-ca-005', section: 'Current events of national and international importance', topic: 'Sports', difficulty: 'medium', question: 'The final of the 2023 ICC Cricket World Cup, hosted in India, was won by which team?', options: ['India', 'South Africa', 'New Zealand', 'Australia'], correctIndex: 3, explanation: 'Australia won the 2023 ICC Cricket World Cup final, defeating India at the Narendra Modi Stadium, Ahmedabad.', source },
  { id: 'upsc-cse-p1-ca-006', section: 'Current events of national and international importance', topic: 'Static GK', difficulty: 'medium', question: 'The Bharat Ratna, India\'s highest civilian award, is formally conferred by whom?', options: ['The Prime Minister', 'The Chief Justice of India', 'The Speaker of the Lok Sabha', 'The President of India'], correctIndex: 3, explanation: 'The Bharat Ratna is formally conferred by the President of India, generally on the recommendation of the Prime Minister.', source },
  { id: 'upsc-cse-p1-ca-007', section: 'Current events of national and international importance', topic: 'International Organizations', difficulty: 'medium', question: 'The International Court of Justice, the principal judicial organ of the United Nations, has its seat in which city?', options: ['Geneva', 'Vienna', 'The Hague', 'Brussels'], correctIndex: 2, explanation: 'The International Court of Justice has its seat at the Peace Palace in The Hague, Netherlands.', source },
  { id: 'upsc-cse-p1-ca-008', section: 'Current events of national and international importance', topic: 'India and the World', difficulty: 'hard', question: "India's G20 presidency in 2023 was conducted under which Sanskrit-derived theme, meaning \"One Earth, One Family, One Future\"?", options: ['Ekam Sat Vipra Bahudha Vadanti', 'Satyameva Jayate', 'Sarve Bhavantu Sukhinah', 'Vasudhaiva Kutumbakam'], correctIndex: 3, explanation: "India's G20 presidency in 2023 adopted the theme \"Vasudhaiva Kutumbakam — One Earth, One Family, One Future.\"", source },
  { id: 'upsc-cse-p1-ca-009', section: 'Current events of national and international importance', topic: 'International Organizations', difficulty: 'medium', question: 'The World Economic Forum holds its best-known Annual Meeting each year in which Swiss town?', options: ['Zurich', 'Geneva', 'Davos', 'Bern'], correctIndex: 2, explanation: "The World Economic Forum's Annual Meeting is held each January in Davos, Switzerland.", source },
  { id: 'upsc-cse-p1-ca-010', section: 'Current events of national and international importance', topic: 'International Organizations', difficulty: 'medium', question: 'The United Nations currently has how many member states?', options: ['189', '191', '193', '195'], correctIndex: 2, explanation: 'The United Nations has had 193 member states since South Sudan joined the organisation in 2011.', source },
  { id: 'upsc-cse-p1-ca-011', section: 'Current events of national and international importance', topic: 'India and the World', difficulty: 'medium', question: 'Before its 2024 expansion, the BRICS grouping (Brazil, Russia, India, China, and South Africa) had how many member countries?', options: ['Four', 'Five', 'Six', 'Seven'], correctIndex: 1, explanation: 'Before its 2024 expansion, BRICS consisted of five members: Brazil, Russia, India, China, and South Africa.', source },
  { id: 'upsc-cse-p1-ca-012', section: 'Current events of national and international importance', topic: 'International Organizations', difficulty: 'hard', question: 'Unlike the other Nobel Prizes, which are awarded by institutions in Sweden, the Nobel Peace Prize is awarded by which body?', options: ['The Swedish Academy', 'The Norwegian Nobel Committee', 'The Royal Swedish Academy of Sciences', 'The Karolinska Institute'], correctIndex: 1, explanation: 'Unlike the other Nobel Prizes, the Nobel Peace Prize is awarded by the Norwegian Nobel Committee, based in Oslo.', source },
  { id: 'upsc-cse-p1-ca-013', section: 'Current events of national and international importance', topic: 'India and the World', difficulty: 'hard', question: 'India held the chairmanship of the Shanghai Cooperation Organisation (SCO) for 2022–23 and hosted its summit in July 2023 in which format?', options: ['An in-person summit in New Delhi', 'A virtual summit', 'A summit held jointly with China', 'The summit was postponed to 2024'], correctIndex: 1, explanation: "India hosted the SCO Summit in July 2023 in a virtual format during its 2022–23 chairmanship of the organisation.", source },
  { id: 'upsc-cse-p1-ca-014', section: 'Current events of national and international importance', topic: 'Sports', difficulty: 'easy', question: 'The 2024 Summer Olympic Games were hosted by which city?', options: ['Tokyo', 'Paris', 'Los Angeles', 'London'], correctIndex: 1, explanation: 'Paris hosted the 2024 Summer Olympic Games.', source },
  { id: 'upsc-cse-p1-ca-015', section: 'Current events of national and international importance', topic: 'India and the World', difficulty: 'medium', question: "Consider the following statements:\n1. India's G20 presidency began in December 2022.\n2. The New Delhi Summit of September 2023 was held during India's G20 presidency.\nWhich of the statements given above is/are correct?", options: ['1 only', '2 only', 'Both 1 and 2', 'Neither 1 nor 2'], correctIndex: 2, explanation: "India's G20 presidency began in December 2022, and the New Delhi Summit of September 2023 was indeed held during this presidency. Both statements are correct.", source },
];
